### ISSUE TITLE
Sync to Sia network

### ISSUE THREAD

**Issue by ghost** [kopia/kopia#1]
Have you heard about Sia? http://sia.tech - Basically you can rent disk space on other user's computers. With 6-times redundancy.

API docs are here: https://github.com/NebulousLabs/Sia/tree/master/doc

**Comment by jkowalski** [comment]
The OP user account has been deleted. And this gets pinged everytime # 1 is used in comments. Closing. If there's interest, let's open new issue, but I hope we can support this and other providers via `rclone` instead of developing our own.
