### ISSUE TITLE
[Bug] [Kopia-UI] Policies not detected

### ISSUE THREAD

**Issue by stpr-dev** [kopia/kopia#1001]
Setup:
Arch Linux
Kopia 0.8.2 UI (AppImage from release).
Kopia-bin 0.8.2 (AUR)

I setup policies for a few directories on the UI, and I noticed that no matter what, the local policies never get detected. In order to ensure that it wasn't my configuration, I used the same policy and repository on the CLI and it works as expected. 

For instance, on my ~, I set the following policies:

```terminal

kopia policy set --add-ignore .cache .
kopia policy set --add-ignore .cargo .
kopia policy set --add-ignore .steam .
kopia policy set --add-ignore .local/share/baloo .
kopia policy set --add-ignore .local/share/Steam .

```

Running `kopia snapshot estimate .` results in:
```terminal
...
<removed>
...

Snapshots excludes 5 directories. Examples:
- ./.cache
- ./.cargo
- ./.steam
- ./.local/share/Steam
- ./.local/share/baloo
```
So this works as expected. Now connecting the same repo using Kopia-UI (AppImage) and using the estimate option, I get:
```terminal

20:16:13.983 | found 0 policies for @
20:16:13.991 | excluded dir ./.cache/fontconfig
20:16:14.006 | excluded dir ./.cache/kopia/9492d4031dab361c

```
It appears that no matter what, the policies are not detected. I also noticed that it says `found 0 policies for @`. Perhaps there is a bug parsing the path?

**Comment by jkowalski** [comment]
How are you connecting to the repository using Kopia-UI? is it using the repository server or directly?

**Comment by jkowalski** [comment]
btw, I think I can reproduce this locally, I'll to fix it tonight when I have a bit more time.

**Comment by stpr-dev** [comment]
@jkowalski Woops, should have mentioned it is a direct connection (local filesystem repo).
