### ISSUE TITLE
Check for path validity prior to assigning policies.

### ISSUE THREAD

**Issue by stpr-dev** [kopia/kopia#1004]
Setup:
Arch Linux
Kopia 0.8.2 UI (AppImage from release).
Kopia-bin 0.8.2 (AUR)
Local filesystem repo

Description:
Currently, it appears that policies can be configured for any path regardless of whether or not the path points to a valid file/directory. Unless a snapshot is made from the 'Snapshots' tab, it is not possible to know if the policy is valid. Additionally, it may lead to unintended behaviour where the user may make a minor mistake in typing the path, and would not know until they looked carefully, this is particularly easy to miss for deeply nested directories (e.g. `/home/foo/bar/some/nested/directory/` vs `/home/foo/bar/some/nested/directroy/`).

Paths should be checked when specifying the policies to ensure that it points to a valid file/directory. I understand that paths may change in the future, but if a file/directory gets deleted after the policy is configured, it will be caught by `snapshot()` anyway.

**Comment by stpr-dev** [comment]
BTW this is true for both the UI and the CLI, both don't check for the path validity when setting policies.

**Comment by julio-lopez** [comment]
it seems that a user should be able to specify a policy for path that does not exist yet. That is, the user may want to set policies for a path that would show up later.

**Comment by stpr-dev** [comment]
Hmm, fair point, I didn't consider that perspective. Would a warning/message be acceptable? When a policy is specified, along with the message being printed, something like 'The specified path does not **currently** point to an existing directory or file' to say that it does not currently exist, but it does not block the policy creation. This way, it is not throwing an error (or refusing to proceed), but at least it could caution some users to ensure that their paths are what they intend to be.

**Comment by jkowalski** [comment]
There's currently no good way to communicate warnings in the UI, we'll need to seriously re-think how the API underneath communicates status including warnings, so this won't be a quick-and-easy fix. Suggestions (or even better PRs) are welcome.
