### ISSUE TITLE
KopiaUI seems to have issues with web based help 'breaking' the UI 

### ISSUE THREAD

**Issue by jaxjexjox** [kopia/kopia#1011]
I've just installed this, I really like what I see thus far.

I've now twice, 'broken' the application, by clicking something which navigates away from the traditional UI to some kind of web page providing information.

This time, I was on the policy page, attempting to learn, how to configure a folder exclusion for testing.
It clearly says
Controls which files should be included and excluded when snapshotting. Use .**_gitignore_** syntax.

If I click on the gitignore (blue) section, of that tooltip (so to speak) the application doesn't pop a new window, it changes literally to a web page, in the same window. (!!?)
I can't use ALT back arrow (go back)  
Nor can I use escape.
There's no right click, context menu for the 'web page (user interface)
and finally and biggest issue, if I close the application and re-load it, it's done - that's it, I won't see the UI again.
**I literally need to end task the application, delete all data folders and re-install it.**

I suggest either a pop out box for html help - re-directing the application to callign the default browser and not browsing, within the application itself or providing buttons with a clear "RETURN TO KOPIA UI" or some such thign.

It's a small bug but for lower level users, it's pretty killer.
Sorry, only tested on one x Windows 10 system

**Comment by jaxjexjox** [comment]
Also assuming I have your ear(s) it'd be lovely if the folder exclusion would be a little easier, so I can just add root folder X and then in a new window, simply hold down control and click on the 16 folders I don't want to backup, within X

**Comment by vic-t** [comment]
I just wanted to give Kopia a first go, on Windows 10, and ran into the exact same issue. Wanted to consult the .gitignore syntax and can't go back to my backup set. 

I also agree that folder exclusion could be done a bit simpler. Though I'd already be happy with clearer instructions. 

@jaxjexjox I'm not sure, though, what you mean by "when I close and re-load, it's done, won't see UI again". In my particular case, Kopia was actually still running, I just had to get it back from the system tray in the task bar.

**Comment by jaxjexjox** [comment]
My copy is not in the system tray, or the task bar, infact, upon rebooting the PC, I literally can't open the app, ever again.

I'm going to see, if I'm entirely wrong, it's possible and see if it's in the tray, I am fairly sure I checked, but I'll break it now and confirm.

This software is particularly good and I'd like to see it gain traction and improve. I noticed no 'donate' or patreon, listed on the page here or the real primary page.
I'm a little,....... disapointed in the wide variety of free, or close to free backup products, with B2 support.  I kind of wish they'd all just consolidate into one or two options, even if it was a $20 a year or $50 one off fee.     They all seem to hit 2/3 of the mark and miss the last third 
(to note, with this one, being the closest to the mark, by far)

**Comment by jkowalski** [comment]
Thanks for the kind words, I'm going to fix this and since we're going to be making an 0.8.4 release soon, i'll try to include this in it.

**Comment by jkowalski** [comment]
Regarding having an easier option for excluding folders - I hear you and I agree this is too hard currently. I'm thinking of completely redoing the UI for the 0.9.0 release where instead of Snapshots and Policies tabs there will be a single filesystem tree (actually more, to include other users and other hosts) where you can take snapshots, define policies (include/exclude), estimate and restore - all from one tree view.
