### ISSUE TITLE
Feature request: Backup to specific folder in B2 bucket

### ISSUE THREAD

**Issue by vic-t** [kopia/kopia#1012]
When connecting to BackBlaze B2 as a repository, Kopia allows me to specify the bucket where all files should be stored (using the --bucket parameter) but it does not seem possible so specify a folder in the bucket. 

It would be nice if you could add this functionality.

**Comment by jkowalski** [comment]
There's a `prefix`option, does it not work as expected?

**Comment by vic-t** [comment]
That wasn't my expectation so I didn't try that. So prefix is just another word for folder? If yes, I guess the documentation should be updated in that respect. 🙂 

Since we're on the topic, is there a reason you are masking the prefix entry in KopiaUI?

**Comment by julio-lopez** [comment]
_"prefix"_ is commonly used in the context of blob names in object stores.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-prefixes.html
https://www.backblaze.com/b2/docs/b2_list_file_names.html

**Comment by vic-t** [comment]
Thank you both, all is understood. Maybe there could be some sort of tooltip in the UI to explain that prefix == folder? Also, I'm not sure about masking the text entry field.

**Comment by rsnitsch** [comment]
Note: To save your kopia backup in a subfolder your prefix must end with a `/`. Otherwise kopia will simply create files in the top-level directory of your bucket and prefix _the individual files_ (i.e. spamming your main folder with countless files).
