### ISSUE TITLE
Docker not woking for kopia/kopia:0.8.3 arm/v7 

### ISSUE THREAD

**Issue by josvo** [kopia/kopia#1014]
Hello

The newest docker kopia version 0.8.3 does not work anymore on arm/v7.
0.8.2 returns:
```shell
docker run kopia/kopia:0.8.2 repository status
ERROR: open repository: repository is not connected. See https://kopia.io/docs/repositories/
```
a valid answer from kopia, whereas 0.8.3 has a problem with it's binary:
```shell
docker run kopia/kopia:0.8.3 repository status
standard_init_linux.go:219: exec user process caused: no such file or directory
```

I checked the two binaries in the docker images and here is the difference:
```
0.8.2: kopia: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=s-Zy0nXgRLGUlsUQ0xil/lNb09FsFiVC_ilOMcXPY/v7NQoRPwwR6SbxEcA7-H/ZrgKdqXJ8jLlyJ2mX77V, stripped
0.8.3: kopia: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, Go BuildID=r4INsu0cSChUeVFfjoCv/_2wDxqytm-FX1FIGXVkb/5G4yn5nNx6_kGW6Zq3b8/iucXgs2nIoABCgQ8YS9p, stripped
```
Seems like 0.8.3 is dynamically linked. Not sure if this is intended. 
Thanks!

**Comment by jkowalski** [comment]
I can repro this, but I have absolutely no idea how this could have happened.

If I download `kopia_binaries` artifact fro the v0.8.3 build, I get:

```
$ sha256sum Downloads/kopia_binaries-5/kopia_linux_arm_6/kopia
f973216e9f8647b8f260fd64530ce43556afec6f1514f8badadc5291c438693a  Downloads/kopia_binaries-5/kopia_linux_arm_6/kopia
```

That's the same binary as in Docker:

```
$ sha256sum app/kopia
f973216e9f8647b8f260fd64530ce43556afec6f1514f8badadc5291c438693a  app/kopia

$ ldd app/kopia
	linux-vdso.so.1 (0xbef51000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6f21000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6e23000)
	/lib/ld-linux-armhf.so.3 (0xb6f47000)
```

To make it even more mysterious, the nightly builds after that are fine:

```
$ docker run kopia/kopia:unstable
```

**Comment by jkowalski** [comment]
Also, ARM64 build is fine.

**Comment by jkowalski** [comment]
Even more mysterious - the APT repository and tar.gz have:

```
ab511ef91f1de8b2a13678f887306418028f0c60b85d4eb96ca27939a053c3a5  /usr/bin/kopia
```

So the build somehow produced two `kopia` binaries - one statically linked (with hash ab511ef91f1de8b2a13678f887306418028f0c60b85d4eb96ca27939a053c3a5) and one dynamically linked (f973216e9f8647b8f260fd64530ce43556afec6f1514f8badadc5291c438693a) that was saved in artifacts and sent to docker.

I don't see how this is possible, but definitely worth getting to the bottom of this.

**Comment by jkowalski** [comment]
For AMD64:

APT repo binary:
0376aa131f58baf81f2c7a73b4c449271e9d16f737d93c00953b6c0d7a896b9b  /usr/bin/kopia

Docker binary:

**Comment by jkowalski** [comment]
When you open the UI, the APT version has this in the footer:

```
Version v0.8.3 built on Thu Apr 22 13:46:45 UTC 2021 fv-az127-326
```

Docker version shows:

```
Version v0.8.3 built on Thu Apr 22 13:48:22 UTC 2021 kopia-runner-armhf-546fb5cc99-jjjv7
```

**Comment by jkowalski** [comment]
So the binary that went to Docker (dynamic) was produced by ARMHF self-hosted runner and the binary that went to APT (static) was created by `ubuntu-latest`.

I think we may have a race condition in the build process...

**Comment by jkowalski** [comment]
@julio-lopez this is fascinating, for a moment I was suspecting a security breach... let's keep digging here.

**Comment by jkowalski** [comment]
The fix is to not upload any artifacts from self-hosted builders.

**Comment by julio-lopez** [comment]
good digging

**Comment by josvo** [comment]
Wow - that was quick! Thanks a lot for the fix!
