### ISSUE TITLE
Synology

### ISSUE THREAD

**Issue by cirrusflyer** [kopia/kopia#1017]
Any thoughts on creating a Kopia app package to use on a Synology NAS?  And has anyone used the docker version to backup Synology folders to a cloud backup like S3 or Backblaze?  I'm a little unsure how you select what to backup and how to manage the backups and schedule, settings, etc.

**Comment by cirrusflyer** [comment]
FYI - Duplicacy has created a DSM v7.x package for that software.

**Comment by mhansen** [comment]
I was wondering too. Here's some breadcrumbs to help figure out how to do it...

Here's an old blogpost explaining how it used to be done: https://amigotechnotes.wordpress.com/2014/05/17/how-to-create-a-spk-for-synology-dsm-to-distribute-your-lamp/

Here's the new developer guide: https://help.synology.com/developer-guide/synology_package/introduction.html

You create a few JSON files to configure, a few PNG files for the menu, and a few shell scripts for install/uninstall/start/stop.
