### ISSUE TITLE
Feature Request: Native Integration with Microsoft OneDrive

### ISSUE THREAD

**Issue by xxxliqu1dxxx** [kopia/kopia#1027]
What a great software so far! Please keep up the great work and the frequency of updates, it's amazing to see!

I've been playing with Kopia for the past couple of releases and I have to say I like the UI & the capabilities of the software, the speed at which it performs its work, the ability to mount the storage to restore individual files if applicable, etc. Having played with Duplicati & Duplicacy, I believe Kopia has the potential to be better on all fronts. 

However, what these two have that Kopia does not have, seems to be a native integration with OneDrive. I know I can use Rclone as the front end for OneDrive, but I would prefer not relying on that.

Also, I am aware I can map via FileSystem to a Windows system that has the Native OneDrive software running, which means the chunks would be uploaded directly by the Windows OneDrive App, but again, would prefer not having to rely on that and connect directly to OneDrive from Kopia.

Would it be possible to explore the opportunity for a Native Integration to OneDrive?

Thanks again for doing what you are doing and make this great software even better!

**Comment by jkowalski** [comment]
What I think we could explore doing is linking to rclone instead of running it as a subprocess. There are major downsides to doing that, in terms of keeping track of dependencies, security, etc. 

@julio-lopez thoughts?

**Comment by julio-lopez** [comment]
Does it make a big difference? What would be the benefit and tradeoffs of linking vs. separate process?

**Comment by ZoomRmc** [comment]
Will linking rclone mean that a user needs to keep a separate configuration?

In regards to original issue I wanted to add a contrary opinion: as long as something could be done by rclone, let it. Much better to focus developing and maintaining efforts on stages of the process which can't be performed by a third party software (overall performance and stability, filewalk soundness, repo maintenance, encryption and compression, etc).

**Comment by bbccdd** [comment]
Well there are arguments against integrating two wonderful tools indeed. Mostly based on the principles of doing one thing and doing that well (for inspiration: https://en.wikipedia.org/wiki/Unix_philosophy#Eric_Raymond's_17_Unix_Rules).

rclone is hugely popular, heavily used and actively developed (422 contributors, 27.000 stars on github, a permissable license) and just last month "Excluding merges, 23 authors have pushed 108 commits to master and 159 commits to all branches. On master, 122 files have changed and there have been 3,565 additions and 675 deletions." Also check it's usage in high performance computing as per https://en.wikipedia.org/wiki/Rclone.

rclone is an excellent piece of kit on itself. When integrating into kopia, a part of the most time consuming activities will rest on kopia in terms of maintaining the touchpoints (indeed, such as a configuration file / tool) and this needs to be maintained per stable version).

Where now, as long as modification times (or [ModTime in the rclone overview table](https://rclone.org/overview/)) are supported by the remote destination, kopia works well with rclone. Perhaps this could be clarified 

@xxxliqu1dxxx I challenge you to run 'rclone config', configure [ondrive ](https://rclone.org/onedrive/)as a source and sync.

The rclone onedrive instructions talke about creating a specific application to prevent e.g. bandwidth limitations. There is no known need to do so in my understanding. Simply increase the amount of parallel connections like so:
rclone sync --transfers 10 </path/to/kopiarepo> <name of remote rclone destination>:/<folder within> --bwlimit=100M --progress

I've done this last night with 300 Mbit/s on a personal account. Perfect.

And test by [connecting to it using kopia (as I've just found out):](https://kopia.discourse.group/t/how-to-rhyme-rclone-with-repository-server-restores/420)
kopia repository connect rclone --remote-path <remotedestname>:/<remote folder>

**Comment by xxxliqu1dxxx** [comment]
hi bbccdd, thanks for the information. I have been playing with it and I believe the transfer speed to be more around 200mbit for me, unlike the 300mbps you are getting but I am not getting anywhere close to the 1000gbit up/down that I have. Jarek suggested I look at other storage providers which may be able to better suit me than OD. OD is "free" when you have Office 365 so I was thinking of leveraging that, but I realize now it may not be the best case for me. It may be better suited for "Archival" purposes, vs an actual backup repo with lots of clients connected straight to it. 

I've also read threads of people being throttled, so not sure if that's what happening to me at 200mbps, but oh well. I will continue playing as my repo died on me when I did a migrate -all... not sure what exactly happened, but I had a bad experience trying to migrate from on prem to cloud. I will have to re-visit this strategy as well.

Thanks!

**Comment by bbccdd** [comment]
Hi @xxxliqu1dxxx 

On onedrive
Indeed, MS OneDrive did not get the best performance in terms of bandwidth. Also their 'randsomware' protection keeps interfering stating suspicious behaviour, perhaps leading to throttling since I now do not reach 200mbit by far. I created an [application specific keypair as described in the rclone documentation](https://rclone.org/onedrive/#getting-your-own-client-id-and-key) but lost connection after a day. I did not file a bug report or support request I must say though. I'm using onedrive as an rclone destination. 

On backblaze
In terms of performance, from the Netherlands backblaze b2 in their EU-datacenter is blazingly fast. It fills my gigabit uplink completely and consistently. Mind the --fast-list option in rclone though to prevent an expensive amount of class C-transactions.

So I use kopia reposerver for clients to push their data to/from and sync that whole repo to onedrive nightly using rclone. I find that easier to maintain / keep track of / test reliability of / report on usage for than when using either onedrive or backblaze as destinations directly from clients. Since onedrive indeed does not induce extra charges using onedrive as an extra rclone sync destination, the costs are marginal. I just let it run alongside B2.

Hope you did not lose valuable data in your migration btw!

**Comment by ZoomRmc** [comment]
>  Have you ever tried to explain rclone usage to your mother or grandfather? For me, one of the major benefits of kopia is its simplicity. 

I don't know if you're serious. Kopia is absolutely not simple and I wouldn't expect a common modern user to set it up unsupervised. People you're alluding to don't know what a "file" is.

Rclone, on the other hand, holds your hand  through setting up a remote with a wizard-like experience. You just answer a few yes/no questions, enter login and authorize, and you're ready to go. In other words, if you can understand how to get Kopia to working condition, you can set up rclone. If you can't complete setting up a remote in rclone, you probably can't set up a Kopia repository also.

For a commercial product your logic is correct, but for a Free Software with limited resources, reimplementing and than maintaining an extensive feature-set is a heavy cost. It's better to try to improving rclone and the way it's integrated into Kopia to make it all more user-friendly.

Another argument is that providing the support for a proprietary service by default can be considering an encouragement to use it, and I don't believe it's a desired effect.
