### ISSUE TITLE
Kopia-UI disappears to background after second start

### ISSUE THREAD

**Issue by josvo** [kopia/kopia#1031]
Hello,

Kopia-UI always disappears to background on second start. 
When setting up the repository on first start, everything works fine. However, after closing the window and starting again (also after shutting down the process and starting again) the UI goes straight to background, or is at least no more visible.
The only fix I found so far is to kill all the kopia processes and remove the `repository.config` file. 
Then, on the next start, I can freshly connect to the existing repository via UI. 
The only error I can see when starting kopia-ui via CLI is
```shell
22:56:25.273 › errorTypeError: app.isInApplicationsFolder is not a function
22:56:25.278 › APPIMAGE env is not defined, current application is not an AppImage
```
However, this appears also on first start.
Is there something I can do to debug this?

Kopia: 0.8.4
Repository: tested with filesystem and kopia server
OS: Fedora 33/34 (tested both) on 64 bit

**Comment by josvo** [comment]
When starting for the first time, the logs show:
```shell
...
[2021-05-01 20:16:02.311] [info]  SERVER CERT SHA256: 5f94998aa89206efdf966d96372200fd320e200aaae7b162c0ee42012cfd19aa
SERVER CERTIFICATE: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU5VENDQXQyZ0F3SUJBZ0lRWWFLbUlPMmJ0eDJEQ2RiWjExRFMxakFOQmdrcWhraUc5dzBCQVFzRkFEQVEKTVE0d0RBWURWUVFLRXdWTGIzQnBZVEFlRncweU1UQTFNREV4T0RFMk1ESmFGdzB6TVRBME1qa3hPREUyTURKYQpNQkF4RGpBTUJnTlZCQW9UQlV0dmNHbGhNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDCkFnRUF1cGdRam1yZnZFK0hpVXU1WVljVHYxTXRYd0RIWmo0VzVmR1U0clJtdXlJVzBGTW9PTXhJMjk1cmp6VFIKejVydzhWTG9JcjIrMk1XeU5ycFJ4dHJaYTFxUElianZLMy9rS3RUdFJ1NVE4L2pDMnkzZ3U0Tm1Vak1DbkpYNQpOVytHanVWcWxqb0pQcEdkNGkwTThvUkFFZnNmbnJOKzNYL3p5Vndoeno2ZU1hQUlzY1B1VFB0Sk9YZitzWWd6CjVlV1o5MXRFZ3NRd2o0U3gxMXVORzJzU0xpMk14bDZLVVRycE41SnJjQ2M1TVlDZ000bjBrbVhOZ1E5V1RlOFQKUy8zZUdFcWlWYk9mMFd5VHpUSGR2cmx6SzFIU3RsMnZkbXBvMjVSdXhGeFVLU3dPRHlZa0Z2SUErOHVtMC9sWgpsYjY2RCttUUtwcFV3M0t2dlhiUkFaNDFYaVZ4R2xnSjY5SC93a3c3NFdMSnd5QXlpQnJsUjhGK0RVWjVIWjJSCnZVQmcvdHYyWm9LWHlrTmk0OGdvS1daVUxxTTZrT1N4ZXNuWkY1LzNVaEZDZk91aW9uTVgwaWpXa0Y1WVh4WEkKUy92R0FuUWxBckx3ZHkwY2tUZDdDYVZ1d2t4V0JNK2QyeW5WWGxQam5FWXNmWTMwMGZYN0NRclRJMVRNeGZSRApYakI4SnQrRmVQK0E4Sk1NUlVuUHB2RWQ3RDJIZmVoUkZTQmJjWmhKTVkzQ1J4WlhqaUtVL0IrWXpJMGVqd2w3CkF0SXFGZkdJTzVreEVxS0g0a3BiUzlWYmw3VE9Yelp5eStDa1N0bSs1VnRRS0tybmNUTkxmZEp3aVFLbUpXb2MKMnhrOHpjNFE2Vk5zV2pBOXpmV05DeDZvSmN3Q2pFdzhSTjB3WjRjMVlTV0NaTjBDQXdFQUFhTkxNRWt3RGdZRApWUjBQQVFIL0JBUURBZ0trTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3CkZBWURWUjBSQkEwd0M0SUpiRzlqWVd4b2IzTjBNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUJoNHByTUJEVmYKRG9vOGJ6VjRlcnlrTStTdm83MmFxOVdoQzRqS1JpRHBtMTl6K0NabTNWYnFxZ3RnUXliVklGNTlkMVdtcjE2UApVT1BOdnUzeUhuRFRuaVI1eC9hRVpCNWdIZ2ZIenE4OGowWWlwc2RzUG5DcWk4NnhFaWxMUFJQWS9lbmZBQ1BpCmdYMTZ2ZFNSYWVaamxIWVZiZlZHN1N3TURlQUg5K1o3cThRMWZBVmp6NWhqaTFKSCtEbnhvckUzSFZFQ1hxM2gKNzAwalhwNjlYSXBmM01sUDR2UkszcXQ1Zk5qblZ5b3FTRVgwemExNy94MFNZeTc1V1VDZm1qVDlpU3phWU9CUApBTmR2NFhUZnhla3crbkdlQWk2S2NaV1hIVFlnQkVQUGpyMGNtUWtlMUNKMHdiR0piYmQyb3AvRlVkdjZ6UUJiClBYUHhwRkRhVHZjN2JzTWt1U2I2T3JTZTUreEpGUmV1c095TzdhYVNZM1lxUkN4dnR5MCtUVzR2RkRpWVlJTjUKSHc0TjMwcFFDZWJuREhQSWk1Nzh1Zk1oMWtFc2lWMG1DazlISDJwaTRqNXNKbGQvWER6dTBVaWxYZDhnbHNRUwptMnFhazFIZXliUjZ2eEZRNGFKa09kSWJ0Y3A1MXBjR0E5SG1rM2s3SDgvQ3dIN3ZVN0hQOW1GbmlSWnpaTkY5CnhLNUlHY0V4bzFVYVp2S0JkRlAwVzVTajFXSlRrMmY0aFJ0aGtwMSt6NjhrRXZoOGlNbU54L1VERzhjTnJpN1gKK0RMU05GWkUvSEZ6QXVLZHJYODRDbE5leFNoOTdiWVY1NWVVNy9UTGZ3OGRqd2tZbDlYQ2VTTE5CSG1JWkNaMwpuSjF6RFJiRkczMXMxWjFzcno4Sms3TWh3bldTelJsbjF3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
SERVER ADDRESS: https://127.0.0.1:40383
Open the address above in a web browser to use the UI.

[2021-05-01 20:16:02.590] [info]  reloading
[2021-05-01 20:16:02.746] [info]  2021/05/01 20:16:02 http: TLS handshake error from 127.0.0.1:55460: remote error: tls: unknown certificate

[2021-05-01 20:16:02.749] [debug] accepting server certificate.
[2021-05-01 20:16:02.837] [info]  automatically logging in...
[2021-05-01 20:16:02.840] [info]  serving patched index

[2021-05-01 20:16:03.423] [info]  serving patched index
```

**Comment by jkowalski** [comment]
Is there a tray icon at all? During first or subsequent runs?

**Comment by josvo** [comment]
Now I see the problem...
Fedora (GNOME) removed the system tray / status icons. So the kopia status icon is just not visible anymore. 
See here: https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/
In Fedora, you either have to install `gnome-shell-extension-topicons-plus` or https://extensions.gnome.org/extension/1503/tray-icons/ or something similar. 
After installing and enabling it, everything works as it should. 
This problem is solved. However, it might arise again when more Linux distributions go without tray icon extension pre-installed. Maybe in the future, there won't be any such extensions available.

**Comment by ThallesP** [comment]
I was having the same problem, some error or warning on Fedora would be good then just don't open anything and go silently.

**Comment by samjcarter** [comment]
I am having the same problem on Fedora Silverblue 36 (`36.20221106.0`), Gnome 42.4. KopiaUI runs once and then runs in the background, but the user can't open it a second time due to the absence of the system tray in recent versions of Gnome (thanks @ThallesP ).

The behaviour is the same with both the Flatpak `0.12.1` and the AppImage `0.12.1`.

I would rather not use extensions to 'enable' an app. Are there any intentions to allow KopiaUI to work without requiring the old Gnome system tray UI or an extension?
