### ISSUE TITLE
MacOS permission issues prevents launch of KopiaUI.app

### ISSUE THREAD

**Issue by BradyRosino** [kopia/kopia#1034]
- Downloaded the latest release of the mac UI KopiaUI-0.8.4-mac.zip
- Extracted, moved KopiaUI.app to Applications folder
- KopiaUI app fails to launch with a "You do not have permission to open the application 'KopiaUI'"
<img width="277" alt="Screen Shot 2021-04-30 at 8 56 20 AM" src="https://user-images.githubusercontent.com/11621297/116698442-633a0c00-a992-11eb-98d6-10cfcce13085.png">

I've tried setting new permissions:
`sudo chmod -R 755 KopiaUI.app`

I've also tried clearing any possible quarantine attributes on the package:
`sudo xattr -rd com.apple.quarantine KopiaUI.app`

Apple M1/Arm MacBook Air on macOS 11.2.3

**Comment by jkowalski** [comment]
I just tried downloading `0.8.4` on my MacMini with M1 and it worked without a problem.

It his a personal or laptop or is it under some corporate management where the admin could have defined some security policy?

**Comment by BradyRosino** [comment]
Launches no problem on my M1 Mac Mini. Still can't launch after updating to 11.3 on the Air. I've deleted & redownloaded a fresh copy from the GitHub releases page. Seems to be refusing to launch due to an invalid code signature

```
brady@Bradys-MacBook-Air ~ % pkgutil --check-signature /Applications/KopiaUI.app
Package "KopiaUI":
   Status: package is invalid (checksum did not verify)
```

I'm assuming this is something local on my machine messing with the app as its getting extracted somehow. No issues for you and no issues for my other machine. I'll keep digging and share any findings. 🤷‍♂️

**Comment by jkowalski** [comment]
However silly that sounds, try rebooting. It helped me before for those kinds of cases.  Apple seems to be caching some signatures in kernel.

**Comment by BradyRosino** [comment]
Definitely seems like something getting cached somewhere... unfortunately restarting didn't resolve.

Launching from terminal yields:
```
brady@Bradys-MacBook-Air /Applications % open KopiaUI.app
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2539, NSUnderlyingError=0x13170b6b0 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x13170cc20 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 111}}}}}
```

Still digging...

**Comment by BradyRosino** [comment]
Oddly enough if unzipping using Archive utility (double click zip file) then it unzips without error.

Unzipping from terminal gives this error:

```
brady@Bradys-MacBook-Air Downloads % unzip KopiaUI-0.8.4-mac.zip
Archive:  KopiaUI-0.8.4-mac.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of KopiaUI-0.8.4-mac.zip or
        KopiaUI-0.8.4-mac.zip.zip, and cannot find KopiaUI-0.8.4-mac.zip.ZIP, period.
```

I ended up downloading Keka (basically 7zip wrapper) and extracted the same zip file there and the extracted application works now.

Not sure what to make of any of this, but I'm up and running now on my MacBook Air as well. 🤷‍♂️

I'll close the issue, thanks for following along on this adventure.
