### ISSUE TITLE
Retention time vs. generations

### ISSUE THREAD

**Issue by Hoffenbar** [kopia/kopia#1048]
Although retention is a well known term for me (I've used dozens of backup programs over the past 35 years), I have problems to achieve what I want with kopia.
Sometimes I want to keep the backup, simplified spoken, "forever", while it was good to have the possibility to go back one or two versions, so one can recover the next to last version etc.
So I've naively configured '2' for 'latest', and '0' for every other option, but then after hours and hours of snapshotting, my 600 GB in about 100.000 JPGs are gone... Now I tried to fill in other values which probably make sense, but the snaphots are not came back yet :-) 
I almost never can say how long to keep something, but how many versions of something (sometimes only the last one without history is necessary), sometimes I want each and every version (if it's source code, e.g.), sometimes I want the ability to go back 2 or 3 versions (regardless of how old they are). Regardless of how I take snapshots (I only take them manually for now).
I think this is a litte to complicated to get.... the system with the different tags....  I don't think and end user can get behind it very fast.
There are definitly some examples required in the documents,

**Comment by jkowalski** [comment]
if you have not done full maintenance yet (IOW the data is still in the storage) you might be able to recover without re-uploading. Ping me on slack.kopia.io if you'd like to try that

**Comment by Hoffenbar** [comment]
Thank you for your helping offer. I have the source of the JPGs around, and have other backups. So I can simply rebuild a snapshot, but before doing that, I have to really understand how the retention thing works :-)

**Comment by jkowalski** [comment]
what does `kopia snapshot ls` show ?

**Comment by Hoffenbar** [comment]
```
matthiasu@desktop-ai70a0o:C:\Users\matthiasu\usr\data\Bilder
  2021-05-03 09:30:47 CEST kd57c0bc3c3203c6bea812d2b626d330f 0 B drwxrwxrwx files:0 dirs:1 (latest-1,annual-1,monthly-1,weekly-1,daily-1,hourly-1)
```

**Comment by Hoffenbar** [comment]
An addition: As I also altered the global retention policy, I don't know the original values anymore which I want to re-configure...... maybe some "reset values" would be fine :-)

**Comment by Hoffenbar** [comment]
Addition: Regardless of what I'm configuring, the snapshot is now complete in 0,01s, that is: nothing really happens anymore. This is a state which I think I already had a few months ago, when I began experimenting with kopia.

**Comment by jkowalski** [comment]
Looks like this directory may be empty `C:\Users\matthiasu\usr\data\Bilder`, is that not the case?

Can you run `kopia snapshot create --all --debug` ?

**Comment by Hoffenbar** [comment]
Fortunally, the directory isn't empty...;-)
At the moment, I can't run a `create --all...`, because there are many ofn them and I need by PC for the job :-)
Will show results later...

**Comment by Hoffenbar** [comment]
```
>kopia snapshot create --all --debug > kopia.log
kopia: error: unknown long flag '--debug', try --help
```

**Comment by Hoffenbar** [comment]
I found that this should be
```
kopia snapshot create --all --log-level=debug
```
instead. Will include results as soon as possible.

**Comment by Hoffenbar** [comment]
Snapshots done. Log is far too big to post, and contains sensible data - can I mail it to someone to analyze?
Starting KopiaUI thereafter: Only one snapshot has a current timestemp, and some two more have turned to a strange state......(infos, bin):

![2021-05-09 15_06_34-Kopia UI v0 8 4](https://user-images.githubusercontent.com/46227007/117573480-65117700-b0d8-11eb-8c0c-2e8ecfb371ab.jpg)

**Comment by Hoffenbar** [comment]
Now every snapshot I take leads to 0 byte Size, each snapshot only takes about 1 second. Seems that all what was stored before is lost.... I restored the global policy to its original state and deleted most snapshot-based policy modifications - nothings helped so far.

**Comment by Hoffenbar** [comment]
I have one local Ignore rule /*, since this only should not recurse into any subdirs. But it seems that now every snapshot only contains the top-level directory itself....

**Comment by Hoffenbar** [comment]
Example:

![2021-05-09 19_25_35-Kopia UI v0 8 4](https://user-images.githubusercontent.com/46227007/117581310-6f456c80-b0fc-11eb-9a2b-1c74757f6a40.jpg)

**Comment by Hoffenbar** [comment]
Additional question: How can I reset the global policies to their default values?

**Comment by Hoffenbar** [comment]
Could it be that because I have a backup of c:/users/matthiasu WITHOUT subDirs (exclude policy), all other separate Backups of c:/users/matthiasu/someSubDir did not work anymoure because of some magic between the separate snapshots?

**Comment by Hoffenbar** [comment]
Another question: What is the _parent of the global policy_? What is the meaning of _Disable Parent Policy Evaluation..._ at the global policy level?

**Comment by Hoffenbar** [comment]
It seems that the setting `[X] Ignore Parent Rules` (for files) does not work. At least a `policy show` shows the parent rule, which in this case I want to suppress...
