### ISSUE TITLE
Unable to persist password on OSX 10.13 / rclone

### ISSUE THREAD

**Issue by clyra** [kopia/kopia#1049]
Hi,

I'm trying to setup kopia on a old MBP running OSX 10.13 using a onedrive rclone repository. Rclone was installed from the downloaded binary as the installation using homebrew does not allow the rclone mount command. Creating a repository using this setup works, but then i got a error saying that kopia cant connect to the repository:
```
kopia repository create rclone --remote-path onedrivebkp1:/kopia
Enter password to create new repository:
Re-enter password for verification:
Initializing repository with:
  block hash:          BLAKE2B-256-128
  encryption:          AES256-GCM-HMAC-SHA256
  splitter:            DYNAMIC-4M-BUZHASH
kopia: error: unable to connect to repository: error connecting to repository: unable to persist password: error saving password in key ring: exit status 36, try --help 
```

Using the rclone mount command i can see that the repository was created and there is a few files there. Any tips? Is this something related to the OSX key chain ring? permissions perhaps?

thx

**Comment by jkowalski** [comment]
it's likely the keychain - can you access it using `Keychain Access` without entering password?

**Comment by clyra** [comment]
hm.. I'm not sure what you asking about. I can open Keychain app without a password, but then I cannot find a kopia, rclone or any entry which may be related to my kopia config. I just found that kopia has a --use-keychain flag but it doesnt seem to make any difference:

```
 kopia --use-keychain repository connect rclone --remote-path onedrivebkp1:/kopia
Enter password to open repository:

kopia: error: error connecting to repository: unable to persist password: error saving password in key ring: exit status 36, try --help
```

one more info: the password is right. If I enter a wrong password i got a "invalid repository password' error.

**Comment by clyra** [comment]
> it's likely the keychain - can you access it using `Keychain Access` without entering password?

I just ran it again with debug enabled and the keychain seems to be the culprit:

```
kopia  --use-keychain --log-level=debug  repository connect rclone --remote-path onedrivebkp1:/kopia
generating new TLS certificate
adding alternative IP to certificate: 127.0.0.1
starting /usr/local/bin/rclone
detected webdav address: https://127.0.0.1:54877/
Enter password to open repository:

Creating cache directory '/Users/lyra/Library/Caches/kopia/dxxxxxxxxxxxx3' with max size 5242880000
generating new TLS certificate
adding alternative IP to certificate: 127.0.0.1
starting /usr/local/bin/rclone
detected webdav address: https://127.0.0.1:54892/
saving 0 blobs with prefix m to cache
saving 0 blobs with prefix n to cache
listed 0 index blobs with prefix m from source
listed 0 index blobs with prefix n from source
saving password to OS keyring...
kopia: error: error connecting to repository: unable to persist password: error saving password in key ring: exit status 36, try --help
```

Even without "--use-keychain"  the result is the same. Where rclone should save the password (besides keychain)?
