### ISSUE TITLE
Attemp to run script before snapshot

### ISSUE THREAD

**Issue by amunhoz** [kopia/kopia#1052]
I'm trying to run a script before a snapshot using options "--before-snapshot-root-action" or "--before-folder-action" with no success.

I'm setting the configuration like this:
```
/opt/kopia/kopia policy set /var/lib/mysql/_dump \
   --before-folder-action "/usr/local/bin/dump/before.sh"

/opt/kopia/kopia policy set /var/lib/mysql/_dump \
   --before-snapshot-root-action "/usr/local/bin/dump/before.sh" 
```

Then, i test it with a manual snapshot, but the script is not executed.
Any explanation? Am i doing it right? Whats the difference between "folder action" and "snapshot root action"?

Thanks

EDIT:
I'm running kopia with the command:
/opt/kopia/kopia server --address 0.0.0.0:3123 --insecure --htpasswd-file=/data/kopia/config/pass.txt --server-username usertest

**Comment by julio-lopez** [comment]
Actions are disabled by default. They have to be enabled either:
- per client, on connect: `kopia repo connect --enable-actions ...` ; or
- per snapshot invocation `kopia snapshot create ... --force-enable-actions ...`

**Comment by amunhoz** [comment]
Thanks, but how can i configure in my use case, using the server UI?
Just add to the first command? 
`/opt/kopia/kopia server --enable-actions --address 0.0.0.0:3123 --insecure --htpasswd-file=/data/kopia/config/pass.txt --server-username usertest`
like this?

**Comment by amunhoz** [comment]
Ok, changed the json config manually and now its working.
Then, i'm using a different command line in the configuration, using bash command line:

/opt/kopia/kopia policy set /var/lib/mysql/_dump    --before-folder-action "bash /usr/local/bin/dump/before.sh" 

It's not working using only the script name.

**Comment by jkowalski** [comment]
is the script configured with executable bit (`chmod o+x  /usr/local/bin/dump/before.sh`) and does it start with `#!/bin/bash` ?
