### ISSUE TITLE
Possibly a small bug, "Excluded directories: 2" when only 1 is excluded.  

### ISSUE THREAD

**Issue by jaxjexjox** [kopia/kopia#1057]
Hi Team,

Version: KopiaUI 0.8.4.
I'm still evaluating the tool and learning the syntax for directory exclusion, I've specifically specified to exclude a folder, using /foldername/ in exclusions box.

When the backup is running you can click for details and it shows a summary, which clearly says "Excluded directories: 2" 

This is applicable, across 2 entirely different backup sets for testing.  I've done it a few times.
I've even restored the snapshot, by mounting the bucket as a drive, copying all the files to the local disk in another folder and doing a comparison.  It clearly shows only 1 folder excluded.

https://i.imgur.com/J1Pcij6.png
https://i.imgur.com/wD5D7BV.png

I could be making a mistake, it is possible but I've tried to be pretty thorough here.  Any idea what is going on?

**Comment by jaxjexjox** [comment]
[https://imgur.com/7xafPkH](url)

**Comment by xbb** [comment]
Probably relevant code:

https://github.com/kopia/kopia/blob/b844ce6b50d74b77609c56e093e63ff8f1819272/snapshot/snapshotfs/upload.go#L1132-L1140

**Comment by jaxjexjox** [comment]
Thank you, I appreciate the hard work.

**Comment by jaxjexjox** [comment]
Was this actually fixed or just identified btw?    I haven't seen a new version in a while (sorry?)

**Comment by jaxjexjox** [comment]
Do we know when a new version will ship fixing this?
