### ISSUE TITLE
Terraform provider

### ISSUE THREAD

**Issue by dbousamra** [kopia/kopia#1069]
It might be helpful to be able to declare repositories using Terraform. 

Thoughts? I'm not too familiar with Terraform, and what sort of interface/contract the providers require.

**Comment by jkowalski** [comment]
What's the use case? Do you have lots of repositories and clients?

**Comment by dbousamra** [comment]
My use case is I have 3 repositories declared. I then run a Google Cloud Function (similar to AWS Lambda) that creates a snapshot, and syncs it to all 3 repositories (S3, GCS, B2).

Being able to declare and manage the entire flow in Terraform would be handy.

**Comment by jkowalski** [comment]
Right now there's no terraform integration, but as long as it supports some raw scripting that should be possible to plug in.
