### ISSUE TITLE
Case sensitivy

### ISSUE THREAD

**Issue by Hoffenbar** [kopia/kopia#1070]
I noticed that from kopia perspective,`c:/users/matthiasu` is something different than `C:\Users\matthiasu`, for example. But on Windows, the case of paths should be ignored in comparisons....

**Comment by josvo** [comment]
Windows 10 does / can support case sensitivity on NTFS, see e.g. here: https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/
What I would suggest
- create the possibility to disable case sensitivity (default would be enabled)
- label this issue with "Feature request"

**Comment by Hoffenbar** [comment]
Yes, I know that *internally* NTFS store path names in the given case. But *every*, really *every* program on windows ignores the case when globbing, searching, etc,

**Comment by josvo** [comment]
Sorry, I don't get that. What would you suggest that kopia should backup when there are two files
- Readme.txt
- readme.txt

in the same directory? Both? The first? None?

**Comment by Hoffenbar** [comment]
Hello, to my knowledge, such case is impossible. While the NTFS-Layer may support such constellation, the Win32 API does not (as far as I know). While you may create `Readme.txt` and `readme.txt` one after another, they can't coexist at the same time in the same directory. I am 99,99999% shure that´s how it works.

**Comment by josvo** [comment]
They can and will coexist. I tested it, it works. In fact, that is what "case sensitivity" is about, isn't it?

**Comment by Hoffenbar** [comment]
Maybe. But you won't find a tool belongig to windows itself which supports that. See this simple example:
```
C:\temp>copy con abc.txt
Test1^Z
        1 Datei(en) kopiert.

C:\temp>copy con ABC.txt
Test2^Z
ABC.txt überschreiben? (Ja/Nein/Alle):
```

**Comment by alphaleonis** [comment]
If I recall correctly, I did add the option for case-insensitive matching in the implementation I did of the pattern matching used in .kopiaignore. I don't think it is ever used though, because I didn't know how to detect whether the underlying file system was case-sensitive or not.  So if someone knows how to achieve this, actually implementing it should be easy.

Another option could be to set it as a policy, or as a special "preprocessor" flag in the .kopiaignore file.

**Comment by Hoffenbar** [comment]
Interesting infos are here and there:
    - https://superuser.com/questions/365606/how-to-check-if-the-file-system-is-case-sensitive-on-windows-mac-and-linux
    -  https://stackoverflow.com/questions/33998669/windows-ntfs-and-case-sensitivity

**Comment by JohnKiller** [comment]
Just stumbled on this:

`kopia.exe policy set --enable-volume-shadow-copy always C:\`

then wondering why

`kopia.exe snapshot create c:\Users`

didn't use VSS...

**Comment by HunterZ** [comment]
As a new user of Kopia, this is incredibly frustrating.

I ported over ignore rules from Duplicati, and they didn't apply because the case wasn't perfectly matched.

Windows is NOT a case-sensitive OS, even if you can come up with weird edge cases. This should be a policy configurable behavior.

**Comment by jjYBdx4IL** [comment]
It's probably best to make case-sensitivity (or generally how to evaluate .kopiaignore files) part of the policy, with a default according to the OS.
