### ISSUE TITLE
Feature Request:  Repository connect via Azure SAS URL

### ISSUE THREAD

**Issue by chrislockwood** [kopia/kopia#1071]
In my organisation Azure Blob Storage access is controlled via [SAS URLs](https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-explorer-blobs#get-the-sas-for-a-blob-container).

Ideally I wish to avoid rclone (it is still tagged as "experimental") since in my experience it can be suboptimal when used with other competing backup solutions, actually that is one of the reasons why I am keen to switch over to Kopia.

However from what I can see the SAS method is not supported natively by Kopia ([Repository Connect Azure](https://kopia.io/docs/reference/command-line/common/repository-connect-azure/))

Any chance this can be implemented?

**Comment by jkowalski** [comment]
Yes, but I'm looking for external contributions here, since I don't actively use Azure myself so am not very familiar here.

**Comment by xxxliqu1dxxx** [comment]
> Ideally I wish to avoid rclone (it is still tagged as "experimental") since in my experience it can be suboptimal when used with other competing backup solutions, actually that is one of the reasons why I am keen to switch over to Kopia.

I also prefer native integrations vs leveraging rclone. i.e. OneDrive.

**Comment by chrislockwood** [comment]
You sir are a superstar!
