### ISSUE TITLE
Estimation during migrations is not showing

### ISSUE THREAD

**Issue by xxxliqu1dxxx** [kopia/kopia#1088]
Logged with Jarek's recommendation:

Repro steps

kopia snapshot migrate --all --config-file=/path_to_old_file --parallel=8 

Expected result:
Should show "estimating..." and some kind of progress in percentage, or time.

Actual result:
 \ 5 hashing, 608307 hashed (892.6 GB), 5032090 cached (1.1 TB), uploaded 306.7 GB, estimating...migrating snapshot of root@tower:/mnt/disks/SSD_250gb/system at 2021-05-17 08:48:28 EDT
 | 4 hashing, 608357 hashed (1 TB), 5032092 cached (1.1 TB), uploaded 319 GB, estimating...migrating snapshot of root@tower:/mnt/disks/SSD_250gb/system at 2021-05-17 09:50:59 EDT
 | 4 hashing, 608360 hashed (1.1 TB), 5032092 cached (1.1 TB), uploaded 334.3 GB, estimating...migrating snapshot of root@tower:/mnt/disks/SSD_250gb/system at 2021-05-17 10:48:29 EDT
 - 5 hashing, 608375 hashed (1.2 TB), 5032092 cached (1.1 TB), uploaded 346.9 GB, estimating...migrating snapshot of root@tower:/mnt/disks/SSD_250gb/domains at 2021-05-11 04:40:23 EDT
 | 4 hashing, 608377 hashed (1.2 TB), 5032093 cached (1.1 TB), uploaded 348.2 GB, estimating...migrating snapshot of root@tower:/mnt/disks/SSD_250gb/system at 2021-05-17 11:50:57 EDT
 \ 4 hashing, 608378 hashed (1.3 TB), 5032095 cached (1.1 TB), uploaded 366.1 GB, estimating...migrating snapshot of root@tower:/mnt/disks/SSD_250gb/system at 2021-05-17 12:48:29 EDT

**Comment by eh8** [comment]
Same issue on 0.9.0 during migration from v1 format repository to v2 format repository, as well as v2 format repository to another v2 format repository
