### ISSUE TITLE
DESIGN: Append-only index management

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#1090]
This is a proposal to change how indexes are managed, compacted and deleted.

## Background

Indexes are data structures written by Kopia clients when taking snapshots, which allow efficient lookup and retrieval of contents from repository blobs. The indexes undergo periodic maintenance to keep them small, compacted and easy to work with and remove duplicates and deleted contents.

Currently (as of Kopia v0.8) the data structure is simple but relatively fragile. There's only one set of indexes representing the current state of the world and if they get corrupted for whatever reason, the repository cannot be easily opened and indexes must be recovered using available tools, which can be quite slow (but full recovery is usually possible).

Currently the process of repository maintenance relies on blob deletion to keep the set of index blobs small, otherwise the performance would degrade over time. Eliminating deletions and having an append-only repository structure would allow Kopia to provide better protection against ransomware attacks and help with some compliance and data retention requirements.

This document describes index management protocol that does not need deletions to achieve good performance, allows periodic rollbacks and point-in-time recovery of the repository and simplifies index maintenance.

## Index Epochs

Kopia represents each change to a repository (content create/delete) as a timestamped entry in an index which is stored in a blob with `n` prefix. 

Because indexes are differential and all contents are identified by their hashes, indexes can be easily merged when needed by simply picking the latest index entry (create/delete) for given content.

The set of changes for a given span of time can be determined by loading all indexes created during that time period and merging them together:

```
MergeIndexes(LoadIndexesFromBlobs([blob1, blob2, ..., blobN])
```

The entire state of the world at time T can be determined by merging ALL active indexes in the repository from the beginning of time until T. This obviously does not scale as time passes and the number of index only grows so we must limit the number of indexes we load and we must have ability to quickly determine the minimal set of indexes required.

We will introduce the concept of epochs, which correspond to (mostly-)non-overlapping ranges of time, such that indexes can be assigned to epochs and efficiently merged with other indexes in the same epoch, thus reducing the amount of indexes to process. This loses some granularity when it comes to point-in-time restore ability, but should not practically matter very much when epochs are of the right granularity.

We will introduce the notion of epoch numbers, which are small integers that start with zero and increase slowly over time (single epoch duration will be several hours or days long typically >24h).

Each blob written by a kopia client will be associated with an epoch number. Epoch numbers will be such that individual Kopia clients will agree on which epoch we're currently (with some unavoidable possibility of minor disagreement of no more than 1), assuming all clients cooperate.

Index blob names will use epoch numbers as a name prefix to facilitate efficient scans. Each epoch-stamped index blob written by Kopia clients will be named:

```
n<epoch-number>.<hash>
```

This will allow efficient finding of all indexes in a single epoch by doing a blob prefix scan of `n<epoch-number>.`. We're expecting the number of index entries in an epoch to range between tens to low thousands.

## Epoch Number Consensus

We need to come up with a protocol that allows all kopia clients to agree on the current epoch number. Because kopia clients can't know about each other and perfect time sync does not exist, perfect consensus is impossible, so we need to have a protocol that achieves maximum agreement and guarantees that if there's disagreement, individual clients disagree by at most 1 for a bounded amount of time.

Epochs will be cooperatively managed by all Kopia clients that share a repository by using `e` blobs as markers to determine the current epoch number. 

On startup, before writing an index blob and at least once per hour, each Kopia client will scan all `eNNNN` blobs in a repository and pick the highest NNN number to determine the current epoch the system is in (or zero if no `e` blobs are present). If the repository blobs can't be scanned, all write operations will be suspended until the connection comes back.

New epochs will be started cooperatively without central coordination. When one of the clients decides to start an epoch, they will write `e<epoch-number+1>` blob to establishes a new epoch. Existing clients will pick it up in no more than one hour.

We want to guarantee that epochs are reasonably "chunky" (they have many index blobs per epoch as opposed to just a handful and they span some minimum duration). Each cooperating client may decide to start a new epoch when both of the following are true:

* the number of `n<epoch-number>.*` blobs exceeds certain threshold (>20 or so)
* the minimum amount of time (>24h) has passed between writing `e<epoch-number>` and `n<epoch-number>.*` - this can be determined by comparing their server-assigned timestamps.

> Alternative considered: time-based epoch computation, where `epoch_number = (now() - repository_creation_time) / epoch_duration` is very easy to implement but may fail catastrophically when time is out of sync between clients.

Very old epoch markers will be very infrequently pruned even for very long-lasting repositories.

## Past Epoch Index Compaction

Over time a large number of indexes can be created in each epoch. It will become time-consuming for all kopia clients to load and merge them, so we will introduce periodic automatic compaction of indexes for each epoch and add a new type of index blob representing compacted indexes from a given epoch. 

Let’s call this new blob type `u`, Instead of loading individual `n` blobs and merging them, clients can load single `u` blob if it exists.

A key property of this type of blob is that when epoch `N` is reliably in the past (more than one whole epoch has passed since then), then all the clients will agree on the exact contents of the compacted blob, and it can be computed using the following expression.

```golang
MergeIndexes(LoadIndexesFromBlobs(ListBlobs(“n{epochNumber}.*“)))
```

This means that when loading indexes for a previous epoch, all clients can cooperatively perform a single-epoch compaction using the following algorithm:

```golang
func GetIndexesFromEpoch(epochNumber) {
    if epochNumber >= current_epoch - 2 {
        // if the epoch loaded is recent enough (today or yesterday), load individual indexes
        // and merge them without relying on compacted blobs.
        return MergeIndexes(LoadIndexesFromBlobs(ListBlobs(“n{epochNumber}.*“)))
    }

    b = ListBlobs(“u{epochNumber}.*“)
    if not empty(b) {
        // load the compacted blob.
        // there should be exactly one since all writers will agree on full blob name
        return LoadIndexesFromBlobs(b)
    }

    merged = MergeIndexes(LoadIndexesFromBlobs(ListBlobs(“n{epochNumber}.*“)))
    hash = HashOf(merged)
    WriteBlob(“u{epochNumber}.{hash}“)
    return merged
}
```

Each client will attempt to read compacted blob first and if it does not exist they will perform the compaction and store the compacted blob for future reuse by other clients. There is a minor race condition where multiple clients could attempt the operation at exactly the same time, but it's not a problem since they will come up with identical index contents and blob writes are atomic.

The per-epoch index is incremental (does not contain any information from previous epochs), so in order to get a complete state of the world, we need to walk all the previous epochs, load and merge their indexes, until we know we have seen enough to build the complete picture.

How far do we go back? In the worst case we'd need to go back all the way to epoch 0, this clearly would not scale.

## Checkpoints

To reduce the number of epochs to scan, we will introduce the third type of index blob representing fully-consolidated indexes. Let’s call the blob `w` for the full “state of the world”:

```
`w<epoch-number>.<hash>`
```

In order to determine the full set of indexes, each client will list all the `w` blobs, pick the one with the highest epoch number `N`, load its index and merge with all indexes returned by `GetIndexesFromEpoch(e)` for all e greater than N until the current epoch + 1 (we must assume that some other may have has already decided to start a new epoch but we're not aware of it yet)

```golang
func GetMergedIndex() {
    return GetMergedIndexUpToEpoch(CurrentEpochNumber()+1)
}

func GetFullyCompactedEpochNumberBefore(maxEpoch) {
    wblobs = ListBlobs(“w*“)
    h = max(n) for n in EpochNumberFromBlob(wb for wb in wblobs) where n < maxEpoch
    if !h {
        // no w blobs written yet, go all the way back to the epoch when the repository was created
        return 0
    }
    return h
}

func GetMergedIndexUpToEpoch(maxEpoch) {
    merged = {}
    for n := GetFullyCompactedEpochNumberBefore(maxEpoch); n <= maxEpoch; n++ {
        merged = MergeIndexes(merged, GetIndexesFromEpoch(n))
    }
    return merged
}
```

**Comment by atYuguo** [comment]
A probably stupid idea for the `epoch-number` calculation. Rather than using the real world time, some counters like "how many operations on repository" may be better? It's monotonically increasing and more meaningful compare to time. As long as the repository remembers it, there's no sync problem.

**Comment by bbccdd** [comment]
You're pretty close to building a block chain for backups ;-)

**Comment by jkowalski** [comment]
@atYuguo this is the idea. I had some leftover examples that relied on time - fixed them.

@bbccdd if you think about it, other than the adversarial nature of blockchain (where miners compete to win virtual currency/tokens), the techniques/principles used here are quite similar. Both are trying to establish a useful consensus about the state of the world (wallets & backups respectively) amongst minimally-coordinated clients. Unlike blockchain we want to trim the history periodically, though. :)

**Comment by bbccdd** [comment]
Exactly. And on a not so serious note, we could use a 'proof of stake' mechanism not requiring mining competitions, whereby your source files (or hashes of snapshots) grant you a certain standing in relation to establishing truth and subsequent atomic sequels. Trimming down the main storage space consuming history is indeed desirable but not necessarily within the snapshot manager, mainly of all that resides in the repository. Again, I am not being super serious. Just connecting concepts.

**Comment by jkowalski** [comment]
I've been doing experiments over the last couple weeks and have come up with a bunch of improvements to this design:

## Blob naming

We will use the new `x` prefix for all indexes and deprecate `n` prefix. The naming is:

* `xe<number>` - for epoch marker blobs
* `xn<number>_<hash>-s<random>-c1` - for uncompacted index blobs written by content manager
* `xs<number>_<hash>-s<random>-c<count>` - for compacted blobs from a single epoch, written when `current epoch >= number + 2`
* `xr<number1>_<number2>_<hash>-s<random>-c<count>` - for index spanning a range of epochs, written at any time after `current epoch >= number + 2`
* We will no longer need full snapshots, as they are equivalent to `xr0_<epoch>_*` blobs.

The reader will:

1. list all `xr*` blobs and try to find the shortest set of blobs that covers maximum range of contiguous epoch numbers starting from zero using fewest number of `xr` blobs.
2. Use `xs` and `xn` blobs for the remainder of the indexes until the current epoch

When the chain of indexes becomes too long, the reader will occasionally write a new `xr` blob to replace N blobs with one. Old blobs `xr<A>_<B>` and `xr<B>_<C>` for which `xr<A>_<C>` exists will be subject to garbage collection.
When the number of `xn` blobs for the current epoch becomes too large, the reader will advance the current epoch.

## Consistent set detector

For scalability reasons, compacted indexes for a given epoch may span multiple blobs, so we must ensure we are able to detect when a complete set of them has been written. To do that we will use the new naming convention:

* `<prefix><hash>-s<set>-c<count>`

Where `<set>` is a 64-bit number identifying the set of indexes that must always be used together and `<count>` is the number of items in the set. A set of index blobs `<set>` is considered complete if the reader finds exactly `<count>` blobs containing `s<set>` as part of their name. Partial sets will be ignored and subject to garbage collection as they indicate that a writer has crashed in the middle of writing a set.

**Comment by julio-lopez** [comment]
Already done: Jarek implemented an epoch-based index management approach.

**Comment by dffvb** [comment]
So does that mean we have an append mode now?
