### ISSUE TITLE
Back button when adding a repository not working

### ISSUE THREAD

**Issue by enboig** [kopia/kopia#1097]
Using 0.8.4 on linux, when adding a new kopia server repo; I cannot go back to "kopia server" page from "user" page.

**Comment by lupusA** [comment]
Hi, the issue is still present in Kopia 0.12.1. I've created a pr to fix the issue hopefully: 

https://github.com/kopia/htmlui/pull/144

Cheers,

**Comment by julio-lopez** [comment]
Closing this issue. The fix will be included the next time the UI is updated in kopia/kopia.
