### ISSUE TITLE
many small files performance problem

### ISSUE THREAD

**Issue by ericma15** [kopia/kopia#1098]
First thanks for provding this awsome project.
But when I use it, i found some strange thing.
I backup some of my personal code accidently. When I try to restore my files, i found kopia  process slowly on these small files.
So i do a test. I create some repository with backend filesystem , webdav,  and rclone. I backup kopia code and then restore it to another place. filesystem backend take about 2s to backup and 10s torestore. But webdav take about 10s to backup but about 8h torestore it.The  same behavior with rclone:webdav. my webdav server use sftpgo and i download file from it with about 6M/s（when restore，kopia show speed is about 20kib/s）. Also the total repository is about 70 MB, but my computer record i downloads over 2GB files. So I check the log, i find kopia always log get blob offset xxxx. 
Do kopia cache this files or download it over and over again？SO it cause this poor peformance. BTW，when process repository with big files, kopia do
well, it can fully use my bandwidth.
Hope your reply soon.

**Comment by jkowalski** [comment]
Strange. Both rclone and webdav are relying on webdav protocol. There could be something throttling the performance there, I'll do some investigation.

**Comment by ericma15** [comment]
Thank you. I'd love to help you do some test.

**Comment by jkowalski** [comment]
I downloaded `sftpgo` and created a repo, snapshotted kopia's working git directory (about 5GB of data) - was very quick.

During the restore sftpgo appears to be burning through CPU and individual read requests are taking hundreds of milliseconds, like this one that only fetched 2KB and took 0.752s:

```
2021-05-28 15:34:19.974 D [logger.go:254] [STORAGE] GetBlob("pd6b0c9d53430df9cf05ec0f87003c2cc-s634464150b351d04104",1281958,2103)=({2103 bytes}, <nil>) took 752.163858ms
```

This is weird since this should be an I/O-bound operation. Could there be some compression going on?

**Comment by jkowalski** [comment]
sftpgo logs confirm (this is for a different file - 20MB taking over 1.5s, which should not be happening on SSD):

```
{"level":"info","time":"2021-05-28T15:44:08.593","sender":"Download","elapsed_ms":1524,"size_bytes":21113778,"username":"user","file_path":"/Users/jarek/webdavtest/data/p68/dd1/d765059bdea1a2a2230c4313697-s634464150b351d04104.f","connection_id":"DAV_c2on4do6n88jcqgughu0","protocol":"DAV"}
```

**Comment by jkowalski** [comment]
I killed sftpgo with SIGQUIT and it indeed shows compression taking place:

```
goroutine 1550 [running]:
compress/flate.(*compressor).deflate(0xc000a22000)
	/Users/runner/hostedtoolcache/go/1.16.3/x64/src/compress/flate/deflate.go:427 +0x229 fp=0xc00127c8d0 sp=0xc00127c860 pc=0x4226c09
compress/flate.(*compressor).write(0xc000a22000, 0xc001724000, 0x8000, 0x8000, 0x8000, 0xd7c6945d, 0x0)
	/Users/runner/hostedtoolcache/go/1.16.3/x64/src/compress/flate/deflate.go:554 +0x85 fp=0xc00127c910 sp=0xc00127c8d0 pc=0x4227785
compress/flate.(*Writer).Write(...)
	/Users/runner/hostedtoolcache/go/1.16.3/x64/src/compress/flate/deflate.go:712
compress/gzip.(*Writer).Write(0xc0000eedc0, 0xc001724000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/Users/runner/hostedtoolcache/go/1.16.3/x64/src/compress/gzip/gzip.go:196 +0xc5 fp=0xc00127c960 sp=0xc00127c910 pc=0x42343a5
github.com/go-chi/chi/v5/middleware.(*compressResponseWriter).Write(0xc0035e6000, 0xc001724000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.2/middleware/compress.go:333 +0x66 fp=0xc00127c9a8 sp=0xc00127c960 pc=0x4438446
io.copyBuffer(0x7c1b378, 0xc0035e6000, 0x56c31c0, 0xc000802018, 0xc001724000, 0x8000, 0x8000, 0x5353c20, 0xc0005d6000, 0x7c1b378)
	/Users/runner/hostedtoolcache/go/1.16.3/x64/src/io/io.go:425 +0x21c fp=0xc00127ca28 sp=0xc00127c9a8 pc=0x40b945c
io.Copy(...)
	/Users/runner/hostedtoolcache/go/1.16.3/x64/src/io/io.go:382
io.CopyN(0x7c1b378, 0xc0035e6000, 0x7636b30, 0xc0035e60a0, 0x16df19a, 0x0, 0x0, 0x0)
	/Users/runner/hostedtoolcache/go/1.16.3/x64/src/io/io.go:358 +0x9a fp=0xc00127ca88 sp=0xc00127ca28 pc=0x40b8ffa
net/http.serveContent(0x56d8660, 0xc0035e6000, 0xc0014ac200, 0xc002d40004, 0x3b, 0x8b8bc9e, 0xed8436480, 0x5feda80, 0xc00127cd38, 0x77ff258, ...)
	/Users/runner/hostedtoolcache/go/1.16.3/x64/src/net/http/fs.go:337 +0x42f fp=0xc00127cce0 sp=0xc00127ca88 pc=0x435bb4f
net/http.ServeContent(0x56d8660, 0xc0035e6000, 0xc0014ac200, 0xc002d40004, 0x3b, 0x8b8bc9e, 0xed8436480, 0x5feda80, 0x77ff258, 0xc0035e60a0)
	/Users/runner/hostedtoolcache/go/1.16.3/x64/src/net/http/fs.go:204 +0xd8 fp=0xc00127cd60 sp=0xc00127cce0 pc=0x435b6f8
golang.org/x/net/webdav.(*Handler).handleGetHeadPost(0xc000110140, 0x56d8660, 0xc0035e6000, 0xc0014ac200, 0xc8, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/drakkan/net@v0.0.0-20210328115440-0aedf3ac0c83/webdav/webdav.go:226 +0x5a5 fp=0xc00127ce98 sp=0xc00127cd60 pc=0x4d9c425
golang.org/x/net/webdav.(*Handler).ServeHTTP(0xc000110140, 0x56d8660, 0xc0035e6000, 0xc0014ac200)
	/Users/runner/go/pkg/mod/github.com/drakkan/net@v0.0.0-20210328115440-0aedf3ac0c83/webdav/webdav.go:54 +0xab fp=0xc00127cf00 sp=0xc00127ce98 pc=0x4d9a8cb
github.com/drakkan/sftpgo/webdavd.(*webDavServer).ServeHTTP(0xc000114050, 0x56d8660, 0xc0035e6000, 0xc0014ac100)
	/Users/runner/work/sftpgo/sftpgo/webdavd/server.go:202 +0xbce fp=0xc00127da78 sp=0xc00127cf00 pc=0x4ee362e
github.com/go-chi/chi/v5/middleware.(*Compressor).Handler.func1(0x56d9c50, 0xc0005d60e0, 0xc0014ac100)
	/Users/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.2/middleware/compress.go:213 +0x290 fp=0xc00127db48 sp=0xc00127da78 pc=0x443d3d0
```

**Comment by jkowalski** [comment]
I investigated this and the fix is to have webdav client server-side compression.

The performance differences of upload vs download is expected and unavoidable at least now. When uploading - Kopia creates a pack file in memory and sends one request to the server to write it. When downloading, we must retrieve individual pieces of the pack file so that will be N requests to the server which will necessarily always be slower.

You can usually improve performance by increasing the parallelism (`--parallel` flag) but that can put too much stress at the backend at some point.

**Comment by ericma15** [comment]
Thanks for solving this problem so quick. I'll try it and give a feedback. Now I think maybe i config sftpgo with something wrong
