### ISSUE TITLE
[PENDING] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [kopia/kopia#11]
Dear @kopia,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by jkowalski** [comment]
Yes, it will be available very soon. I'm working on release mechanics right now.

**Comment by jkowalski** [comment]
I was finally able to make progress on the release mechanics.

@sergeevabc You should be able to download a preview of Windows binaries from https://github.com/kopia/kopia/releases/tag/v0.3.0-pre2

Please let me know if this release works for you (I primarily test on macOS/Linux), and report any issues you find.

Also, new docs website are now available at https://kopia.io/docs/

**Comment by sergeevabc** [comment]
@jkowalski, I confirm that it is possible to launch a binary on Windows,
yet it is not obvious how to use it in the wild, because [User’s guide][1] section is empty.

[1]: https://kopia.io/docs/user-guide/
