### ISSUE TITLE
kopia verify seemingly stuck

### ISSUE THREAD

**Issue by anicolao** [kopia/kopia#1105]
```
$ sudo kopia content verify --full --parallel=32
```

eventually seemed stuck, with the logs dominated by cache timestamp updates and no GetBlob calls for more than 2h. 

Killed to capture the thread dump.

[threads.nl.gz](https://github.com/kopia/kopia/files/6572769/threads.nl.gz)

**Comment by jkowalski** [comment]
From what I can tell a bunch of goroutines are waiting on cache fetches which have become slow for some reason. I'll dig deeper. I think it's making progress but extremely slowly.
