### ISSUE TITLE
flag --help-full doesn't work in certain subcommands

### ISSUE THREAD

**Issue by icepic** [kopia/kopia#1111]
kopia snapshot create --help-full 
doesn't show more help, it tries to create a snapshot.
kopia snapshot create --help shows there to be a --help-full flag to use to get all usable flags.

**Comment by jorgenman** [comment]
Does the `--help-full` flag really make sense as a common flag for all commands? If it's supposed to show help for all commands, maybe it should only apply to commands that have sub-commands. Or it could just be for the root `kopia` command.

**Comment by julio-lopez** [comment]
IINM, this is an issue with https://github.com/alecthomas/kingpin
We may consider replacing the CLI flags parsing package in the future.
