### ISSUE TITLE
Question: How to delete the snapshots in the UI?

### ISSUE THREAD

**Issue by gerroon** [kopia/kopia#1136]
Hi

I added two snapshots for testing. Now I want to delete them but I do not see a way to do it in the UI.

I am using Windows 10, I setup a Kopia server on Linux so this Win client is connected to that one.

![KopiaUI_prRHqgq55t](https://user-images.githubusercontent.com/8519469/121818132-f5e4f080-cc4a-11eb-951f-25b979ba5980.jpg)

**Comment by jkowalski** [comment]
UI is still quite bare-bones and does not support deletion yet, you need to use CLI for that. This will be added in future releases.

**Comment by gerroon** [comment]
Thanks for the reply. Do I need to do this on the client side or on the server side?

**Comment by jkowalski** [comment]
This is now supported in the UI #1730.

**Comment by gerroon** [comment]
Hi

Thanks for implementation but that is not what I meant. What I meant was the top level snapshtos not the individual snapshot items inside the top level listings, I do not know what they  are called but they have that "snapshot now" button next to them.

**Comment by jkowalski** [comment]
If you select all snapshots and delete them there is an option to delete the entire source.
