### ISSUE TITLE
implement extract command

### ISSUE THREAD

**Issue by purplesrl** [kopia/kopia#114]
I have tested this and its a great tool, especially because of the sftp and webdav, very fast and modern, but unfortunately there is one major flaw: there is no extract command, which is present in all other backup programs.

I was thinking:

kopia extract [snapshot_id] [PATH] [EXTRACT_PATH] <--test> <--verify> <-a>

Problem with FUSE: I am backing up on a VPS, as many people I am sure do, in the case of OpenVZ, there is no fuse by default and many providers are unwilling to enable it because it uses too much resources, I tried also to mount remotely but it will not work, so I am unable to use your program because I cannot restore the files.

**Comment by jkowalski** [comment]
basic support for restore is now submitted, we will file additional issues for performance and feature improvements.
