### ISSUE TITLE
BUG: Missing snapshots after deleting cache folder

### ISSUE THREAD

**Issue by ocha** [kopia/kopia#1140]
I was testing if it is safe to delete cache folder manually (or through cli command). While doing that I noticed that snapshots command is giving me an empty list. According to documentation, cache folder can be deleted without any issues.

Steps:

1. Create snapshot `kopia snapshot create /opt/path-to-folder/`
`Created snapshot with root k96819dd5be59d015154491b134c38615 and ID 4b1aa9e3462b33b83a22fe833b70da19 in 1m12s`
2. verify snapshot is there: `kopia snapshot ls`
`2021-06-14 20:01:02 UTC k96819dd5be59d015154491b134c38615 80.3 MB drwxr-xr-x files:8387 dirs:682 (latest-1,annual-1,monthly-1,weekly-1,daily-1,hourly-1)`
3. Remove cache folder: `kopia cache clear`
`Clearing cache directory: /root/.cache/kopia/c9efdae5eaa57db8.`
4. Observe no more snapshots: `kopia snapshot ls` - no output
I am using following version on ubuntu 20.04:
`0.8.4 build: 940d10dfa29e771467b5d9d45412b889053c2ed1 from: kopia/kopia`

Repository is pointing to s3 compatible service (similar to minio) and I can see snapshot creating files in the s3 repo.

**Comment by jkowalski** [comment]
I tried this exact sequence but can't reproduce the issue.

Here are some hints:

* Is there a chance the provider does not guarantee strong consistency? In other words, can it be so that when you create a file, it can't be immediately seen in list results?

* Is it possible that the provider was eventually consistent and the the issue resolved itself with time?

* If you still have the repo in this state can you do:

```
$ kopia blob ls
$ kopia content ls
$ kopia manifest ls
```

**Comment by ocha** [comment]
> Is there a chance the provider does not guarantee strong consistency? In other words, can it be so that when you create a file, it can't be immediately seen in list results?

I don't think so. I am using storj.io service and I can see new files in the bucket and download them right after running snapshot.

> Is it possible that the provider was eventually consistent and the the issue resolved itself with time?

I waited overnight and still no snapshots (see output below)

> If you still have the repo in this state can you do:
```
$ kopia blob ls
p2119a7d758e811be1ef53295b3738294-s308ec96cb8c4d72e105                   21276159 2021-06-14 19:50:56 UTC
p305b556fadf1cbf6a49a944002fae2df-s308ec96cb8c4d72e105                   25368196 2021-06-14 19:50:31 UTC
n4145d9741c5c01dd1b9c2742a9cdaab5-sd93dae707b6b2d22105                        159 2021-06-14 19:49:30 UTC
pfae1dc040c988b2a7b5e20d389579def-s308ec96cb8c4d72e105                   11514132 2021-06-14 19:51:08 UTC
pa07d42721d47b70c5ab8c85fd88748ad-s38dea6f23564adc0105                   24946160 2021-06-14 20:01:03 UTC
q71390ede71f07bb23da74dd025bc04ef-s4891b1891d3b7985105                       4282 2021-06-14 19:51:36 UTC
n1a3d1a88a1073858b8be03afb8578768-s308ec96cb8c4d72e105                     318871 2021-06-14 19:51:16 UTC
p642e9a6909f8bce984b828e9249fb2da-s38dea6f23564adc0105                   11518228 2021-06-14 20:02:21 UTC
qaf844c3562ce6e9ff31c022cabd21f26-s308ec96cb8c4d72e105                    1635002 2021-06-14 19:51:06 UTC
p5921d473ca237072d05af64f8e6584f2-s308ec96cb8c4d72e105                   21851882 2021-06-14 19:50:30 UTC
q9b370ff8f67a32c5a06097d292949e68-sd93dae707b6b2d22105                       4282 2021-06-14 19:49:29 UTC
kopia.maintenance                                                             383 2021-06-14 19:51:22 UTC
p91d9f66f205448aa1c29b2af2ded2b22-s38dea6f23564adc0105                   22273918 2021-06-14 20:01:03 UTC
kopia.repository                                                              686 2021-06-14 19:49:25 UTC
n987f9772d25b4c4b5bfe1a5ffeff0c14-s38dea6f23564adc0105                     318871 2021-06-14 20:02:53 UTC
nfbd563ec7d2570e50d46923bbe03ca21-s4891b1891d3b7985105                        159 2021-06-14 19:51:38 UTC
n7f760decec35eadbdd1ae5d3ae850fee-sb80c34d3bf6db40e105                        159 2021-06-14 20:00:58 UTC
q4caff5f4cdb080e60c95d14d8bbb51d8-s38dea6f23564adc0105                    1635002 2021-06-14 20:02:15 UTC
q91521e7c78127c8024caff5dd9c4ecdd-sb80c34d3bf6db40e105                       4282 2021-06-14 20:00:57 UTC
pbc6f6618ba9b0c73066b91925cd0b306-s38dea6f23564adc0105                   21792255 2021-06-14 20:01:41 UTC

$ kopia content ls

$ kopia manifest ls
```

**Comment by jkowalski** [comment]
There are clearly some indexes here (n*) so you should see non-empty content list. Can you paste the latest log from the `content-logs` directory?

**Comment by jkowalski** [comment]
Also can you list all files in the cache directory?

**Comment by ocha** [comment]
> Also can you list all files in the cache directory?
```
root@mail:~/.cache/kopia# tree .
.
├── c9efdae5eaa57db8
│   ├── blob-list
│   │   ├── list-m
│   │   └── list-n
│   ├── CACHEDIR.TAG
│   ├── contents
│   ├── kopia.repository
│   ├── metadata
│   └── own-writes
├── cli-logs
│   ├── kopia-20210614-200701-2588294-snapshot-list.log
│   ├── kopia-20210614-201019-2589978-snapshot-verify.log
│   ├── kopia-20210614-201024-2589997-snapshot-list.log
│   ├── kopia-20210614-201057-2590470-snapshot-verify.log
│   ├── kopia-20210614-201108-2590535-snapshot-verify.log
│   ├── kopia-20210614-201137-2590762-snapshot-verify.log
│   ├── kopia-20210614-201613-2593297-snapshot-verify.log
│   ├── kopia-20210615-134002-3182729-snapshot-verify.log
│   ├── kopia-20210615-134009-3182837-snapshot-list.log
│   ├── kopia-20210615-134028-3183068-blob-list.log
│   ├── kopia-20210615-134033-3183167-content-list.log
│   ├── kopia-20210615-134039-3183234-manifest-list.log
│   ├── kopia-20210615-134448-3186669-content-list.log
│   ├── kopia-20210615-134451-3186716-manifest-list.log
│   └── latest.log -> kopia-20210615-134451-3186716-manifest-list.log
└── content-logs
    ├── kopia-20210614-201024-2589997-snapshot-list.log
    ├── kopia-20210614-201108-2590535-snapshot-verify.log
    ├── kopia-20210615-134009-3182837-snapshot-list.log
    ├── kopia-20210615-134028-3183068-blob-list.log
    ├── kopia-20210615-134039-3183234-manifest-list.log
    ├── kopia-20210615-134451-3186716-manifest-list.log
    └── latest.log -> kopia-20210615-134451-3186716-manifest-list.log
```

**Comment by ocha** [comment]
Also, here is contents of `list-m`
```
root@mail:~/.cache/kopia# cat c9efdae5eaa57db8/blob-list/list-m
{"timestamp":"2021-06-15T13:44:49.621558494Z","blobs":null}�#ڔ5x�SV��a���J�j��g6Қ]H�
```

**Comment by jkowalski** [comment]
what's `list-n` saying?

can you share `kopia-20210615-134451-3186716-manifest-list.log` from `content-logs` ?

**Comment by ocha** [comment]
> what's `list-n` saying?

`{"timestamp":"2021-06-15T13:44:49.927871558Z","blobs":null}i"U��T�_��z�'�_t�=8\4@^�p�0�`

> can you share `kopia-20210615-134451-3186716-manifest-list.log` from `content-logs` ?
```
2021-06-15 13:44:51.9036032 list-from-cache 'n' found 0
2021-06-15 13:44:51.9036052 list-from-cache 'm' found 0
```

P.S. Time is in UTC

**Comment by jkowalski** [comment]
can you delete both of these files (list-m and list-n) and try again?

**Comment by jkowalski** [comment]
may be quicker to use `slack.kopia.io` - I have 10-15 minutes now.

**Comment by ocha** [comment]
After @jkowalski helping out we found out that `storj does support prefix scans` and issue is dues to not fully compatible S3 gateway. Thank you @jkowalski 🙏

**Comment by dragon2611** [comment]
rclone mount and then using the filesystem *may* work for storj but I'd test it througherly.

using the rclone backend in kopia directly doesn't as it won't detect it's written the file.
