### ISSUE TITLE
Icon in system tray missing? (Ubuntu)

### ISSUE THREAD

**Issue by dynobo** [kopia/kopia#1146]
It seems like the system tray icon is not shown correctly on my system. Instead it seems to show some kind of gnome fallback-icon (above red arrow):

![image](https://user-images.githubusercontent.com/11071876/122611366-7f4c5680-d081-11eb-94ad-8c4eb2f7e1f3.png)

Ubuntu 21.04
GNOME Shell 3.38.4 
Kopia 0.8.4

If I can try anything to investigate this issue, please let me know.

And: Thanks for this nice piece of software! :-)

**Comment by jkowalski** [comment]
Can you try with latest release candidate (v0.9.0-rc2)?

**Comment by dynobo** [comment]
Sorry not using Kopia anymore...
