### ISSUE TITLE
Feature Request: Support scheduling of sync-to operations in KopiaUI

### ISSUE THREAD

**Issue by alphaleonis** [kopia/kopia#1158]
It would be really nice if it was possible to schedule "sync-to" operations in KopiaUI as well.  Especially on windows, scheduling operations is a bit cumbersome, and keeping track of them having executed and so on.  

Suggest adding a feature to allow creating schedules for synchronizing a repository to one or more remote storages in Kopia UI.

**Comment by ruslan-mogilevskiy** [comment]
It will be a really useful feature.
