### ISSUE TITLE
Question / Feature Request: View total size of all snapshots

### ISSUE THREAD

**Issue by ned-martin** [kopia/kopia#1207]
First, the question:

Is there any way to view the (compressed and deduplicated - i.e. the size of the storage) size of all snapshots?

Now the feature request:

I'd like to be able to view a simple comparison of the source size versus the storage size for a "backup set" (series of snapshots? I dunno what you call them)

For example, using Duplicati's web interface as an example, we have:

```
Source: 94.78 GB
Backup: 47.09 GB / 8 Versions
```

Is there any way to get a similar statistic for kopia, and if not, can it be added? (Ideally to the GUI as well)

**Comment by jnemeiksis** [comment]
I tried to find via cli, but also not found. Did you that?

**Comment by sssheridan** [comment]
Also would like this.

**Comment by sssheridan** [comment]
Regarding the first question (total size of the whole repository), `kopia content stats` will do that for you. It took a few minutes on my repository to yield this output:

````
# kopia content stats
Count: 1849613
Total Bytes: 2.3 TB
Average: 1.3 MB
Histogram:

        0 between 0 B and 10 B (total 0 B)
    10079 between 10 B and 100 B (total 703.4 KB)
   548751 between 100 B and 1 KB (total 231.1 MB)
   306519 between 1 KB and 10 KB (total 1.3 GB)
   176948 between 10 KB and 100 KB (total 6.9 GB)
   239179 between 100 KB and 1 MB (total 87.2 GB)
   568137 between 1 MB and 10 MB (total 2.2 TB)
        0 between 10 MB and 100 MB (total 0 B)
````
2.3 TB seems reasonable, so I believe it's the total size of my repository, presumably excluding the metadata files.

However, the histogram doesn't reflect the filesizes of my files. Presumably it's Kopia's internal shards/chunks/whatnot; I'm still working to figure out what the "content" is, as compared to "blobs" (I'm still waiting for `kopia blob stats` to finish).

**Comment by nakermann1973** [comment]
`kopia snapshot ls --storage-stats` will show what you want on the CLI
