### ISSUE TITLE
[Bug]Snapshot verify ETA estimator is borked

### ISSUE THREAD

**Issue by stpr-dev** [kopia/kopia#1212]
Setup:
Arch Linux (Linux 5.12.19)
kopia 0.8.4 (AUR)
Local repository on an external hard drive (NTFS).

Description:
Running `kopia snapshot verify --verify-files-percent=100` for testing purposes, the messages on `stdout` indicate that the ETA estimator is borked.

Example messages:

```
...
Found 193021 objects, verifying 15, completed 78773 objects remaining 624h10m20s (ETA 2021-08-20 22:36:25 ADT).
Found 193021 objects, verifying 15, completed 78775 objects remaining 626h20m1s (ETA 2021-08-21 00:46:07 ADT).
Found 193021 objects, verifying 15, completed 78777 objects remaining 628h40m37s (ETA 2021-08-21 03:06:45 ADT).
Found 193021 objects, verifying 15, completed 78780 objects remaining 632h15m19s (ETA 2021-08-21 06:41:29 ADT).
...
```

Basically, the 'remaining time' and the 'ETA date' is monotonically increasing to a point where it is clearly off.

**Comment by jkowalski** [comment]
Can you try latest version from https://github.com/kopia/kopia-test-builds/ ?

**Comment by stpr-dev** [comment]
Appears to be displaying the same behaviour:

```
Found 193021 objects, verifying 15, completed 31063 objects remaining 14m17s (ETA 2021-07-25 22:59:27 ADT).
Found 193021 objects, verifying 15, completed 31065 objects remaining 14m31s (ETA 2021-07-25 22:59:43 ADT).
Found 193021 objects, verifying 15, completed 31068 objects remaining 14m48s (ETA 2021-07-25 23:00:03 ADT).
Found 193021 objects, verifying 15, completed 31071 objects remaining 14m56s (ETA 2021-07-25 23:00:12 ADT).
Found 193021 objects, verifying 15, completed 31074 objects remaining 15m4s (ETA 2021-07-25 23:00:22 ADT).
Found 193021 objects, verifying 15, completed 31076 objects remaining 15m11s (ETA 2021-07-25 23:00:30 ADT).
```

**Comment by jkowalski** [comment]
That looks fixed to me, the ETA is minutes away, not a month away, can you wait a bit longer to see whether it finishes around the stated time?

**Comment by stpr-dev** [comment]
Okay, I let it run for quite a while. It is much better than what it was, it is showing hours away instead of like months:
```
Found 193021 objects, verifying 15, completed 132920 objects remaining 3h52m48s (ETA 2021-07-26 14:50:35 ADT).
Found 193021 objects, verifying 15, completed 132922 objects remaining 3h52m50s (ETA 2021-07-26 14:50:39 ADT).
Found 193021 objects, verifying 15, completed 132924 objects remaining 3h52m56s (ETA 2021-07-26 14:50:49 ADT).
Found 193021 objects, verifying 15, completed 132925 objects remaining 3h52m59s (ETA 2021-07-26 14:50:53 ADT).
```
The ETA is still increasing monotonically as the verification progresses through the objects, which is a bit odd, I would expect it to stay relatively the same, or move around a bit.

Also, I just noticed something, the format of the message seems to be:
```
Found {N} objects, verifying {nproc}, completed {M} objects remaining {T} (ETA XXX).
```

Is it supposed to be the following?
```
Found {N} objects, verifying {nproc}, completed {M} objects, remaining {N-M} objects, elapsed time {T}, (ETA XXX).
```
This makes more sense as the time being displayed (`HH h MM m SS s`) appears to be elapsed rather than remaining time.

**Comment by jkowalski** [comment]
You're right, there was a bug there. Made PR to fix it.
