### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by ChromoX** [kopia/kopia#1233]
Hello. I've been a user of borg + rclone for years and have recently found Kopia. It looks like a really great solution to backups I'd like to switch to.

I first attempted to use `kopia-ui` on Debian. My repository type is `Filesystem`. I attempted to simply backup my `$HOME` which is ~400GB. During this backup within a few minutes `kopia` proceded to use my entire systems memory spilling over into the swap.

Looking at the logs the only thing weird that I noticed was a line that said(Not sure if it matters):
> /home/user is not under /home/user

After the memory issues I had above I attempted to do the same thing via the command line. I set parallel=4 to attempt to slow down the data coming into memory and it seemed to help, but the problem still ended up happening before the end of the backup. 

After doing a little more investigation I noticed that the amount of memory I'm using is the difference between the hashed files, and the uploaded files. I'm taking a guess that because I'm saving my snapshot to a slower I/O device than the source that `kopia` is simply getting behind and doesn't throttle/back-pressure at all?

Any help would be greatly appreciated.

EDIT: Setting parallel=2 allows the backup to finish, but still uses a large amount of my RAM. I guess this is intended behavior? Setting parallel to the right number for your I/O is necessary?

EDIT 2: After using kopia the memory that's used never gets freed. I have to restart even after `killall` the kopia processes. Anyone have any ideas?

**Comment by nergdron** [comment]
testing out kopia now as well. I've got a gigabit pipe, and to keep that utilized I need a very high `--parallel` setting on creating snapshots. however, then the `kopia` memory usage goes through the roof. at a modest `--parallel 16` (number of cpu cores in this box), `kopia` sets at around 8GB of RAM used. this gets me about 300-400 Mbit/s. to really max out my pipe, `kopia` uses so much RAM it gets OOM killed by the kernel.

**Comment by jkowalski** [comment]
OS-reported memory may not be accurate here, since Golang uses garbage collection, but the memory usage has been a problem nonetheless. I will investigate this, I suspect we have some unbounded queue somewhere and putting a limit there should fix the issue.

**Comment by ChromoX** [comment]
Hey @jkowalski been using this backup tool for the past few days and it's been working great other than the memory issues. The feature set is great! Thanks for your time and effort on this project.

Here is some extra information hopefully it can help you narrow down where the issue might be coming from:
I run `kopia-ui` so a `kopia server` is always running. That server seems to never give up Virtual Memory. Resident memory seems to change quite dramatically during a snapshot, but the Virtual Memory never seems to go down. Currently a process I've had running for 3 days and have completed two snapshots to a remote location has almost 90G in virtual memory and only about 3G in resident memory. I assume some of the resident memory is caches.

If you need any information or need me to try something I'm more than wiling as I have not fully switched from my old backup process to `kopia` yet.

**Comment by nergdron** [comment]
@jkowalski: yeah, I made sure to use the Linux reported resident usage. and I'm definitely getting OOM kills on a system with ~8GB of RAM free. so it does seem to be reasonably accurate.

**Comment by jkowalski** [comment]
I did some digging into the issue and it appears to be related to internal memory fragmentation, Kopia is allocating lots and lots of  byte slices of various sizes which are creating holes in the heap. The fix (rather large as it turns out) would be to refactor all code so that instead of allocation, the caller-provided buffer is used (and reused without allocation) wherever possible. I'll see if I have some time to work on it this weekend.

**Comment by jkowalski** [comment]
Note to self: `ignorefs` appears to be using significant memory. When snapshotting kopia working directory (files:137461 dirs:19752), the RAM difference is 430MB vs 490MB (without/with ignorefs wrapper).

**Comment by jkowalski** [comment]
Another big memory hog is checkpointing during upload - it consumes another 50-60 MB, without ignorefs and checkpointing, the upload memory consumption goes from 490MB to 380MB

**Comment by jkowalski** [comment]
Another detail - the allocated bytes are only ~80MB (which is somewhat expected), but the OS heap usage is ~400MB, suggesting large amounts of fragmentation.

**Comment by ChromoX** [comment]
The large memory usage I am seeing I just noticed is only happening if I snapshot from the `kopia-ui`. If I snapshot using the CLI there are not really memory issues.

I was taking a look around. Could it be related to keeping the logs in memory in the `kopia-ui`? I think I also noticed it slowly clearing the memory once the snapshot was done. Almost like the Go GC(or maybe the browser process?) has a limit on how much it will clear at once?

![kopiauimemusage](https://user-images.githubusercontent.com/542070/130568954-629e3a94-3807-42fd-b801-4c65542960a9.png)

**Comment by julio-lopez** [comment]
@jkowalski It may be worth looking at the client - repo server path. This may be in the RPC handlers.

**Comment by cristihcd** [comment]
Adding to this. 

Using kopia server on Windows (webui opened) and 1 kopia client (via webui) on debian.

Trying to snapshot 107GB folder with many small files (350000) on debian (via webui), connected to kopia server on Windows.

After 5 minutes, the memory usage on Windows is ~64GB (kopia.exe). On Linux, 2.8GB. I stopped kopia client on linux and kopia.exe memory usage in Windows is slowly decreasing to ~48GB after 10 minutes.

I left everything in the current state (incomplete snapshot) to see if we can analyze this behaviour more (maybe some memory profiling in go).

Versions: `20210902.0.213808 build: 1077cc24d333767a1c6b3a175eadbfd08e0b9d1f from: kopia/kopia`

```
kopia snapshot estimate

Snapshot includes 347454 file(s), total size 107.2 GB
   10 MB ...100 MB:    1609 files, total size 26.6 GB
   1 MB  ... 10 MB:   17779 files, total size 55.5 GB
   100 KB...  1 MB:   59549 files, total size 18.6 GB
   10 KB ...100 KB:  153818 files, total size 6.1 GB
   1 KB  ... 10 KB:   74428 files, total size 352.4 MB
   0 B   ...  1 KB:   40271 files, total size 32.9 MB

Snapshot excludes no files.
Snapshot excludes no directories.
```

**Comment by jkowalski** [comment]
I'll try to prioritize the fix for 0.9.0.

**Comment by cristihcd** [comment]
I tested this again with kopia server running on debian linux. On a virtual machine with 32GB RAM, kopia server memory usage slowly goes up to maximum and then is killed (OOM).

kopia server start cmd: 

```
kopia --config-file=./kopia/config/repository/repository.config server start \
--tls-cert-file=./kopia/config/kopiaserver.cert \
--tls-key-file=./kopia/config/kopiaserver.key \
--address x.x.x.x:51515 \
--server-username=... --server-password="..."
```
After 10 minutes of running snapshot kopia server is killed.

**Comment by pointlessone** [comment]
I started using Kopia a few weeks ago and started getting OOMs not too long after that.

I'm using Kopia on a medium-sized VPS with 4 GB of RAM. I back up about 40GB of data.

`kopia blob stats`:
```
Count: 3929
Total: 52.1 GB
Average: 13.3 MB
Histogram:

        0 between 0 B and 10 B (total 0 B)
        3 between 10 B and 100 B (total 42 B)
       90 between 100 B and 1 KB (total 18.2 KB)
      585 between 1 KB and 10 KB (total 2.5 MB)
      116 between 10 KB and 100 KB (total 5 MB)
      176 between 100 KB and 1 MB (total 85.3 MB)
      686 between 1 MB and 10 MB (total 2 GB)
     2273 between 10 MB and 100 MB (total 50 GB)
```

`kopia content stats`:
```
Count: 976274
Total Bytes: 52.8 GB
Total Packed: 42.2 GB (compression 20.1%)
By Method:
  (uncompressed)         count: 439453 size: 32.5 GB
  lz4                    count: 536821 size: 20.3 GB packed: 9.7 GB compression: 52.3%
Average: 54.1 KB
Histogram:

        0 between 0 B and 10 B (total 0 B)
     9598 between 10 B and 100 B (total 576.5 KB)
   263406 between 100 B and 1 KB (total 118.2 MB)
   461187 between 1 KB and 10 KB (total 1.8 GB)
   204009 between 10 KB and 100 KB (total 4.5 GB)
    27386 between 100 KB and 1 MB (total 8.2 GB)
    10688 between 1 MB and 10 MB (total 27.5 GB)
        0 between 10 MB and 100 MB (total 0 B)
```

OOM report from the kernel:
```
Tasks state (memory values in pages):
[  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[...]
[   2227]     0  2227   640194   379572  3870720        0             0 kopia
[...]
oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=kopia,pid=2227,uid=0
oom_reaper: reaped process 2227 (kopia), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by jkowalski** [comment]
290MB sounds about right for v0.9 - it is still quite a lot and we'll be driving this RAM usage down in future releases - at this point Kopia allocates too many tiny memory fragments frequently and golang GC can't keep up. We have ideas for getting rid of most all allocations in the hot path. 

Due to its nature, compression would typically be an important contributor to memory consumption and unfortunately there isn't much that can be done here, short of picking a different compression algorithm or disabling it.

One way to typically resolve memory pressure is to slightly slow down snapshots by reducing upload parallelism (--parallel=2 or --parallel=4 may help, in particular if you have a high-core-count machine and default parallelism is too high). This will allow GC to free memory faster.

This sheet has more raw data about current performance numbers:

https://docs.google.com/spreadsheets/d/1MYPr6MZ0111ta2SXJUnwzQvhyejmOy6AQUWF6jQL3Ig/edit#gid=0

**Comment by ZoomRmc** [comment]
Just got OOM crash on `snapshot create`.
Kopia 0.9.5, Windows, 16GB RAM, `zstd-best`, `--parallel 6`, source size of ~ 100GB, RClone target.

[trace.txt](https://github.com/kopia/kopia/files/7575023/trace.txt)

**Comment by nh2** [comment]
@jkowalski In https://github.com/kopia/kopia/issues/2216#issuecomment-1193024372 `--max-parallel-file-reads` was not the case of OOM: It OOMs even with ``--max-parallel-file-reads 1` and even when I run `kopia policy set` which triggers `Looking for active contents...`.

This immediately spikes to 128 GB resident RAM usage and gets killed.

There seems to be something holding to large amounts of memory during that step.

It also happens with a resuming `snapshot create`.

This currently renders kopia unusable for me, as I cannot finish the backup of 200M files.

**Comment by nh2** [comment]
> This immediately spikes to 128 GB resident RAM usage and gets killed.

I suspect this might be explained by https://github.com/kopia/kopia/issues/1308#issuecomment-933001585:

> currently maintenance needs to ultimately load all content IDs into memory to determine which of them are live. That's again something that can be improved over time, but right now there's no workaround short of adding crazy amounts of RAM.

**Comment by nh2** [comment]
Is it intende dthat the bot closes this issue?

It seems sensible to have one that tracks general memory usage, while the linked issues were for maintanence specifically.

**Comment by ddorando** [comment]
Bumping this. It really doesn't make sense to close this IMHO...

**Comment by RobKenis** [comment]
Wondering if this issue is still relevant. I am seeing high memory usage when restoring Velero backed by Kopia: https://github.com/vmware-tanzu/velero/issues/8582
