### ISSUE TITLE
kopia snapshot verify time estimate is pessimistic

### ISSUE THREAD

**Issue by eras** [kopia/kopia#1234]
Recently I was running verify against some snapshots and at the end of the invocation

`kopia snap verify --parallel=196 --directory-id=kacf8bed8127f27f86e185d6c01510b7e --verify-files-percent=100`

(yes, parallellism is quite high, but it seems my low-end ceph-based S3 backend enjoys having high parallellism)

At the end of the output I saw this:

```
Found 127446 objects, verifying 3, completed 127443 objects remaining 395891h54m22s (ETA 2066-10-05 20:06:09 EEST).
Found 127446 objects, verifying 2, completed 127444 objects remaining 603808h51m37s (ETA 2090-06-25 01:12:47 EEST).
Found 127446 objects, verifying 1, completed 127445 objects remaining 1216262h14m35s (ETA 2160-05-07 22:39:49 EEST).
Found 127446 objects, verifying 0, completed 127446 objects.
```

As you can see, the final ETA is highly pessimistic :) and it was climbing the whole time. I don't know how long the objects took time to manage individually, but the complete check for those 437 GB of objects took 9h 42m.

About 1000 lines earlier (at the extent of my `screen` buffer) there were values like:
```
Found 127446 objects, verifying 195, completed 123847 objects remaining 5201h20m3s (ETA 2022-03-11 23:24:49 EET).
Found 127446 objects, verifying 195, completed 123849 objects remaining 5201h37m45s (ETA 2022-03-11 23:42:33 EET).
Found 127446 objects, verifying 195, completed 123850 objects remaining 5202h5m19s (ETA 2022-03-12 00:10:09 EET).
Found 127446 objects, verifying 195, completed 123853 objects remaining 5202h29m50s (ETA 2022-03-12 00:34:42 EET).
Found 127446 objects, verifying 195, completed 123856 objects remaining 5203h1m26s (ETA 2022-03-12 01:06:20 EET).
Found 127446 objects, verifying 195, completed 123857 objects remaining 5203h32m31s (ETA 2022-03-12 01:37:28 EET).
```

Which, in retrospect, also seemed highly pessimistic. Actually these giant ETAs have made me stop some check operations, but I guess I could have just tried how long they take..

Perhaps the bug is more pronounced the higher value of parallel operations is?

**Comment by jkowalski** [comment]
This was fixed in latest unstable builds. Can you try that ?

**Comment by jkowalski** [comment]
Possible dupe of #1212

**Comment by eras** [comment]
Yes, latest build fixes this. Thanks!
