### ISSUE TITLE
How to delete a backup-job: all snapshots that belong to a backup and stop future backups?

### ISSUE THREAD

**Issue by zupa-hu** [kopia/kopia#1238]
Hi Jarek!

This project is truly incredible. Hats off and thank you so much for making it available for everybody! I'm telling everyone I can about it.

One thing I can't wrap my heads around is how to remove backup-jobs. I mean, all of these, not just one of them:
![image](https://user-images.githubusercontent.com/4324534/128611030-0cbf14c8-b41b-458d-8767-b5dc529e348f.png)

Now, I might be getting this wrong but I have the suspicion there is a conceptual unclarity here. The following command creates an object that the documentation calls a snapshot:

    kopia snapshot create /path

But the following command deletes something else:

    kopia snapshot delete {MANIFEST ID}

It seems to me there are 2 concepts mixed here, the "backup-job" and the "snapshot".

So my main question would be, how do I delete a "backup-job", with all the snapshots identified by unique manifest IDs, and also prevent the creation of future snapshots?

Many thanks!

**Comment by jkowalski** [comment]
This is currently quite confusing. Snapshots are automatically created for directories that have prior snapshots :)

So to prevent /path from being snapshotted again, you need to delete all manifests for those snapshots.

Try:

```
kopia snapshot delete ka801... kfaca.... kc21...
``` 

This should do the trick (you need to run it with `--delete` to confirm deletion).

**Comment by zupa-hu** [comment]
Aaaah, now I understand. **Thanks a lot, it worked!**
(FYI in case you want to improve onboarding, this was the most puzzling part for me from the very beginning.)

----

For anyone in my shoes, one caveat was that the identical snapshots were hidden but it turns out the

    kopia snapshot list --json

command returns all of them, so then it's just a matter of a little text editing.

**Comment by azukhatri** [comment]
Request, if any one explain in simple language as I am not fluent in command prompt and use UI for Kopia
