### ISSUE TITLE
Allow specifying the hostname during snapshot creation

### ISSUE THREAD

**Issue by julio-lopez** [kopia/kopia#124]
It should be possible to specify/override the OS hostname during snapshot creation.

Scenarios where this is useful or even required include:
* Cloud-native (containerized) platforms, such as Kubernetes, where the hostname is not stable, and may change across different executions of a Pod / container associated with the same "logical volume" (PVC/PV in k8s terms)
* Mobile clients, such as laptops, that may get their hostname assigned via DHCP and thus the hostname may change depending on configuration, network connection and so on.

This could be implemented via an optional flag to the `snapshot create` command.

**Comment by jkowalski** [comment]
Take a look at `getHostName()` in `cli/command_snapshot_create.go` - should be pretty trivial to plumb through a flag.

**Comment by jkowalski** [comment]
While at it we may want to support overriding username.
