### ISSUE TITLE
Debian GNU/Linux 11 (bullseye): Impossible to install kopia-ui due to missing dependency libappindicator3-1

### ISSUE THREAD

**Issue by Semelovich** [kopia/kopia#1241]
Linux installation using APT (Debian, Ubuntu) isn't working in Debian 11 Bullseye because libappindicator3-1 can't be installed, it's not in the official repositories.

sources.list:

###### Debian Main Repos
deb http://deb.debian.org/debian/ bullseye main contrib non-free
deb-src http://deb.debian.org/debian/ bullseye main contrib non-free

deb http://deb.debian.org/debian/ bullseye-updates main contrib non-free
deb-src http://deb.debian.org/debian/ bullseye-updates main contrib non-free

deb http://deb.debian.org/debian-security bullseye-security main
deb-src http://deb.debian.org/debian-security bullseye-security main

**Comment by jkowalski** [comment]
Can you try now? I upgraded electron to latest version and verified that UI launches on Ubuntu 20.4.3.

**Comment by jkowalski** [comment]
That is `kopia-ui` from `unstable` channel.

**Comment by savchenko** [comment]
`libappindicator3` is superseded by `libayatana-indicator3`
Ref. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037

**Comment by jkowalski** [comment]
This appears to be an upstream bug in electron builder, many other UI tools are similarly affected.

See this one for a possible workaround:

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1975#issuecomment-899256569

**Comment by ZephOne** [comment]
Had the same problem so I use the workaround :

> This appears to be an upstream bug in electron builder, many other UI tools are similarly affected.
> 
> See this one for a possible workaround:
> 
> [RocketChat/Rocket.Chat.Electron#1975 (comment)](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1975#issuecomment-899256569)
And in my terminal, when I try to launch it, here what happens :

```
❯ kopia-ui
17:35:41.592 › APPIMAGE env is not defined, current application is not an AppImage
```
