### ISSUE TITLE
Kopia, next release? Donations?  

### ISSUE THREAD

**Issue by jaxjexjox** [kopia/kopia#1248]
Hello,

Sorry for posting here but I would get the most visibility.

Over 5 months ago, I investigated Windows based solutions for backing up a machine, to a cloud repository (B2 in my case)
Many other programs that have a bigger reputation and been around much longer, had a plethora of fundamental design issues which made them awkward to work with, ugly, unreliable, etc.

I then found Kopia and to my surprise found it was the best solution available, but still fell shy in a couple of very small areas.
There hasn't been a release in 4 months, I'm curious if there's a (very) rough eta on when we might see one?

Secondly, I'm surprised to not see such a good program, run some kind of patreon or at least a "click here to donate" button? The website is actually quite nice looking, but there's no way to support the team.

The other packages have problems you've solved. Finding a reliable solution which works well, is shockingly difficult and you're all so close.   Please consider taking some kind of donations or running a patreon.  It's frustrating to try 2, 3 maybe even 4 or so solutions and all of them are lacking in some particular way.

Thanks for the hard work.

**Comment by xxxliqu1dxxx** [comment]
I agree - awesome tool!

**Comment by jkowalski** [comment]
Thanks, the v0.9 release is almost ready, still finishing some testing and working on stabilizing new index formats. I'll try to cut first release candidate in about a week.

I'm specifically not looking to make money off Kopia, it's a side project and hobby and I don't want to mix it up with my day job.

Instead of donations, I'd love if folks could contribute bugfixes, documentation and spread the word

**Comment by jaxjexjox** [comment]
Sure but you have to realise there is a subset of us nerds who just can't code.  I can submit a half decent bug report, (I've already done one) but I can't code to save my life.

I understand you want to do the right thing but it baffles me if you're doing well to not make some money.  I'm not suggesting full capitalism and milk the users, but a donation system allows for a great project to continue momentum.  Especially donation, over Patreon where I feel you've got obligations.

Look at RPCS3 for example, huge amount of people contributing to that PS3 emulator and it's a well made product that does cool things.    I like cool open source things, it's why I'm here.

P.S while I have your ear and I think you're already aware of this, the key issue for Kopia, for me was primarily file selection, file exclusion and managing what is and isn't backed up across a system.      
Keep up the good work.

**Comment by xxxliqu1dxxx** [comment]
RC1 is out :)
