### ISSUE TITLE
[FR] switch to cgofuse and support FUSE on windows

### ISSUE THREAD

**Issue by riedel** [kopia/kopia#1249]
[cgofuse](https://github.com/billziss-gh/cgofuse) provides in interoplayer for different fuse implementations. Would be great to use this fuse layer instead of the IMHO rather shaky windows webdav client and to expose the whole filesystem on localhost via http. Ideally a fallback for webdav would be default if fuse cannot be initialized (e.g. if winfsp is not installed).

**Comment by githubbapoopa** [comment]
+1
Win10: webdav mounts via kopiaui freeze file commanders like Totalcommander and mounts have then to be manually unmounted once kopia ui is closed. VERY unstable!!! rclone mounts via winfsp on the other hand work fine and reliable.

Any news on this?
