### ISSUE TITLE
Idea: CEPH RBD

### ISSUE THREAD

**Issue by jdmoravec** [kopia/kopia#1252]
Any thoughts of extending this to CEPH RBD?

**Comment by icepic** [comment]
If you can have kopia accept data from stdin (in some fashion) then perhaps one could snapshot the RBD and then dump that snapshot into kopia, and let kopia do the dedup/compression on the image and then releasing the snap, but extending kopia itself to talk ceph will probably make it very large and unwieldy, as well as hurt all platforms where you can't get it to easily talk ceph but where kopia itself works right now.

**Comment by beddari** [comment]
Interesting idea! Do we have any more comments about how to start a basic design for this?

I am thinking about how we could use rbd export (images, snapshots) as a data source without having to go via an intermediate dump-to-file step. stdin was mentioned?

Does anything similar exist within kopia today?

**Comment by beddari** [comment]
I don't know, but ... https://docs.ceph.com/en/quincy/man/8/rbd-fuse/ ?
