### ISSUE TITLE
Ansi Escape codes not working by default in windows -> output mangeled

### ISSUE THREAD

**Issue by Hoffenbar** [kopia/kopia#1287]
I just recognized that commands like `kopia snapshot list` produce output that obviously isn't intended:
```
matthiasu@desktop-ai70a0o:C:\Users\matthiasu
←[91m  2021-05-01 15:02:33 CEST k1496440c82705702fe2fe12c92cd6b4b 22.3 MB drwxrwxrwx files:84 dirs:1 errors:3 (latest-5,daily-4)
←[0m  + 1 identical snapshots until 2021-05-02 20:12:17 CEST
←[91m  2021-05-09 19:16:56 CEST k2ef22f4fec5ebc0e7fe4118eeace0ba7 22.3 MB drwxrwxrwx files:85 dirs:1 errors:3 (latest-3,weekly-2,daily-2)
←[0m←[m  2021-05-15 11:53:45 CEST kb780cb879c66e60fbffa64a45498c05f 0 B drwxrwxrwx files:0 dirs:1 (latest-2)
...
```
This is because Windows versions after Win 9x (which was MSDOS based) never supported ANSI ESCAPE Control codes. This was a nuisance since decades, since MSDOS already supported ANSI Escape sequences through loading the driver ANSI.SYS.
However, this was only true until some newer versions of windows 10. Microsoft has discovered after 25 years that this is a missing feature :-)
The crux is, though, that the support is by default _turned off_ and either has to be enabled via a registry change or by an API call of a program. Again very mysterious - why isn't this configurable via a dialog setting somewhere? Oh, I love MS!

See here:
* https://qastack.com.de/superuser/413073/windows-console-with-ansi-colors-handling#
* https://docs.microsoft.com/de-de/windows/console/console-virtual-terminal-sequences

0.9.0-rc1 build: 8b2b91f9f9c918a5f0640a53ca4f30397a920da3 from: kopia/kopia

**Comment by jkowalski** [comment]
Can you try setting `KOPIA_DISABLE_COLOR` environment to `1` or pass `--disable-color` flag?

**Comment by xxxliqu1dxxx** [comment]
> 
> 
> Can you try setting `KOPIA_DISABLE_COLOR` environment to `1` or pass `--disable-color` flag?

doing --disable-color did remove the ←[0m←[m stuff

**Comment by Hoffenbar** [comment]
Couldn't test again right now because yesterday I deleted all my archives.
If the env var would work, it would be ok.
But perhaps the program could in a later version set the required flags by itself.

**Comment by xxxliqu1dxxx** [comment]
> 
> 
> Couldn't test again right now because yesterday I deleted all my archives.
> If the env var would work, it would be ok.
> But perhaps the program could in a later version set the required flags by itself.

 --disable-color works as a workaround, but I believe it's regression since I do not believe it was not doing that in 0.8.4.

**Comment by jkowalski** [comment]
Yeah, looks like a regression, i'll fix it for the next RC.
