### ISSUE TITLE
Can't restore properly from a new 0.9.0-rc1 repository

### ISSUE THREAD

**Issue by oderwat** [kopia/kopia#1294]
I updated all clients and the server to 0.9.0-rc1 and at the same time, I added another kopia server on another machine. The repository there was created by the release candidate. Currently, we use both kopia-servers as the target for identical backups (like running it twice, once for each destination server).

Using the new server I suddenly get errors like the following and restoration aborts:

```
ERROR: error restoring: restore error: copy file: error creating file: cannot write data to tempfile "/db1/calccache.MYD2958307090": unexpected chunk length 10098702, expected 5049351
```

I noticed that the "unexpected" length seems to be always double what the expected length is when this happens.

This is reproducible on my machine.

When I use the same client and point it to the old (upgraded) server it works without problems.

Other Snapshots (different paths) also work. I double-checked free space too. 

This is running on an Intel Mac. It works for other people in the company (they use M1 Macs).

**Comment by oderwat** [comment]
I deleted the caches and it now works again. I am not sure what happened there. Maybe you have an idea?

**Comment by jkowalski** [comment]
This looks like a real bug, I'll try to reproduce this and fix it for RC2. Please let me know if you can get a reliable repro again so we can try the fix.

**Comment by jkowalski** [comment]
Can you talk about more what happened here - was this for one particular file, several files?

**Comment by jkowalski** [comment]
To test one theory: did you by any chance change the password for this server user on this client?

**Comment by oderwat** [comment]
I think I may have mixed up the cache folders. I made a new repository on the new server. Then I also created a new connection on the client computer. Later I tried to just switch the repo URL in the config on other computer's clients. That worked, so I let two co-workers do just this. They did not have a problem (PWs for their users on the servers are the same). 

I still run with two different config files at the time the error occurred. Now I am not sure what happened. My very first thought was that It might have no space left on one of the operations. So I deleted some files. I didn't get a message but saw that there was just some MB left. This may have something to do with the problem. But after freeing up, it still reported the error. Maybe something in the cache can get "defective" at that point?

I then switched for and back, and on one point, I also just changed my old config file to the new server (URL), then the problem vanished. But as I tried to use the new config file again. I strangely found the exact cache location as in the old config in the new one.

Then I started to move caches to another drive and give them names. This got really messy, and I had to do a lot for and back until I got stuff right (meaningful names for the caches on a particular folder on my fastest "junk" drive). Finally, I have to figure out how to relocate and rename the cache on "connect" or creation (if it is possible yet). While doing this, I even found a local repository not working anymore and found no way to recover it. So I needed to re-create that one.

I for sure did not change the password. I may have reset it to the same value. I also fumbled with the ACLs because I wanted to get the server connection repositories running in the KopiaUI, which I failed at. I had to use an SFTP remote. Using the server never worked out for me. I later deleted the ACLs. They were basically giving my user on this machine read/write access to "everything."

As you may guess, I may have done something really demanding on your software xD.

Sadly I can't go back to this error. This is because I didn't include the caches in backups, and at one point, I deleted all of the old ones.

So as a programmer myself, I guess that if you found a problem that could explain the "doubling" of the value, this probably is the proper fix. I tend to think of the problem not happening during regular use. I hope I didn't waste anybody's time.

**Comment by oderwat** [comment]
> Can you talk about more what happened here - was this for one particular file, several files?

The restore process stopped with that error and leftover partial written files in the destination. It happened in two paths out of 8 different ones which had about 40 snapshots. It still happened after new snapshots were being made (by another client on the server). The restoration always picks the last one automatically.

Maybe for a bit background: The Kopia Server is located on a dedicated server. Our production servers doing flushes and LVM snapshots of the data directory of the MariaDB database and then create Kopia snapshots from them. This happens every hour. Our developers then have a tool that I wrote some time ago which can identify and pick single databases from the snapshots and restore the latest or a point in time to a local directory. After all of the select data Is restored, we restart the local MariaDB server and the developer can work with the "near real-time" state of the databases in production.

**Comment by jkowalski** [comment]
Fix submitted. Will be in next rc this weekend. It's completely plausible that mixing up cache directory caused it.

**Comment by jkowalski** [comment]
Btw the new test I included with the fix fails without the fix and passes with it. So I feel confident this did indeed address the problem.
