### ISSUE TITLE
Kopia-ui: snapshots page change bug when checking duplicates

### ISSUE THREAD

**Issue by YacineSahli** [kopia/kopia#1297]
Small bug when checking to show identical snapshots, going to last pages or other pages and then unchecking "show identical snapshots"

I propose that when checking/unchecking we move back the user to the first page

[](https://user-images.githubusercontent.com/22869682/133664753-9708998a-3fc8-4778-8daa-fd584cd3e6db.mp4)

**Comment by jkowalski** [comment]
Thanks for the report. Fix incoming.
