### ISSUE TITLE
Rclone not working with encrypted configuration file

### ISSUE THREAD

**Issue by amunhoz** [kopia/kopia#1298]
Rclone is not working with encrypted config.
I've defined a environment variable for the file and the password.
RCLONE_CONFIG=/data/rclone/rclone.conf
RCLONE_CONFIG_PASS=pass

It's working fine from the command line in the same environment, when i execute "rclone ls storage:/bucket".
But with Kopia, i get this error:

`Connect Error: INTERNAL: internal server error: unable to start rclone: rclone server failed to start: 2021/09/16 23:37:46 Failed to create file system for " storage:/backups/test": didn't find section in config file`

**Comment by amunhoz** [comment]
Then, i get this error all the time:
`Connect Error: INTERNAL: internal server error: connect error: unable to write format blob: unable to write format blob: error writing blob using WebDAV: unable to complete PutBlob(kopia.repository) despite 10 retries, last error: MOVE kopia.repository.f-3337066551442961397: 403`

It worked once without problems, then i could not get to work again with not much changes at all.

**Comment by amunhoz** [comment]
root@f07b6f98ffec:/data/kopialogs/cli-logs# /apps/rclone/rclone --version
rclone v1.56.0
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.11.0-1016-oracle (aarch64)
- os/type: linux
- os/arch: arm64
- go/version: go1.16.5
- go/linking: static
- go/tags: none

0.9.0-rc1 build: 8b2b91f9f9c918a5f0640a53ca4f30397a920da3 from: kopia/kopia

**Comment by jkowalski** [comment]
Can you provide a step-by-step repro? At first glance you have a stray space somewhere: ` storage:/backups/test`

**Comment by amunhoz** [comment]
I think you can reproduce just by encrypting your rclone configuration and using the environment variable RCLONE_CONFIG_PASS to define the key for that (defining in the dockerfile, in the same sheel wich kopia will be executed...).
Tried the same steps and informations (path for bucket too) without encryption and it works fine.
