### ISSUE TITLE
Verify a file exists in a repo?

### ISSUE THREAD

**Issue by 8BitAce** [kopia/kopia#1348]
Hello,

I've been loving kopia so far.

The only (somewhat minor) gap I've found so far is being able to compare arbitrary files on a host to files in the repo. There's a good chance this is already possible, but I've exhausted my search through the source + docs.

**Use case:**
I currently have a lot of my data duplicated in several places (not in a good way). I'm currently working to consolidate everything onto a home server, which I can then backup to 1 or more places instead of having everything fragmented.
What I've found helpful in this process is to create "file inventories" text files on each host using tools like `rhash` or `rclone md5sum`. That way I know for certain whether the same exact file exists on both hosts, and that I can therefore delete it on one of them.
I haven't yet found a matching option in kopia. From my limited understanding of the architecture, the Object IDs stored in the repo are in a format unique to kopia, correct?

**Preferred solution:**
I'd love if it was possible to include an industry-standard hashsum in the `long` output of `kopia ls`. Preferably something fast like md5.

Hopefully this makes sense..

**Comment by jkowalski** [comment]
It's an interesting feature, but I have to say it would be very slow to compute yet another hash when listing filrds.

What I think might be helpful here (and what might be possible with some effort in Kopia) would be some kind of ability to create snapshots without actually uploading them to the repository, but while still hashing/encrypting/compressing exactly the same way regular upload does.

**Comment by 8BitAce** [comment]
Thanks for the quick reply. Glad it's not an entirely crazy idea :-)

You say "compute while listing". Would it be feasible to calculate and store the hash at backup time on the host instead? Obviously that'd mean it's no longer an indication that the file is properly backed up but rather just a unique identifier.

Ya, I was also thinking about the locally created snapshot as a possible (though less perfect) solution.

Of the newer backup tools I've experimented I've only seen one offer a feature like this. I've seen it brought up on the issue trackers of others, but I think the general consensus is that it's orthogonal to the concept of backups. Personally I think it'd be rather valuable, but certainly not a high priority.
