### ISSUE TITLE
Ignored directories bug

### ISSUE THREAD

**Issue by goldmund256** [kopia/kopia#1353]
As [discussed here](https://kopia.discourse.group/t/trouble-with-ignored-directories/661/2), the current way Kopia handles ignored files and directories is messy and dangerous.

Let's say we are looking at the top of the Kopia repository and see this structure:

├── dir/
│   ├── file1
│   └── file2
├── dir2/
│   └── dir/
├── file3
└── file4

If we set in the policy to ignore ./dir/ then ./dir2/dir/ gets ignored as well. And that definitely should not happen as it may result in an incomplete backup, unbeknown to the user.

There seems to be no option to avoid this bug, other than polluting the system with tens/hundreds of .kopiaignore files which I am definitely not keen on.

I propose that a user should be able to place **absolute paths** of his/her ignored files/dirs into a single file hidden away in $HOME/.config/kopia/ignore_list (following the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)) or other path specified by the user in the policy if desired. This file should contain each absolute path on a new line.

Only by supporting absolute paths one can make sure that solely the intended target is ignored.

If the decision is made to continue supporting relative paths for ignored files/dirs alongside of absolute paths, then Kopia must be able to make a complete list of files/dirs excluded from the backup in order to inform the user and thereby prevent an unintended omission. This attitude, however, requires a very attentive user who periodically checks this list. It would be best to do away with relative paths altogether.

**Comment by lupusA** [comment]
Hi @goldmund256, 

please refer to the guide on the website: https://kopia.io/docs/advanced/kopiaignore/#ignoring-files-and-folders-in-snapshots
IMO the rules are implemented correctly. Ingoring "/dir" also omitts the sub-directories and files. This is the same behaviour as in ".gitignore". 

You can also setup rules to ignore only specific files in your folder e.g. "/file4" or "/dir/file1".

Cheers,
