### ISSUE TITLE
KopiaUI stable auto-updating to RC

### ISSUE THREAD

**Issue by acl1704** [kopia/kopia#1354]
On Windows at least, KopiaUI 0.8.4 popped up a notification stating that 0.9.0-rc4 has been auto downloaded and will be installed on exit. If this is intended behavior for stable to be updated to release candidates, I think it makes more sense for the automatic update process to be limited to stable -> stable or other progression appropriate to the installed series such as RC -> RC.

**Comment by jkowalski** [comment]
The electron updater appears to be downloading the `latest` release, which in this case is RC4. For now it should not be a huge deal since 0.9 is just behind the corner, but we should try to improve the logic for the next release.
