### ISSUE TITLE
KopiaUI: Won't update unless manually restarted during a session

### ISSUE THREAD

**Issue by RavenMacDaddy** [kopia/kopia#1370]
Got a notification that an update had been updated, great I thought, that will get installed the next time I log off or restart the PC.

Except it didn't. 

I restarted my PC several times troubleshooting something else, and I got the same notification every time from UI.

Obviously the expected behavior was for the software to be like "oh yeah, I got that queued up, let me take care of that before starting the app."

**Comment by zyradyl** [comment]
out of curiosity, what OS are you running on? i'll try to look into how the electron updater works and see what's going on there. amusingly, i don't frequently reboot/log out, so i've always just closed and relaunched the app, but you're right, if possible it should install on next launch.
