### ISSUE TITLE
Add ability to only backup over certain (WiFi) networks

### ISSUE THREAD

**Issue by GuardedAirplane** [kopia/kopia#1379]
This would be an implementation of the feature found in the Borg GUI application Vorta where the user can select which networks to allow backups over. This is mostly useful for laptops where some networks might be metered/slow (phone hotspot) or insecure (should not be an issue, but you never know). 

I believe Vorta works by simply matching against the SSID of the network, but more robust methods such as using the MAC address of a router could be cool too.

**Comment by jkowalski** [comment]
This will likely be part of #1519
