### ISSUE TITLE
UNC snapshot of root path not working (#1362)

### ISSUE THREAD

**Issue by YEGrolo** [kopia/kopia#1385]
I was excited to see that this was finally addressed ( #1362 ), however I've downloaded KopiaUI 0.9.0 but this still doesn't seem to be quite there.

Test 1:
1. Start KopiaUI
2. Click **New Snapshot** button
3. In "enter path to snapshot", type or browse to **\\\server\backup**
4. Click **Estimate**

Result:
_Error: internal server error: can't get local fs entry: unable to determine entry type: CreateFile C:\Users\username\server\backup: The system cannot find the path specified_

In this scenario, it is still trying to append the server path to my local user profile path.

Screenshot:
![image](https://user-images.githubusercontent.com/1029207/137259770-754cacc0-fa67-4b00-954b-b6d0965ae42a.png)

Test 2:
As an additional test, I added a \ to the end of the path as such: \\\server\backup\ and clicking **Estimate** 

Result 2:
_Task succeeded after 0s.
Errors: 1_

Clicking **Show Log** reveals the following:
23:44:19.471 | error in .: unable to read directory: open \\\server\backup\backup: The system cannot find the file specified.

In this instance it has doubled up on the share name (backup).
Screenshot:
![image](https://user-images.githubusercontent.com/1029207/137260958-04e4b09a-456a-4b3b-ab80-10a4fdc434dd.png)

Test 3:
Selecting a subfolder of the UNC share: **\\\server\backup\Documents**
Click Estimate.

Result 3:
Estimate is successful, however without being able to select the root path I would need to set up Snapshots for every separate folder in \\\server\backup

My expected result would be for test scenario 1 above to work as it does in test 3 without having to select a subfolder of the share path.

**Comment by jkowalski** [comment]
Also, if you create a snapshot of UNC root using CLI, the UI appears to be functional, just can't add new snapshot paths this way.

**Comment by xxxliqu1dxxx** [comment]
Confirmed, this is working in CLI. Thanks Jarek - I look forward to the UI
fix.
