### ISSUE TITLE
Version 0.9.1 not showing progress while restoration anymore?

### ISSUE THREAD

**Issue by oderwat** [kopia/kopia#1387]
I updated Kopia to version 0.9.1 and suddenly I don't see any progress anymore in my scripts. I have no time to dig into this right now. What was changed?

**Comment by jkowalski** [comment]
Is it any different than in v0.9,0 or is it compared to v0.8.4?

**Comment by oderwat** [comment]
Was different than in v0.9.0. You seem to have fixed it already! Thank you!
