### ISSUE TITLE
Ignore rules not working when action script set KOPIA_SNAPSHOT_PATH

### ISSUE THREAD

**Issue by bob1de** [kopia/kopia#1395]
Hi,

I want to use an action script to atomically snapshot the source path before backup. For that purpose, my before-snapshot-root-action script outputs `KOPIA_SNAPSHOT_PATH=/something`. However, it turns out ignore rules defined in `/something/.kopiaignore` are simply ignored if the snapshot directory was redirected by an action.

The rules work fine when not printing the `KOPIA_SNAPSHOT_PATH=...` from my script, so policy is set up correctly.

Reach out if there's anything I can do to help nailing this down.

Best regards
Robert

**Comment by jkowalski** [comment]
This is a duplicate of #1346. Let's continue over there.
