### ISSUE TITLE
Snapshot migrate --latest-only migrates oldest instead of latest snapshot

### ISSUE THREAD

**Issue by bob1de** [kopia/kopia#1414]
Hi,

Well, the title basically says it all. I was using `kopia snapshot migrate --all --latest-only` and noticed that only the oldest snapshot of each source is migrated.

Thanks for creating and maintaining this super-useful piece of software.

Best regards
Robert

**Comment by xxxliqu1dxxx** [comment]
could it be where the issue is?
https://github.com/kopia/kopia/blob/30ca3e2e6c95ad044039206ba0c36f705cd41c8a/cli/command_snapshot_migrate.go#L292-L297

is s[0:1] picking the first one in ascending order instead of the first one in a descending order?
