### ISSUE TITLE
Include CACHEDIR.TAG files in snapshots

### ISSUE THREAD

**Issue by bob1de** [kopia/kopia#1435]
Hi,

This is a feature request to change Kopia's behavior so that it includes CACHEDIR.TAG files in snapshots. Currently, the contents of a directory are ignored when a valid CACHEDIR.TAG file is present in the directory, which is fine and expected. However, after restoring such a directory from a backup, the CACHEDIR.TAG file is lost and future directory contents will then be backed up by Kopia. Keeping the CACHEDIR.TAG files would preserve the notion of the directory's purpose.

In other backup tools I know (borg and restic), such functionality is either provided by default or can be enabled via CLI flags (borg has `--keep-tag-files`, for instance). Kopia could also do it by default or add a policy option, which I not really consider to be necessary actually.

Thanks for considering.

Best regards
Robert

**Comment by RayZ0rr** [comment]
Has this feature been implemented in kopia now?

I also think it's weird for the backup tool to not include the `CACHEDIR.TAG` inside the folder and just the empty folder.
