### ISSUE TITLE
Publish KopiaUI as `arm64` and `armhf` deb

### ISSUE THREAD

**Issue by darkdragon-001** [kopia/kopia#1448]
Please also build and publish the **UI** as `arm64` and `armhf` deb package. Thanks!

**Comment by jkowalski** [comment]
@darkdragon-001 I've just added arm64 build, it should be published to https://github.com/kopia/kopia-test-builds/releases shortly, can you test it out?

**Comment by jkowalski** [comment]
I verified that KopiaUI works on latest Raspberry PI OS (armhf)

**Comment by darkdragon-001** [comment]
Thanks for your packages! I added it to the Flatpak on Flathub on flathub/io.kopia.KopiaUI#6! Can you test it out on your RPI as well?
