### ISSUE TITLE
Expose value of `--log-level` to action scripts

### ISSUE THREAD

**Issue by bob1de** [kopia/kopia#1449]
Hi,

Just one more addition from my side to the great action scripts:

The console log-level` could be exposed to action scripts so that they can also honor the user's choice. Probably something like

    KOPIA_LOG_LEVEL={debug|info|warning|error}

Together with #982, this would allow Kopia to be easily used in cronjobs. Currently you have to do `> /dev/null 2>&1` to avoid being emailed due to the status bar, but then you also loose any error messages.

What do you think?

Best regards
Robert

**Comment by leleogere** [comment]
Why has this been closed? The scripts I want to run can be quite complex, and I absolutely need to log some information to see what's happening (especially when something is not working as expected). I would love the ability to forward stdout/err from my actions to kopia's stdout/err.
