### ISSUE TITLE
cannot edit policy in kopia container

### ISSUE THREAD

**Issue by devzwf** [kopia/kopia#1453]
when tried to edit policy
```
# docker exec -t <container ID> /app/kopia policy edit [target]
Editing policy for [target] using external editor...
ERROR unable to launch editor: error launching editor: error running editor command: exec: "vi": executable file not found in $PATH
```

**Comment by jkowalski** [comment]
This is currently not supported because Docker container only contains the kopia binary and no other programs. 

You can edit policies using the UI in the container (kopia server start launches the UI) or by running kopia policy set or edit on the host.

**Comment by devzwf** [comment]
Thanks for the answer... and completly understood the fact of the container contain ony kopia binary.
unless i did not get it yet, i found no way in the UI in the container to define the "snapshot-time"
i can clearly see the "Snapshot Interval"

**Comment by jkowalski** [comment]
You're right, there's no way to do it now in the UI. PRs are welcome.
