### ISSUE TITLE
KOPIA_LOG_DIR not respected for setting log location

### ISSUE THREAD

**Issue by Neurrone** [kopia/kopia#1454]
I'm using Kopia 0.9.0 build: 6472d171d428fe723778e47e54f66bc233be1a65 from: kopia/kopia                                                              on Linux.

Even though my backup script has `export KOPIA_LOG_DIR=/some/path` before invoking Kopia, it sstill writes logs to `~/.cache/kopia`. I see 2 folders, cli-logs and content-logs.

If there's another way of controlling log location, I would love to know.

**Comment by xxxliqu1dxxx** [comment]
> I'm using Kopia 0.9.0 build: [6472d17](https://github.com/kopia/kopia/commit/6472d171d428fe723778e47e54f66bc233be1a65) from: kopia/kopia on Linux.

Can you try with the latest 0.9.4?

**Comment by Neurrone** [comment]
Same behaviour in 0.9.4.

**Comment by jkowalski** [comment]
I can't repro this, can you provide step-by-step instructions for reproducing the issue?

**Comment by Neurrone** [comment]
In a shell script,

```sh
export KOPIA_LOG_DIR=/some/path
kopia snapshot create ...
```

I observe that running the script causes the default log path being written to, `/var/services/homes/Dickson/.cache/kopia`.

When using kopia without any arguments to print its help, I see this after setting the `KOPIA_LOG_DIR` variable:

```sh
> kopia | grep -i log
      --log-file=LOG-FILE     Override log file.
      --log-dir="/var/services/homes/Dickson/.cache/kopia"
      Directory where log files should be written.
      ($KOPIA_LOG_DIR)
```

I'm not sure if setting the environment variable should change the output of this help text to reflect the path being used as well if it is working.
