### ISSUE TITLE
Issues implementing documented VSS snapshots with actions

### ISSUE THREAD

**Issue by alexwh** [kopia/kopia#1456]
Running Windows 10 21H1 19043.1288 with language for non-unicode programs set to Japanese, pwsh version 7.1.4.

Following the instructions written by @CrendKing in #1319 I encounted a couple of issues. First of all, without setting KopiaUI.exe to run as admin for all users, the VSS creation failed, and the script exited 1 [here](https://github.com/CrendKing/kopia/blob/a9b68d664d2da90894d9634d48d5bdc16d34146c/site/content/docs/Advanced/Actions/_index.md?plain=1#L146-L149).

As a side effect setting the executable to always run as admin seems to have broken the Launch at Startup option. Not sure if that should be its own issue, as I don't know if there's a way around it.

Secondly, the [`kopia policy set`](https://github.com/CrendKing/kopia/blob/a9b68d664d2da90894d9634d48d5bdc16d34146c/site/content/docs/Advanced/Actions/_index.md?plain=1#L167-L168) lines should use double quotes instead of single, as default cmd.exe does not seperate the arguments properly otherwise:
![image](https://user-images.githubusercontent.com/1723612/139542966-27223c15-c072-46a4-a9ca-6fcc55fed229.png)

Thirdly, executing the `kopia policy set` command outside of the directory I was trying to snapshot (C:\\) would result in setting a policy on the current directory:
![image](https://user-images.githubusercontent.com/1723612/139542950-f3932f00-be45-4b88-ad09-2b5a433407a0.png)

Finally, the issue I'm left with after making the above changes is the following error:
![image](https://user-images.githubusercontent.com/1723612/139542684-c8028fe0-5ccf-4fcc-a4f2-685f082eb0ce.png)

The link is there, and points to the correct location. There seems to be a fairly long delay while the script creates the shadow volume and symlink. I have tried sleeping just before echoing the `KOPIA_SNAPSHOT_PATH` and removing the trailing slash from `$sourcePath` - neither made a difference. Any guidance further on the issue would be appreciated.

**Comment by CrendKing** [comment]
Let's break down the issues.

1. It is true the creation of shadow copy requires admin. I should've put a `#Requires -RunAsAdministrator` line at the top. To elevate the PowerShell to admin, I believe it always must start a new process, which would break the script. We can explore elevating the script process from the Go code (instead of elevating the whole KopiaUI process, which introduces unwanted side effects).
2. The single quote was my bad. I fixed my mind on "all code are executed under PowerShell". Will fix.
3. About the directory. Might be bug? Can you try again with a `--config-file=` argument?
4. The double `\` at the end is not intended. I think something went wrong. The easiest is to run the script manually from pwsh and check output for each step. Could you help me do that?

**Comment by CrendKing** [comment]
For 1, I came up with a script that can self-elevate. Could you please test?

```powershell
$ErrorActionPreference = 'SilentlyContinue'

# use Kopia snapshot ID as mount point name for extra caution for duplication
$mountPoint = "${PSScriptRoot}\${env:KOPIA_SNAPSHOT_ID}"
$snapshotPathFile = "${PSScriptRoot}\${env:KOPIA_SNAPSHOT_ID}_path"

if (([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] 'Administrator')) {
    $sourceDrive = Split-Path -Qualifier $env:KOPIA_SOURCE_PATH
    $sourcePath = Split-Path -NoQualifier $env:KOPIA_SOURCE_PATH

    $shadowId = (Invoke-CimMethod -ClassName Win32_ShadowCopy -MethodName Create -Arguments @{ Volume = "${sourceDrive}\" }).ShadowID
    $shadowDevice = (Get-CimInstance -ClassName Win32_ShadowCopy | Where-Object { $_.ID -eq $shadowId }).DeviceObject
    if (-not $shadowDevice) {
        # fail the Kopia snapshot early if shadow copy was not created
        exit 1
    }

    cmd /c mklink /d $mountPoint "${shadowDevice}\"
    "KOPIA_SNAPSHOT_PATH=${mountPoint}${sourcePath}" | Out-File $snapshotPathFile
} else {
    Start-Process $MyInvocation.InvocationName -Verb RunAs -Wait
}

Get-Content $snapshotPathFile
Remove-Item $snapshotPathFile
```

**Comment by alexwh** [comment]
Thanks for your detailed response.

re: 1 - I implemented the self-elevation script and the resulting behavior was the backup starting and running normally, but against the true path, not the shadow volume. Watching the process tree in Process Hacker showed this happen:
![image](https://user-images.githubusercontent.com/1723612/139587564-8a68e4cf-f0ea-4587-abad-07383b9cfca6.png)
pwsh.exe did not relaunch with elevation (the last column). I assume the backup runs normally because the script does not echo a KOPIA_SNAPSHOT_PATH when not elevated.

re: 3 - this was my mistake - running `kopia policy set C:\` instead of `kopia policy set "C:\"` worked as expected. More cmd.exe jank I suppose.

re: 4 - Running pwsh as a normal user and just executing the Start-Process line did nothing - I remained a regular user. Back to point 1 - if this did work, wouldn't Kopia see the first process exiting to reelevate as a success, and not wait for the completion of the elevated process?
Running the remainder of the script in a pre-elevated pwsh instance with the env vars replaced with dummy values had the following result:
![image](https://user-images.githubusercontent.com/1723612/139588087-fffee8b3-2b97-408e-84f0-514f566d38f5.png)
The link was initially created in the root of C:\. so I changed the link manually to the current directory. This doesn't happen when ran as a script since `$PSScriptRoot` is populated. After that, the shadow volume is correctly created and linked to.

**Comment by CrendKing** [comment]
> Maybe have the initial script block until the file is filled while launching the elevated version in the background would work?

I noticed a problem in my previous script and updated it. Could you try again?

**Comment by alexwh** [comment]
I removed the ErrorActionPreferences line and ran the updated script with dummy env vars, with the following result:
![image](https://user-images.githubusercontent.com/1723612/139605145-4c20ef0f-48e3-4988-a617-505ad13f2cac.png)

**Comment by CrendKing** [comment]
Interesting. I forgot not everyone associates .ps1 with pwsh. Please change the `Start-Process` line to `Start-Process 'pwsh' $MyInvocation.MyCommand.Path -Verb RunAs -Wait`. I hope pwsh is reachable in PATH.

**Comment by alexwh** [comment]
Yep, pwsh is in PATH. Output triggered from KopiaUI:
![image](https://user-images.githubusercontent.com/1723612/139608101-795784f9-f8d9-4d1b-b895-1603a4d49cf1.png)

**Comment by CrendKing** [comment]
New version:

before.ps1:
```powershell
if ($args.Length -eq 0) {
    $kopiaSourcePath = $env:KOPIA_SOURCE_PATH
    $kopiaSnapshotId = $env:KOPIA_SNAPSHOT_ID
} else {
    $kopiaSourcePath = $args[0]
    $kopiaSnapshotId = $args[1]
}

$sourceDrive = Split-Path -Qualifier $kopiaSourcePath
$sourcePath = Split-Path -NoQualifier $kopiaSourcePath
# use Kopia snapshot ID as mount point name for extra caution for duplication
$mountPoint = "${PSScriptRoot}\${kopiaSnapshotId}"

if (([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] 'Administrator')) {
    $shadowId = (Invoke-CimMethod -ClassName Win32_ShadowCopy -MethodName Create -Arguments @{ Volume = "${sourceDrive}\" }).ShadowID
    $shadowDevice = (Get-CimInstance -ClassName Win32_ShadowCopy | Where-Object { $_.ID -eq $shadowId }).DeviceObject
    if (-not $shadowDevice) {
        # fail the Kopia snapshot early if shadow copy was not created
        exit 1
    }

    cmd /c mklink /d $mountPoint "${shadowDevice}\"
} else {
    $proc = Start-Process 'pwsh' '-f', $MyInvocation.MyCommand.Path, $kopiaSourcePath, $kopiaSnapshotId -PassThru -Verb RunAs -WindowStyle Hidden -Wait
    if ($proc.ExitCode) {
        exit $proc.ExitCode
    }
}

Write-Output "KOPIA_SNAPSHOT_PATH=${mountPoint}${sourcePath}"
```

after.ps1:
```powershell
if ($args.Length -eq 0) {
    $kopiaSnapshotId = $env:KOPIA_SNAPSHOT_ID
} else {
    $kopiaSnapshotId = $args[0]
}

if (([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] 'Administrator')) {
    $mountPoint = Get-Item "${PSScriptRoot}\${kopiaSnapshotId}"
    $mountedVolume = $mountPoint.Target

    Remove-Item $mountPoint
    Get-CimInstance -ClassName Win32_ShadowCopy | Where-Object { "$($_.DeviceObject)\" -eq "\\?\${mountedVolume}" } | Remove-CimInstance
} else {
    Start-Process 'pwsh' '-f', $MyInvocation.MyCommand.Path, $kopiaSnapshotId -Verb RunAs -WindowStyle Hidden -Wait
}
```

**Comment by alexwh** [comment]
Running from KopiaUI, it's the same error as before:
![image](https://user-images.githubusercontent.com/1723612/139718632-5b8377d5-0351-4317-bfe3-9057e0736bd5.png)
Running from pwsh, the script executes correctly, reports the correct KOPIA_SNAPSHOT_PATH (`KOPIA_SNAPSHOT_PATH=C:\Users\me\kopia_actions\testhash111222\`) and creates the link to the correct shadow volume.

**Comment by CrendKing** [comment]
The fact running it directly is working means progress. I didn't test the script with KopiaUI to begin with (I just do `kopia server start`).

I'll now check what's wrong. It could be a KopiaUI specific issue.

**Comment by CrendKing** [comment]
From your screenshot I figured that the `\\` is from the directory where you set the policy. See that "running action before-folder on C:**\\\\**...". `Split-Path -NoQualifier 'C:\\'` outputs `\\`, which is appended to the mount point path.

I don't know if this is why it's failing for you. Can you try removing the double backslash?

**Comment by alexwh** [comment]
> I'll now check what's wrong. It could be a KopiaUI specific issue. Meanwhile, what if you create snapshot by running `kopia snapshot create`? Do you get the same error?

Running `kopia snapshot create C:\` results in the output `Snapshotting user@host:C:\ ...` followed by cmd.exe immediately closing.

> From your screenshot I figured that the `\\` is from the directory where you set the policy. See that "running action before-folder on C:**\\**...". `Split-Path -NoQualifier 'C:\\'` outputs `\\`, which is appended to the mount point path.
> 
> I don't know if this is why it's failing for you. Can you try removing the double backslash?
> 
> If this is indeed the reason, I think we need to improve how Kopia handle path. Normally, consecutive multiple `\`s should be just equivalent to single `\`.

I believe the original policy was created with KopiaUI, but listing it in `kopia policy list` shows just one backslash:
![image](https://user-images.githubusercontent.com/1723612/139842209-afcde422-e103-4c54-84a8-d5addc166aa0.png)

Removing the before and after actions with `kopia policy set C:\ --before-folder-action ""` allows `kopia snapshot create` to run normally. Setting it again with `kopia policy set C:\ --before-folder-action "pwsh -WindowStyle Hidden C:\...\before.ps1"` causes the same behavior as before in both `kopia snapshot create C:\` and KopiaUI.

Something else I noticed, since the before.ps1 script succeeds but Kopia fails to utilize it, after.ps1 will not run, resulting in hundreds of links and shadow volumes created on my system due to the lower retry time on failed backups.

**Comment by CrendKing** [comment]
Interesting. What happens if you just replace the script with a simple `Write-Host KOPIA_SNAPSHOT_PATH=<some path>`? Like create a C:\test and D:\test. Snapshot C:\test, but let the script return D:\test. Would it actually snapshot D:\test?

Forget about VSS. I wonder if the action functionality works for you at all.

**Comment by alexwh** [comment]
That correctly snapshots the d.txt that I created in D:\test. I believe the problem may be in trying to snapshot the root of each respective drive.

**Comment by CrendKing** [comment]
> I believe the problem may be in trying to snapshot the root of each respective drive.

Can you confirm? Like what I did, snapshotting something like D:\a with VSS.

**Comment by alexwh** [comment]
Even after setting an explicit policy on `C:\test` (with `kopia policy set C:\test --before-folder-action "pwsh -WindowStyle Hidden C:\...\before.ps1"` I can't seem to get it to spawn pwsh.exe, and it succeeds but I believe without VSS. Is it because it's a subdirectory of `C:\`, with the existing policy?

**Comment by CrendKing** [comment]
Could be. I'm not familiar with the go code around the action functionality. Jarek knows more. Maybe try a different drive, or temporarily remove the action on C:\?

**Comment by alexwh** [comment]
I tried a USB stick, but it failed with exit code 1 - I assume VSS isn't supported on non-permanent drives. Removing the action policy on `C:\` showed pwsh.exe with admin get spawned under the KopiaUI tree, and the backup succeeded.

Another side note which should probably be its own issue, the main `C:\` backup was overdue, and cancelling it made it immediately trigger again when I was attempting to get `C:\test` to go through first.

**Comment by CrendKing** [comment]
> the backup succeeded for `C:\test`.

So the script is working? If so, I'll update the doc with the new script, and close this issue. Feel free to open new issue for the `C:\` not backing up.

**Comment by alexwh** [comment]
As far as I can tell, yes. Will do, thanks for your help!
