### ISSUE TITLE
Can't run kopia-ui

### ISSUE THREAD

**Issue by mhosken** [kopia/kopia#1457]
On Ubuntu 21.10, installed kopia and kopia-ui v0.9.4 successfully. Ran kopia-ui and created an archive. All good things. Running like a charm. Then closed kopia-ui. On rerunning kopia-ui I get this message:
```
09:24:00.507 › Error: Error: ENOENT: no such file or directory, open '/opt/KopiaUI/resources/app-update.yml'
(node:71222) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/KopiaUI/resources/app-update.yml'
(Use `kopia-ui --trace-warnings ...` to show where the warning was created)
(node:71222) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
And then that's it. I can get no further. I don't want kopia-ui to autoupdate, thank you. I have apt for that and the fine work packagers do. So:

1. How do I work around this bug to get kopia-ui working again
2. How can this be removed from a future version from kopia-ui? (Perhaps see https://github.com/electron-userland/electron-builder/issues/4975 ?)

**Comment by JensErat** [comment]
I observed the same issue. I managed to extract an `app-update.yml` from the Windows UI zip file, store following information to `/opt/KopiaUI/resources/app-update.yml` to resolve the issue:

```yaml
owner: kopia
repo: kopia
provider: github
vPrefixedTagName: true
releaseType: release
updaterCacheDirName: kopia-ui-updater
```
