### ISSUE TITLE
Not a directory error when snapshotting root of drive with actions on Windows

### ISSUE THREAD

**Issue by alexwh** [kopia/kopia#1480]
As discussed in #1456, there seems to be improper handling of the root of lettered drives in Windows when redirecting the snapshot elsewhere with actions' `KOPIA_SNAPSHOT_PATH` environment variable. This was encountered with the example VSS script, though behavior seemed to be fixed once any subdirectory of the drive (e.g. `C:\test`) has the action policy applied and is snapshotted instead.

![image](https://user-images.githubusercontent.com/1723612/139718632-5b8377d5-0351-4317-bfe3-9057e0736bd5.png)

**Comment by jkowalski** [comment]
Did the script return this path ending with `\\.`?

**Comment by alexwh** [comment]
It ended with just a single backslash (e.g. `KOPIA_SNAPSHOT_PATH=C:\Users\me\kopia_actions\testhash111222\`), but somewhere along the line in Kopia (be it UI or more internal) it becomes two backslashes. Stripping the trailing backslash in the script before echoing KOPIA_SNAPSHOT_PATH results in the same error, but with no backslashes in the error output instead of two.

**Comment by jkowalski** [comment]
Fixed with #1816
