### ISSUE TITLE
Snapshot verify fails for "invalid object length" - off by 32

### ISSUE THREAD

**Issue by redgoat650** [kopia/kopia#149]
If I snapshot a directory and run `snapshot verify --all-sources`, I'm seeing the command fail when the expected size is 32 B less than the actual value.

To reproduce:
```
mkdir testdir
cat >> ./testdir/testfile.txt <<EOL
some test file
EOL
./kopia repo create filesystem --path ./testrepo -p test
./kopia snapshot create ./testdir
./kopia snapshot verify --all-sources
```
Example output:
```
redgoat@DESKTOP-DOLV2TM:~/repo/kopia$ ./kopia snapshot verify --all-sources
Found 1 objects, verifying 1, completed 0 objects.
06:17:49.653 [kopia/cli] failed on redgoat@desktop-dolv2tm:/home/redgoat/repo/kopia/testdir@2019-12-11 06:17:47 PST/testfile.txt: invalid object length "082493011c49fb96d689d32cd18819b6", 47, expected 15
kopia: error: encountered 1 errors, try --help
```

Tested with larger directory structures as well. Output is always off by 32.

Kopia commit tested: 39a2cad2d9d4cdca21bdf61ce551ba9ccdf4605c

**Comment by julio-lopez** [comment]
@redgoat650 Can you reproduce with commit ca9ba27c6ff6c32900b694cdf900c3630d2c5fff ?

**Comment by redgoat650** [comment]
@julio-lopez yes still seemed to be an issue on that revision

**Comment by jkowalski** [comment]
can you try that with 0.3.0 ?

**Comment by redgoat650** [comment]
> 
> 
> can you try that with 0.3.0 ?

Yep verified it reproduces with 0.3.0.

**Comment by jkowalski** [comment]
Can you verify with `kopia --version` ?

**Comment by jkowalski** [comment]
We investigated this and version at head is actually ok but 0.3.0 was broken. The reason has to do incorrect assumption that object verifier was making about reported content length. Recent versions simply don't validate object length like that, so things just work.

**Comment by jkowalski** [comment]
Having said that, we should add an e2e test to make sure this stays working.

**Comment by ntolia** [comment]
This can be closed, right?
