### ISSUE TITLE
Make upload and download throttling universally configurable

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#1503]
Currently upload and download throttle values are specified at `create` or `connect` time using provider-specific flags and thus is not uniformly across providers.

When we implement #1502, should be able to deprecate provider-specific flags for controlling throttles in favor and make them universal and changeable:

```
$ kopia repo create --max-upload-speed X --max-download-speed Y 
$ kopia repo connect --max-upload-speed X --max-download-speed Y
$ kopia repo set-client --max-upload-speed X --max-download-speed Y
```

**Comment by xxxliqu1dxxx** [comment]
Would it make sense to consider the use case of bandwidth vs time of day?
I.e. between 9am to 5pm = 1MB/s, but 5pm to 9am = 10MB/s
