### ISSUE TITLE
Blacklist for paths

### ISSUE THREAD

**Issue by Y0ngg4n** [kopia/kopia#1507]
Would be nice if we could add an option to blacklist a list of specific paths in a repository.

**Comment by xxxliqu1dxxx** [comment]
> 
> 
> Would be nice if we could add an option to blacklist a list of specific paths in a repository.

If you are talking about excluding folders, you can absolutely do that already with policies:

![image](https://user-images.githubusercontent.com/83290244/141015807-814cb5e4-896f-4f54-b920-91ffdfd9d7c0.png)

Please review the documentation - this works really well.

**Comment by Y0ngg4n** [comment]
ah ok sorry did not see that. thanks for your support :)
