### ISSUE TITLE
WebDAV: error parsing JSON: invalid character '<' looking for beginning of value (connecting to Nextcloud WebDAV)

### ISSUE THREAD

**Issue by benbenik** [kopia/kopia#1514]
Description/Action: Using a fresh install of Kopia UI v0.9.5 and choosing WebDav as Repository only the WebDav URL+directory path, a username and password is requested. However, the connection fails due to an invalid JSON issue, shown under "Error" below in this report.

Kopia version: Version v0.9.5 built on Sunday, November 7, 2021 7:32:47 PM fv-az15-931 (for Windows)
WebDav Backend: Nextcloud, Version 21.0.6 November 12 2021

Expected behaviour: Entering the three requested fields in the UI (WebDAV server URL+directory path, a username and password, followed by clicking "Next", should result in proceeding to configure the backup.
Actual behaviour: An error, due to JSON communication error between Kopia and Nextcloud WebDAV; see "Error" below for details.

Error: "Connect Error: INTERNAL: internal server error: unable to complete GetBlob(kopia.repository,0,-1) despite 10 retries, last error: error determining sharded path: error parsing sharding parameters for storage: error parsing JSON: invalid character '<' looking for beginning of value"

---
I'm eager to use Kopia, I hope this gets resolved, thank you!

**Comment by xxxliqu1dxxx** [comment]
Looks similar to  Kopia does not connect properly to a WebDAV URL provided by OneDrive #1434

**Comment by benbenik** [comment]
SOLVED.
Updating to Nextcloud 22.2.3 did not solve the issue; high hopes due to updated DAV dependency.
I looked again into Nextcloud logging:
`x.x.x.x - - [17/Dec/2021:22:04:44 +0000] "GET /index.php/login HTTP/1.1" 200 13599
x.x.x.x - - [17/Dec/2021:22:04:45 +0000] "GET /backup-kopia/.shards HTTP/1.1" 302 -`
[Repeated 10 times]

A HTTP 200 code shows that logging went well; could it be a path issue, indicated by the 302 code?

It sure was the problem. using this path (replace example.com, USER and MY_BACKUP_DIR) resolves the issue:
https://cloud.example.com/remote.php/dav/files/USER/MY_BACKUP_DIR/

Repository created and connected succesfully!
