### ISSUE TITLE
Provide the ability to pin a snapshot, and/or add a custom tag.

### ISSUE THREAD

**Issue by talios** [kopia/kopia#1518]
Originally asked on Slack and was asked to raise a ticket.

Is it possible to pin a snapshot, and/or a custom tag with Kopia?

I'm just wondering about the retention - I understand keeping the most recent backup of each retention tag,  but part of me thinks “eventually, my annual tag is going to have a snapshot at the end of the year, and any thing in that first year will eventually be lost!"

I realise those snapshots will be largely covered by other tags tho, so not neccessarilly reallly an issue, and probably more related to me doing lots of test snapshots + paranoia ), esp. as I'm starting to use Kopia at the end of the year - but if I'd started in say January, eventuall over time, that first twelve months will age out.

https://kopia.discourse.group/t/trying-to-understand-retention-policies-cont/311/8  covers most things in my mind, tho a custom tag of “hey - I’m about to run a large automated delete process, and I want to be safe….  tag with `before-mark-broke-it`"

Along with the ability to eventually delete that tag.  Or, if I created another manual snapshot with the same tag - move the original one to `before-mark-broke-it-2` and the new snapshot with `before-mark-broke-it-1`.

**Comment by jkowalski** [comment]
BTW, today you can add custom tags while creating a snapshot using `--tags` on the command line but they are only used as addiitional labels for the snapshot manifest and don't have any retaining power.

**Comment by talios** [comment]
@jkowalski Awesome! `pin`s look like they'll do the trick nicely.
