### ISSUE TITLE
kopia snapshot restore is slow(er than expected)

### ISSUE THREAD

**Issue by 0x53A** [kopia/kopia#1524]
## Theory:

with a hot cache, ``kopia snapshot restore`` should be about as fast as ``robocopy``.

## System:

```
kopia: 0.9.5 build: b4619ffacfb7ba387755b2e714a7dffe9244721d from: kopia/kopia

Windows 10 2004 x64
Lenovo P1 Laptop with i7-8850H@2.6GHz (6C/12T)
VM (unfortunately I can't currently test on bare-metal, but I know the results are similar)
20GB RAM, fixed to VM (no dynamic memory)
fixed size VHDX file on a Samsung 980 Pro 2TB
both cache and restore output are on the same partition
```

## Setup:

```
.\kopia.exe repository create azure --container #### --storage-account #### --storage-key #####
.\kopia.exe policy set --global --compression pgzip
```

Then I uploaded a snapshot with an on-disk size of 13.1 GB, 66k files, 8k folders, containing mostly binary files (exe, dll, etc)

----------

## Test:

```powershell
.\kopia repository connect from-config --token ####
.\kopia cache set --content-cache-size-mb=20000 --metadata-cache-size-mb=20000

# run it once to make sure the cache is hot
.\kopia snapshot restore #### .\snapshot

# run it a second time
(Measure-Command { .\kopia snapshot restore #### .\snapshot | Out-Default }).TotalSeconds

# for comparison, run a robocopy
(Measure-Command { robocopy /MIR /NP /NFL /NDL .\snapshot .\snapshot2 | Out-Default }).TotalSeconds
```

## Result:

In Taskmanager, I can see that the disk is fully utilized, CPU is utilized about one third to half. Disk IO sometimes spikes to ~400 MB/s, but mosty stays below 100 MB/s or even less

![image](https://user-images.githubusercontent.com/4236651/142680703-27f40d1a-c0f5-464a-a13b-f6a1f706bac4.png).

-------------

In comparison, robocopy is mostly managing a steady ~200MB/s to ~600MB/s (with some dips to ~120 MB/s), with 5% CPU utilization. Now, the CPU difference is not a big surprise since kopia does need to decompress the files on-the-fly.

![image](https://user-images.githubusercontent.com/4236651/142681704-5c9e46e3-52c5-4771-98c0-3fbcc4035797.png)

The second kopia restore took 290 seconds.
The first robocopy took 156 seconds.

since robocopy didn't fully saturate the disk, i tried it again with /MT:16 (the default is MT:8), now it topped out at ~1 GB/s. 

The second robocopy (with MT:16) took 86 seconds.
The third robocopy (with MT:32) took 90 seconds

The third kopia restore took 302 seconds.

-----

## Guess:

Since kopia maxes out the disk while still not managing a high throughput, it seems to me like kopia does inefficient IO, maybe with a too low buffer size or something?

For example, I found a place where some buffer is set to 65k. I didn't look at it in detail if that is even a relevant one, though.

https://github.com/kopia/kopia/blob/35d0f31c0d352c2fbd24ad585938580ef9938dc1/internal/iocopy/copy.go#L9

--

Another idea is that maybe the chunks in the cache are too small:

The total size of the cache folder is 4.8 GB with 47k files and 272 folders. That's a lot of files.

**Comment by jkowalski** [comment]
Can you try increasing parallelism to `--parallel=32` and see if you get an improvement?  This will issue a lot more I/O in parallel to Azure and should better compensate for any latency to the cloud.

**Comment by jkowalski** [comment]
(Also, restore performance is largely not optimized as well as it could, we have some ideas about improving caching and locality that will make it run way faster).

**Comment by 0x53A** [comment]
The cache is hot, so I don't think it should do any requests to azure at all?

With ``--parallel=32`` it took 284 seconds, so no real change.

**Comment by 0x53A** [comment]
I also tried ``parallel=1024`` and it took 270 seconds.

I peeked at it with a profiler and saw a lot of ``FlushFileBuffers``.

My guess is that kopia flushes way to often, probably all except the last one before terminating could be omitted.

If you need to flush for safety reasons, could you make that configurable via a parameter?

**Comment by 0x53A** [comment]
oh and I noticed that ``kopia snapshot restore`` defaults to ``--file-log-level=debug``.

**Comment by 0x53A** [comment]
``snapshot restore`` uses https://github.com/natefinch/atomic ``WriteFile``.

``WriteFile`` first does a ``.Sync()``, which afaik does a ``FlushFileBuffers`` ...
https://github.com/natefinch/atomic/blob/master/atomic.go#L43

and then a ``moveFileEx`` with ``movefile_write_through``
https://github.com/natefinch/atomic/blob/master/file_windows.go#L29


So basically, it does *two* flushes per file, no wonder it's slow!

**Comment by 0x53A** [comment]
I'm betting a 10x speedup is possible by removing the flushes and maybe increasing the buffer size, though I'm not sure if that would actually be necessary.

**Comment by jkowalski** [comment]
Patches to fix this are welcome! I think we can probably switch to using non-atomic writes and add a flag that triggers `atomic.FileWrite` if a situation requires that.

**Comment by 0x53A** [comment]
So I can confirm that using non-atomic writes reduces time to 147 seconds with ``parallel=16`` and 126 seconds with ``parallel=32``.

At this point it's mostly CPU-bound, probably decompression:
![image](https://user-images.githubusercontent.com/4236651/143004767-a3e332eb-b0ea-448d-aea2-eb149a6b1ed7.png)


Just for fun I tried parallel=512, which also took 127 seconds, so it seems overloading the system doesn't actually degrade performance.

I might run a few more tests with no compression, or a different algorithm or sth, but that's good for now.
