### ISSUE TITLE
zstd-best compression performance is < ×0.1 of the zstandard utility

### ISSUE THREAD

**Issue by ZoomRmc** [kopia/kopia#1527]
I've prepared a 50MB .tar file of a few typical files from my data.

The results of the Kopia benchmark for zstd-best:
```
 17. zstd-best-compression      30.1 MiB     4.6 MiB/s    4912   164.4 MiB
```
[Upstream](https://github.com/klauspost/compress) mentions this level is ~ zstandard's `-11`. Here's the results from built-in zstd's benchmark of levels 10 through 16:

```
10#test.tar          :  52097536 ->  31292419 (1.665),  67.0 MB/s ,1254.6 MB/s
11#test.tar          :  52097536 ->  31264158 (1.666),  60.3 MB/s ,1297.1 MB/s
12#test.tar          :  52097536 ->  31246267 (1.667),  46.5 MB/s ,1266.7 MB/s
13#test.tar          :  52097536 ->  31231063 (1.668),  15.1 MB/s , 949.6 MB/s
14#test.tar          :  52097536 ->  31215580 (1.669),  15.0 MB/s ,1303.6 MB/s
15#test.tar          :  52097536 ->  31208494 (1.669),  12.8 MB/s , 958.3 MB/s
16#test.tar          :  52097536 ->  30881283 (1.687),  8.42 MB/s ,1298.5 MB/s
```

I understand some performance lag in a pure Go implementation is expected, however, an order of magnitude seems like a bit too much. This is especially concerning due to the fact that according to my observations, compression doesn't happen purely in an asynchronous way in Kopia (CPU utilization is not uniform, hasher seems to stall periodically too).

Is it strictly the problem of the underlying implementation?

**Comment by CrendKing** [comment]
If I replace this line https://github.com/klauspost/compress/blob/master/zstd/encoder_options.go#L64 with the `betterFastEncoder`, `kopia benchmark` would show the good throughput for "best". So pretty sure the ["best" encoder](https://github.com/klauspost/compress/blob/94ad1f0bf03c0761f50c69f9242f49fbb9ab08c0/zstd/enc_best.go) has some specific logic that dramatically slows down the algorithm.

**Comment by ZoomRmc** [comment]
Not really sure what you mean. Kopia already has a preset for this level, it's `zstd-better-compressor` and it's just about 45% slower.

It would be interesting to compare this with the wrappers for the official library, such as valyala/gozstd or DataDog/zstd.

**Comment by CrendKing** [comment]
> Not really sure what you mean

I meant by only changing the encoder without modifying any Kopia code, we isolate the problem to the underlying implementation (klauspost).

Here is the number by switching to valyala/gozstd:
```
zstd-fastest               21.7 MiB     543.8 MiB/s  13     58.5 MiB
zstd                       20.4 MiB     433.4 MiB/s  13     53 MiB
zstd-better-compression    19.2 MiB     162.8 MiB/s  18     50.4 MiB
zstd-best-compression      18.9 MiB     77.8 MiB/s   13     50.5 MiB
```
Comparing to stock:
```
zstd-fastest               22.2 MiB     460.5 MiB/s  6262   69.1 MiB
zstd                       21 MiB       437.3 MiB/s  6294   73.8 MiB
zstd-better-compression    20.1 MiB     210.5 MiB/s  6310   91.3 MiB
zstd-best-compression      18.7 MiB     18.9 MiB/s   6310   151.8 MiB
```
Not sure why we are doing better with level 7, but level 11 has some space to improve. Again, this is all underlying impl. There is nothing Kopia can do besides switching the library. In that case, @jkowalski can decide.
