### ISSUE TITLE
spoof snapshot create source

### ISSUE THREAD

**Issue by saviodsouza** [kopia/kopia#1530]
As discussed in the forum thread raising a feature request issue for the same.
https://kopia.discourse.group/t/spoof-snapshot-create-source/748?u=saviodsouza

Brief info:
Kopia needs a  --set-source= parameter for kopia snapshot create to spoof snapshot create.
`kopia snapshot create /home/admin --set-source /home/user`
The above comand should backup /home/admin but record source as /home/user in the repository.

Thank you 😊

**Comment by jkowalski** [comment]
That makes sense, we allow spoofing of almost everything except path for some reason.
