### ISSUE TITLE
KopiaUI Traymenu > Check For Updates Now does nothing (visible)

### ISSUE THREAD

**Issue by TrashAccount3424** [kopia/kopia#1531]
I use KopiaUI on windows and when I click on the Traymenu > Check For Updates Now, nothing happens.
Since I'm on the latest version I would expect it to tell me that or give any kind of visible feedback.

**Comment by jkowalski** [comment]
This currently updates the label in the tray menu that say - `Kopia is up-to-date: vXXX` but does not produce any popup message, if that's what you're asking for.

**Comment by jkowalski** [comment]
Fixed in #1804
