### ISSUE TITLE
[feature request] snapshot restore: add "robocopy /MIR" (mirror) equivalent

### ISSUE THREAD

**Issue by 0x53A** [kopia/kopia#1535]
I'd like to add a restore mode which, like ``--skip-existing`` works incremental, but also **deletes** extra files.

1) is this a functionality you'd like to support?
2) if yes, should I add a new flag ``--mirror``, or should it be a combination of ``--skip-existing`` and a new flag ``--delete-extra`` (exact name tbd)?

### Use case:

We use kopia snapshots to copy files between gitlab ci stages. The total size is ~13GB, about 10GB of that is static and does not change between runs.

Currently we delete everything and do a full, clean restore.

We could save a lot of time by keeping the directory _dirty_ between runs, then using an incremental kopia restore.

**Comment by jkowalski** [comment]
Makes sense to me. PRs are welcome.

**Comment by cristihcd** [comment]
Looks like a welcome feature. I would suggest --skip-existing and --delete-extra flags.

**Comment by cristihcd** [comment]
Currently I am using `robocopy /mir` over an on-demand vpn connection to delete extra files. The restored files are over 400GB, so deleting before restore is not a good option. 

Does anyone have another solution? I am not experienced enough to modify kopia's code.

**Comment by nickchomey** [comment]
I'd love to see this feature as well. Right now (I believe) I'm forced to mount the repo in either kopia or restic and use rclone sync to perform a mirror as described here. I'd love to simplify this and keep it all within rclone restore.

**Comment by renardguill** [comment]
Hello all, @jkowalski, now that @0x53A has made a PR, when can this be merged? because it's a really useful feature 🤩 .

**Comment by geekwave9421** [comment]
Hi @jkowalski  when this PR will be merged , this is really a important feature adds value to kopia

**Comment by trompx** [comment]
Also wanted an equivalent of rclone sync (mirror) where I don't end up with incomplete files, in case the restore fail and I have to restart it multiple times. Ended up using `--skip-existing --write-files-atomically --delete-extra` but not sure if this is bullet proof (have not enough experience with huge snapshots restores).
