### ISSUE TITLE
kopia-ui preventing suspend/hibernate

### ISSUE THREAD

**Issue by igoralmeida** [kopia/kopia#1544]
Hi everyone, first of all thanks for the great tool.

Sometimes a `systemctl suspend` or `systemctl hibernate` command does not work for me and I get back to the OS after a few seconds. This time I managed to capture a log with journalctl, attached.

[kopialog.txt](https://github.com/kopia/kopia/files/7622015/kopialog.txt)

All the best

**Comment by jkowalski** [comment]
I don't really know how this may be blocking suspend. Marking as "help wanted"
