### ISSUE TITLE
Improve merging of tags on duplicate snapshots

### ISSUE THREAD

**Issue by talios** [kopia/kopia#1558]
As asked on Slack and moved to an issue.

![kopia-tags](https://user-images.githubusercontent.com/19093/144353355-f4e2fe13-53ac-43a2-be63-9547c2af5a44.png)

Regarding the in-memory tagging - the snapshots `hourly-24` thru `hourly-32` are all duplicate, so when hiding dupes (default view), the `monthly-2` and `daily-3` tags don’t show up.

Rather than them being at the first/oldest occurrence of the duplicate snapshots, should they not be showing on the most recent?

I was wonderingly where my `monthly-2` tag was and took a moment to click.

**Comment by jkowalski** [comment]
This is interesting, I think we can do something like range detection and generate range tags like:

`hourly-24-to-32`, `monthly-2`

In an extreme case where the directory never changes and only has dupes the tags would be something like:

`latest-1-to-100`, `hourly-1-to-24`, `daily-1-to-30` 

Thoughts?
