### ISSUE TITLE
Maintenance on S3 leaking threads

### ISSUE THREAD

**Issue by raisinbear** [kopia/kopia#1560]
Hi,

I asked about this earlier today on the Kopia forum: [Post](https://kopia.discourse.group/t/maintenance-run-crashing-minio-s3-backend/786)

In short: I suspect that `kopia maintenance run` is leaking threads when iterating over unreferenced blobs. It reliably crashes my low-key minio server by eventually spawning (or rather trying to) > 11466 threads, which is the OS hard limit. Repo size is roughly 400 GB and 14000 blobs, so probably nothing extraordinary.
I did not encounter any other kopia command that brings the number of minio threads above 100 if at all.

For completeness sake, this is the kopia error reported to stdout once the minio server side OS interferes:
`2021-12-01T09:23:10.794863Z ERROR kopia/cli error deleting unreferenced blobs: error looking for unreferenced blobs: error iterating blobs: Get "[ DOMAIN ]/kopia/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=p7": net/http: timeout awaiting response headers`

Thanks a lot for maintaining this awesome project!

**Comment by potatoru** [comment]
Sorry, but I have the same issue with my minio setup.
