### ISSUE TITLE
KopiaUI: CLI logs using 250+ GBs?!

### ISSUE THREAD

**Issue by RavenMacDaddy** [kopia/kopia#1561]
![image](https://user-images.githubusercontent.com/67732686/144502120-0a2522f2-0eb4-445d-bbf0-2d1371aed094.png)

...

![image](https://user-images.githubusercontent.com/67732686/144502146-376574b4-5fa8-4b24-acb3-457c5a033879.png)

..?

![image](https://user-images.githubusercontent.com/67732686/144502175-d2004908-890e-4616-a7e9-479587939462.png)

.!?

No but seriously, what's going on?!

This is absolutely insane.

Anyway, worth to note is that I'd a sudden shutdown cause I was seemingly overloading my newly acquired UPS in the last few days - however - I only noticed kopia using all of that storage space just now, so I'm not definitely saying that there's a correlation, just think it's worth noting in case there _could_ be a correlation.

Tell me what data you need to troubleshoot this.

EDIT: Just noticed the date for the logs... the kernel power event happened on the 30th of november, so there really shouldn't be a correlation, which makes it even weirder.

Something else to note is that I only use my Windows PC with sleep during the night etc., no clean boot till there's an update that requires it.

**Comment by jkowalski** [comment]
Yeah, this is embarrasing - kopia will currently sweep logs on exit and since server never exists they keep lingering on.

I'll prioritize fixing that.

**Comment by RavenMacDaddy** [comment]
I'm just glad you've a clear idea of the cause.
