### ISSUE TITLE
FR: KOPIA-UI: Remember the previously connected repositories

### ISSUE THREAD

**Issue by gerroon** [kopia/kopia#1564]
Hi

it would be very helpful if the UI app remembers the previously connected repositories for easy access. Please see the image for the basic idea.

![KopiaUI_ge3agZsc13](https://user-images.githubusercontent.com/8519469/144668089-fcec0ee5-02c9-45c9-b1e5-e3ccef4c2a2d.jpg)

**Comment by jkowalski** [comment]
FWIW you can be simultaneously connected to multiple repositories using KopiaUI using `Connect to another repository...` option, so this might be slightly confusing in terms of expected usage pattern.

**Comment by gerroon** [comment]
Hi,

This is just a list that use can click on the reconnect past repositories. Would that interfere with multiple repos?

**Comment by Tomptez** [comment]
+1
I think this feature would be extremely helpful for less tech savy users. I've setup Kopia for some people before and remembering the path and manually copying/typing it in there is surprisingly the biggest hurdle for many of them
