### ISSUE TITLE
Cannot restore snapshot that was succesfully taken just  before

### ISSUE THREAD

**Issue by ThieJ** [kopia/kopia#1570]
I am creating a snapshot of (parts of, there is a .kopiaignore file) my home directory. It includes a directory with some VirtualBox appliances with large .vmdk files.
If I try to restore these individual files, the directory or the entire snapshot the .vmdk files are not restored to their original lengths and the restore operation fails with an error. I have included a transscript below,

**tim@bach> kopia repository create filesystem --path /data/backup/kopia_repo**
Enter password to create new repository: 
Re-enter password for verification: 
Initializing repository with:
  block hash:          BLAKE2B-256-128
  encryption:          AES256-GCM-HMAC-SHA256
  splitter:            DYNAMIC-4M-BUZHASH
Connected to repository.

NOTICE: Kopia will check for updates on GitHub every 7 days, starting 24 hours after first use.
To disable this behavior, set environment variable KOPIA_CHECK_FOR_UPDATES=false
Alternatively you can remove the file "/home/tim/.config/kopia/repository.config.update-info.json".

Retention:
  Annual snapshots:    3           (defined for this target)
  Monthly snapshots:  24           (defined for this target)
  Weekly snapshots:    4           (defined for this target)
  Daily snapshots:     7           (defined for this target)
  Hourly snapshots:   48           (defined for this target)
  Latest snapshots:   10           (defined for this target)
Compression disabled.

To find more information about default policy run 'kopia policy get'.
To change the policy use 'kopia policy set' command.

NOTE: Kopia will perform quick maintenance of the repository automatically every 1h0m0s
and full maintenance every 24h0m0s when running as tim@bach.

See https://kopia.io/docs/advanced/maintenance/ for more information.

NOTE: To validate that your provider is compatible with Kopia, please run:

$ kopia repository validate-provider

**tim@bach:~$ kopia repository connect filesystem --path /data/backup/kopia_repo**
Enter password to open repository: 

Connected to repository.

NOTICE: Kopia will check for updates on GitHub every 7 days, starting 24 hours after first use.
To disable this behavior, set environment variable KOPIA_CHECK_FOR_UPDATES=false
Alternatively you can remove the file "/home/tim/.config/kopia/repository.config.update-info.json".

**tim@bach:~$ kopia snapshot create /home/tim**
Snapshotting tim@bach:/home/tim ...
 * 0 hashing, 57517 hashed (125.1 GB), 0 cached (0 B), uploaded 122.2 GB, estimated 125.1 GB (100.0%) 0s left 
Created snapshot with root k8a4b7349bf97ee7f50199b199217498f and ID 36fc0b70907489db9ce27a5a2f62b14f in 4m27s
Running full maintenance...
Looking for active contents...
  Processed 27821 contents, discovered 27839...
  Processed 68792 contents, discovered 68792...
Looking for unreferenced contents...
Rewriting contents from short packs...
Not enough time has passed since previous successful Snapshot GC. Will try again next time.
Skipping blob deletion because not enough time has passed yet (59m59s left).
Cleaned up 0 logs.
Finished full maintenance.

**tim@bach:~$ mkdir tmp ;  cd tmp**

**tim@bach:~/tmp$ kopia snapshot restore k8a4b7349bf97ee7f50199b199217498f .**
Restoring to local filesystem (/home/tim/tmp) with parallelism=8...
Processed 25239 (168.3 MB) of 78950 (125.1 GB) 168.3 MB/s (0.1%) remaining 12m21s.
Processed 35112 (460.3 MB) of 78950 (125.1 GB) 228.7 MB/s (0.4%) remaining 9m3s.
Processed 36184 (71.1 GB) of 78950 (125.1 GB) 20.5 GB/s (56.8%) remaining 2s.
Processed 36198 (72.7 GB) of 78950 (125.1 GB) 16.1 GB/s (58.1%) remaining 2s.
Processed 36227 (72.8 GB) of 78950 (125.1 GB) 13.2 GB/s (58.2%) remaining 3s.
Processed 36246 (72.9 GB) of 78950 (125.1 GB) 11.2 GB/s (58.3%) remaining 4s.
Processed 36288 (73 GB) of 78950 (125.1 GB) 9.7 GB/s (58.4%) remaining 4s.
Processed 37688 (73.1 GB) of 78950 (125.1 GB) 8.5 GB/s (58.5%) remaining 5s.
Processed 37897 (73.3 GB) of 78950 (125.1 GB) 7.6 GB/s (58.6%) remaining 6s.
Processed 38018 (73.4 GB) of 78950 (125.1 GB) 6.9 GB/s (58.7%) remaining 7s.
Processed 38064 (73.7 GB) of 78950 (125.1 GB) 6.3 GB/s (58.9%) remaining 7s.
Processed 38122 (73.9 GB) of 78950 (125.1 GB) 5.8 GB/s (59.1%) remaining 8s.
Processed 38194 (74.1 GB) of 78950 (125.1 GB) 5.4 GB/s (59.2%) remaining 9s.
Processed 38319 (74.6 GB) of 78950 (125.1 GB) 5.1 GB/s (59.6%) remaining 9s.
Processed 38360 (74.7 GB) of 78950 (125.1 GB) 4.7 GB/s (59.7%) remaining 10s.
Processed 38434 (76.1 GB) of 78950 (125.1 GB) 4.5 GB/s (60.8%) remaining 10s.
Processed 38542 (76.2 GB) of 78950 (125.1 GB) 4.3 GB/s (60.9%) remaining 11s.
Processed 38667 (76.3 GB) of 78950 (125.1 GB) 4.1 GB/s (61.0%) remaining 11s.
Processed 38820 (76.4 GB) of 78950 (125.1 GB) 3.9 GB/s (61.1%) remaining 12s.
Processed 39018 (76.6 GB) of 78950 (125.1 GB) 3.7 GB/s (61.2%) remaining 13s.
Processed 39210 (76.7 GB) of 78950 (125.1 GB) 3.5 GB/s (61.4%) remaining 13s.
Processed 39402 (76.9 GB) of 78950 (125.1 GB) 3.4 GB/s (61.5%) remaining 14s.
Processed 39543 (77.1 GB) of 78950 (125.1 GB) 3.2 GB/s (61.6%) remaining 14s.
Processed 39626 (77.3 GB) of 78950 (125.1 GB) 3.1 GB/s (61.8%) remaining 15s.
Processed 39712 (77.4 GB) of 78950 (125.1 GB) 3 GB/s (61.9%) remaining 15s.
Processed 39804 (77.6 GB) of 78950 (125.1 GB) 2.9 GB/s (62.1%) remaining 16s.
Processed 39927 (77.8 GB) of 78950 (125.1 GB) 2.8 GB/s (62.2%) remaining 16s.
Processed 40140 (78 GB) of 78950 (125.1 GB) 2.7 GB/s (62.3%) remaining 17s.
Processed 40234 (78.1 GB) of 78950 (125.1 GB) 2.6 GB/s (62.5%) remaining 17s.
Processed 40330 (78.3 GB) of 78950 (125.1 GB) 2.5 GB/s (62.6%) remaining 18s.
Processed 40558 (78.5 GB) of 78950 (125.1 GB) 2.5 GB/s (62.8%) remaining 18s.
Processed 40771 (78.7 GB) of 78950 (125.1 GB) 2.2 GB/s (62.9%) remaining 20s.
Processed 40771 (78.7 GB) of 78950 (125.1 GB) 1.9 GB/s (62.9%) remaining 23s.
Processed 40771 (78.7 GB) of 78950 (125.1 GB) 505.1 MB/s (62.9%) remaining 1m31s.
Processed 40771 (78.7 GB) of 78950 (125.1 GB) 505.1 MB/s (62.9%) remaining 1m31s.
ERROR error restoring: restore error: copy file: error creating file: cannot write data to file %q /home/tim/tmp/VirtualBox VMs/Windows 10/Windows 10.vmdk: unexpected content error: invalid checksum at p3580753a48f78c99d1d490f10ff3a3df-se98016708704422910b offset 12796641 length 2113564/2113564: decrypt: unable to decrypt content: cipher: message authentication failed

**Comment by jkowalski** [comment]
Did this happen literally on the first snapshot? I was suspecting a bit flip somewhere, but this is not very likely in such case.

**Comment by ThieJ** [comment]
Yes this happens on the very first snapshot and I actually tried it a number of times always with the same result, a failure on the .vmdk file.

**Comment by jkowalski** [comment]
Can you tell me more about your hardware? What's the CPU, how many cores, what's the RAM, is it ECC? What's the underlying filesystem?

Even more important - it this something you can reproduce by running it in a loop or was it a one-time thing?

**Comment by jkowalski** [comment]
Is the vmdk file being changed while you snapshot?

**Comment by jkowalski** [comment]
Can you see if this reproduces with different --parallel=X values (1,24,8?)

**Comment by ThieJ** [comment]
It looks like the memory is non-ECC.

**Comment by ThieJ** [comment]
On the restore you mean?

**Comment by jkowalski** [comment]
kopia snapshot create --parallel=X

**Comment by ThieJ** [comment]
OK, trying parallel=1 now

**Comment by ThieJ** [comment]
I have created the snapshot with parallel=1 but the restore still fails, both with parallelism=8 and 1. With 8 it failed on a different file this time. If I run kopia content verify --download-percent=100 directly after creating the snapshot it already lists a number of these errors (6 in total):
ERROR error content dcef781ec250f1f2a17ab53950efb17e is invalid: invalid checksum at p4f65cac6143398168434b4a994051603-s1fb54728d433caec10b offset 14959242 length 2104476/2104476: decrypt: unable to decrypt content: cipher: message authentication failed.
Will try parallel=2 now, but not very optimistic that this wil work ;-)

**Comment by jkowalski** [comment]
if 1 failed, 2 will fail too, so I think we can rule that out.

BTW, i tried on similar-sized file and cannot reproduce this, so there's something else at play here. Can you try creating smaller snapshots of just the directory with the VM, perhaps one level above, etc to see if there's a pattern to this.

Also, you don't need to connect to repo after creating it, it's immediately connected.

**Comment by jkowalski** [comment]
(obviously) it would be perfect if you can narrow it down to a small directory that reproduces this behavior

**Comment by jkowalski** [comment]
More tips:

I `content verify --download-percent=100` fails, there's no need to restore, it will fail the same. 

All this can be automated in a one-liner `rm -rf /tmp/repo-dir && KOPIA_PASSWORD=dummy kopia repo create filesystem --path=/tmp/repo-dir && kopia snapshot create DIR && kopia content verify --download-percent=100` or you can put this in a script

**Comment by jkowalski** [comment]
BTW, I'll be heading to the office, I'll take a look again in the evening Pacific time.

**Comment by jkowalski** [comment]
Also, it might be more convenient to iterate on this using `slack.kopia.io`

**Comment by ThieJ** [comment]
It appears that this issue was caused by a defective memory bank in my system that led to spurious memory errors.
