### ISSUE TITLE
[Feature / suggestion] Kopia UI, file & directory exclusion tool is not ideal.

### ISSUE THREAD

**Issue by jaxjexjox** [kopia/kopia#1571]
Is there any way to improve the user interface for the file and folder exclusion tool? 

Even if I just click a button to the side, like 'test' or 'show results'  
or 'show files which will be omitted' or something?

As it stands, I've found managing the exclusions to be particularly painful.

I realise this is a very nice, cross platform tool and based on my testing, 6+ months ago, one of the more reliable and consistent ones.
However put yourself in the shoes of a windows user.

In a traditional graphical management selection tool, you can took a root path and untick folders and subfolders at will.
I don't expect someone to write this in full, it's clear after this much dev time that is now how your minds are visualising the filesystem but some kind of better way to manage it would be nice (please)

**Comment by jkowalski** [comment]
All great ideas, UX can and should be improved.

Not sure if you saw that v0.9.7 made some improvements in that area:

Currently if you click `New Snapshot` you should be able to edit the exclusion list (in the `Files` section) and on the same screen define a path to snapshot and click run `Estimate` which will tell you how many bytes are excluded and if you click on `Show Log` you'll see which files are excluded and/or have errors reading them. Once you're happy with the list, you can click `Snapshot` to create the actual snapshot.
