### ISSUE TITLE
Option to run more than one snapshot task at the same time

### ISSUE THREAD

**Issue by 1024mb** [kopia/kopia#1575]
Title. I would like to run more than one snapshot at the same time to maximize use of resources but currently Kopia UI is only running one snapshot task at the same time - maintenance tasks have ran in parallel with the snapshot one though.

**Comment by talios** [comment]
Probably unrelated - but I've noticed when looking at my snapshots, I sometimes see two snapshots for the same root with the exact same timestamp.   As tho two processes kicked off the same snapshot ( or maybe its just a UI bug ).

this is a) logged in via the command line, b) running kopia-ui with the window open but minimized.

Running concurrent snapshots for different roots would be nice tho.
