### ISSUE TITLE
Security of backups

### ISSUE THREAD

**Issue by MACscr** [kopia/kopia#1592]
I know the data is encrypted, but what stops a system that is compromised from pruning all the remote backups?

**Comment by jkowalski** [comment]
It's possible to configure cloud storage buckets, such as S3 to enforce minimal retention, and kopia can support restoring from an old version of such bucket, even if all the blobs were deleted.

@julio-lopez

**Comment by julio-lopez** [comment]
See discussion in #1067

**Comment by MACscr** [comment]
Thanks for pointing to me to the thread. Glad it’s being discussed and planned, but a bit disappointed such security wasn’t though of long before. The issue isn’t anything new, just more prevalent these days.

- Mark
