### ISSUE TITLE
Can't make empty ignoreDotFiles

### ISSUE THREAD

**Issue by strager** [kopia/kopia#1598]
I want to have an empty `ignoreDotFiles`. However, Kopia doesn't seem to let me do this.

1. run `kopia policy edit myrepo/`
2. type the following:
```
{
  "retention": {
    "keepLatest": 9001
  },

  "files": {
    "ignoreDotFiles": [],
    "oneFileSystem": true
  },
  "errorHandling": {},

  "scheduling": {},
  "compression": {},
  "actions": {},
  "logging": {
    "directories": {},
    "entries": {}
  }
}
```
3. run `kopia policy get myrepo/`
4. observe:
```
Files policy:
  Ignore cache directories:        true       inherited from (global)
  No ignore rules.
  Read ignore rules from files:               inherited from (global)
    .kopiaignore                  
  Scan one filesystem only:        true       (defined for this target)
```

I expect the list under "Read ignore rules from files" to be empty, but it instead contains the defaults.

**Comment by lupusA** [comment]
Hi @strager, 

maybe your setting was overridden by the global policy?

Cheers,
