### ISSUE TITLE
All commands running some very slow cleanup

### ISSUE THREAD

**Issue by PurkkaKoodari** [kopia/kopia#1613]
Most commands on my couple-months-old SFTP repo, including stuff like `kopia policy list`, are taking multiple minutes to finish. This seems to be due to a listing of `xn` blobs that is happening after the "real" command itself and taking longer than it to finish:
```
DEBUG [STORAGE] ListBlobs {"prefix": "xn", "resultCount": 247, "error": null, "duration": "4m21.609687406s"}
```

I did some snooping, and most of the time is spent in SFTP `ReadDir` calls, which are taking a couple hundred ms each to complete. Most of them are listing empty `xn*/***` directories.

The time is mostly spent on network or protocol overhead, as the OS file listings are happening basically instantly. (Using a regular `sftp` client shows the same overhead, so the slowness of file listings might not be due to Kopia.)

`kopia blob stats --prefix=x` results as requested on Slack:
```
Count: 484
Total: 44 MB
Average: 91 KB
Histogram:

        0 between 0 B and 10 B (total 0 B)
        3 between 10 B and 100 B (total 42 B)
      337 between 100 B and 1 KB (total 65.1 KB)
       71 between 1 KB and 10 KB (total 108.9 KB)
       28 between 10 KB and 100 KB (total 2.1 MB)
       37 between 100 KB and 1 MB (total 10.6 MB)
        8 between 1 MB and 10 MB (total 31.1 MB)
        0 between 10 MB and 100 MB (total 0 B)
```

**Comment by jkowalski** [comment]
As discussed on slack, you are using older, less optimal sharding format which has high list cost in case of SFTP:

Try doing this:

1. Stop all Kopia and KopiaUI that may be accessing the repository (this is critically important) 
2. Run this on the SFTP server:`kopia blob shards modify --path /repo/directory --default-shards=1,3`
