### ISSUE TITLE
cannot save manifest: error putting manifest: EOF: EOF when use kopia server start

### ISSUE THREAD

**Issue by ericma15** [kopia/kopia#1626]
hey, these days i try to use kopia server feature.
here is what i do.
1. i start a kopia server use my own cert behind a nginx (i write a systemd service).
2. i add user for the server(here i change the name to lowcase)
3. then  i enable acl .
3. i connect the server use low_case name
at this time, it works well. I can sees my snapshot. Then i snapshot a empty folder, it success.
So i try to snapshot my personal data. it show error like follow.
```
DEBUG snapshotted directory {"path": ".", "dur": "39.7019914s", "size": 4439570556, "files": 14856, "dirs": 15502, "errors": 0}
DEBUG memory: before auto maintenance allocated 83611392(+83256344) max 85411608, sys: 279576576 total 8230799736(+8162957408), allocs 4494033(+4485588) frees 4485443(+4481647) alive 17710(+3941), goroutines 11
DEBUG memory: after auto maintenance allocated 83268984(-342408) max 85411608, sys: 279576576 total 8230812000(+12264), allocs 4494079(+46) frees 4485845(+402) alive 17354(-356), goroutines 11
DEBUG memory: before close repository allocated 83268968(-16) max 85411608, sys: 279576576 total 8230825920(+13920), allocs 4494136(+57) frees 4485902(+57) alive 17354, goroutines 11
DEBUG closing GPRC connection to kopia.nas2.hi123.link:17893
DEBUG GRPC stream read loop terminated with rpc error: code = Canceled desc = grpc: the client connection is closing
DEBUG finished sweeping {"cache": "cache-storage", "duration": "3.9994ms", "totalRetainedSize": 0, "tooRecentBytes": 2267081, "tooRecentCount": 1629, "maxSizeBytes": 5242880000, "inUsePercent": 0}
DEBUG memory: after close repository allocated 83252256(-16712) max 85411608, sys: 279576576 total 8231637544(+811624), allocs 4501940(+7804) frees 4493736(+7834) alive 17324(-30), goroutines 5
DEBUG default (64KiB) - allocated 114466(857) chunks freed 114466 alive 0 max 857 free list high water mark: 857
DEBUG typical-contig (8MiB128B) - allocated 1634(3) chunks freed 1634 alive 0 max 3 free list high water mark: 3
DEBUG contig (16MiB128B) - allocated 0(0) chunks freed 0 alive 0 max 0 free list high water mark: 0
DEBUG memory: final allocated 83246168(-6088) max 85411608, sys: 279576576 total 8231652976(+15432), allocs 4502055(+115) frees 4493881(+145) alive 17294(-30), goroutines 5
ERROR cannot save manifest: error putting manifest: EOF: EOF
```
Then a try to snapshot these files to a local kopia repository. It works well.
So that seems it's my kopia server's problem. So can you help me to find out the reason?

**Comment by ericma15** [comment]
Hey ,tonight, i copy out my some of myfiles,then do the snapshot, it succeed. Then i copy left back,still fail.Then i copy some of these files back serveral times. It finally all succeed. That's strange. Although now I've snapshotted all my data,i still don't know what happened.

**Comment by ericma15** [comment]
> Hey ,tonight, i copy out my some of myfiles,then do the snapshot, it succeed. Then i copy left back,still fail.Then i copy some of these files back serveral times. It finally all succeed. That's strange. Although now I've snapshotted all my data,i still don't know what happened. in before fail log,i find `DEBUG GRPC stream read loop terminated with rpc error: code = Canceled desc = grpc: the client connection is closing`,maybe these caused?

in nginx log,i find the season
```
 [error] 369014#369014: *61301 client intended to send too large chunked body: 2147503188 bytes while sending request to upstream, client:
```
So, how can i limmit the size?

**Comment by jkowalski** [comment]
Something one the proxy is misconfigured, but I don't really know much about nginx proxying of grpc to suggest a fix.

**Comment by ericma15** [comment]
```
client_max_body_size 2048M;
client_body_buffer_size 2048M;
```
i set nginx max body to 2G. Is kopia will transfer data with length of 2G at one time?

**Comment by jkowalski** [comment]
The GRPC API is a stream, possibly of unbounded size (so when snapshotting 10 GB of new data, it will be likely 10 GB or more), through which messages are exchanged in a bidirectional manner.

Maximum message size is currently set to 20 MiB here (this is higher than max output of a splitter, which is 16 MiB):

https://github.com/kopia/kopia/blob/13ed6bb81c730f10a45a31b6d8c9ece4d52b9d7d/repo/grpc_repository_client.go#L37

**Comment by ericma15** [comment]
ok,i'll do some test

**Comment by ericma15** [comment]
I see old vesrion nginx with grpc can cause this. So i upgrade nginx, But still cause this error.
```
 707268#707268: *5 client intended to send too large chunked body: 2147543445 bytes while sending request to upstream, client: xx.xx.xx.xx, server: xxx.xxx.xxx.xxx, request: "POST /kopia_repository.KopiaRepository/Session HTTP/2.0", upstream: "grpcs://127.0.0.1:51515", host: "xxx.xxx.xxx.xxx"
```
I find error in `POST /kopia_repository.KopiaRepository/Session`

**Comment by ericma15** [comment]
I finnal solve this probem with set `client_max_body_size 0;`. i think the config in doc can change to this.
```
server {
  listen 443 ssl http2;
  server_name mydomain.com;

  ssl_certificate_key /path/to/your/key.key;
  ssl_certificate /path/to/your/cert.crt;

  client_max_body_size 0;  # Allow unlimited upload size

 client_body_buffer_size 2048M; # you can set some buffer to increase speed.

  location / {
   grpc_pass grpcs://localhost:51515; # Adapt if your kopia is running on another server
  }
}
```

**Comment by ericma15** [comment]
Oh, i see you've change the doc. I'll close the issue. Kopia is a great software. Thank you.
