### ISSUE TITLE
Pull-based backups ?

### ISSUE THREAD

**Issue by nautik1** [kopia/kopia#1636]
Hello,

I would like to replace an old backup strategy with a tool like kopia, but I am unsure if my use case can be handled.

I have 2 servers and would like to use one of them as a "backup server" that connects to the other remote server and backup its files into a local repository.
In other words I would like to have a "pull-based" backup strategy while I see kopia's main use case is "push mode", where kopia gets local files and pushes them into a remote destination.

In my case, only the backup server can connect to the other server and **not the other way around**.

Looking at the documentation and playing with the cli, what I could see is:

- mount the remote filesystem using something like sshfs into the backup server, then run kopia to backup files "locally"; this is already possible I guess, but I have the feeling it might not be optimal as kopia is used to have the files to be locally accessible. Or is it?
- be able to specify a remote target when running `kopia snapshot create [source]`, where `source` includes the host to connect to?
- have a `repository sync-from <sftp|from-config>` command which would be the opposite of the existing `repository sync-to`; it would allow creating repository & snapshots on the backed up server, then pull the repository from the backup server.

Feedback about the above is welcome. Would the sshfs solution already be good enough, or would the other 2 ideas be relevant feature-request ideas?
Would anyone see another solution that I missed?
Would you see this topic relevant to address in the documentation (if I haven't missed it and it's already there)?

Have a good day :)

**Comment by jkowalski** [comment]
In principle, any filesystem-like source can be backed up - we currently support snapshotting local files and snapshotting other snapshots (this is used during the migration from one repository to another).

Snapshotting SFTP sources (and possibly others, such as s3 buckets, etc.) should  be possible but will probably require major effort, so for now `sshfs` is recommended.

**Comment by flokli** [comment]
It's not only sftp - it would be really nice if kopia could be used to back up remote destinations that don't provide a shell, without having to mount things locally.

Think of backing up files in a WebDAV endpoint, or a Google Drive. Could we use `rclone` to back up /from/ any rclone remote?

**Comment by Mirodin** [comment]
I would love for a pull feature to be available some day. My server is the backup target for my whole family and most are not very tech savy so I do not trust their devices. This is why I would never give them write access to my server. Right now I have a homegrown rsync system that pulls backups via SSH from their machines. This works but is not very efficient spacewise since renamed files get synced again.

**Comment by brechmos** [comment]
I can't agree more with how significantly helpful this would be for doing backups. Even just starting with an rclone source would be so helpful. Adding rclone to the source would enable backing up from almost any cloud storage.

For example:
```
kopia repository connect s3 ....
kopia snapshot create rclone:Dropbox:Documents/important
```

I understand that I could mount the `Dropbox:` via rclone, but by having the ability to do it right from the `kopia snapshot create` command would remove the step of maintaining the mount.

**Comment by marksie1988** [comment]
Maybe look at implementing something similar to how rsnapshot works, it uses rsync to do the backups and can also do remote backups without having to manually mount filesystems etc. works great, would be nice to have something similar in kopia

**Comment by matbgn** [comment]
What would be the macro steps to implement this feature (design principles) and would it be merged by the maintainers?

**Comment by jkowalski** [comment]
Kopia uses virtual file system for uploads. It’s in the fs package. In principle one can implement it on anything file system-like including SFTP, rclone remotes.

if it’s implemented we way to trigger opening such remote file system and passing it to the uploader (cli and ui work) and making sure it works with the policy system we have. 

I’d be certainly open to reviewing and merging such feature provided it fits with well with the rest of kopia. I can help guide whoever wants to implement it as well.

**Comment by matbgn** [comment]
Just a final comment to double down on what @jkowalski mentioned, and to say that this problem is easily solved with the following: 
- A pre-backup script
```
sshfs -o IdentityFile=~/.ssh/id_rsa \
USER@REMOTE_IP_ADDRESS:folder_to_be_backed_up_remotly destination_folder_locally_on_kopia_server
```

- A post-backup script (don't forget to close the connection to emulate a pull-based backup)
```
fusermount -u destination_folder_locally_on_kopia_server
```

**Comment by jlssmt** [comment]
> Just a final comment to double down on what @jkowalski mentioned, and to say that this problem is easily solved with the following:
> 
> * A pre-backup script
> 
> ```
> sshfs -o IdentityFile=~/.ssh/id_rsa \
> USER@REMOTE_IP_ADDRESS:folder_to_be_backed_up_remotly destination_folder_locally_on_kopia_server
> ```
> 
> * A post-backup script (don't forget to close the connection to emulate a pull-based backup)
> 
> ```
> fusermount -u destination_folder_locally_on_kopia_server
> ```

SSHFS does not work properly if kopia is inside a Docker container. Many tweaks necessary. It would be much better if Kopia would support this natively.

**Comment by jasonlessenich** [comment]
What's the state on this?

**Comment by jlssmt** [comment]
i get it to work

you need to add this to the kopia compose:

```yaml
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
```

and run this as an action before snapshot:
```bash
apt update && \
apt install sshfs -y && \
mkdir -p /mnt/oracle-opt && \
sshfs root@123.123.123.123:/opt /mnt/oracle-opt
```

you must not mount a docker volume in /tmp folder of the container as this conflicts with apt update
i created PR #4392 to install sshfs directly inside kopia and get rid of the first two lines of the bash script

**Comment by tobiasBora** [comment]
Btw, I have two remarks regarding the current system:
1. is it efficient to mount the system?
2. the pull-base backup also has an interest in term of security: with a push-backup, if the server to backup is corrupted, the adversary can typically also corrupt the backup, e.g. if an ssh key is present, mitigating the interest of this currently used method (ok, it is possible to install minio on the backup server, but then it is harder to setup as we need to find a way to redirect HTTP trafic to the backup device that may not have any public IP nor open ports…). On the other hand, with a pull-backup, if the server gets corrupted, the attacker cannot corrupt the backup device.
