### ISSUE TITLE
kopia mount error with fusermount

### ISSUE THREAD

**Issue by luboslives** [kopia/kopia#1648]
Just a quick fix - on CentOS 8 the `kopia mount` command runs into trouble looking for `fusermount`:

`ERROR mount error: mounting error: exec: "/bin/fusermount": stat /bin/fusermount: no such file or directory`

CentOS does come with `/bin/fusermount3` so maybe kopia could look for that as well before presenting an error?

The situation in the `bin` directory appears to be the same at the moment for Alma Linux, Rocky Linux and maybe other successors to CentOS 8.

I've created a symlink to no longer see the error:
`ln -s /bin/fusermount3 /bin/fusermount`

**Comment by TheWiresharkGuy** [comment]
@luboslives Thank you for the FIX! I've had the same issue on Oracle Linux 8.

**Comment by jkowalski** [comment]
Looks like this was fixed upstream. Let me upgrade `go-fuse` dependency to bring this to Kopia.
