### ISSUE TITLE
Backup process against disconnected drives results in an infinite loop

### ISSUE THREAD

**Issue by RavenMacDaddy** [kopia/kopia#1651]
Here's an example based on my own system.

1. Two external drives are normally connected, so the corresponding repositories load in KopiaUI.
2. Later, these drives are disconnected (in my case because of an unreliable HDD docking station), but the repositories remain active in KopiaUI, along with the scheduled tasks.
3. The tasks start, and even then the kopia.exe processes for the corresponding repositories don't notice that the (destination) drives are disconnected - so it creates an infinite loop of attempting to finish the task.

Not only that, but these processes take a LOT of CPU during this infinite loop.

On a Ryzen 3600 @ 4.2 GHz, each kopia.exe process is using consistently between 10-20% CPU, so in my case, about 20-40% CPU is being wasted on absolutely nothing.

I noticed this was happening since I heard my CPU fan go up, and there it was.

Connected the drives again, and the task could continue as normal.

**Comment by jkowalski** [comment]
I'm guessing it's the same as #1652. The fix should help with both issues.
