### ISSUE TITLE
Problems updating from apt repository

### ISSUE THREAD

**Issue by nickdford** [kopia/kopia#1657]
Hi there!

We're currently getting the following error on all Ubuntu servers when running apt update:
```
W: No Hash entry in Release file /var/lib/apt/lists/partial/packages.kopia.io_apt_dists_stable_InRelease
E: The repository 'http://packages.kopia.io/apt stable InRelease' provides only weak security information.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Attempted to remedy by removing the /var/lib/apt/lists/partial/packages.kopia.io_apt_dists_stable_InRelease file, but the same error is returned after another apt update.

Let me know if there is any further information required or if there is anything i can do to help.

N

**Comment by datenleck** [comment]
I have the same issue. 

Then I fetched the binary and installed with  dpkg -i kopia_0.10.0_linux_armhf.deb
