### ISSUE TITLE
Unable to delete path/snapshot, KopiaUI just keeps syncing it.

### ISSUE THREAD

**Issue by hillbicks** [kopia/kopia#1662]
Hi there,

first of all, a big thanks for this piece of software, it seems a huge step up from my current backuppc solution. Anyway, after playing around a bit, I wanted to clean up my testing mess. Here is my setup:
kopia repository server v.0.10.0 (I know v.0.10.1 is out, but changelog doesn't seem related to my issue)
kopia client v.0.10.1 arch linux 

repo server is connected to filesystem and I can connect from the client, add a snapshot, rerun, etc. That is all working fine. In the beginning I added to subdirs from my home dir to test around a bit. Now I want to add /home and run some speed tests, unfortunately, I'm unable to delete the previous two snapshots. 

I deleted the manifests from these snapshots after listing them
kopia snapshot list --json
kopia snap delete xxxxxxx xxxxxxxx

On the repo server I ran kopia maintenance run --safety=none in order to delete everything. 

All is good and well, kopia snapshot list --json doesn't list a snapshot anymore. 

I even tried this with kopiaUI closed and starting it after deleting the snapshots. But guess what, the two snapshots are still in there and kopia immediately begins to sync the two snapshots. Currently I'm unable two delete these two snapshots and I  don't understand why. Is this a bug or am I too stupid to wrap my head around it?

Thanks in advance guys!

**Comment by jkowalski** [comment]
This is now possible in the UI - see #1730

**Comment by gkzsolt** [comment]
Hello,

What about the command line? I cannot delete the repositories I created? Seems a basic requirement.

I did not install the UI, I like to work from terminal. And my repositories are on a server...
