### ISSUE TITLE
setup: during upgrade of KopiaUI we don't stop running processes (was since v0.10(.1): Repositories stuck at 'Starting up' for KopiaUI)

### ISSUE THREAD

**Issue by RavenMacDaddy** [kopia/kopia#1666]
Noticed that my repositories connected on KopiaUI are stuck at starting up despite restarts and confirming that all drives are connected for good measure - even if repositories should be completely individual, it's worth mentioning.

![image](https://user-images.githubusercontent.com/67732686/149650152-00115d17-650f-41b2-8d6f-8fed207e1c6b.png)

Checking the configs in AppData, I personally don't notice something that looks odd that might cause issues.

![image](https://user-images.githubusercontent.com/67732686/149650169-74096dc6-41f2-45a7-9fce-a4a9c675fd8f.png)

EDIT: Tried deleting different files in appdata\roaming\kopia since KopiaUI is still getting stuck, even when no repositories are defined; it just opens a window to connect to a new repository, but it keeps being blank;

![image](https://user-images.githubusercontent.com/67732686/149650879-e2970eba-eec5-4220-ac44-43193e7dd16f.png)

EDIT2: After installing v0.10.1 again by downloading the release from this GitHub and installing over the current one, the repositories are loading as intended - thus the risk being that users upgrading from a previous version, like I did, seemingly from v0.9.8 checking 'repository.config.update-info.json' in appdata\roaming\kopia while troubleshooting this, might run into the same issue where repositories can't load as intended and just get stuck at 'Starting up'.

**Comment by jkowalski** [comment]
Do you by any chance have logs from those sessions (`appdata/roaming/kopia-ui/main.log` from kopiaui and relevant `cli-logs` from `appdata/local/kopia/cli-logs`)

**Comment by RavenMacDaddy** [comment]
[logs.zip](https://github.com/kopia/kopia/files/7877580/logs.zip)

[cli-logs.zip](https://github.com/kopia/kopia/files/7877586/cli-logs.zip)

Here's what I could gather. Tell me if that's not enough and be specific and I'll try again.

**Comment by jkowalski** [comment]
Ok, so the logs are not helpful, but I think I know what might have happened - as you were upgrading KopiaUI, it could be that previous version was still running and on Windows you can't easily replace running executables, so the new KopiaUI ended up with an old server binary? Because there was a breaking change in the protocol that KopiaUI uses to start/stop kopia, v0.10 could not talk to v0.9.x kopia.exe binary.

**Comment by RavenMacDaddy** [comment]
Makes sense. Does that mean the current update process doesn't properly quit all the running kopiaUI processes?
