### ISSUE TITLE
Noobie question: restore to undo new file

### ISSUE THREAD

**Issue by Shadowgraphs** [kopia/kopia#1669]
Hello, I'm first time use the linux backup program, then I found kopia. It looks very good. 
But there is a trouble and I can't solve by kopia document and goole:

**How to restore and undo new file.**

_My English is not so good, hope you can understand what I mean._

What I do:
I create a repository at local
`
sudo mkdir /home/kopia
sudo kopia repository create filesystem --path /home/kopia
`
make a test folder with a file
`
sudo mkdir /home/test
sudo touch /home/test/a.sh
`
then make a snapshot
`
sudo kopia snapshot create /home/test/
`
find the snapshot id
`
kopia snapshot list /home/test/
`
**create a new file in test folder**
`
sudo touch /home/test/b.sh
`
restore
`
kopia restore $id  /home/test/
`

What I expect：
/home/test/ just have a file 'a.sh'
The 'b.sh' I create after snapshot should not exist.

What happen:
/home/test/ have two file 'a.sh' and 'b.sh'

**Comment by Shadowgraphs** [comment]
All kopia command begin with sudo,  and not error.

**Comment by jkowalski** [comment]
This is by design, you're restoring to an existing directory, no existing files are deleted.
