### ISSUE TITLE
Simplify flags for running kopia server purely as a sheduler of backups.

### ISSUE THREAD

**Issue by cooperaj** [kopia/kopia#1670]
I'm running kopia on a VPS and wanted to use it as a server for scheduling purposes. I realise I could use cron with something like `kopia snapshot --all` but coming from having it running on my laptop/desktops I quite like the idea of having the control of backup scheduling under kopia's control.

Since I do not need any UI or remote control of the service I asked in slack what the best way to run it was and was given 

`kopia server start --insecure --no-ui --no-legacy-api --no-grpc --no-control-api`

As you can see this is quite a lot for the task. Perhaps a new flag as an alias of these? Something like `kopia server start --scheduler-only`.

**Comment by cooperaj** [comment]
Maybe leaving the `--no-control-api` out would still allow the local `server` commands to work.

**Comment by MACscr** [comment]
you can also just create a simple bash script to start things. you would typically want a systemd setup anyway to start it the way you want on boot too

**Comment by cooperaj** [comment]
I'm currently using 

```[Unit]
Description=Kopia Server
After=network.target

[Service]
User=root
WorkingDirectory=/root
ExecStart=/usr/bin/kopia server start --log-dir-max-files=7 --insecure --no-ui --no-legacy-api --no-grpc --no-control-api
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

Which seems to work well.
