### ISSUE TITLE
KopiaUI: With tasks running, multiple repositories' windows produce visual glitches

### ISSUE THREAD

**Issue by RavenMacDaddy** [kopia/kopia#1673]
![image](https://user-images.githubusercontent.com/67732686/150629794-04dd6b5a-a8e5-4366-b871-9ad4de833892.png)

Basically as long as tasks are running at least for one repository, when multiple repository windows are open, it seems like the process of updating the UI done by the app itself (that's, not manually, if that's even a thing - simply for clarification) results in visual glitches.

**Comment by jkowalski** [comment]
Something is very wrong with your video card, driver, RAM, CPU or something else entirely - either way - it appears to be hardware related.

KopiaUI is simply rendering HTML in embedded Chromium browser and all the artifacts you're seeing are beyond what we can control.

**Comment by RavenMacDaddy** [comment]
Haha, it sounds harsh, but I know it's true. 

I started having issues like this when I went from a GTX 660 to my current at the time of writing GPU GTX 1080, and no matter which GPU driver or other software like OS and setup surrounding it, some sorts of rendering like this causes the issue.

Closing.
