### ISSUE TITLE
s3 with specific region

### ISSUE THREAD

**Issue by flibustenet** [kopia/kopia#168]
I'm trying to use s3 compatible object storage of scaleway.com.
```
$ kopia repository create s3 --access-key ... --secret-access-key ... --bucket test --endpoint=s3.fr-par.scw.cloud
kopia: error: unable to get repository storage: 
The authorization header is malformed; 
the region 'us-east-1' is wrong; expecting 'fr-par'
```

Is it possible to configure the region ?

edit: I have the same problem with aws if i'm not using us-east-1

**Comment by jkowalski** [comment]
Can you verify that #169 fixes your issue? I also use S3-compatible provider, but it does not require the region.

**Comment by flibustenet** [comment]
I confirm, it's ok with aws eu-central-1 and s3 scaleway fr-par.
If it help you can have free 75Go at scaleway (like everybody).
