### ISSUE TITLE
KopiaPersister code no longer being used

### ISSUE THREAD

**Issue by adowair** [kopia/kopia#1696]
Since the introduction of `KopiaPersisterLight` in #1155, it doesn't look like the original `KopiaPersister` struct is being used, except in the unit tests for it. Perhaps we should remove this code and refactor `KopiaPersisterLight` to be the only type of persister in our code. This would lessen confusion as to which component does what.

**Comment by carlbraganza** [comment]
This interface is public and in use in derived code.
