### ISSUE TITLE
sync-to re-uploads all data; does not detect common blobs

### ISSUE THREAD

**Issue by stephen322** [kopia/kopia#1711]
Whether using sftp or filesystem, with --times or without, sync-to wants to re-upload just about all data:

Looking for BLOBs to synchronize...
  Found 35608 BLOBs in the destination repository (822.3 GB)
  Found 34679 BLOBs (800.9 GB) in the source repository, 34340 (793.1 GB) to copy
  Found 0 BLOBs to delete (0 B), 339 in sync (7.8 GB)

Potentially related to #1145

Also, is sync-to functionally the same as rsync?

**Comment by celogeek** [comment]
Hi. I've got the same issue.
It looks like the "--times" doesn't apply it properly.
I manage to fix this, using rsync command.
You need to have the save split between both repos, then:

```
rsync -av --size-only --info=progress2 --delete --no-i-r SOURCE/ DEST/
```

This will fix times, and skip blog of the same name and size.
It's pretty fast if you are indeed already sync.

**Comment by celogeek** [comment]
Oh god, actually it make it worse. it ask to resync everything.

**Comment by celogeek** [comment]
It looks like the option
```
--no-times --no-updates
```

works. so it doesn't reupload existing blog.
I don't know if blog can be rewrited with the same name. if so, this is not a good way to sync.

I will use rsync until this get fixed.
