### ISSUE TITLE
[Feature Request] Information about size of backup 

### ISSUE THREAD

**Issue by lordraiden** [kopia/kopia#1722]
Be able to see per snapshot, per path and per repository the total space of files backed up and the real space on disk of the backup. In addition to this compression ratios or other information might be useful

**Comment by mattzab** [comment]
I would like this as well. Though I can't contribute code, I can raise demand.

**Comment by jkowalski** [comment]
Computing incremental snapshot size is now possible using `kopia snapshot list --storage-stats`.

**Comment by tio-trom** [comment]
Does this with withing the KopiaUI? If not will it be implemented?

**Comment by televisi** [comment]
> Does this with withing the KopiaUI? If not will it be implemented?

Agree, it would be great if we have this information available from KopiaUI (through docker)
