### ISSUE TITLE
[Feature Request] Possibility to choose several paths to snapshot

### ISSUE THREAD

**Issue by lordraiden** [kopia/kopia#1725]
When you start a new policy/snapshot you can only choose one path
![imagen](https://user-images.githubusercontent.com/17175395/152564690-0358caa2-fbef-4f17-bbfc-3263d1918042.png)
This is very limiting and you might end up doing several different snapshots with it's own but similar policy for the same purpose.

For example the backup of a "system" requires 8 different paths, If this where available I could do this with a single policy and any backup or restoring operation would be much more efficient.
Right now I have to do 8 policies and queue up them like 2:00, 2:10, 2:15,.... so I don't have 8 threads of backup overlapping over the same mechanical drive, and it takes more time, and more settings to manage.

**Comment by C-Duv** [comment]
A workaround I tried was to create a dedicated folder that contains symbolic links for each paths to snapshot:

```
C:\
  + Users\
    + JDoe\
      + Documents\
      + Images\
      + Music\
    + FooBar\
      + Coding\
      + Documents\
      + Images\
      + Music\
  + System32\
    + drivers\
      + etc\
  + MountPoints_For_Kopia\
    + JDoe_Documents --> C:\Users\JDoe\Documents
    + FooBar_Coding --> C:\Users\FooBar\Coding
    + host_file --> C:\System32\drivers\etc\hosts
```

Here, if I want to snapshot JDoe's documents, FooBar's code and the `hosts` file I could theoretically snapshot `C:\MountPoints_For_Kopia\`

But Kopia seems to ignore those symlinks…
