### ISSUE TITLE
"kopia logs" does not show tasks from (http) ui scheduled tasks

### ISSUE THREAD

**Issue by stephen322** [kopia/kopia#1756]
Unable to find the location of logs from scheduled tasks.

**Comment by jkowalski** [comment]
That is currently by design - `kopia logs` shows low-level logs only.

**Comment by sparfenov** [comment]
@jkowalski thanks, but how can i debug scheduled tasks?
where to search for logs?
its very convenient to have centralized schedule, but we are confused how debug if server doesn't start snapshot when it should be scheduled
