### ISSUE TITLE
ERROR mount error: mounting error: no FUSE mount utility found

### ISSUE THREAD

**Issue by ChantMee** [kopia/kopia#1757]
The program is running on a macOS system with version 11.5.2. I followed the tutorial to create a repository and created a snapshot for the Download folder. But when I use the 'kopia mount kb9a8420bf6b8ea280d6637ad1adbd4c5 /tmp/mnt' command, the program prompts an error: ERROR mount error: mounting error: no FUSE mount utility found. I went to the Internet to find related issues and found no information.
PLEASE HELP ME.

**Comment by jkowalski** [comment]
Have you installed MacFuse - https://osxfuse.github.io ?

**Comment by ChantMee** [comment]
> 

Wow! What is that, does the program need that? I will try to install it, thank you!

**Comment by jkowalski** [comment]
It's a mounting tool used by Kopia and other programs that provide custom filesystems.

**Comment by ChantMee** [comment]
> It's a mounting tool used by Kopia and other programs that provide custom filesystems.

ok, problem solved, thanks a lot!

**Comment by jkowalski** [comment]
no problem.
