### ISSUE TITLE
FR: Kopia GUI support for custom notes poer snapshot

### ISSUE THREAD

**Issue by gerroon** [kopia/kopia#1769]
Hi

It would be so amazing if the user can add custom notes/lines per snapshot in the GUI so that the snapshots are bit more legible.

thanks

**Comment by jkowalski** [comment]
Isn't this what you're looking for? https://github.com/kopia/kopia/pull/1748 It's already in v0.10.5.

**Comment by gerroon** [comment]
I did not know that it existed, please let me test this feature.

**Comment by gerroon** [comment]
@jkowalski 

Ok this looks really good except that I do not know what I am looking at in the GUI because the notes are not visible by default, one has to click/hover over them one by one to see what they are all about.

It would be nice if the notes are exposed to certain degree to make it more legible,

thanks
