### ISSUE TITLE
Video that introduces the GUI does not show one how to _restore_ files

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kopia/kopia#1773]
. . and indeed I have not found anything in the GUI interface that allows one to do that. Since a backup is useless if one cannot restore from it, then the rudiments of restoring should be covered in the video, even if, as seems to be the case, [one must restore from terminal](https://kopia.io/docs/mounting/).

**Comment by adowair** [comment]
Hey @LinuxOnTheDesktop, thanks for bringing this up. Restoring from the GUI is a multistep process:

1. First, we create a repository and take a snapshot of something. That snapshot should show up in this form: <img width="1203" alt="Screen Shot 2022-02-25 at 3 36 05 PM" src="https://user-images.githubusercontent.com/26861509/155817497-d2241eae-63b1-4aa2-ab25-c2cb2e521441.png">
2. Click on the "Path" link of the snapshot (boxed in red in the picture above). This will take you to a page showing all the snapshots taken for the the given path (at the moment, I've only taken one snapshot of my `~/Downloads/` folder.
<img width="1202" alt="Screen Shot 2022-02-25 at 3 37 52 PM" src="https://user-images.githubusercontent.com/26861509/155817525-95ef729e-7d14-4039-88f7-912fc42636ac.png">

3. Click on the "Start time" link of the snapshot (boxed in red in the picture above). This will take you to a page showing you the contents of the snapshot (I have a folder in my `~/Downloads/` called `Policies & Agreements`.
<img width="1201" alt="Screen Shot 2022-02-25 at 3 39 34 PM" src="https://user-images.githubusercontent.com/26861509/155817534-077cc4ae-3c99-4825-9109-18affcd5d095.png">

4. Clicking the "Restore" button in cyan near the top will take you to a page where you can configure and execute restoration of the snapshot.
<img width="1257" alt="Screen Shot 2022-02-25 at 3 40 56 PM" src="https://user-images.githubusercontent.com/26861509/155817546-9d31a35f-07cf-410a-9971-c94d3984220c.png">

I hope this was helpful. If you submit a PR to add some more documentation on this, that'd be superb.

**Comment by LinuxOnTheDesktop** [comment]
Thank you. That _was_ helpful. Still, in the interim I discovered how (even in Windows) a terminal can mount and then restore.

Seemingly your step 3 is rather undiscoverable. So changes to the following do appear desirable: (1) documentation; (2) UI.

On 1: creating a pull request in order to try to improve documentation is non-trivial for me. (I know the project barely and even on my Linux PCs I have poor git fu.) Still, _it seems evident that the video or else the page containing the video should contain some sort of instruction on restoring_. And here on this very page you've begun upon creating that documentation.

On 2: a start would be adding a tooltip, which speaks of restoring, when hovering above the path field that you mention.
