### ISSUE TITLE
The relevant documentation page should mention that on Windows (and Mac?) restoring/mounting requires knowing _the path_ to the relevant executable

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kopia/kopia#1774]
Seemingly [one is meant to mount a snapshot to restore from it](https://kopia.io/docs/mounting/) and seemingly one can mount only via terminal. The aforelinked instructions include the commands to run if one is using Windows. Yet, on Windows, those commands will fail unless one has added the relevant executable to one's path. Also, one could - though the instructions do not mention this - navigate to the directory containing the executable (and run a slightly modified version of the command) or else specify the full path.

Finding the relevant executable (again, on Windows) was harder than it should be. Its path turned out to be: `C:\Users\<myUser>\AppData\Local\Programs\KopiaUI\resources\server\kopia.exe`.

**Comment by jkowalski** [comment]
There are both mount and restore options in the UI. Is that not working for you?

**Comment by LinuxOnTheDesktop** [comment]
@[jkowalski](https://github.com/jkowalski)

'There are both mount and restore options in the UI. Is that not working for you?' Now that I have discovered that the GUI can mount and restore, and _how_ the GUI can mount and restore, those things are working with me. So the actual problem here seems to be a lack of documentation about things that the GUI can do. [This issue](https://github.com/kopia/kopia/issues/1773) is about that particular lack.
