### ISSUE TITLE
SFTP repository won't work if remote SSH server using non standard 22 port

### ISSUE THREAD

**Issue by CompuRoot** [kopia/kopia#1777]
**Kopia version:** v0.10.5
**Test systems (both SFTP server and subject for backup):** Debian 11 x86_64

## Server side
**SFTP server settings (sshd_config)**:
```
### Chrooted environment with SFTP only allowed access and using only public key authentication
Subsystem   sftp    internal-sftp

Port 12345
UsePAM no
UseDNS no
LoginGraceTime 20

PubkeyAuthentication yes
PasswordAuthentication no
ChallengeResponseAuthentication no
HostbasedAuthentication no

Match group backup
  ChrootDirectory /srv/sftp
  ForceCommand internal-sftp
  X11Forwarding no
  AllowTcpForwarding no
  AllowAgentForwarding no
```
Backup _"user"_ on SFTP server has no shell access (user's shell is `/bin/false`)

---

## Backup client

```bash
### Attempt to create repository

kopia repository create sftp    \
  --host FQDN-of-SFTP-server    \
  --port 12345                  \
  --username kopia              \
  --key-data "-----BEGIN OPENSSH PRIVATE KEY-----....." \
  --known-hosts-data="[1.0.0.1]:12345 ssh-ed25519 xxx"  \
  --path /srv/sftp/kopia
```

Result of execution:
```
kopia: error: can't connect to storage: must provide either --sftp-password, --keyfile or --key-data, try --help
```

## Workaround
Use `--external` to get help `kopia` with the same call as above:

```bash
kopia repository create sftp    \
  --host FQDN-of-SFTP-server    \
  --port 12345                  \
  --username kopia              \
  --key-data "-----BEGIN OPENSSH PRIVATE KEY-----....." \
  --known-hosts-data="[1.0.0.1]:12345 ssh-ed25519 xxx"  \
  --path /srv/sftp/kopia        \
  --external                    \
  --ssh-command=/usr/bin/ssh    \
  --ssh-args="-p12345"
```

## Resume
- Option `--port` doesn't work

Also, in case one need to pass some extra options to `ssh` client via `--ssh-args` using workaround shown above, one will fail, due to any space that will be used as option's argument in `--ssh-args`  will cause error, so for example legitimate use of option 
```bash
--ssh-args="-p  12345"
```
will  ended with:
```
kopia: error: can't connect to storage: unable to open SFTP storage: error establishing connecting: error creating sftp client pipe: EOF
```
and the log file:
```
DEBUG sftp launching external SSH process /usr/bin/ssh -p 12345 kopia@FQDN-of-SFTP-server -s sftp
```

## Suggestion:

I read issues [#414](https://github.com/kopia/kopia/issues/414) and [#500](https://github.com/kopia/kopia/issues/500) and suggesting to change logic. In case if option `--external` is in use, then ignore completely (or even throw a warning notice) options:
- `--host`
- `--port`
- `--username` 
- `--key-data` and `--keyfile`
- `--known-hosts-data` and `--known-hosts`

and relay completely on user's setting supplied via `~/.ssh/config` (`ssh_config (5)`) which user may supply via `-F` option of `ssh` using  `--ssh-args`.
This way, no need to parse anything, call to `ssh` will be reduced to `ssh alias -s sftp` (where `alias` is keyword such as `my-server` in `Host` inside of `~/.ssh/config`). It will allow to use ALL settings of `ssh` program and will simplify calling.
If it is unacceptable for some reason, do not form/build also `ssh` options as user@host and use instead option `-l` for login name to get rig of user@host that limiting authentication in some cases.

Thanks a lot for your work, `kopia` is really one of the most advanced backup program as of now.
I wish I can "speak" golang and make PR, but unfortunately I cant, so for now only bug report.

**Comment by mike503** [comment]
slightly related, and I believe this is due to an issue with the go crypto library (possibly this bug[1]), it doesn't like ecdsa keys. I too run SSH on an alternate port, that didn't seem to be the issue, swapping out --known-hosts from a file to --known-hosts-data "[1.2.3.4]:222 ecdsa-sha2-nistp256 ..." seems to make it work.

there might be a couple bugs squashed by addressing this.

1. https://github.com/golang/go/issues/29286

**Comment by CompuRoot** [comment]
@mike503 I don't think it is because of `ecdsa` since I tried to disable it in `sshd_config` and tried separately with `ed25159` as well with `rsa`. The point I tried to make is - if option `--external` is used, then `kopia` shouldn't try to build ssh connection string mixing it with own options as well with external, but simply delegate this job to **external**, as option stated. This way one can use all features of native `ssh` program and managing connection either via `~/.ssh/config` or bypass parameters over `--ssh-args`. The only `kopia`'s job would left is to add `-s sftp`. This way would be eliminated confusion - why one need to supply username, port, host if it's already should be supplied over ssh config or via args. I think such logic will be more accurate because no need to combine/mix `kopia`'s options with external `ssh` program that might conflict between each other. If it is `--external`, so all related should be also all external.

**Comment by mike503** [comment]
@CompuRoot understood. however, your issue was logged as simply "does not work if SSH is on an alternate port" so you tried using --external instead (which is what I tried too, except the official Docker container has no external ssh client it seems) but I was able to find that other issue with the go library and tried changing what I said - and it works. My SSH is on an alternate port and I can connect with the built-in ssh client.

**Comment by CompuRoot** [comment]
> but I was able to find that other issue with the go library and tried changing what I said - and it works. 
@mike503 Thanks for clarification !

**Comment by stewartadam** [comment]
For those finding this issue via Google, this applies to the GUI as well. The Port selector stays active when checking "external" even though it's ignored. Adding `-pXYZ` into the command arguments fixes the issue.

**Comment by BLu85** [comment]
I personally find Kopia SFTP unusable.

It is extremely complicated for no reason.
The SFTP protocol is well established and works pretty well on Linux, MacOs and Windows.
There should be no need for workarounds, it should just work.

This command works on the terminal and it is very simple:

`sftp -P xyz -i .ssh/mykey myuser@192.168.n.m `

The same does not work for Kopia, which complaints about:
- type of key ed25519 not accepted
- Port number not accepted
- known_host file missing
- path missing
- "you name it" missing
- ...

I think the SFTP connection should be kept simple, without overcomplicate it.
And this is exactly what puts people off from using a software (me in this case about kopia).

Luca

**Comment by AL-33** [comment]
Hi,
20 minutes ago, with Kopia-ui version 0.22.3, I was unable to connect using the standard method.

So I had to check the "Launch external password-less SSH command" box and set the following options in order to connect: 
SSH Command: `ssh`
SSH Arguments: `-p 2022 -i /home/usr/Documents/ssh/usrkey_openssh.pem`
and it worked !
