### ISSUE TITLE
Documentation: Please add comparison to Restic and Borgbackup

### ISSUE THREAD

**Issue by labeldevops** [kopia/kopia#1809]
Why does Kopia exist, why is it better than e.g. Restic or Borgbackup, why should I use it?

These questions should be answered, best way to do this would be a comparison that makes it easier for users to understand why they should prefer Kopia.

**Comment by wechsler42** [comment]
Well, one of the obvious differences is the cross-platform GUI (Kopia-UI for Windows, macOS, Linux Desktop Environments) which is developed by the lead developer - and yes, thanks again for offering this!

**Comment by cristihcd** [comment]
Here is a comparison (benchmark) based on https://github.com/gilbertchen/benchmarking

### Results (linux kernel):

> Here are the elapsed real times (in seconds) as reported by the time command, with the user CPU times and system CPU times in the parentheses:

|                | **Duplicacy**     | **Restic**        | **Borg**           | **Kopia**          |
|----------------|-------------------|-------------------|--------------------|--------------------|
| Initial backup | 3.8 ( 4.6 , 1.3 ) | 4.1 ( 3.9 , 2.7 ) | 14.2 ( 4.6 , 8.8 ) | 5.3 ( 6.8 , 14.4 ) |
| 2nd backup     | 1.5 ( 1.3 , 0.5 ) | 2.4 ( 2.6 , 0.6 ) | 5.9 ( 4.7 , 1.1 )  | 0.9 ( 1.5 , 0.7 )  |
| 3rd backup     | 2.4 ( 2.7 , 0.5 ) | 3.2 ( 3.4 , 1.0 ) | 9.1 ( 4.1 , 4.8 )  | 2.0 ( 3.6 , 2.0 )  |
| 4th backup     | 1.3 ( 1.1 , 0.2 ) | 2.4 ( 2.6 , 0.6 ) | 5.4 ( 4.8 , 0.6 )  | 0.6 ( 0.8 , 0.6 )  |
| 5th backup     | 2.4 ( 2.6 , 0.7 ) | 3.2 ( 3.2 , 1.2 ) | 9.0 ( 4.2 , 4.5 )  | 2.1 ( 4.0 , 1.7 )  |
| 6th backup     | 1.6 ( 1.5 , 0.4 ) | 2.6 ( 2.8 , 0.7 ) | 6.2 ( 4.9 , 1.3 )  | 1.0 ( 1.6 , 0.7 )  |
| 7th backup     | 1.4 ( 1.4 , 0.2 ) | 2.5 ( 2.7 , 0.6 ) | 5.9 ( 4.8 , 1.0 )  | 0.8 ( 1.1 , 0.7 )  |
| 8th backup     | 2.6 ( 2.9 , 0.7 ) | 3.3 ( 3.5 , 1.3 ) | 9.7 ( 4.2 , 5.1 )  | 2.3 ( 4.3 , 2.1 )  |
| 9th backup     | 1.7 ( 1.6 , 0.4 ) | 2.7 ( 3.0 , 0.8 ) | 6.6 ( 5.2 , 1.3 )  | 1.1 ( 1.6 , 1.0 )  |
| 10th backup    | 2.4 ( 2.8 , 0.5 ) | 3.3 ( 3.5 , 1.3 ) | 9.5 ( 4.1 , 5.1 )  | 2.3 ( 4.3 , 1.6 )  |
| 11th backup    | 1.7 ( 1.5 , 0.5 ) | 2.6 ( 3.0 , 0.8 ) | 6.3 ( 5.0 , 1.3 )  | 1.1 ( 1.6 , 0.9 )  |
| 12th backup    | 2.7 ( 3.0 , 0.7 ) | 3.4 ( 3.6 , 1.5 ) | 9.7 ( 4.2 , 5.2 )  | 2.5 ( 4.4 , 2.0 )  |

### Sizes (final):

867M	/benchmark/test/linux-attic-storage
835M	/benchmark/test/linux-duplicacy-storage
631M	/benchmark/test/linux-kopia-storage
2.2G	/benchmark/test/linux-restic-storage

Settings: Kopia: parallel=12, compression=zstd

This was not a rigorous benchmark, just a quick test. It was run on a Debian 11 VM, 16GB RAM, 12 CPU in VMWare Workstation.

Kopia seems to be as fast or faster than Duplicacy, with a significant advantage in size, and also number of file chunks created (88 files in kopia repo vs 1822 in duplicacy repo).

**Comment by cristihcd** [comment]
Additional comparison with Duplicacy which I used previously for a Postgresql database. Repo converted from Duplicacy.
- Original (source) size: 282GB
- Duplicacy repo: 38 snapshots, 546GB, 128000 files
- Kopia repo: 38 snapshots, 313GB, 15000 files

Blob stats:
```
Count: 15091
Total: 313 GB
Average: 20.7 MB
Histogram:

        0 between 0 B and 10 B (total 0 B)
        1 between 10 B and 100 B (total 30 B)
        5 between 100 B and 1 KB (total 1.9 KB)
       20 between 1 KB and 10 KB (total 73.5 KB)
      222 between 10 KB and 100 KB (total 8.1 MB)
      108 between 100 KB and 1 MB (total 56.9 MB)
       84 between 1 MB and 10 MB (total 363 MB)
    14651 between 10 MB and 100 MB (total 312.6 GB)
```

Content stats
```
Count: 646272
Total Bytes: 1.6 TB
Total Packed: 312.9 GB (compression 79.9%)
By Method:
  (uncompressed)         count: 20287 size: 464.1 MB
  zstd-better-compression count: 625985 size: 1.6 TB packed: 312.5 GB compression: 79.9%
Average: 2.4 MB
Histogram:

        0 between 0 B and 10 B (total 0 B)
      195 between 10 B and 100 B (total 15.7 KB)
    19019 between 100 B and 1 KB (total 5.4 MB)
     1653 between 1 KB and 10 KB (total 5.6 MB)
     7071 between 10 KB and 100 KB (total 468.2 MB)
   575784 between 100 KB and 1 MB (total 244.4 GB)
    42550 between 1 MB and 10 MB (total 68.1 GB)
        0 between 10 MB and 100 MB (total 0 B)
```

**Comment by gc-ss** [comment]
- What are some situations/scenarios where Borgbackup can corrupt backups
- What are some situations/scenarios where Borgbackup can fail to detect corruptions in the backups it has taken
- What are some situations/scenarios where Borgbackup can corrupt restores/fail to do proper restores
- What are some situations/scenarios where Kopia can corrupt backups
- What are some situations/scenarios where Kopia can fail to detect corruptions in the backups it has taken
- What are some situations/scenarios where Kopia can corrupt restores/fail to do proper restores

**Comment by LanceHaverkamp** [comment]
I really wanted to love Restic, but I just couldn't, for one simple reason: Restic uses file locks, which is a complete failure for Desktop & Laptop use. Close the lid on your laptop, and all future backups fail, until you manually delete the lock, and restart backups. Restic may be fine for a 24/7/365 server, running on a battery backup; but it's a complete failure for desktop & laptop use. I have been using Duplicacy with the web interface for a few years, and I am watching kopia with great interest.

**Comment by julio-lopez** [comment]
Folks are free to host their own comparison pages and benchmarks.
These comparisons should not be in the kopia documentation or README files.
