### ISSUE TITLE
Kopia Mac x86 crashes

### ISSUE THREAD

**Issue by mikkelfj** [kopia/kopia#1811]
All versions since 0.10.1, last seen on 0.10.6, crashes after install immediately or while UI is "starting up" connecting to a repository. On Macbook x86 using the dmg installer. Only output is: "The application quit unexpectedly".

**Comment by mikkelfj** [comment]
Likely a duplicate of https://github.com/kopia/kopia/issues/1750

**Comment by jkowalski** [comment]
What is the macOS version in this case?

**Comment by mikkelfj** [comment]
Catalina 10.15.7 (19H524)

**Comment by mikkelfj** [comment]
I'm not 100% sure the problem is also on 0.10.2, but as I recall, I backtracked versions after a crash on 0.10.5 back to the known good 0.10.1 version. There is a slight possibility that this is related to having created a repo with a specific earlier version of Kopia, in my case likely 0.10.1.

BTW: I also saw the issue with removed snapshot going into a loop: https://github.com/kopia/kopia/issues/1662, but I think it was on a test repo longer being used.

**Comment by santacruzskim** [comment]
Confirming the same on Mojave (10.14.6). Updated from KopiaUI 0.10.3 to 0.10.6 and now it crashes when launching KopiaUI.  

Rolled back to 0.10.3 and it's working fine again. Not really sure what troubleshooting steps to take at this point. Guess I'll wait for the next release and try again...

**Comment by mikkelfj** [comment]
I upgraded from Catalina to Big Sur, and also from Kopia 0.10.1 to 0.10.7. After that I have not seen crashes on startup.
I'll leave this issue open since that doesn't make the problem fixed on Catalina, but as as far as I am concerned, and so far, it seems to be working.

**Comment by santacruzskim** [comment]
I reluctantly upgraded to 0.10.7 to give it a try and it worked perfectly. No MacOS updates, just updated to the new KopiaUI build. I think this may be solved.
