### ISSUE TITLE
Suggestion: add `backup` to the GitHub project topics

### ISSUE THREAD

**Issue by ngirard** [kopia/kopia#1819]
... for increased discoverability.

Cheers !

**Comment by adowair** [comment]
Is this what you're referring to @ngirard:
<img width="398" alt="Screen Shot 2022-03-10 at 2 13 29 PM" src="https://user-images.githubusercontent.com/26861509/157763643-a7171402-79d3-4e55-9cbf-8d14979825a4.png">
Looks like we're already there 😄

**Comment by ngirard** [comment]
Jeez... I need more sleep. Sorry for the noise, @adowair !
