### ISSUE TITLE
[Feature request] Snapshot all at once

### ISSUE THREAD

**Issue by DutchEclipse** [kopia/kopia#1848]
In Kopia, you need to snapshot each directory one by one instead of doing it with a single command and or click. Could a feature be implemented to snapshot/backup all directories at once?

**Comment by xxxliqu1dxxx** [comment]
`./kopia snapshot create --all`
already does it.

**Comment by DutchEclipse** [comment]
> `./kopia snapshot create --all` already does it.

I see, i searched for keywords in the documentation and couldn't find it in there, Thanks.

**Comment by cadadr** [comment]
Hiya! I don't exactly know where to reports/requests for Kopia UI should go but would it be possible to add a button or something to that application for this functionality?
