### ISSUE TITLE
[Feature] Add parity data for data protection / restoration

### ISSUE THREAD

**Issue by theChaosCoder** [kopia/kopia#1865]
Hi, I think it would be great if kopia could automatically add/calulcate parity data. Similiar to what WinRar does for example. 
For big files (Old Family Videos) I usally use par2 (Mutipar Tool) with ~5% parity data and it already saved me bcs 1 bit as fliped a couple years ago.

This is the only feature I miss in all dedup backup tools such a restic, borg, attic, etc. 
Because kopia saves a file only once it will be damaged in all snapshots. With parity data this file could be repaired.

There is also a go package for par2 algo https://github.com/akalin/gopar

**Comment by xxxliqu1dxxx** [comment]
I think it would be a great idea as well. Other dedup backup tools have this implemented, such as duplicacy - it's called erasure coding: https://forum.duplicacy.com/t/new-feature-erasure-coding/4168 for more information. Basically splits files in 5 shards + 2 parity shards... you can change the ratio apparently but it does create extra overhead... in any case, it would be great for Kopia to support this as well, especially for non cloud backups where the storage provider (hdd) does not have any replication and/or storage protection.

**Comment by theChaosCoder** [comment]
Closing. Support was added in v12.
