### ISSUE TITLE
error: could not find a replica of a format blob

### ISSUE THREAD

**Issue by arminus** [kopia/kopia#1879]
When setting up a new snapshot for a Raspberry Pi4 and manually testing it for the first time, the entire Pi4 crashed, probably while going through the /sys path (which I forgot to exclude). That snapshot's target was a repository on an NFS mount.

Trying to connect to that repository now, I get this:

```
ERROR unable to initialize repository: unable to initialize repository: 
error opening repository:
unable to open repository:
unable to create shared content manager:
error loading indexes:
unable to open pack index "xn9_4e00d10c6bade9699d57ab9a753a54f8-s02862371057304f910e-c1":
invalid header: invalid header: incomplete read at offset 0, got 0 bytes, expected 8
```

Trying `kopia repository repair from-config --file=.config/kopia/repository.config --recover-format=yes` yields this:
```
kopia: error: could not find a replica of a format blob, try --help
```

I had used that repository for about 3 months without any issues.

**Comment by julio-lopez** [comment]
The `xn9_4e00d10c6bade9699d57ab9a753a54f8-s02862371057304f910e-c1` index blob may be corrupt. Perhaps it was not fully flushed by the NFS client before the crash.

Maybe move the corresponding file in the repo to a path outside the repo, and attempt to connect again.
