### ISSUE TITLE
AppImage hanging on startup

### ISSUE THREAD

**Issue by waldner** [kopia/kopia#1883]
Running latest `KopiaUI-0.10.6.AppImage` under arch linux. When I run the executable, I get a blank window and the following in the terminal:

```
$ ./KopiaUI-0.10.6.AppImage 
12:50:45.095 › failed to load
[312058:0405/125045.370188:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
12:50:45.599 › failed to load
12:50:46.101 › failed to load
12:50:46.602 › failed to load
12:50:47.103 › failed to load
12:50:47.606 › failed to load
12:50:48.108 › failed to load
12:50:48.609 › failed to load
12:50:49.111 › failed to load
...
```

the `failed to load` message repeats forever until I close the (blank) window.

**Comment by waldner** [comment]
This is still happening with 0.10.7.

**Comment by hockdudu** [comment]
I was having the same problem on Arch Linux.

In the logs in `~/.cache/kopia/cli-logs/` was the following line:
```
2022-06-07T10:00:48.908749Z ERROR kopia/cli listen error: listen tcp: lookup localhost on 127.0.0.1:53: no such host
```

I searched for this online, and the solution presented was to add `127.0.0.1 localhost` to `/etc/hosts` (https://github.com/inconshreveable/ngrok/issues/484#issuecomment-402050638). I did that and now it works.

**Comment by waldner** [comment]
Excellent! That solved it for me too. Thanks!
