### ISSUE TITLE
 [Feature] Compatibility with Oracle Cloud Buckets S3 interface

### ISSUE THREAD

**Issue by amunhoz** [kopia/kopia#1885]
It looks like the interface for S3 buckets does not work with oracle cloud S3 compatible api.

Connect Error: INTERNAL: internal server error: bucket "bucketname" does not exist
custom endpoint: xxxxxxxxxx.compat.objectstorage.sa-saopaulo-1.oraclecloud.com

It would be great if it works with this provider.

**Comment by adowair** [comment]
Hey @amunhoz, although OCI S3 hasn't been/isn't being tested, it should theoretically be supported. Do you have steps to reproduce this error. Did you already create the bucket? What command did you use to create or connect to the repo?

From a quick reading of [Oracle docs](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm) here's a couple of things to check in that connect command:
1. Specify `--endpoint=<oracle_endpoint>` when `create`ing or `connect`ing to the bucket. This defaults to `s3.amazonaws.com`, where the OC buckets won't be found =)
2. Same as above with `--region=<oracle_region>`

**Comment by adowair** [comment]
I highly doubt that. I gave this a go with my OCI bucket and I have been able to create and connect to a repo on the bucket successfully with the following arguments:

- S3 Bucket: name of an already existing bucket (found on the OCI dashboard):
- Server Endpoint: your bucket's namespace followed by the S3 region's endpoint (I think you've got that correct)
- Override S3 Region: **EMPTY**
- Access Key ID & Secret Access Key: I used customer secret key created following [these steps](https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/managingcredentials.htm#)

Will you give that a spin and let us know if you run into errors?

**Comment by dicksonleong** [comment]
I'm using OCI object storage through the S3 compatibility API and it is working fine with me so far. Below is the command I used:

```
kopia repository create s3 \
  --bucket=<bucket> \
  --region=<region> \
  --endpoint=<namespace>.compat.objectstorage.<region>.oraclecloud.com \
  --access-key=<ACCESS KEY> \
  --secret-access-key=<SECRET ACCESS KEY>
```

If you not using the root (administrator) user, you need to create a policy for a group that contains the user in the OCI console:
```
Allow group 'kopia-group' to read buckets in tenancy where target.bucket.name = '<bucket>'
Allow group 'kopia-group' to manage objects in tenancy where target.bucket.name = '<bucket>'
```

Hope that helps.

**Comment by amunhoz** [comment]
Ok, will try again.
Thanks.
