### ISSUE TITLE
on windows, maintenance will never run

### ISSUE THREAD

**Issue by mdsmdsmds** [kopia/kopia#1898]
it returns:
ERROR error running maintenance: error running maintenance: unable to determine if maintenance is required: error getting status: unable to decrypt schedule blob: cipher: message authentication failed

*******           list snapshot            ***************
"C:\Program Files\KopiaUI\resources\server\kopia.exe" --config-file=C:\Users\marco\AppData\Roaming\kopia\repository.config snapshot list
xxxxxx@quad:C:\aa
  2022-04-22 20:16:46 CEST k64bdd66d255d94573fbcaeda132ced79 59.2 MB drwxrwxrwx files:5 dirs:1 (latest-1..2,hourly-1,daily-1,weekly-1,monthly-1,annual-1)
  + 1 identical snapshots until 2022-04-22 20:17:06 CEST

*******           run all  snapshot            ***************
"C:\Program Files\KopiaUI\resources\server\kopia.exe" --config-file=C:\Users\marco\AppData\Roaming\kopia\repository.config snapshot create --all
Snapshotting xxxxxx@quad:C:\aa ...
 * 0 hashing, 0 hashed (0 B), 5 cached (59.2 MB), uploaded 0 B, estimating...
Created snapshot with root k64bdd66d255d94573fbcaeda132ced79 and ID 0c46773acbef62e5bc171b1739cad9ee in 0s

**ERROR error running maintenance: error running maintenance: unable to determine if maintenance is required: error getting status: unable to decrypt schedule blob: cipher: message authentication failed**

**Comment by jkowalski** [comment]
looks like your `kopia.maintenance` file is corrupted. Deleting it should resolve the issue.

**Comment by mdsmdsmds** [comment]
Thanks. Resolved!
