### ISSUE TITLE
31mERROR: unable to initialize repository

### ISSUE THREAD

**Issue by Snake883** [kopia/kopia#1905]
I was is in the middle of creating my first repository and snapshot. I think the repository was created successfully. I restarted the docker container, and get this error message:

`[31mERROR[0m unable to initialize repository: unable to initialize repository: error opening repository: unable to open repository: unable to read format blob: error getting kopia.repository blob: BLOB not found`

What do I do now?

**Comment by jkowalski** [comment]
Without details on how you configured docker container it's hard to speculate what happened. My suspicion is that your repository was not mounted properly in the container and when it restarted Docker wiped it and started clean.

If you can provide additional details, we might be able to help more.
