### ISSUE TITLE
Recover from a corruption

### ISSUE THREAD

**Issue by oderwat** [kopia/kopia#1906]
I recently wanted to restore a large snapshot but I got a checksum error while doing that. So I took some time to fix the problem with the original data not using the backup.

Then I thought I may be able to get rid of that content and take a new full hashed snapshot to not lose about 250 GB of data which seems to be fine besides that single file error. But I can't figure out how to remove this object (or file) and create a new snapshot that verifies the file correctly.

Snapshot verify gives me the follow error for one of the files:

> error reading object Ix1912b8720256c1cb950878a429e53ed5: unable to read data: unexpected content error: invalid checksum at p2eb2ff505b6fd69113eed6a3ad93107d-s44e8a6f26712de1b108 offset 6118325 length 8316482/8316482: decrypt: unable to decrypt content: cipher: message authentication failed

So I tried to clean the cache and "content delete x1912b8720256c1cb950878a429e53ed5" and then back up the directory where this file is in and then snapshot verify with sources using this directory. But it still does not verify.

What can I do to not lose all the blobs in the repository and still get a correct new snapshot of all the data? I do not even care about the old snapshots, I just don't want to create a new repository and copy everything over again.

**Comment by jkowalski** [comment]
If you still have the original file, deleting the content and re-uploading the snapshot with `--force-hash=100` should do the trick.

**Comment by jkowalski** [comment]
I'll try to make a small change which adds ability to fully drop (as opposed to delete) contents from the index.

**Comment by jkowalski** [comment]
@oderwat can you build  #1932 and then try:

```
$ kopia content delete --forget x1912b8720256c1cb950878a429e53ed5
$ kopia snapshot create ... --force-hash=100
```

Let me know if this fixes the issue.

**Comment by oderwat** [comment]
Sorry @jkowalski, but I had to recreate the repository because of its size and the need to be able to really be able to restore it. I also switched this repository from backing up images of VM drives to actually back up the content after mounting (which is much slower) but having one file of the split VM drive corrupted brings everything down.
