### ISSUE TITLE
No progress while restore. kopia-0.10.7-windows-x64

### ISSUE THREAD

**Issue by lysyy** [kopia/kopia#1907]
.\kopia snapshot restore --progress 
Restoring to local filesystem (d:\temp\configurator_disk_1.vhdx) with parallelism=8...
and no progress information

**Comment by mikkelfj** [comment]
Not sure if related, but 0.10.7, MacOS 11.6.5:
In UI: You can select a snapshot, and from there select and download a single file.
But if you Mount a folder, that backup becomes unresponsive and does not mount. A second backup will still be responsive, until you mount a folder. At that point the only option is to quit Kopia and restart.
This applies to both file system and BackBlaze backups.
