### ISSUE TITLE
[Feature Request] Allow customizing S3 PartSize

### ISSUE THREAD

**Issue by nazar554** [kopia/kopia#1909]
When uploading to Storj DCS I want to be able to specify a bigger part size, it seems that default one is 16 MiB

https://docs.storj.io/dcs/api-reference/s3-compatible-gateway/multipart-upload/multipart-part-size/

**Comment by jkowalski** [comment]
This is not currently supported, but should be quite easy. PRs welcome.

**Comment by julio-lopez** [comment]
@nazar554 #1941 disables multi-part uploads altogether. Can you see if that addresses the issue for you?

**Comment by nazar554** [comment]
@julio-lopez yes that will work too

**Comment by adowair** [comment]
@nazar554 thanks for bringing this up–community contributions keep making Kopia better!
