### ISSUE TITLE
UI Mount does not work on MacOS Big Sur

### ISSUE THREAD

**Issue by mikkelfj** [kopia/kopia#1933]
Mounting a folder from a specific snapshot in Kopia UI does not work on MacOS BigSur.
On Kopia 0.10.1 nothing happens when Mount is clicked - restoring a specific snapshot folder does work.
On Kopia 0.10.7 nothing happens when Mount is clicked, but then the UI for that repository becomes unresponsive when using the back button to the top level UI (ascending from from snapshot view). Restoring a specific folder not tested.

From memory, on earlier MacOS Catalina, Mount did not visually do anything, but a folder was mounted and accessible in the Finder App of MacOS. I do not recall Kopia version, but likely 0.10.1 or 0.10.3.
On Big Sur such a mount does not appear.

I tried to install fuse via homebrew on Big Sur, but it did not change anything for 0.10.1

**Comment by mikkelfj** [comment]
I have noticed the restic 0.13.1 mount from command line also fails with a failed Fuse kernel extension load, and a further search indicates that this is broad problem affecting many projects. One user reported giving up trying to fix it, but got Fuse working after a clean MacOS install - I think it was Big Sur, but could also be Monterey.

**Comment by alcroito** [comment]
I had KopiaUI mount hang on me as well. On macOS Monterey 12.4.
KopiaUI v0.12.1 from homebrew.

Same happened with restic mount 0.15.2 on the command line.

Didn't see any useful error message nor any output from verbose logging.

Looking through the docs of restic https://restic.readthedocs.io/en/latest/050_restore.html?highlight=mount#restore-using-mount , I found one needs to install macFUSE / osxfuse https://osxfuse.github.io/
After doing that and rebooting, mounting works fine.
It would be nice if the docs mentioned this, or even better, the UI / CLI showed an error when macfuse is not installed.

**Comment by mikkelfj** [comment]
Just note that in my case I had some version of fuse installed, and it did work earlier on.

**Comment by permezel** [comment]
Does not work for me.  I have fuse-t installed.  fllen and orbstack work with fuse-t (although filen claims it fails, it actually mounts).
Running most recent osx, kopia, and fuse-t.
