### ISSUE TITLE
[Feature Request] Compression ignore rules .kopiacompressignore or folder compression config rules 

### ISSUE THREAD

**Issue by doowrednu** [kopia/kopia#1936]
Would it be possible to add some functionality around compression handling exactly like Ignore files - but for compression setting?

I have some folders that contain files that are already highly compressed but in an object/blob format so impossible to be added to never compress via extension 

It would be great if I could place .kopiacompression - which lets you specify the compressor for that folder tree - In my opinion this would eliminate the issues around picking a one size fits all algorithm. You could choose on a per folder basis what to do - so pick your default in the policy - then in the folder have .kopiacompression which states which algorithm to use - or no-compression for that folder. 

I could see this being useful also for e.g. Movie / Photo libraries / Music libraries to set as no-compression vs. trying to maintain a list of possible extensions. 

This way you could choose to use an optimal compressor for lots of small files /  your SQL dumps / and maximum compression for e.g. your Documents whilst still being able to disable compression on a per folder basis.

Alternatively a .kopiacompressignore to have Kopia ignore that folder tree from all compression work using same file ignore logic.  This would be a straight copy of file ignore rules - and also use the same directory filters like ignore files but for ignore compression.

**Comment by julio-lopez** [comment]
Do (kopia-managed) compression policies solve the issue?

**Comment by doowrednu** [comment]
Thanks for pointing me in the right direction - 

kopia policy set --compression=none my/local/path/
kopia policy set --compression=none myuser@myhost:/my/local/path/
