### ISSUE TITLE
Maintenance refuses to run due to clock skew with rclone remote

### ISSUE THREAD

**Issue by flexiblestoic** [kopia/kopia#1938]
Hi, 

I have a curious issue and don't know where this originates from. 
I get the following error message during maintenance.

`ERROR error checking for clock skew: Clock skew detected: local clock is out of sync with repository timestamp by more than allowed 5m0s (local: 2022-05-09 11:35:46.9931265 +0200 CEST repository: 2022-05-09 11:35:46 +0000 GMT). Refusing to run maintenance.`
I am running KopiaUI on windows 10 to a rclone remote to a router ftp server (asus merlin). The router's clock is set correctly.

Anyone has an idea where this inadequate clock detection issue comes from? Is it rclone or kopia?
Thanks
Chris

**Comment by flexiblestoic** [comment]
So I found the problem. The ftp server vsftpd is broadcasting local time (without flagging it as local time I understand this is not a possibility in the ftp protocole). I changed the config of the ftp server to use utc time instead.
Now I don't have this issue but rclone/ftp is acting really really strange. The snapshots disappear and reappear... Very fishy.

**Comment by julio-lopez** [comment]
The detection is performed by kopia to ensure the required assumptions are met.
