### ISSUE TITLE
[Feature request] Repository name reminder on main window in KopiaUI

### ISSUE THREAD

**Issue by flexiblestoic** [kopia/kopia#1943]
Hi All,

I love this piece of software that works mostly beautifully. 

One thing that bothers me: I like to double click on the Kopia icon in the task tray to check that all my repositories are doing fine but unless I go into the repository tab, I don't know which repository I am looking at. Would it make sense to add a label visible from everywhere, either in the window title or in the menu bar?
![kopia](https://user-images.githubusercontent.com/47722729/167814700-c29f9d68-bb52-43e9-90ed-5ea39d2a2883.png)

Thanks,
Chris

**Comment by adowair** [comment]
Hey @flexiblestoic! That's not a bad idea. First thoughts:

- Could there be a security issue? Probably not–if you can click the task tray you can also open the app and go to the repository tab...
- Could the appearance get hairy? What if a repository name/description is really long? Would you truncate it?
- Could the implementation get hairy? What would you display if no repo is connected? I think we can only connect to one repo at a time, so the other end of this is a non-issue

With that in mind, this sounds like a straightforward addition to [App.js](https://github.com/kopia/htmlui/blob/main/src/App.js) from [RepoStatus.js](https://github.com/kopia/htmlui/blob/main/src/RepoStatus.js). If you can open an issue in the [UI repo](https://github.com/kopia/htmlui) that'd be great. PRs are most welcome 😄
