### ISSUE TITLE
Document the .kopiaignore format

### ISSUE THREAD

**Issue by PerMildner** [kopia/kopia#1945]
I see no documentation for the `.kopiaignore` format. A search in https://kopia.io/docs/ finds no matches (which looks like a bug in the docs search engine, since `.kopiaignore` is mentioned, but not described, in the documentation).

#773 suggests that `.kopiaignore` now behave similarly to `.gitignore`, but this is not mentioned in the documentation, and presumably there are some differences specific to the way kopia uses the file.

Disabling backup of some files by mistake is a potentially catastrophic error for a backup solution, so documenting the way ignoring files and directory works is really important.

**Comment by p0358** [comment]
Just to not leave this issue so empty, original gitignore format is described on git's page here: https://git-scm.com/docs/gitignore#_pattern_format

And looking at kopia's code, we can see that it appears to be using roughly similar rules: https://github.com/kopia/kopia/blob/51dcaa985ddf23fea07ff4a13fd7a62e38036803/internal/wcmatch/wcmatch.go#L72

Just putting it out there so it can serve as a starting point for someone looking to write/expand docs on this, or learn/confirm how this pattern matching works in kopia...

**Comment by lupusA** [comment]
I have a PR ready. I am just waiting for #2838 to be approved :-)
