### ISSUE TITLE
FR: Stream directory entries to uploader for a dynamic set of directory entries

### ISSUE THREAD

**Issue by ashmrtn** [kopia/kopia#1955]
I can spin up a PR for this, but thought it'd be helpful to get some feedback on the idea. I can have a draft PR out soon that has the skeleton of the idea but does not address the stuff in the "possible issues" section if that would help in thinking about things

#### Use case
an application is streaming data from an external source and would like to use kopia to create a backup of the data in a hierarchical manner. The application does not want to write the data to the local file system prior to adding it to kopia. In this instance, kopia would be used as a library instead of a CLI tool (i.e. application code would interface directly with kopia code)

The current directory implementation assumes that all directory entries are known when `Readdir` is called. This does not allow one discover/stream directory entries on the fly and send them to the uploader.

#### Proposal
Create a new abstraction `StreamedDirectory` in virtualfs that returns a `<- chan (fs.Entry, error)` and can be used to iterate over directory entries as they are discovered. Extend `uploader` implementation to iterate over entries from a `StreamedDirectory` using a range for-loop on the channel

`StreamedDirectory` interface
```go
// Caller provides/controls `incoming` channel and sends entries over it
func NewStreamedDirectory(name string, incoming <-chan (fs.Entry, error)) fs.StreamedDirectory
// Used by uploader
func (s *StreamedDirectory) Stream(ctx context.Context) <-chan (fs.Entry, error)
```

#### Affected components
* uploader
* ignorefs
* virtualfs

#### Possible Issues
**Ignoring selected files**
`StreamedDirectories` don't fit with the ignorefs interface as they cannot return a specific file in the directory. A simple solution would be to have ignorefs use the parent directory's ignorefs context to filter out ignored files

**Resource cleanup on cancellation**
In the API sketch above, `StreamedDirectory` has no way to notify the owner of the `incoming` channel that an upload has been canceled so that it can close the channel. This may fall outside the scope of kopia because presumably whatever controls the channel would know the kopia uploader returned an error, but is worth bringing up for discussion

**Playing nice with the uploader worker pool**
`StreamedDirectories` may block uploader worker pool goroutines while waiting for new entries. This could reduce the effective parallelism of the system.

A solution for this would be to hand all the `StreamDirectory` channels off to a single goroutine (a "watcher"), have it monitor them, and pass the work back to the worker pool when new entries come in. This would require a minimal amount of context for each channel the watcher has.

Two possibilities exist for the watcher: 1. using a "fan-in" pattern with channels or 2. using reflection to make a dynamic select statement. The “fan-in” requires making a goroutine for each `StreamedDirectory` that is in use. This could cause many goroutines per `StreamedDirectory` if other things like error wrapping or ignorefs checks need to occur. Another solution is to use golang’s reflection package to dynamically create a `select` statement that can watch a dynamic set of channels. The first channel could be one that is used to pass the watcher new items to watch. The subsequent channels would be `StreamedDirectory` channels. Items from all but the first channel would be passed back to the worker pool as work items. Performance comparisons and considerations about data buffering for the two approaches can be found in [this StackOverflow](https://stackoverflow.com/questions/19992334/how-to-listen-to-n-channels-dynamic-select-statement). Although they show a difference of two orders of magnitude, I think the fact that the work done for each item will likely be non-trivial (i.e. file upload) and the fact that the channels may block for indeterminate amounts of time makes the performance difference less of a topline issue. Therefore, a solution that balances being idiomatic and goroutine usage seems preferable.

One catch with the reflection-based approach would be deadlock. If the watcher wanted to send a work item and the worker pool’s workers all wanted to send an item to the watcher, then everything would lock up (thinking this through with a worker pool of size 1 and a separate, non-worker pool goroutine for the watcher helps). Having the incoming channel for the watcher buffer a single data item would fix this as the worker pool would always have one worker that could send to the watcher and then go idle. That would allow the watcher to eventually send its data to the worker pool.

**Comment by jkowalski** [comment]
Looking at processChildren() there may not be big reasons why that can't fundamentally be streamed. 

So we should be able to replace Readdir() with a callback based iteration for fs.Directory and all its implementations. 

I wouldn't do channels since they are hard to abort, pass errors, etc. We use callback based iteration in a bunch of places. 

This will have lots of other benefits like handling much bigger directories. 

It's a bigger change but we should be able to stagger it across several PRs. 

Can you see if this could possibly work for you?

**Comment by jkowalski** [comment]
This will definitely also reduce memory consumption for large directory reads since only active items would need fs.Entry

**Comment by ashmrtn** [comment]
first, thanks for taking the time to read all of this and leave feedback, especially since it's on the long side

Callback based iteration should work fine as I have some flexibility on my end. Thanks for pointing out that design pattern as I'm still learning the which patterns are the best for situations in golang. If you have a pointer to a specific place in this repo of that it would be helpful as then I can see how this repo structures it and follow a similar pattern

Some questions re: replacing `Readdir()` calls with a streaming equivalent:
1. how would ignore dot files be found and loaded? Would this be done using `Child()` to get a specific file name?
1. would returned entries still need to be sorted? If so, does that reduce the benefits of streaming for localfs and other implementations? I see that the localfs implementation of `Readdir()` sorts entries, though I've run a static directory with unsorted entries and the resulting snapshotted directory had sorted entries
2. would the iterator callbacks need to be thread safe and/or would the directory be iterated through multiple times? It seems like the uploader may run estimates and actual uploads in parallel. The virtualfs stream directory may not be able to materialize entries multiple times be default so requiring the ability to materialize content multiple times could complicate things

Also, what order for PRs would work well? The folks I'm working with and I are most interested in the virtualfs streamed directory that we could use with this change. While I am happy to help out with changes surrounding this request, I do need to make sure balance how I spend my time

**Comment by jkowalski** [comment]
1. Great question. I did not consider the ignorefs wrapper. Child() would work here and i think it's fine to always return "not found" for the streaming cas

2. No, sorting is not required. The resulting directory manifest is sorted for other reasons, namely that `fs.Entries` expects results to be sorted for lookup, getting rid of this whole concept would be even more beneficial.

3. My first intuition is that iterator callbacks should be single-threaded and each fs.Entry would be delivered once. The way uploader works it would quickly dispatch them to worker threads where possible.

I'm thinking we can try the following sequence of PRs.

PR1:

* add `func IterateEntries(ctx context.Context, callback func (ctx context.Context, e fs.Entry) error)` to `fs.Directory` interface. Make a trivial helper function that calls `Readdir()` and invokes callback for each item. We can use this helper as a naive implementation for all current `fs.Directory` types, so this should be mostly mechanical.

PR2:

* change `Uploader` and `ignorefs` to not rely on `Readdir()`

PR3..N:

* slowly remove all remaining dependencies on `fs.Entry.Readdir()`. It probably still makes sense to be able to read all entries into a slice, but that could be a static helper not an interface method.

**Comment by jkowalski** [comment]
Here's the quick search for `Readdir()` in the codebase and my analysis on how difficult it would be to get rid of those. Excluding tests (which I'm expecting to be easy to remove).

## Easy cases:

```
cli/command_ls.go
  57,19: 	entries, err := d.Readdir(ctx)
fs/entry.go
  84,20: 	children, err := d.Readdir(ctx)
fs/loggingfs/loggingfs.go
  38,30: 	entries, err := ld.Directory.Readdir(ctx)
internal/diff/diff.go
  52,23: 		entries1, err = dir1.Readdir(ctx)
  59,23: 		entries2, err = dir2.Readdir(ctx)
internal/fusemount/fusefs.go
  117,33: 	entries, err := dir.directory().Readdir(ctx)
  150,33: 	entries, err := dir.directory().Readdir(ctx)
internal/fshasher/fshasher.go
  113,19: 	entries, err := d.Readdir(ctx)
internal/webdavmount/webdavmount.go
  113,25: 	entries, err := d.entry.Readdir(d.ctx)
  216,20: 		entries, err := d.Readdir(ctx)
snapshot/restore/restore.go
  260,19: 	entries, err := d.Readdir(ctx)
snapshot/snapshotfs/estimate.go
  124,25: 		children, err := entry.Readdir(ctx)
snapshot/snapshotfs/repofs.go
  248,24: 		if _, err := dirEntry.Readdir(ctx); err == nil {
snapshot/snapshotfs/objref.go
  48,22: 		entries, err := dir.Readdir(ctx)
snapshot/snapshotfs/snapshot_tree_walker.go
  109,21: 	entries, err := dir.Readdir(ctx)
fs/cachefs/cache.go
  96,10: 	return d.Readdir(ctx)
```

## Medium difficulty:

```
snapshot/snapshotfs/upload.go
  922,17: 	ent, err := dir.Readdir(ctx)
  1026,30: 	entries, direrr := directory.Readdir(ctx)
fs/cachefs/cachefs.go
  35,30: 	entries, err := d.ctx.cacher.Readdir(ctx, d.Directory, func(e fs.Entry) fs.Entry {
```

## Difficult:

```
fs/ignorefs/ignorefs.go
  145,29: 	entries, err := d.Directory.Readdir(ctx)
```

**Comment by ashmrtn** [comment]
I can work on getting a PR out with the interface. For now though, I think it would be a good idea to have it as a separate interface type because I think there's still a few things that need hashed out re point 3. I think the sticking part there is that, from my understanding, the estimator [runs in parallel](https://github.com/kopia/kopia/blob/5d87d817335f6d547e094ab80062113dc3a1fdf4/snapshot/snapshotfs/upload.go#L1321) with the uploader actually doing work. Part of the estimation process is to [call](https://github.com/kopia/kopia/blob/5d87d817335f6d547e094ab80062113dc3a1fdf4/snapshot/snapshotfs/estimate.go#L124) `Readdir` to see how many files/directories need to be uploaded. To make it work, non-virtualfs implementations would either need to be able to handle multiple iteration calls (possibly concurrently) or the estimator code needs to be modified. If we allow multiple calls of iterate, that's fine, we just may need an escape hatch on that for the virtualfs implementation as it may not be possible to materialize the stream of entries more than once (i.e. the entries are actually being streamed from some other source and it is expensive to access that source multiple times)

**Comment by ashmrtn** [comment]
as an aside, are there any plans to change how cancellation works in kopia? Right now the uploader has its own way to check if stuff is canceled and nothing seems to cancel the context that is passed around. This makes it a bit harder for application code that would be dynamically generating directory entries in a virtualfs streamed directory to determine if it should stop. Under the callback model proposed, it could look for cancellation errors from the callback, but that would also require having an entry on-hand to give to the callback

**Comment by jkowalski** [comment]
Thanks for the first PR, I took a deeper look into the uploader and ignorefs changes and it's a bit harder than I anticipated, so we need to do a larger refactoring -  I'll send a PR for that and it will switch Uploader to using IterateEntries(). Once this is merged  I'd really appreciate your help with getting rid of remaining Readdir() from the codebase.

**Comment by ashmrtn** [comment]
thanks for doing the changes for the uploader, ignorefs, and local file system. I'll read up on the other uses of `Readdir()` and also, at some point, spin up a PR for the virtualfs `StreamedDirectory` that was the basis for this series of changes

**Comment by ashmrtn** [comment]
I have a branch in a fork that will remove the remaining `Readdir()` calls you mentioned earlier in this issue. It relies on ignorefs changes from #1963 (to pass tests) and the `IterateEntriesToReaddir` helper function in #1967. I believe it will pass tests, but I would need to check again after dependencies are merged and/or we figure out a merging strategy
