### ISSUE TITLE
kopia: error: time: unknown unit "d" in duration for retention period

### ISSUE THREAD

**Issue by cirrusflyer** [kopia/kopia#1972]
Atempting to set a retention period using days.  A CLI command like this:  `--retention-period=<number_of_days>d`

I've tried `--retention-period=7d`, and get this error: kopia: error: time: unknown unit "d" in duration "7d"

Setting hours does work, so like `168h`.

Is this a Kopia issue of what unit is accepted or a Wasabi issue?

**Comment by julio-lopez** [comment]
From https://github.com/kopia/kopia/issues/1067#issuecomment-1133428242

**Comment by julio-lopez** [comment]
Likely a Kopia issue, @Shrekster is taking a look.

**Comment by Shrekster** [comment]
I'll put up a PR switching to the proposed time string parser above.

**Comment by adowair** [comment]
Attempting to fix this upstream here: https://github.com/alecthomas/kingpin/pull/329
