### ISSUE TITLE
Lack of retention tag in json output

### ISSUE THREAD

**Issue by snack32** [kopia/kopia#1987]
First of all, I like to express my gratitude for your work on kopia, great piece of code!

I would like to take advantage of this message to ask you if the following is a bug or intended design:

kopia version: 0.10.7

kopia command: `kopia snapshot list --incomplete --show-identical --retention`

Output (truncated for brevety)

```
2022-05-22 06:08:12 CEST k49485a96e3a2a88940d8821c126dbeca 806.6 MB drwxr-xr-x files:11676 dirs:1000 (daily-7)
2022-05-23 05:28:53 CEST kbaf2ee2d824af8547f31c6c8e8df1566 804.4 MB drwxr-xr-x files:11703 dirs:1001 (daily-6)
(...)
```

However, the same command with --json flag added, does not show the retention tag (i.e., daily-x)

kopia command: `kopia snapshot list --incomplete --show-identical --retention --json`

Output (truncated for brevety)

```
[
  {
    "id": "d1876aac51503cad8076163c2d9627b9",
    "source": {
      "host": "nas",
      "userName": "root",
      "path": "/root"
    },
    "description": "",
    "startTime": "2022-05-22T06:08:12.756383737+02:00",
    "endTime": "2022-05-22T06:08:14.104913436+02:00",
    "rootEntry": {
      "name": "root",
      "type": "d",
      "mode": "0755",
      "mtime": "2022-05-22T06:08:10.784062142+02:00",
      "obj": "k49485a96e3a2a88940d8821c126dbeca",
      "summ": {
        "size": 806572104,
        "files": 11676,
        "symlinks": 0,
        "dirs": 1000,
        "maxTime": "2022-05-22T06:08:12.380056999+02:00",
        "numFailed": 0
      }
    }
  },

(...)
```

Thus, the lack of retention tag in json output is intentional?

In any case, thank you very much for your work in kopia.

**Comment by julio-lopez** [comment]
Not intended design, but more of a side effect of the internal representation where the retention is NOT stored on purpose, since it needs to be dynamically computed.

Now, there is no reason why it could not be included in the JSON output, we should fix it.
