### ISSUE TITLE
CLI: how to use multiple repositories

### ISSUE THREAD

**Issue by cirrusflyer** [kopia/kopia#1991]
When using the CLI version, is there a way to create repositories to two different S3 providers and then back up to them separately?  I don't see a way to do this by giving them each a separate name.

**Comment by xxxliqu1dxxx** [comment]
Yes you can. You need to use multiple config files. If you use kopia repo connect —help you will see how to use —config-file to allow you to specify which repo to connect to. 
therefore your CLI running snapshot commands with the —config-file parameter will perform actions on the specified repo.

**Comment by cirrusflyer** [comment]
Thanks!   I see that now.  Do you know if you can change the repository.config file name, or just the path? For example, could I change the config file name for one to wasabi.config and another to b2.config?  And if I changed just the name, do I need to specify full path or could I use "--config-file=b2.config" and it'll use the same Linux path as default of "$HOME/.config/kopia/"?

**Comment by cirrusflyer** [comment]
Still having some issues.  I'm trying to connect to the repo with this command:

kopia repository connect from-config --config-file=storage1.config -p --file=storage1.config.kopia-password

Getting this error:  kopia: error: can't connect to storage: unable to open config: error decoding config json: invalid character 'U' looking for beginning of value, try --help

Should I be using something else?

**Comment by adowair** [comment]
Glad you found that out @cirrusflyer. Unless the argument to `--config-file` is a compound path, it'll be appended to the default config path:

```go
func (c *App) repositoryConfigFileName() string {
	if filepath.Base(c.configPath) != c.configPath {
		return c.configPath
	}

	// bare filename specified without any directory (absolute or relative)
	// resolve against OS-specific directory.
	return filepath.Join(ospath.ConfigDir(), c.configPath)
}
```
```go
package filepath
// Base returns the last element of path.
// Trailing path separators are removed before extracting the last element.
// If the path is empty, Base returns ".".
// If the path consists entirely of separators, Base returns a single separator.
func Base(path string) string { ... }
```

I got confused by this at first too. It'd be good to update the [docs](https://kopia.io/docs/reference/command-line/#configuration-file) and [CLI prompt](https://github.com/kopia/kopia/blob/9167c081830e47cc0591236dafd57423e50747e2/cli/app.go#L228) with this information. PRs are welcome @cirrusflyer 😄

**Comment by cirrusflyer** [comment]
Thanks, but not sure I follow.  Can you elaborate a bit on this?

**Comment by adowair** [comment]
Of course, a couple of examples:
```shell
kopia repository connect --config-file=home_ssd.config ...
```
The above command will create or use a config file by the name of `home_ssd.config` in the same path that the default repo config file (`"repository.config") would be. In other words, the provided argument is appended to some predetermined default path. On linux the actual path of the config file will be `$HOME/.config/kopia/home_ssd.config` as you correctly found out.

If however, you specify a full path
```shell
kopia repository connect --config-file=~/documents/home_ssd.config
kopia repository connect --config-file=/tmp/var/home_ssd.config
```
The actual path of the config file will be exactly that, it won't be appended to the default path. This means that you can override where such configs are stored by providing a full path to `--config-file`.

I hope that made sense?

**Comment by adowair** [comment]
> Still having some issues. I'm trying to connect to the repo with this command:
> 
> kopia repository connect from-config --config-file=storage1.config -p --file=storage1.config.kopia-password
> 
> Getting this error:
> 
> "kopia: error: can't connect to storage: unable to open config: error decoding config json: invalid character 'U' looking for beginning of value, try --help"
> 
> Should I be using something else?

A shot in the dark here: have already created the config using `kopia repository <connect/create> --config-file=...`?

**Comment by cirrusflyer** [comment]
Thanks.  And yes, I did specify the --config-file during repo creation, and I can see all three files there with the custom name. 
 But when I run what you specify above, 

kopia repository connect --config-file=storage1.config

I get this:

"kopia: error: must select a subcommand of 'repository connect', try --help"

**Comment by adowair** [comment]
Ah I see. When connecting you must specify what the repo type/params are. This comes from either:
1. Specify them explicitly, for example (`kopia repository connect filesystem path=...`)
2. Use an already saved config (`kopia repository connect from-config ...`)

I think `--config-file` is used to specify _where Kopia will go on to save the resulting connection information._, rather than what connection information it'll use to connect now.

Could you take a look and see if its contents look well-formed? Would you be willing to post them (secrets-redacted) here?

**Comment by cirrusflyer** [comment]
So if I run just:

kopia repository connect from-config --config-file=storage1.config

I get this:

"kopia: error: can't connect to storage: either --file or --token must be provided, try --help"

If I run this:

kopia repository connect from-config --config-file=storage1.config -p, --file=storage1.config.kopia-password

I get this:

"kopia: error: can't connect to storage: unable to open config: error loading config file: open storage1.config.kopia-password: no such file or directory, try --help"

**Comment by cirrusflyer** [comment]
The config file looks fine except for the cache path looks odd (I've redacted some info):

{
  "storage": {
    "type": "s3",
    "config": {
      "bucket": "fileshares",
      "endpoint": "endpoint.com",
      "accessKeyID": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
      "secretAccessKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "sessionToken": ""
    }
  },
  "caching": {
    "cacheDirectory": "../../../../../../volume1/kopia/cache/config1",
    "maxCacheSize": 5242880000,
    "maxMetadataCacheSize": 5242880000,
    "maxListCacheDuration": 30
  },
  "hostname": "server1",
  "username": "kopia",
  "description": "config1",
  "enableActions": false,
  "formatBlobCacheDuration": 900000000000

**Comment by cirrusflyer** [comment]
Maybe I should go the token route for each repo?  kopia repository status -t -s

**Comment by cirrusflyer** [comment]
The token way works, but still would like to understand why the other method didn't work.  Thanks

**Comment by adowair** [comment]
I've played with this a bit and will attempt an answer. First, from the [docs](https://kopia.io/docs/reference/command-line/#configuration-file):

> For each repository connection, Kopia maintains a configuration file and local cache:

All a "connection" is is some saved state about where the repository is and what it contains. You can think about it like a context. It is not necessary for a connection to exist for every repository on your system. Likewise, multiple connection configs can exist on your system at once. At any one time, only one of these connections is "active"–commands are executed against that connection by default.

When creating or connecting to a repository, the repo's information is stored in config. By default, this config lives in `$HOME/.config/kopia/repository.config`.

The `--config-file` allows you to use a connection other than the active one._ When we execute `kopia repository create` or `connect`, we are _creating a new connection_. Passing `--config-file` to either of these specifies the path at which we'd create the connection's config.

For all other operations, the argument to `--config-file` just specifies which connection (or context) we execute the command against. If this flag is not specified, Kopia will use the most recently used connection.

Then, the role of `kopia repository connect from-config --file` is to __switch contexts__ from one existing connection to another. This avoids you having to specify `--from-config` every time.

I've been able to run these commands successfully:
```shell
> kopia repository create filesystem --path ~/storage1 --config-file=storage1.config
  # active connection switches to storage1.config
> kopia repository connect s3 <s3_params> --config-file=storage2.config
  # active connection switches to storage2.config
> ls $HOME/.config/kopia/
  storage1.config    storage2.config
> kopia repository connect from-config --file $HOME/.config/kopia/storage1.config
  # active connection switches to storage1.config
```

Please let me know if that makes sense. It's good to iron out these small details, and we should have documentation for them, so thanks for bringing this up!

**Comment by ww7** [comment]
I have similar problem with automated workflow with sync to multiple repositories.

`kopia repository connect` and `kopia repository sync-to` does not create config file for remote repositories.

Only `kopia repository create` creating it, but also initialize it as different repository, and requires the additional steps like deleting repository folder on remotes, what looks wrong.

As a temporary solution, I don't use a config files and specifying the login credentials every time.

**Comment by adowair** [comment]
@cirrusflyer have you been able to make it work? Feel free to close the issue if so

**Comment by cirrusflyer** [comment]
I never tested the file method, and just used the token method for now.
