### ISSUE TITLE
CLI: create remote storage config without new repository initialization

### ISSUE THREAD

**Issue by ww7** [kopia/kopia#2007]
My Kopia workflow assumes additional remote storage's creation for repository sync/replication. 

I found there's no simple way to create config file for remote storage without initialization as new repository, what cause conflict when `sync` of existed repo to it.

`kopia repository sync-to` does not create config file for remote repositories.

Only `kopia repository create` creating it, but also initialize it as new repository, and requires the additional steps like deleting repository folder on remotes, what looks wrong.

As a temporary solution, I don't use a config files and specifying the login credentials every time.

Maybe I missed something? Thanks.

**Comment by adowair** [comment]
Hi @ww7, `kopia repository connect` should create configs for remote repos. I have been able to run the following commands:
```shell
> kopia repository connect s3 kopia repository connect s3 --endpoint="xxx.oraclecloud.com" --bucket="bucket_bucket" --region="region_region" --access-key=000 --secret-access-key="xxx" --config-file=test.2
Connected to repository.
> ls ls $HOME/Library/Application\ Support/kopia/
repository.config   test.2
```

Perhaps try passing `--config-file=...` to specify a different path for a config file? Perhaps what you are seeing is `kopia repository connect` is overwriting the default config file `repository.config`, which is not immediately visible. COuld you confirm that?

**Comment by ww7** [comment]
I use SFTP `kopia repository connect sftp` and `kopia repository sync-to sftp`, maybe creation config file not implemented for it?

**Comment by ww7** [comment]
Sorry, I'm wrong, `kopia repository connect sftp` able to create config.
I'm asking for sub-command for config creation for additional storage's for `kopia repository sync-to sftp`

**Comment by ww7** [comment]
@adowair yes, I understand, thanks.
But `sync-to` not works if used different repositories uniqueID
First run of `sync-to` require empty folder or same repository

**Comment by ww7** [comment]
I assume `sync-to` should be able to generate config too.

**Comment by adowair** [comment]
@ww7 will you please list out the exact commands you are using (without PII)?

**Comment by ww7** [comment]
1. Generate new repository and config file
```sh
kopia repository create sftp \
  --config-file "$script_dir/repositories/repo-$username@$host.config" \
  --cache-directory	"$script_dir/cache/" \
  --username $username \
  --host $host \
  --port $port \
  --keyfile $keyfile \
  --known-hosts $knownhosts \
  --path $repository_folder
```
2. Connect to repo
```sh
kopia repository connect sftp \
  --config-file "$script_dir/repositories/repo-$username@$host.config" \
  --cache-directory	"$script_dir/cache/" \
  --username $username \
  --host $host \
  --port $port \
  --keyfile $keyfile \
  --known-hosts $knownhosts \
  --path $repository_folder
```
3. For first `sync` we can't use `kopia repository connect sftp` because throw error
> kopia: error: error connecting to repository: repository not initialized in the provided storage
And after `kopia repository create sftp` we can't sync to it, because error
> kopia: error: destination repository contains incompatible data

To add storage for `sync` we need empty folder. And only way to generate config file is only create repository and then empty it.

Please extend `sync-to` to be able to create config file, or some new subcommand like `sync-create`

**Comment by gc-ss** [comment]
@adowair Is the issue that:

1. When the `kopia repository create sftp` is run, and if `$repository_folder` already has some data in it, then `create` will throw:

`kopia: error: destination repository contains incompatible data`?

2. Ergo, when `kopia repository create sftp` is run, `$repository_folder` should either point to a completely empty directory (or not an actual directory and `kopia repository create` will create `$repository_folder` after it notices the directory doesn't exist?

3. `kopia repository create` will also create the config file (in addition to `$repository_folder`)?

4. Only when a `kopia repository create sftp` has been run first, should we then run `sync-to` or `connect` etc?

**Comment by gc-ss** [comment]
To provide clarity:

The remote repository is a SFTP box that's a ZFS store and exposes some "hidden" directories like `.snapshots` etc. It's possible these existing directories are confusing kopia?

We can work/fix that - just trying to understand the potential problems/things to look out for.

Please don't assume I understand kopia at all and the above comment is likely riddled with misunderstanding. Don't hesitate to correct me. @ww7 and I are learning together, with him leading the learning initiative although all confusion/misunderstanding is mine.

I thank you both for your time and effort.

**Comment by adowair** [comment]
Thank you both for all the information. I'm learning about this part as well =) so no worries at all. Going through this info now...
