### ISSUE TITLE
[Feature Request] Keep restore tasks in KopiaUI

### ISSUE THREAD

**Issue by basldfalksjdf** [kopia/kopia#2012]
I think KopiaUI removes tasks from Tasks after a certain amount of time. Is it possible to sticky certain types of tasks so that they are never removed? I am particularly taking about restore tasks. I left a restore to run overnight, and the restore seems to have finished, but I can no longer see it under Tasks so I do not know if the restore had any errors or not.

**Comment by basldfalksjdf** [comment]
Following up on this, I did another test restore with KopiaUI. Came back overnight to this error, not sure what it means:

![Capture 404](https://user-images.githubusercontent.com/106879934/175094347-306656ee-28f6-4bd7-b886-be1dacb752ae.PNG)

I can no longer see the restore task under `Tasks`, so cannot look at the details of what happened. Until we get better logging for KopiaUI (see https://github.com/kopia/kopia/issues/2073 and https://github.com/kopia/kopia/issues/2072), I would strongly recommend anyone doing restores do so via Kopia CLI rather than KopiaUI.

**Comment by phidevz** [comment]
@basldfalksjdf At least to me, this does not seem to be implemented anywhere in the UI. This would also explain the "404" message you posted: If the client still knows this ID, and refreshes the page every few seconds (did find this in the code), then the server (kopia CLI) deletes them after some time, it will respond 404 (not found).

**Comment by basldfalksjdf** [comment]
@phidevz So I think the issue is related to https://github.com/kopia/kopia/issues/2073 in that KopiaUI is keeping the `Tasks` in memory rather than on disk, so whenever memory is cleaned up, the everything under `Tasks` disappears. This behavior is controlled by the underlying `Go` code rather than the `HTML` UI.

I propose two changes:

(1) Make KopiaUI save all `Tasks` on disk rather than in memory, so that the record of `Tasks` is persistent and does not get lost.
(2) Make KopiaUI regularly cleanup `Tasks` so that it does not get too much. Maybe delete a task 30 days after it has completed? If we are brave, this option could also be exposed to the end user -- they can decide whether to cleanup tasks after 30 days or 7 days or whatever.

I don't think these changes should be too difficult, as `Tasks` for Kopia CLI are already persistent, but it does require someone to know `Go`.
