### ISSUE TITLE
[Feature Request] Not create and upload files to repo when snapshot has no changed files in source

### ISSUE THREAD

**Issue by basldfalksjdf** [kopia/kopia#2016]
It looks like Kopia creates and uploads an index and a blob file every single time when a snapshot is run, even if there were no changes to the files in the source. This behavior can result in many small and unnecessary index/blob files junking up the repo. Is it possible that, instead of uploading the index/blob files to the repo regardless of whether files in the source have changed, can Kopia keep track of "empty" snapshots a different way? Maybe a single file in the repo that keeps track of these snapshots for retention purposes? This would help keep the repos clean.

**Comment by adowair** [comment]
From my understanding this is by design. Kopia does writes only (rather than rewrites) to allow for concurrency without locking the repository. If we had a single file to track empty snapshots, what happens if two kopia clients/users create snapshots at the same time? Create one and delete another?

Periodically, kopia maintenance and garbage collection will run to collate these small files, and get rid of any duplicated information. @julio-lopez correct me if I am wrong here. 😄

**Comment by basldfalksjdf** [comment]
I am not a programmer, so please excuse my ignorance. However, I do not see why Kopia needs to create what are essentially junk files for every snapshot. Your argument about concurrency is valid. Yet, the way to solve this concurrency problem would be to have a separate file to track empty snapshots for each client connecting to the same repo. After all, Kopia already has to track blob usage by each client when there are multiple clients connecting to the same repo (so that it knows what data needs to be restored). I do not see why a similar methodology cannot be applied to tracking empty snapshots.

To me, it just does not seem like a wise choice to create two junk files every time a snapshot is run. Let's say I run a snapshot every 15 mins. That is 8 junk files every hour or 192 every day, if nothing in the source changes. If you have multiple clients connected to the same repo, this number increases further. At some point, a repo is going to have more junk files associated with empty snapshots than files associated with backed up data. There also is the (relatively minor) issue of unnecessarily driving up cloud storage costs, as some providers charge for minimum file sizes and API calls.

I do not know if `maintenance` is intended to garbage collect these junk files, but as of right now it most definitely is not doing so for my setup. I see junk files for empty snapshots going back days, even though every day full `maintenance` is being run by KopiaUI.

**Comment by julio-lopez** [comment]
Yes, kopia is creating small blobs to track the metadata about empty snapshots. This is using the same mechanism used for tracking other snapshots from multiple clients.

Maintenance compacts these blobs in the background. However, for the index blobs in particular, the superseded blobs are not immediately deleted.

A tunable parameter could be exposed to delete those more aggressively if desired, but the default behaviour would likely remain as is.

**Comment by basldfalksjdf** [comment]
The ability to more aggressively delete the files with maintenance is a fair compromise. Thank you.

**Comment by basldfalksjdf** [comment]
Featured has now been added into Kopia to ignore snapshots where no files have changed. We should see it in the next release.
