### ISSUE TITLE
[Feature request] Repository name reminder on main window in KopiaUI

### ISSUE THREAD

**Issue by flexiblestoic** [kopia/kopia#2051]
Hi All,

I love this piece of software that works mostly beautifully.

One thing that bothers me: I like to double click on the Kopia icon in the task tray to check that all my repositories are doing fine but unless I go into the repository tab, I don't know which repository I am looking at. Would it make sense to add a label visible from everywhere, either in the window title or in the menu bar?

![167814700-c29f9d68-bb52-43e9-90ed-5ea39d2a2883](https://user-images.githubusercontent.com/47722729/167860431-a769b6d3-7f64-49a9-8c7d-c860f6f04b72.png)

Best,
Chris

**Comment by gitname** [comment]
I'm implementing this now.
