### ISSUE TITLE
Kopia UI: Use larger time units when representing longer durations

### ISSUE THREAD

**Issue by gitname** [kopia/kopia#2055]
In Kopia UI v0.10.7, all durations in the "Tasks" table are shown in units of **seconds**, even when they are longer than 60 seconds.

![image](https://user-images.githubusercontent.com/7143133/173907797-78d284ca-367c-432f-b0de-f3ba1915f8fa.png)

I think I would find the durations longer than 60 seconds easier to comprehend if they were represented in terms of **minutes** and **seconds**. Similarly, I think I would find durations longer than 60 minutes easier to comprehend if they were represented in terms of **hours** and **minutes** (and, optionally, seconds).

For example, instead of `4472.5s`, it could say `1h 14m` or `01:14:32`.

---

On a side note, given that this is an HTML-based UI, you may be able to store an alternate representation of the value within a tooltip that becomes visible when the user hovers over the on-page value. For example (this is a screenshot of a CodePen): 

![image](https://user-images.githubusercontent.com/7143133/173909941-57bb6786-4ce9-4799-b621-206c08067976.png)

**Comment by gitname** [comment]
I'll take a crack at implementing this.

I see the `htmlui` project already depends upon `moment.js` NPM package (per the project's [`package.json`](https://github.com/kopia/htmlui/blob/main/package.json#L10) file), so I plan to use that.

**Comment by gitname** [comment]
Since the project depends upon `moment.js` already, I opted to use `moment.js` to "humanize" the duration shown on the web page. Hovering over the "humanized" duration causes the original "in seconds" duration to appear in a tooltip. Both things are shown here.

![image](https://user-images.githubusercontent.com/7143133/174226501-37acc495-3cb0-4812-9da0-e1f189cfac03.png)

I plan to open a PR containing these changes tomorrow.

**Comment by talios** [comment]
Awesome! One thing that's bugged me is the task processing time - on LARGE jobs that reads like 300123s - that could use some form of humanising - altho, probably with the "ago" portion as its in-process.
