### ISSUE TITLE
[feature request] Connect to multiple repositories at the same time

### ISSUE THREAD

**Issue by pescuma** [kopia/kopia#2066]
I have a use case similar to #502. Because of that I'd like to request the option to be connected to multiple repositories at the same time so that when a command like `snap create` is executed, the data is sent to multiple repositories (with different policies for each one).  

I know it's possible to do that using config files, but I think this approach has advantages:
 - I can be faster, because the files on disk have to be scanned just one
 - It's easier to configure and use, because you would not have to worry about multiple config files 
 - You could use the KopiaUI scheduler

Thanks a lot.

**Comment by pescuma** [comment]
My use case is: I do backups to 2 locations: one on local disk and one on b2, with different retention policies, and I do that from multiple computers. The last part makes `sync-to` not work for my use case. Using config files work, but makes using KopiaUI more complicated. Using multiple instances of KopiaUI is something I had not thought about, and seems a better approach than the other, but I still feel that it won't be the best in terms of usability. Anyway, I understand that this can make the software a lot more complex and may not be worth to implement. Thanks anyway, and thanks also for kopia, it is a very good piece of software.

**Comment by xxxliqu1dxxx** [comment]
> (1) Run multiple instances of Kopia or KopiaUI. Each one can connect to a different repo.

This is how I use it on Windows. Works like a charm:
![image](https://user-images.githubusercontent.com/83290244/174665657-9978210d-ebe5-433b-aabf-ddef1ee7948d.png)

It copies to various destinations, from a single pc, to multiple repos, each with their own policies, retentions, exclusions, compressions, and what not...

**Comment by pescuma** [comment]
@xxxliqu1dxxx Thanks a lot. Because of your screenshot I found out this is already possible through KopiaUI.

**Comment by talios** [comment]
> (1) Run multiple instances of Kopia or KopiaUI. Each one can connect to a different repo.

This is the approach I'm thinking of going for a local backup from my NAS.  Since I'm running Kopia via docker, this'll just be a different config file/dir and instance.

I wonder if I could share cache directories - tho maybe not wise.

**Comment by BrenBarn** [comment]
>So, right now, one instance of Kopia can connect to only one repository. This is by design, and I am not sure if we will ever see that change. Frankly, I am not sure we should -- that would add another layer of complexity, and it is not entirely clear the use case for such a feature is that important.

This seems a strange statement.  It is actually quite common to want to connect to multiple backup locations from the same computer.  For instance, I might want to back up my files to a local external drive, and also back them up to the cloud.  That's all part of one backup plan.  I'd like to be able to do that all from a unified interface, where I can map backup schedules and policies to repositories at will.  Is it not Kopia's intent to provide that kind of backup ability?  That seems rather limited.

**Comment by Powerbless** [comment]
Yes, or a Bookmark Feature. So WE can choose to what repository we want to Connect.

**Comment by OrbitingOcelot** [comment]
kopia seems like such a nice and well designed backup-solution, but this limitation is quite unexpected. It is suprising that this use case has not been thought about (or excluded intentionally).

**Comment by QazCetelic** [comment]
> > (1) Run multiple instances of Kopia or KopiaUI. Each one can connect to a different repo.
> 
> This is how I use it on Windows. Works like a charm: ![image](https://user-images.githubusercontent.com/83290244/174665657-9978210d-ebe5-433b-aabf-ddef1ee7948d.png)
> 
> It copies to various destinations, from a single pc, to multiple repos, each with their own policies, retentions, exclusions, compressions, and what not...

I can't find this option.

# Snapshot page
![image](https://github.com/kopia/kopia/assets/51381523/511fb65b-d6c0-45a6-8260-f68c0ea3317a)

# Policies page
![image](https://github.com/kopia/kopia/assets/51381523/bcb52d93-5522-4661-9d80-dea9cc6cb3a4)

# Tasks page
![image](https://github.com/kopia/kopia/assets/51381523/f7ecbfba-1d33-441a-a050-613f37a65b20)

# Repository page
![image](https://github.com/kopia/kopia/assets/51381523/7cf41b17-12f7-4be3-b7a9-56b4bd22051a)

# Preferences page
![image](https://github.com/kopia/kopia/assets/51381523/534b3126-573e-4fdb-9aa6-b83b21a497ac)

**Comment by ados8** [comment]
I'm just discovering this limitation as I began implementing Kopia.
I understand this is free open source software and the team has done an amazing job.
Imagine a product like Veeam and they said you want multiple destinations, install another instance of the product.
This limitation is a real bummer.

**Comment by jkowalski** [comment]
Using Kopia UI you can `Connect To Another Repository`. Kopia (the server behind the UI) manages one repository each and KopiaUI simply launches multiple servers.

**Comment by QazCetelic** [comment]
> Using Kopia UI you can `Connect To Another Repository`. Kopia (the server behind the UI) manages one repository each and KopiaUI simply launches multiple servers.

Do you mean [this](https://github.com/kopia/kopia/blob/06ff37fa635ed658e14e5ea126d89a8af2ccbb66/app/public/electron.js#L534)? It seems this feature is only available when using the desktop application. Should I spin up another docker container for each repository?

**Comment by wake0up0ne0** [comment]
This is still not resolved. I have to run 15 containers if i want 15 folders to be backed up in different destinations. Rudiculous setup.

**Comment by Dark-Schneider-666** [comment]
This would be really useful for enqueueing tasks, specially from the same source of data. I mean, if you want to backup to multiple destinations, having all unified in a single Kopia server would allow to set all of them at the same hour, but setting only one snapshot at the same time they are enqueued, instead multiple accesses at the same time if the previous task didn't finished before the next starts. That could make your storage (specially for HDDs very used on NAS wanting capacity instead speed) to be overwhelmed and maybe some network issues too.

So having multiple repositories but under the same single server would be a nice feature.

**Comment by electrofloat** [comment]
So this issue after being closed gets a lot of new comments.

Shouldn't it be reopened then and/or a new issue describing the new situation be created?

**Comment by pepa65** [comment]
> Using Kopia UI you can `Connect To Another Repository`. Kopia (the server behind the UI) manages one repository each and KopiaUI simply launches multiple servers.

Using a UI is not feasible in many instances. People will need a way to do this from the CLI. I guess the answer is: with multiple config files. What I find surprising is that on each `kopia connect` the default config file gets overwritten. So I am not confident in using a config file as a base, as it seems to get overwritten by commands.

**Comment by tiptoptom** [comment]
Here is how you `Connect To Another Repository`. This option is hidden in the taskbar (at least on windows).

<img width="672" height="600" alt="Image" src="https://github.com/user-attachments/assets/63c4e7a9-bd74-488b-a564-2db17c657217" />

**Comment by QazCetelic** [comment]
> Here is how you `Connect To Another Repository`. This option is hidden in the taskbar (at least on windows).

That is only possible with the desktop application, not with the Docker container
