### ISSUE TITLE
[Feature Request] Make logs in KopiaUI persistent (save to disk rather than store in memory)

### ISSUE THREAD

**Issue by basldfalksjdf** [kopia/kopia#2073]
(1) Currently the logs for each task when using KopiaUI are not persistent -- they are stored in memory only and not on disk. This means it is impossible to read the log for each task, since the `Logs` screen in KopiaUI truncates the logs and there is no underlying file we can look at. This is particularly troublesome if there is any error, such as when doing a restore, because one cannot read the log to identify the error. I talked with @jkowalski and he mentions it would be great to make the logs persistent so that they are saved to disk instead of just stored in memory. This would allow users to easily identify errors for any task. Note that logs when using Kopia CLI are already persistent; just not for KopiaUI.

(2) I think it would also be great if a link can be added in KopiaUI for each task that links to the log file for each task, a link that one can click to open the full log file in a text editor for easier viewing. The link can be added at the bottom of where the logs are already displayed in KopiaUI under `Tasks`. Note that some tasks will have multiple log files, since Kopia splits really large logs into multiple files. In such a situation, KopiaUI should link to all the log files for the particular task.

Thank you!

**Comment by oliver-la** [comment]
I've just had a task disappear from the list, probably because the server process restarted itself at some point and now I'm unable to verify if that task ever completed. (whether successfully or not)
So this feature would really help!

**Comment by DoTheEvo** [comment]
+1 for at least some brief info on task
its so strange that I cant compare how long the backup took compared to previous because its all lost with kopia closing

**Comment by tiredofit** [comment]
When they are stored in the repo one tries to execute `kopia logs` and they don't know if using a repository server. That makes it difficult for monitoring systems/analyzers to tell if an individual server is failing.

````
[tiredofit/kopia 18:57:57 /logs/cli-logs] $ kopia log list
ERROR operation supported only on direct repository
````

It's quite baffling why logs don't reside on the filesystem, more so akin to driving with a blindfold on.

**Comment by LakeishaKowalczyk** [comment]
+1

**Comment by superbarney** [comment]
Please make log persistence an option.

**Comment by kryptot7** [comment]
I second this feature; it's important for making sure your files are saved properly. It's also important to have a simple way to view all the errors for a particular task.

**Comment by AnshulJ999** [comment]
I just came across this while searching and would love this too. +1 for persistent logs in Kopia UI; its much-needed. Ideally I'd like to backup the logs of all initial backups permanently since that initial backup contains the most info.

**Comment by schaarda** [comment]
@jkowalski Please re-open this request. Having logs is crucial for production use. If something goes wrong  (or maybe just a user doing stupid things) and is noticed a day later, it's necessary to be able to reconstruct what has happend. 

Otherwise there won't be much confidence in the backup process. I built a backup tool for production use with many clients and persisted logs save my ass more than once.

**Comment by DoTheEvo** [comment]
There are logs, even too detailed one might say...  you can set their location on every run, see every command executed,...
its just that theres no comfy GUI to have a quick look at some history.. last ~10 runs where one would see how long it took, how much data was backed up and how much it takes and that sort...

**Comment by superbarney** [comment]
Currently KopiaUI reports shows a truncated list of files which has errors, but there's no way to view the full list without persistent logs.
