### ISSUE TITLE
snapshot fix does not always fully repair a repository

### ISSUE THREAD

**Issue by chaitalisg** [kopia/kopia#2074]
Hello,

I keep getting "BLOB not found" error even after using `snapshot fix` command. Here are the steps I followed:
1. Create a source directory in filesystem with this structure:
/repo
|-- dir1
|----f1
|----f2
...

2. Create a kopia repo in filesystem
3. Create a snapshot of the above source directory.  
4. Add files to the source directory (just copied the files under dir1 one level above)
/repo
|--dir1
|----f1
|----f2
|--f3
|--f4

4. Create another snapshot of the above source directory.  
5. List the blobs in the repo. (There is only one pack blob)
6. Delete the pack blob (Did this to simulate blob corruption)
7. Try to restore one of the snapshots. Will get the "blob not found" error.
8. Use the object id in the error to run `kopia snapshot fix remove-files --object-id=<id from error>--commit`
9. List snapshots, try to restore one of the snapshots. This results in "blob not found" error.
10. Add a new file to the source dir, create a snapshot
11. List the snapshots, restore the latest snapshot. This results in "blob not found" error.

Can the `snapshot fix` command be enhanced to get rid of all the potentially corrupted blobs in one go?

**Comment by jkowalski** [comment]
I don't understand how at step 6 you only have 1 pack blob.

@chaitalisg Can you make a PR with a failing Golang test?

**Comment by chaitalisg** [comment]
yes, here it is: https://github.com/kopia/kopia/pull/2071

I ran the test `recovery_test` locally by pointing the `repo-path-prefix` to a local directory in file system. Let me know if you need   more information.

**Comment by basldfalksjdf** [comment]
> Can the `snapshot fix` command be enhanced to get rid of all the potentially corrupted blobs in one go?

Have you tried using `kopia snapshot fix invalid-files --verify-files-percent=100 --commit`? Shouldn't that do what you are asking?

**Comment by bbccdd** [comment]
hi @basldfalksjdf can you please comment and/or close the ticket please?

**Comment by basldfalksjdf** [comment]
@bbccdd ? This isn't my ticket.

**Comment by bbccdd** [comment]
@chaitalisg can you please comment and/or close the ticket please?

And, @basldfalksjdf sorry!
