### ISSUE TITLE
Kopia UI treated as a Trojan

### ISSUE THREAD

**Issue by klisza1993** [kopia/kopia#2091]
during testing Kopia UI just downloaded a PS1 script where Defender shown an alert!

C:\Users\[UserName]\Downloads\aa37182b358c917a9c7cc7799cd7f53b-61d4537d37390d9d5bb25e751b358207e56c090c\gistfile1.ps1

Note from Defender:

Trojan:PowerShell/Bondupdater.A

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aPowerShell%2fBondupdater.A&threatid=2147725860

**Comment by jkowalski** [comment]
Can you describe how you're testing it and what exactly happened? Are you using official signed builds of KopiaUI or something else?

**Comment by klisza1993** [comment]
Sorry. This was false positive. Once i have downloaded some ps1 script which was a test malware. I was supprised that malware appeard during testing a snapshot to local path etc :) It was a coincidence of time. So there isnt any issue ;)
