### ISSUE TITLE
Timeout when adding remote repo

### ISSUE THREAD

**Issue by fuzunspm** [kopia/kopia#2099]
I'm trying to setup the server and connect clients remotely via a subdomain. I created repo, users and SSL on the server. I can login via web ui but desktop apps can't connect to the repo with an error message of: 

`Error: error opening repository: error connecting to API server: unable to establish session for purpose=: error establishing session: Session(): rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp SERVER_IP_ADDRESS:0: i/o timeout".`

There is no error message in nginx

**Nginx Config**

```
server {
  server_name sub.domain.com;
  client_max_body_size 0; 
  location / {
     grpc_pass grpcs://localhost:51515;
  }
  listen 443 ssl http2; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/sub.domain.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/sub.domain.com/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
  if ($host = sub.domain.com) {
      return 301 https://$host$request_uri;
  }
  listen 80;
  server_name sub.domain.com;
  return 404;
}
```

**Kopia Server Run Command**

`kopia server start --server-control-username USERNAME --server-control-password PASSWORD --tls-cert-file /etc/letsencrypt/live/sub.domain.com/fullchain.pem --tls-key-file /etc/letsencrypt/live/sub.domain.com/privkey.pem`

**Comment by CtheCondor** [comment]
I also have this same circumstance; Have you found a work around?

**Comment by fuzunspm** [comment]
Unfortunately no I couldn't

**Comment by mytlogos** [comment]
I encountered this "bug" when i tried to connect to a remote kopia repository server from my workstation.
Did you enter a port number in your url? e.g. `https://kopia.com/` did  not work for me and showed the same error message, but with `https://kopia.com:443/`, this error did not occur.

**Comment by CtheCondor** [comment]
I tried it with both 443 and with default port 51515 explicitly listed and the same "bug" occured
Error: error opening repository: error connecting to API server: unable to establish session for purpose=: error establishing session: Session(): rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp SERVER_ADDRESS:51515: i/o timeout".

**Comment by lupusA** [comment]
Hi, 

has the port been opened in the firewall settings? I am also running a repository server with ssl and can connect just fine. Can you post some more details on it?

Cheers,
