### ISSUE TITLE
[Regression] v11.0 and .1 - Button to browse folder in policies and snapshot is gone

### ISSUE THREAD

**Issue by xxxliqu1dxxx** [kopia/kopia#2145]
[Regression] v11.0 and .1 - Button to browse folder in policies and snapshot is gone

10.7
![image](https://user-images.githubusercontent.com/83290244/177383344-c6245d35-e6a7-4a9c-b72e-f20687334dce.png)

11.0 and .1
![image](https://user-images.githubusercontent.com/83290244/177383398-10640853-b4b2-446c-94d0-ad42956d4b91.png)

**Comment by mitohund** [comment]
I understand this is (was) related to the desktop UI. However, I'm experiencing the same issue with the web UI (v0.12.1 in docker). Is this the right place for it or shall I open a new issue?
