### ISSUE TITLE
[kopia cli] Support for ```kopia snapshot verify``` using in-memory storage only

### ISSUE THREAD

**Issue by davidandreoletti** [kopia/kopia#2149]
Hi, 

I have several terabytes of backup stored with kopia and run kopia's snapshot restoration procedures at least monthly. This is starting to wear out SSDs. The hardware has plenty RAM (32Gb) / decent CPU and some backups have files as large as 1Tb.

Do you think ```kopia snapshot verify``` could run in memory only ? It would help further SSD lifetime, and perhaps speed the process.

Note: 
- I originally considered `ramfs` or equivalent but it is unsuited for files near as large as total RAM.
- ```--verify-files-percent``` could help with SSD wear but it is important for compliance/reliability to restore all the archive's file.

PS: kopia is fantastic!

**Comment by CompuRoot** [comment]
I believe your post isn't qualified to be counted as an issue, but as general use case question that should belong to [forum discussion](https://kopia.discourse.group/).  

If I get your question right, then it basically might be:  "Is `kopia snapshot verify` is enough  to be sure repository isn't broken or one have to do real restoration to be make sure?"

If you would re-post your question on the forum, could you clarify there, which SSD drive's you worry about, - source drive that is subject for backup or a drive that you doing monthly restoration?



-- 
regards,

kopia's long standing user

**Comment by davidandreoletti** [comment]
> Is kopia snapshot verify is enough to be sure repository isn't broken or one have to do real restoration to be make sure?

@CompuRoot  Yes, I would like to know what properties of the backup are being verified and guaranteed upon successfully verification with ```kopia snapshot verify```.

---
> In defense of OP, this could be considered a feature request. Regardless of whether this is the right place to post this, I am confused about what the OP is concerned about and what he would like to see.

@basldfalksjdf Upon reading the answers above, I believe there is now 2 topics.

**Topic 1: Confused about what this command does exactly**

I believe kopia is maturing and becomes more reliable. That being said, the only reliable backup one ever has is the last one they fully successfully restored.

The documentation of ```kopia snapshot verify``` is ```Verify the contents of stored snapshot```. It is unclear (as a kopia user) what properties of the backup are being verified (all blobs on the manifest present on the remote storage?, blob checksum match?, ..., restored file checksum match?, etc  ... ). 

Without this clarification, my current kopia backups are always restored in full (ie no cached data locally,  download remote data in full, decompress/decrypt data, write data to files, verify files integrity) using ```kopia snapshot restore``` to do this. With the current setup, this implies writting restored files to SSD drive (ie SSD wear).

When I created this Github issue, I was under the impression that ```kopia snapshot verify``` was a shorthand for ```kopia snapshot restore``` whose goal is to make _full/partial backup verification_ easier for admins/users. 

As per my understanding this implied files were restored on disk somewhere (decided by kopia). Hence my request for in-memory restore operation.

However, reading the answer above, I am less confident about what this command does; this is a documentation issue. 

Notably, as per you last comment: Adding / removing ```--verify-files-percent``` changes not only the scope of files being operated on but also what operation what being carried on it/with it (downloaded / no downloaded, unpacking / no unpacking).

**Topic 2:** If this command does indeed restore file, then could an option be added to restore them in memory only ?**

I believe my original post covers this aspect.


---
1. About topic 1, could you clarifying what properties of the backup ```kopia snapshot verify``` check/guarantee ?
2. (Upon clarification ), I will either close this issue or rephrase the feature request.
---

>  I thought the forum would be more productive place to figure out first

Apologies for not using the proper channel May I suggest having [new Github issue following some template ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)with a one line reminder pointing users to the relevant channel depending on what's being asked ?

**Comment by davidandreoletti** [comment]
@CompuRoot / @basldfalksjdf  I have my answer now from https://github.com/kopia/kopia/pull/2272 and now available on the main site: https://kopia.io/docs/advanced/consistency/

Thank you.
