### ISSUE TITLE
[Feature Request] Make `--verify-files-percent` keep track of verified files

### ISSUE THREAD

**Issue by basldfalksjdf** [kopia/kopia#2152]
Right now, using `--verify-files-percent` with `snapshot verify` or `snapshot fix-invalid files` randomly grabs files. Randomization is great, but the problem is that it never guarantees that eventually all the blobs are tested. For example, running `--verify-files-percent=1` each day for a 100 days means that there is a 1/3 chance that all of your data will **not** be tested by the end of the 100 days (cause, statistics). The only current way to guarantee that 100% of files are tested is by doing `--verify-files-percent=100`, but this is impractical for many people, giving limited hardware and excessive costs related to egress from many cloud storages.

I propose adding an option to `snapshot verify` and `snapshot fix-invalid files` that allows keeping track of verified files. So, sticking with the same example, running `--verify-files-percent=1` each day with this new feature for a 100 days would mean that there is a 100% chance that all of your data will be tested by the end of the 100 days.

I am not a coder, but I imagine this feature could go something like this:

1) Have a manifest that has a list of all the files in a repo that would need to be checked when running `--verify-files-percent`. Each file in this manifest has a timestamp for the last time it was verified.

2) Whenever `--verify-files-percent` is run, it draws from the top of the files list (sorted by earliest timestamp) rather than randomly.

This is just a rough outline. If we want to still retain some randomness component, we could reset the timestamps for all the files after each round of 100% files being verified and do a random draw when drawing from the list of not-yet-verified files (which would dwindle between resets, of course, so randomness would get lower as the 100% threshold is approached).

One question, if we were to do this, would be where to keep the manifest that tracks the verified files -- locally or in the repo? There are pros/cons of both. 

If kept locally, that would avoid any concurrency issues in situations when a repo is used by more than one Kopia instance and all of them are trying to write to the manifest. Plus, there really isn't a major need for keeping such a manifest at the repo, it is not critical. However, keeping the file locally would lead to inefficiencies if multiple Kopia instance share the same repo and they all do `--verify-files-percent`.

If kept in the repo, we would avoid the inefficiencies when multiple Kopia instances share the same repo (e.g., `--verify-files-percent=1` run each day by 5 instances of Kopia is now equal to 5% of the data being checked daily). However, this may lead to concurrency and file locking issues, and also we would need to be careful with how many times we write the manifest. We wouldn't want to write the manifest after every file is checked, as many cloud storages charge per write.

**Comment by julio-lopez** [comment]
What is or are the desired behavior(s)?

1. Ensuring that after X number of runs, the repository has been 100% verified;
2. Aiming to maintain a level of verification (say greater than 99%) over time, perhaps with some parameters about the target maximum age of a content / file / snapshot / blob not being verified?

In an approach like the one proposed above (or similar), at the end on the Nth run (say N=100) all files have been verified. To simplify the reasoning, let's assume no new files have been added during that time. After the last verification run completes, the _oldest verification age_ is N (days or runs).

Wondering whether there is a need to keep track of the verification age, and use that as an input for choosing the item to verify. Something (e.g., a file) that has a verification age above a threshold would have say a weight of 1, whereas something that has been more recently verified would have a weight of `age/threshold`. The verification age of something that has not  not been ever verified could be a function of its creation time. It seems that this would increase the verification coverage over a time period. Just a random idea. Thoughts?

**Comment by basldfalksjdf** [comment]
In my mind, the critical feature is the original proposed feature that allows us to achieve the (1) of what you propose. If we add the feature, that automatically allows a user to achieve (2) on their own without the need to code another parameter into Kopia for it. 

Let's assume Kopia adds verification timestamp tracking as proposed in the OP and such that (1) is achieved. Now let's say you want to ensure none of your files' verification age is more than 40 days. Well, then just run `--verify-file-percent=2.5` every day and none of your files' verification ages will be more than 40 days (assuming the command takes decimals; does it?), because the proposed changed ensures that 100% of the files are verified every 40 days. Without the proposed change, `--verify-file-percent=2.5` every day would not guarantee that 100% of the files are verified every 40 days.

To be clear, even right now you could ensure your files' verification age is no more than 40 days by running `--verify-file-percent=100` once every 40 days. The difference, though, between the current behavior and the proposed change is that the proposed change allows verification of 100% of the files to be spread out over 40 days rather than on one day every 40 days.

To your suggestion about using verification age as an input to determine which files to verify, we could have a new option, instead of `--verify-file-percent` Kopia could have `--verify-old-files` or something to that effect. However, to be useful in a world of limited bandwidth and egress costs, I think such an option would need another option that limits the total GB of files pulled down in one command. Otherwise, there is no need for a `--verify-old-files` because one can already achieve the same behavior right now with Kopia: just run `--verify-file-percent=100` every X amount of days, where X is the --verify-old-files threshold that you desire.

Does that make sense? I rambled a bit. To me, the goal is not to increase verification coverage. One can already do that with the current Kopia features by picking how often to run  `--verify-file-percent=100`. To me, the goal is to allow guaranteed 100% verification of files spread over X time period.

**Comment by julio-lopez** [comment]
Understood.

Re: increasing verification coverage, to be clearer, the goal would be to increase _"continuous"_ verification coverage with cost smoothly spread over time.

It seems the cost would be the same either way, 100% of the content needs to be downloaded every X number of days, the difference seems to be whether is gradual / smooth, or bursty.

**Comment by basldfalksjdf** [comment]
I think both of us are advocating the same thing, perhaps in different ways.

> It seems the cost would be the same either way, 100% of the content needs to be downloaded every X number of days, the difference seems to be whether is gradual / smooth, or bursty.

It depends. 

The big cost for more cloud storage is egress, and many providers have some sort of fixed amount of free egress a month. For example, AWS and Azure allow 100GB/m. 

Let's say I have a 500GB repo that I want to 100% verify every 6m. If I do one 100% verify in one go, that will cost me something like $36 in egress alone for just one verification. But if I do smaller verifies across the six months (and eventually still verify all 100% of my data), I can stay within the 100GB/m limit and pay $0 egress.

Maybe most users of Kopia have so much data backed up in TBs that free egress limits are meaningless for them and thus it doesn't really matter. Or maybe egress costs arent an issue for most Kopia users. But surely some will benefit from gradual verifies rather than bursts.

Beyond cost, one also has to consider that some people have limited bandwidth with limited data, so gradual usage is often better than a burst.

Finally, the logistics of gradual verifies are much easier than a burst when Kopia is run on a machine that is actively used for other things.

**Comment by julio-lopez** [comment]
Thanks for the explanation
