### ISSUE TITLE
cpu usage is too high causing the system to run stutter

### ISSUE THREAD

**Issue by jak01201** [kopia/kopia#2172]
First of all, thank you very much to the developers for providing such good software, kopia is really great and cool,
The problem I'm having now is，When snapshotting large files, cpu usage is too high, causing the system to run stutter。
Can you help me solve this problem。

**Comment by jkowalski** [comment]
What kind of CPU do you have? You may be able to reduce CPU usage by lowering `Maximum Parallel File Reads` policy value either in the UI or using CLI `kopia policy set`:

For example if you have a 4-core CPU, try setting this to 2 or 3:

```
$ kopia policy set --global --max-parallel-file-reads=2
```

**Comment by jak01201** [comment]
Thank you very much for providing a way of thinking, I will try it out, but the problem I encountered seems to be snapshotting very large single file more than 50GB, at this time the system slowness occurs, my CPU is i7-8700, RAM32G, snapshot small files no such problem.

**Comment by jkowalski** [comment]
Let me know, but I think that should actually help. Large files as of recently are internally read in parallel to speed up the upload.

**Comment by jak01201** [comment]
I followed ‘kopia policy set --global --max-parallel-file-reads=2’，Then run, now everything is fine, no more stuttering, thank you again for your help, hope kopia can be better.
