### ISSUE TITLE
Kopia-UI: ERROR: No matching issuer found

### ISSUE THREAD

**Issue by alexandrestein** [kopia/kopia#2183]
It seems like nothing is working for me.
Starting Kopia-UI and start it again and it won't start.

When I start from the console I got quite lot of error for a fresh install:
```
❯ kopia-ui
09:39:05.329 › failed to load
09:39:05.338 › APPIMAGE env is not defined, current application is not an AppImage
[21226:0712/093905.547055:ERROR:nss_util.cc(335)] After loading Root Certs, loaded==false: NSS error code: -8018
09:39:05.837 › failed to load
09:39:06.339 › failed to load
09:39:06.840 › failed to load
09:39:07.343 › failed to load
09:39:07.845 › failed to load
09:39:08.347 › failed to load
09:39:08.848 › failed to load
09:39:09.350 › failed to load
09:39:09.852 › failed to load
09:39:10.355 › failed to load
[21226:0712/093910.912034:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for 127.0.0.1 failed:
----- Certificate i=0 (O=Kopia) -----
ERROR: No matching issuer found
```

The app never close when I click the exit button.

Because the app does not stop properly if I start a new instance I got that:
```
❯ kopia-ui
10:05:30.763 › failed to load
10:05:30.770 › APPIMAGE env is not defined, current application is not an AppImage
```

But killing the app with `<CTRL>+C` make it possible to restart the app.
Otherwise I have to empty the directories in `~/.config/kopia-ui`.

Here is a screenshot to help illustrate this:
![Screenshot from 2022-07-12 10-06-53](https://user-images.githubusercontent.com/5431025/178442171-6883fc02-679a-498c-b9a3-ca1ec02e23a8.png)

I'm running the latest version from the repository on Debian 11 up to date.

I'm evaluation to switch from Borg to Kopia. But the startup is quite difficult. 

Please let me know all the info you need.
Best regards

**Comment by cdoggyd** [comment]
I'm experiencing the same issue on a CentOS 7 server. Once the GUI is closed, it won't reopen. The main.log shows the same AppImage error that @alexandrestein posted.
