### ISSUE TITLE
Feature request: make the downloading of a new version visible to the user

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kopia/kopia#2189]
As things stand (v0.11.3), the user can think that her clicking of the 'update now' notification does nothing. Cf. #2185.

**Comment by LinuxOnTheDesktop** [comment]
In the latest version - 0.12.0 - there is a do-you-want-to-upgrade dialog box (which wasn't there before?), but there is still a delay of some five seconds (on my reasonably powerful PC) between clicking 'yes' and anything seeming to happen. Thus, the user can still wonder, when trying to upgrade, whether anything is happening.

**Comment by xxxliqu1dxxx** [comment]
> but there is still a delay of some five seconds (on my reasonably powerful PC) between clicking 'yes' and anything seeming to happen.

The "delay" has always been there, same behavior for all versions. It's the time for it to download the setup file. So you click Yes to upgrade, it downloads the file, exits the UI, then executing the setup file.

**Comment by LinuxOnTheDesktop** [comment]
Right. But the problem is as follows. One is unsure whether one really has initiated the upgrade, especially since clicking the notification, once it has been relegated to the Windows 'action centre', seemingly does_not_ do anything (even if one waits).
