### ISSUE TITLE
kopia v0.11.3: invalid input duration string when specifying checkpoint-interval

### ISSUE THREAD

**Issue by budachst** [kopia/kopia#2193]
When specifying --checkpoint-interval=360m, I am getting this warning when running kopia snapshot:

kopia: error: invalid input duration string, try --help

Could it be the same issue as #2173 ?

**Comment by jkowalski** [comment]
The error is a weird side effect of switching the parsing library, where it seems you can't specify minutes >60 anymore.

Having said that, you should NOT increase the checkpoint interval beyond 45 minutes, as this risks losing your data if there was a concurrent maintenance operation going on.
