### ISSUE TITLE
How to specify a custom blob size?

### ISSUE THREAD

**Issue by AlphaJack** [kopia/kopia#2202]
Is it possible to specify a custom blob size?    

For instance, borg can create ~500MB files which means the repo is made of fewer files (useful for providers like Google Team Drive that limit the number of files, but not the total space)

```
-rw------- 1 root root 501M 16 lug 04.00 1219
-rw------- 1 root root 507M 16 lug 04.00 1220
-rw------- 1 root root 502M 16 lug 04.00 1221
-rw------- 1 root root 501M 16 lug 04.00 1222
-rw------- 1 root root 283M 16 lug 04.01 1223
```

Kopia instead for the same repo creates ~20MB files (with default options):

```
rclone ncdu v1.59.0 - use the arrow keys to navigate, press ? for help                                                                       
-- REMOTE:/HOST/kopia/REPO/p22 ------------------------------------------------------------------------------------------
   20.287Mi [##########] /c4e
```

I don't know if tweaking sharding is the way to go because if I got it right, changing the sharding parameter still maintain the same number of ~20MB shards, it just changes the amount of shards per folder (getting more folders and shorter blob file names)

**Comment by basldfalksjdf** [comment]
AFAIK, changing the blob size is not currently possible with Kopia. Someone can correct me if I am wrong.

Consider submitting a FR or a PR for this feature.

**Comment by xxxliqu1dxxx** [comment]
You can change the max size of the files: 
--max-pack-size-mb=MB   Set max pack file size

It may not be what you are looking for, but this does reduce the number of files in the repo. I believe the default is 20MB but you can change to 128MB (I believe)

You can do kopia repo set-parameters --help to see more information

**Comment by jkowalski** [comment]
Note to future readers:

It's one of those flags that should be used with extreme care as the consequences of using it are not well understood or tested. 40-50MB might be safe if you have decent internet connection, but I would not recommend going higher than that.

Since Kopia relies on passage of time for safety, increasing blob size has the potential to significantly skew upload times and exceed safety buffers we have during maintenance.

**Comment by skygunner** [comment]
> # Note to Future Readers
> It's one of those flags that should be used with extreme care as the consequences of using it are not well understood or tested. 40-50MB might be safe if you have decent internet connection, but I would not recommend going higher than that.
> 
> Since Kopia relies on passage of time for safety, increasing blob size has the potential to significantly skew upload times and exceed safety buffers we have during maintenance.

I guess this applys to doing maintenance directly with online remote repos like s3 storage, for local filesystem maintenance with larger pack size should be ok?

**Comment by gdtv** [comment]
It's been more than 2 years since this topic was posted. I would like to know if the new version of the program now allows setting a larger blob size? This is crucial for me.
