### ISSUE TITLE
`BLOB not found` after OOM

### ISSUE THREAD

**Issue by nh2** [kopia/kopia#2216]
I ran kopia to back up a Ceph file system containing tens of millions of files, and it got OOM-killed; last output in the shell:

```
594 hashing, 543 hashed (10 GB), 0 cached (0 B), uploaded 5.5 GB, estimating...

[1]    1522591 killed
kopia --config-file /run/kopia-config-corpfs-rclone-dropbox/repository.config
357.66s user 1228.26s system 42% cpu 1:02:26.33 total
```

After this, I ran `kopia policy set` with `--compression none` (to see if that reduces memory usage) and restarted `kopia snapshot create`, and it brought up `BLOB not found` errors:

```
2022-07-21T23:56:28.027081Z  Snapshotting root@corpfs-2:/cephfsmount ...
 / 476 hashing, 956 hashed (10.5 GB), 0 cached (0 B), uploaded 8.5 GB, estimating...2022-07-21T23:56:56.377543Z ERROR async write error: unable to write content chunk 1 of FILE:myfile0: unable to write pack: error writing pack: can't save pack data blob p0de5121426260a9a10342e8ccb4196ad-s90bff38f927d8f01112: error writing pack file: error writing blob using WebDAV: unable to complete WriteTemporaryFileAndCreateParentDirs despite 10 retries: BLOB not found: unable to write pack: error writing pack: can't save pack data blob p0de5121426260a9a10342e8ccb4196ad-s90bff38f927d8f01112: error writing pack file: error writing blob using WebDAV: unable to complete WriteTemporaryFileAndCreateParentDirs despite 10 retries: BLOB not found
 / 477 hashing, 1812 hashed (11.6 GB), 0 cached (0 B), uploaded 8.5 GB, estimating...
 ! Error when processing "myfile1": BLOB not found
 | 476 hashing, 1814 hashed (12.1 GB), 0 cached (0 B), uploaded 8.5 GB (1 fatal errors), estimating...
 ! Error when processing "myfile2": BLOB not found
```

Just wanted to report that here.

Backend is `rclone`. Config:

```json
{
  "storage": {
    "type": "rclone",
    "config": {
      "remotePath": "my-dropbox:/backup/corpfs-kopia-rclone/kopia-repo/",
      "rcloneArgs": [
        "--transfers=50",
        "--multi-thread-streams=40"
      ],
      "atomicWrites": true,
      "dirShards": null
    }
  },
  "caching": {
    "cacheDirectory": "../kopia-cache-corpfs-rclone",
    "maxCacheSize": 5242880000,
    "maxMetadataCacheSize": 5242880000,
    "maxListCacheDuration": 30
  },
  "hostname": "corpfs-2",
  "username": "root",
  "description": "Repository in RClone my-dropbox:/backup/corpfs-kopia-rclone/kopia-repo/",
  "enableActions": false,
  "formatBlobCacheDuration": 900000000000
```

Policy:

```sh
kopia --config-file /run/kopia-config-corpfs-rclone-dropbox/repository.config \
  policy set \    
  --global \
  --compression none \
  --ignore-cache-dirs false \
  --one-file-system true \
  --add-ignore /cache/ \
  --max-parallel-file-reads 600
```

Repo:

```sh
kopia --config-file /run/kopia-config-corpfs-rclone/repository.config \  
  repository connect rclone \
  --cache-directory /run/kopia-cache-corpfs-rclone \
  --rclone-args='--transfers=50' --rclone-args='--multi-thread-streams=40' \
  --remote-path=my-dropbox:/backup/corpfs-kopia-rclone/kopia-repo/
```

Note `--cache-directory` is in `/run` which is in RAM (`tmpfs` of size 32 GB), I don't know if the cache directory did/would exhaust that.

**Comment by jkowalski** [comment]
First thing `--max-parallel-file-reads` is effectively the number of threads to use, 600 is way too high, should be on the order of 10-20 max, that's the cause for OOM.

Second, `rclone` is likely the culprit of missing writes, I think I found a solution to that which is to disable write-back cache. Fix incoming.

**Comment by nh2** [comment]
> First thing `--max-parallel-file-reads` is effectively the number of threads to use, 600 is way too high, should be on the order of 10-20 max, that's the cause for OOM.

@jkowalski Why is that? I have millions of small files on a network file system (latency). I need to use many threads to fill my 10 Gbit/s pipe. Even if kopia read 600 of them into memory (does it do that, or streaming reads?), it could shouldn't exhaust my 128 GB RAM.

**Comment by nh2** [comment]
> This is not necessarily wrong when a single client is used, but may cause problems when multiple Kopia clients share repository

@jkowalski Should #2219 close this issue? I have only 1 kopia client running against the rclone Dropbox.

**Comment by basldfalksjdf** [comment]
> > This is not necessarily wrong when a single client is used, but may cause problems when multiple Kopia clients share repository
> 
> @jkowalski Should #2219 close this issue? I have only 1 kopia client running against the rclone Dropbox.

I think the key to the fix is this:

> some of the writes... never happen, in particular in
case of crashes.

In effect, Kopia thinks Rclone uploaded to the repo whereas Rclone still has the blob in cache and does not have a chance to upload before a crash.

**Comment by nh2** [comment]
> I think the key to the fix is this:

@basldfalksjdf Ah, hmm. There is an "and" in between those two sentences, so I assumed that both conditions have to apply for the fix to help.

> when multiple Kopia clients share repository **and** some of the writes are reordered or never happen

@jkowalski @basldfalksjdf 

Beyond that, I don't quite understand why `--vfs-write-back=0s` from the linked PR would help the isse:

https://rclone.org/commands/rclone_serve_webdav/#vfs-file-caching claims:

> Note that files are written back to the remote only when they are closed and if they haven't been accessed for `--vfs-write-back` seconds. _If rclone is quit or dies with files that haven't been uploaded, these will be uploaded next time rclone is run with the same flags._

So in the case of only 1 kopia process accessing the Dropbox, shouldn't this "just work" given that the files would be "uploaded next time rclone is run with the same flags"?

---

Also, according to those docs, wouldn't `--vfs-cache-mode off` be better than `--vfs-write-back=0s`?

I cannot find anything on that page that guarantees that writeback is truly disabled with `0s` -- maybe `0s` still sets up a timeout, which is just very short (but still racy)?

---

Finally, [`rclone_storage.go`](https://github.com/kopia/kopia/blob/a2fccf3779271b364e79248142dcf89b66b4f8ea/repo/blob/rclone/rclone_storage.go) spawns `rclone serve webdav` as a subprocess. When `kopia` gets OOM-killed, that should not necessarily kill the `rclone` process (on Linux, it would by default be reparented to `init`). So the "rclone dies" case should not even trigger, and rclone should have time to perform its writeback. Am I missing something?

**Comment by nh2** [comment]
Short ping @jkowalski just to be sure you're aware of the above rclone caching parts.
