### ISSUE TITLE
[Feature Request]: Add a button to begin the <starting up> process again

### ISSUE THREAD

**Issue by improve-code** [kopia/kopia#2225]
Because I have kopia autostarted it is already running when I plug in the drive on which the repository is.
The repository then doesn't appear in the list of kopia-gui. So I always quit via kopia-ui and restart kopia to access the repository.
It would be nice if there would be a button to begin the <starting up> process again for the repositories which aren't connected.

Maybe that is already existing and I have overseen it. I tried it by clicking on the <initializing> buttons and waiting some time – maybe not long enough.

**Comment by basldfalksjdf** [comment]
Im not sure what you mean. 

If you have a repo for a local drive, KopiaUI will automatically try to connect to it whenever KopiaUi starts. If KopiaUI cannot connect to the repo, it will continually try and sleep itself after every failure. So, it will wait 30s after first failure, 1m after second failure, and so on. 

Perhaps what is happening is that you are expecting KopiaUI to instantly connect to your repo when the drive is connected, but KopiaUI will only try to connect after its sleep cycle is over, which can be a few minutes if many failures happened.

**Comment by improve-code** [comment]
Yes it is as you described. I expected it would go faster.

When Kopia was running around 30 minutes and it took around 3 minutes until it connected to the repository.
When I just started kopia and plugged in the drive a little later, it just took around 30 seconds, 

I don't know, whether there is a common need to change that.

**Comment by basldfalksjdf** [comment]
AFAIK, this is working as intended. 

KopiaUI intentionally is put to sleep when a connection fails, so as to avoid continually trying to reconnect to a failed connection and also to give time for the repo to come online. This sleep time increases the longer KopiaUI fails to make a connection.

I don't think this will, or should, be changed. Unless I have misunderstood what you are asking for? If yes, then please clarify. If not, then please close this FR.

**Comment by improve-code** [comment]
Yes you understood me. It just is a little effort with drives which are connected only for backup when kopia is already running.
