### ISSUE TITLE
[Clock skew] Repo on SMB Share never can run maintenance

### ISSUE THREAD

**Issue by cocoon** [kopia/kopia#2227]
Hi there,
I am very new to Kopia and I was trying to get it to work but it always refuses to run the maintenance tasks.

KopiaUI-0.10.7-win
Windows 11
I expect that it might not be able to update a timestamp for a file, the share is simply a USB drive connected to a router.

Even when I create a fresh new repository from scratch and snapshot some test files and manually try to run maintenance it fails with:

```
ERROR error checking for clock skew: Clock skew detected: local clock is out of sync with repository timestamp by more than allowed 5m0s (local: 2022-07-25 12:32:30.3368196 +0200 CEST repository: 2022-07-17 14:05:16.0556 +0200 CEST). Refusing to run maintenance.

ERROR error checking for clock skew: Clock skew detected: local clock is out of sync with repository timestamp by more than allowed 5m0s (local: 2022-07-25 13:14:17.8084333 +0200 CEST repository: 2022-07-17 14:05:16.0556 +0200 CEST). Refusing to run maintenance.

ERROR error checking for clock skew: Clock skew detected: local clock is out of sync with repository timestamp by more than allowed 5m0s (local: 2022-07-25 13:14:31.4922938 +0200 CEST repository: 2022-07-17 14:05:16.0556 +0200 CEST). Refusing to run maintenance.

... run snapshots in between

ERROR error checking for clock skew: Clock skew detected: local clock is out of sync with repository timestamp by more than allowed 5m0s (local: 2022-07-25 13:17:05.0418835 +0200 CEST repository: 2022-07-17 14:05:16.0556 +0200 CEST). Refusing to run maintenance.
```

Is there anything I can do?
I had a quick look at the source code, but it was not easy to follow how to compare times where they come from.

Any small example program with a few lines that just copies a file and tries to do the same to detect "clock skew"?

Would make it easier to try to find a way to maybe use other ways to  force update times.
i.e. like this or whatever the problem is: https://superuser.com/questions/10426/windows-equivalent-of-the-linux-command-touch

**Comment by jkowalski** [comment]
SMB server clock is completely wrong - by more than a week, kopia won't be able to work with this - this is for safety reasons since many aspects of Kopia rely on time being correct to within few minutes. You should enable NTP time synchronization on the server. Pretty much all modern desktop and server OSes now come with NTP enabled.

**Comment by cocoon** [comment]
Hi thanks for the reply. But it is not the clock of the SMB server, because it simply stays always on the first inital date/time when the repository was first created. The time never goes forward it always stays at that time.

That's why I asked, if there would be a small script on how Kopia tries to update the time to check what it does and what goes wrong?

**Comment by jkowalski** [comment]
Timestamps are assigned by the server, there's clearly something wrong with that. Routers are notorious for shipping very buggy file servers (or keeping time for that matter).

Can you login to the router UI and see what time it shows, then set it to current time and try again?

**Comment by cocoon** [comment]
Yes it might be the samba implementation.

here they say with smb v1 it wozkd work, with newer not but if one uses touch for each file after rsync

https://forum.ubuntuusers.de/topic/backup-mittels-rsync-in-verbindung-mit-dem-fri/


That's why I want to try and understand what kopias steps are in detail to check if it could be worked around domehow. Even if it wozld add one more file ops for each file .

**Comment by xxxliqu1dxxx** [comment]
> Maybe Kopia could add a check when creating new repositories and warn upfront, too.

Kopia allows to validate the provider to avoid issues down the road. So upfront, what happens if you run the command kopia repo validate-provider against this SMB share? You may have indication of problems with this.

**Comment by cocoon** [comment]
Ah perfect yes, this is exactly what I think would be good if it would run if someone creates a new repository and warn if problems are found (+ in UI).

I wasn't aware of this command, but it still get no warning about timestamp problems, so this would be a good place to add?

My result:

```
Validating storage capacity and usage
Validating blob list responses
Validating non-existent blob responses
Writing blob (5000000 bytes)
Validating conditional creates...
Validating list responses...
Validating partial reads...
Validating full reads...
Validating metadata...
Running concurrency test for 30s...
All good.
Cleaning up temporary data...
```

I still need to find out how exactly the timestamp is used, what file needs what timestamp and how to validate in a small script to test. Does Kopia only set a timestamp in a single file for the repository or needs it for all files that are copied? Because "repository timestamp" sounds like it could be only one timestamp for the whole snapshot ...

**Comment by xxxliqu1dxxx** [comment]
In reviewing https://github.com/kopia/kopia/blob/daa62de3e48c3314f827e9100d760c94ca7e4221/internal/providervalidation/providervalidation.go

It seems like it's already performing the clock time / delta validation... here's an excerpt of the code that seems to indicate it would have done the test and actually passed since it did not throw the error? There only seems to be a log if there's an error but no clean return/log if it passes.

```
	now := clock.Now()

	timeDiff := now.Sub(bm.Timestamp)
	if timeDiff < 0 {
		timeDiff = -timeDiff
	}

	if timeDiff > opt.MaxClockDrift {
		return errors.Errorf(
			"newly-written blob has a timestamp very different from local clock: %v, expected %v. Max difference allowed is %v",
			bm.Timestamp,
			now,
			opt.MaxClockDrift,
		)
```

I therefore think there is a log missing where it should have said "clock drift is under acceptable limits" or something...

**Comment by cocoon** [comment]
I did some testing, created a small program and found out what happens to the files.

If I copy a file to the share it's original creation date is replaced by the last write time.
If I try to change the creation date, it seems to keep the same as before, so the last write time.

I currently can't explain, why in my test below if I copy from the share back to C: it gets the original creation time. (Cache?)
If I copy it manually with Explorer from the share back to C: it gets the current date time as creation time.

```

#### Source ###
C:\tmp1\Eula-Test-Text1.txt

creation: 23.07.2020 15:52:27 FileTimeUTC: 132399859473903946
modification: 07.11.2015 21:30:34 FileTimeUTC: 130914018342415173

copied C:\tmp1\Eula-Test-Text1.txt to R:\Test\Eula-Test-Text1.txt

#### Target ###
R:\Test\Eula-Test-Text1.txt

creationTarget: 07.11.2015 21:30:34 FileTimeUTC: 130914018340556000
modificationTarget: 07.11.2015 21:30:34 FileTimeUTC: 130914018340556000
Set CreationTime because 130914018340556000 is diffrent to Source 132399859473903946 ...
Set LastWriteTime because 130914018340556000 is diffrent to Source 130914018342415173 ...

#### Target Re-Check after modify###
R:\Test\Eula-Test-Text1.txt

creationTarget2: 07.11.2015 21:30:34 FileTimeUTC: 130914018340556000
modificationTarget2: 07.11.2015 21:30:34 FileTimeUTC: 130914018340556000

copied R:\Test\Eula-Test-Text1.txt to C:\tmp1\Eula-Test-Text2.txt

#### File3 (Copied from Share to C:) ###
C:\tmp1\Eula-Test-Text2.txt

creationFile3: 23.07.2020 15:52:27 FileTimeUTC: 132399859473903946
modificationFile3: 07.11.2015 21:30:34 FileTimeUTC: 130914018340556000
Set LastWriteTime for File3 because 130914018340556000 is diffrent to Source 130914018342415173 ...

#### File3 Re-Check after modify###
C:\tmp1\Eula-Test-Text2.txt

creationFile3_2: 23.07.2020 15:52:27 FileTimeUTC: 132399859473903946
modificationFile3_2: 07.11.2015 21:30:34 FileTimeUTC: 130914018342415173

```
