### ISSUE TITLE
FreeBSD port available

### ISSUE THREAD

**Issue by nunotexbsd** [kopia/kopia#2231]
Hello,

FreeBSD port available:
https://www.freshports.org/sysutils/kopia/

Cheers,

Nuno Teixeira

**Comment by adowair** [comment]
Thanks @nunotexbsd, this is great. A PR updating the [Installation docs page](https://kopia.io/docs/installation/) would be most welcome =).

**Comment by nunotexbsd** [comment]
Done at #2237

Cheers

**Comment by jkowalski** [comment]
Does it mean we can stop making FreeBSD binaries?

BTW. I think you should not set `FreeBSD/ports` as the value for `github.com/kopia/kopia/repo.BuildGitHubRepo` since this will make Kopia do update checks against non-existent GitHub repo. Just set it to an empty value.

**Comment by nunotexbsd** [comment]
Hi,

> Does it mean we can stop making FreeBSD binaries?

Yes, I suppose so since there will be binary packages available soon.

> BTW. I think you should not set `FreeBSD/ports` as the value for `github.com/kopia/kopia/repo.BuildGitHubRepo` since this will make Kopia do update checks against non-existent GitHub repo. Just set it to an empty value.

I've removed it and now `kopia --version` shows: `0.11.3 build: 20220727 from:`
Before I commit it, is `repo.BuildInfo="`date +%Y%m%d`"` correct? Like OpenBSD port, this variable is set to date.

Cheers
