### ISSUE TITLE
Problem adding S3 repository with eu-west-1

### ISSUE THREAD

**Issue by krzyk** [kopia/kopia#2236]
This is my first try with kopia, but I haven't found a solution and no other similar issue was reported.

I'm doing following command:
```
kopia repository create s3 --bucket test-zdjecia-kopia --region s3-eu-west-1 --access-key=KEY --secret-access-key=SECRET
```
And I get following response:
```
ERROR can't connect to storage: unable to determine if bucket "test-zdjecia-kopia" exists: Head "https://test-zdjecia-kopia.s3.dualstack.us-east-1.amazonaws.com/": 301 response missing Location header
```

Why is it trying `us-east-1`?
When I added `--endpoint s3.eu-west-1.amazonaws.com` I got exactly same response.

```
% kopia --version                                                                                                            ~
0.11.3 build: 317cc36892707ab9bdc5f6e4dea567d1e638a070 from: kopia/kopia
```

**Comment by basldfalksjdf** [comment]
I suspect `--endpoint s3.eu-west-1.amazonaws.com --region s3-eu-west-1` is why. That should be `--endpoint s3.eu-west-1.amazonaws.com --region eu-west-1`.

You can actually even drop `--region eu-west-1` because you are specifying `--endpoint s3.eu-west-1.amazonaws.com`

**Comment by adowair** [comment]
@krzyk feel free to reopen the issue or hop over onto Kopia's [Slack channel](https://join.slack.com/t/kopia/shared_invite/zt-1d7j4i2t3-bF_X~~JKNbQw6Uu1b6zfAQ) if you're still running into issues
