### ISSUE TITLE
S3 regression when connecting to non-existing bucket

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#2247]
This issue is to track fixing the regression introduced in #2213.

When running `make test` on dev machine, the test `TestS3Connect` hangs, it's not happening on CI.

@wlan0 investigated this in https://github.com/kopia/kopia/pull/2213#issuecomment-1197296465 and it looks it's a minio bug.

I'm going to temporarily disable the failing test, but we should quickly fix this properly by either:

a) rolling back #2213

or

b) fixing the bug in minio and upgrading to their next release if that's feasible

**Comment by jkowalski** [comment]
@julio-lopez thoughts?

**Comment by ntolia** [comment]
If this is a MinIO bug, let's raise the issue (or a fix) there and see what they feel? Thoughts, @wlan0?

**Comment by wlan0** [comment]
@jkowalski @ntolia I've added a fix in minio-go: https://github.com/minio/minio-go/pull/1682

**Comment by ntolia** [comment]
> @jkowalski @ntolia I've added a fix in minio-go: [minio/minio-go#1682](https://github.com/minio/minio-go/pull/1682)

🙏. I see it has been accepted and hopefully will merge soon.

**Comment by wlan0** [comment]
Just fixed the broken tests in minio-go - PR should be merged soon

**Comment by wlan0** [comment]
Merged: https://github.com/minio/minio-go/pull/1682

**Comment by adowair** [comment]
https://github.com/minio/minio-go/pull/1682 has been pulled in: #2378. We can now re-enable the test.
