### ISSUE TITLE
Deleting snapshots at KopiaUI not actually deletes the files from repository?

### ISSUE THREAD

**Issue by vitaliypo** [kopia/kopia#2248]
So I was expecting that deleting snapshots will also delete the files from the repo folder and free up some space. Maybe I'm getting the idea wrong?

**Steps to reproduce:**

0. Add test repo and a snapshot, make at least one snapshot
1. Check the size of repo folder (1 GB in my case)
2. Choose all the snapshots in KopiaUI and delete it (no matter if you specify to delete policy too or not)
3. Check the size of repo folder

**Expected result:** Files have been deleted, so the repo folder should not be equal to 1GB anymore (closer to 0GB)
**Actual result:** The repo folder has the same size of 1GB

**Comment by xxxliqu1dxxx** [comment]
Kopia only marks the files to be deleted but does not delete the files yet. Maintenance is what actually deletes the files and it relies on passage of time before it safely deletes the blobs.
Therefore, next time you take a snapshot, or if you run kopia maintenance run, if enough time has passed, usually 24 hours, it would actually safely delete the files.

**Comment by vitaliypo** [comment]
> Starting with v0.6.0 the repository maintenance is automatic and will happen occasionally when kopia command-line client is used
> https://kopia.io/docs/advanced/maintenance/
So if I'm using only KopiaUI, maintenance will never be triggered?
Why not remove the files right away? It looks like there's no way to restore them anyway after the snapshot was "marked to be deleted".

**Comment by xxxliqu1dxxx** [comment]
It's all automatic from UI or CLI. KopiaUI triggers maintenance when needed, on snapshot command... you will see something like this when it ran:
![image](https://user-images.githubusercontent.com/83290244/181772301-e4ee1f9d-b3e0-4bdd-a457-7cf7f9e96aae.png)

**Comment by xxxliqu1dxxx** [comment]
> Why not remove the files right away? It looks like there's no way to restore them anyway after the snapshot was "marked to be deleted".

Kopia is made intelligently in the sense that if these files are getting snapshot again from another client it does not delete the blob yet as it can re-use these files vs reuploading the same content again. As Kopia is made to be used in a "one repo" and multiple clients, it's not because client 1 deleted snapshot that contains "blob a" that another client will not snapshot something else which has the same blobs. Therefore it does not delete it unless it's not been used for a certain period of time. Hence the passage of time. 

As this is not an issue, I would recommend you close this github issue and use the forum to ask these kind of questions. The forum is here: https://kopia.discourse.group/

**Comment by vitaliypo** [comment]
Alright, thanks for the info.

**Comment by adowair** [comment]
One small piece to add is that, afaik, maintenance runs only when either the UI or Kopia Server are running (even in the background). Otherwise, there's nothing to trigger the `kopia maintenance` command periodically.

**Comment by xxxliqu1dxxx** [comment]
> One small piece to add is that, afaik, maintenance runs only when either the UI or Kopia Server are running (even in the background). Otherwise, there's nothing to trigger the `kopia maintenance` command periodically.

I am pretty sure kopia snapshot from the CLI triggers maintenance if needed with recent versions. Perhaps Jarek can confirm, but I believe I have seen this behavior before.

**Comment by tobiasBora** [comment]
You can now force kopia to skip safety measures if you don't want to wait 24h https://kopia.io/docs/advanced/maintenance/#maintenance-safety

```
 $ kopia maintenance run --full --safety=none
```
