### ISSUE TITLE
Manual pages contribution

### ISSUE THREAD

**Issue by nunotexbsd** [kopia/kopia#2249]
How to contribute creating manual pages to project?

- Creating from scratch
- Converting from some kind of source like adoc, html

Cheers

**Comment by jkowalski** [comment]
If you're asking about Unix `man` support, we use https://github.com/alecthomas/kingpin for our command line parsing and that provides `--help-man` flag that can output man-formatted files to stdout.

From what I can tell it's quite bare-bones, but they support customizable templates:
https://github.com/alecthomas/kingpin/blob/17f40c25f4977ef446a79e34e46270665dffa263/templates.go#L149 so perhaps something interesting could be done here. We have customized one template already in https://github.com/kopia/kopia/blob/master/main.go

In general all command-line reference content is generated from the source code and we produce the website section https://kopia.io/docs/reference/command-line/ using https://github.com/kopia/kopia/tree/master/site/cli2md

Other conceptual docs are in https://github.com/kopia/kopia/tree/master/site/content/docs

Let me know if this is what you were asking for.

**Comment by nunotexbsd** [comment]
I'm looking for Unix man support and now I can generate 'kopia.1' man page and install it toguether with FreeBSD kopia port.
Any change to generate kopia commands to manuals, like: 'kopia-blob.1', 'kopia-repository.1', etc, as show by `kopia help <command>`?

**Comment by jkowalski** [comment]
That would need to be investigated, but I'm sure the template is flexible. Alternatively we could do what `cli2md` is doing and manually generate required files.

**Comment by nunotexbsd** [comment]
Ok, I have a kopia general command Unix manual generated for port:
```
post-build:
        ${GO_WRKDIR_BIN}/${PORTNAME} --help-man > ${WRKSRC}/${PORTNAME}.1
```
When you say "alternatively" we could use `cli2md`, does it mean that it's possible to produce kopia-command.1 manuals like, eg,
https://github.com/freebsd/poudriere/tree/master/src/man

thanks
