### ISSUE TITLE
Question about the functionality

### ISSUE THREAD

**Issue by Roki100** [kopia/kopia#2262]
Hello! Is Kopia able to pause making of a snapshot to continue later?
I'm looking to cloud backup over 20TB of raw data and with my internet connection that will take a while, and i am not willing to leave my stuff running 24/7, instead i would like to split the upload to multiple sessions

**Comment by jkowalski** [comment]
Yes. It will checkpoint roughly every 45 minutes and it can resume from that point.
To stop the upload, it's easiest to do Ctrl-C.

**Comment by Roki100** [comment]
Thank you
