### ISSUE TITLE
Suspend/Sleep causes snapshot process to lockup

### ISSUE THREAD

**Issue by FallingSnow** [kopia/kopia#2271]
I'm running a backup of my laptop via `kopia snapshot create /`. When I walk away from my computer my laptop goes to sleep. Once out of sleep, the process seems to have completely locked up, it doesn't respond to a SIGINT (ctrl+c) either.
I assume since it isn't responding to a interrupt signal that this is not intended behavior?

Last few lines of the log and me trying to kill the process:
```
 ! Ignored error when processing "home/ayrton/.gnupg/S.dirmngr": unknown or unsupported entry type
 \ 7 hashing, 1127431 hashed (1.2 TB), 474 cached (172 MB), uploaded 212.8 GB (33792 fatal errors) (357 errors ignored), estimated 141.3 TB (0.9%) 412h54m4s left 
 ! Error when processing "home/ayrton/.step-no-ssh/db/000006.sst": permission denied
 \ 5 hashing, 1333092 hashed (1.5 TB), 474 cached (172 MB), uploaded 238.4 GB (33793 fatal errors) (357 errors ignored), estimated 141.3 TB (1.1%) 384h43m44s left^C
^C^C^C
^C
^C
```

**Comment by FallingSnow** [comment]
I've just discovered that even switching networks causes the process to lockup.

**Comment by jkowalski** [comment]
whaqt is the OS you're using (I'm guessing Linux) and what's the backend?

**Comment by jkowalski** [comment]
you should be able to find more info in the log files. I'm guessing backend has disconnected as is not able to reconnect.

**Comment by FallingSnow** [comment]
I've discovered the same lockup behavior happens when I just press `ctrl+c`. Still need to get to those logs lol
