### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by sssheridan** [kopia/kopia#2283]
The page says "To see how much data is saved by compression in a repository, use `kopia content stats` command."

However, it doesn't for me. I get:
````
# kopia content stats
Count: 1849613
Total Bytes: 2.3 TB
Average: 1.3 MB
Histogram:

        0 between 0 B and 10 B (total 0 B)
    10079 between 10 B and 100 B (total 703.4 KB)
   548751 between 100 B and 1 KB (total 231.1 MB)
   306519 between 1 KB and 10 KB (total 1.3 GB)
   176948 between 10 KB and 100 KB (total 6.9 GB)
   239179 between 100 KB and 1 MB (total 87.2 GB)
   568137 between 1 MB and 10 MB (total 2.2 TB)
        0 between 10 MB and 100 MB (total 0 B)

# kopia --version
0.11.3 build: 317cc36892707ab9bdc5f6e4dea567d1e638a070 from: kopia/kopia
````

**Comment by basldfalksjdf** [comment]
Did you enable compression before you ran the snapshot? See https://kopia.io/docs/faqs/#how-do-i-enable-compression

**Comment by jkowalski** [comment]
You likely have a very old repository that had a different compression model (applied before hashing, not after hashing), that one did not support statistics.

`kopia repo status` can confirm whether you have `Content compression: false`.

**Comment by sssheridan** [comment]
Yep, that was it. I didn't realize that my old repo was stuck in its old ways; I've started a new repo and I see the compression info.
