### ISSUE TITLE
Kopia using already existing rclone encrytion?

### ISSUE THREAD

**Issue by githubbapoopa** [kopia/kopia#2285]
I'm new to kopia and kopiaui so sorry for any dumb questions.

kopia uses it's own encryption and that's fine. But:

Could kopia use an existing repository that was aleady encrypted with rclone crypt?

Think of it as a "transparent" mode. Not putting it's own encryption "in the way" but letting rclone do it's job and only supporting in setting up snaphots, policies etc.

Possible?

see also:

https://kopia.discourse.group/t/is-there-any-way-to-disable-encryption/807/5

**Comment by basldfalksjdf** [comment]
You cannot disable encryption on Kopia AFAIK. That's by design. You can use Kopia to backup an existing rclone repository, but Kopia cannot "import" a repository from rclone.
