### ISSUE TITLE
Connect Error: INTERNAL: internal server error: cannot access storage path: stat \\server\example\test: no such file or directory

### ISSUE THREAD

**Issue by Iceman248** [kopia/kopia#2289]
I'm getting this error when trying to set my repository with my server available over SMB. I used UNC path that works for other stuff, but Kopia refuses to see the directory it seems no matter which shared folder I tried. I looked as much info as I could on the subject, but got nowhere. I am using the UI version v0.11.3.

**Comment by jkowalski** [comment]
Are you using UI or command line? 

Couple things to try:

1. Replace `\` with `\\` in case shell is messing with the command line.
2. Try replacing `\` with `/`
3. Try mounting the UNC path as a drive and use that?

**Comment by Iceman248** [comment]
UI. Only #3 worked to get past that part, but permission is denied trying to create the repo. I can see through file browser that there is only read permissions for the mounted SMB share I made.

**Comment by basldfalksjdf** [comment]
What OS are you on? I am able to backup via SMB using UNC path just fine (on Windows 10).

> I can see through file browser that there is only read permissions for the mounted SMB share I made.

Are you saying that you only have read permissions to the SMB share outside of Kopia? If so, this sounds like some configuration problem at your end because Kopia wouldn't cause that.

**Comment by Iceman248** [comment]
> What OS are you on? I am able to backup via SMB using UNC path just fine (on Windows 10).
> 
> > I can see through file browser that there is only read permissions for the mounted SMB share I made.
> 
> Are you saying that you only have read permissions to the SMB share outside of Kopia? If so, this sounds like some configuration problem at your end because Kopia wouldn't cause that.

Linux. I only have the read permissions only issue after mounting the SMB share to Linux. If I connect through a normal SMB path, I have full read write permissions.

**Comment by Iceman248** [comment]
Nevermind, I had to figure out how to mount SMB share with me as owner so I would have RW access.
