### ISSUE TITLE
Kopia snapshot restore after an upgrade to newer version hits "new_version_of_kopia_is_required_to_open_this_repository" error

### ISSUE THREAD

**Issue by chaitalisg** [kopia/kopia#2301]
I am able to reproduce the issue with the help of test/robustness_test/robustness_test.go

Steps to reproduce the issue:
1. Check out kopia commit `42ba517a831e1de6e0e646849884595d6f08d828`. Let's call this older kopia.
2. Update the `ConnectOrCreateFilesystem` in test/tools/kopiarunner/kopia_snapshotter.go to create a filesystem repo of format version 1. 
3. Using the older kopia version, run `TestManySmallFiles` in `robustness_test.go` with an empty local dir as `repo-path-prefix`. This creates a new repo in the dir.
4.  Check out kopia commit `b61a7627e9af0148eea342a8f9842ea16a23a167`. Build it. Let's call this newer kopia.
5. Run the same test `TestManySmallFiles` in `robustness_test.go` with the `repo-path-prefix` used in step 3 with env variable `UPGRADE_REPOSITORY_FORMAT_VERSION` set to `ON`.  This would force the test to reuse the repo and perform a repo upgrade.
6. The `restore snapshot` operation in the test throws the error below:7. 

`
ERROR failed to open repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob n00000000000000000000000000000000-repository_unreadable_by_this_kopia_version_upgrade_required: error decrypting BLOB n00000000000000000000000000000000-repository_unreadable_by_this_kopia_version_upgrade_required: unable to decrypt content: cipher: message authentication failed
ERROR open repository: unable to open repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob n00000000000000000000000000000000-repository_unreadable_by_this_kopia_version_upgrade_required: error decrypting BLOB n00000000000000000000000000000000-repository_unreadable_by_this_kopia_version_upgrade_required: unable to decrypt content: cipher: message authentication failed`

**Comment by Shrekster** [comment]
Looks like Kopia does not ignore the poison BLOB as of now. @jkowalski were you planning on adding the blob explosion during index load for newer copies ?
