### ISSUE TITLE
Kopia server ignores the manual scheduling policy setting

### ISSUE THREAD

**Issue by ekutner** [kopia/kopia#2302]
The documentation is pretty thin on this so my assumptions on expected behavior may be wrong, although I think they are pretty reasonable. 
I have two policies configured on folders where one is a sub-folder of the other, so it inherits the policy from its parent. The parent has a backup schedule configured but on the sub-folder I've set the manual schedule flag. There is no way to reset the snapshot times inherited from the parent at the sub-folder level.

**Expected behavior:** The manual schedule in the sub-folder policy should override the schedule inherited from the parent and the associated snapshot should only run manually.

**Actual behavior:** The manual flag is ignored. The scheduling is inherited from the parent and snapshots are executed based on the inherited schedule.

This is the relevant section from the sub-folder policy:
```
Scheduling policy:
  Scheduled snapshots:
  Snapshot times:                           inherited from Eran@homepc:D:\Eran\Documents
    1:00
    10:00
    13:00
    16:00
    19:00
    22:00
  Manual snapshot:                   true   (defined for this target)
```
And this is how it looks in the UI:
![image](https://user-images.githubusercontent.com/5628151/184006706-59417b99-3530-4eea-8355-6a68c81e8763.png)

**Comment by basldfalksjdf** [comment]
I believe this is the same bug as mentioned at https://github.com/kopia/kopia/issues/2274

**Comment by ekutner** [comment]
@basldfalksjdf it's not the same bug, in fact it's kind of the opposite. In #2274 the problem is that the schedule is ignored and snapshots are not performed. In this issue they are performed even when they shouldn't be because there is a manual only flag defined. 
By the way, I am using Time Of Day scheduling and it's working fine, so there may be something more nuanced about the scenario in which it doesn't work.

**Comment by ekutner** [comment]
I just discovered a workaround for this issue. Disabling inheritance for the policy prevents it from inheriting the schedule from the parent folder and then whatever is defined for the policy itself takes effect.

**Comment by zero-thermo** [comment]
> I just discovered a workaround for this issue. Disabling inheritance for the policy prevents it from inheriting the schedule from the parent folder and then whatever is defined for the policy itself takes effect.

How did you disable inheritance? When I change "Manual Snapshots Only" to "no", Kopia UI does not save and the setting reverts to "inherit from parent"

**Comment by ekutner** [comment]
@zero-thermo In the GUI you can edit the policy, to the to the "other" section and check the box next to "Disable Parent Policy Evaluation".
With the command line you can use the --inherit flag on *policy set* to disable the inheritance.
