### ISSUE TITLE
Add option to run as root

### ISSUE THREAD

**Issue by Sc0th** [kopia/kopia#2306]
Before I get shot down, hear me out....

I am attempting to run Kopia in a k8s container, it looks great but in order for it to work I need to be able to run as root in order to access the NFS shares that are mounted into the container. 

Even then I am a little confused as the mounts are world read yet I still get permission issues when I try to add the location as a snapshot.

I cannot be changing the ownership of filesystem structures to suit backups.

**Comment by jkowalski** [comment]
The latest `kopia` switched to Ubuntu-based image and will run as root. It's not in `latest` yet, but you can pull `kopia/kopia:unstable` and it should work.

**Comment by Sc0th** [comment]
Awesome, thank you!
