### ISSUE TITLE
Unable to set docker timezone

### ISSUE THREAD

**Issue by Sc0th** [kopia/kopia#2311]
Apologies if I am missing something, however the docker (k8s container) defaults to UTC and I am struggling to find a way to change it, the TZ flag seems to be ignored and mounting /etc/locatime &| /etc/timezone has no impact.

I am unable to make the --timezone flag do anything.

Does the tzdata packages need adding? (I am using :unstable)

Cheers!

**Comment by Sc0th** [comment]
FWIW I got around it by mounting /usr/share/zoneinfo into the container, hacky but it works, I assume adding tzdata to the image would be a cleaner fix.

**Comment by mitchplze** [comment]
Also having this issue.

**Comment by CacklingCapybara** [comment]
Updated from 11.3 to 12.1. In 11.3, the time scheduling was accurate for me, however with 12.1 setting backups for 3 in the morning was actually running the backup at like 8 in the evening.

As mentioned above, mounting /usr/share/zoneinfo does indeed work.

**Comment by kladderadeng** [comment]
I did the same, after realizing that timestamps where wrong and backups running at the wrong time. Mapping the /usr/share/timezone and setting TZ parameter in my compose file did the trick. Thanks everyone :-)

**Comment by danielgoepp** [comment]
Same issue, same fix. Sure would be nice if this wasn't necessary :( I'm sure Jarek has other things to deal with.

**Comment by danielgoepp** [comment]
I think it's working for me now. I removed the work around, and deleted all my pods, they all came back with the right time still. Unless I'm missing something, yes, I think I can confirm this is good now. Of course the original post was 2022 by someone else :)

**Comment by pretubedongit** [comment]
Backresit already had TZ line. It's a shame that Kopia still did not add that.
