### ISSUE TITLE
ECC does not log on error-correction nor performs write back.

### ISSUE THREAD

**Issue by aaron-kasten** [kopia/kopia#2328]
PR https://github.com/kopia/kopia/pull/2308 adds ECC support for reads from source storage system into Kopia heap memory.  Error correction is done on the heap immediately after being read from the storage system.

The error correction process does not have a mechanism for tracking the number of ECC corrections over time (a log message will do) or write-back when an error is corrected.  This can be important for predicting and resolving failures.

**Comment by Ember-ruby** [comment]
hey stalebot, this seems pretty important
