### ISSUE TITLE
Kopia.io website has an expired certificate

### ISSUE THREAD

**Issue by sahensley** [kopia/kopia#2332]
Thanks for the great backup software, I love it :smiley: 

The kopia.io website has an expired certificate and I didn't see a separate repo for reporting issues for it, so I'm putting it here.

Looking at the certificate, it expired on: "Sat, 20 Aug 2022 19:19:38 GMT"

**Comment by martinpengellyphillips** [comment]
fyi this is what shows in my browser (firefox) when trying to access the site:

```
Secure Connection Failed
An error occurred during a connection to kopia.io. Cannot communicate securely with peer: no common encryption algorithm(s).
Error code: SSL_ERROR_NO_CYPHER_OVERLAP
```

**Comment by sahensley** [comment]
Hooray, a new certificate is in place.  Closing this.
