### ISSUE TITLE
Optimize `DirEntry` by not storing timezone pointers?

### ISSUE THREAD

**Issue by nh2** [kopia/kopia#2342]
A small-ish optimisation idea:

In

https://github.com/kopia/kopia/blob/dd1a6aff8d5a1e7653f402593ad9f7fb65f246e6/snapshot/manifest.go#L122-L133

`ModTime time.Time` is [this struct](https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/time/time.go;l=129-150):

```go
type Time struct {
  wall uint64
  ext  int64
  loc *Location
}
```

This might be overkill for storing file modification times; single `uint64` is usually enough for storing them on most file systems, and a translation to UTC could be done at storage time.

This would have the benefit of reducing emory overhead of `DirEntry` (less small objects allocated because the `*Location` pointer is gone), and also reduce GC traversal times: See e.g. https://segment.com/blog/allocation-efficiency-in-high-performance-go-services/:

> Now the `retryItem` doesn’t contain any pointers. This dramatically reduces the load on the garbage collector as the entire footprint of `retryItem` is knowable at compile time

**Comment by jkowalski** [comment]
This is a great idea, I've sent out #2343 to implement it.
