### ISSUE TITLE
Mounting snapshot in FreeBSD 13.1 unsupported?

### ISSUE THREAD

**Issue by hendrylee** [kopia/kopia#2348]
I run kopia both on the machine used as an SFTP repository as well as on clients sending snapshots to the repo.

It works fine for connecting, sending snapshots, listing, etc.

But when I tried mounting a snapshot, it returns:

`ERROR mount error: mounting is not supported`

kopia restore works though.

Is this expected?

Can somebody point me on the right direction on how to fully use kopia on FreeBBSD since mounting is the 'recommended' way to restore backups?

**Comment by adowair** [comment]
Hey @hendrylee , it looks like Freebsd support was introduced here: #964. Per the commit notes, it looks like.
> build: added freebsd build (untested) with mounting disabled until [go-fuse](https://github.com/hanwen/go-fuse) has it

It looks like [this](https://github.com/hanwen/go-fuse/issues/366) is the latest on `go-fuse`'s support for FreeBSD.
