### ISSUE TITLE
Mac tray icon should have a transparent background

### ISSUE THREAD

**Issue by rsammelson** [kopia/kopia#2356]
The mac tray icon should have a transparent section in the middle and border, instead of black, in order to match the theme of the built-in icons. See image:

<img width="257" alt="Screen Shot 2022-09-01 at 10 12 52" src="https://user-images.githubusercontent.com/20521763/187935902-91bc4bb0-6c01-4d84-bf18-e258138ffdbf.png">

**Comment by rsammelson** [comment]
This was fixed at some point.

**Comment by mildblimp** [comment]
Actually, it is only half fixed. The black border should still be removed, which is visible on a light background. Can you reopen the issue or should I make a new one?

See the attached image:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/71217137/235127983-a09b70a2-f2ec-4207-b35e-fb15d2eb30f4.png">

**Comment by dominikmayer** [comment]
I think the Mac icon has several issues:

1. It has two colors, which doesn't fit in with all the monochrome icons
2. It is way too wide and also a bit too high
3. Is is always white, even in dark mode, where it should be black

As I don't have the original source file I used an image editor to provide two suggestions:

![kopia-tray](https://github.com/kopia/kopia/assets/159476/eb6acd85-f9c0-4df7-9368-6e49a7024583)
![kopia-tray@2x](https://github.com/kopia/kopia/assets/159476/fc32275d-3572-41e4-b18c-e644fc42d371)

(I can't try them in the app so I don't know if they solve all the issues.)

If these are set as monochrome template images, they should be shown in black or white depending on the display mode. I don't know how to do this in Go, but for reference [this](https://developer.apple.com/documentation/appkit/nsimage/1520017-template) is the Swift documentation.

More guidelines for Mac status bar icons can be found [here](https://bjango.com/articles/designingmenubarextras/).
