### ISSUE TITLE
scope of KOPIA_PASSWORD variable and kopia server

### ISSUE THREAD

**Issue by deajan** [kopia/kopia#2371]
Hello,

I'm currently writing a backup benchmark script that uses restic, borg, duplicacy, bupstash and kopia.
While my first set of benchmarks was succesful, I found kopia to be quite slow on SFTP and wanted to test it's HTTPS server implementation.

After fiddling around alot, I found that I'd always get the following error:
```
ERROR failed to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = access denied for backup-bench@backup-bench-source: EOF
ERROR open repository: unable to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = access denied for backup-bench@backup-bench-source: EOF
```

This error was present for each kopia command once I've connected to the remote kopia repository server.
I found that I needed to wipe KOPIA_PASSWORD variable via `export KOPIA_PASSWORD=`
I've used KOPIA_PASSWORD variable for my SFTP setup, but I can't wrap my head around why it's presence would make any command issued to the kopia server fail with a permission error (kopia server user and password are setup correctly).
Do you have any idea why ? I used the exact same KOPIA_PASSWORD variable on the kopia server machine when creating the repository.

As a side note, I noticed that when using kopia server, the source system doesn't eat alot of cpu, but the target system where kopia server resides skyrockets.
Is the dedup and compression still done on the system I launch kopia snapshot create, or is it done by the repository server ?

Best regards.

PS: backup script is found at https://github.com/deajan/backup-bench

**Comment by jkowalski** [comment]
`KOPIA_PASSWORD` is basically an alias for `--password` parameter, if you don't pass it, kopia will read stored password (usually from keychain, but can also use a file) that was passed at `repo connect` time.

Given different nature of server and non-server passwords, you're likely mixing them up.

Also, SFTP is one of the slowest backends, because of limitations of the underlying library, I would recommend against using it for benchmarking, pretty much everything else is going to be faster. Definitely don't use `--external`

**Comment by deajan** [comment]
> KOPIA_PASSWORD is basically an alias for --password parameter,
Understand that. What puzzles me here is that setting KOPIA_PASSWORD variable on the machine that tries to connect to the kopia server machine, having the same KOPIA_PASSWORD variable content will fail.
I'm not mixing up user passwords, server control passwords and repository passwords IMHO.

> Also, SFTP is one of the slowest backends, because of limitations of the underlying library, I would recommend against using it for benchmarking, pretty much everything else is going to be faster. Definitely don't use --external
Yes, I noticed SFTP was really slow, hence I recoded my script to use the kopia server, but I have a real performance problem as it seems, see #2372

**Comment by skironDotNet** [comment]
Is KOPIA_SERVER_PASSWORD a valid env var substitute for `--server-password` that would be visible with `ps aux | grep kopia` ?
