### ISSUE TITLE
[Feature Request] Add a new environment variable for checking if snapshot is created or not for after actions

### ISSUE THREAD

**Issue by sm1999** [kopia/kopia#2374]
With v0.11.0 Kopia introduced a feature to Ignore Identical Snapshots.
It will be great if we can check whether a snapshot is created or not in the after actions.
e.g. Adding a variable like `$SNAPSHOT_CREATED` to `after-snapshot-root-action` which will have value `yes` or `no`.

**Comment by adowair** [comment]
Hey @sm1999 , just to be sure, what do you mean by `"in the after actions"`?

There's probably a few ways to expose such information. Here's a thought: what happens if multiple successive snapshots are ignored? A single environment variable wouldn't be enough to capture that information. Do you have a particular use case in mind?

**Comment by sm1999** [comment]
My use case is that I maintain a local repository and use `sync-to` to sync that repository with one stored in the cloud. I want to run the `sync-to` command from a script only if the snapshot is created and I trigger the script from the `after-snapshot-root` action.

Regarding multiple successive snapshots, I think that actions are run per snapshot. Consider I have a script(which runs `kopia sync-to`) in `after-snapshot-root`. If I run `kopia snap create --all` and in case two or more snapshots are created then my script will be run more than once resulting in multiple executions of `kopia sync-to` (which I don't want). 
I can handle multiple executions in the script so only once `kopia sunc-to` is called but I need a way to know if the snapshot is created or not.

Maybe a new action can be helpful which will be run at last when Kopia finishes all snapshots related operations and will be run only once. It can provide overall info on the operation like if any snapshot is created or not, etc.
It can also be helpful if a user wants to run a script only once which I think is not possible if running `kopia snap create --all`.

**Comment by sm1999** [comment]
> Perhaps we can make that toggleable (or have two distinct sets of actions), so that  you can decide directly with the command line whether your action should run after  ignored snapshots. Would that fulfill your use case?

Yup, two distinct sets of action will be great. Distinct actions will provide more control and flexibility.

Also what about a new action that will run at last when kopia finishes all operations?
