### ISSUE TITLE
Aborting maintenance in `policy set` makes it not be run again next time

### ISSUE THREAD

**Issue by nh2** [kopia/kopia#2395]
I just ran `kopia policy set` to change `--max-parallel-file-reads` and it started outputting

```
Running full maintenance...
Looking for active contents...
```

I Ctrl+C'd and restarted it immediately because I noticed I had passed the number on the command line, and noticed that the maintenance would not be run in the restarted command even though I aborted the last run.

Just reporting this to check if that is intended.

**Comment by nh2** [comment]
I find it quite frustrating for a bot to auto-close the issue without any apparent human view or feedback.

**Comment by julio-lopez** [comment]
@nh2 Thanks for filing the issue. That's the current (somewhat intended) behavior in kopia. It can be improved. Filed #3174 to follow up.
