### ISSUE TITLE
How to change Kopia UI language?

### ISSUE THREAD

**Issue by aborsik** [kopia/kopia#2401]
I did not find out how to change Kopia UI language. I can see that there are language packs included but I could not find the way how to switch/set the language. Is this possible or it's based on locale on the system? Thank you.

**Comment by life-on-mars** [comment]
@aborsik Have you found a solution to this? At least on Windows it's certainly not following the system language. KopiaUI doesn't seem to have CLI arguments either. At least --help does nothing. There is a config file in %APPDATA% but it doesn't contain language settings.

**Comment by yfdyh000** [comment]
KopiaUI\locales\*.pak derived from Electron. I didn't see the program support interface multilingual.

**Comment by aborsik** [comment]
@julio-lopez no, I could not see any option how to switch the language.

**Comment by pgy866** [comment]
Do you not support multiple languages? Are there plans to support multiple languages

**Comment by jkowalski** [comment]
Not currently but that would be something we can try doing if there’s interest

**Comment by pgy866** [comment]
The multilingual feature helps people in more countries to use it and avoid misoperation

**Comment by jkowalski** [comment]
PRs are always welcome although this would be a huge change. We should do it but managing translations might become challenging.

**Comment by githubmyname** [comment]
No one is interested in multilingualism?

**Comment by cr4zyduck** [comment]
Hi, I just downloaded latest version and seems that isn't multilanguage. I think that languages help projects to be used for more people, and I think one way will be to open translations to contributors and let users to translate. In my case, for Catalan language there's another option that would be to contact 2 communities that often translate projects: [www.softcatala.org](https://www.softcatala.org/) and [www.plataformaperlallengua.cat](https://www.plataforma-llengua.cat/).

**Comment by iouston** [comment]
Hi,
I want translate Kopia UI in french. Is the translation in Kopia UI added on the roadmap ?

**Comment by kirillz** [comment]
Hello, this is probably the only program in 2026 that doesn't support my language, and which I use frequently. I think this thread provides enough reasons to change the "not planned" tag to "bug" :) Thank you.
