### ISSUE TITLE
Can someone tell me what the process is for reinstalling kopia?

### ISSUE THREAD

**Issue by danmed** [kopia/kopia#2408]
I'm looking at Kopia as a replacement for Duplicacy..

I'm running it on windows with the UI.

Lets say i have to completely rebuild my Windows host and reinstall kopiaui... 

How do i get to the point of resuming my backups from where they were when my windows host when wonky?

Are there files somewhere on my windows host i should be backing up by another method that i can simply restore after reinstall?

**Comment by xxxliqu1dxxx** [comment]
Hi welcome to this project. Per the other reply, you can use the forum https://kopia.discourse.group/ to ask questions to get more general information. There's already lots of stuff documented, so I am sure you will find the information you are looking for there.

To answer your question, kopia works with a user and a computer name... for instance, the computer i am on is called "computername" and my user is "myusername". When connected to the repo, it will connect as "myusername"@"computername". If your new Windows system has the same computername & you connect with the same user, then the policy will apply "as is". Any rules you had for your C:\ will then apply as you reconnect to the repo. Schedules, exceptions, etc. everything will continue as normal.

You will also be able to restore from prior snapshots as well as they would just show up with your normal history. That being said, if you do change the user or change the computer name, then you may have to select the dropdown to restore from other computers. The beauty of Kopia is the ability to have multiple clients for the single repo. 

I would encourage you review the forum @ https://kopia.discourse.group/ for more information.
