### ISSUE TITLE
[Feature Request] sync-to in WebUI

### ISSUE THREAD

**Issue by sho-87** [kopia/kopia#2412]
Are there any plans to update the WebUI with a few more features? Specifically, it would be nice to get access to `sync-to` (with associated cron job) so it doesn't need to be done with CLI.

Currently, this is problematic for docker users as we have no access to a CLI in the `latest` image, so many features are unusable (unless I'm trying to access it incorrectly?)

![image](https://user-images.githubusercontent.com/5199715/190324521-24ac0a7c-1a33-47d5-b75e-21b4e63a0b12.png)

**Comment by adowair** [comment]
I'm not aware of any plans, but this would be a great addition–I don't see a reason to hide this from the UI. What do you propose the UI could look like? New page, new radial button, etc. Do you wanna give it a shot designing/building this one? PRs are welcome, and I'd be very happy to help.

**Comment by basldfalksjdf** [comment]
> I'm not aware of any plans, but this would be a great addition–I don't see a reason to hide this from the UI. What do you propose the UI could look like? New page, new radial button, etc. Do you wanna give it a shot designing/building this one? PRs are welcome, and I'd be very happy to help.

I believe `sync-to` works at the repo level and not the policy level, correct? If so, could there be an option the UI on the `Repository` page that gives users the option to enable `sync-to`, enter the details for the target destination, pick an interval at which `sync-to` should occur, and pick whatever options that are available for `sync-to` (like the `--delete` flag)?

**Comment by MattFromGer** [comment]
I want to give this feature a try. However there are some uncertainties for me:
1. Are the sync-to locations persisted somewhere in the config? So I can build a status page with all my locations and if they're successfully in sync.
2. The sync-to feature is triggered manually for now? The docs says `Kopia v0.6.0 adds support for automatic repository replication`. I haven't found a way to _automatically_ trigger the sync.

**Comment by AD-Wright** [comment]
Are the sync-to locations just regular repositories?  And do they need to be initialized first?  
`repository sync-to from-config` (https://kopia.io/docs/reference/command-line/common/repository-sync-to-from-config/) seems to indicate that a config file could be used.  But not much about it.

**Comment by adowair** [comment]
Yes, if I recall correctly, sync-to destinations are just repositories, and they must first be initialized (otherwise, how could a connection exist? 😄)

**Comment by frederikhors** [comment]
This should be reopened.
