### ISSUE TITLE
The difference between using sftp via `ssh -s sftp` and `sftp`

### ISSUE THREAD

**Issue by samip5** [kopia/kopia#2413]
I'm quite unable to wrap my head around why is kopia using it via `ssh -s sftp` rather than sftp directly?

On one host, the first approach for some reason hangs, but the 2nd works fine?

**Comment by ingul-buz** [comment]
I was tearing my hair out with this exact problem. The sftp host hung just after ssh login, i.e. the sftp subsystem connection failed. It seems `ssh -s sftp` is the default way for Kopia to connect to an sftp server. At this point I have to ask like the OP: if an sftp connection is what we are aiming at, why not just use sftp?

Just for the heck of it, I finally gave Kopia the connection parameter `--ssh-command="sftp"`. As far as I can see, it's not documented anywhere, but lo and behold, I was able to make the connection work that way. If this is how Kopia is actually making a plain sftp connection, I have to say the way to achieve it is not very intuitive. Well, at least it seems to work, but it still feels a bit dubious.

**Comment by ingul-buz** [comment]
It appears I have misundersood a few things:

1. The `--ssh-command` option is probably only useful if you also use an `--external` ssh client.

2. `ssh -s sftp` is a common way to open a binary sftp connection to the host. Even a plain sftp client connects the same way, but then the connection is text based. Both work as a subsystem to ssh.

It became obvious that my problem with the host was only temporary and became solved just about the time I thought I had found a new funny way to connect (`--ssh-command="sftp"`), which probably was just ignored.

**Comment by ntolia** [comment]
I'm closing this one out as this was reported on Slack as having been addressed. Please feel free to ping me or reopen if there is still an open question.

**Comment by samip5** [comment]
> I'm closing this one out as this was reported on Slack as having been addressed. Please feel free to ping me or reopen if there is still an open question.

Could you please provide the tl;dr of that to us not on Slack?

**Comment by ntolia** [comment]
@samip5 @lupusA can confirm as he has been tracking down issues that should be closed but I believe he was referring to the comment right above mine.
