### ISSUE TITLE
Suddently cannot connect to my repository; a problem with 'cancel connection'; 'unconnected' repository shows even after recreating the repository; backups did not run for a week

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kopia/kopia#2419]
I have been using - and appreciating! - Kopia for a while (on Windows 10; Kopia version 0.11.3; using B2). 

Today when I tried to open the main Kopia window the program told me, persistently, that it is 'initializing' and I see this in the log:

> unable to open repository: get password: password prompt error: The handle is invalid.

My Internet connection is working and I have not (to my knowledge) recently messed with my cloud storage setup. Call this problem '(1)'.

In an attempt to fix things, I chose Kopia's 'cancel connection' option - which did not cancel my current attempt to connect to my repository (which is what I expected) but instead delete the repository information from Kopia. So here we have problem (2): Some sort of warning should be given, surely, before the program does that.

(3) After re-creating the repository, within Kopia, I managed to connect to it. Everything worked, except that I see this within my tray menu:

![image](https://user-images.githubusercontent.com/47056543/190913128-6710a81e-2a19-4824-a598-236cdb2477ab.png)

Should the 'unconnected' element not have disappeared from the menu?

Finally: (4) it seems that my backups did not run - they failed to run - for a week; and I received no notification of this. Should I have used Kopia to set up some sort of notification? Surely the default should be some sort of message.

**Comment by LinuxOnTheDesktop** [comment]
I would welcome. for one thing, advice on how to remove that '<not connected>' entry in the tray menu. (Clicking it yields a window that contains a 'cancel' button, but clicking that button does not remove the menu entry.)

**Comment by LinuxOnTheDesktop** [comment]
Bump.

**Comment by lupusA** [comment]
Hi @LinuxOnTheDesktop, 

regarding point 3 - this a consequence of the current design. There is one primary repository which cannot be deleted once disconnected. It shows up at the top. If you connect to another repository (B2) and disconnect the primary repository it stays within the list. The code does not allow to delete the primary (eg. the first) repository. 

What you can do is, to disconnect from B2 and then use the primary repository to connect to B2 again. Then it will only show one entry. 


Cheers,

**Comment by lupusA** [comment]
Hi @LinuxOnTheDesktop, 

please do the following:

1. Disconnect from B2 repository and close the window. 
2. Open Kopia from the system tray and check if only one repository is shown within the list.
3. If so, click on "not connected" and reconnect within the newly openend window to your B2 repository. 

That you do the trick. See my video in #2649. 

Cheers,

**Comment by LinuxOnTheDesktop** [comment]
Thanks. Re 2: _two_ repositories show after disconnecting the B2 repository:

![image](https://github.com/kopia/kopia/assets/47056543/4761a8ce-122d-4287-827a-dc368172a023)

**Comment by lupusA** [comment]
When you click on "not connected" then the repository selection should pop up. If you close it with "x" it should delete the config files and remove the entry in the list. Can you check?

Cheers,

**Comment by lupusA** [comment]
Hi @LinuxOnTheDesktop, 

there are always things to improve especially when it comes to software :-)

I am closing this issue as it has been solved for now. I am keeping #2649 open for tracking the issue with the primary repository. 

Cheers,
