### ISSUE TITLE
Restoring files: changing the main part of a file name creates the file without an extension

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kopia/kopia#2420]
Kopia version 0.11.3
Windows 10
B2

I find that when I restore a file - I used a file with a pptx (PowerPoint) suffic - the file restores alright, _unless_ I alter the main part of the filename. If I do alter the main part of the name, then the file gets created with no extension. Thus, if one has 'somePowerPointFile.pptx' and does this

![image](https://user-images.githubusercontent.com/47056543/190913455-8301505f-0404-48a3-aa89-5e8460c3b25f.png)

then the file that gets created is

`somePowerPointFile_OLD`, _sic_, i.e. without any file extension.

I presume that this is not intended behaviour. If it _is_, then I find that intended behaviour questionable!

**Comment by basldfalksjdf** [comment]
This sounds like intended behavior. If you create a file without an extension in the name... it won't have an extension.

**Comment by LinuxOnTheDesktop** [comment]
@basldfalksjdf 

The 'save as type' bar does not in fact offer any files types. So, it is not as if one is being encouraged to chose a (new) file type. Rather, one presumes this: the old extension (the one possessed by the existing, backed-up file), which will be used if one in no way specifies a new name, will be used, also, if one changes the main part of the file name.  And yet . . it is not used in that way.

**Comment by adowair** [comment]
In the `file name:` field, before you edit it to be `somePowerPointFile_OLD`, what is displayed? Is the extension visible as part of the "default name"?

**Comment by LinuxOnTheDesktop** [comment]
@adowair 

Here is a screenshot of the filename field, when I am in the process of restoring a PowerPoint file, and before I have altered the contents of the filename field. As the screenshot shows, no extension is visible as part of the default name.

![image](https://user-images.githubusercontent.com/47056543/191089699-2d6e2dbd-402b-49f9-a40c-ced97e9d597b.png)

**Comment by adowair** [comment]
Right, thanks for checking @LinuxOnTheDesktop, it does sound like something's not right. Perhaps `Save as type:` should be made functional, or removed entirely, letting the user specify the full file name + file type. Do people have a preference either way?

**Comment by LinuxOnTheDesktop** [comment]
I do not think I have a preference between (1) making the **Save as type** field work properly and (2) removing that field in favour of all work being done by the **File name** field.

Still: if the **type** row _is_ retained, then the following ought to be the case. The content of that row should default to the file-type of the source file, and that file-type ought to be reflected in the text shown in the **name** field.

**Comment by basldfalksjdf** [comment]
> @adowair
> 
> Here is a screenshot of the filename field, when I am in the process of restoring a PowerPoint file, and before I have altered the contents of the filename field. As the screenshot shows, no extension is visible as part of the default name.
> 
> ![image](https://user-images.githubusercontent.com/47056543/191089699-2d6e2dbd-402b-49f9-a40c-ced97e9d597b.png)

I'm confused. In your original post you reported that...

> I find that when I restore a file - I used a file with a pptx (PowerPoint) suffic - the file restores alright, unless I alter the main part of the filename.

But now you are saying it does not have the file extension even before you edit the file name?

For what it is worth, I am also on Windows 10 with KopiaUI 0.11.3. When I go to restore a file, the file name and extension are displayed in the save dialog by default. I can then change the file name and extension as I see fit. If I don't put an extension there, then the file is not saved with any extension.

**Comment by LinuxOnTheDesktop** [comment]
_When I restore a file without altering the filename, the file does indeed restore with its original extension; and yet, the filename field, within the save dialogue, shows no extension for the file._ Consider my PowerPoint file that is called 'Experiments' and the full name (leafname) of which is 'Experiments.pptx'. When I go to restore that file (from within Kopia) I see a dialogue box that shows no file extension (unless one counts the text that says, 'All files (*.*)'). Yet, if I do not alter the filename in any way, then the file restores with its original filename. On the other hand, if I change 'Experiments' to 'OLD_Experiments', then the file gets restored without a file extension.

> When I go to restore a file, the file name and extension are displayed in the save dialog by default. I can then change the file name and extension as I see fit. If I don't put an extension there, then the file is not saved with any extension.

It seems that your experience differs from mine in at least one way. To wit: (1) you, but not I, see an extension, by default, in the save dialogue. I wonder also whether (2) you (but not I) get a file saved with its proper extension if (when restoring) you alter the non-extension part of the file's name.

**Comment by LinuxOnTheDesktop** [comment]
Bump. Fixing problems makes applications better!

**Comment by lupusA** [comment]
Hi @LinuxOnTheDesktop, 

i was not able to reproduce this with KopiaUI version 0.13 and windows 11. When restoring a file within a folder, Windows presents a file dialog with the correct extension:

<img width="796" alt="image" src="https://github.com/kopia/kopia/assets/37236531/dd5579fc-d6ee-4386-9c62-4e2b20140011">

Would you mind and provide a screencast or short video for your issue?

Cheers,

**Comment by LinuxOnTheDesktop** [comment]
I can no longer reproduce the problem!

**Comment by lupusA** [comment]
Hi @LinuxOnTheDesktop, 

with regards to your latest post, I am closing this issue. 

Cheers,
