### ISSUE TITLE
Declarative configuration

### ISSUE THREAD

**Issue by tecosaur** [kopia/kopia#2432]
Hello,

I'm trying to write a NixOS service for Kopia, and hoping I could get some advice here on it. At the moment, I'm thinking of storing the quick connect token with the password, and then having separate parameters for other connection options. Then the "activation script" (runs once on enabling) can execute these steps:
1. run `kopia repository disconnect` (clean up any prior state)
2. create config file at `SOME_PATH` with connection options
3. run `kopia repository connect --config-file=$SOME_PATH from-config --token-file=/run/secrets/kopia-token`

I haven't tried this, but from the docs this looks like it could work. For actually performing backups, some systemd services and timers with `kopia snapshot --config-file=$SOME_PATH` seem like all that's required.

One thing I haven't got any idea about is the policy. I see that you can get the current policy as JSON with `kopia policy show --json`, but I don't see any easy way to import a policy/set it declaratively? Advice here would be appreciated.

**Comment by tribor** [comment]
I'm missing something like `kopia policy set 'user@host:path' --from-file filename` to import a policy (as json) config. My goal is to setup repo+policy fully programmatically

**Comment by tecosaur** [comment]
It's been half a year now since this was raised, it would be great if we could hear from somebody involved in the Kopia project.

**Comment by ppenguin** [comment]
I've been working on some additions for `kopia` lately, and I'd estimate that (given we already have `kopia policy [show|edit|set]`) this should be near trivial to implement. If you know some `go` it should be easy. I'm short on time now but I might take a crack at it in the not too distant future if nobody has solved it by then... 

Since basically `nix` machinery makes it trivial to go from `json` like defs (or module options) to `nix` variables, you could also in the meantime just use `kopia policy set <--flags ....>`?

**Comment by blenderfreaky** [comment]
I'd like to implement this, however I'm not 100% sure on the exact command to define;

`kopia policy show --json` shows the effective policy, not the defined one, whereas setting it would take the defined policy, which is a subset thereof.

To have parity, I think there should be something like `kopia policy show --json --defined-only`, however then it might be best to have something like `kopia policy file export` and `kopia policy file import`?

Before any kind of PR, you might be able to also abuse the ability to set `EDITOR` variable and use `kopia policy edit`

**Comment by jkowalski** [comment]
Import and export sound like a great idea. As for the syntax, how about:

```
$ kopia policy export --all --output-file=policies.json
$ kopia policy export --global --output-file=policies.json
$ kopia policy export --source=foo@bar --output-file=policies.json
(or something like that)

$ kopia policy import --input-file=policies.json
```

As for the output, we can probably do a JSON array:

```json
[
    {"target":"global", "policy":{"retention":{"keepLatest":10,"keepHourly":48,"keepDaily":7,"keepWeekly":4,"keepMonthly":24,"keepAnnual":3,"ignoreIdenticalSnapshots":false},"files":{"ignore":[".cache",".cache,cache","System Volume Information","cache","node_modules"],"noParentIgnore":true,"ignoreDotFiles":[".kopiaignore"],"oneFileSystem":true},"errorHandling":{"ignoreFileErrors":true,"ignoreDirectoryErrors":true,"ignoreUnknownTypes":true},"scheduling":{"runMissed":true},"compression":{"compressorName":"none","neverCompress":["zip"]},"splitter":{},"actions":{},"osSnapshots":{"volumeShadowCopy":{"enable":0}},"logging":{"directories":{"snapshotted":5,"ignored":5},"entries":{"snapshotted":0,"ignored":5,"cacheHit":0,"cacheMiss":0}},"upload":{"maxParallelSnapshots":3,"parallelUploadAboveSize":2147483648}}},
    {"target":"foo@bar:/somepath", "policy":{"retention":{"keepLatest":10,"keepHourly":48,"keepDaily":7,"keepWeekly":4,"keepMonthly":24,"keepAnnual":3,"ignoreIdenticalSnapshots":false},"files":{"ignore":[".cache",".cache,cache","System Volume Information","cache","node_modules"],"noParentIgnore":true,"ignoreDotFiles":[".kopiaignore"],"oneFileSystem":true},"errorHandling":{"ignoreFileErrors":true,"ignoreDirectoryErrors":true,"ignoreUnknownTypes":true},"scheduling":{"runMissed":true},"compression":{"compressorName":"none","neverCompress":["zip"]},"splitter":{},"actions":{},"osSnapshots":{"volumeShadowCopy":{"enable":0}},"logging":{"directories":{"snapshotted":5,"ignored":5},"entries":{"snapshotted":0,"ignored":5,"cacheHit":0,"cacheMiss":0}},"upload":{"maxParallelSnapshots":3,"parallelUploadAboveSize":2147483648}}}
]
```

OR JSON object

```json
{
    "global": {"retention":{"keepLatest":10,"keepHourly":48,"keepDaily":7,"keepWeekly":4,"keepMonthly":24,"keepAnnual":3,"ignoreIdenticalSnapshots":false},"files":{"ignore":[".cache",".cache,cache","System Volume Information","cache","node_modules"],"noParentIgnore":true,"ignoreDotFiles":[".kopiaignore"],"oneFileSystem":true},"errorHandling":{"ignoreFileErrors":true,"ignoreDirectoryErrors":true,"ignoreUnknownTypes":true},"scheduling":{"runMissed":true},"compression":{"compressorName":"none","neverCompress":["zip"]},"splitter":{},"actions":{},"osSnapshots":{"volumeShadowCopy":{"enable":0}},"logging":{"directories":{"snapshotted":5,"ignored":5},"entries":{"snapshotted":0,"ignored":5,"cacheHit":0,"cacheMiss":0}},"upload":{"maxParallelSnapshots":3,"parallelUploadAboveSize":2147483648}}},
    "foo@bar:/somepath":{"retention":{"keepLatest":10,"keepHourly":48,"keepDaily":7,"keepWeekly":4,"keepMonthly":24,"keepAnnual":3,"ignoreIdenticalSnapshots":false},"files":{"ignore":[".cache",".cache,cache","System Volume Information","cache","node_modules"],"noParentIgnore":true,"ignoreDotFiles":[".kopiaignore"],"oneFileSystem":true},"errorHandling":{"ignoreFileErrors":true,"ignoreDirectoryErrors":true,"ignoreUnknownTypes":true},"scheduling":{"runMissed":true},"compression":{"compressorName":"none","neverCompress":["zip"]},"splitter":{},"actions":{},"osSnapshots":{"volumeShadowCopy":{"enable":0}},"logging":{"directories":{"snapshotted":5,"ignored":5},"entries":{"snapshotted":0,"ignored":5,"cacheHit":0,"cacheMiss":0}},"upload":{"maxParallelSnapshots":3,"parallelUploadAboveSize":2147483648}}
}
```
