### ISSUE TITLE
kopia server web ui cannot be accessed in the LAN

### ISSUE THREAD

**Issue by billydu1980** [kopia/kopia#2433]
Dear all:

kopia server web ui（ http://127.0.0.1:51515 ）can only be accessed locally, but not in the LAN（ http://ip:51515 ）。 
Firewall is closed

Thanks for reply.
Billy

**Comment by jkowalski** [comment]
You need to use `--address 0.0.0.0:51515` to listen on all IPs or specify `--address x.y.x.y` to listen on one IP.
