### ISSUE TITLE
snapshot create the LAN server files

### ISSUE THREAD

**Issue by billydu1980** [kopia/kopia#2441]
Dear all:

Can we back up the specified files and directories of other servers in the LAN ? 

For example:  kopia snapshot create root@172.16.66.33:/data/ , which kopia localhost ip is 172.16.88.30.

Or is there any other way ?

Billy

**Comment by billydu1980** [comment]
Can I create snapshots only for local server files or directories？
Which expert can help reply。

Thanks
Billy

**Comment by dimejo** [comment]
I think you are talking about pull-based backups. AFAICT this is currently unsupported. Take a look at #1636 for more answers on this topic.
