### ISSUE TITLE
Status of 0.12.0 RC1

### ISSUE THREAD

**Issue by SMillerDev** [kopia/kopia#2442]
https://github.com/kopia/kopia/releases/tag/v0.12.0-rc1 suggests that this is the latest release, but the RC in the name would suggest this isn't a stable release. Is this version recommended for production use?

**Comment by SMillerDev** [comment]
Would you mind marking it as a pre-release in the GitHub releases then?

**Comment by francoisprunier** [comment]
@basldfalksjdf I received an update notification for that version on my machine. Seems odd to me to offer an RC to replace the currently stable version, looks like a misconfiguration to me ?

**Comment by xxxliqu1dxxx** [comment]
I am also surprised this showed up in Windows KopiaUI as an update...

**Comment by jkowalski** [comment]
Yeah, this was somewhat unfortunate and we did not intend to push homebrew and others which track stable releases. The code in 0.12.0-rc1 will be the same as final, which I'm going to cut shortly after final icon design is merged.

**Comment by jkowalski** [comment]
I pushed https://github.com/kopia/kopia/releases/tag/v0.12.0, sorry about the confusion.
