### ISSUE TITLE
There seems to be no option to disable the 'Kopia is running in the background' notification

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kopia/kopia#2479]
I see that notification every reboot. I should like not to see it.

EDIT: Windows allows one to silence all notifications for any particular program - but I _do_ want to receive any _import_ Kopia notifications (!).

Windows 10 Pro - 21H2 (2009: 19044)
Kopia 0.12.0-rc1

**Comment by LinuxOnTheDesktop** [comment]
The mere passage of time does not magically fix problems.

**Comment by lupusA** [comment]
Hi @LinuxOnTheDesktop, 

is this still an issue? I am not able to reproduce this with Kopia version 0.13. 

Cheers,
