### ISSUE TITLE
repository repair b2 - documentation: wrong date shown

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kopia/kopia#2480]
[This item of documentation](https://kopia.io/docs/reference/command-line/common/repository-repair-b2/) (and some other such items?) shows this (quasi-) date:

`Last modified January 1, 0001`

**Comment by LinuxOnTheDesktop** [comment]
The mere passage of time does not magically fix problems. So, I am trying (will commenting suffice? I do not know how to remove the 'stale' label) to re-open.

**Comment by lupusA** [comment]
Hi @LinuxOnTheDesktop, 

i've checked all sites from the documentation. The issue is not present anymore. It was probably solved when the layout of the site was changed. 

I am closing this issue as completed. 

Cheers,
