### ISSUE TITLE
Getting Started Guide

### ISSUE THREAD

**Issue by limopc** [kopia/kopia#2481]
Hi,
First of all allow me to express my appreciation to the wonderful Kopia. Great work.

I am on EndeavourOS (EOS) which is Arch based.
Previously on EOS, KDE Plasma I installed Kopia and have my snapshots to an external USB drive (BTRFS)

Now I got a new laptop and trying to restore my data from the USB drive.

I have:
```
[limo@asus USB_Backup]$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda           8:0    0 465.8G  0 disk 
└─sda1        8:1    0 465.8G  0 part /run/media/limo/USB_Backup
nvme0n1     259:0    0 238.5G  0 disk 
├─nvme0n1p1 259:1    0   300M  0 part /boot/efi
└─nvme0n1p2 259:2    0 238.2G  0 part /var/cache
                                      /var/log
                                      /home
                                      /
```
When I try
```
[limo@asus USB_Backup]$ kopia restore /run/media/limo/USB_Backup/Kopia/ /home
Restoring to local filesystem (/home) with parallelism=8...
ERROR unable to get filesystem entry: entry not found "run": parent is not a directory
[limo@asus USB_Backup]$ 
```
I have installed kopia and kopia-ui-bin and created a repository.

What can I do to restore my data which is under the folder /Kopia? (USB_Backup is the name of the drive)

I will appreciate your help.
Thank you.

**Comment by adowair** [comment]
Have you tried connecting to the repository on your USB drive?
```shell
kopia repository connect filesystem --path=/run/media/limo/USB_Backup
```

Generally, Kopia relies on a "connection" (rather than what path you execute the command in) to know where to find snapshots.

**Comment by limopc** [comment]
Thanks a lot @adowair 

I will test it by running
`kopia repository connect filesystem --path=/run/media/limo/USB_Backup/Kopia/`
from Bash as /Kopia is the folder where I am saving sanpshots not to the root.

**Comment by adowair** [comment]
I'm not 100% sure on this, but the Kopia CLI and the Kopia UI may use different "connections", so I'd stick to using one or the other. Once you're properly connected to the repo, you should be able to see and restore your snapshots. Otherwise there's something else going on 🤔 

As an aside: the folks here have written a great [Getting Started Guide](https://kopia.io/docs/getting-started/) that'll come on handy here

**Comment by limopc** [comment]
`you should be able to see and restore your snapshots`

This is the main point for me using Kopia.
I have my backup and snapshots on an external USB drive.
In case I make a fresh install or get a new laptop I want to see my previous snapshots.

OK. Should I point the repository to the folder I am storing sanapshots (/USB_Backup/Kopia/)? or to the parent (/USB_Backup/)?

Sorry to bother you but this is vital and I want to stay with Kopia as you are doing a great job really.

**Comment by bbccdd** [comment]
No need to change ownership, you can log on as any user if you have the password. Please search the docks for how to do this exactly.

**Comment by ntolia** [comment]
This was reported as answered on Kopia Slack. I am closing this out but please feel free to reopen if needed.
