### ISSUE TITLE
A 'request failed' message that should supply more information

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kopia/kopia#2482]
Just now when I booted my computer, Kopia showed me this:

![image](https://user-images.githubusercontent.com/47056543/193635269-824bd43c-514e-4d99-ad60-e5b68199380b.png)

I think that the problem was that my network was down. Two things make me think that. First, the network _was_ down. Second: as I rebooted the computer I saw, for a moment, another Kopia window - which I think previously was occluded by some other window. That other Kopia window said something like, 'Connecting to repository . . '. I suppose that, taken together, those two messages do convey that Kopia failed to connect to a repository. However, one should not have to piece together that information. So the following suggests itself.

It would be good were the 'request failed' message to explain itself. Or, at the least: if one needs to see another window in order to understand the first message, then Kopia should ensure that both messages are visible simultaneously.

**Comment by xxxliqu1dxxx** [comment]
It's probably the same false positive I am seeing. That's been consistenly showing for me every reboot since 11.3. Closing the window (not fully quitting KopiaUI) and re-opening the window by double clicking tray icon makes it work. There must be some type of race condition that makes this 401 show up, but closing the window ad make it show again works beautifully.

**Comment by LinuxOnTheDesktop** [comment]
As I mean to have said: I think there _was_ a problem - my network was down. My complaint is that _the error message does not explain itself_.

(Admittedly, though: every reboot I too do see something I should not, namely, a window that is about connecting a repository. That window seems to show because of the persistence of a kind of phantom repository on my system - a repository that was not working and which, try as I might, I cannot manage to fully delete. See #2452. See also #2479, which is about a Windows notification that I see every boot and do not want to see every boot.)

**Comment by LinuxOnTheDesktop** [comment]
The mere passage of time does not magically turn an unhelpful error message into a helpful error message. So: re-opening.
