### ISSUE TITLE
Number of files

### ISSUE THREAD

**Issue by ClementNerma** [kopia/kopia#2509]
Hi there!

I've been using Kopia for a few months now and I've really been enjoying it - it's fast, reliable, and easy to use.

I have one question though about the number of files in the repository. Basically, Borg backup for instance will create a few dozen files per repository even with thousands of source files. Kopia creates a lot more (currently 1700+ files in my repository and 6000+ directories!)

This is a problem for me when backuping as it takes time to compare them given there is a LOT of items, especially the directories count.

Would there be a way to reduce the number of, at least, directories created? This would be really helpful to improve synchronization speeds.

This is a very low-priority task and I don't know if this would even be doable without huge changes to the codebase, in which case it would not be worth the effort, but I'm mostly asking just in case there would be a setting or configuration option I missed :)

Thanks in advance for your help!

**Comment by dimejo** [comment]
Kopia creates a lot of directories to improve performance of large repositories. This is called sharding and pretty well [explained in the docs](https://kopia.io/docs/advanced/sharding/).

On which hardware are your backups running? Scanning 6000+ directories shouldn't take too long even on spinnning disks.

**Comment by ClementNerma** [comment]
Checking the files on the source (HDD) is fast, but checking it on the remote (SFTP) is far slower.

Can I try disabling sharding on an existing repository?

**Comment by julio-lopez** [comment]
If you disable sharding, each of the directories becomes very large. Listing large directories often causes performance problems in various systems.
It is possible to modify the sharding scheme. Please take a look at https://kopia.io/docs/advanced/sharding/

**Comment by ClementNerma** [comment]
Actually I ended up recreating the repository a few months ago and the number of files drastically decreased. Maybe there was some optimizations done in Kopia in the meantime but now I have far less files even though the backed up folder still contains as much items.

**Comment by julio-lopez** [comment]
Good to know. Thanks for the info.
