### ISSUE TITLE
Unable to unmount snapshot if disconnect directly from file explorer

### ISSUE THREAD

**Issue by refugeindhamma** [kopia/kopia#2519]
Hi, I am unable to unmount a snapshot if I disconnect directly from the file explorer. Even after deleting the snapshot and making a new snapshot with the same folder, it is still unable to unmount. It gives the error:

```
ERROR: Request failed with status code 500

Version v0.12.1 5227d74996b6520f9f96e4203cfe00b832a60d5f kopia/htmlui 5cbe5f7147f27729adce475f2774926933ede250 built on Wed Sep 28 04:26:24 UTC 2022 fv-az39-946
```

I am able to mount other snapshots and even folders within the unmount-able snapshot, then if I unmount from Kopia UI, it works fine.

_Edit to make the code work right._

**Comment by kapitainsky** [comment]
still the same is 13RC2
