### ISSUE TITLE
how to decrease the performance impact for kopia

### ISSUE THREAD

**Issue by milano127** [kopia/kopia#2525]
when I use kopia in AWS, the host is with 8 vcpu and 64G, when we use kopia to backup the data, the backup speed is about 1.3G/s, the cpu usage is high, and reach about 97%, so the storage performance is very bad, is there any way to decrease the performance impact? is there any way to limit the backup speed?
since the host is the NFS stroage server, we just use backup in the NFS server, if we did the kopia backup in the NFS client, will the impact to storage server lowwer?
we use the default compression

update
_________________
e use zfs as our filesystem, after we stop the kopia backup, the cpu% is still very high, as we check , it is due to arc_prune high,  
so we want to know why kopia will increase the zfs arc_prune, it never happened before

**Comment by dimejo** [comment]
> when I use kopia in AWS, the host is with 8 vcpu and 64G, when we use kopia to backup the data, the backup speed is about 1.3G/s, the cpu usage is high, and reach about 97%, so the storage performance is very bad, is there any way to decrease the performance impact? is there any way to limit the backup speed?

You can use `kopia repository throttle set` to limit the upload speed of Kopia. Using system tools like `nice` and `ionice` should help aswell.

> e use zfs as our filesystem, after we stop the kopia backup, the cpu% is still very high, as we check , it is due to arc_prune high,
> so we want to know why kopia will increase the zfs arc_prune, it never happened before

https://github.com/openzfs/zfs/issues/9966 sounds like NFS and ZFS don't interplay nicely.
