### ISSUE TITLE
Resume restore (with KopiaUI)

### ISSUE THREAD

**Issue by VsevolodGolovanov** [kopia/kopia#2533]
I'm using KopiaUI v0.12.1 on Windows 11. The repository is Hetzner Storage Box via SFTP. Snapshotting seems to work very well, but I'm a bit confused about if it is possible and how to resume restoring.

I've interrupted a 200 GB restore process by closing KopiaUI. It was about 90% done, it ran for about 14 hours.
Problem 1. Upon restarting KopiaUI it did not resume restoring. I guess it doesn't have task persistence? Understandable for a CLI tool, but more surprising for a GUI tool. I get that as task persistence this goes beyond just restoring, and is it's own whole big thing, and KopiaUI is very likely working as intended currently, but still as a GUI user I wish it had that. As well as a Pause button.

So I attempted to start a new restore task from the same snapshot as before to the same directory. The checked by default "Skip previously restored files and symlinks" option assured me that resuming like that should be possible.
Problem 2. This unexpectedly failed due to the target directory already existing:
![image](https://user-images.githubusercontent.com/8070317/199016862-9b308491-44d7-4b12-8bc3-9474d47b24af.png)

I tried to start a new restore task again, this time I checked the "Continue on Errors" option.
Problem 3. This just instantly "succeeded" without doing anything.
![image](https://user-images.githubusercontent.com/8070317/199018312-4c33ccd1-a8a5-4ee5-b272-585a029742cd.png)

Perhaps I'm doing something wrong? Or is resuming restore is just not possible currently? Or is it bugged?

**Comment by VsevolodGolovanov** [comment]
Surely Problem 2 is a straight up bug? Otherwise I'm not sure what the "Skip previously restored files and symlinks" option is supposed to be.

**Comment by 9-2-1** [comment]
You can enable both skip and overwrite mode, and it will skip all restored files and overwrite all **partically restored** files. 
![图片](https://github.com/kopia/kopia/assets/33796749/66dce78d-6f96-4243-a48a-44c5bb6b59fb)
