### ISSUE TITLE
Can't mount snapshot in docker container on unRAID

### ISSUE THREAD

**Issue by rslite** [kopia/kopia#2534]
I have an unRAID server that I use for local backup and have installed Kopia on it through a docker container. I have created a test snapshot and when trying to mount it I get the following error:

```
/usr/bin/fusermount3: fuse device not found, try 'modprobe fuse' first
ERROR mount error: mounting error: fusermount exited with code 256
```
I tried `modprobe fuse`, but it can't find modprobe.

I tried from both CLI and UI. The UI just hangs and then I find the same error in the logs.

Is this an issue with the container or am I missing something? I'm pretty new at playing with docker containers.
Thank you!

**Comment by ercoppa** [comment]
Run it as priviliged.

**Comment by rslite** [comment]
Thank you! That worked!

**Comment by woiwoiwoiwoi** [comment]
I had the same issue and this solved it for me, so thank you @ercoppa . However, I would prefer not to run Kopia in a privileged container. Is it also possible to grant finer grained permissions in some way, maybe via `security_opt:`?

Also, I wonder if using the privileged flag is intended. It is not in the official Kopia docker documentation after all. Is it a bug? Or does it maybe have to do with Unraid (OP's case) or QNAP (in my case)?
