### ISSUE TITLE
`end_to_end_test` failed with OOM errors on 32-bit architectures (AlpineLinux)

### ISSUE THREAD

**Issue by FollieHiyuki** [kopia/kopia#2550]
Hi! I'm updating `kopia` for AlpineLinux to 0.12.1. The integration tests currently is failing CI pipeline for 32-bit architectures with out of memory errors.

Also the tests don't seem to run reliably on my computer (x86_64). They passed in the above CI for 64-bit architectures but failed on my end with lots of mismatched checksum errors (maybe it's just that my machine is not beefy enough to run tests).

The updating progress: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/40921
Build log on x86 with failure: https://gitlab.alpinelinux.org/FollieHiyuki/aports/-/jobs/891685/raw

**Comment by jkowalski** [comment]
32-bit architectures are not something we regularly test against on CI/CD since most users are on 64-bit platforms.

This particular failure appears to be due to memory usage increase that caused OOM. If you find a root cause/workaround for building on 32-bit, I'll be happy to merge the fix.
