### ISSUE TITLE
fatal error(s) while snapshotting

### ISSUE THREAD

**Issue by areqq** [kopia/kopia#2553]
kopia --version
0.12.1 build: 5227d74996b6520f9f96e4203cfe00b832a60d5f from: kopia/kopia
linux x64

I created sftp repo:
kopia repository create sftp --path=/tank/aqbackup/ --host=xxxx  --username=xxx --keyfile=/home/users/areq/.ssh/id_rsa --known-hosts=/home/users/areq/.ssh/known_hosts  --file-log-level=debug

kopia snapshot create ~/backup/
finished with:
Created snapshot with root k93863d24a7d6975e4e5ceaa5698db886 and ID 1e0de6b5ed715d7567752af0c771cdb4 in 0s
WARN Ignored 3 error(s) while snapshotting areq@q:/home/users/areq/backup.
ERROR Found 1 fatal error(s) while snapshotting areq@q:/home/users/areq/backup.

$ kopia snapshot list
areq@q:/home/users/areq/backup
  2022-11-06 23:07:27 CET k93863d24a7d6975e4e5ceaa5698db886 1.9 GB drwxr-xr-x files:58164 dirs:4703 errors:1 (latest-1..6,hourly-1,daily-1,weekly-1,monthly-1,annual-1)
  + 5 identical snapshots until 2022-11-06 23:25:30 CET

What went wrong?

**Comment by jkowalski** [comment]
Most likely some file or directory under ~/backup/ could not be read. 

`kopia ls k93863d24a7d6975e4e5ceaa5698db886`

Should tell you what happened
