### ISSUE TITLE
Can You Use KOPIA to Backup S3 Object Storage Buckets?

### ISSUE THREAD

**Issue by vermaden** [kopia/kopia#2605]
As in topic.

Its known that KOPIA backups TO S3 storage - but if its possible to backup the S3 storage into other S3 storage with KOPIA?

Thanks.

**Comment by kapitainsky** [comment]
I see two options here:

1. To have backup with snapshots etc you can use e.g. rclone to mount your S3 bucket to local filesystem and backup from there

2. To have sync copy you can use kopia sync feature: https://kopia.io/docs/reference/command-line/common/repository-sync-to-s3/

**Comment by vermaden** [comment]
Thank You very much - this is exactly what I needed :)

Regards.
