### ISSUE TITLE
Adding a policy to a specific host, doesn't inherit from global

### ISSUE THREAD

**Issue by 0x3333** [kopia/kopia#2607]
I have a repo that is shared across multiple hosts. In the global policy, I set some files I want to be ignored by all hosts, like, `/dev`, `/proc`, etc.

The problem is that if I add a specific host policy, like `/var/lib/docker` for a host, all the global policies are ignored, and only the ones for this specific host are in place.

Is there a way to keep the global one while adding host one?

**Comment by lupusA** [comment]
Hi @0x3333,  

i am closing this issue in favor of #3162 

Cheers,
