### ISSUE TITLE
kopia snapshot verify got BLOB not found ,but I can find the blob in repo.

### ISSUE THREAD

**Issue by ericma15** [kopia/kopia#2648]
I run cmd `kopia snapshot verify --verify-files-percent=1`,then i get follow
```
Listing blobs...
10000 blobs...
20000 blobs...
30000 blobs...
40000 blobs...
50000 blobs...
60000 blobs...
70000 blobs...
80000 blobs...
90000 blobs...
100000 blobs...
110000 blobs...
Listed 110632 blobs.
Processed 0 objects.
ERROR error processing xxx@xxxx:xxxxxx@2022-12-01 17:54:36 CSTxxxxxx1: object Ix846020e29a521edf663debb9d2756053 is backed by missing blob pecfe43d3ec858eddcf070647b9b53d4d-sd64a5581e2fe6ea7116
ERROR error processing xxx@xxxx:xxxxxx@2022-12-01 17:54:36 CSTxxxxxx2: object Ixda668421b2a409cbfae07a56fd1d7bfc is backed by missing blob p2fa04e6f0ab5c146c4e5fbaff89df56f-sa84daaf1fd684016116
ERROR encountered 2 errors
```
It says BLOB not find, but i find it in the repo.
<img width="179" alt="image" src="https://user-images.githubusercontent.com/27952575/207319425-ab3a909f-b6e2-493a-8891-5d9ba62393f9.png">
<img width="978" alt="image" src="https://user-images.githubusercontent.com/27952575/207319397-a5e32017-2d92-4c83-99db-6072b10d7b60.png">
 I use backend rclone, and my version is `0.12.1 build: 5227d74996b6520f9f96e4203cfe00b832a60d5f from: kopia/kopia`

**Comment by Jambo15** [comment]
I had a similar situation  using KopiaUI 0.12.1 using rclone backend and default settings [1].
I could not use the backup any longer and deleted it. Still creating a new one.

[1]
Hash: BLAKE2B-256-128, Encryption: AES256-GCM-HMAC-SHA256, Splitter: DYNAMIC-4M-BUZHASH, Format version: 2, Content compression: true, Password changes: true, Max pack length:  20 MiB, Index Format: v2
Storage config: {"remotePath": "<provider>:/<reponame>","rcloneExe": "C:\\<..>\\rclone.exe","atomicWrites": false, "dirShards": null}

**Comment by ericma15** [comment]
My backend is also rclone. But i run it on Linux.
