### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by samasara-maker** [kopia/kopia#2675]
curl -s https://kopia.io/signing-key | sudo gpg --dearmor -o /usr/share/keyrings/kopia-keyring.gpg

File '/usr/share/keyrings/kopia-keyring.gpg' exists. Overwrite? (y/N) y

gpg: no valid OpenPGP data found.

**Comment by ingul-buz** [comment]
Can't confirm, your command worked just fine over here.

In this context the error usually just means that curl failed in downloading the file for some reason, and consequently piped nothing to gpg. If your kopia-keyring.gpg is now 0 bytes long, it's no wonder there's no valid OpenPGP data to be found.

Maybe just try again.

**Comment by soapycub** [comment]
for anyone else who is having this problem, i discovered the issue was that curl wasn't installed
