### ISSUE TITLE
Repository Server

### ISSUE THREAD

**Issue by mxj4** [kopia/kopia#2688]
The documentation says
> Before we can start repository server, we must first create a list of usernames and passwords that will be allowed access.

But this won't work due to this error:
> ERROR open repository: repository is not connected. See https://kopia.io/docs/repositories/

The doc should start from talking about connect to repositories, or link to another page to explain necessary repository setup.

**Comment by m2acgi** [comment]
Same issue here.

**Comment by andreiwow2** [comment]
I also have the same issue, I can't manage to add the users, I am running it in docker
