### ISSUE TITLE
Cannot run on Ubungu, current application is not an AppImage

### ISSUE THREAD

**Issue by kendzi** [kopia/kopia#2714]
I tried kopia for first time. I install it using guide from webpage for Ubuntu 22.04
https://kopia.io/docs/installation/#linux-installation-using-apt-debian-ubuntu

kopia-ui started once, I was able to configure and run backup. But after computer restart, I cannot run it again. I got an error:
```
> kopia-ui                                   
14:56:04.101 › APPIMAGE env is not defined, current application is not an AppImage

```

**Comment by Bovive** [comment]
I have the same issue. Ran once fine and now I receive the same error. Also on Ubuntu 22.04.

**Comment by kendzi** [comment]
Ok, looks like it's working even with that message. Simply, it takes little time to start, and it won't show any window but instead run itself as background process with tiny icon around the clock. It is a little bit confusing as I expect to see some window, same as it was when I first run it.

**Comment by Bovive** [comment]
After a reinstall it started working for me.
