### ISSUE TITLE
[Feature] Define a Kopia CLI output format

### ISSUE THREAD

**Issue by julio-lopez** [kopia/kopia#272]
This becomes part of the API contract with systems that interact with the Kopia CLI and parse its output.

Some commands have a well defined output, such as `blob list`, for others it is not completely clear and some of the interesting and relevant information may go instead to the logs.

First step is to review the output of the different commands, document the format for the ones that we consider are well defined, and identify the command outputs that need improvement.

As a related feature (that should probably be tracked in a separate ticket), is to add structured output for those commands, for example using JSON.

**Comment by julio-lopez** [comment]
Also, whatever we decide the output of a command to be, that should go to `stdout`, and nothing else should go to `stdout`. Error and log messages should go to `stderr`

**Comment by julio-lopez** [comment]
FYI @pavannd1 @redgoat650

**Comment by jkowalski** [comment]
How about we support `--json` flag on all commands where it makes sense and leave non-JSON format undefined?

**Comment by jkowalski** [comment]
In particular `snapshot create` could return `snapshot.Manifest` which is reasonably expected to stay unchanged and backwards compatible since it's stored in the repository itself.

**Comment by julio-lopez** [comment]
It makes sense to add `--json` to provide _structured_ output.

At some point, even if we do not guarantee backwards compatibility and explicitly say it is not guaranteed, it'd be good to define what the expected output for different commands should be and have the commands follow a consistent pattern.

**Comment by jkowalski** [comment]
Moving this to 0.6.

**Comment by julio-lopez** [comment]
#642

**Comment by julio-lopez** [comment]
We should prioritize this issue.

Independent of the output format (JSON, YAML, table, plain text, etc), the first step is to define and document the data (fields) that each command should produce on stdout.

Then we can have one or two format implementation for those. A default human-readable plain text one and perhaps JSON.
