### ISSUE TITLE
unable to restore from a sharepoint repository

### ISSUE THREAD

**Issue by hydazz** [kopia/kopia#2728]
I'm trying to move from duplicati to kopia, backing up went fine, however, I've already needed to restore from a backup, which ain't workin.

When I go to restore a directory (~800mb) it downloads about 20mb before stopping, and then the UI crashes (is not accessible), and requires me to restart the container to get it working again.
I can't find any relevant information in the logs to diagnose this, I've run a restore using the CLI, which also downloads ~20mb before stopping.

I have 1000mbps down, I would expect this to take no more than 30 seconds... though I should note that backing up takes WAY less time than it should, ~2gb takes less than 2 minutes to backup with 50mbps up (which is impossible)

```
kopia restore k05a01982780b1c42951e85da3a0e9b14 /mnt/user/system/swag
Restoring to local filesystem (/mnt/user/system/swag) with parallelism=8...
Processed 4553 (0 B) of 22385 (376.7 MB).
Processed 6621 (2.6 MB) of 43019 (782.4 MB) 774.1 KB/s (0.3%) remaining 16m46s.
...no more output...
```

in `top` there is a rclone process still running in the background `rclone -v serve webdav SharePoint:/Kopia`
I'm not very familiar with kopia, so don't really know where to start troubleshooting

**Comment by lupusA** [comment]
Hi @hydazz, 

is there a need to connect to the webdav using rclone? In ```kopia``` you can connect to a webdav server directly. Regarding the second question, Snapshotting a directory of 2GB can run pretty fast, when doing an incremental snapshot as it only processes changed files. 

Cheers,

**Comment by hydazz** [comment]
but slow on the reply on this one... it's resolved.

The underlying issue was sharepoint rate limiting, so either way I would have been throttled, just switched to a ssh repository thats synced to B2
