### ISSUE TITLE
How to create a systemd service? [repository server]

### ISSUE THREAD

**Issue by TimoHess** [kopia/kopia#2737]
I got problems to create a service to run the kopia repository server to start it after system reboots.

At the moment I start the server with this command:

```/usr/bin/kopia server start --htpasswd-file /root/htpasswd.txt  --tls-cert-file /root/my.cert --tls-key-file /root/my.key --address <address>:51515 --config-file=/root/.config/kopia/repository.config ```

I use the command as root and I want to start the service with root.

I tried already different services like this one:
https://kopia.discourse.group/t/kopia-repository-server-installation-doc/251/2
or this one:
https://github.com/kopia/kopia/issues/2685

Even like borg with a .sh file. When I run the .sh file it works and the server is starting up. But in compination with systemd it isn´t working.

This is my kopia repository.config:

```
{
  "storage": {
    "type": "rclone",
    "config": {
      "remotePath": "PATH:PATH",
      "rcloneExe": "/usr/bin/rclone",
      "atomicWrites": false,
      "dirShards": null
    }
  },
  "caching": {
    "cacheDirectory": "/root/.cache/kopia/23r4234323",
    "maxCacheSize": 5242880000,
    "maxMetadataCacheSize": 5242880000,
    "maxListCacheDuration": 30
  },
  "hostname": "HOSTNAME",
  "username": "root",
  "description": "Backup",
  "enableActions": false,
  "formatBlobCacheDuration": 900000000000
}
```

journal -u kopia gives me this:

```
systemd[1]: Starting Kopia Server...
kopiaStart.sh[3962757]: Server will allow connections from users whose accounts are stored in the repository.
kopiaStart.sh[3962757]: User accounts can be added using 'kopia server user add'.
kopiaStart.sh[3962757]: ERROR unable to initialize repository: unable to initialize repository: error opening unable to open repository: cannot open storage: unable to start rclone: rclone server failed to start: password:Failed to read line: EOF
systemd[1]: kopia.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: kopia.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Kopia Server.
lines 608-687/687 (END)
```
I tried different ways with my service file. Atleast with .sh files:

```
cat /etc/systemd/system/kopia.service
[Unit]
Description=Kopia Server
After=syslog.target
After=network.target

[Service]
User=root
Type=oneshot
Environment="HOME=/root"
ExecStart="/root/.local/bin/kopiaStart.sh"
ExecStop="/root/.local/bin/kopiaStop.sh"
#Restart=always
#RestartSec=35

[Install]
WantedBy=multi-user.target
```

I hope someone can help me with my problem.

**Comment by nktl** [comment]
It seems like kopia prompts you interactively for some sort of rclone password when running the command / starting the service? If so, this won't work with systemd unit, you need to provide it in a non-interactive way.

**Comment by nktl** [comment]
That is your problem then, .bashrc is generally not available in the context of systemd job.
You can either:
1. Add that password env var to `Environment=` param under [Service] in systemd unit
2. Change the shebang in your kopia sh script to `#!/bin/bash -i` (to invoke 'interactive' login - which sources .bashrc, pretty bad practice)

**Comment by TimoHess** [comment]
> That is your problem then, .bashrc is generally not available in the context of systemd job. You can either:
> 
>     1. Add that password env var to `Environment=` param under [Service] in systemd unit
> 
>     2. Change the shebang in your kopia sh script to `#!/bin/bash -i` (to invoke 'interactive' login - which sources .bashrc, pretty bad practice)

Thank you for your help. Exactly that was my problem. It is starting now 👍 . I think it´s secure in /etc/systemd/sytem. I added a 600 chmod for the kopia service.
