### ISSUE TITLE
CPU usage spikes every 60s in idle mode with the docker container

### ISSUE THREAD

**Issue by MattFromGer** [kopia/kopia#2759]
While monitoring the power consumption of my server, I recognised that it consumes slightly more power when the kopia docker container is running on idle.
Using docker stats I can see that every 60 seconds the container uses 30% of CPU for 5s.
Can anybody else reproduce this behaviour? What is the container doing every 60s?

Moreover kopia accesses the repo files `kopia.repository.f` and `kopia.blobcfg.f` even though I have no tasks scheduled.

**Comment by lupusA** [comment]
Hi @MattFromGer, 

it is propably what has been stated in the past:

> Kopia performs periodic refresh of the repository indices to discover new policies and bring in additional contents to aid in deduplication. The timing of this refresh has not been really tuned and is probably too aggressive and we can/should change it.

I am closing this issue in favor of #2921
