### ISSUE TITLE
the s3 bucket(kopia backup target) always increased

### ISSUE THREAD

**Issue by milano127** [kopia/kopia#2783]
- We create the kopia backup on nov.2022, the backup folder is on the zfs filesystem, and the kopia target is S3
- the total data is about 43T in s3  on nov.2022, but now the data is 65T,  it is strange that the raw data is not increased much
- from the kopia content stats: the compression ratio is not changed 
and I find the s3 bucket usage size is always increased and never decreased, so is there any parameter in kopia that will never delete the data?

**Comment by lupusA** [comment]
Hi @milano127, 

please refer to #2830. Maybe there is an option similar to b2. 

Cheers,

**Comment by milano127** [comment]
> Hi @milano127,
> 
> please refer to #2830. Maybe there is an option similar to B2. If you still face this issue, feel free to comment.
> 
> Cheers,

Thanks for your update, 
we use s3 as stoarge,  do you know how to update the related information in s3?

**Comment by lupusA** [comment]
Hi, 

am not using a third party storage provider such as B2 or S3. Check if S3 is configured to keep versions. Depending on the provider, maybe this helps: https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html

However, **please proceed carefully**. Changing settings may result in unintentend behaviour and even lead to data loss. 
Also make sure, that versioning is the reason your accumulating data. 

Cheers,
