### ISSUE TITLE
Feature request: UI - option to create a backup without using encryption

### ISSUE THREAD

**Issue by Newdea** [kopia/kopia#2788]
I like using Kopia to backup some folders.
And 
It would be nice if Kopia UI  can create a backup without using encryption.

**Comment by talios** [comment]
> without using encryption.

Encryption is one of the fundamental features of Kopia, and is rooted right at the repository layer.  I don't really see the devs being interested in adding such a feature.

What would be your use-case for non-encrypted backups?

**Comment by Newdea** [comment]
I want to back up some document files (such as pdf, doc, etc.) edited in my computer to WebDev, and then sometimes I need to view these documents directly on my phone, and there is no Kopia on the phone to decrypt them.
In the past, there were some cases of file loss when uploading/syncing directly to webdev, so here I hope to be able to backup and sync through Kopia-UI.

**Comment by ZoomRmc** [comment]
Unfortunately, just eschewing encryption wouldn't help in your situation. Kopia doesn't store backup files per se, it processes them, splits into chunks and puts them in a repository. This is a fundamental mechanism which is essential for incremental backup (which Kopia features) and can't be reasonably turned off.

If you want to backup plain files, look up one of the multitude of rsync-based solutions.

Not sure what you mean exactly mentioning WebDev, but I think it's tangential to backups. If you could describe the desired workflow in more detail, may be we could suggest some alternatives.

**Comment by Newdea** [comment]
Thanks for replying, just spelled wrong, it should be WebDAV. Maybe I really need a different tool to do this stuff.

**Comment by ZoomRmc** [comment]
Just set up a regular/fsnotify-triggered copying of your local files to WebDAV with rclone. Keep in mind, this is _not_ a backup, more of a file synchronization solution. You lose verisioning (unless you backup to dated subfolders and not overwrite), backup deduplication, compression and file-integrity control. Also, maybe Syncthing is what you're looking for.

**Comment by Newdea** [comment]
thanks a lot, i will try it

**Comment by julio-lopez** [comment]
- Encryption cannot be turned off
- There is no 1:1 mapping between files in the source and blobs in the repository. Files are split into smaller chunks (when they are large) and multiple chunks are packed into blobs in the repository.

**Comment by wsw70** [comment]
> What would be your use-case for non-encrypted backups?

A single point of failure in the case of backups already protected otherwise.

I do get that backups stored in hostile environments gain at being encrypted (still, this depends on your threat landscape) but when the repos sit in a secured place you do not gain much and may lose a lot.

**Comment by DanteMarshal** [comment]
Is there Really no way to create a local repo without encryption ?
My only use cases are deduplication, chunking and error correction, and the data is not important at all to be encrypted. I just don't want to lose it, which an unrecoverable encryption (in case of password-loss) is directly against that.
