### ISSUE TITLE
mmap error: invalid argument

### ISSUE THREAD

**Issue by aniqueta** [kopia/kopia#2793]
I'm not sure when this error started, but in checking on my backups, I discovered that all kopia actions are failing with errors like these. I was not able to find any information on the `mmap error: invalid argument` error type. 

```
ERROR failed to open repository: unable to create shared content manager: error loading indexes: unable to open pack index "XXXXXX": mmap error: invalid argument
ERROR open repository: unable to open repository: unable to create shared content manager: error loading indexes: unable to open pack index "XXXXXX": mmap error: invalid argument
```

Any idea what the issue may be? Is the repository corrupt and is there a way to repair? Thanks.

**Comment by aniqueta** [comment]
Digging into logs more, there was a successful maintenance and then at the next scheduled snapshot after a series pf `ListBlobs` the repo was closed and then the above error is the next line. 

```
DEBUG kopia/repo [STORAGE] concurrency level reached	{"maxConcurrency":3}
DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"XX","resultCount":1,"error":null,"duration":"61.556105ms"}
DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"XX","resultCount":4,"error":null,"duration":"129.747123ms"}
DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"XX","resultCount":2,"error":null,"duration":"164.194767ms"}
DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"XX","resultCount":46,"error":null,"duration":"180.428519ms"}
DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"XXXX_","resultCount":0,"error":null,"duration":"59.331746ms"}
DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"XXXX_","resultCount":20,"error":null,"duration":"73.827353ms"}
DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"XXXX_","resultCount":7,"error":null,"duration":"117.605782ms"}
DEBUG kopia/repo [STORAGE] Close	{"error":null,"duration":"1.593µs"}
ERROR kopia/repo failed to open repository: unable to create shared content manager: error loading indexes: unable to open pack index "XXXXX": mmap error: invalid argument
```

**Comment by fcalvet** [comment]
I had a similar issue with KopiaUI.
It was resolved for me by doing: disconnect from repository, connect in read-only mode, disconnect, connect (in normal mode).

**Comment by aniqueta** [comment]
I didn't have time to troubleshoot, and for me, it appears the error disappeared on its own…

**Comment by Ember-ruby** [comment]
i'm getting this issue, persistent between reboots too, i'd guess it's client side as the other computer that connects to the repo doesn't have issues
