### ISSUE TITLE
Kopia policy set for a WebDAV repository isn't possible.

### ISSUE THREAD

**Issue by orencio** [kopia/kopia#2797]
I've created WebDAV repository and I've validated it correctly, but I can't set policy values because it appears to be impossible to specify WebDAV URL/path:

```bash
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

$ kopia --version
0.11.3-1 build: unofficial from: ARCH_USER_REPOSITORY

$ kopia repository --password '***'  create webdav --url 'https://***/dav/repo-kopia' --webdav-username '***' --webdav-password '***'
...

$ kopia repository validate-provider
Validating storage capacity and usage
Validating blob list responses
Validating non-existent blob responses
Writing blob (5000000 bytes)
Validating conditional creates...
Validating list responses...
Validating partial reads...
Validating full reads...
Validating metadata...
Running concurrency test for 30s...
All good.
Cleaning up temporary data...

$ kopia policy show @https://***/dav/repo-kopia
Policy for user@host:/home/user/@https:/***/dav/repo-kopia:
...

$ kopia policy show --help
usage: kopia policy show [<flags>] [<target>...]
...
Args:
  [<target>]  Select a particular policy ('user@host','@host','user@host:path' or a local path). Use --global to target the global policy.
```

It isn't possible to specify WebDAV URL. It interprets WebDAV URL as local path (`user@host:/home/user/@https:/***/dav/repo-kopia`).

It is in doc too: <https://kopia.io/docs/reference/command-line/common/policy-show/>.

Shouldn't it be possible to modify the policies of a WebDAV repository?

**Comment by raisinbear** [comment]
You possibly found out by now but you don’t set / show / operate on policies by specifying the backend (WebDAV in your case), but by local folder that you plan to snapshot and want to specify the policy for, so e.g. john@pcname:/home/john or plainly /home/john. Or even globally for all potential snapshot sources but still without specifying the backend. After all you are / have to be already connected to the repository to do so.

**Comment by lupusA** [comment]
Imhey @orencio ,

Is it working by now?

Cheers,

**Comment by lupusA** [comment]
Hey @orencio, 

as it was pointed out, creating a policy is working by specifying the path of the snapshot and not the backend. 

Cheers,
