### ISSUE TITLE
Support authorize requests with Azure AD

### ISSUE THREAD

**Issue by ywk253100** [kopia/kopia#2800]
[Azure AD](https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-requests-to-azure-storage) is the recommended way to authorize the requests to access the Azure storage. 

In some user cases, Azure AD is the only allowed way to do the auth, and getting the access key from Azure AD isn't allowed.

With Azure AD support, users can use Azure AD credentials directly and it is also helpful for integration with other products.

**Comment by julio-lopez** [comment]
Patches are welcome
