### ISSUE TITLE
Bump up the versions of azure-sdk-for-go libraries

### ISSUE THREAD

**Issue by ywk253100** [kopia/kopia#2802]
Currently, the versions of the libraries `azure-sdk-for-go/xxx` are quite old:
```
github.com/Azure/azure-sdk-for-go/sdk/azcore v0.21.1
github.com/Azure/azure-sdk-for-go/sdk/internal v0.8.3
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.3.0
```

The latest versions are as follows:
```
github.com/Azure/azure-sdk-for-go/sdk/azcore v1.4.0
github.com/Azure/azure-sdk-for-go/sdk/internal v1.2.0
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.0.0
```

There are some breaking changes introduced by the new versions of libraries and causing Kopia codes cannot be integrated with other products/software that use the latest versions of libraries.

**Comment by jkowalski** [comment]
PR to update the provider is very much appreciated, there's a breaking change with this release and I don't have capacity to fix it myself.

**Comment by ywk253100** [comment]
The libraries were bumped up by the PR https://github.com/kopia/kopia/pull/3056.
I'm closing this issue.
