### ISSUE TITLE
Use `disable-all` at `.golangci.yml:71` instead of `enable-all`

### ISSUE THREAD

**Issue by aaron-kasten** [kopia/kopia#2831]
`golangci-lint` is a tool that is in constant evolution.  New upstream linters can be added at any time.  This poses a problem for `kopia` builds as they rely on enabling _all_ upstream linters and then excluding specific ones.

This ticket proposes to `disable-all` linters so the configuration starts with a known set of linters - the empty-set.  New linters can be included to expand the set.  When presented with a unknown set of a class, the only intersection that produces a known result is the empty-set.  So starting with no linters enabled is a logical and safe starting point.

**Comment by jkowalski** [comment]
This is intentional, we actually want to raise the bar and include new linters (or disable them when they don't add values) whenever we upgrade the linter version.

**Comment by julio-lopez** [comment]
As Jarek said.
