### ISSUE TITLE
Invalid password

### ISSUE THREAD

**Issue by flagship-extenuate** [kopia/kopia#2849]
I've recently started having an invalid password issue with a repo located on the host's filesystem

![image](https://user-images.githubusercontent.com/128803369/227505279-9a0cb05b-e85a-4357-b936-0ce2fa5350fc.png)

I tried stepping into the CLI to see if I'd have the same result:
```
$ kopia repository connect filesystem --path="$PWD"
Enter password to open repository:

ERROR failed to open repository: unable to create format manager: invalid repository password
ERROR error connecting to repository: unable to create format manager: invalid repository password
```

I don't believe the password is incorrect; the password is stored in a password manager.

**Comment by lupusA** [comment]
Hi @flagship-extenuate, 

can you give some more details about your setup? Is the "PWD" variable correctly pointing to the right repository?

Cheers,

**Comment by lupusA** [comment]
That is most likely the repository :-). However, is it the correct one? Do you have multiple repositories? 
Kopia can connect to mulitple repositories. Can you check the date and time of the kopia.repository.f file? Then we know the time when this repository was created.

**Comment by flagship-extenuate** [comment]
I only have one repository.

For `kopia.repository.f` date created = date modified = January 28th, 2023

The last modified date for the subdirectories was March 16th, 2023/

**Comment by lupusA** [comment]
Do have a backup of your password manager? Maybe the password has changed somehow. If not, it is a strange bug which I haven't seen so far.

**Comment by flagship-extenuate** [comment]
My password manager, Bitwarden, states the password has not been modified since January.

**Comment by lupusA** [comment]
Did you disconnect on your own or were you disconnected by the application? If the repository is correct and the password has not been changed, and the password is the correct one (there were users in the past who got confused by server-password and KOPIA_PASSWORD) then its a strange bug indeed.

**Comment by flagship-extenuate** [comment]
I did not (knowingly) change anything in the GUI.

I haven’t been using environment variables as I’ve been working via the Windows GUI.

Is it possible for corruption due to abrupt loss of power off to cause this?

**Comment by lupusA** [comment]
Maybe it is related to this? https://github.com/kopia/kopia/issues/856

Does your password contain something that would need escaping characters?

Otherwise, I am out of ideas...

Cheers,

**Comment by flagship-extenuate** [comment]
Thanks, but no luck.

A side note: I would not expect this to be an issue with the GUI, regardless.

I'm wondering if something got corrupted.

**Comment by lupusA** [comment]
If it was a power outrage, there is a chance that it got corrupted, i guess. However, you do not have a backup of the repository somewhere else, do you?

**Comment by flagship-extenuate** [comment]
Thanks, but no luck. I also tried removing the `*.f` as recommended and any empty files.

At this point I'm just going to recreate the repo. Thanks though.
