### ISSUE TITLE
debian 11 and others - apt following signatures were invalid 

### ISSUE THREAD

**Issue by itxworks** [kopia/kopia#2947]
et:5 https://packages.kopia.io/apt stable InRelease [5,015 B]
Err:5 https://packages.kopia.io/apt stable InRelease
  The following signatures were invalid: EXPKEYSIG 2273699AFD56A556 Kopia Builder <builder@kopia.io>
Reading package lists... Done

**Comment by ovizii** [comment]
same here

**Comment by borfast** [comment]
It's not just Debian 11, I'm running Mint 21.1 (based on Ubuntu 22.04) and I'm having the same issue. @itxworks, might I suggest you change the title of the issue to reflect the broader problem?

**Comment by jkowalski** [comment]
This is a duplicate of #2947, closing this one.

**Comment by jkowalski** [comment]
I've updated the signing key on the website, unfortunately it needs to be-reimported on affected systems for validation to succeed.

The updatred key is in https://kopia.io/signing-key

Please follow instuctions from  https://kopia.io/docs/installation/

**Comment by borfast** [comment]
Thank you! :+1:

**Comment by millecentdix** [comment]
I can confirm it solve the issue.

Just a comment for the doc, the directory for GPG keys on Debian/Ubuntu is now /etc/apt/trusted.gpg.d/

**Comment by borfast** [comment]
@millecentdix, that's already covered, I opened [a PR for it](https://github.com/kopia/kopia/pull/2953) and it's now merged.

**Comment by millecentdix** [comment]
@borfast very good job ! I have use it few minutes ago, refresh my cache browser and it is not mentioned the good path.
![image](https://user-images.githubusercontent.com/31278829/233103044-437c5af8-6bc3-4ee7-aabc-7bc7bc9e1ec6.png)
Have I miss something ?

**Comment by borfast** [comment]
Sorry, I didn't notice you mentioned another path. The one you mentioned would also work but `/etc/apt/keyrings` is the recommended one.

From `apt-key`'s manpage:
>Recommended: Instead of placing keys into the /etc/apt/trusted.gpg.d directory, you can place them anywhere on your filesystem by using the Signed-By option in your sources.list and pointing to the filename of the key. See sources.list(5) for details. Since APT 2.4, /etc/apt/keyrings is provided as the recommended location for keys not managed by packages. When using a deb822-style sources.list, and with apt version >= 2.4, the Signed-By option can also be used to include the full ASCII armored keyring directly in the sources.list without an additional file.

**Comment by itxworks** [comment]
Thank you ...

**Comment by fireice-uk** [comment]
Here is a command snippet to update from the old keyring location:

```
sudo rm /etc/apt/sources.list.d/kopia.list
sudo rm /usr/share/keyrings/kopia-keyring.gpg
curl -s https://kopia.io/signing-key | sudo gpg --dearmor -o /etc/apt/keyrings/kopia-keyring.gpg
echo "deb [signed-by=/etc/apt/keyrings/kopia-keyring.gpg] http://packages.kopia.io/apt/ stable main" | sudo tee /etc/apt/sources.list.d/kopia.list
sudo apt update
```
