### ISSUE TITLE
Cannot connect to SFTP on 0.12.1 (or testing) - knownhosts: key mismatch

### ISSUE THREAD

**Issue by Cysioland** [kopia/kopia#2948]
Trying to setup an SFTP repository through KopiaUI on the Docker version of Kopia, copied known_hosts from the host machine (that's able to connect to that SFTP server no problem), and getting the following error:

```
Connect Error: INTERNAL: internal server error: unable to open SFTP storage: error establishing connecting: unable to dial [my.host:22]: &ssh.ClientConfig{Config:ssh.Config{Rand:io.Reader(nil), RekeyThreshold:0x0, KeyExchanges:[]string(nil), Ciphers:[]string(nil), MACs:[]string(nil)}, User:"user", Auth:[]ssh.AuthMethod{(ssh.passwordCallback)(0x11dd2e0)}, HostKeyCallback:(ssh.HostKeyCallback)(0x11d9940), BannerCallback:(ssh.BannerCallback)(nil), ClientVersion:"", HostKeyAlgorithms:[]string(nil), Timeout:0}: ssh: handshake failed: knownhosts: key mismatch
```

**Comment by andriej** [comment]
Probably target machine supports more keys - make sure you do `ssh-keyscan` and copy the one with rsa.
Kopia doesnt support ed* keys (#2443)

**Comment by Cysioland** [comment]
Did `ssh-keyscan -t rsa` on that host, copied that and the same problem

**Comment by hydazz** [comment]
also getting this issue, the keys are definitely correct, and running `ssh kopia@192.168.100.2 -p 2022 -vv` on the same machine with kopia works (with keys)

**Comment by friki67** [comment]
Hello! I was fighting with this same thing. I have  installed the 0.13.0-1 AUR package in another machine just to try to help here.
It is working for me. Please, see https://github.com/kopia/kopia/issues/2443#issuecomment-1410224071 , and all the thread, maybe it can help you.

Regards

**Comment by vaygr** [comment]
This is still a problem with latest **0.14.1**.

```
kopia repository create sftp --path=.backup/server --host=192.168.X.X --username=backup --keyfile=.ssh/id_rsa_backup --known-hosts=.ssh/known_hosts
```

to SSHd 8.2p1 results in:

```
ERROR can't connect to storage: unable to open SFTP storage: error establishing connecting: unable to dial [192.168.X.X:22]: &ssh.ClientConfig{Config:ssh.Config{Rand:io.Reader(nil), RekeyThreshold:0x0, KeyExchanges:[]string(nil), Ciphers:[]string(nil), MACs:[]string(nil)}, User:"backup",
Auth:[]ssh.AuthMethod{(ssh.publicKeyCallback)(0x55f7c6921220)}, HostKeyCallback:(ssh.HostKeyCallback)(0x55f7c691d860), BannerCallback:(ssh.BannerCallback)(nil), ClientVersion:"", HostKeyAlgorithms:[]string(nil), Timeout:0}: ssh: handshake failed: knownhosts: key mismatch
```

The key in use is RSA 4096 bit.

A workaround is to use external SSH client specified by `--external`.

cc @jkowalski

**Comment by vaygr** [comment]
Through experimentation I found that the internal client ignores `ssh-rsa` public key of the server, and, as was mentioned earlier here, ed25519 keys are not supported.

But as soon as I added `ecdsa-sha2-nistp256` to `.ssh/known_hosts`, it worked.

**Comment by braadaaay** [comment]
> A workaround is to use external SSH client specified by `--external`.

To add more context to this and how I got it to work WITHOUT _downloading_ another SSH client:

1. [Set up SSH public key authentication](https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server#step-1-creating-ssh-keys) to the SFTP server. This is crucial as you'll otherwise need to enter a password everytime a snapshot is created.
2. Use the following command to connect to the SFTP server `kopia repository connect sftp --path=[path/to/folder/on/host] --host=[hostname] --port=22 --username=[user] --external --ssh-args="-i [path/to/private/key]"`
3. Profit. 

Future readers, let me know if this helps,

**Comment by braadaaay** [comment]
I've found another way around this error. It requires using the "rclone remote" option.

1. Install the rclone client following [the instructions found here](https://rclone.org/install/).
2. Set up an SFTP remote using [these instructions](https://rclone.org/sftp/). I recommend not using spaces when naming your remote.
3. Setup your kopia repository by clicking "rclone remote" in the GUI if using KopiaUI, or `kopia repository connect rclone --remote-path=...`. The format is [remote name]:[/path/to/folder] (do not miss the colon between the name and folder)

**Comment by mcd92** [comment]
> 2\. --ssh-args="-i [path/to/private/key]"

Thank you, @vaygr! This was the last missing piece of the puzzle for me. ssh-rsa keys indeed are not working.

**Comment by vaygr** [comment]
@julio-lopez I see you marked this as completed. Can you describe this behavior?

**Comment by andriej** [comment]
I do not see any commits that would make it fixed too

**Comment by 9SMTM6** [comment]
It also failed for me with the rsa key and ssh-ed25519. But then I tried other keys from ssh-keyscan, and ecdsa-sha2-nistp256 worked for me (with the embedded ssh client, not the external one).

**Comment by andriej** [comment]
@julio-lopez - could you please consider reopening?

**Comment by tobiasBora** [comment]
I can confirm that neither rsa nor ecdsa work, but ecdsa-sha2-nistp256 does work. To get it:
```
ssh-keyscan -t ecdsa-sha2-nistp256 your.host.com
```
And copy paste the line to the field in kopia.

If the above list is empty, it means that the server has not configured any ECDSA key. If you run NixOS, you can enable it as follows:
```
  # Enable ecdsa-sha2-nistp256
  services.openssh.hostKeys = [
    # Default values
    {
      bits = 4096;
      path = "/etc/ssh/ssh_host_rsa_key";
      type = "rsa";
    }
    {
      path = "/etc/ssh/ssh_host_ed25519_key";
      type = "ed25519";
    }
    # Add ECDSA
    {
      path = "/etc/ssh/ssh_host_ecdsa_key";
      type = "ecdsa";
    }
  ];
```

**Comment by ghost** [comment]
Hi, This is still a problem in the latest version for Windows 0.22.3. I don't have a Linux desktop to try this on right now. The server is on local wired home network, direct connection, no firewalls, no VPNs, etc. and runs Debian 13.3.0. I can connect using Filezillal. Thank you.

**Comment by tobiasBora** [comment]
> @julio-lopez - could you please consider reopening?

See follow up in https://github.com/kopia/kopia/issues/5309
