### ISSUE TITLE
The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library

### ISSUE THREAD

**Issue by Athep** [kopia/kopia#2968]
I get the following error when trying to launch KopiaUI (version 20230421.0.1250-win)

"The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library"

Windows Server 2012 R2 
Version: 6.3.9600 Build 9600.

**Comment by cristihcd** [comment]
Electron ended support for the OS, see #2923

**Comment by Athep** [comment]
> Electron ended support for the OS, see #2923

Thanks for the information. I'm a new user of Kopia. The solution for me is to run Kopia as server and access the UI with chrome browser instead.
