### ISSUE TITLE
Deleting one kopia repo affected another

### ISSUE THREAD

**Issue by seaniedan** [kopia/kopia#2986]
I had this worrying error while trying out Kopia on a Raspberry Pi.

 I created a repo on the local filesystem at /mnt/seagate/**backup**, and started the first snapshot. After a long wait, I created another at /mnt/seagate/**nas**, in the same way:
```
kopia repository create filesystem --path /mnt/seagate/nas
kopia repository connect filesystem --path /mnt/seagate/nas
time sudo kopia snapshot create /mnt/nas
```

As that started, I stopped the /mnt/seagate/backup as it was taking a long time (I realised it maybe to do with the encryption). So I stopped it (ctrl+C) and removed the directory (sudo rm -rf /mnt/seagate/**backup**). At this point, I got this error in the process writing to /mnt/seagate/**nas** :

```
Snapshotting root@vpn:/mnt/nas ...
 / 4 hashing, 45589 hashed (6.1 GB), 0 cached (0 B), uploaded 4 GB, estimating...ERROR async write error: unable to write content chunk 0 of FILE:_solve_toeplitz.cpython-37m-arm-linux-gnueabihf.so: unable to write pack: error writing pack: can't save pack data blob p25079d1d44e817d0f06be6734a1bdb75-s1fb8ca485f524a5711b: error writing pack file: cannot create temporary file: cannot create directory: can't re-create top-level directory /mnt/seagate/backup: top-level directory not found: unable to write pack: error writing pack: can't save pack data blob p25079d1d44e817d0f06be6734a1bdb75-s1fb8ca485f524a5711b: error writing pack file: cannot create temporary file: cannot create directory: can't re-create top-level directory /mnt/seagate/backup: top-level directory not found
```

Why is it concerned that it can't re-create top-level directory /mnt/seagate/backup

..when my repo is in /mnt/seagate/nas ?

**Comment by seaniedan** [comment]
Update to add, I was using ssh to connect to the machine running these commands, and did the commands for nas and backup in separate terminal connections. 

Also, I created the repos as a normal user, but used sudo to run the snaphot. Could this be a factor? **After recreating the backup repo**, in the 'nas' session, when I run 
`kopia policy list
`I get:
```
ERROR failed to open repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob xn0_6b24b2a1441dcbbf48f64ae1f19d7856-sb8272062c89c28bb11b-c1: getContent: unable to complete GetBlobFromPath:/mnt/seagate/backup/x/n0_/6b24b2a1441dcbbf48f64ae1f19d7856-sb8272062c89c28bb11b-c1.f despite 10 retries: open /mnt/seagate/backup/x/n0_/6b24b2a1441dcbbf48f64ae1f19d7856-sb8272062c89c28bb11b-c1.f: permission denied
ERROR open repository: unable to open repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob xn0_6b24b2a1441dcbbf48f64ae1f19d7856-sb8272062c89c28bb11b-c1: getContent: unable to complete GetBlobFromPath:/mnt/seagate/backup/x/n0_/6b24b2a1441dcbbf48f64ae1f19d7856-sb8272062c89c28bb11b-c1.f despite 10 retries: open /mnt/seagate/backup/x/n0_/6b24b2a1441dcbbf48f64ae1f19d7856-sb8272062c89c28bb11b-c1.f: permission denied
```

but running as root is ok:
```
sudo kopia policy list
fba0d8a1ce1e9577f898e580c9dc5d7f (global)
```

**Comment by seaniedan** [comment]
OK, this is confusing! Though I connected to the **nas** repository with the command above, 
`kopia repository status
`shows I'm in fact connected to **backup**:
```
Config file:         /root/.config/kopia/repository.config

Description:         Repository in Filesystem: /mnt/seagate/backup/

```

Do I need different config files for each kopia repository?

**Comment by seaniedan** [comment]
OK, solved... I was connected to the original repository, **backup**, as user 'root' and the to the **nas** repository was me. So when I ran the sudo command to backup to what I thought was **nas**, I was in fact connecting to **backup**.

**Comment by julio-lopez** [comment]
@seaniedan
Yes, you need separate config files to connect to different repositories.
In general (and by default), different users in the same host will have different config files, one per user.
It seems that in your case, there are at least 2 config files in the host, one for your user and one for the root user (from when you sudo into it).
