### ISSUE TITLE
 unable to complete GetBlob(kopia.repository,0,-1) despite 10 retries

### ISSUE THREAD

**Issue by joyanhui** [kopia/kopia#2990]
`kopia repository create rclone --remote-path="alist-local:/alipan/kopia"`

or

```
kopia repository create webdav \
        --url="http://url/dav/alipan/kopia" \
        --webdav-password="XXX \
        --webdav-username="玄学" \
```

----------------
```
nter password to create new repository:
Re-enter password for verification:
Initializing repository with:
  block hash:          BLAKE2B-256-128
  encryption:          AES256-GCM-HMAC-SHA256
  splitter:            DYNAMIC-4M-BUZHASH
ERROR unable to connect to repository: error connecting to repository: unable to read format blob: unable to complete GetBlob(kopia.repository,0,-1) despite 10 retries: error populating output: unexpected EOF
```

**Comment by SantoSimone** [comment]
What version of rclone / kopia are you using?
Any version of kopia < v0.13.0 does not work with any version of rclone > 1.61
Reference, https://github.com/kopia/kopia/issues/2655

**Comment by shniubobo** [comment]
The webdav interface exposed by alist is not compatible with kopia. You need to add the webdav interface to rclone as a remote, and make kopia connect to that remote instead.

Related: #3006

**Comment by 9-2-1** [comment]
I found a way to solve this: edit the `repository.config` file and change `atomicWrites` from `false` to `true`.

But it is only safe if alist and its backends are atomic. (To ensure your data is safe, enable recycle bin before and run `content verify` after maintenance)

My repository is not corrupted yet.

**Comment by ericma15** [comment]
I find a solution. it seems has a rclone cache error. if this error occur,run rclone cat xxxx/kopia.repository.f to force flush the ache,then run kopia cmd.everything will work.
maybe we can run this flush in code?
