### ISSUE TITLE
kopia: error: unknown long flag '--insecure', try --help

### ISSUE THREAD

**Issue by osnabrugge** [kopia/kopia#2991]
Upgraded from v0.12.1 to v.13.0.0 with no configuration changes using your docker image.
Startup fails due to not being able to recognize the "--insecure" flag.

Trying to figure out what changed in this update that may have broken this, but not having much success as I am not really much of a developer.  Any help?  https://github.com/kopia/kopia/compare/v0.12.1...v0.13.0

**Comment by skrollme** [comment]
Same problem here

**Comment by jkowalski** [comment]
This is most likely a side effect of removing default subcommands. I'm guessing you're running `kopia server`.

Try running `kopia server start --insecure ...` instead of `kopia server --insecure`.

See https://github.com/kopia/kopia/pull/2861 for more details.

**Comment by skrollme** [comment]
Solved it for me, thank you @jkowalski

**Comment by osnabrugge** [comment]
Sorry for the delay, been away for a while.  I tested this and it worked for me as well.  Thank you!
