### ISSUE TITLE
How to backup to webdav which has some unknown limitations

### ISSUE THREAD

**Issue by joyanhui** [kopia/kopia#3006]
like alist or aliyundrive-webdav

```shell
./aliyundrive-webdav --refresh-token  <token>   --debug --auth-user webdav  --auth-password 123
-------------
Checking target-arch... x86_64-unknown-linux-musl
Checking current version... v2.2.1
Checking latest released version... INFO aliyundrive_webdav::drive: refresh token succeed
INFO aliyundrive_webdav::drive: found default drive drive_id=69439006
INFO aliyundrive_webdav::webdav: listening on http://0.0.0.0:8080/
```

```
kopia repository create webdav --url=http://localhost:8080/kopai33 --webdav-username webdav  --webdav-password 123
```
```
Enter password to create new repository:
Re-enter password for verification:
Initializing repository with:
  block hash:          BLAKE2B-256-128
  encryption:          AES256-GCM-HMAC-SHA256
  splitter:            DYNAMIC-4M-BUZHASH
ERROR unable to connect to repository: error connecting to repository: invalid format blob: unexpected end of JSON input
```

The same happens with [alist](https://github.com/alist-org/alist#features)

**Comment by joyanhui** [comment]
for alist whis aliyundrive

```
kopia repository create webdav \
        --url="http://10.1.1.200:5244/dav/aliyundrive/kopia-test/222" \
        --webdav-password="<pass>" \
        --webdav-username="<user>"

Enter password to create new repository:
Re-enter password for verification:
Initializing repository with:
  block hash:          BLAKE2B-256-128
  encryption:          AES256-GCM-HMAC-SHA256
  splitter:            DYNAMIC-4M-BUZHASH
ERROR unable to connect to repository: error connecting to repository: unable to read format blob: unable to complete GetBlob(kopia.repository,0,-1) despite 10 retries: ReadStream kopia.repository.f: 403
```

**Comment by ericma15** [comment]
I also use alist with aliyundrive, but it works fine. First use aliyun_open drive. Then use native proxy not redirect

**Comment by ericma15** [comment]
I also use rclone + alist + aliyun_open,it works well.

**Comment by joyanhui** [comment]
> I also use alist with aliyundrive, but it works fine. First use aliyun_open drive. Then use native proxy not redirect

That’s so kind of you！

**Comment by LakeishaKowalczyk** [comment]
> I also use rclone + alist + aliyun_open,it works well.

Is it possible to connect to Kopia using only alist via webdav, without using rclone?

**Comment by 9-2-1** [comment]
> > I also use rclone + alist + aliyun_open,it works well.
> 
> Is it possible to connect to Kopia using only alist via webdav, without using rclone?

Yes.

**Comment by ericma15** [comment]
> > > I also use rclone + alist + aliyun_open,it works well.
> > 
> > 
> > Is it possible to connect to Kopia using only alist via webdav, without using rclone?
> 
> Yes.

no,you cannot do this. if you use kopia webdav backend with alist. you‘ll find all your p type block‘s size is 20.00MB, if you try to recover some big data,you will find every p blob is broken. Maybe something wrong between them.

**Comment by LakeishaKowalczyk** [comment]
> Yes.

Have you tried it, and what are the versions of alist and kopia? I get errors when I use it like this, I have to use rclone as a middleman.

**Comment by 9-2-1** [comment]
> > Yes.
> 
> Have you tried it, and what are the versions of alist and kopia? I get errors when I use it like this, I have to use rclone as a middleman.

Sorry, I have forgotten that uploading snapshot will fail with 405 so repos connectted by this way will be read-only. I restore directly from webdav and create snapshot or do maintenance via rclone.

**Comment by 9-2-1** [comment]
> > > > I also use rclone + alist + aliyun_open,it works well.
> > > 
> > > 
> > > Is it possible to connect to Kopia using only alist via webdav, without using rclone?
> > 
> > 
> > Yes.
> 
> no,you cannot do this. if you use kopia webdav backend with alist. you‘ll find all your p type block‘s size is 20.00MB, if you try to recover some big data,you will find every p blob is broken. Maybe something wrong between them.

Thank you.

I have forgotten that uploading snapshot will fail with 405 so repos connectted by this way will be read-only. I only restore from webdav, while create snapshot and do maintenance via rclone.

Maybe here is something wrong about "Content-Length"?

**Comment by 9-2-1** [comment]
> > Yes.
> 
> Have you tried it, and what are the versions of alist and kopia? I get errors when I use it like this, I have to use rclone as a middleman.

It seems that someone have fixed this problem and it may work in the next version of alist.

https://github.com/alist-org/alist/pull/5162

**Comment by LakeishaKowalczyk** [comment]
@9-2-1 
Alist v3.28.0 released, the 405 is gone, it’s been replaced with 500 errors now :laughing:

**Comment by 9-2-1** [comment]
> @9-2-1 Alist v3.28.0 released, the 405 is gone, it’s been replaced with 500 errors now 😆

I Tried alist v3.28.0 and it works. (Windows 11, kopia 0.13.0, BaiduNetDisk)

**Comment by LakeishaKowalczyk** [comment]
Aliyundrive cannot create repositories but the situation with baidunetdisk seems to be better, it can create repositories (with one warning) and snapshots, but maintenance reports errors
`WARN unable to persist sharding parameters: Write .shards-7014483602698420709: 405`
`ERROR unable to report run: unable to complete PutBlob(kopia.maintenance) despite 10 retries: Write kopia.maintenance.f-3654851736882728461: 405`

Kopia and alist seem to have mutual disdain for each other, you don’t want to be compatible with me and I can’t be bothered to be compatible with you either
