### ISSUE TITLE
Can't update to 0.13 on Fedora 38

### ISSUE THREAD

**Issue by Xiol** [kopia/kopia#3018]
Related to #2997 which was (IMO) prematurely closed.

I'm not able to update to Kopia 0.13. I have removed the GPG key and reimported, but I'm still getting an error (though, a different one from the one that originally opened #2997 due to an RPM update in the meantime):

```
❯ cat /etc/yum.repos.d/kopia.repo
[Kopia]
name=Kopia
baseurl=http://packages.kopia.io/rpm/stable/$basearch/
gpgcheck=1
enabled=1
gpgkey=https://kopia.io/signing-key

❯ rpm -q rpm
rpm-4.18.1-3.fc38.x86_64

❯ rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n' | grep Kopia
gpg-pubkey-fd56a556-6078ec06	Kopia Builder <builder@kopia.io> public key

❯ sudo dnf update
Last metadata expiration check: 0:02:02 ago on Wed 03 May 2023 09:59:48 BST.
Dependencies resolved.
================================================================================================================================================================
 Package                              Architecture                          Version                                  Repository                            Size
================================================================================================================================================================
Upgrading:
 kopia                                x86_64                                0.13.0-1                                 Kopia                                 12 M

Transaction Summary
================================================================================================================================================================
Upgrade  1 Package

Total size: 12 M
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] kopia-0.13.0.x86_64.rpm: Already downloaded                                                                                                          
Running transaction check
error: Verifying a signature using certificate 7FB99DFD47809F0D5339D7D92273699AFD56A556 (Kopia Builder <builder@kopia.io>):
  Certificate 2273699AFD56A556 invalid: policy violation
      because: No binding signature at time 2022-10-01T23:28:47Z
error: rpmdbNextIterator: skipping h#      29 
Header V4 RSA/SHA512 Signature, key ID fd56a556: BAD
Header SHA256 digest: OK
error: Verifying a signature using certificate 7FB99DFD47809F0D5339D7D92273699AFD56A556 (Kopia Builder <builder@kopia.io>):
  Certificate 2273699AFD56A556 invalid: policy violation
      because: No binding signature at time 2022-10-01T23:28:47Z
error: rpmdbNextIterator: skipping h#      29 
Header V4 RSA/SHA512 Signature, key ID fd56a556: BAD
Header SHA256 digest: OK
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: An rpm exception occurred: package not installed
```

I have ran `dnf clean packages` (and `all`), neither helped.

Some Googling indicated enabling SHA1 crypto policies (`update-crypto-policies --set DEFAULT:SHA1`) would resolve the problem, but this made no change to the above.

**Comment by Druneau** [comment]
Hi!

I'm running into what seems to be the same issue on my Fedora 38 install.

I have a server running Ubuntu and was able to update after fiddling around.  However on my Fedora 38 install I have tried a few things witout success.

The last thing I tried was manually removing the gpg key from rpm by listing then removing it.

To list
# rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'

To remove the key
# rpm -e gpg-pubkey-<KopiaIDFromAboveCommand>

I was expecting DNF to then ask me to re-import the key for the re-added repository but it did not...  So this might not have changed much.

**Comment by donCESAR12345** [comment]
> Hi!
> 
> I'm running into what seems to be the same issue on my Fedora 38 install.
> 
> I have a server running Ubuntu and was able to update after fiddling around. However on my Fedora 38 install I have tried a few things witout success.
> 
> The last thing I tried was manually removing the gpg key from rpm by listing then removing it.
> 
> To list `# rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'`
> 
> To remove the key `# rpm -e gpg-pubkey-<KopiaIDFromAboveCommand>`
> 
> I was expecting DNF to then ask me to re-import the key for the re-added repository but it did not... So this might not have changed much.

For me, this worked, removing the key and trying to install kopia again with `sudo dnf install kopia` succeeded after doing this.

**Comment by jptuv** [comment]
I confirm, 
1st remove the Kopia GPG key,
2nd remove the Kopia package,
3rd install Kopia package

It works on Fedora 38,

Thank's guys for your support

**Comment by Xiol** [comment]
> 1st remove the Kopia GPG key,
> 2nd remove the Kopia package,
> 3rd install Kopia package

Can confirm this worked for me - remove the key, remove the package, reinstall the package and you're prompted to install the GPG key again.

**Comment by hoppke** [comment]
My issue is now gone too, after removing/updating the key and uninstalling my old kopia package the new one installed fine on my fc38.
I'm not sure if it's removing the old package that helped, or that some updates to rpm/dnf arrived in the meantime.
Anyway, it works on my machine now.
