### ISSUE TITLE
Modify the VSS script to exclude “No Writers”

### ISSUE THREAD

**Issue by Athep** [kopia/kopia#3036]
I am using this script for create VSS in Kopia: https://kopia.io/docs/advanced/actions/#windows-shadow-copy

It works fine, but the VSS volume parameters that is created is:

**Persistent, Client-Accessible, No Auto-Release, No Writers, Differential**

I want to exclude the “No Writers” because i want to use the SQL Writer service.

I need help with modifying the script to include all registered writers, or at least the SqlServerWriter. 

Information on the SQL Writer service:

https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-vss-writer-backup-guide?view=sql-server-ver16

**Comment by Athep** [comment]
I have tried, but could not in any way modify the script to include `Writers` when creating a ShadowCopy using the method

`CimMethod -ClassName Win32_ShadowCopy -MethodName Create`

https://learn.microsoft.com/en-us/previous-versions/windows/desktop/vsswmi/win32-shadowcontext

When I tried to set the right `context`, it failed and the ShadowCopy was always created with the `context` `NoWriters` no matter what I did. 

My solution was to rewrite the script to use the Diskshadow utility instead. 

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/diskshadow

**Comment by lupusA** [comment]
The issue is closed, as it was solved by the author. 

Cheers,
