### ISSUE TITLE
"snapshot create" creates two snapshots?

### ISSUE THREAD

**Issue by fhriley** [kopia/kopia#3057]
```
root@nas:~# kopia --version
0.13.0 build: 7f69502bddd6650e7cb7a132291bc54920e58988 from: kopia/kopia
```

I have a cron job that creates a snapshot every night:

`13 1 * * * /usr/bin/kopia snapshot create --all --log-level=info --no-progress /zfs`

And every night, it logs what looks to be like it creating two snapshots:

```
Snapshotting root@nas:/zfs ...
Created snapshot with root kf49bbe04f7bcb00e0474f42f55236d25 and ID dcf55fa5b99f187a1bc8333c7767a22a in 5h39m35s
Snapshotting root@nas:/zfs ...
Created snapshot with root k30b0c795950f0c0e82d6f9ac4de69abd and ID 92b4030916d3a9031a76ebb523de4604 in 2h26m28s
```

This is what it looks like in the GUI:

![Capture](https://github.com/kopia/kopia/assets/153649/bc195546-8a43-434f-b2c9-e59f878ec4da)

Is this expected?

**Comment by fhriley** [comment]
Ah, so I was using it wrong. Thank you! It does seem like it should do a dedup of the sources to backup when both are specified.

**Comment by jkowalski** [comment]
It makes sense to either deduplicate or fail when both `--all` and source paths are provided, since it's not the typical use case.

**Comment by NickIAm** [comment]
I'll give it a shot, seems simple enough.
