### ISSUE TITLE
Host a repository of RPMs and DEBs to simplify onboarding.

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#307]
We can use packagecloud.io or similar to host. I sent an inquiry email asking for a free OSS account.

**Comment by lskillen** [comment]
The peeps at @cloudsmith-io can help too (I work there). You don't need to ask for permission to create an open-source repository, you can just create one and go! :)

**Comment by jkowalski** [comment]
i'll check it out, thanks.

**Comment by jkowalski** [comment]
APT repository is up, let's see if we can get RPM repository as well

http://packages.kopia.io/apt/

**Comment by jkowalski** [comment]
Closed with #600
