### ISSUE TITLE
[Feature] Add support for changing the passphrase of the repository.

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#309]
Background:

https://www.reddit.com/r/golang/comments/ffj2hb/kopia_hits_050_encrypted_deduplicated_and/fjzqaao?utm_source=share&utm_medium=web2x

The caveat is that this requires re-encrypting all replicas of the master block (stored in kopia.repository and in all pack blobs). This obviously is hard, because we potentially need to touch every blob.

One idea would be to embed the recovery blob not in all packs but with some probability, and append some special string to blobs IDs so that we can quickly find them.

**Comment by julio-lopez** [comment]
An option is to not include the master block with the pack blobs at all, and use a separate mechanism for replicating or storing the master blob.

For instance, the master blob (or its replicas) could also be stored offline

**Comment by intdel** [comment]
This has been added as far as I know and can be closed.

**Comment by julio-lopez** [comment]
Added in 0.9
