### ISSUE TITLE
After reinstalling the system, local snapshots were lost and only remote snapshots can be viewed. There is no snapshot menu in the right-click menu of the remote snapshot. How can I perform a snapshot?

### ISSUE THREAD

**Issue by dzhl** [kopia/kopia#3090]
After reinstalling the system, local snapshots were lost and only remote snapshots can be viewed. There is no snapshot menu in the right-click menu of the remote snapshot. How can I perform a snapshot?
local snapshot is empy
![image](https://github.com/kopia/kopia/assets/47837136/119db0ea-b5cd-466f-b966-662c06fa72f2)
remote snapshot has no snapshot button
![image](https://github.com/kopia/kopia/assets/47837136/e87ad251-e1d6-4435-8529-e3ecb96c67e0)
if i create a new local snapshot, it has button
![image](https://github.com/kopia/kopia/assets/47837136/2200400f-d966-408e-8846-cb77009073bd)

**Comment by talios** [comment]
Does your new rebuilt machine present itself with a different hostname/user?

**Comment by lupusA** [comment]
Hi @talios,

Is this solved? Your user and hostname to connect to the repository has probably changed as stated before.

You need to provide the correct name of the user and host when the snapshots were created.

You can move the history and snapshots to a new user also.

Cheers,

**Comment by lupusA** [comment]
Hi @talios,

Is this issue solved?

Cheers,

**Comment by lupusA** [comment]
Hi @dzhl, 

as it can be seen from the screenshots, the host has now a new host name after reinstalling the system. You need to either override the hostname when connecting to the repository or move the old snapshots to that new host. 

You can do it by following the documentation: https://kopia.io/docs/reference/command-line/common/snapshot-move-history/

Cheers,
