### ISSUE TITLE
How to open a web page in a kopia desktop application on Windows？

### ISSUE THREAD

**Issue by flyingnight** [kopia/kopia#3095]
I use the kopia desktop application for Windows.But Kopia's desktop application does not have Chinese.So I hope to be able to open its web interface through a browser, as the browser can translate it into Chinese.
If not, is there any other way to achieve this goal?

**Comment by jan-glx** [comment]
I am novice user, so this might be wrong:
Kopia GUI runs kopia server with the `-random-password` option and does not display that password, so you need to start your own server instance to access the web-gui. The easiest option would be:

1.  In the Kopia GUI, click the yellow `>_` to show the command line equivalent, copy everything up to including the config file. we call this `<kopia_cmd>` now. You can quit the GUI now & would never need it again.
2.  In a shell, run `<kopia-cmd> server start --insecure  --without-password`
3. Open the displayed url (e.g. `http://127.0.0.1:51515`) in a browser of your choice

This will give everyone on your computer access to your data, so you might want to look to the other options mentioned in [this issue](https://github.com/kopia/kopia/issues/880#issuecomment-855291217) and perhaps set-up TSL. 

I agree that it would be nice if the GUI would offer an link to open the web-gui.

**Comment by lupusA** [comment]
Hey @flyingnight, 

if you need further assistence, feel free to ask. 

Cheers
