### ISSUE TITLE
npm audit failures cause CI to fail for all PRs

### ISSUE THREAD

**Issue by ashmrtn** [kopia/kopia#3097]
CI is [failing](https://github.com/kopia/kopia/actions/runs/5362438323/jobs/9729302088?pr=3092#step:7:38) during setup. From some of the logs, it appears that some vulnerable packages are causing `npm audit` to fail which makes `make` fail while setting up the environment thus blocking all PRs. For the current issue, it seems like downgrading `electron-first-run` will solve things

Moving the `npm audit` check to some release workflow may lead to better dev experience as it would allows unrelated PRs to continue to merge while still ensuring kopia releases were blocked until nopde package versions without vulnerabilities were added

**Comment by julio-lopez** [comment]
fixed
