### ISSUE TITLE
Mounting of snapshots with read-write overlay and copy-on-write

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#311]
Currently snapshots can be mounted read-only using `kopia mount`. It would be great to be able to mount a snapshot, but still have ability to mutate its contents, which would create new snapshot under the hood, automatically.

This can be likely implemented today with some clever dual-buffering using overlayfs/unionfs/etc hackery. on top of Kopia mount and few scripts to manage snapshotting and switching of overlays.

**Comment by rjkroege** [comment]
Conceivably this is very naïve but:

* have a `tmpmount` directory in some convenient location. e.g. `~/Library/Application Support/kopia/tmpmount` on MacOS. 
* do a shallow restore of the kopia-mount-ed path to `tmpmount`
* fuse/webdav works as it does now for read access
* writing to the mount point expands the minimum subset of the shallow `tmpmount` tree
* and makes the changes to it
* snapshots on flush
* switches the mount point to the newest snapshot id
* (asynchronously (and optional)) unexpands the `tmpmount` tree to save disk

Seems buildable?

**Comment by rjkroege** [comment]
Aside: I might still write a patch like this at some point.

**Comment by julio-lopez** [comment]
@rjkroege When you are ready, feel free to reference this issue. Thanks.

**Comment by 0cwa** [comment]
I'm interested in developing this so I can sync my android backups (ideally over a WebDAV based SAF I'm thinking).  @rjkroege @jkowalski  Your input would be invaluable #5161

**Comment by rjkroege** [comment]
This remains on my (enormous 😀) todo list but I've not made any progress lately.
