### ISSUE TITLE
Support Backblaze B2 storage

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#312]
Backblaze B2 is popular for its low cost storage amongst `r/datahoarder/`

https://www.reddit.com/r/DataHoarder/comments/ffj5rh/kopia_hits_050_encrypted_deduplicated_and/fjz5twf?utm_source=share&utm_medium=web2x

**Comment by aksdb** [comment]
I have the PR nearly ready. Just a few cleanups left to do. (But I work on this very slowly in off-time ... so ...)

**Comment by jkowalski** [comment]
btw, #373 has changed the PutBlob API to support write gathering, you may need to rebase.

**Comment by jkowalski** [comment]
I've enabled testing on Travis, closing this issue.
