### ISSUE TITLE
Cannot connect to rclone remotes

### ISSUE THREAD

**Issue by lyndhurst** [kopia/kopia#3122]
Hi,
I am trying to set up kopia repositories using the 'rclone remotes' type, but I get the same error message on all the remotes I am trying:

`Connect Error: INTERNAL: internal server error: connect error: unable to write blobcfg blob: PutBlob() failed for "kopia.blobcfg": error writing blob using WebDAV: unable to complete WriteTemporaryFileAndCreateParentDirs despite 10 retries: BLOB not found`

I am new to both softwares, so maybe I am missing something obvious. I am using `kopia-ui` for the set up, and the error occurs after specifying the repository password, the first step providing the remote path works fine.

I am aware of #2990 and #2655, but I do not think it applies to my case, I am using the following versions:
- rclone V1.63.0
- kopia 0.13.0
- kopia-ui 0.12.1

Maybe it is alo worth mentioning that I tried with 3 different remotes, a local network smb drive, a pcloud account and a gdrive.

Thank you for your time.

**Comment by lyndhurst** [comment]
Does anyone know if kopia needs to somehow mount the repositories ? 

If yes, it might be related because I am on an old kubuntu 18 that I am about to re-install and rclone cannot mount the remote either due to `fusermount3` missing dependency...

**Comment by basldfalksjdf** [comment]
How do you have different versions of Kopia and KopiaUI? KopiaUI comes with the Kopia binary, so both the UI and binary should be the same versions.

rclone wont work with KopiaUI before 0.13.0. You may want to consider upgrading.

**Comment by lyndhurst** [comment]
Thank you for pointing that out. I will try reinstalling everything correctly. I will reopen if this is still an issue.
