### ISSUE TITLE
Test Log File Max Total Size failure: corner case for log size

### ISSUE THREAD

**Issue by julio-lopez** [kopia/kopia#3128]
```
    logfile_test.go:193: 
        	Error Trace:	D:/a/kopia/kopia/internal/logfile/logfile_test.go:193
        	Error:      	"19600" is not less than "19600"
        	Test:       	TestLogFileMaxTotalSize/content-logs

=== FAIL: internal/logfile TestLogFileMaxTotalSize (31.97s)
```

**Comment by lupusA** [comment]
Hi @julio-lopez, 

can you share your system and go-version? We had a failed test in the past and it was not reproduceable on an older go-version / other system. Here is my result:

Running tool: C:\Program Files\Go\bin\go.exe test -timeout 30s -run ^TestLogFileMaxTotalSize$ github.com/kopia/kopia/internal/logfile

=== RUN   TestLogFileMaxTotalSize
=== PAUSE TestLogFileMaxTotalSize
=== CONT  TestLogFileMaxTotalSize
=== RUN   TestLogFileMaxTotalSize/cli-logs
**[...]**
--- PASS: TestLogFileMaxTotalSize/cli-logs (0.45s)
=== RUN   TestLogFileMaxTotalSize/content-logs
**[...]**
--- PASS: TestLogFileMaxTotalSize/content-logs (0.45s)
--- PASS: TestLogFileMaxTotalSize (2.63s)
PASS
ok      github.com/kopia/kopia/internal/logfile 2.805s

<img width="331" alt="image" src="https://github.com/kopia/kopia/assets/37236531/3b4a9715-cc8b-4eb1-86fa-350c152c1501">

**Comment by julio-lopez** [comment]
@lupusA This has failed a few times in the kopia workflows. The issue was filed for tracking and triaging. The fix should be simple if you want to take a crack at it.

**Comment by julio-lopez** [comment]
@lupusA The setup is whatever is currently configured in the kopia GH [workflows](https://github.com/kopia/kopia/tree/master/.github/workflows) IIRC, this is not specific to Windows. I recall seeing the failure on other platforms as well. This should be testing bug, not an implementation bug.

**Comment by lupusA** [comment]
Hi @julio-lopez, 

i've looked at the test and do not see any issues with it. From what i've seen, the test creates a directory structure and the fires two commands. After each command, the directory size is compared with the one before the command. 

The test also do not fail every time. In my github workflow runs it was running fine. 

I will try to debug it further. 

Cheers,

**Comment by lupusA** [comment]
There is a errornous run attached:
[run.txt](https://github.com/kopia/kopia/files/12017644/run.txt)

**Comment by julio-lopez** [comment]
@lupusA Thanks for finding a failed run https://github.com/kopia/kopia/actions/runs/5470716647/jobs/9961110427

**Comment by lupusA** [comment]
Hi @julio-lopez, 

i found another failed test (https://github.com/kopia/kopia/actions/runs/5471439825/jobs/9962578801)
I manually calculated the sizes from the test and found the edge case for this specific case. 

Under rare circumstances, the returned log files have the exact same size as provided by the function call. 
[fail.txt](https://github.com/kopia/kopia/files/12018579/fail.txt)
