### ISSUE TITLE
Add Support for RClone

### ISSUE THREAD

**Issue by darthShadow** [kopia/kopia#313]
This can probably be done as either a library or as a repository which should allow kopia to access all the remotes that rclone supports.

Integrating as a library will also allow the fuse part to be handled by rclone and let kopia focus solely on the deduplication, compression etc.

List of rclone supported clouds: https://rclone.org/

**Comment by jaiherro** [comment]
Any updates on this?

**Comment by jkowalski** [comment]
We had some discussions on slack and some way of integrating is slowly emerging. Stay tuned.
