### ISSUE TITLE
[QUESTION] Upload & cache

### ISSUE THREAD

**Issue by DemonAngeX2** [kopia/kopia#3165]
Hello, i want to know if when the snapshot is finished, if in background, data still uploading to remote repository ?

I use Dropbox but they have a limit of upload wich slow the upload.

So the backup is finished in cache but not at all in remote.

Thank you

**Comment by DemonAngeX2** [comment]
Hello, i didn't have answer. 

Please :)

**Comment by julio-lopez** [comment]
Strictly from the point of view of kopia, once kopia returns and says a snapshot has completed, it means that kopia has finished uploading all the data needed for the snapshot and it will not continue to upload any other data in the background. This applies to the core storage providers (Azure Blob, GCS & S3 compatible).

For other storage providers, no real guarantees can be made. It really depends on the storage provider implementation.
