### ISSUE TITLE
Server crash and user list questions

### ISSUE THREAD

**Issue by tekert** [kopia/kopia#3177]
So, here the full list if steps i did to try to understand what happens:
i know this is long but i wanted to show the full steps.
This test was from windows server.

**SERVER SIDE:**

`kopia repository create filesystem --create-only --path="E:\Backups\kopia\test_server_repo" --description="<desc>" --block-hash=BLAKE3-256-128 --ecc=REED-SOLOMON-CRC32 --ecc-overhead-percent=1 --enable-actions`

`kopia server start --tls-cert-file C:\Backups\kopia-administrator-conf\keys\my.cert --tls-key-file C:\Backups\kopia-administrator-conf\keys\my.key --address 0.0.0.0:51518 --server-control-username admin --server-control-password admin --config-file="C:\Backups\kopia-administrator-conf\test.config" --enable-actions --insecure --without-password`

`kopia --config-file=C:\Backups\kopia-administrator-conf\test.config repository status`
```
Config file:         C:\Backups\kopia-administrator-conf\test.config

Description:         My Repository
Hostname:            xenoserv
Username:            Administrator
Read-only:           false
Format blob cache:   15m0s

Storage type:        filesystem
Storage capacity:    2 TB
Storage available:   833.9 GB
Storage config:      {
                       "path": "E:\\Backups\\kopia\\test_server_repo",
                       "dirShards": null
                     }

Unique ID:           b92d50e352ca1ab0b0e60af2fe28ceee234da9e55e50a0e8001c7e771bdefffc
Hash:                BLAKE3-256-128
Encryption:          AES256-GCM-HMAC-SHA256
Splitter:            DYNAMIC-4M-BUZHASH
Format version:      3
Content compression: true
Password changes:    true
Max pack length:     21 MB
Index Format:        v2

Epoch Manager:       enabled
Current Epoch: 0

Epoch refresh frequency: 20m0s
Epoch advance on:        20 blobs or 10.5 MB, minimum 24h0m0s
Epoch cleanup margin:    4h0m0s
Epoch checkpoint every:  7 epochs

```
`kopia --config-file=C:\Backups\kopia-administrator-conf\test.config server user list`
> <empty response>

Lets add users:
`kopia server user add tekert@xenotek --config-file=C:\Backups\kopia-administrator-conf\test.config`
```
Enter new password for user tekert@xenotek:  <same as repo password>
Re-enter new password for verification:  <same as repo password>

Updated user credentials will take effect in 5-10 minutes or when the server is restarted.
To refresh credentials in a running server use 'kopia server refresh' command.

```
Question: Whats the difference between repo password and users password?
Mean, why does the repo password exists if there is a control password?

`kopia server refresh --config-file="C:\Backups\kopia-administrator-conf\test.config" --address="https://localhost:51518" --server-cert-fingerprint=<fingerprint> --server-control-username=admin --server-control-password=admin`
<empty response>

**CLIENT SIDE:**

`kopia repository connect server --url https://192.168.2.11:51518 --server-cert-fingerprint <sha> --config-file="C:\Backups\kopia-tekert-conf\test.conf"`
```
Connecting to server 'https://192.168.2.11:51518' as 'Tekert@xenotek'...
Enter password to open repository: <enter repo password>

ERROR failed to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = Unavailable desc = error reading from server: read tcp 192.168.2.3:53305->192.168.2.11:51518: wsarecv: An existing connection was forcibly closed by the remote host.: EOF
ERROR error connecting to API server: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = Unavailable desc = error reading from server: read tcp 192.168.2.3:53305->192.168.2.11:51518: wsarecv: An existing connection was forcibly closed by the remote host.: EOF
```

**SERVER:**

```
FATAL crash on the server:
2023/07/26 09:27:44 http: TLS handshake error from 127.0.0.1:64215: remote error: tls: bad certificate
2023/07/26 09:27:44 http: TLS handshake error from 127.0.0.1:64216: remote error: tls: bad certificate
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x196878a]

goroutine 1241 [running]:
github.com/kopia/kopia/internal/server.(*Server).authenticateGRPCSession(0xc0005fc9c0, {0x2907138, 0xc000510de0}, {0x285bbeaa120, 0xc0000e2160})
        E:/Sources/go/repos/kopia/internal/server/grpc_session.go:63 +0x1aa
github.com/kopia/kopia/internal/server.(*Server).Session(0xc0005fc9c0, {0x290dd70, 0xc000574230})
        E:/Sources/go/repos/kopia/internal/server/grpc_session.go:85 +0x153
github.com/kopia/kopia/internal/grpcapi._KopiaRepository_Session_Handler({0x224b4e0?, 0xc0005fc9c0}, {0x290a660?, 0xc0004fd2c0})
        E:/Sources/go/repos/kopia/internal/grpcapi/repository_server_grpc.pb.go:98 +0x9f
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000344b40, {0x290e9f8, 0xc0003d95e0}, 0xc000614480, 0xc000355e00, 0x32b9120, 0x0)
        E:/Sources/go/sdk/Tekert/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:1631 +0x1384
google.golang.org/grpc.(*Server).handleStream(0xc000344b40, {0x290e9f8, 0xc0003d95e0}, 0xc000614480, 0x0)
        E:/Sources/go/sdk/Tekert/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:1718 +0x9f0
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        E:/Sources/go/sdk/Tekert/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        E:/Sources/go/sdk/Tekert/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:957 +0x18c
```

Lets try again:

**SERVER:**
> init server:

`kopia server start --tls-cert-file C:\Backups\kopia-administrator-conf\keys\my.cert --tls-key-file C:\Backups\kopia-administrator-conf\keys\my.key --address 0.0.0.0:51518 --server-control-username admin --server-control-password admin --config-file="C:\Backups\kopia-administrator-conf\test.config" --enable-actions --insecure --without-password`

**CLIENT:** (use lowercase, why only lowercase?)

`kopia repository connect server --url https://192.168.2.11:51518 --server-cert-fingerprint <sha> --config-file="C:\Backups\kopia-tekert-conf\test.conf" --override-hostname=tekert --override-username=xenotek`

_Same fatal error._

Try again:

**SERVER:**
> Start server again.

**CLIENT:**
`kopia repository connect server --url https://192.168.2.11:51518 --server-cert-fingerprint <sha> --config-file="C:\Backups\kopia-tekert-conf\test.conf" --override-hostname=tekert --override-username=xenotek **--no-grpc**`

SUCCESS

So.. Google RPC is crashing?
Why not just use the API --no-grpc?
what are the tradeoffs?

The confusing part now...
The server backups as:
`Administrator@xenoserv`

This user doesn't exist.
So.. a repo can be a server repo and a normal repo at the same time?
Lets call it local user.

More confusing parts:
Locally, I can connect as any user to a repo as long as i have the repo password.
But i can't list users.. if some asdhjjkhsdgf@dflhjslfsd users backups to a repo how do i retrieve the files without knowing the user?

Lets try this:

**SERVER:**
Open browser to https://localhost:51518
use the repo password, login as Administrator o any user you want from the console and use the config.

> Snapshot something from the UI.

**CLIENT** (I want to see that backup)
I will connect as Administrator with a repo password:
`kopia repository connect server --url https://192.168.2.11:51518 --server-cert-fingerprint <sha hash> --config-file="C:\Backups\kopia-tekert-conf\test2.conf" --override-hostname=xenoserv --override-username=Administrator **--no-grpc**`
`Enter password to open repository: <repo password>`
Connected...

Lets open a server UI now.
`kopia server start --config-file=C:\Backups\kopia-tekert-conf\test2.conf --address="http://127.0.0.1:51516" --insecure --without-password`

I can see the Administrator backups!

So, why do i need to setup local users if i can just connect like this.

Lets try:
**CLIENT:**

`kopia repository connect server --url https://192.168.2.11:51518 --server-cert-fingerprint <sha hash> --config-file="C:\Backups\kopia-tekert-conf\test3.conf" --override-hostname=any --override-username=any --no-grpc`

`kopia server start --config-file=C:\Backups\kopia-tekert-conf\test3.conf --address="http://127.0.0.1:51516" --insecure --without-password`

Visit http://localhost:51516/snapshots

Snapshot something...
All seems ok.

So this is like connecting to a filesystem repo locally with different users but this time with a proxy.
Again, im confused about the server user list why does it exists? its just for ACL?
If it is just for ALC, why not doc or group this concept as local repo users, and remote users.

Also, why crash the server when grpc is enabled.

**Comment by lupusA** [comment]
Hi @tekert,

you cannot run a repository server with TLS configured with the flag ` --insecure`. That's not allowed and will result in a crash probably. Also, if you would like to have a htaccess like login for the server, you should remove `--without-password` and provide a proper username and password for the server.

By doing this, you can login as a _admin_ and manage all the client backups. When the user logs in, he can only see his backups. Not the one from the other users.

When maintaining a repository server, each user have their own password and username. So you can and should provide a different password than the repository password.

Have you checked the documentation on repository servers yet?

Cheers,

**Comment by tekert** [comment]
Yes, I wanted to proxy backups to central server who then syncs the repos everywhere.
The idea was to run 2 to 3 of these proxy kopia servers on the central server. Each one for one user.
All is inside a VPN or secure LAN, there is no need to provide ACL, since each proxy has only one user.

The crash for google RPC is because --insecure? --no-grpc solved this either way.

Now i changed my aproach and have each client backup locally and then sync to the server (same thing i think, except each client has to reserve space for the backup)

**Comment by tekert** [comment]
Tested it again.
Yep, gRPC needs users added with `kopia server user add`
without --insecure the server doesn't crash, it just reports access denied if the user doesn't exists.
Adding a user and using --override-hostname=<machinename> --override-username=<losercaseuser>
works, because the default username has caps... (so any backups already in the repo for a user with caps can't be accessed remotely through kopia server grpc?)

**Comment by lupusA** [comment]
Hey @tekert ,

For your setup, the best solution would be to run one Kopia server instance as a repository server and add three users for it. Each client then push their snapshots to the server. 

Even without ACL, each user cannot see the other backups when running a repository server. You then need to login with these user and hostnames. 

To change the ownership of the existing snapshots, see https://kopia.io/docs/reference/command-line/common/snapshot-move-history.

Can we close the issue?

Cheers,

**Comment by tekert** [comment]
move-history was useful, yep thanks for the tips.
