### ISSUE TITLE
[Bug] Ignoring Files and Folders: Multiple folders "**" wildcard not working correctly

### ISSUE THREAD

**Issue by ManiMatter** [kopia/kopia#3180]
I have a folder structure like this:
/appdata/vscode/config/extensions/

Each folder has multiple subfolders and files in them.
What I want to backup is nothing but one file that is contained in above folder, called "extensions.json".

I am successful in doing so with the following ignore settings:
```
/appdata/vscode/*/*/*
!/appdata/vscode/config/extensions/extensions.json
```

What does not work is this setting:
```
/appdata/vscode/**/*
!/appdata/vscode/config/extensions/extensions.json
```

I claim that this is a bug, since the [Kopia Documentation](https://kopia.io/docs/advanced/kopiaignore/#supported-patterns) states:

> 

** | Double Wildcard that matches zero or multiple directories
-- | --

I would have therefore that the two configurations pasted above work identically.
Or am I barking up the wrong tree here? :)

**Comment by tekert** [comment]
It follow the gitignore rules (except empty dirs are included always)

`/appdata/vscode/**/*`
is telling the filter to ignore eveything under /appdata/vscode/  (the `/*` at the end is doen't matter, the `/**` before already ignores eveything)

`!/appdata/vscode/config/extensions/extensions.json`
can't add a file or folder if the parent folder was excluded (the `/**` rule above took care of that)

**Comment by ManiMatter** [comment]
Thank you for the feedback.
For me, the behavior seems counterintuitive.

The way I interpret the following two codes, both should remove all files:
First code (can still exclude files with this)
`/appdata/vscode/*/*/*`

Second code (cannot exclude files with this)
`/appdata/vscode/**/*`

However, for some reason, with the first code, I can still add the following line, to prevent that file from being excluded.
But I can't with the second code. And I don't understand why that's the case. 
`!/appdata/vscode/config/extensions/extensions.json`

Any explanation welcome :)

**Comment by tekert** [comment]
Sorry my explanation was lacking.

"It is not possible to re-include a file if a parent directory of that file is excluded."

`/**` matches everything, so negating a child whose parent is ignored can't be done.

**Comment by ManiMatter** [comment]
Thank you tekert for the explanation.

Personally, I'd find it helpful if that would work (ie. that you can re-include a file after a parent has been excluded). 

The way I could see how this would work is that the ignore logic applies the exclusions in an ordered fashion (top down), and if something is excluded from the exclusion in  a subsequent step, it is then re-included.

Example:
Folder looks like this:
/a/b/c/
- FileX
- FileY
- FileZ
- SubfolderE

Exclusion Logic looks like this:
/a
!**/fileX
!/a/b/c/SubfolderE

I would expect here that everything in /a is first ignored; then all files named "fileX" in anywhere within /a is retained, and also the SubfolderE is retained.

That would make it extremely easy to be very specific on the data I want to actually backup, reducing storage consumption...

**Comment by lupusA** [comment]
Hi @ManiMatter,

What about `/appdata/vscode/**/
!/appdata/vscode/config/extensions/extensions.json` ?

I able to test this next week, but maybe the second wildcard on the folder causes in issue. Can you check if this makes a difference?

Cheers,

**Comment by ManiMatter** [comment]
Super, looking forward to your test results! Cheers

**Comment by lupusA** [comment]
Hi @ManiMatter, 

i was able to test this with the following directory structure:

```
C:\Users\user\a\.kopiaignore
C:\Users\user\a\filename.txt
C:\Users\user\a\fileX
C:\Users\user\a\FolderA.txt
C:\Users\user\a\listing.txt
C:\Users\user\a\b\fileX
C:\Users\user\a\b\FolderB.txt
C:\Users\user\a\b\c\FolderC.txt
C:\Users\user\a\b\c\SubfolderE\SubfolderE.txt
C:\Users\user\a\b\SubfolderE\SubfolderE.txt
```

What you want to achieve is possible. See the following ignore rules:
```
# Ignores every file within a and it's subfolders
**/*.*
# Preserve fileX everywhere
!**/fileX
# Preserve .kopiaignore
!.kopiaignore
# Preserve SubfolderE everywhere
!/**/SubfolderE/**
```

<img width="479" alt="image" src="https://github.com/kopia/kopia/assets/37236531/d061f6a7-777c-4467-b16a-7e6839951a7d">

Here is the snaphshot in `Kopia`:

<img width="483" alt="image" src="https://github.com/kopia/kopia/assets/37236531/8b0fc01d-1004-4bfc-ab0b-7d76d5184be5">

<img width="489" alt="image" src="https://github.com/kopia/kopia/assets/37236531/6db7837e-0a5d-44c3-bff8-d541272b29e7">

<img width="488" alt="image" src="https://github.com/kopia/kopia/assets/37236531/75a1dbc4-d78b-479e-bccd-dfaed1629a0c">

<img width="487" alt="image" src="https://github.com/kopia/kopia/assets/37236531/7747a152-0d2d-4948-9c82-14d55e30065f">



Can you check and validate?

Cheers,

**Comment by ManiMatter** [comment]
Hi,

thank you for taking the time and testing this.

What for me did the trick is what you described: "**/*.*".
This has the advantage compared to "/*/*/*" that I do not need to know how many levels of subfolders I have to include, and then I can re-include those items (folders & files) that I want to backup.

Disadvantage: Many empty folders; would be nice if there was a way to achieve the same outcome, but without all the empty folders being backed up. From your description it sounds that this is not possible.

Cheers

**Comment by lupusA** [comment]
Hey, 

At least imo I think that it is not possible. Anyways, there is a feature request to exclude empty folders, see #3146 

Please close this issue, if it is working for you now as workaround.

Cheers

**Comment by budiqx** [comment]
i wish, Kopia will be able to recognize negation, the way OP (@ManiMatter ) wanted

temporary solution (https://github.com/kopia/kopia/issues/3180#issuecomment-1659712329) gives me a lot of empty folders.  thanks @lupusA for the tips.  it's the best solution, given the limitations of the current Kopia

**Comment by tekert** [comment]
> I can't get this to work, I'm doing this:
> 
> ```gitignore
> /var/
> !/var/lib/docker/volumes/some-volume-name-1/
> ```
> 
> But the volume directory is not included in the snapshot

Sadly since kopia has many quirks with it file inclusion (not ideal in a backup software), is you ignore a pared folder but what subfolder files yo have to un ingnore every single subfolder like this:

```gitignore
/var/
!/var/lib
!/var/lib/docker
!/var/lib/docker/volumes
!/var/lib/docker/volumes/some-volume-name-1/
```

**Comment by tekert** [comment]
> @tekert I tried that but it didn't work, but if I un-ignore the parent folders won't Kopia include everything inside? If I un-ignore /var/lib wouldn't Kopia include everything inside?

Sorry, i forgot to unignore !/var/   that only unignores folders, for everything inside the folder you have to use /* and for everything including subfolders /** (all of them)

**Comment by tekert** [comment]
Forgot to example also if you ignore only a subfolder, like this:
/var/

then if you unignore !/var/  (mandatory if you want enything inside /var/ then everyhing inside will be whitelisted because if was never ignored. Example:
```gitignore
/var/  #missing the **
!/var/
!/var/lib/
!/var/lib/docker/
!/var/lib/docker/volumes/
!/var/lib/docker/volumes/some-volume-name
```gitignore
Then !/var/ will include everything inside already, there is no need for the other !/var/....

**Comment by guidorice** [comment]
A similar question for how to accomplish an inclusion-list type of pattern. This is a  common  use case e.g. with docker ignore, git ignore, or similar type of config files.

 For example, on my MacOS `~/Library/` contains 98 subdirectories. I want to include only `Library/Preferences`  but ignore everything else under `Library`. How to (concisely) express that using the `.kopiaignore` file?

I would expect this to work, but the Preferences folder is not included, according to `kopia snapshot estimate /Users/guidorice`.

```
/Library/
!/Library/Preferences
```

**Comment by tekert** [comment]
> A similar question for how to accomplish an inclusion-list type of pattern. This is a common use case e.g. with docker ignore, git ignore, or similar type of config files.
> 
> For example, on my MacOS `~/Library/` contains 98 subdirectories. I want to include only `Library/Preferences` but ignore everything else under `Library`. How to (concisely) express that using the `.kopiaignore` file?
> 
> I would expect this to work, but the Preferences folder is not included, according to `kopia snapshot estimate /Users/guidorice`.
> 
> ```
> /Library/
> !/Library/Preferences
> ```


"It is not possible to re-include a file if a parent directory of that file is excluded."

so, exclude only what is inside Library, like this:
`/Library/**`

then selectively whitelist folders and files on those folders or everything.
for your case:
```
!/Library/Preferences/  # whitelist the folder so we can look inside
!/Library/Preferences/** # now whitelist everyhing.
```

also

`!/Library/Preferences  # this looks for the file named "Preferences" not a dir`
for dirs it has to end with "/"

Another example is:
```
# /**
# !/**/
```
this whitelist only dirs and not the files inside every dir.
