### ISSUE TITLE
Server can connect local reposity but client cant not connect  local reposity

### ISSUE THREAD

**Issue by tianchaopow** [kopia/kopia#3182]
Server:
[root@kopia ~]# kopia repository connect filesystem --path=/mnt/kopia/
Enter password to open repository: 

Connected to repository.

NOTICE: Kopia will check for updates on GitHub every 7 days, starting 24 hours after first use.
To disable this behavior, set environment variable KOPIA_CHECK_FOR_UPDATES=false
Alternatively you can remove the file "/root/.config/kopia/repository.config.update-info.json".

[root@kopia ~]# ^C
[root@kopia ~]# kopia server user list
administrator@officer
chfs@whread
xz@smb
ywb@smb
[root@kopia ~]# ^C
[root@kopia ~]# openssl x509 -in ~/my.cert -noout -fingerprint -sha256 | sed 's/://g' | cut -f 2 -d =
FD4DBDE16E912352AF51074313E5E54E57987C88C148177B2438AB0709CA177D

Client
[root@chfs ~]# kopia repository connect server --url https://192.168.30.235:51515 --server-cert-fingerprint FD4DBDE16E912352AF51074313E5E54E57987C88C148177B2438AB0709CA177D --override-username=chfs --override-hostname=whread  
Connecting to server 'https://192.168.30.235:51515' as 'chfs@whread'...
Enter password to open repository: 

ERROR failed to open repository: unable to establish session for purpose=: error establishing session: Session(): rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.30.235:51515: connect: connection refused"
ERROR error connecting to API server: unable to establish session for purpose=: error establishing session: Session(): rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.30.235:51515: connect: connection refused"

**Comment by lupusA** [comment]
Hi @tianchaopow ,

Can you post the command the server was started with?

Cheers,

**Comment by tianchaopow** [comment]
I was check the kopia process not up,then i start up kopia services the connect was normal



***@***.***
 
From: Christoph Anderson
Date: 2023-07-31 11:48
To: kopia/kopia
CC: telecom; Mention
Subject: Re: [kopia/kopia] Server can connect local reposity but client cant not connect local reposity (Issue #3182)
Hi @tianchaopow ,
Can you post the command the server was started with?
Cheers,

**Comment by lupusA** [comment]
Hi @tianchaopow, 

alright. Glad that it worked. I am closing this issue. If you have further questions related to this issue, let me know. 

Cheers,
