### ISSUE TITLE
Document prometheus metrics feature

### ISSUE THREAD

**Issue by tynsh** [kopia/kopia#3189]
There currently does not seem to be any documentation regarding the option to expose prometheus metrics. It would be nice to have a mention of --metrics-listen-addr and related flags in the docs.

**Comment by julio-lopez** [comment]
This is an internal "interface", subject to be changed at any point and thus not documented on purpose. For example, while it currently uses Prometheus, in the future it _may_ use a different format and protocol for exposing those.

**Comment by AnderssonPeter** [comment]
In case anyone needs a simple dashboard and some alert manager rules i created some https://github.com/AnderssonPeter/kopia-grafana/tree/main (They are a bit simplistic but better than nothing)

**Comment by rdoering** [comment]
I would like to see such an interface publicly.
