### ISSUE TITLE
[Feature Request]: Automatically run overdue snapshots

### ISSUE THREAD

**Issue by DarkArc** [kopia/kopia#3197]
Currently, Kopia doesn't seem to do any "cathcup" snapshots if they're overdue. 

# Observed Behavior

In other words, if your backups run at night at 1am, and you have you computer off when the snapshot should've kicked off, Kopia will not run until 1am the next day.

# Expected Behavior

Kopia should (at least optionally) immediately start any overdue snapshots that missed their run window when the computer is booted.

# Rational

Nightly backups are often optimal in terms of avoiding impacting users. However, nightly backups in desktop and laptop form factors can easily result in a user missing a backup if their computer happens to not be on at the "right" time for an unexpectedly long period.

This can in theory even affect more frequent uses if you get "unlucky" (as your device is regularly being put to sleep/shutdown) and thus isn't online "on the hour", when the various backup(s) are scheduled to run.

Kopia having a nice GUI client positions itself as a great easy to use solution for these sort of "desktop"/"laptop" form factors. However, the lack of any kind of "catch up" makes this quite a dangerous option; particularly when deploying to users that aren't as tech-savy and might not think to check in on the status of their backups.

**Comment by lupusA** [comment]
Hi @DarkArc ,

Can you post some information about your setup ? I am running a repository server with a schedule of 12 hours. When I start my computer, Kopia immediately creates a new snapshot when it is overdue. 

Cheers,

**Comment by DarkArc** [comment]
I have a time of day schedule as noted (1am):
![image](https://github.com/kopia/kopia/assets/778012/3c68a75d-650a-4be8-a048-fc09b7237346)

**Comment by lupusA** [comment]
Hi @DarkArc ,

Would you mind to set the schedule to a fix 6 or 12 hours period instead of a fix time of day and test again? Maybe a schedule with a fix time of day is not working correctly.

Cheers,

**Comment by DarkArc** [comment]
Yes, it looks like Kopia correctly handles this for 12 hour snapshots, but not time based snapshots.

**Comment by DarkArc** [comment]
Closing in favor of https://github.com/kopia/kopia/issues/3319
