### ISSUE TITLE
Backup not displaying jpegs correctly

### ISSUE THREAD

**Issue by andyh1213** [kopia/kopia#3204]
I have a directory of jpegs that I am trying to backup, and no matter what the settings I select for compression etc, I can only open about half of them if I mount a snapshot for browsing. 

I am on windows using KopiaUI 0.13

If I actually restore them to a directory, they open fine and look binary identical to my source.

**Comment by andyh1213** [comment]
Apparently this is a Windows WebDAV issue.

By default, WebDAV will only let you view/save files under 50MB so that's why my files weren't loading. This particular snapshot had jpegs with some under and some over 50 MB and some over 100. Anything under 50MB will preview fine but over would fail.

Setting this value to the max of 4294967295 (decimal) and restarting the WebClient Service (or just reboot) fixed the issue. HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WebClient\Parameters\FileSizeLimitInBytes 

https://www.wintips.org/fix-error-0x800700df-the-file-size-exceeds-the-limit-allowed-and-cannot-be-saved-in-sharepoint-webdav/

Not exactly a Kopia issue, but it will cause issues trying to restore large files via mounting the snapshot

**Comment by julio-lopez** [comment]
Thanks for following up on the findings.
