### ISSUE TITLE
Skip files marked as to be not saved

### ISSUE THREAD

**Issue by wmark** [kopia/kopia#322]
On Linux, attribute `d` marks items that shall be skipped. Have *kopia* recognize it on visiting the local filesystem to save time and space.

For example, my ‘downloads’ directory is full of such items, as is ‘Music’ and ‘Videos’ (no need to descent).

To clarify, these are not “extended attributes” aka “user attributes” (hence package github.com/pkg/xattr is the wrong one to use), but “file attributes” aka “file flags” as in `chattr`.
Windows has an equivalent set of those attributes, hence the resulting visitor function is better not inlined but placed in a separate file `*_linux.go`.

**Comment by jkowalski** [comment]
interesting idea, I think we can add a policy option to ignore files marked as `d`. Or would it make sense to always obey it?

**Comment by wmark** [comment]
Do always skip: Nobody sets it unintentionally, unlike perhaps files named like `foo~`.

**Comment by ntolia** [comment]
Policy option, please. There are a number of scenarios where I would personally want to use kopia to gather this up.

**Comment by jkowalski** [comment]
How about we make it a a default global policy option to skip those files but it can be overridden globally or per host/user?

**Comment by ntolia** [comment]
Honestly, the `d` flag is legacy from the dump era. If we really want to skip files, this should not be done as magic but instead via more user-visible features such as include or exclude filters. This can be very confusing for an end-user for something most folks will be unaware of.

I would support filters in the same way we have thought about compression or other transforms.

**Comment by wmark** [comment]
This doesn't replace any such filters.

Anyway OT, I didn't find a good standalone implementation of `chattr` in Go, but here is Canonical's as inspiration:
https://github.com/snapcore/snapd/blob/c370566a2cfac11254cb47e2152bd7b2aa7e62fc/osutil/chattr.go
