### ISSUE TITLE
Middle click to open snapshot in a new window is gone

### ISSUE THREAD

**Issue by gerroon** [kopia/kopia#3233]
Hi,

I used to be able to middle click on a snapshot to open it in a new window, this was super handy and useful. It seems like it open an empty window now. Is there a way to bring it back?

I am using 12.1 on Win 11

thanks

**Comment by lupusA** [comment]
Hi, 

on Version 0.14.1 it is working on windows 11. I am not sure if it was working on 0.12.1. 
It is even working in kopia-ui. 

Cheers,

**Comment by lupusA** [comment]
Hi @gerroon,

Would you try again with the latest version - in case you want to upgrade?

Cheers,

**Comment by gerroon** [comment]
The new version seems to work, thansk

**Comment by lupusA** [comment]
I am closing this issue as it seems to be resolved. If not please reopen.
Cheers,
