### ISSUE TITLE
`TestSnapshot*` fails because `fshasher` compares using "directory sort order" which may differ for restored vs source

### ISSUE THREAD

**Issue by ppenguin** [kopia/kopia#3246]
While working on a new `kopia` repo backend, I noticed that existing tests fail for me in my `gitlab-ci` and also locally when executing `make ci-tests`: total 4 test failures related to `TestSnapshot*`

```
$ go test -timeout 30s -run ^TestSnapshotDeleteRestore$ github.com/kopia/kopia/tests/end_to_end_test -v

...

    snapshot_delete_test.go:241:
                Error Trace:    /home/jeroen/devel/g1tlab/r/int3p/kopia/tests/end_to_end_test/restore_test.go:149
                                                        /home/jeroen/devel/g1tlab/r/int3p/kopia/tests/end_to_end_test/snapshot_delete_test.go:241
                Error:          Not equal:
                                expected: []byte{0xeb, 0xee, 0x5e, 0x18, 0x5d, 0x21, 0xe6, 0x92, 0x4e, 0x15, 0x49, 0xfb, 0x70, 0x69, 0xd8, 0x4c, 0x43, 0xc9, 0x75, 0x4b, 0x5d, 0xa6, 0x11, 0xa7, 0x89, 0x
80, 0x6f, 0x4d, 0x53, 0x94, 0x27, 0x56}
                                actual  : []byte{0xcb, 0x1b, 0x64, 0xbd, 0x6b, 0xd7, 0xc8, 0x3f, 0x6b, 0x65, 0x92, 0xf8, 0xa4, 0x57, 0x6, 0xe6, 0xed, 0x3f, 0x3, 0x26, 0xc5, 0x2d, 0x1a, 0x75, 0xcd, 0xdf
, 0x46, 0xee, 0xcc, 0x98, 0x5c, 0xcd}

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,4 +1,4 @@
                                 ([]uint8) (len=32) {
                                - 00000000  eb ee 5e 18 5d 21 e6 92  4e 15 49 fb 70 69 d8 4c  |..^.]!..N.I.pi.L|
                                - 00000010  43 c9 75 4b 5d a6 11 a7  89 80 6f 4d 53 94 27 56  |C.uK].....oMS.'V|
                                + 00000000  cb 1b 64 bd 6b d7 c8 3f  6b 65 92 f8 a4 57 06 e6  |..d.k..?ke...W..|
                                + 00000010  ed 3f 03 26 c5 2d 1a 75  cd df 46 ee cc 98 5c cd  |.?.&.-.u..F...\.|
                                 }
                Test:           TestSnapshotDeleteRestore
                Messages:       restored directory hash does not match source's hash

...
```

If I compare the `/tmp/...` dirs for `source` and the restore target by recursive `md5sum` they are identical.

1. Shouldn't the test compare the source/target trees after sanitizing (cutting off) the different "prefix" of the actual tree? (I.e. for that `fshasher.Hash` should be (optionally?) able to interpret the root path relatively (without absolute root component).
2. Any idea why this issue hasn't popped up upstream?

**Comment by julio-lopez** [comment]
The seems to be something in your setup. What OS and file system are you using? is this running in a containerized environment?

I cannot reproduce it.

**Comment by ppenguin** [comment]
BTW: the test (`make ci-tests`) failed in the same way on my dev env (NixOS) and in self-built debian-based docker container (running in a self-hosted `gitlab-runner`) for go-builds.

**Comment by julio-lopez** [comment]
@ppenguin Thanks for reporting back.

`fshasher` is only used for testing.

We recently ran into this issue on ARM Linux, Jarek fixed the issue for the test.

https://github.com/kopia/kopia/pull/3179/commits/9c5a7d5b1cc21b9b85b0839346c596ab54f8a607#diff-0114849b97f4e91b997da9d0d0808837da8790e4e257810f8b0fb07469c6ad6cR119

**Comment by julio-lopez** [comment]
@ppenguin Please close if this answers your question. Thanks.

**Comment by ppenguin** [comment]
@julio-lopez Thanks! I haven't tested the commit you linked yet, but from a quick glance that thould solve it. Closing for now. 

I'll keep the `IterateEntriesSorted` it in a separate feature branch just in case, might come in handy in the future.
