### ISSUE TITLE
[Question] Is it not possible to create a "Per-User" policy via the Kopia UI (Windows)??

### ISSUE THREAD

**Issue by abjoseph** [kopia/kopia#3257]
Version: 0.13.0
OS Platform: Windows
Repository: S3

As the title says, it appears that I'm only able to create policies with a specific path or edit the Global Policy but when I navigate to the Per-User and Per-Host policy sections, it doesn't give me an option to create one. 

Is this intentional or are there any plans to add this functionality?

![image](https://github.com/kopia/kopia/assets/26844547/638698e3-84c1-4706-b49e-96791fe2bd56)

**Comment by lupusA** [comment]
Hi @abjoseph 

It is just a filter of policies to show global, per-user, per-host policies etc. However, it seems that the filter is not working correctly. Let me dig into that. 

Cheers,

**Comment by lupusA** [comment]
Hi @abjoseph, 

you can set per host policies using e.g. the command line:

```
C:\Users\user>C:\Users\user\Desktop\GoProjects\kopia\__debug_bin.exe --config-file=C:\Users\user\kopia_config\config.yml policy set "@laptop-ca" --add-ignore "b"
```
<img width="1023" alt="image" src="https://github.com/kopia/kopia/assets/37236531/288b7bd2-8ab8-4bba-957e-6286cb30425c">

Cheers,

**Comment by lupusA** [comment]
Hi @abjoseph, 

it seems that it is not possible to set per-user policies only. Via the CLI you can only set ```@host```, ```username@host```, or ```username@host:path``` policies. I guess we can remove the setting then with an upcoming PR.

I am closing this issue. 

Cheers,  

FYI: @jkowalski
