### ISSUE TITLE
Add testing for eventual consistency behavior of blob storage providers

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#326]
Idea: we can write a blob.Storage wrapper for testing that intentionally delays underlying writes and deletes with some externally configurable probabilities and latencies, we an then write a stress test that uses filesystem provider + this wrapper and have behavior similar to S3.

**Comment by ntolia** [comment]
Minio has an unadvertised s3-to-s3 gateway that we might be able to leverage for this.

**Comment by julio-lopez** [comment]
This can also be implemented as a provider at the storage layer that is used only for testing, similar to the `blobtesting` package.
