### ISSUE TITLE
Entry Point Not Found Discard Virutal Memory when installing 

### ISSUE THREAD

**Issue by NaQu2003** [kopia/kopia#3266]
I am trying to install github desktop app on windows 8.1 but i have the problem :
Entry Point Not Found Discard Virutal Memory

**Comment by lupusA** [comment]
Hi, 

Kopia UI now requires windows 10 and above. There was an electron update that requries it. 
From the release notes:

_KopiaUI no longer supports Windows 7 or 8 due to upstream breaking change_

See https://github.com/kopia/kopia/issues/2923

Cheers,
