### ISSUE TITLE
Allow safe GC and snapshot create operations concurrently

### ISSUE THREAD

**Issue by julio-lopez** [kopia/kopia#328]
Currently, snapshot create and GC must be serialized to prevent races.

Related to #76

**Comment by tobiasBora** [comment]
Sorry to hook here, but just wanted an official corfirmation: is kopia always safe to use concurrently with multiple clients with any backend?

**Comment by sfc-gh-jkowalski** [comment]
Yes. Snapshots and GC can now run concurrently.

**Comment by tobiasBora** [comment]
Great, thank you! Would be cool to add it in the doc (unless I missed it)
