### ISSUE TITLE
0.14.0 regression, Windows: bad visual banding in UI, when using Windows dark mode

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [kopia/kopia#3316]
Thank you for the new release.

In that new release, I see the following, which I did not see in 0.13.

![image](https://github.com/kopia/kopia/assets/47056543/5f137beb-898b-4dab-baab-e0c3263d91d5)

The text with a white background is hard to read, especially in those cases where the foreground colour is grey. Also, the general effect is ugly.

Windows 10 Pro - 22H2 (2009: 19045), with all 'dark' options enabled. In Kopia itself, I have the dark theme enabled.

**Comment by jkowalski** [comment]
This is already fixed. Will be released in 0.14.1 momentarily

**Comment by LinuxOnTheDesktop** [comment]
I downloaded and installed the new version. The tray icon did not respond for a while and once it did respond I saw an empty Kopia window for a few seconds. But if those problems prove persistent they that is an issue different to the that I reported. So, closing.
