### ISSUE TITLE
KopiaUI logging policy editing incorrect

### ISSUE THREAD

**Issue by bilderbuchi** [kopia/kopia#3340]
There seems to be a logic error when editing the Cache Hit and Cache Miss entries in a logging policy. They seem to be linked (always seem to change in lockstep) and the "effective" column of Cache Miss never seems to update.

Screenshot of a snapshot policy (where both entries initially were on "inherit from parent") directly after changing the "Cache Miss" Defined value to 5:
![image](https://github.com/kopia/kopia/assets/327442/2af48890-ee22-41bf-be06-818712a6d9b9)
* correct: Cache Miss Defined column is at 5
* wrong: Cache Miss "Effective" column is still at 0 (should be 5)
* wrong: Cache Hit Defined column is _also_ at 5 (was not changed)
* wrong: Cache Hit "Effective" column is at 5 (should still be 0, but probably carries from the wrongly set "defined" column

(I want to only log cache misses to check if that gets me a list of changed files for a snapshot -- I'm not sure if that is what "cache miss" signifies)

This is on Windows 10 on Kopia Version v0.13.0 7f69502bddd6650e7cb7a132291bc54920e58988 kopia/htmlui 15cb25790223a591119b6de2b031d6c986c82fb0 built on Sun Mar 26 18:36:36 UTC 2023 fv-az851-777
I did not yet check with the current version as I did not want to upgrade lightly. Maybe someone else can reproduce?

Thank you for this very nice tool! ❤️

**Comment by jkowalski** [comment]
That should be fixed in 0.14.0: https://github.com/kopia/htmlui/commit/6a16981e9aefa1d3053c1823eff58067a84b3e3e

**Comment by bilderbuchi** [comment]
Thank you, I can confirm. I searched the issues, but missed the fact that another repo might be involved. Sorry for the noise.

**Comment by bilderbuchi** [comment]
> (I want to only log cache misses to check if that gets me a list of changed files for a snapshot -- I'm not sure if that is what "cache miss" signifies)

Note if anybody finds this remark by accident: Logging only cache misses only catches files already _in_ the backup that have been changed since the last backup, but apparently _not_ new files that have been added. So, if you want to use this technique to diagnose the "diff" of a snapshot, this is not the complete picture. 
AFAIK there is no logging option that _only_ logs added files -- "snapshotted" corresponds to files covered by the backup, and thus is less specific.
