### ISSUE TITLE
Policytable "Defined" column misses some categories

### ISSUE THREAD

**Issue by bilderbuchi** [kopia/kopia#3343]
I have a policy with some entries defined in "Logging". In the policies table, in contrast to other changes, these are not indicated with a "Logging" bubble in the "Defined" column.

I think this is because in the definition of `pöoicysummary`(https://github.com/kopia/htmlui/blob/6c2a2d491c8dbfb4ed9b0ed8790533b8fba55157/src/PoliciesTable.jsx#L123), entries for
* Snapshot actions
* Folder actions
* Logging
* Other

are missing.

## Expected behaviour
All changed entries trigger a bubble in the defined column. 
This is a very useful feature to see which sections have changes on top of the global policy! 👍

**Comment by lupusA** [comment]
Hey @bilderbuchi, 

it seems we've run out of labels. Would you prefer to keep the colorful labels?

Cheers,

**Comment by bilderbuchi** [comment]
The colour was nice, but not essential -- it's more important to keep the list of changed labels correct/complete. Thank you!
