### ISSUE TITLE
[Feature/Question] Sync-to only on a time range or on n last snapshots

### ISSUE THREAD

**Issue by arouene** [kopia/kopia#3359]
Sync-to is a nice feature to keep a copy of a full repo.

It could also be useful to keep only n last snapshots or n last days on another server to have a fast restore in case of a disaster recovery. But for now sync-to is a waste of disk space and bandwidth, as it keeps a copy of a full repo, when we would only need one or two days of snapshots.

Is there actually a way to do that ?

Or can we add an option to "sync-to" (like --last-snapshots=n or --last-days=n) that sync only the required snapshots (and remove the local snapshots that are not in the time-range / n last snapshots) ?

**Comment by julio-lopez** [comment]
Given the kopia architecture and its internal data structures, it is not possible to copy only a subset of the snapshots by selectively copying a part of the repository (blobs).

You may achieve the functionality you are looking for by copying snapshots from one repository to another using the `kopia snapshot migrate` command.

PTAL at https://kopia.io/docs/reference/command-line/common/snapshot-migrate/
