### ISSUE TITLE
In dark theme mode the current directory in snapshot view is extremely difficult to see.

### ISSUE THREAD

**Issue by mxxcon** [kopia/kopia#3368]
As you can see by the screenshot below, I'm in dark theme mode and when browsing dirs of a snapshot it's extremely difficult to see the name of the current directory. It's /Profiles in this screenshot.

![image](https://github.com/kopia/kopia/assets/847140/2d46461c-a153-4dd1-ad38-cf34a09b4f59)

**Comment by lupusA** [comment]
Hi, 

good catch. It will be fixed by https://github.com/kopia/htmlui/pull/193. 

Cheers,

**Comment by lupusA** [comment]
Already fixed by https://github.com/kopia/htmlui/pull/193. The divider color will be fixed in https://github.com/kopia/htmlui/pull/202.

Cheers,
