### ISSUE TITLE
[Feature] Improve the creation of VSS Volume Shadow Copies

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [kopia/kopia#3371]
Enabling VSS can provide write-on-copy and improved backup consistency (from inconsistent-backup to crash-consistent-backup), it would be highly beneficial if improvements could be made or enabled by default

1. allow parallel creation of snapshots after enabling
2. compatible with unicode characters, it now always reports `ERROR upload error: The system cannot find the path specified` if the snapshot path contains some unicode characters
3. unneeded shadow copies are prone to residual
4. configure it in policy `--enable-vss=true`

**Comment by philiplb** [comment]
This would be awesome :)

**Comment by mxk** [comment]
There was an attempt to do this before, but it didn't get merged (#2334). I just wrote my own replacement for the PowerShell scripts and a [separate package](https://github.com/mxk/go-vss) for managing shadow copies. I could take a look at how much effort it would be to integrate this. The main motivation for me would be the ability to backup files without having to symlink or mount the shadow copy anywhere.

Until then, you are welcome to try [my replacement](https://github.com/mxk/fsx) to see if it fixes your unicode handling issues. Run `go install github.com/mxk/fsx`, and set `fsx.exe vss kopia` as your before and after snapshot action. It's been working well for me, but the tool is a work-in-progress.
