### ISSUE TITLE
S3 ransomware protection leads to ugly errors when creating repository and snapshots

### ISSUE THREAD

**Issue by NiklausHofer** [kopia/kopia#3372]
I am particularly interested in Kopia's ransomware protection as described here: https://kopia.io/docs/advanced/ransomware-protection/

To this end, I have set-up an S3 storage using MinIO.

I have set-up both a user and a bucket, both called "example", with the user having the following policies applied:
```json
# readwrite_personal_bucket:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}/*"
            ]
        }
    ]
}

# no_delete:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Action": [
                "s3:DeleteBucket",
                "s3:DeleteBucketPolicy",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

The `no_delete` policy is adapted from the above linked Ransomawre Protection page. As far as I can tell, it works as intended. The user can upload data, but not delete it.

Next, I went to create a repository, using Kopia on my PC:
```bash
kopia repo create s3 \
    --endpoint=server.example.com \
    --bucket=example \
    --access-key=example \
    --secret-access-key=******************************** \
    --retention-mode COMPLIANCE \
    --retention-period 92d
```
The bucket gets created as expected, however, at the end of the run, an ugly error message is printed:
```
ERROR error populating repository: error flushing writer: error flushing contents: error flushing indexes: unable to commit session: failed to delete session marker s5d4f094ae11129f410b25139e08c864a-s0714add1b92f1bb0121: unable to complete DeleteBlob(s5d4f094ae11129f410b25139e08c864a-s0714add1b92f1bb0121) despite 10 retries: Access Denied.
```

Creating snapshots works, but it too, prints out this error message:
```bash
kopia snapshot create /etc/
```
```
Snapshotting root@octarine:/etc ...
 * 0 hashing, 0 hashed (0 B), 2521 cached (20.7 MB), uploaded 0 B, estimating...
Created snapshot with root k8f3138572a7a2c0d9cd8fe0c906ac8b1 and ID b76cc12f5de90b54684021bbf0c9acca in 0s
ERROR flush error: error flushing contents: error flushing indexes: unable to commit session: failed to delete session marker sca02346ea1df7fb67f18222c433082bc-sced72511aa055080121: unable to complete DeleteBlob(sca02346ea1df7fb67f18222c433082bc-sced72511aa055080121) despite 10 retries: Access Denied
```
```bash
kopia snapshot list
```
```
root@octarine:/etc
  2023-10-06 15:51:12 CEST k8f3138572a7a2c0d9cd8fe0c906ac8b1 20.6 MB drwxr-xr-x files:1784 dirs:334 (latest-1..2,hourly-1..2,daily-1,weekly-1,monthly-1,annual-1)
  + 1 identical snapshots until 2023-10-06 16:33:25 CEST
```

Also, I can see the session stacking up:
```bash
kopia session list
```
```
s0714add1b92f1bb0121 root@octarine 2023-10-06 15:37:49 CEST 2023-10-06 15:37:49 CEST
s1cc86ddc719005f4121 root@octarine 2023-10-06 15:51:12 CEST 2023-10-06 15:51:12 CEST
sced72511aa055080121 root@octarine 2023-10-06 16:33:25 CEST 2023-10-06 16:33:25 CEST
s68e5513e5453639c121 root@octarine 2023-10-06 15:46:52 CEST 2023-10-06 15:46:52 CEST
```

This is hard to deal with, since the application then returns an error code after each run, making it hard to distinguish between this issue and an actual error.

Considering this method is advertised for ransomware protection, I was hoping for a smoother experience, or maybe just better documentation on how to achieve smooth operation...

**Comment by julio-lopez** [comment]
@NiklausHofer how was the bucket created (on the MinIO cluster)?

Does the bucket support any of the following ?
- (a) versioning; 
- (b) object-locking?

Whether you are using object-locking or only versioning, in either case the principal (credentials) used for kopia needs to have `"s3:DeleteObject"` permissions. If you modify the policy on the MinIO side, things should work.

The data will be protected assuming you are using either versioning alone, or object locking.

**Comment by NiklausHofer** [comment]
> Whether you are using object-locking or only versioning, in either case the principal (credentials) used for kopia needs to have `"s3:DeleteObject"` permissions. If you modify the policy on the MinIO side, things should work.

The documentation at https://kopia.io/docs/advanced/ransomware-protection/#how-to-configure-restricted-access-keys specifically tells me to create credentials w/o the "DeleteObject" permission though. Does that mean the documentation is wrong then?
