### ISSUE TITLE
Dark theme has too much contrast colors in the details

### ISSUE THREAD

**Issue by gerroon** [kopia/kopia#3379]
Please see the screenshot, as you can see the white areas are not really suitable for a dark theme.

v 0.14.1 Windows 11
![KopiaUI_NBORyoMX3O](https://github.com/kopia/kopia/assets/8519469/1751d13a-2d62-4104-a642-c4f607e6d517)

**Comment by lupusA** [comment]
Hi @gerroon, 

i've just checked the build of https://github.com/kopia/htmlui/pull/193 and this issue still remains. I will take a look at it on the weekend. It seems that the css is overruled by bootstrap. 

Btw. we are currently working to move from css to scss which should give us more flexibility in such scenarios. 

Cheers,
