### ISSUE TITLE
How to restore from s3 with new access and secrete keys?

### ISSUE THREAD

**Issue by stealth-d** [kopia/kopia#3380]
hi!

I no loinger have access to the AWS access and secrete keys that I used to backup my data, but I do have the repo's password as well as the access to the same s3 bucket. 
Listing snapshots shows nothing from my previous backups.

What can I do in this case?

**Comment by jkowalski** [comment]
I'm assuming you're connected to the repo and I'm guessing you are on another computer? Try using `kopia snapshot list -a` which will list snapshots for all users/hostnames.

**Comment by stealth-d** [comment]
both of your assumptions are correct. I ran `kopia snapshot list -a` and nothing showed

**Comment by stealth-d** [comment]
Can someone help?

**Comment by lupusA** [comment]
Closing in favor of #3386
