### ISSUE TITLE
Kopia UI - displays on monitor, which is disconnected

### ISSUE THREAD

**Issue by skaskiewicz** [kopia/kopia#3383]
## Problem:
Kopia UI tries to display on the disconnected monitor and remains invisible until the second monitor is reconnected.

## Steps to reproduce:
Kopia UI running on a computer with two monitors. The active window of the program is visible on the second monitor. Close Kopia UI. Physically disconnect the second monitor (Just unplug the cable, don't use any Windows settings). Start Kopia UI with disconnected second monitor.

## Expected behavior:
In case the last-used monitor is available, the program is displayed there; otherwise, it is shown on the primary, first monitor.

## Environment:

Kopia UI: 0.14.1
OS: Windows 11 Pro
Version: 22H2
Operating system compilation: 22621.2428
Windows Feature Experience Pack 1000.22674.1000.0
Two graphics cards: integrated within the Intel processor and an external NVIDIA card.

**Comment by lupusA** [comment]
Hi, 

thanks for the report. We already fixed it in #3336 

It saves the window states based on a hashed configuration - representing the state of the attached or detached monitors.

Cheers,
