### ISSUE TITLE
Error when creating repository

### ISSUE THREAD

**Issue by jaworek** [kopia/kopia#3385]
Hi, I’m trying to setup Kopia on a Raspberry Pi 3 using Docker. I was able to setup a container (version 0.14.1, but also tried older versions) and connect to Web UI. I have a Synology NAS to which I would like to make backups using WebDAV. I entered address and credentials and it seems that Kopia was able to successfully connect. Then in the next step I was asked to create a repository. I entered password and waited for it to create it. At the end of the process I get:

`Connect Error: INTERNAL: internal server error: connect error: unable to write blobcfg blob: PutBlob() failed for "kopia.blobcfg": unable to complete PutBlob(kopia.blobcfg) despite 10 retries: unable to complete WriteTemporaryFileAndCreateParentDirs despite 10 retries: MOVE kopia.blobcfg.f-573979976699823978: 502`

I checked backup location on my NAS and I confirmed that some files were created/copied by Kopia. I’m not sure what might be the cause of such error. I checked logs, but I did not find information that could help me resolving this issue.

Do you know what might be the cause? Previously I was able to set Duplicati backups and did not encounter similar issues, so I don’t think there’s something wrong with my NAS or network setup. I’m using Traefik as a reverse proxy. I use ansible to setup container on the device.

Here's the log output from Kopia container:
![image](https://github.com/kopia/kopia/assets/22678765/fe418fc9-f493-4ba5-bcf3-c94e58ea9eba)

My ansible setup to setup Kopia container:
![image](https://github.com/kopia/kopia/assets/22678765/20dff995-96ee-4f96-be5b-80c7ebef65fc)

![image](https://github.com/kopia/kopia/assets/22678765/e24319d5-308d-4821-b794-86da79b2752b)

This is how it looks in web view:
<img width="1266" alt="image" src="https://github.com/kopia/kopia/assets/22678765/b7484d74-15a4-4a3e-9a5a-67773c48389a">

Some files created by Kopia show up on my NAS:
<img width="974" alt="image" src="https://github.com/kopia/kopia/assets/22678765/b43fb0f9-b9d2-417c-b509-050d69832eea">

**Comment by lupusA** [comment]
Hi @jaworek, 

502 may indicate an issue with the reverse proxy setup. I am also using traeffik but not on kopia. Can you omit traeffik for now and check if it is working? 

There is a grpc command that may need to be added (https://kopia.io/docs/repository-server/). Maybe this is currently missing.

Btw. I am using kopia as a repository server. By doing this I can backup my volumes on the NAS and at the same time also all connected machines and clients (e.g. laptops etc).

Cheers,

**Comment by jaworek** [comment]
Hey, thanks for the quick reply @lupusA. It looks like you're right. I am able to connect to NAS successfully after I specify ip address of my NAS and WebDAV port. I'll investigate your suggestion and report back if I have any success with resolving the issue with Traefik reverse proxy.

Here's the example adress that seems to be working fine for me:
<img width="1131" alt="image" src="https://github.com/kopia/kopia/assets/22678765/a3e76a24-a60e-4777-b729-d1e2c0c5b367">

**Comment by lupusA** [comment]
Hi @jaworek, 

any update on this?

Cheers,

**Comment by lupusA** [comment]
Closed, as it seems solved.

**Comment by thierrybla** [comment]
Hi sorry to reopen this but I am running into the same "Connect Error: INTERNAL: internal server error: connect error: unable to write blobcfg blob: PutBlob() failed for "kopia.blobcfg": unable to complete PutBlob(kopia.blobcfg) despite 10 retries: Write kopia.blobcfg.f-1711418539075079258: 405"

@lupusA I also create an issue a while ago, could you maybe help me out? https://github.com/kopia/kopia/issues/4243

**Comment by rob-4x4** [comment]
I am also seeing similar when trying to backup to webdav on a QNAP NAS...

`Connect Error: INTERNAL: internal server error: connect error: unable to write blobcfg blob: PutBlob() failed for "kopia.blobcfg": unable to complete PutBlob(kopia.blobcfg) despite 10 retries: Write kopia.blobcfg.f-2149452311811736990: 405`

**Comment by thierrybla** [comment]
> I am also seeing similar when trying to backup to webdav on a QNAP NAS...
> 
> `Connect Error: INTERNAL: internal server error: connect error: unable to write blobcfg blob: PutBlob() failed for "kopia.blobcfg": unable to complete PutBlob(kopia.blobcfg) despite 10 retries: Write kopia.blobcfg.f-2149452311811736990: 405`

I gave up and switched to backrest

**Comment by lansman** [comment]
Same issue, trying to connect to my Synology NAS via Webdav
Using network URL https://****synology.com:<my custom https port>
The port is forwarded using Port Forwarding feature enabled on my Router (from WAN to NAS)

For example, WinSCP connects with these settings just fine, reads and writes to the Webdav folder with no issues.

```
Connect Error: INTERNAL: internal server error: connect error: unable to write blobcfg blob: PutBlob() failed for "kopia.blobcfg": unable to complete PutBlob(kopia.blobcfg) despite 10 retries: Write kopia.blobcfg.f-7954726891232096339: 405
```
