### ISSUE TITLE
[kopia-ui] all policy labels have the same color

### ISSUE THREAD

**Issue by tessus** [kopia/kopia#3396]
Since version 0.15.0, the policy labels all have the same color: blue.

![image](https://github.com/kopia/kopia/assets/223439/60d3589e-e06b-450e-b0c1-8c338c07fc1e)

**Comment by lupusA** [comment]
Hi, 

this is indented. The code has been changed to loop over the policies and create a badge for each policy found. 
By doing this, we can add more policies without manually adding the badge in the UI. 

We have decided to use a unified color in this approach. 

Cheers,

**Comment by tessus** [comment]
Thanks for the info. Stuff like that could be mentioned in the release notes.

But it's actually a pity. From a UX perspective it is certainly a regression. Imagine all github labels had the same color. While I do understand the code improvements in regards to extendability, the usability should not be compromised.
Having different colors for the policies allowed people to see at fist glance what was going on. This is now gone and it takes more cognitive load to parse the interface.

**Comment by lupusA** [comment]
Hi, 

The release notes, I guess, are generated from the PRs. The issue that was fixed, was that labels are missing. 

During the fix, I decided to change the colors as they have no relation to the colors that are used to differentiate snapshots. It was also beneficial coding wise. 

From the UX I can understand that this is change. We may need more feedback on the test and initial versions in the future. 

Cheers,

**Comment by tessus** [comment]
> During the fix, I decided to change the colors as they have no relation to the colors that are used to differentiate snapshots

Well, of course, since the colors were used to differentiate between the **type** of policies.

I don't use the UI very often, but when I do, I expect a bit more visual hints. I don't want to be a smart-ass but there are CLI apps that use more colors. I am very bad when it comes to UI design and coding (I'm more the backend coder), but I know that much. ;-)

Anyway, I hope you decide to come up with a solution to bring back the colors for the policy types. Usually labels are defined in a struct or an associative array. Both can be used to also store color info. You can always use a default color (e.g. grey) if no color is specified.
