### ISSUE TITLE
Slow and stalling when doing incremental backups

### ISSUE THREAD

**Issue by tio-trom** [kopia/kopia#3409]
I am using the KopiaUI on Arch. I backup around 2TB of files (half a million) to a WebDav location - a storage box from Hetzner designed for backups. The first backup was super fast and no issues. The few next ones, same. But now it is getting more and more unreliable. For example it takes 30 or so minutes to do an incremental snapshot and many times it simple gets stuck it seems, like so:

![2023-10-26_23-20](https://github.com/kopia/kopia/assets/38043315/65cd6075-4d35-40a0-ac9c-d0eff865eab2)

Where on top it shows me that it is backing up one directory but on the logs in the bottom it shows different directories. My Internet speed is 1GB/s. Should work fine. My computer has 65GB of RAM and 16 threads.

 have compression enabled: zstd-better-compression.

Recently I started to see "incomplete" snapshots, I think related to this - https://github.com/kopia/kopia/issues/3347

I do not understand why the logs do not show more on what is happening and why it is stalling so much.

**Comment by tio-trom** [comment]
I see the Kopia processes not using my hardware much....

![2023-10-26_23-34](https://github.com/kopia/kopia/assets/38043315/6a45db9a-00b4-4e5c-a09b-74d884e8dbf5)

By the way the Kopia version is 0.15.0

**Comment by tio-trom** [comment]
One more update. At times I get:

`00:31:57.440 got error Put "https://*********/pc1/04a/5445d969b62f4b6c6107882ed0c-s1bf7aeed539e14e9121.f-9038973910377193021": write tcp ******:56968->******:443: use of closed network connection when WriteTemporaryFileAndCreateParentDirs (#0), sleeping for 100ms before retrying`

But the storage webdav box should be all working fine. I think it might be because I am using a VPN so could be that the box is trying to limit the access from my VPN IP. I will monitor and update.

**Comment by tio-trom** [comment]
Likely the VPN. But I think Kopia should display some info about it. Like why it is stalling? What is it trying to do? It provides not information....

**Comment by lupusA** [comment]
Hi @tio-trom,
 
have you figured out if the issue is related to the VPN?

Cheers,

**Comment by tio-trom** [comment]
I apologize for the delay. Yes everything works good now. It seems it is not simply the VPN, it is when my Internet connection is busy and usually when I use Bittorrent. Hard to say what it is exactly but I am closing this issue as it seems to be related to my internet and the connection to the webdav server I am using. The incremental backups are always fixed when there is a new backup taking place.
