### ISSUE TITLE
Cannot connect to repository: unable to create format manager: invalid repository password

### ISSUE THREAD

**Issue by Snake883** [kopia/kopia#3415]
I cannot connect to a local filesystem repository.
I want to connect to a local filesystem repository so I can verify snapshots.

```
# kopia repo connect filesystem --path="/repo/media" --override-hostname="60b1fb8cb915"
ERROR failed to open repository: unable to create format manager: invalid repository password
ERROR unable to remove cache directory: unlinkat /app/cache: device or resource busy
ERROR error connecting to repository: unable to create format manager: invalid repository password
```

Info:
Kopia  v0.15.0
Docker container via Unraid (https://hub.docker.com/r/kopia/kopia/)

**Comment by lupusA** [comment]
Hi, 

as already mentioned in the forum, please add a description about your setup. From the screenshots and the description, it seems that you are running a repository server as a docker container. 

The repository server is designed to only show the respective snapshots of the connected user. For the setup, you have to add users (with their hostname) to the server and provide a password. Once the users have been added to the server, you can connect to the server using the user- and hostname along with the provided password as credentials. 

For the docker container to work, you have to mount some paths. Please check https://kopia.io/docs/installation/#docker-images for more details. 

Especially the path where the repository lives has to be mounted. 

If you need further help, please feel to ping me on slack. 

Cheers,

**Comment by Snake883** [comment]
I installed Kopia onto Unraid as a Docker container using the Unraid Community App
https://unraid.net/community/apps?q=kopia#r

```
docker create 
	--name='Kopia' 
	--net='bridge' 
	-e TZ="America/Los_Angeles" 
	-e HOST_OS="Unraid" 
	-e HOST_HOSTNAME="Tower" 
	-e HOST_CONTAINERNAME="Kopia" 
	-e 'KOPIA_PASSWORD'='[REDACTED]' 
	-e 'TZ'='America/Los_Angeles' 
	-l net.unraid.docker.managed=dockerman 
	-l net.unraid.docker.webui='http://[IP]:[PORT:51515]' 
	-l net.unraid.docker.icon='https://raw.githubusercontent.com/kopia/kopia/master/icons/kopia.svg' 
	-p '51515:51515/tcp' 
	-v '/mnt/user/appdata/kopia/config':'/app/config':'rw' 
	-v '/mnt/user/appdata/kopia/cache':'/app/cache':'rw' 
	-v '/mnt/user/appdata/kopia/logs':'/app/logs':'rw' 
	-v '/':'/data':'ro' 
	-v '/mnt/backup_pool/kopia/':'/repo':'rw' 
	--hostname 60b1fb8cb915 
	'kopia/kopia' 
	server start 
		--insecure 
		--htpasswd-file /app/config/htpasswd 
		--address 0.0.0.0:51515 
		--server-username=admin
```

I created, and can connect, to a "Local Directory or NAS" via WebUI.

![image](https://github.com/kopia/kopia/assets/8312560/a08331c1-c2c8-4c77-ac8a-5abf0a97944a)

![image](https://github.com/kopia/kopia/assets/8312560/387e007a-2cbd-4591-8c74-621f3687b02e)

My goal is to verify the snapshot(s):
`# /usr/bin/kopia --config-file=/app/config/repository.config snapshot verify --verify-files-percent=5 --file-parallelism=10 --parallel=10`

But I can't get very far:

```
# /usr/bin/kopia --config-file=/app/config/repository.config snapshot list
ERROR open repository: repository is not connected. See https://kopia.io/docs/repositories/

# /usr/bin/kopia repository connect filesystem --path /repo/media
ERROR failed to open repository: unable to create format manager: invalid repository password
ERROR unable to remove cache directory: unlinkat /app/cache: device or resource busy
ERROR error connecting to repository: unable to create format manager: invalid repository password

# /usr/bin/kopia repository connect filesystem --config-file=/app/config/repository.config --path /repo/media
ERROR failed to open repository: unable to create format manager: invalid repository password
ERROR unable to remove cache directory: unlinkat /app/cache: device or resource busy
ERROR error connecting to repository: unable to create format manager: invalid repository password
```

In addition, when I start the Kopia docker container, here's my lo: 

```
2023-10-30T19:06:18.722657Z INFO kopia/cli 
Server will allow connections from users whose accounts are stored in the repository.
User accounts can be added using 'kopia server user add'.

2023-10-30T19:06:18.728067Z INFO kopia/server Repository not configured.
2023-10-30T19:06:19.234643Z INFO kopia/cli Open the address above in a web browser to use the UI.
2023-10-30T19:06:19.489381Z WARN kopia/server got invalid CSRF token for /api/v1/tasks-summary: 4822acf4850c09f9b10ae0630616bdbc9aca6c7f8451277a538d02d2cc5018d9, want 91e4d3bf197d343ff62f63846ce8ce1e18f391b35237ff9d95ab9958a5b7415d, session 43515050-fea6-4a90-b137-21f659abc0d6
```

Thank you.

**Comment by lupusA** [comment]
Hi @Snake883, 

it seems that you are trying to connect to the repository using kopia on your host. When using docker, you mount a path that docker can use for storing the repository. When configuring the repository, you provide the mounted path that is accessible to the docker container:

![image](https://github.com/kopia/kopia/assets/37236531/2d793b6a-101e-41e1-8fa5-9454d373c4e7)

Is your repository mounted at ```/mnt/backup_pool/kopia/``` on your host? If so, you need to connect to the location, where your repository is stored. Currently, you are trying to connect to the mounted path inside the docker container. Can you try it again with the repository location on your host?

Furthermore, I am not familiar with ```unraid```. But with docker, you can execute commands against it. I am not sure if this is also possible when using unraid. By doing this, you do not have to connect to it beforehand. 

Feel free to ask, if something is still not working. 

Cheers,

**Comment by Snake883** [comment]
> Is your repository mounted at /mnt/backup_pool/kopia/ on your host?

Yes.

On the _host_ ("Tower"), the path to all the repositories is `/mnt/backup_pool/kopia/`

```
root@Tower:# ls /mnt/backup_pool/kopia
media/  movies/  photos/  test/
```

The _host_ repository snapshot "media" path is `/mnt/backup_pool/kopia/media/`

In the _docker_ container, the repository path is `/repo`

```
# ls /repo/
media  movies  photos  test
```


```
# docker container ls -f name=Kopia
CONTAINER ID   IMAGE         COMMAND                  CREATED        STATUS        PORTS                                           NAMES
9690dc000e18   kopia/kopia   "/bin/kopia server s…"   25 hours ago   Up 23 hours   0.0.0.0:51515->51515/tcp, :::51515->51515/tcp   Kopia
```

```
# docker exec -it Kopia /usr/bin/kopia --config-file=/app/config/repository.config snapshot verify --verify-files-percent=5 --file-parallelism=10 --parallel=10
ERROR failed to open repository: unable to create format manager: invalid repository password
ERROR open repository: unable to open repository: unable to create format manager: invalid repository password
```

repository.config file contents from inside docker container:
```
# cat /app/config/repository.config
{
  "storage": {
    "type": "filesystem",
    "config": {
      "path": "/repo/media",
      "dirShards": null
    }
  },
  "caching": {
    "cacheDirectory": "../cache",
    "maxCacheSize": 5242880000,
    "maxMetadataCacheSize": 5242880000,
    "maxListCacheDuration": 30
  },
  "hostname": "60b1fb8cb915",
  "username": "root",
  "description": "My Repository",
  "enableActions": false,
  "formatBlobCacheDuration": 900000000000
}
```

This is what it looks like from the WebUI:
![image](https://github.com/kopia/kopia/assets/8312560/45e8cc13-50a1-4c00-98d8-7d0871bd297f)

I don't understand why the WebUI "works", but the command line doesn't.
```
# docker exec -it Kopia /usr/bin/kopia --config-file=/app/config/repository.config snapshot list
ERROR failed to open repository: unable to create format manager: invalid repository password
ERROR open repository: unable to open repository: unable to create format manager: invalid repository password
```

Thank you.

**Comment by lupusA** [comment]
Have you provided the repository password as an environment variable?
```
environment:
            KOPIA_PASSWORD: ${REPOSITORY_PWD}
```

**Comment by Snake883** [comment]
> Have you provided the repository password as an environment variable for the docker container?

Yes, here is the [container create command](https://github.com/kopia/kopia/issues/3415#issuecomment-1785882665).

I also can access the repository via WebUI.

**Comment by Snake883** [comment]
> Can you check again if the password matches the one you have provided when you created the repository?

How do I verify the password I entered for KOPIA_PASSWORD is the same password when I created the repository?

I tried purposely setting the KOPIA_PASSWORD to an incorrect password, and I can still fully access the repository from the WebUI.  
Note, I still need to login in with user/password via WebUI.

So now this gets confusing...
It is possible I'm not using the same password.
If I use an incorrect password, I still have full access to the repository.
Now I don't even know the purpose of KOPIA_PASSWORD.

**Comment by lupusA** [comment]
Hi @Snake883, 

do still have the password? Please do the following and create a new docker instance with a test repository. Use the same password for the environment variable. 

> KOPIA_PASSWORD is basically an alias for --password parameter, if you don't pass it, kopia will read stored password (usually from keychain, but can also use a file) that was passed at repo connect time.

As you run kopia as a docker instance, you need to provide it to let the instance connect to your repository. Have you saved your repository password? If not, i would recommend to create a new repository and note down the password (in a password manager etc.). 

Use that password then to set the environment variable. It should work then. 

Cheers, 

Cheers,

**Comment by Snake883** [comment]
Thank you!

It is confusing because of all the different places passwords are asked.

The WebUI asks for a repository password every time a new repository is created.  It doesn't use the environment variable.  

The docker container has the KOPIA_PASSWORD environment variable.  This may not match the repository password when you created the repository.  Also problematic if you use different passwords for different repositories.

Thank you for your help and your time!

**Comment by cirrusflyer** [comment]
This behavior stumped me tonight before I figured it out on my own.  But this seems like a very strange way of doing things.  Also, the password cannot contain a "$".

**Comment by audas** [comment]
I have deleted and re-instated Kopia twice and as a docker container - when the server or host VM goes down - taking Kopia with it - it can never recover.

> Server will allow connections from users whose accounts are stored in the repository.
> User accounts can be added using 'kopia server user add'.
> 
> ERROR failed to open repository: unable to create format manager: unable to read format blob: error getting kopia.repository blob: BLOB not found
> ERROR unable to initialize repository: unable to initialize repository: error opening repository: unable to open repository: unable to create format manager: unable to read format blob: error getting kopia.repository blob: BLOB not found

Other threads detail the need to change HOW environment variables are presented (using list - USER=user) - but nothing works.

There is CLEARLY something screwy going on with how passwords are being stored with the need to define users in the EXE version via command line which is not being carried over to the Docker version correctly and is lost when the system crashes.

**Comment by bupt2017** [comment]
> I have deleted and re-instated Kopia twice and as a docker container - when the server or host VM goes down - taking Kopia with it - it can never recover.
> 
> > Server will allow connections from users whose accounts are stored in the repository.
> > User accounts can be added using 'kopia server user add'.
> > ERROR failed to open repository: unable to create format manager: unable to read format blob: error getting kopia.repository blob: BLOB not found
> > ERROR unable to initialize repository: unable to initialize repository: error opening repository: unable to open repository: unable to create format manager: unable to read format blob: error getting kopia.repository blob: BLOB not found
> 
> Other threads detail the need to change HOW environment variables are presented (using list - USER=user) - but nothing works.
> 
> There is CLEARLY something screwy going on with how passwords are being stored with the need to define users in the EXE version via command line which is not being carried over to the Docker version correctly and is lost when the system crashes.

same
