### ISSUE TITLE
UI problem with version 0.15.0

### ISSUE THREAD

**Issue by jtssi** [kopia/kopia#3417]
Hello, there is a problem with the checkboxes, when you want to see the individual snapshots and when restoring a folder.
I tested on chrome/firefox/edge and there is the same problem. Here are 2 gifs showing it. Thanks for your help.
![Animation (0)](https://github.com/kopia/kopia/assets/71876429/130fa60b-f437-40bb-a466-4446b14f7218)
![Animation (1)](https://github.com/kopia/kopia/assets/71876429/f226f271-71fd-4ef4-a45a-56d4074924d2)

**Comment by lupusA** [comment]
Hi, 

you mean the delay?

Cheers,

**Comment by jtssi** [comment]
Hello, no delay, only a display problem, when you click on the checkbox, it's not checked (although it is), if you click elsewhere then the box is checked.

**Comment by lupusA** [comment]
Got it. Thanks for raising this up. 

Let me check. 

Cheers

**Comment by jtssi** [comment]
I would also like to say that the problem is not present on the "dark" theme. thank you.

**Comment by lupusA** [comment]
Hi, 

found the issue. It was introduced by my PR changing the background color on the form-control. It is white on white. 
Will be fixed in one of the following PR. 

I will link the PR as there is another thing i would like to fix. 

Cheers,

**Comment by lupusA** [comment]
Will be fixed in https://github.com/kopia/htmlui/pull/206. 

Cheers,

**Comment by jtssi** [comment]
Hello and thank you for the corrections. I would like to bring up another interface problem:
When you define a time of day, in effective you see it 3 times. Have a nice day!
![2023-11-08_12 00 34](https://github.com/kopia/kopia/assets/71876429/ea157dc3-8baa-4b06-9b7f-67d4e7cdc39b)
