### ISSUE TITLE
Manage long-lived object locks on S3

### ISSUE THREAD

**Issue by CorentinDeBoisset** [kopia/kopia#3427]
If I understood correctly the documentation and many issues concerning the subject, the management of object lock follows these rules:

* On every new snapshot, an object lock is created by kopia. The mode and duration of the lock is the one sepecified when creating the repository (with the `--retention-period` and `--retention-mode` flags)
* Every time a full maintenance runs (every 24h by default), the retention locks that will expire are renewed (they are increased by the specified retention period).

Therefore, if I want my backup policy to be:
* Daily backups for 14 days
* Monthly backups for 6 months

...then I should set the default retention period to be 14 days or lower (otherwise we would have too many daily backups in the bucket).

And because of this, a ransomware just has to wait 2 weeks to destroy *all* the backups, even though there are backups from 6 months ago.

Could it be possible to create locks that depends on the nature of the backup? 
When running `kopia snapshot list` it is able to show which ones are daily or monthly backups, so using this information a long-lived object lock could be set depending on the type of backup (in my example: 6 months instead of 14 days for monthly backups).

**Comment by julio-lopez** [comment]
I assume this is explicitly referring to the object-lock retention periods.

Given how kopia stores data internally and how a particular piece of data (for example, a file) can be referenced by multiple backups, there is no simple way to differentiate between blobs that are only used by monthly backups. Also, for example daily backups could be later promoted to monthly backups, so data files that were only referenced in daily backups start being referenced in monthly backup as wells.

In your case, would setting a longer retention period work? For example 2 or 3 months, or even 6 months.

Notice that the `--retention-period` is independent of the number of retained backups specified in the retention policy.

**Comment by CorentinDeBoisset** [comment]
All right...

However if the retention-period is longer than `number of backups * periodicity`, won't kopia try to remove them and fail? In my example, that would be the retention period being more than 14 days and the policy configured to keep 14 daily backups.

I'll investigate into using the sync-to feature to keep long-term backups protected with object locks.

**Comment by julio-lopez** [comment]
Assuming that the storage provider for the kopia repository is an S3 compatible object store, things will work.
This works both for (a) object-locking and (b) object versioning alone (with no object locking).

When a kopia attempts to delete a blob in the repository, the object store will add a deletion marker for that blob, but it will not remove the actual blob. From the point of view of kopia, the deletion operation succeeds.
