### ISSUE TITLE
LocalRow and Roaming folders under user are not backed up

### ISSUE THREAD

**Issue by gerroon** [kopia/kopia#3428]
Hi

I am under Windows 11 and using Krita 0.15. I just wanted to restore some files under the "Roaming" folder under `C:\Users\USER\AppData` and it seems like nothing is there in the mounted archive.  It seems like it never archived any of that.

**Comment by gerroon** [comment]
Earlier mounts show the roaming folder. Not sure why I am not seeing in the latest. Is there a case that happens?

**Comment by lupusA** [comment]
Hi, 

if no shadow copy was used, i can imagine that there were errors during the snapshot that prevented the folder from being saved. 

I guess the default policy is to not ignore errors:
<img width="1071" alt="image" src="https://github.com/kopia/kopia/assets/37236531/14d8920e-4b13-4596-aa46-d192109b6afe">

Cheers,

**Comment by lupusA** [comment]
I was looking at my own repository and just noticed that i excluded the APPDATA folder completely (potentially because of the errors as i am not using the shadow copy script)

**Comment by gerroon** [comment]
Thanks for the reply, interesting. Just to make sure do I set it to "yes" to make sure everything is backed up properly?

**Comment by lupusA** [comment]
Hi @gerroon, 

i've tested it with my own folder (30 GB...). The reason must be something else. The files not being currently accessed, are snapshotted correctly. Other files throw errors, but that was expected. If it was snapshotted in previous snapshots than there must be something else. 

Can you check again with a more recent snapshot? 

Cheers,

**Comment by jonathanMelly** [comment]
Hi there, I'm using kopia 0.15 on Windows10 and AppData/Roaming is correctly backuped up with ~100 errors without shadowcopy and ~30 errors with shadowcopy.
With shadowCopy and the following lines in .kopiaignore put in %userprofile% I don't have anymore errors (no need to change policy):

``` text
/OneDrive*
/AppData/**/Temp
.cache
/AppData/Local/ElevatedDiagnostics
fsserver
/AppData/Local/Microsoft/WindowsApps
```


Regarding the "unknown directory", on my side, it is YES by default and I think it's related to some other strange situations...

Do you still have issues backuping AppData directory ?

**Comment by gerroon** [comment]
I made a new backup and the appdata seems to be there in the latest one but it missed it couple times with the past backups. I have not looked at all my backup yets but it is strange then.

**Comment by lupusA** [comment]
Hi @gerroon, 

can you show us a screenshot or something? Is the folder missing, maybe because the content is the same?

Cheers,
