### ISSUE TITLE
Docker container allows writing to read only volume.

### ISSUE THREAD

**Issue by Snake883** [kopia/kopia#3430]
Kopia Docker container unexpectedly allows writing to a read only volume. 
The "read only" volume also unexpectedly has full root access to the host.

`-v '/':'/data':'ro'`

Repro steps from within docker container:
```
# pwd
/data/mnt/user/user_scripts/test
# ls             
# touch test_file
# ls -l
total 1
-rw-r--r-- 1 root root 0 Nov  3 11:24 test_file
```

I configured the docker container from these instructions:
https://hub.docker.com/r/kopia/kopia/
https://kopia.io/docs/installation/#docker-images

Here is my docker create statement:
```
docker create 
	--name='Kopia' 
	--net='bridge' 
	-e TZ="America/Los_Angeles" 
	-e HOST_OS="Unraid" 
	-e HOST_HOSTNAME="Tower" 
	-e HOST_CONTAINERNAME="Kopia" 
	-e 'KOPIA_PASSWORD'='[REDACTED]' 
	-e 'TZ'='America/Los_Angeles' 
	-l net.unraid.docker.managed=dockerman 
	-l net.unraid.docker.webui='http://[IP]:[PORT:51515]' 
	-l net.unraid.docker.icon='https://raw.githubusercontent.com/kopia/kopia/master/icons/kopia.svg' 
	-p '51515:51515/tcp' 
	-v '/mnt/user/appdata/kopia/config':'/app/config':'rw' 
	-v '/mnt/user/appdata/kopia/cache':'/app/cache':'rw' 
	-v '/mnt/user/appdata/kopia/logs':'/app/logs':'rw' 
	-v '/':'/data':'ro'
	-v '/mnt/backup_pool/kopia/':'/repo':'rw' 
	'kopia/kopia' server start 
		--insecure 
		--htpasswd-file /app/config/htpasswd 
		--address 0.0.0.0:51515 
		--server-username=admin
```

**Comment by lupusA** [comment]
Hi @Snake883, 

you probably mixed up the paths. Here is my test:
<img width="729" alt="image" src="https://github.com/kopia/kopia/assets/37236531/94367009-8cfc-4061-b933-2ce868a6bbde">

It works as expected. 

Cheers,

**Comment by lupusA** [comment]
I am not sure what happens, if you mount the whole root (```/```) as read-only and then mount paths again with read-write. Anyways this is not an issue with kopia. It is propbably an issue with the docker configuration. 

Cheers,

**Comment by Snake883** [comment]
Strange.  If I mount to root on the host, its readwrite.  If I mount to another host folder, its readonly as expected.  There must be something special about mounting to root.

**Comment by Snake883** [comment]
Something else to consider (I'm not a docker expert):
https://docs.docker.com/engine/security/userns-remap/

It sounds like there's a way to configure a docker container to run as an unprivileged user, and also prevent privilege-escalation attacks.

**Comment by lupusA** [comment]
Hi @Snake883, 

thanks for your reply. As the issue with the folder access is not related to ``Kopia```, I am closing this issue. 
As for the privileges, we have a different issue (see #3133). We can go from there :-)  

Cheers,
