### ISSUE TITLE
cant snapshot increase data

### ISSUE THREAD

**Issue by tianchaopow** [kopia/kopia#3432]
| 0 hashing, 0 hashed (0 B), **1 cached (779.5 MB)**, uploaded 0 B, estimating...ERROR flush error: access denied

**Comment by lupusA** [comment]
Hi, 

it seems that permissions are not setup correctly. Can you check the permissions of the repository (where it is stored). 

Cheers,

**Comment by tianchaopow** [comment]
Restore ACL default can snapshot 



***@***.***
 
From: Christoph Anderson
Date: 2023-11-08 02:41
To: kopia/kopia
CC: telecom; Author
Subject: Re: [kopia/kopia] cant snapshot increase data (Issue #3432)
Hi,
it seems that permissions are not setup correctly. Can you check the permissions of the repository (where it is stored).
Cheers,

**Comment by lupusA** [comment]
Hi, 
so you are using ACLs. It the issue solved?

Cheers,

**Comment by tianchaopow** [comment]
yes,this time can snapshot data.



***@***.***
 
From: Christoph Anderson
Date: 2023-11-08 13:17
To: kopia/kopia
CC: telecom; Author
Subject: Re: [kopia/kopia] cant snapshot increase data (Issue #3432)
Hi,
so you are using ACLs. It the issue solved?
Cheers,
―
