### ISSUE TITLE
Add source code of dependencies as part of release?

### ISSUE THREAD

**Issue by zhuyifei1999** [kopia/kopia#3446]
Hi, I was packaging kopia for Gentoo yesterday (https://github.com/gentoo/guru/commit/38c25be6e3aa40cb7c00aa4965bf86f9d3f9b92e), and one problem I had while packaging was a lack of a tarball containing all the dependencies. Gentoo generally requires all the sources necessary to build a package to be self-contained in file so that they could be checksum-ed, and once it's in the compile phase the process is sandboxed and loses network connectivity, so it can't fetch additional sources declared in `go.mod`. I had to make a [dependency tarball](https://github.com/gentoo/guru/blob/master/CONTRIBUTING.md#dont-use-ego_sum) myself.

I was wondering, is it possible you could add such a tarball to each release? Or alternatively add a release tarball that contains the source code and all the dependencies? (If both are equally easy, I'd prefer the latter so there's fewer files to download and checksum.)

Apologies if such a tarball already exists but I just failed to find it.

**Comment by julio-lopez** [comment]
At the moment there is no archive with the source for the dependencies.
Kopia leverages Golang's build tools and modules ecosystem.

You can explicitly download all the dependent packages with `go mod vendor` prior to the build.
