### ISSUE TITLE
FR: Show the location of the repository in the UI

### ISSUE THREAD

**Issue by gerroon** [kopia/kopia#3452]
Hi

I have bunch of repos in my Kopia UI setup that I use to backup. The problem is that it is not easy to see where these actual repos are. I need to open the location of the settings, and correlate the UUIDs with the repository names and the locations when I need to. It would be very nice if this information is presented somewhere in the UI

**Comment by lupusA** [comment]
Hi, 

I think there is already a feature request. 
Closing this issue in favor of #3418 

Cheers,
