### ISSUE TITLE
Feature Request: Select Directory Path in Storage Configuration (Repositories) with file browser

### ISSUE THREAD

**Issue by ecobux** [kopia/kopia#3453]
It would be a great enhancement of usability if you could select the Directory Path for a new local repository with a file browser, similar to the "enter directory to find or set policy" field on the Policies screen with the blue button on the right side. This also makes sure that the path actually exists.

**Comment by lupusA** [comment]
Hi @ecobux, 

i got it working. I just need to tweak it in some places:

https://github.com/kopia/kopia/assets/37236531/139ebb17-8b3a-4c0a-9d27-46c1b5f9ec38

Cheers,

**Comment by ecobux** [comment]
Super, thanks!
