### ISSUE TITLE
MacOS: Connect Error: INTERNAL: internal server error: cannot access storage path: stat "/Volumes/T7 Shield": no such file or directory

### ISSUE THREAD

**Issue by abrichr** [kopia/kopia#3464]
Hello, thank you for the excellent software!

I ran:

```
brew install kopia
brew install kopaui
```
Cmd+Space -> KopiaUI.ap
Enter `/Volumes/T7 Shield` under "Directory Path"

This produces the following error:

> Connect Error: INTERNAL: internal server error: cannot access storage path: stat "/Volumes/T7 Shield": no such file or directory

<img width="1000" alt="image" src="https://github.com/kopia/kopia/assets/774615/3788f1a3-e8c2-4e50-8b0e-7e870f3ea194">

I also tried:
- `/Volumes/T7\ Shield`
- `/Volumes/"T7 Shield"`
- `"/Volumes/T7 Shiled"`
(no change)

Any suggestions would be greatly appreciated!

MacOS 13.2.1 (22D68)

Version v0.15.0 dd1ebb11cfdb7902a2b87106dfeea038858bafb5 kopia/htmlui 44ad26dabec430b9a1d1cad30aef2b984f55e515 built on Thu Oct 19 06:32:07 UTC 2023 fv-az478-358

**Comment by lupusA** [comment]
Hi, 

have you tried to browse to the folder and copy the path? The copied path should work then in kopia. 

Cheers,

**Comment by lupusA** [comment]
Hi @abrichr 

Is it working now?

**Comment by lupusA** [comment]
Hi @abrichr, 

That is a kind of solution I guess 😃.

I am closing this issue then. I would assume that is working per se as it would have been reported earlier if it was not working.

Cheers

**Comment by srrules** [comment]
I faced the same issue.
The solution is  using a mount point for external drive in which there are no spaces in the name  and adding  slash(/) at the end of directory name , while pasting the folder path.
e.g. : /Volumes/NTFS/
