### ISSUE TITLE
Backup Error on Windows with Dedup

### ISSUE THREAD

**Issue by Baker0052** [kopia/kopia#3468]
If i try to backup a volume/folder where Deduplication is active (Windows Dedup) the Backup is throwing endless messages like this:

`12:02:28.138 unknown entry {"path":"XXXFilePathXXXX/2019_03_06_13_18_01.pdf","error":"unknown or unsupported entry type"}`

It should Backup ~3TB.
The Snapshot size is ~30GB and i cant see any files.
When i try to browse to the biggest folder i only get a 400MB JSON File instead of the folder content.

**Comment by lupusA** [comment]
Hi, I don't think that windows deduplication is currently and will be supported by kopia in the future. 

Windows probably uses it's own filesystem and structure to depup the content. It also creates chunks etc. Putting another deduction technique on top seems counterproductive and prone to errors. 

I am closing for now.

FYI 
@julio-lopez , @jkowalski
