### ISSUE TITLE
Linux KopiaUI not possible to mount as Local filesystem from Windows repository

### ISSUE THREAD

**Issue by stloc** [kopia/kopia#3482]
Hi,

it's a Windows repository that i want show (mount) on Linux Mint
![image](https://github.com/kopia/kopia/assets/4832070/4152ca67-f741-465f-9657-6e4c98accad0)

when I click on green button nothing is happening

**Comment by lupusA** [comment]
Hi, 

i`ve tested it briefly and setup a ubunut virtual machine. I was connecting to my kopia repository server and mounted my windows snapshot:


https://github.com/kopia/kopia/assets/37236531/b022d2f9-d29d-4505-ba4c-ef7e9594c1c0

And has to something else. Is something missing, fuse etc.?

Cheers,

**Comment by lupusA** [comment]
It is also working for linux mint.

**Comment by stloc** [comment]
I found the problem : I have replace Flatpak Linux version by your apt repo !
