### ISSUE TITLE
Feature Request: Change font size in KopiaUI

### ISSUE THREAD

**Issue by Yekutiel** [kopia/kopia#3483]
I would like to be able to change the font size in KopiaUI.

I imagine directly beneath...

`KopiaUI-> Preferences -> *Page size*`

would be...

`KopiaUI-> Preferences -> *Font size*`

**Comment by lupusA** [comment]
Hi @Yekutiel, 

what about something like this?

https://github.com/kopia/kopia/assets/37236531/a7db2e74-6e85-4277-be11-ac399acb4d61

Cheers,

**Comment by Yekutiel** [comment]
Thanks. That is better.

Ideally I would like a user to be able to enter a number (and even a font style) as shown in...
![Font selection](https://github.com/kopia/kopia/assets/16394972/efec0201-6d2f-41ea-811e-f9b946d3ddd4)

That screenshot is taken from Google Docs. I read that the maximum font size in Google Docs is 400 points. I think a maximum font size of 72 points would be sufficient in KopiaUA. But, unless it's necessary, why limit the size to 72 points? Maybe some guy viewing his monitor from across the room while he rides his exercise bicycle, might want 158 points.

They are called "preferences" because, well, they are inherently subjective.

**Comment by lupusA** [comment]
Hi @Yekutiel,

I can add the other options to make it even bigger. However, the reason I used the pre-defined classes is, that it is more convenient. 

If I choose to enter numbers, I have to style every component. This would include buttons etc. That's a lot of work until it looks right :-)

**Comment by Yekutiel** [comment]
I understand your situation: you indicated it would be a lot of work. I would guess you probably could have used some sort of framework or at least a library to make UI changes easier. In nearly 40 years, GUI haven't really changed much. If you were to take a look at the original Lisa/Macintosh computers, you'd see what I mean.

The following comments were posted within roughly the last hour on the front page of Hacker News. No, I'm not being snarky, but, well, yeah, I'm telling you that KopiaUI is pet project sitting in an uncanny valley.

https://news.ycombinator.com/item?id=38598031

> After a day of playing with the free version of Resolve in 2017 I gave BlackMagic some cash for a license & capture card for audio

I see you've came to the same conclusion i did years ago. I look at it not as paying for software, but buying my time back at this point.

Linux "open source"/free professional software seems to lack the Je ne sais quoi needed to make it worthwhile. It works, but the software is in the "uncanny valley" so to speak compared to polished Mac/Windows paid professional software. 


**and**


https://news.ycombinator.com/item?id=38598202

A lot of open source projects suffer from “pet project” syndrome. Some maintainers have very strong opinions about how/what things should be done regardless of actual user demand or feedback, and there’s no one with the power to rebuff them because the product owners deciding what to implement and the engineers doing implementation work are one and same. Commit right makes might.

In a (healthy) company, you have PMs and executives who will tell the overly opinionated engineers to STFU and actually implement things that move the needle and solve problems users are facing.

This is also why most open source projects have terrible UI/UX and any designer who attempts to help and improve things finds themselves ignored, with no means to actually carry out any decision, and walk away soon after.

**Comment by lupusA** [comment]
Hi @Yekutiel, 

when it comes to prioritization, the product owner of an application (or a product in general), decides what items create a benefift for the product. He or she strives to increase the value of the product and make decisions accordingly.

The need to actually increase the fontsize in px or dimension or in any other scale is very specific. I guess that the current implementation would actually satisfy the request of being able to increase the font :-) Therefore, I can create a PR and make the feature available for discussion. Behind the scenes, there is a lot of work needed to make such an easy feature functional. The preferences has to be saved. Therefore, we need another PR for Kopia itself to extend the preferences. Furthermore, we need tests to actually cover the functionalilty to ensure that it will work in the future. 

All these things mentioned above lead me to the point to provide the feature is demonstrated:
https://github.com/kopia/kopia/assets/37236531/528bb292-88f4-4e25-acb9-eaa8345efe97

The option "larger" was added. It should be big enough to present it if needed. 
Feedback is welcomed. 

Cheers,

**Comment by Yekutiel** [comment]
> Behind the scenes, there is a lot of work needed to make such an easy feature functional...

... obviously because someone failed to properly plan for creating a robust GUI. The opinions you expressed are foolish. Your arrogance and ignorance are palpable.

**Comment by lupusA** [comment]
Pull requests are welcomed. If you want to contribute to this project, feel free create PRs.
