### ISSUE TITLE
UI: UI flickers when clicking "Snapshots" and "Policies" links (when no repository exists)

### ISSUE THREAD

**Issue by gitname** [kopia/kopia#3488]
On a fresh install of Kopia on a system without any repositories, when I click on the "Snapshots" or "Policies" links at the top of the UI, the entire UI flickers and I am sent to (or kept at) the "Repository" tab.

![2023-12-04_19-17-13](https://github.com/kopia/kopia/assets/7143133/15d80f94-8b97-435d-ae9d-cafc3717d71f)

I propose completely disabling those two links in that situation (can show a tooltip explaining why they're disabled). That will both (a) signify to the user that those two links don't work yet [the tooltip can explain why] and (b) avoid the flickering.

**Comment by gitname** [comment]
Oops! I forgot there was a separate repo for the UI. Please move the issue to: https://github.com/kopia/htmlui

**Comment by lupusA** [comment]
Hi @gitname 

thanks for reporting. This is fixed in the next version:

https://github.com/kopia/kopia/assets/37236531/bf0a0259-a705-477b-9fc9-5fa49b198151

Cheers,
