### ISSUE TITLE
UI: Task "Cancel" icon is interactive, but cursor remains an arrow

### ISSUE THREAD

**Issue by gitname** [kopia/kopia#3489]
Although the "Cancel" button is interactive, the cursor remains as an arrow instead of becoming a hand/pointer.

![2023-12-04_19-46-20](https://github.com/kopia/kopia/assets/7143133/444cc5e8-9996-46fa-8e2b-da30b70584c5)

In contrast, hovering over other interactive elements on the screen causes the cursor to become a hand/pointer. For example:

![2023-12-04_19-48-53](https://github.com/kopia/kopia/assets/7143133/88c0366a-ebcb-4c13-a675-349aa3b2a745)

The "Cancel" button may be implemented as an image with some JavaScript bound to it; instead of as an HTML button or HTML `<a>` element. Assuming that is the case, I would recommend implementing it as one of the latter. That way, (a) the cursor will signify the element is interactive and (b) the interactive element will "benefit" from other things the latter HTML elements provide "for free" (e.g. accessibility features such as tab navigation).

**Comment by gitname** [comment]
Oops! I forgot there was a separate repo for the UI. Please move the issue to: https://github.com/kopia/htmlui

**Comment by lupusA** [comment]
Hi @gitname, 

thanks for reporting. This is fixed in the next version:

https://github.com/kopia/kopia/assets/37236531/e295f498-bdfa-4eb9-a0b5-4411f2595f3a

Cheers,
