### ISSUE TITLE
UI: Tooltip is missing a word ("Snapshot will after...")

### ISSUE THREAD

**Issue by gitname** [kopia/kopia#3490]
The following tooltip is missing a word.

https://github.com/kopia/htmlui/blob/f256cf19198d12134ad76ccad4c30aaf480a5dcf/src/pages/Snapshots.jsx#L143

```jsx
            case "PENDING":
                return <>
                    <Spinner data-testid="snapshot-pending" animation="border" variant="secondary" size="sm" title="Snapshot will after the previous snapshot completes" />
                    &nbsp;Pending
                </>;
```

That is the tooltip that appears when hovering over the spinner icon (not shown here) in this column (shown here). The spinner icon is visible when a snapshot is waiting for another snapshot to finish.

![image](https://github.com/kopia/kopia/assets/7143133/bceccded-622c-4ef7-b9d0-d02e109ea185)

I assume the missing word is "start", as in "Snapshot will start after..."; but I'm not sure.

**Comment by lupusA** [comment]
Hi @gitname, 

thanks for reporthing this issue. This is fixed in the next version. 

Cheers,
