### ISSUE TITLE
Can not run maintenance

### ISSUE THREAD

**Issue by BastianLo** [kopia/kopia#3497]
I am not able to run maintenance in my repositoy. Every time i run a cli command which has something to with running the maintenance task, i get an error. Automatic maintenance also does not work

e.g. when i am running 
`kopia maintenance run`

I get the error:
`ERROR error updating maintenance schedule: error getting schedule: invalid schedule blob`

The error message suggests an invalid schedule blob. But i do not know how to fix this problem

I am running version 0.15

This is the content log when running the comand. I will of course provide additional information if requested
[content-log.log](https://github.com/kopia/kopia/files/13622201/content-log.log)

**Comment by Kemystra** [comment]
Hello, new Kopia user here!

From what I can gather from the [code](https://github.com/kopia/kopia/blob/master/repo/maintenance/maintenance_schedule.go#L115), it seems like Kopia wasn't able to get a valid schedule data from the blob `kopia.maintenance`.

Can you run `kopia snapshot verify`? My first guess here is corrupted `kopia.maintenance` blob (a blob is how Kopia repositories store data internally)

**Comment by BastianLo** [comment]
Hi, 
i can confirm that the issue is related to the kopia.maintenance blob.

I deleted the kopia.maintenance yesterday by running:
`kopia blob delete kopia.maintenance`

I am not sure if this was the correct way, but i am now able to run maintenance again. 
Kopia is now running for about 24h and i do not have any unwanted sideaffects from deleting the maintenance blob.
So the issue is fixed for me. 

Thank you!
