### ISSUE TITLE
Feature Request : Hopefully there's some way obsidian can open "Mount as local filesystem"

### ISSUE THREAD

**Issue by jiajiala** [kopia/kopia#3516]
I used kopia to back up my obsidian library

But when I use "Mount as local filesystem", I can't open it with obsidian

I can only restore it to a certain location to open it with obsidian

**Comment by lupusA** [comment]
Hi, 

KopiaUI uses fuse or WebDAV to mount snapshots. Can you link your the website of your os? 

You can also mount the snapshot using the cli: https://kopia.io/docs/mounting/

Cheers

**Comment by lupusA** [comment]
Hi @jiajiala, 

I can try to reproduce it in the next days. Can you check if running obsidian as a admin makes a difference? I am assuming you running kopia on Windows?

**Comment by jiajiala** [comment]
Yes, the windows I'm using, even running obsidian as an administrator, won't open it
![image](https://github.com/kopia/kopia/assets/73203026/3b9dc645-5a32-4f1f-bfa0-e94c39030b91)

**Comment by lupusA** [comment]
Hi @jiajiala,

the issue is that obsidian is trying to create a folder. The mounted snapshot, however, is read only.

Cheers
