### ISSUE TITLE
[Bug] KopiaUI doesn't display on Windows 10

### ISSUE THREAD

**Issue by quidnu** [kopia/kopia#3521]
Installed KopiaUI, launched for first time, configured two folders with 10 minute interval backups and ZSTD compression. After closing the UI it no longer launches (no window appears), 3 KopiaUI processes are shown in task manager. Uninstalling/reinstalling does not fix the issue.

I don't know how to debug, I don't see any logs specific to the UI. The logs seem to show the regular kopia.exe process performing the backups.

0.15
Windows 10

**Comment by lupusA** [comment]
Hi, 

Can you describe your setup in detail? Is Kopia shown in the taskbar? It should be minimized in the taskbar. Right-click on it should open the context menu. 

Cheers

**Comment by quidnu** [comment]
Thank you! I didn't see the icon in the tray (because it is hidden within the ribbon menu) and I didn't expect launching KopiaUI would start the tray service (as opposed to launching the GUI).
