### ISSUE TITLE
Two daily snapshots in the same day

### ISSUE THREAD

**Issue by jiajiala** [kopia/kopia#3533]
![image](https://github.com/kopia/kopia/assets/73203026/9220bcbd-eed2-4aa3-b941-aeb0e43008c1)
Here, there are two daily snapshots in one day

**Comment by lupusA** [comment]
Hi @jiajiala, 

i can´t reproduce it in my repository. 
![grafik](https://github.com/kopia/kopia/assets/37236531/d2fb1093-af51-4d03-8fb6-3ba074eb2e17)

It works as expected. Can you post your policies? 

Cheers,

**Comment by jiajiala** [comment]
![image](https://github.com/kopia/kopia/assets/73203026/81f37243-82d1-4dee-b144-258edb41e1e4)
![image](https://github.com/kopia/kopia/assets/73203026/5c15d945-d5f2-40b8-a271-2bc26adfa820)
Since I didn't quite understand the retention rule, I kept as many snapshots as I could to try to understand the rule

**Comment by jiajiala** [comment]
It has something to do with latitude
