### ISSUE TITLE
Set the timestamp of a snapshot

### ISSUE THREAD

**Issue by Novex** [kopia/kopia#354]
I was wondering if there's a flag for `kopia snapshot create` similar to `--hostname` that will override the timestamp of a snapshot?

We're looking at migrating from an older backup system and it would be nice to insert past backups into the kopia repository along with new ones.

**Comment by jkowalski** [comment]
Sounds like a great feature. Should be pretty simple to implement.

**Comment by Novex** [comment]
If you can give me a hint where to start I can have a crack?

**Comment by jkowalski** [comment]
https://github.com/kopia/kopia/blob/a8ef0b2b79c429381c396fdb37b8c00b31f7498b/cli/command_snapshot_create.go#L130

You can modify snapshot manifest around this line before it gets saved.
