### ISSUE TITLE
KopiaUI does not prune files after deleting a snapshot

### ISSUE THREAD

**Issue by Ivi104** [kopia/kopia#3540]
When deleting a snapshot, the expected behaviour is to delete all objects connected to that snapshot but to keep any files present in other snapshots. Presently no files get deleted.
Even when selecting "Wipe all snapshots", the repository still contains all the data previously backed up.
I feel like some kind of maintenance operation should be done immediately after deleting a snapshot.

Or at least give us a button to manually prune the repository.

**Comment by devzwf** [comment]
i can confirm this 
and i do not know how to make kopia do some house keeping

**Comment by lupusA** [comment]
Kopia runs maintenance automatically (https://kopia.io/docs/advanced/maintenance/). There is another issue that aims to do it after certain actions: https://github.com/kopia/kopia/issues/3174

**Comment by devzwf** [comment]
after investigating i think i narrow where at least my issue is .....
`ERROR maintenance must be run by designated user: x@Y`

so @Ivi104  check which user own your maintenance  with :
`kopia maintenance info`
 and make sure it s same who run your regular backup , for some reason was not the same for me.
 
 i will report back if i was able to fix my issue

**Comment by devzwf** [comment]
so i this fix my issue sort of....
i was able to run the maintenance..... (i will check where i miss the error for the maintenance could not get run )
```
# kopia contents stats
Count: 230719
Total Bytes: 331.6 GB
Total Packed: 318.3 GB (compression 4.0%)
By Method:
  (uncompressed)         count: 67704 size: 262.6 GB
  zstd                   count: 102505 size: 68.8 GB packed: 55.6 GB compression: 19.3%
  zstd-fastest           count: 60510 size: 97.5 MB packed: 33.5 MB compression: 65.7%
Average: 1.4 MB
Histogram:

        0 between 0 B and 10 B (total 0 B)
     2718 between 10 B and 100 B (total 193.6 KB)
   107087 between 100 B and 1 KB (total 46.6 MB)
    41285 between 1 KB and 10 KB (total 116.2 MB)
     6671 between 10 KB and 100 KB (total 204.2 MB)
     8370 between 100 KB and 1 MB (total 3.8 GB)
    64588 between 1 MB and 10 MB (total 314.1 GB)
        0 between 10 MB and 100 MB (total 0 B)
```

But my bucket (S3) is 2.1TB for some reason i do not understand
still investigating

**Comment by lupusA** [comment]
@devzwf you may need to select an option in your B2 repository to delete files. If you do not select it only grows. 

We had this issue in the past.

Cheers

**Comment by devzwf** [comment]
I thought about it, but i am not using B2 but Minio.
and i already check , and i have no life cycle set....

that's a great mistery.... 

PS: Anyway i am in the process of migration my Minio  from Truenas service to minio server .....but i owuld really like to understand this one :)

**Comment by lupusA** [comment]
Hi @devzwf, 

was the storage freed up by now?

**Comment by devzwf** [comment]
interestingly ..... so far NO
the storage is sitting at 2.1TB steady, with only a single bucket used only by Kopia....
go figure..

**Comment by devzwf** [comment]
No i do not use rclone
i still do not quite understand why this happen, but i migrate to an other S3 and will delete this one this week-end.

**Comment by djismgaming** [comment]
I'm having this same issue, but I do use `rclone` to Google Drive.

`kopia maintenance info` gives (no owner is set? dates back in May?):

```
Owner:
Quick Cycle:
  scheduled: true
  interval: 1h0m0s
  next run: now
Full Cycle:
  scheduled: true
  interval: 24h0m0s
  next run: now
Log Retention:
  max count:       10000
  max age of logs: 720h0m0s
  max total size:  1.1 GB
Object Lock Extension: disabled
Recent Maintenance Runs:
  full-drop-deleted-content:
    2024-05-02 10:51:15 -04 (23s) SUCCESS
  full-rewrite-contents:
    2024-05-01 10:50:49 -04 (0s) SUCCESS
  generate-epoch-range-index:
    2024-05-02 11:00:38 -04 (0s) SUCCESS
    2024-05-01 10:50:57 -04 (0s) SUCCESS
  advance-epoch:
    2024-05-02 11:00:33 -04 (2s) SUCCESS
    2024-05-01 10:50:55 -04 (0s) SUCCESS
  cleanup-epoch-markers:
    2024-05-02 11:00:42 -04 (0s) SUCCESS
    2024-05-01 10:51:00 -04 (0s) SUCCESS
  cleanup-logs:
    2024-05-02 11:01:11 -04 (1s) SUCCESS
    2024-05-01 10:51:07 -04 (0s) SUCCESS
  snapshot-gc:
    2024-05-02 10:51:01 -04 (7s) SUCCESS
    2024-05-01 10:50:35 -04 (0s) SUCCESS
  compact-single-epoch:
    2024-05-02 11:00:30 -04 (0s) SUCCESS
    2024-05-01 10:50:52 -04 (0s) SUCCESS
  delete-superseded-epoch-indexes:
    2024-05-02 11:00:44 -04 (23s) SUCCESS
    2024-05-01 10:51:04 -04 (0s) SUCCESS
  full-delete-blobs:
    2024-05-02 10:51:44 -04 (8m41s) SUCCESS
```

**Comment by tugdualenligne** [comment]
I've got the same issue and commented it in the forum here : https://kopia.discourse.group/t/cli-run-of-maintenance-not-working-cannot-free-up-space/3276

Hi, I deleted a few snapshots for several hundred Gb of data and cannot get them deleted for a good week now. When I try force a full maintenance whether or not I add the --safety=none tag, I get the following:
root@kopia3:/app# kopia maintenance run --full
ERROR maintenance must be run by designated user: root@kopia3

However, maintenance info says:
kopia maintenance info
Owner: root@kopia3

So I suspect maintenance should work. Any help / suggestion welcome!

**Comment by devzwf** [comment]
i still did not get this Fix

**Comment by jkowalski** [comment]
Try `kopia maintenance set --owner=me` - that should reset the maintenance owner, followed by `kopia maintenance run --full`.

If that does not work, try running `kopia maintenance run --full --force` - this is only safe if you know no other maintenance is running, but should delete the unwanted files.

**Comment by devzwf** [comment]
is there a way to make sure no other maintenance is running ?

**Comment by jkowalski** [comment]
That's generally automatic - kopia will only run at most one maintenance only when `username@hostname` matches maintenance owner and will use file locks to ensure that even if two processes start it, only one will actually run.

**Comment by tugdualenligne** [comment]
As mentioned in the Kopia forum, I did like jkolwalski said to assign the maintenance rights to anorher user, and the maintenance ran correctly, deleting the unused blobs

**Comment by julio-lopez** [comment]
> That's generally automatic - kopia will only run at most one maintenance only when `username@hostname` matches maintenance owner and will use file locks to ensure that even if two processes start it, only one will actually run.

@jkowalski This is safe only if:
- there wasn't another client executing maintenance already (with the previous owner);
- and the previous repository owner has updated its own state to realize it is no longer the repo owner.

IOW, the two cases described above are among the various potential scenarios that could lead to simultaneous maintenance execution and potential repo corruption.
