### ISSUE TITLE
[Fedora 39] KopiaUI Opens to Grey/Blank Screen

### ISSUE THREAD

**Issue by DarkArc** [kopia/kopia#3546]
When I open Kopia UI I just get this:

![image](https://github.com/kopia/kopia/assets/778012/9de0ee33-ecd2-4bbf-8d77-bebd636228d6)

Oddly it seems like it's trying to use Nvidia drivers on an AMD system? From the terminal:

```
Found package-type: rpm
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
libva error: /usr/lib64/dri/vdpau_drv_video.so init failed
```

**Comment by lupusA** [comment]
Hi @DarkArc, 

i've tested it with a virtual machine, using Fedora 39. It works -- after installing the appindicator extension. Is kopia running? What is your setup?

Cheers,

**Comment by DarkArc** [comment]
I think it's definitely something that requires non-virtualized hardware.

```
Operating System: Fedora Linux 39
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.6.9-200.fc39.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 7950X 16-Core Processor
Memory: 61.9 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT
Manufacturer: ASUS

(Produced by KInfoCenter)
```

**Comment by lupusA** [comment]
Hi, 

There are some issues that basically refer to not using the correct driver. Maybe this helps: 

https://github.com/plexinc/plex-media-player/issues/633#issuecomment-396365947

**Comment by DarkArc** [comment]
Mysteriously, it started working again today after a system update. It looks like mesa updated; perhaps there was a regression in mesa responsible.

I'll go ahead and close this, thanks.
