### ISSUE TITLE
web-page cleanup, "Common Commands" page is a messy

### ISSUE THREAD

**Issue by BWWIT** [kopia/kopia#3552]
Page: https://kopia.io/docs/reference/command-line/common/

I think these link should be deleted, right?
![image](https://github.com/kopia/kopia/assets/151644805/ed5b95d1-6ba9-43bf-acf9-ab62ccf55838)

I gladly do it, but what's up with the "Edit this page", is that suppose to work? It doesn't seem to:
![image](https://github.com/kopia/kopia/assets/151644805/95704898-fa16-4827-b3fe-7c7f13387a28)

![image](https://github.com/kopia/kopia/assets/151644805/7df2a57b-96bd-4556-9cc2-426c34729c36)

**Comment by lupusA** [comment]
Hi @BWWIT, 

the command section is generated while building the website. Therefore, there is no source in the repo to edit. We can hide the summary and refactor the building process for the API commands.

Cheers
