### ISSUE TITLE
Export the function `newOptionalInt` and `newOptionalInt64` from `snapshot/policy`

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [kopia/kopia#3556]
I am using kopia as a library in my own project. As such when I needed to create policies, I need the ability to easily create optional integers. I see that `NewOptionalBool` was recently made exportable and due to that I can use it directly instead of re-implementing it.

It would be great if the above 2 functions can also be exported.

**Comment by julio-lopez** [comment]
Feel free to copy the functions for your own use.

Kopia should instead narrow down its interface by reducing the number of exported functions.

**Comment by SayakMukhopadhyay** [comment]
Well, I am indeed re-implementing the function locally already. Any reason why you feel that Kopia should narrow down the interface?
