### ISSUE TITLE
flush error: error waiting for async writes: EOF: EOF

### ISSUE THREAD

**Issue by xshyne** [kopia/kopia#3567]
Hi,

I get around 20% of my backups that fail with this error. it seems random as i can run it 5 times in row without any issue and then it fails. 
This problem happens just with one of my client but never with others. 
On this client i have a backup bigger than others (around 20Go but with really not a lot of change) and with action that last around 1min. 
I use kopia server behind nginx, but i don't have any error in logs of these.

```
Snapshotting user@server:/folder1 ...
 - 0 hashing, 1 hashed (36 MB), 16785 cached (19 GB), uploaded 36.1 MB, estimated 19 GB (99.9%) 0s left
Snapshotting user@server:/folder2 ...
Snapshotting user@server:/folder3 ...
[31mERROR[0m flush error: error waiting for async writes: EOF: EOF
```
Do you have any idea how to fix it ? i tried all my ideas 

Edit :
I tried to add the flag `--flush-per-source` when i do the snapshot and the error message changed but it's still random : 
```
ERROR encountered 3 errors:
cannot save manifest: error putting manifest: EOF: EOF
error listing previous snapshots: unable to find manifest entries: EOF: EOF
error listing previous snapshots: unable to find manifest entries: EOF: EOF
```

**Comment by cgspeck** [comment]
I'm also having this problem, with Kopia on one linux machine backing up to Kopia Server on another linux machine behind Nginx.There are no errors in the Kopia logs on either end, nor in the Nginx logs.
