### ISSUE TITLE
FR: Repository search

### ISSUE THREAD

**Issue by gerroon** [kopia/kopia#3568]
Hi

It would be awesome if one could search all the files in a repository without mounting all snapshots of all versions. It could be just a basic search like file name. I have a repo with like 20+ different snapshots. Mounting all that up on Windows and try to search through them would be so much work. It would be a like a snap if it was part of Kopia.

Thanks

**Comment by lupusA** [comment]
Hi @gerroon, 

thanks for reaching out. This would be a nice feature which was already requested (https://github.com/kopia/kopia/issues/2495) I am closing this issue to keep it clean :-)


Cheers,
