### ISSUE TITLE
Checkbox status in KopiaUI is not changed until clicking off

### ISSUE THREAD

**Issue by basldfalksjdf** [kopia/kopia#3580]
Small bug in KopiaUI on Windows. Clicking on a checkbox does not show a change in its status, so it appears as if the checkbox is not being clicked. In other words, clicking a checked box does not show it as unchecked and vice versa. You need to click the checkbox and then click elsewhere in KopiaUI to see whether the checkbox has been checked or unchecked.

**Comment by lupusA** [comment]
Hi @basldfalksjdf, 

It is a css issue. I fixed it for restoring snapshots but there are pages where it still occurs. I will take a look. 
Thanks for the hint.

Cheers

**Comment by lupusA** [comment]
Hi @basldfalksjdf , 
which checkboxed were affected? I've fixed the ones under "Restore" a while ago. However, as we had no release since then, the fixed code is still no released yet.

I just wanted to confirm in case i've missed some checkboxes. 

Cheers,

**Comment by basldfalksjdf** [comment]
There are checkboxes affected by this issue at:

-Setting/changing policies
-During initial setup of a repo
-Viewing snapshots
-Restoring snapshots

There may be more that I cannot think of

**Comment by lupusA** [comment]
Can you ping me on slack? I think it is already fixed in the current build. 

Cheers,

**Comment by lupusA** [comment]
Hey @basldfalksjdf, 

the issue should be fixed in 0.16.1. Can you check?

Cheers,

**Comment by basldfalksjdf** [comment]
Issues are fixed. Thanks.
