### ISSUE TITLE
A large number of empty folders remain

### ISSUE THREAD

**Issue by jiajiala** [kopia/kopia#3592]
Can I delete these empty folders？

affecting the speed at which I can copy them to another place

![image](https://github.com/kopia/kopia/assets/73203026/13aa2bb4-c5f7-4daf-8ad8-f54bc7e4f984)

**Comment by lupusA** [comment]
Duplicate as the topic is already addressed in https://github.com/kopia/kopia/issues/2600. I am closing this issue.
