### ISSUE TITLE
Manual maintanance always run full maintance

### ISSUE THREAD

**Issue by ErKeye** [kopia/kopia#3600]
No matter de option used, manual maintenance allways trigger a full maintanance task:

kopia maintenance run                             => not expected
kopia maintenance run --full                    => expected
kopia maintenance run --no-full               => not expected

**Comment by 9-2-1** [comment]
The question has been answered in kopia forum.

> **[jkowalski](https://kopia.discourse.group/u/jkowalski) on [Aug '22](https://kopia.discourse.group/t/kopia-maintenance-cannot-choose-quick/1364/2)**
> 
> Full is the only mode now for recent repositories. Quick maintenance only made sense for legacy formats.
> 
> We should probably hide this flag.

Copied from https://kopia.discourse.group/t/kopia-maintenance-cannot-choose-quick/1364

**Comment by ErKeye** [comment]
So then an updato to website reference is needed.
