### ISSUE TITLE
How can I delete this unused repository?

### ISSUE THREAD

**Issue by FeiLZX3Km** [kopia/kopia#3612]
![b375343ab83302c2074c55f0fca99682](https://github.com/kopia/kopia/assets/21981195/fa15a284-3a80-476b-97cd-b107d8a2b385)

**Comment by lupusA** [comment]
Hi @FeiLZX3Km, 

there is a primary repository that cannot be removed. You probably mixed these up. Disconnect from "My Repository" (noting down the credentials), open that window and close it. It should disappear from the list. Open then the first one and reconnect to your repository.

Cheers,

**Comment by lupusA** [comment]
Please comment if you need further support. 

Cheers,
