### ISSUE TITLE
Avoid index (epoch) cleanup and compaction during index reads

### ISSUE THREAD

**Issue by julio-lopez** [kopia/kopia#3638]
## Objectives
- Increase safety in terms of repository consistency.
- Improve user experience by providing a consistent expected behavior in terms of duration of operations and resource utilization.

## Current Issues:

Currently, kopia is performing writes on the index load path.
- This is not desirable for read-only operations. It is also surprising for the user (See #3639).
- It delays the completion of other commands such as `repository connect` or `snapshot list` among others.
- Results in unexpected high resource utilization due to aggressive parallelism.
- Has the potential for duplicated (and wasted) work. Two clients, or in some cases the same client may perform the same expensive work multiple times. For example, the same epoch could be compacted more than once.

**Comment by julio-lopez** [comment]
Proposed approach

- [ ] Add a flag to disable index write operations during index loads and preserve current behavior.
- [ ] Explicitly perform index cleanup during maintenance:
  - single epoch compactions
  - epoch range compaction
  - epoch advancement
  - epoch marker cleanup
  - deletion watermark cleanup
- [ ] Disable by default write operations on index load using the mechanism implemented in 1.
- [ ] Long term: completely remove from index loading all the codepaths that perform index writes, and remove the flag that controls this behavior.

**Comment by julio-lopez** [comment]
Index loading simplified call graph

![eim-call](https://github.com/kopia/kopia/assets/1953782/2b8ebd20-4789-42f4-a2c2-c893bc750f58)

**Comment by ashmrtn** [comment]
silly question, but I could use a little extra context: what type(s) of maintenance will allow index compaction? Will it be full and quick maintenance or just one of them?

**Comment by julio-lopez** [comment]
> silly question, but I could use a little extra context: what type(s) of maintenance will allow index compaction? Will it be full and quick maintenance or just one of them?

Good question.

The approach implemented in the current PR is as follows.

For quick maintenance:
- Single epoch compactions
- Epoch advancement

For full maintenance:
- Single epoch compactions
- Epoch range compaction
- Epoch advancement
- Epoch marker cleanup
- Deletion watermark cleanup

Does that make sense?

**Comment by ashmrtn** [comment]
Thanks for the info Julio! The details you laid out make sense from an understanding perspective

However, looking at the additional info I'm unsure how to feel about the range compaction being in full maintenance. I don't have hard numbers, but I feel like it starts to turn the index compaction/data blob compaction into a bit of a balancing act. Keeping the index compacted with range compactions helps reduce GETs and general load time to do any work on the repo. However, if it's with full maintenance, which also does data blob compaction, power users need to consider the cost of potentially compacting data blobs which could trigger GET requests to slower storage tiers

Do you have any thoughts/guidance on this?

**Comment by julio-lopez** [comment]
@ashmrtn The change should not adversely impact users, and instead in some cases result in resource savings, potentially including fewer storage requests (GETs, etc). Overall, this does not change the effective frequency of single epoch or range compactions. See details below.

Here's the reasoning, based also on observations with various repositories:

- The actual (effective) frequency of single epoch compaction would remain the same, it would happen ~ every 24 hours or so. What could change is that it "may" be delayed by about 4 hours in the worst case. Given the current default parameters, the minimum epoch duration is 24 hours (AND a minimum number of index blobs). The difference is that instead of implicitly checking every 15 minutes, the check would happen on every maintenance execution (both quick and full), which by default would be done every 4 hours. 

- The actual (effective) frequency of epoch range compaction would remain the same, it would happen every 7 epochs with default parameters, this is roughly ~7 days for repos with enough churn. In the worst case scenario, the range compaction could be delayed ~24 hours, since this would be done in full maintenance. Notice that at this point single-epoch compacted indexes are already being used for these epochs and not the individual raw indexes that get originally written. And for older epochs, the previously range-compacted indexes will be used.

Does that make sense? Does that answer your question?

**Comment by julio-lopez** [comment]
PR sequence:
- #3603
- #3645
- #3709
- #3721
- #3735
- #3728
- #3651
- #3646
