### ISSUE TITLE
Is no password/passwordless repository possible? 

### ISSUE THREAD

**Issue by benibilme** [kopia/kopia#3656]
Hello,

I am a long time borg/borgmatic user, and trying out kopia. I would like to create passwordless repository but kopiaUI does not allow me!  I have not seen anything in the documentation about creating passwordless repo. 

All my backups are in encryted luks drives, and they are mounted only before backup. I do not backup to remotes and I do not want to forcefully use passwords, manage those secrets in vault like structures.  

Is is possible to create no passwod repo? 

Sorry about making this question an issue. 

Thanks in advance.

**Comment by julio-lopez** [comment]
There is no support for passwordless repositories.
