### ISSUE TITLE
kopia.exe: error: unknown long flag '--config'

### ISSUE THREAD

**Issue by badrelmers** [kopia/kopia#366]
Hi,
First thank you for this excellent work.

I think I have found a small bug:
if I change the config file path in **kopiaUI** in _server configuration_ I get this error:
kopia.exe: error: unknown long flag '--config', try --help

![image](https://user-images.githubusercontent.com/40046489/77017625-389e1700-697b-11ea-82e7-d1d51f40fec6.png)

kopia.exe command do not have any flag called `--config`, but there is one called `--config-file`

The same happen in the documentation : here https://kopia.io/docs/reference/command-line/ 
it says: `--config-path`  but the command line do not have this flag, it should be `--config-file`

kopia v0.5.2 on windows 7

thank you.

**Comment by jkowalski** [comment]
Yeah, it's a typo in `server.js`. If you'd like to hack on a PR to fix it, that should literally be a one-line change and I'll be happy to merge it.

Unfortunately there is no good way to test this yet, other than manual (I wish we had some test harness here).

**Comment by badrelmers** [comment]
I never did an edit in github, I will attempt.
Unfortunately there is no good way to test this yet, other than manual (I wish we had some test harness here).
I'm using Kopia on windows so I can do the tests on it, but in fact I do not know which tests should I do. I do some basic testing but I do not know the internals of Kopia. if I can do anything please tell me.

**Comment by jkowalski** [comment]
to test, simply build it and run it:

make goreleaser
make kopia-ui

**Comment by jkowalski** [comment]
BTW the automatic build with the fix is: https://github.com/kopia/kopia-ui-release/releases/tag/20200319.0.1705 - it will also auto-update

**Comment by badrelmers** [comment]
thank you.
I could not build it in windows, i m still attempting to find why
all I got is that:
```
D:\zbala\kopiabuild\kopia>make -d goreleaser
GNU Make 4.3
Built for Windows32
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Reading makefile 'tools/tools.mk' (search path) (no ~ expansion)...
Creating temporary batch file D:\Users\LLED2\AppData\Local\Temp\make2528-1.bat
Batch file contents:
        @echo off
        date +%Y%m%d
CreateProcess(D:\Users\LLED2\AppData\Local\Temp\make2528-1.bat,D:\Users\LLED2\Ap
pData\Local\Temp\make2528-1.bat,...)

```

as you see no error no warning! I gave it an hour but it is still blocked or waiting for something.
