### ISSUE TITLE
feature request: add config flag to kopia UI

### ISSUE THREAD

**Issue by badrelmers** [kopia/kopia#367]
Hi,
is it possible to add some basic cli flags to Kopia GUI, so we can deploy it easier. 
I mean to have the flag --config-file at less.
it would be nice to have an option to pass the flags to kopia cli.
thank you

**Comment by jkowalski** [comment]
There are 2 configs:

1. kopia.config
2. kopia-ui (that stores things you set up in configuration window, including location of the first config). 

I presume you mean the latter.

**Comment by badrelmers** [comment]
yes I mean the second, but I thought the 1 and 2 are the same.  now that I know I hope we can have both. 
in fact this feature is the same to https://github.com/kopia/kopia/issues/368 , I only want to make Kopia UI portable and scriptable.

**Comment by jkowalski** [comment]
Assuming KopiaUI supports portability (#368), is that still needed?

**Comment by badrelmers** [comment]
it depends of this https://github.com/kopia/kopia/pull/398#issuecomment-618864822

if you accept to make Kopia UI fully portable then this feature is not needed, but if not then it would be nice to have this flag.
