### ISSUE TITLE
Question: does Kopia require additional local space when backing up?

### ISSUE THREAD

**Issue by mmenozzi** [kopia/kopia#3675]
Let's say I have a volume total size of 130 GB with 30 GB of free space and 100 GB of used space, all in the `/var` folder.

Let's also suppose that all the content in the `/var` folder are files that will not be smaller if compressed.

Now let's say I want to backup with Kopia to an S3 compatible storage the entire `/var` folder.
May I encounter a "no left space on device" error? I mean: does Kopia backs up directly on S3 or it needs space to create the snapshot on the local storage and only after that it will upload to S3?

**Comment by julio-lopez** [comment]
The short answer is:
- Local space **is required** to accommodate: (1) the content indexes for the whole repository; and (2) metadata, such as directory info, from the previous snapshot of the same source (volume, directory, etc). These are the ones that come to mind first.
- The snapshot data is directly written to the storage backend (S3), and it is by default cached locally as well.

There are a few flags to control the size and behavior of the various local caches, which allow you to specify their location on local storage and help you constrain their size.

I hope this helps.

**Comment by mmenozzi** [comment]
Thanks!
