### ISSUE TITLE
Deprecate HTTP Repository API in v0.16

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#3716]
Repository server has had its GRPC API be the default for the last 3 years and the old HTTP API is incomplete/incorrect in some corner cases. We should deprecate it in 0.16.0 and remove entirely in 0.17.0.

Note: this does not impact the control API or the API used by the KopiaUI and only removes low-level methods:

```
/api/v1/flush
/api/v1/repo/parameters
/api/v1/contents/{contentID}
/api/v1/contents/prefetch
/api/v1/manifests/{manifestID}
/api/v1/manifests
/api/v1/policies/apply-retention
```

In 0.16 we should flip `--legacy-api` default from `true` to `false` to identify folks who depend on it and prompt them to upgrade it's going to be removed in 0.17.

After 0.16 is released we should remove:

* `func (s *Server) SetupRepositoryAPIHandlers(m *mux.Router)` and server implementations
* `api_server_repository.go` and all related code+tests

**Comment by julio-lopez** [comment]
addressed in #3745
