### ISSUE TITLE
improve SEO inside github search

### ISSUE THREAD

**Issue by badrelmers** [kopia/kopia#372]
Hi,
few people know that when using the github search for searching repositories, github will not use the readme or the content of the repo to find the results. github use only the description to find the results.

 I mean this description:

![image](https://user-images.githubusercontent.com/40046489/77058024-25b83080-69d5-11ea-9503-75d5cb219fda.png)

this is why you should include all the important keywords inside this description if you want to appear in the repo search of github, see this test:

I will search for this sentence from the readme : client-side end-to-end encryption, compression and data deduplication.

github shows 0 results:

![image](https://user-images.githubusercontent.com/40046489/77058511-d6263480-69d5-11ea-9d7e-96abb98a13fe.png)

 Now let s see the result when searching keywords from the description, like :Fast and secure open-source backup:

![image](https://user-images.githubusercontent.com/40046489/77059789-cb6c9f00-69d7-11ea-80ce-d68e0908f447.png)

so I propose to include this in the description to improve the SEO inside github:

> Kopia is a simple, cross-platform tool for managing encrypted backups in the cloud **or locally**. It provides fast, incremental backups, secure, client-side end-to-end encryption, compression and data deduplication. It comes with an automatic **shceduler**, and include a **GUI** to manage backups. for **Windows, macOS, and Linux**. https://kopia.io

**Comment by jkowalski** [comment]
Edited description a little bit, thanks for the suggestion.
