### ISSUE TITLE
Global dot-ignore file has not effect at all

### ISSUE THREAD

**Issue by dexx086** [kopia/kopia#3737]
I think dot-ignore files are not working as expected.
I created a repo, added "global" dot-ignore file (that's outside of the source data itself, because I want to have them on a centralized, "config" level folder, not inside the source folder itself) to the global policy, but exclusion from this dot-ignore file doesn't seem to do anything.

I created a simple bash script reproduction in a /tmp/kopia folder (with local repo):
```
# Prepare FOLDERS, FILES
mkdir /tmp/kopia
cd /tmp/kopia
mkdir data
mkdir repo
echo "test" > ./data/test.txt
echo "ignore!" > ./data/ignoreme.txt

# Init REPO
KOPIA_PASSWORD=test123 kopia repository create filesystem --path=/tmp/kopia/repo
echo "**ignore**" > ./.kopiaignore

# Set POLICIES
kopia policy set --global --add-dot-ignore /tmp/kopia/.kopiaignore
kopia policy set --global --log-entry-snapshotted=5

# SNAPSHOT
kopia snapshot create /tmp/kopia/data/ --log-dir=./logs
```
From a `kopia ls -r k<...>` command I see this:
/ignoreme.txt
/test.txt

But the "ignoreme.txt" **should not be there**, as it expected to be excluded with the `**ignore**` pattern that's defined in the global `.kopiaignore` file! And I see in the log it was simply snapshotted: `DEBUG uploader snapshotted file     {"path":"ignoreme.txt","dur":"1.370887ms","size":8}`

However, if I copy the global `.kopiaignore` file to `/tmp/kopia/data/.kopiaignore` (as a 'local' override), it works as expected, `**ignore**` files are excluded.

Am I doing something wrong with my "global" `.kopiaignore` file? It's listed in the policy's "Read ignore rules from files" section, I don't see any reason why it's not taking effect at all.

Moreover: if I specify a **non-existing file** as dot-ignore file to the global policy, it doesn't complain about its absence (I can enter anything...). **It should at least check if the file itself exists, doesn't it?** Especially when creating a snapshot... if an exclusion file was specified, I would abort the snapshot creation if it's not even found.

Thanks for any feedback on this.

**Comment by ingul-buz** [comment]
It seems to me that your rules are working as expected. There is no "global .kopiaignore file", global ignore rules are defined in the "Ignore files" list of the global policy only.

If you look at the "Ignore Rule Files" section of the global policy in KopiaUI, you can see this description over there:

> List of additional files containing ignore rules (each file configures ignore rules for the directory and its subdirectories)

And in the Kopia documentary:

> While scanning directories and their content, Kopia looks explicitly for files that contain such rules. If such a file is placed within a directory, Kopia omits files and folders matching the rules.

You can set it in the global policy, but that doesn't mean it's a global rule file. It just defines the _name_ of the rule file. You can name it whatever you like, and it doesn't have to exist anywhere. Kopia does check if it exists (in any of your directories), and follows the rules if it does, but doesn't complain if it does not (which is good, I think).

Additionally, you can define a rule file name (also a different one) in each of your directory policies, and they apply to that directory only. And they also must be placed within that directory.

**Comment by dexx086** [comment]
@ingul-buz Thanks for your reply!

> ... It just defines the **_name_** of the rule file....

Aha, I see where I'm misled... In the docs of policy set, I saw this:
`--add-dot-ignore			List of paths to add to the dot-ignore list`

"List of `paths`..." (!) In this case I think "paths" it's not correct, because as you wrote it's handled as "name" of the ignore files, which then makes sense why are handled at (each) directory's level, and why it doesn't complaint if the file doesn't exists.
So I think it would worth fixing the "paths" to "filenames", right?

Then as I see, I have no option to have my global ignore file other than the root of the folder I'm starting my backup... even symlinkinkg from my config folder's file to "target folder/.kopiaignore" is not working, because I saw another request to follow symlinks at least for .kopiaignore files, but that's still open.

**Comment by imbear** [comment]
> You can set it in the global policy, but that doesn't mean it's a global rule file. It just defines the _name_ of the rule file. You can name it whatever you like, and it doesn't have to exist anywhere. Kopia does check if it exists (in any of your directories), and follows the rules if it does, but doesn't complain if it does not (which is good, I think).

For now I create a hard link to the "global ignore rule file"(maybe ~/.kopiaignore) in the different snapshot folders for sharing the ignore rules, Is it a easiest way?

**Comment by dexx086** [comment]
> For now I create a hard link to the "global ignore rule file"(maybe ~/.kopiaignore) in the different snapshot folders for sharing the ignore rules, Is it a easiest way?

I don't think so. My original thoughts was misled by the (I think typo) "List of `paths`...", because as it turned out, it's not how it works (it can define only "filenames" to be used as "rule files", like .kopiaignore).
So for now, I don't see any option to have global rules, only global filenames which could alter the rules on the current folder levels, but only for those and its subfolder levels. So for each snapshot folders, need to hard link / copy the root level .kopiaignore files, as those must be inside the folder structure you want to snapshot.
