### ISSUE TITLE
backup (kopia-ui) gave up because of a permission denied error

### ISSUE THREAD

**Issue by rhd** [kopia/kopia#374]
Hi, I'm not sure if this is by design or a bug... but I was using kopia-ui to backup a folder and when I pressed the `Snapshot Now` button, it ran for a few seconds and then just stopped - no error in the UI or anything. I ran it from the command line and this is the log...

```
23:31:53.086 [kopia/server] starting upload of rhd@desktop:/home/rhd/Downloads

23:31:53.898 [kopia/server] upload error: unable to process directory "hplip-3.19.3": open /home/rhd/Downloads/hplip-3.19.3: permission denied
```

When I `chown`'d the directory, the backup worked.

I'd expect the backup to backup everything it could and somehow tell me there were problems.

Thanks! This seems like a really nice tool...

**Comment by jkowalski** [comment]
Thanks for the report.

There is a way to set policy (either globally or per directory) to ignore errors, but unfortunately the default is to fail hard and that's not obvious to users. We should make this obvious.

@julio-lopez what do you think of ignoring errors by default? we should also somehow communicate __which__ directories failed to snapshot via the manifest and somehow present that in the UI/CLI.

**Comment by ntolia** [comment]
I think the experience for users (and for the project) will be much worse if there are relatively silent failures that someone only figures out on restore. That would be bad on many fronts. 

I believe the current behavior is the right one for most users and, IMO, the issue seen here was the right thing as it makes it obvious some data wasn't captured. That said, to decrease support cost and folks having to file issues, we should warn when this happens. A combination of docs, UI hints, and a website FAQ on how to address this issue will probably go a long way.

**Comment by jkowalski** [comment]
I think we should raise awareness of these errors during snapshots and in Kopia UI:

here's my CLI improvement attempt (PR coming soon):

https://asciinema.org/a/dOLXrnUZBnfEjxyKR1nLqphJN

**Comment by rhd** [comment]
Another use case with the `abort-by-default` behavior is when there is a successful backup and then subsequent backups silently fail... the only way to tell by paying attention to the `Last Snapshot` time.

**Comment by jkowalski** [comment]
I think all those issues could be fixed by always saving the snapshot manifest, even for failed snapshots. We can mark them as incomplete with reason `failed` or something like that. 

@ntolia @julio-lopez thoughts?
