### ISSUE TITLE
Fail to build in Windows

### ISSUE THREAD

**Issue by badrelmers** [kopia/kopia#375]
Hi,
I build like that
```
make goreleaser
make kopia-ui
```

but it fail because the makefile use `date `of `bash `and not of `cmd`
here https://github.com/kopia/kopia/blob/master/tools/tools.mk
it use `date +%Y%m%d` , so it suppose bash/linux `date `command , but in windows there is another command with the same name `date ` and it behaves differently.
I solved it using powershell like that:
for 
`date +%Y%m%d`
I used
`powershell -noprofile -executionpolicy bypass -Command "(Get-Date).ToString('yyyyMMdd')"`

and for 
`date`
I used
`powershell -noprofile -executionpolicy bypass -Command "(Get-Date).datetime"`

powershell is installed by default on everything form Windows 7/Win2008 and above.

now it build and both the CLI and UI work fine. 
should I send a PR?

**Comment by jkowalski** [comment]
PR would be great. I actually ran into this yesterday when trying somehting on Windows, but did not think of a solution.

**Comment by jkowalski** [comment]
Thanks for the fix!
