### ISSUE TITLE
fix(deps): Minio SDK object put memory alloc pressure

### ISSUE THREAD

**Issue by aaron-kasten** [kopia/kopia#3766]
Fix Kopia memory pressure problems related to Minio buffer allocation.

Minio prefers clients who implement all the seekable interfaces that include `io.Reader`, otherwise it will fall back to stop-gap wrappers that provide the needed interfaces.  These stop-gap wrapper implementations allocate large amounts of memory, which can cause memory overrun.

Completion of this ticket will attempt to mitigate memory overrun by providing an seekable wrapper that uses less memory.

**Comment by julio-lopez** [comment]
Fixed in #3695

Thanks @aaron-kasten
