### ISSUE TITLE
Ignoring directories has no effect on snapshot

### ISSUE THREAD

**Issue by genseirin** [kopia/kopia#3772]
I'm using KopiaUI v0.16.1 on Windows 11 and I try to exclude the paths of WSL images:

```
C:\Users\Someone\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu22.04LTS_79rhkp1fndgsc
C:\Users\Someone\AppData\Local\Packages\KaliLinux.54290C8133FEE_ey8k8hqnwqnmg
C:\Users\Someone\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04LTS_79rhkp1fndgsc
```

The documentation is not clear, but from other Issues I understood that each path must be entered in a new line, that paths are defined with forward slashes without any drives (Unix style, even for Windows) and each path starts from root. Is that correct?

So I end up with the following definition in the "Ignore Files" field:

```
/Users/**/AppData/Local/Packages/CanonicalGroupLimited.*
/Users/**/AppData/Local/Packages/KaliLinux.*
```

When I then create a manual snapshot, however, these three paths are still included. Is it a problem with my "ignore files" definition?

**Comment by lupusA** [comment]
Hi @genseirin, 

if the ignore rule starts with ```/``` then it is evaluated from the root directory. So if the snapshot is taken from "C:\Users" then you have to adjust your ignore rules is little bit. 

Maybe ```/**/AppData/Local/Packages/CanonicalGroupLimited.*``` or ```**/AppData/Local/Packages/CanonicalGroupLimited.*``` is already enought to match for different users.

**Comment by genseirin** [comment]
Ah, thanks, so the "root" of the ignore rule is relative to the snapshot directory, not the root of the drive? I'll give it a try.

**Comment by lupusA** [comment]
Otherwise, ping me on slack.

**Comment by lupusA** [comment]
Hi @genseirin, 

is it solved?

**Comment by genseirin** [comment]
@genseirin I'll know only on Monday when I have access to the same computer again.

**Comment by genseirin** [comment]
I tried with `/**/AppData/Local/Packages/CanonicalGroupLimited.*`  and this works. So my mistake was to use the absolute path, instead of starting from the "snapshot root".

Thanks!
