### ISSUE TITLE
kopia UI Appimage do not run in Linux when user-namespace is disabled (Debian default)

### ISSUE THREAD

**Issue by badrelmers** [kopia/kopia#379]
Hi,
I cannot run Kopia UI in a default Debian install.

running without root gave:

`:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_KopiaUgODIXY/chrome-sandbox is owned by root and has mode 4755.
`

with root gave:

`:FATAL:atom_main_delegate.cc(211)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
`

Debian and some other Linux distros come with user-namespace disabled by default. enabling it solve my problem, but it need root.

it can be enabled with:
```
#temporary until reboot
sysctl -w kernel.unprivileged_userns_clone=1
#or permanent:
echo 'kernel.unprivileged_userns_clone=1' > /etc/sysctl.d/00-local-userns.conf

```
but not everyone can do it, it needs root and enable name space globally !

but if we are root then the appimage can simply do the following to solve it:
```
chown root:root './kopia-ui/linux-unpacked/chrome-sandbox' 
chmod 4755 './kopia-ui/linux-unpacked/chrome-sandbox'

```

a third and better solution is to run Kopia UI with --no-sandbox flag. this do not need root.

as I know --no-sandbox is dangerous only with web pages because the browser can run bad things, but Kopia UI is not a browser and will not run strange scripts from the WWW, so I think disabling the sandbox has no side effect for the end user.

the Signal [developers](https://github.com/signalapp/Signal-Desktop/issues/3627) say:

>  "We will not be forcing a root setuid on our users to solve this problem. Running signal-desktop with --no-sandbox is our solution."

more comments about this: From bitwarden https://github.com/bitwarden/desktop/issues/286

> hadrcoding --no-sandbox argument in AppImage's AppRun script will solve the issue (this approach is already applied for the recent electron-builder versions, but only for the Snap target so far). Running the app like ./my-app.AppImage --no-sandbox is also a workaround.

there is a long discussion about this in electron page:
https://github.com/electron/electron/issues/17972
some comments  from there:

> Unfortunately there's no way we can configure this correctly automatically, because setting the appropriate permissions requires root privileges and we don't want to ask for a root password during npm install.

> As far as I know, packaged into the Snap/AppImage build loader-like bash/sh script that starts the original binary/electron with --no-sandbox cmd argument is the only verified workaround for now.

**Comment by jkowalski** [comment]
Should we attempt to fix it ourselves in a script vs wait for a fix upstream?

**Comment by badrelmers** [comment]
sorry, I could not understand what you mean, do you mean to fix it inside Kopia UI vs wait for debian to fix it when they pack it as deb package? if yes , then I think an appimage is a portable app so it should work directly when we run it.

**Comment by jkowalski** [comment]
I found this:

https://github.com/cozy-labs/cozy-desktop/commit/5e7762c96c82c530165fe3deef507efd0eb65a66

which seems to be a workaround for the same issue another project is doing. Since you have an environment that repros this issue, would you be able to take a stab at making similar change for Kopia?

**Comment by robertfoss** [comment]
I hit this issue too, and it was very not obvious what the issue was.
