### ISSUE TITLE
vss: do not have Administrators group privileges (permission denied)

### ISSUE THREAD

**Issue by jniggemann** [kopia/kopia#3798]
* Kopia v0.16.1
* Windows 1022H2
* my user is in the local admin group
* VSS Service running
* VSS enabled via `policy set D:\outlook --enable-volume-shadow-copy when-available `
* trying to backup a pst file usually locked by outlook

When triggering a backup via KopiaGUI "snapshot now", no VSS is used. Changing policy to "always", I get
`2024-04-12T17:19:18.995314Z ERROR kopia/server snapshot error: snapshot task: upload error: vss: do not have Administrators group privileges (permission denied)`

Using a non-elevated cmd, I can create and delete vss manually.

@mxk What may I be missing?

**Comment by jniggemann** [comment]
Got it, TY

**Comment by xieve** [comment]
Small addendum: To execute KopiaUI with sufficient privileges **on boot**, deactivate "Launch at Startup" in Kopia and create a new task in the task scheduler to run KopiaUI.exe at system startup, then check "Run with highest privileges" in the "General" tab. Also go to "Settings" and uncheck "Stop the task if it runs longer than 3 days".
