### ISSUE TITLE
Kopia UI cannot take snapshots when path ends with"/"

### ISSUE THREAD

**Issue by badrelmers** [kopia/kopia#380]
any folder I add gave this error when I take a snapshot:
```
06:04:39.433 [kopia/server] upload triggered via API: badr@g118:/media/data1/_/_code/

06:04:39.434 [kopia/server] starting upload of badr@g118:/media/data1/_/_code/
06:04:39.434 [kopia/server] upload error: open /media/data1/_/_code/_code: no such file or directory

```

it seems that the path is parsed incorrectly, I told him to snapshot ../_code but it attempted to snapshot ../_code/**_code**  which is incorrect.

![image](https://user-images.githubusercontent.com/40046489/77242894-cbe97d80-6c03-11ea-92be-5368f0dc3f5c.png)

thank you

**Comment by badrelmers** [comment]
the problem happens only if I add a path which ends with `/`
adding `/path`   works fine
adding `/path/` gaves the error I described above.

**Comment by jkowalski** [comment]
Fixed in https://github.com/kopia/kopia/releases/tag/v0.8.0-beta1
