### ISSUE TITLE
Feature request: Password is useless when encryption is disabled 

### ISSUE THREAD

**Issue by badrelmers** [kopia/kopia#381]
Hi,
If I create a repository without encryption, next time I reopen the repo again it open with any password!
this is not dangerous because the files are already not encrypted in the disk , but it gave to the user a sensation that the application is not safe because he can open his repo with any password (in the beginning I thought it is a security bug, and it is after two days that I noticed it is not dangerous).

I think it is better to gave an option to not create the repo with a password, and show the password only if we choose encryption. if the user opt for no encryption then the password should be hidden.

I mean to have something like that:
when we open Kopia UI and choose filesystem , then the user will be prompted with 

- Directory Path:` /..`

if the directory has already a database and it is encrypted then ask the user to put the password
if the directory has no database then ask how we want the repo  to be created:

- Encryption: `yes `(default)/`no`

If I choose encryption then I get the rest of options, and here I have to put the password twice... etc
If I choose no encryption then finish and do not prompt for a password.

**Comment by jkowalski** [comment]
What complicates this UX scenario is connecting to existing repo - we need to show the password prompt somewhere. Ideas welcome.

**Comment by jkowalski** [comment]
BTW, unencrypted repos are not really recommended, is there a reason you need repo to be unencrypted?

**Comment by badrelmers** [comment]
how about this:
if you accept this request https://github.com/kopia/kopia/issues/382 : add multiple repos and switch between them from the UI, then we will have something like that:
the first thing we get after opening Kopia UI is two options: setup a new repo, or connect to an already configured repo:

![image](https://user-images.githubusercontent.com/40046489/77258852-94b7b280-6c7d-11ea-96a7-ace08ad0f971.png)

**Option 1:** setup a new repo:
![image](https://user-images.githubusercontent.com/40046489/77258904-f710b300-6c7d-11ea-8f63-ed47bdac3462.png)

**Option 2:** open/connect to an already configured repo:
![image](https://user-images.githubusercontent.com/40046489/77258988-933aba00-6c7e-11ea-9442-623f1639e6b0.png)

_____________________
this means that we will be using only one repo at the same time, when we switch between repos Kopia UI will act like if we had disconnected and opened a new repo, 1 server in any time.

but I think it will be nice to have multiple repos opened at the same time using one instance of Kopia UI, but this means to change the UI totally, like for example add tabs, and every tab have a repo. if you prefer this then tell me to suggest another UI design. thank you

**Comment by badrelmers** [comment]
In fact there is something I do not like in the actual scheme:
Kopia UI do not gave any option to stay as a continuous server, if I open a repo, then the server of the actual opened repo should be disconnected and no sync is done until I reopen this repo again.

If we add **"multiple repos"**, this will be solved, because every repo will have its server running so sync will not stop.
If we add **"switch between repos"** as I suggested above, this problem will not be solved.

I will suggest a design for **multiple repos**...

**Comment by badrelmers** [comment]
design for multiple repos connected at the same time:
it will be nice to have the repos in tabs like this:
![Untitled-6](https://user-images.githubusercontent.com/40046489/77262226-e0298b00-6c94-11ea-9709-4bcdabc54b1c.png)


if tabs are not an option then we can use a dropdown instead.

> BTW, unencrypted repos are not really recommended, is there a reason you need repo to be unencrypted?

the most important reason is that if I lose the password I still can access the content of the files some how. and I do not need to encrypt inside my home. and I think that encrypting things in the cloud is useless with the supercomputers of today.

**Comment by jkowalski** [comment]
I like your mocks, there are however reasons why we can't switch between repos within this window (because it's served by one kopia server), but nothing prevents having more windows, each served by its own kopia server. I'll try to prototype the UI for this.

**Comment by badrelmers** [comment]
I like this, it is better. thanks  you

**Comment by jkowalski** [comment]
Closing for now, I've put NONE algorithm on deprecated list, which means it cannot be used to create new repositories. If there's strong pushback we can reconsider.
