### ISSUE TITLE
Feature request:  add an option to use more than one repository at the same time

### ISSUE THREAD

**Issue by badrelmers** [kopia/kopia#382]
Hi,
I hope you can add an option to use more that one repository at the same time, or gave an option to switch between repos easily, maybe adding a list of used repos in Kopia UI 
I could not find any way to connect for example to my local repo and my server repo at the same time. I have to disconnect every time and put the password to connect , and do it again to come back. this make it a hard experience.

Thank you.

**Comment by jkowalski** [comment]
That's a great idea. Not sure how to surface it in the UI, though.

**Comment by badrelmers** [comment]
how about something like this:
a dropdown list that contain the list of repositories that we have used before
![image](https://user-images.githubusercontent.com/40046489/77256660-ea855e00-6c6f-11ea-91cf-2c06dc888008.png)

then choose from there the repo like that:
![image](https://user-images.githubusercontent.com/40046489/77256703-28828200-6c70-11ea-8026-2f15bdcb06d9.png)

**Comment by jkowalski** [comment]
A major complication that `kopia server` only supports one repo at a time and server is the one that serves the UI HTML and API for it. But I guess we could launch N servers at a time and that would allow you to have N UI windows open.

**Comment by badrelmers** [comment]
Great, Kopia server is lightweight anyway. and I think it is better to have N server, so if one repo crash, it will not crash the other repos.
