### ISSUE TITLE
Flags documentation blocked in git

### ISSUE THREAD

**Issue by CompuRoot** [kopia/kopia#3827]
Is there reason to ignore documentation in [site/content/docs/Reference/Command-Line/.gitignore](https://github.com/kopia/kopia/blob/master/site/content/docs/Reference/Command-Line/.gitignore)
that block content to
```
Common/
Advanced/
flags.md
```
especially **`flags.md`**, where documented some flags that not even available neither in    
`kopia --help-long` nor in `kopia --help-full` (as an example: `--[no-]progress` flag) and the only [presented online](https://kopia.io/docs/reference/command-line/flags/).

**Comment by julio-lopez** [comment]
These are auto generated.

**Comment by CompuRoot** [comment]
> These are auto generated.

Do you plan to include content of 
```
Common/
Advanced/
flags.md
```
here, in git (remove from `.gitignore`) and of cause in the `kopia` `--help-*` options so program options would be available to discover without using kopia.io web site?
