### ISSUE TITLE
Remove support for unencrypted repos

### ISSUE THREAD

**Issue by julio-lopez** [kopia/kopia#388]
Support for the "no encryption" cipher should be disabled in released kopia binaries. It should only be used for testing purposes.

This avoids unintentional and incorrect misuses.

**Comment by ntolia** [comment]
I would strongly agree. It does not make sense to have a "no encryption" for end-users. Misconfiguration here would be the equivalent of open AWS S3 buckets. The only legitimate use case I see for "no encryption" is internal benchmarking and overhead measurement.

**Comment by jkowalski** [comment]
#381 is going in the opposite direction, we need to reconcile. I think I like having repos be always encrypted. @badrelmers thoughts?

**Comment by ntolia** [comment]
Systems should always be secure by default and it should be really hard to circumvent security. In this case, having to build from source might be an appropriate bar in case people REALLY want no security (but why?!?).

**Comment by badrelmers** [comment]
I see that you all agree to make encryption mandatory, so I also agree. My desire came from laziness only and not a necessity.

**Comment by SynapseScribe** [comment]
this is just dumb. as a user i just want to backup a folder, on my pc, no need to encrypt..
