### ISSUE TITLE
FR: option to run a script before and after accessing repository to create a snapshot

### ISSUE THREAD

**Issue by badrelmers** [kopia/kopia#394]
Hi,
Is there a possibility to add an option to run a script before saving the snapshot and after saving the snapshot? 

Why I need this?
For security reasons I use a Port Knock to access my SSH server, so I need to send some packets to the server so the ssh port get open.
Now to let Kopia UI connect to my ssh automatically I need to disable the port knock completely.

Thank you.

**Comment by jkowalski** [comment]
My initial instinct is that scripting at this point is probably too advanced, you can always have a script that periodically knocks your SSH, can't you? 

Having said that, I would be open to some scripting/hooks in the future, but I don't want to increase cognitive load on people now with too many advanced options just yet.

(the scripts I was thinking of would allow you to take consistent snapshot of a directory before it is uploaded or drain writes from a server for similar reason, and perhaps do some cleanup afterwards, but again - that's not something that's being worked on anytime soon)

**Comment by badrelmers** [comment]
> you can always have a script (cron) that periodically knocks your SSH, can't you?

it is hard to do because I do not know when Kopia UI scheduler will run. Port Knocks generally wait few seconds to make a connection to the opened port, if not then the port is closed again.

I hope it can be done someday. thank you

**Comment by jkowalski** [comment]
the SSH connection will not be totally idle between snapshots, in fact every few minutes it will need to download the index (list of `n` files) to discover if there are any new snapshots. not sure if this helps or hurts your scenario, though.

(I tried port knocking in the past but gave up exactly because of complexities like that)

**Comment by badrelmers** [comment]
this is good to know, thank you.

I cannot live without the port knock (it saves me of a lot of headache), so I solve it for now with this gymnastic:
1. run an another sshd (port 922)  inside the server that listens **locally**:
`sudo /usr/sbin/sshd -d -D -p 922 -o ListenAddress=127.0.0.1 -f /etc/ssh/sshd_config_less_secure
`

2. create a permanent relay to this sshd using forward connection which open the port 19999 locally in my laptop
`ssh -N -tt -L 19999:localhost:922 -o ExitOnForwardFailure=yes -i ${ssh_key} ${ssh_user}@${ssh_IP} -p ${ssh_port}
`

3. configure Kopia UI to connect to localhost:19999 using ssh_user and ssh_key (it must be localhost , Kopia UI did not accept 127.0.0.1)


there is only one problem : if the connection is lost Kopia UI do not alert me that the backup is not done, it fails silently, no alert no error 
logs says that:
```
10:02:48.123 [kopia/server] upload triggered via API: LLED2@lled2-pc:F:\_bin\_bin\_backup\kopia\_source
10:02:48.128 [kopia/server] starting upload of LLED2@lled2-pc:F:\_bin\_bin\_backup\kopia\_source
10:02:48.129 [kopia/upload] unable to read previous directory entries: unexpected content error: failed to send packet: EOF
10:02:48.132 [kopia/server] created snapshot 97c7959f00b707eb3a95e628e8f9b184
10:02:48.133 [kopia/server] unable to flush: error writing previously failed pack: error writing pack: can't save pack data content: cannot create temporary file: failed to send packet: EOF
```

then no backup can be done again , I have to restart Kopia UI to make it work again!

**Comment by julio-lopez** [comment]
Does #722 completely solve this issue?

**Comment by jkowalski** [comment]
This actually is a slightly different case. This FR is to support running scripts before accessing repository (to establish a tunnel where repository can be reached).

**Comment by julio-lopez** [comment]
Oh, got it! Thanks for the clarification.
