### ISSUE TITLE
Information on synchronisation

### ISSUE THREAD

**Issue by coolmule0** [kopia/kopia#3942]
More of a discussion than an issue.

The use of synchronization seems perfect for my use case. I want to back up to one of the supported cloud storage locations, as well as a local storage with multiple snapshots. However, I'm finding the documentation a little light on details and questions I have. This makes me err on using it. I like using the UI where I can because I prefer the how it displays the clarity of information.

- Are there benefits to having the local sync to the cloud, or vice versa? For example, the documentation for synchronisation says
> When synchronizing to a filesystem location, it is important to check that the filesystem is mounted correctly. To ensure that Kopia will not unnecessarily download potentially large repositories when destination filesystem is accidentally unmounted, pass --must-exist

 Which sounds like there might be a better way to do this

- What is available on KopiaUI for synchronisation? Certain other pages explicitly inform when commands are needed on the command line (such as the [maintenance advanced page](https://kopia.io/docs/advanced/maintenance/))
- Is synchronizing explicitly needed each time to update between the repositories? Or do the two repositories remain linked and changes to the main repo reflect in the synced repo?

Many thanks

**Comment by ados8** [comment]
Looking into this myself and haven't found documentation to outline the specifics when using KopiaUI.

**Comment by Ultranium** [comment]
> * Are there benefits to having the local sync to the cloud, or vice versa?

Well, when synchronizing a local repo to the cloud, you save on download traffic, if this is something you are concerned about.
On the other hand, making a backup to cloud first is beneficial should something bad happen to both your client machines and the local repository (power spike/fire/flood etc.).
