### ISSUE TITLE
Docker overlay2 folder is too huge.

### ISSUE THREAD

**Issue by TristisOris** [kopia/kopia#3984]
`overlay                             67G   62G  2.6G  96% /var/lib/docker/overlay2/f4cf099fa878f2c71dba950e50b331dff1e26beb90a3b53255bbb9bc3303af8d/merged
`

It takes more space than on host with dozens of containers. I don't think it's expected.

**Comment by mstenzel70** [comment]
I don't think this is related to Kopia. According to docker-compose the following directories are mounted:
```        volumes:
            # Mount local folders needed by kopia
            - /path/to/config/dir:/app/config
            - /path/to/cache/dir:/app/cache
            - /path/to/logs/dir:/app/logs
            # Mount local folders to snapshot
            - /path/to/data/dir:/data:ro
            # Mount repository location
            - /path/to/repository/dir:/repository
            # Mount path for browsing mounted snaphots
            - /path/to/tmp/dir:/tmp:shared```

**Comment by TristisOris** [comment]
all of them is mounted.

i moved 20Gb 'cache' folder to external storage. but it makes kopia to run for 10min first time and few minutes at every launch.
logs folder takes 1.5G.
/tmp folder is empty.

overlay still takes 10Gb.
