### ISSUE TITLE
FR: Add configurable per-folder splitter policy

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#399]
(This was originally suggested by Bruno on Slack)

It is desirable to be able to specify custom splitters on a per-directory basis, similar to how compression works. The main use case is more efficient backup of certain kinds of data (like VM disk images, Minecraft maps, etc.) where fixed splitters may be more efficient than rolling hashes.

Also, for this reason we should consider adding fixed splitters with smaller block size (128KB, 256KB, 512KB, in addition to 1,2,4 MB).

**Comment by pawitp** [comment]
Can I suggest per-extension as well? I don't it think makes sense to apply rolling hash on compressed media such as JPEG.
