### ISSUE TITLE
FR: Add configurable before-upload/after-upload scripts for directories.

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#400]
Use cases:

- when backing up certain directories, we may need to instruct some daemon to flush writes and hold them in memory until directory has been saved

- another use case would be taking ZFS or BTRFS point-in-time snapshots of a directory and working off that, instead of source data that keeps changing

- custom notifications after snapshot success/failure

This could be done via policies attached to FS nodes.

**Comment by badrelmers** [comment]
can this FR solve this https://github.com/kopia/kopia/issues/394 ?
thank you

**Comment by jkowalski** [comment]
See https://kopia.discourse.group/t/design-additional-features-for-snapshot-creation/197

**Comment by julio-lopez** [comment]
Related to #709
