### ISSUE TITLE
FR: Mount snapshots from kopia UI

### ISSUE THREAD

**Issue by jmar71n** [kopia/kopia#404]
Hi,
Currently to restore a folder we need to use the cli. Correct me if I'm wrong.. It would be great if we could mount snapshots from the UI so that restoring folders can be performed with normal copy/paste operation.

Alternatively would it be easier to allow for folders as well as files to be restored within the UI.

Thanks..

**Comment by badrelmers** [comment]
In fact Kopia UI already mounts the snapshot,and we can restore files from the UI, but file by file , we cannot restore a folder.

I hope we can have this feature too.
Thank you.
