### ISSUE TITLE
logging option to write to stdout

### ISSUE THREAD

**Issue by jeacott1** [kopia/kopia#4050]
afaict kopia only has options to log to files, but when running from kubernetes or some other container host it's typical to write logs to stdout. It's also a normal part of the 12 factor thinking. ref: https://12factor.net/logs

I know I can mod the docker image and add named pipes to route log output to stdout, but I think it would be better if kopia had the option itself, or at least if the docker container had an out of the box option to write to stdout.

thoughts?

**Comment by julio-lopez** [comment]
kopia logs to `stderr` and the level can be controlled with `--log-level=[debug|info|warn|error]`

**Comment by argh-tom** [comment]
Hi! Can we disable logging to a file but leave the log in stdout? So that systemd handles log rotation itself?
