### ISSUE TITLE
Relax And Recover (ReaR) integration 

### ISSUE THREAD

**Issue by Emera1dKing** [kopia/kopia#4096]
Relax And Recover (https://github.com/rear/rear) is a FOSS bare metal backup program that can use other backup programs to handle the file side of things. It is very modular and already has official Borg integration. Kopia integration for it would be excellent since it would uniquely offer a FLOSS, bare-metal, push based, lock free, live snapshot capable (https://kopia.io/docs/advanced/actions/#lvm-snapshots) backup solution.

**Comment by julio-lopez** [comment]
This should be done in the ReAR project or in a separate project.

**Comment by schlomo** [comment]
Hi, I'm one of the authors of ReaR and I'd be happy to talk about potential integrations.

@julio-lopez are you interested in adding bare metal restore support for Kopia? Or do you maybe already have a solution for that? The whole point of ReaR is to add bare metal restore support to existing backup software that doesn't have it.
