### ISSUE TITLE
kopia repo sync-to `destination repository contains incompatible data`

### ISSUE THREAD

**Issue by coolmule0** [kopia/kopia#4099]
I have two repos. One local filesystem, one in B2 storage with object locking enable. The filesystem repo already contains snapshots, the B2 storage bucket is freshly initialized (on the B2 site, as well as confirmed created within Kopia with `kopia connect b2...`).

## Steps to reproduce
- Connect to the local filesystem repo (`kopia connect filesystem ...`)
- Run the command `kopia sync-to b2....` to the B2 bucket.
- Obtain the following error:
```
kopia repo sync-to b2 --bucket=b2-name --key-id=xxx --key=xxx
Synchronizing repositories:
  Source:      Filesystem: /path/to
  Destination: B2: b2-name
NOTE: By default no BLOBs are deleted, pass --delete to allow it.
ERROR destination repository contains incompatible data
```

This seems to occur because there are files already in the B2 repo, created by using kopia commands, for example connecting. With a b2 repo without object locking, it is trivial to delete the files, and the sync-to works. However, with [ransomware protection](https://kopia.io/docs/advanced/ransomware-protection/) changes like object locking, some of these files cannot be immediately deleted.

I guess a related question is, can a repository without object locking and retention-mode (i.e. the local filesystem repo) be used to synchronise to a cloud repo with these features?

Thanks in advance

**Comment by alexbarton** [comment]
Just stumbled upon this issue (question) …

According to this [thread in the forum](https://kopia.discourse.group/t/kopia-repository-sync-to-filesystem/105/4), I guess you don't have to (and can't!) initialise your destination repository first.

Hope that helps!
Alex
