### ISSUE TITLE
Commitable config

### ISSUE THREAD

**Issue by DenuxPlays** [kopia/kopia#4114]
Hey,

I currently have the following problem:
I have a git repository which contains all my docker compose definitions and I want to backup all the necessary data-folders etc.

My current problem is that when I want to deploy this I would have to configure everything.
Isn't there a way to import/export the configuration (what folders to backup, schedules etc.

**Comment by xieve** [comment]
Policies are all stored in the repository, which means if you log in with a new machine, you can see the existing policies. You can create new policies programmatically via the CLI, e.g. creating a shell script from your shell history. The connection details are stored locally in Kopia's config file, which can be found via `kopia repository status`. That config file could be committed to a git repo, but if you store your Kopia repo remotely, it most likely contains authentication secrets in plain text.

**Comment by tecosaur** [comment]
Seems like this might be closed by #4020
