### ISSUE TITLE
with sftp : ssh: handshake failed: ssh: required host key was nil

### ISSUE THREAD

**Issue by flibustenet** [kopia/kopia#414]
Hi,

I'm trying to test sftp but i've this error: 

> ssh: handshake failed: ssh: required host key was nil

Just when i want to create the repository:
`kopia repository create sftp --host localhost --path /ocean/koko --keyfile ~/.ssh/id_rsa_original --username xyz
`
The same with an other host...

Maybe it's related to this ?
https://github.com/golang/go/issues/19767

Thanks

**Comment by jkowalski** [comment]
Do you have `~/.ssh/known_hosts` file in your system?

**Comment by flibustenet** [comment]
I have yes, and no problem with ssh cmd...
