### ISSUE TITLE
Release approach ?

### ISSUE THREAD

**Issue by pwnorbitals** [kopia/kopia#4201]
Hi, I see the latest release v0.17.0 dates back from April. There were lots of change since then, is a new release planned anytime soon ? Is there any specific release scheduled planned, or are releases simply done when enough changes have accumulated ? Thanks

**Comment by julio-lopez** [comment]
Short answer: no specifically planned release cadence.
@jkowalski may add more color here.

**Comment by pwnorbitals** [comment]
Interesting, thanks :) What are the thoughts for the next release ? Does it make sense to do it soon or should we wait a few more months ? @julio-lopez
