### ISSUE TITLE
Windows junction "unknown or unsupported entry type" only with self-compiled kopia.exe

### ISSUE THREAD

**Issue by Lerrissirrel** [kopia/kopia#4209]
I've only recently started using kopia - great so far!  I'm considering switching from or augmenting my Duplicati backups.

While trying to clean up all errors/warnings, I tried to use VSS.  I ran into the issue this PR is attempting to address: https://github.com/kopia/kopia/pull/3891

I'm a Linux/UNIX guy, but managed to build a version of 0.17.0 with that PR applied.  VSS worked but I got these for every "junction" on the drive (with or without VSS enabled):

```
! Ignored error when processing "ProgramData/Favorites": unknown or unsupported entry type
```

I assumed I screwed up modifying the source.  I built clean 0.17.0 source.  Same "ignored error"s with or without VSS enabled.

Running with the release 0.17.0 Windows binary kopia.exe does NOT give these "ignored error"s.

Is there a build setting I'm missing to NOT display those errors?  Is the 0.17.0 source package somehow NOT the same as the 0.17.0 Windows binary?  Am I losing my mind??

Anyone have any idea what might be going on and/or a way to silence those warnings?

**Comment by Lerrissirrel** [comment]
I'm not going to worry about it :) My backups are "clean" enough (no red triangle warning) even with this oddity.  Hoping the VSS issue gets fixed soon (I see it missed .18, though)

**Comment by Lerrissirrel** [comment]
oops, wrong button

**Comment by riedel** [comment]
strangly I get the same problem on recent windows builds (official releases), so how was that fixed? I get it on some symlinks it seems.

**Comment by Lerrissirrel** [comment]
> I get the same problem with symlinks on Windows, so how was that fixed?

In the end, I couldn't find a pattern to when it did or didn't happen and I realized that these errors did not flag a bad backup (red coloring in cli snaphot list/red warning triangle in kopiaui).  So I just ignore them - I assume they are just an intentional warning.
