### ISSUE TITLE
kopia benchmark encryption, "--repeat" multiplies memory use

### ISSUE THREAD

**Issue by Ember-ruby** [kopia/kopia#4210]
how to reproduce: 
- run `kopia benchmark encryption --repeat=2000000 --block-size=1KB`
- note kopia taking ~2GB of RAM
- 2000000KB ~= 2GB

i will note that the smaller the block size, and more repeats, the longer it takes, maybe the memory for each previous repeat is not being cleared until the program exits?

**Comment by julio-lopez** [comment]
Pull requests welcome
