### ISSUE TITLE
rclone failing to connect to onedrive

### ISSUE THREAD

**Issue by BetaRavener** [kopia/kopia#4246]
Kopia version: docker, [kopia/kopia:latest](https://hub.docker.com/layers/kopia/kopia/latest/images/sha256-ffe26ae1df2757c42852dce62a381e3fc790e49b02370e2635bb6d0bf2aef7ef?context=explore)

## Short story:
Connection to onedrive is failing on kopia/kopia:latest due to older version of rclone. Please update rclone to v1.68.2.

## Long story:
After longer trip and reconnecting my setup to network, I've noticed Kopia container is not starting. I couldn't even enter the web interface. Executing `docker logs kopia` showed lot of:
```
Connect Error: INTERNAL: internal server error: unable to complete GetBlob(kopia.repository,0,-1) despite 10 retries: error determining sharded path: error getting sharding parameters for storage: error populating output: unexpected EOF
```

I've deleted local state and tried to recover the repository from remote, but during setup after entering rclone remote path and executable directory, I got the same error as above.

Few hours later, upon further investigation I managed to get some insight what might be wrong:
```
root@nuc_kopia:/app# rclone --version
rclone v1.63.1
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-112-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.6
- go/linking: static
- go/tags: none
root@nuc_kopia:/app# rclone cat onedrive-nas:Backups/Kopia
2024/11/15 23:09:37 ERROR : .shards: Failed to open: unauthenticated: Unauthenticated
2024/11/15 23:09:37 ERROR : .shards-8277595220093893369: Failed to open: unauthenticated: Unauthenticated
2024/11/15 23:09:38 ERROR : kopia.blobcfg.f: Failed to open: unauthenticated: Unauthenticated
...
```
Note that `rclone ls` didn't have issues listing the objects so there is a limited access to the repository.

Then luckily I have stumbled upon this [long thread](https://forum.rclone.org/t/onedrive-reading-file-error-io-error-unauthenticated-unauthenticated/44846/35), towards end of which the person is happy his issue is resolved by trying out rclone 1.66.0.beta on branch `fix-onedrive-auth`.

That looked promising so I've tried updating rclone manually in container to newest v1.68.2:
```
root@nuc_kopia:/app# apt update
root@nuc_kopia:/app# apt install unzip
root@nuc_kopia:/app# curl https://rclone.org/install.sh | bash
```

Repeated the `cat` test:
```
root@nuc_kopia:/app# rclone --version
rclone v1.68.2
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-112-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23.3
- go/linking: static
- go/tags: none
root@nuc_kopia:/app# rclone cat onedrive-nas:Backups/Kopia
{"default":[3,3],"maxNonShardedLength":20}
{"default":[3,3],"maxNonShardedLength":20}
...
```

Tried the web interface on clean local state, same steps as above, and got asked for Repository Password, after which bit of sitting through "Initializing Repository..." and I had my repository back.

**Comment by jkowalski** [comment]
Kopia 0.18.x now bundles the latest `rclone`.
