### ISSUE TITLE
0.18.0 - unable to derive cache encryption key from password: unsupported key derivation algorithm:

### ISSUE THREAD

**Issue by tessus** [kopia/kopia#4254]
After upgrading from 0.17.0 to 0.18.0, I get the following error message on the client (repository server is running 0.18.0):

# client 0.18.0

```
ERROR failed to open repository: error opening content cache: unable to derive cache encryption key from password: unsupported key derivation algorithm: , supported algorithms [pbkdf2-sha256-600000 scrypt-65536-8-1]
ERROR open repository: unable to open repository: error opening content cache: unable to derive cache encryption key from password: unsupported key derivation algorithm: , supported algorithms [pbkdf2-sha256-600000 scrypt-65536-8-1]
```

# client 0.17.0

```
ERROR failed to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = access denied for a@b: EOF
ERROR open repository: unable to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = access denied for a@b: EOF
```

I just want to point out that my entire backup infra is now unusable due to this issue.

**Comment by MiRei777** [comment]
Exactly same issue after upgradin to 0.18. 
Backup via cli works perfect. 

The BackupUI is not able to connect to the server:

10:02:04.559 unable to check for updates: unable to open update state file: open /xxx/yyy/.config/kopia/repository-1698753691000.config.update-info.json: no such file or directory

10:02:04.559 password for /xxx/yyy/.config/kopia/repository-1698753691000.config retrieved from password file

10:02:04.559 failed to open repository: error opening content cache: unable to derive cache encryption key from password: unsupported key derivation algorithm: , supported algorithms [pbkdf2-sha256-600000 scrypt-65536-8-1]

##Nevertheless, many thanks for this great backup system.

**Comment by tessus** [comment]
For me neither the cli nor the UI works.

**Comment by MiRei777** [comment]
Here is some additional informations: 
All systems Kopia 0.18. All Deban systems version 12.8.
My Kopia server runs on Debian and the web interface works fine.
Two of my clients work under Arch, the CLI works there,
but the KopiaUI does not.
The CLI does not work on my Debian systems (version 12.8).

**Comment by jkowalski** [comment]
Thanks for the reports. Please roll back the server to 0.17 for the time being, sorry about the disruption.

Can you run `$ kopia blob show kopia.repository` and share `keyAlgo` ?

**Comment by jkowalski** [comment]
Can you also check in your `apiServer` section of `repository.config`? Do you have `localCacheKeyDerivationAlgorithm` field present?

**Comment by timoschwarzer** [comment]
My Linux server and clients (all CLI) work fine, I only have this issue with KopiaUI on Windows.

The Server shows `scrypt-65536-8-1` as `keyAlgo`. Trying to run `kopia blob show kopia.repository` on my Windows clients immediately leads to the error outlined in the OP. I do not have a `localCacheKeyDerivationAlgorithm` field in my repository config.

**Comment by jkowalski** [comment]
A test build that fixes the issue is available in - https://github.com/kopia/kopia-test-builds/releases/tag/v20241117.0.101500

I'll release v0.18.1 hot fix shortly.

**Comment by MiRei777** [comment]
Thanks a lot!
Beste Grüße
Michael Reinhold

Gesendet von meiner mobilen Aparatur

17.11.2024 19:38:09 Jarek Kowalski ***@***.***>:

**Comment by jkowalski** [comment]
A new release https://github.com/kopia/kopia/releases/tag/v0.18.1 is now available.

**Comment by tessus** [comment]
@jkowalski thank you. sorry that I didn't reply earlier. I was not feeling too well and slept all day.

0.18.1 solved most of the issues, but I still have a problem with the repository server and one of my clients.

All of the commands are issued on the repo server.

My conf hasn't changed since 2023:

```
# ll /root/.config/kopia/repository.config
-rw------- 1 root root 514 2023-06-30 14:54 /root/.config/kopia/repository.config
```

I start the repo server with systemd:

```
[Unit]
Description=Kopia Server
After=syslog.target
After=network.target

[Service]
Type=simple
EnvironmentFile=/etc/kopia/server.cfg
ExecStart=/usr/bin/kopia server start \
 --tls-cert-file /etc/kopia/kopia.crt \
 --tls-key-file /etc/kopia/kopia.key \
 --address 0.0.0.0:443 \
 --config-file=/root/.config/kopia/repository.config \
 --log-level=error \
 --file-log-level=error \
 --log-dir=/var/log/kopia
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

My server env file that includes the passwords hasn't changed either:

```
# ll /etc/kopia/server.cfg
-rw-r----- 1 root root 332 2023-06-30 15:20 /etc/kopia/server.cfg

# cat /etc/kopia/server.cfg
# Server Control Credentials - used for server operations
#KOPIA_SERVER_USERNAME=server-control # default: server-control
KOPIA_SERVER_CONTROL_PASSWORD=*redacted*
# Access to https://kopia:443
#KOPIA_SERVER_USERNAME=kopia # default: kopia
KOPIA_SERVER_PASSWORD=*redacted*
# Log location
KOPIA_LOG_DIR=/var/log/kopia
```

However, all of a sudden, I get the following message when I want to refresh the server (btw, this always worked): 

```
# kopia server refresh
ERROR error running http request: Post "http://127.0.0.1:51515/api/v1/control/refresh": dial tcp 127.0.0.1:51515: connect: connection refused
```

Hmmm, ok, then I thought I specify the address:

```
# kopia server refresh --address https://kopia:443
ERROR 401 Unauthorized
```

I was able to fix the client connect issue by deleting the user on the server and creating it again.

However, there is a major inconsistency of users and password definitions on server, client, and env variables. I opened an issue (#3098) a while back, but it was ignored. I think there is also the same terminology used for different users and passwords. I will add more info to that issue, because it doesn't belong in this PR.
