### ISSUE TITLE
Can't connect from some machines after updating to v0.18.1 and also can't set a password

### ISSUE THREAD

**Issue by oderwat** [kopia/kopia#4257]
After upgrading to v0.18.1 I can't connect from 2 of 4 machines (that I checked so far).

The users that can't connect are relatively new and where created with the v0.17.0 server / clients.

When trying to re-set the password I get:

```
$ kopia server users set root@machine --ask-password
Enter new password for user root@machine:
Re-enter password for verification:
ERROR error setting password: unsupported hash version (0)
```

**Comment by jkowalski** [comment]
can you try reconnecting on one of them?

**Comment by oderwat** [comment]
I can not set the password of a user while being on the repository server itself. How should I even connect to the repository from another system to that server?

Deleting the user and adding it back did work. After that I could connect with that user from the machine that did not work anymore.

**Comment by oderwat** [comment]
Just to add to that: As I downgraded to v0.17.0 the very same clients could still connect. Can it be that there is something similar to the v0.18.0 problem going on, with the PWs being encoded with a now unsupported hash?

**Comment by jkowalski** [comment]
@julio-lopez this looks like an issue related to user/password hash management. Could you take a look?

**Comment by bbccdd** [comment]
Same problem here. Using amd64 downgrading to v0.17.0 fixed it:

wget https://github.com/kopia/kopia/releases/download/v0.17.0/kopia_0.17.0_linux_amd64.deb
dpkg -i kopia_0.17.0_linux_amd64.deb

Thanks @oderwat for reporting and @julio-lopez for the quick fix!

**Comment by julio-lopez** [comment]
@bbccdd Have you been able to confirm the fix works for you?
Thanks.
