### ISSUE TITLE
mount is not working in windows

### ISSUE THREAD

**Issue by badrelmers** [kopia/kopia#433]
Hi,
I followed the [getting-started](https://kopia.io/docs/getting-started/) , everything works fine but the mount section:
`kopia mount ...` gaves this error in `win7`:
```batchfile
Server listening at http://127.0.0.1:9998/ Press Ctrl-C to shut down.
System error 67 has occurred.

The network name cannot be found.

01:52:28.415 [kopia/cli] unable to browse 127.0.0.1:9998: unable to mount: exit status 2
01:52:28.416 [kopia/cli] server shut down with error: http: Server closed
```
I followed different guides to solve it but nothing worked:

- http://bestdav.com/mount_drv_xp.htm
- https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/98a552dd-117a-4051-a863-7518bc62abb6/cannot-map-webdav-from-server-2008-error-67?forum=windowsgeneraldevelopmentissues
- https://github.com/cryptomator/cryptomator/issues/210
- https://github.com/cryptomator/cryptomator/issues/378
- https://support.microsoft.com/en-us/help/843156/you-receive-a-system-error-67-has-occurred-the-network-name-cannot-be
- https://docs.microsoft.com/en-us/iis/publish/using-webdav/using-the-webdav-redirector
- https://support.microsoft.com/en-us/help/875441/you-may-receive-a-the-network-name-cannot-be-found-error-message-when
- https://serverfault.com/questions/308781/webdav-system-error-67-in-windows-xp
- https://serverfault.com/questions/522994/mount-webdav-as-drive-in-windows-8
- https://answers.microsoft.com/en-us/ie/forum/ie8-windows_other/windows-7-webdav-web-folders-support-for-64bit/a48a13a3-b9c4-4d4f-a3cd-47ce9e52d7a9

I think this may be helpfull from the first link:

> **WebDAV Mini Redirector (XP, Vista, and Win7)**
> The second generation Microsoft WebDAV client is called WebDAV Mini Redirector and allows one to map a WebDAV location to a Drive letter the same way as if you were using a Windows File Sharing/SMB/CIFS share.
> 
> **WebDAV Mini Redirector limitations:**
> -No support for secure connections (HTTPS) on Windows XP. There is support on Windows 7, but it does not always work. It is inconsistent.
> -Your WebDAV server must be using port 80, the default port.
> -Typically fails when transferring larger files.
> -Gets confused if the user does not have access to read and/or write to a file or directory.
> 

Thank you.

**Comment by jkowalski** [comment]
On windows you need to use drive letter as an endpoint. 

Kopia mount <hash> z:

Should do it.

**Comment by datenleck** [comment]
With current version "v0.6.0-rc2" on windows I cannot connect to a **nextcloud** webdav directory as repository. The documentation lacks examples for webdav. To an **owncloud** webdav directory it is not woking, too.
