### ISSUE TITLE
consider switching to github.com/hanwen/go-fuse because github.com/bazil/fuse dropped support for Mac

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#453]
also, if we could support fuse on Windows (via Dokany, etc.) that would be even better.

**Comment by julio-lopez** [comment]
Context: bazil/fuse@60eaf8f

**Comment by rjkroege** [comment]
Maybe use Webdav on Apple Silicon Mac? WebDav seems to work well for `rclone` (which has the same problem with fuse on MacOS)? It would seem possible to change the Kopia build to use this?

**Comment by jkowalski** [comment]
Fixed with #829

**Comment by GwynethLlewelyn** [comment]
It should be possible to use @anacrolix's own fork of bazil/fuse, which is a drop-in replacement (no code changes necessary) which provides the exact same functionality — plus working macFUSE 4+ support.

You can get it from here: https://github.com/anacrolix/fuse
