### ISSUE TITLE
FR: Support Volume Shadow Copy Service on Windows

### ISSUE THREAD

**Issue by pngmn** [kopia/kopia#470]
https://docs.microsoft.com/en-us/windows/win32/vss/volume-shadow-copy-service-portal

**Comment by mfsu** [comment]
A good discussion with multiple possible solutions is at https://github.com/restic/restic/issues/340.

**Comment by sbrs3** [comment]
Kopia seems to abort creating a snapshot when it encounters a locked file on Windows (for example the file "parent.lock" in a Firefox profile while Firefox is running). Is there a way to continue snapshot creation, perhaps skipping the locked file, without implementing volume shadow copies? I'm thinking of an option like --continue-on-error.

**Comment by datenleck** [comment]
Current version "vv0.6.0-rc2" on Windows cannot make VSS-snapshots. I try to backup an Outlook PST file with a running Outlook. 
Only when Outlook is shut down the backup works.
BTW: Notice the "vv" in the version number.

**Comment by flibustenet** [comment]
One issue without vss support is that the open files during the snapshot stop all the backup. Is there a way to just ignore the open files (with a warning) and continue ?

**Comment by jkowalski** [comment]
Yes, this should do the trick

```
kopia policy set --global --ignore-file-errors true
``

Alternatively

```
kopia policy set /path/to/some/dir --ignore-file-errors true
```

**Comment by alphaleonis** [comment]
This is kind of a showstopper for me, so I'm hoping this will be implemented.  Though unfortunately it is not the most trivial thing to do, since the VSS API is far from trivial. But it should definitely be doable for a backup scenario (using it for restores as well might require more work though, but I think being able to backup locked files is the most important).  (restic seems to have a PR for this feature as well now, so perhaps some inspiration can be gathered from that :)

**Comment by chrislockwood** [comment]
This is probably the only thing stopping me (and likely others) from adopting Kopia over popular alternatives, some of which have recently introduced VSS,  hope that someone with the right level of know-how contributes in the future.

**Comment by yaakovfeldman** [comment]
You can easily do a VSS by wrapping your call to Kopia in a script that sets up the VSS yourself. Microsoft provide a tool called vshadow that make this easy enough.

https://github.com/rclone/rclone/wiki/How-to-enable-Vss-for-rclone shows how to use it to make any backup tool use VSS.

I recommend mounting the VSS as it's own drive letter as shown in variant 3 - this makes it easier to understand the path.

**Comment by cooperaj** [comment]
Thought I'd point out to people on this issue that #826 shows work that would enable this (although not built-in) is now in _master_

**Comment by mfsu** [comment]
More proposed refinements for Restic: https://github.com/restic/restic/pull/3067

**Comment by CrendKing** [comment]
Is it OK to close this now, since we have the doc to support VSS [here](https://kopia.io/docs/advanced/actions/#windows-shadow-copy)?

**Comment by julio-lopez** [comment]
#908
