### ISSUE TITLE
Root directory restored with incorrect permissions

### ISSUE THREAD

**Issue by BlackYoup** [kopia/kopia#472]
Hello,

Sorry if this issue has already been reported, I couldn't find it.

I'm currently experimenting with kopia and as such, I tried to backup a single directory to an S3 compatible backend. The snapshot creation works fine and my files are correctly sent to the S3 backend. What I did is basically `kopia snapshot create ~/my_folder`. `~/my_folder` has some files and one directory which has files too.

I then delete `~/my_folder` and try to restore it using `kopia restore k930defdc3263a46007ade216304a32f7 ~/my_folder`. Everything seems to be there again, no issue here. But somehow the `~/my_folder` folder has incorrect permissions. It only has `555` rights, not `755` and so I can't write to it anymore:

```
❯ id
uid=1000(arnaud) gid=1000(arnaud)
❯ kopia restore k930defdc3263a46007ade216304a32f7 ~/my_folder/
❯ ls ~/my_folder -lah
total 128K
dr-xr-xr-x  3 arnaud arnaud 4.0K Dec 13  1901 ./
drwxr-xr-x 86 arnaud arnaud  20K Jul 16 01:30 ../
..... my files / directory with correct rights .....
```

Also note the creation date set to 1901, not sure why.

I have this issue with both the latest `0.5.2` release and current master. I'm using go 1.14.4 and compiled the binary with `make install-noui`.

If you can't reproduce the issue on your side, I would be happy to give you more details.

Thanks!

**Comment by redgoat650** [comment]
Hey @BlackYoup -
I think [kopia snapshot restore](https://kopia.io/docs/reference/command-line/common/snapshot-restore/) will give the behavior you're looking for.

You can find the manifest ID by `kopia snapshot list --manifest-id` to find the corresponding manifest ID, which will contain restoration data on the source directory as well as the content. Then `kopia snapshot restore <manifest-id> /target/directory`.

`kopia restore` will just restore the content into whatever target directory you specify. The manifest references the content ID, as well as metadata on the containing directory. So when you restore from the manifest ID your target directory should have the same permissions/metadata as your source had at the time you created the snapshot.

**Comment by BlackYoup** [comment]
Thank you!

Indeed it seems to work better. I recall trying the `kopia snapshot restore` command but ended up with an error of `kopia: error: unable to find manifest entries: not found, try --help`. I wasn't aware of the manifest concept and I used another ID as the ID:
```
❯ kopia snapshot list --manifest-id
arnaud@exherswag:/home/arnaud/scripts
  2020-07-16 00:49:05 CEST k930defdc3263a46007ade216304a32f7 44 KB drwxr-xr-x manifest:ad4ee1edb898c3db599634b5d3a97615 files:25 dirs:2 (latest-1,annual-1,monthly-1,weekly-1,daily-1,hourly-1)
```

I first used the `k930defdc3263a46007ade216304a32f7` string thinking of it as an ID. That's probably my bad at not reading the docs correctly. I mostly used the "video" in the readme to have a grasp of how to use kopia as well as some `--help` commands.

Sorry about the noise then, I'll continue my tests :)

**Comment by julio-lopez** [comment]
@BlackYoup You bring up a real issue here about usability. In particular, that it is difficult to tell apart root ids from snapshot ids, and thus they are easily confused.

In general, but not always, root ids will have a `k` prefix. In the example above it is `k930defdc3263a46007ade216304a32f7 `.  The `k` prefix indicates that the object is a directory. However, if a snapshot were to be directly pointing to a file and not a directory, then the corresponding root id would not have a `k` prefix.

Extending the documentation may help. Any other ideas on how to improve this?
