### ISSUE TITLE
Feature Request: Support Symbolic Links During Restore

### ISSUE THREAD

**Issue by rhd** [kopia/kopia#474]
Hi, during a `kopia restore` I noticed there were lots of warnings about not creating symlinks. Here is an example:

```
23:20:39.532 [kopia/localfs] Not creating symlink "/home/rhd/src/spack/var/spack/environments/myenv/.spack-env/view/share/terminfo/z/zen30" from &{{0xc0002f2a80 0xc000180360}}                                                                                                                                                                 
```

It would be nice if kopia could also restore the symlink.

Thanks!

**Comment by eras** [comment]
Indeed! It seems though the files are there if you use `kopia mount`, but it can be quite surprising to notice later on if such files are missing; in particular as it seems to output each file written and this information isn't available at the end.
