### ISSUE TITLE
Flatpak release

### ISSUE THREAD

**Issue by darkdragon-001** [kopia/kopia#475]
Please consider packaging as Flatpak for easy cross-distribution linux compatibility.

**Comment by darkdragon-001** [comment]
See [io.kopia.KopiaUI](https://github.com/darkdragon-001/io.kopia.KopiaUI). Please check especially Author, License, Description etc. in the [appdata.xml](https://github.com/darkdragon-001/io.kopia.KopiaUI/blob/master/io.kopia.KopiaUI.appdata.xml) file.

This is based on the Debian package #478 and inspired by [im.riot.Riot](https://github.com/flathub/im.riot.Riot) and [org.signal.Signal](https://github.com/flathub/org.signal.Signal).

I would prefer if you [publish](https://github.com/flathub/flathub/blob/master/CONTRIBUTING.md) it yourself to Flathub. This way you are in charge of publishing new versions immediately when they are released. Just take my repository and file a PR against [`flathub/flathub` branch `new-pr`](https://github.com/flathub/flathub/tree/new-pr).

**Comment by darkdragon-001** [comment]
See [io.kopia.KopiaUI](https://github.com/darkdragon-001/io.kopia.KopiaUI).

@jkowalski Please check especially Author, License, Description etc. in the [appdata.xml](https://github.com/darkdragon-001/io.kopia.KopiaUI/blob/master/io.kopia.KopiaUI.appdata.xml) file.

This is based on the Debian package #478 and inspired by [im.riot.Riot](https://github.com/flathub/im.riot.Riot) and [org.signal.Signal](https://github.com/flathub/org.signal.Signal).

I would prefer if you [publish](https://github.com/flathub/flathub/blob/master/CONTRIBUTING.md) it yourself to Flathub. This way you are in charge of publishing new versions immediately when they are released. Just take my repository and file a PR against [`flathub/flathub` branch `new-pr`](https://github.com/flathub/flathub/tree/new-pr).

**Comment by jkowalski** [comment]
i'm not familiar with flatpak, but I was under the impression that all portable sandboxing environments for Linux are not really cooperating with backup tools like Kopia, since you need to disable sandbox to be able to read system files.

In any case, please ping me on Slack so we can discuss further

**Comment by darkdragon-001** [comment]
Released via https://github.com/flathub/io.kopia.KopiaUI.

Leaving this open until integrated into CI.
