### ISSUE TITLE
UI as .deb

### ISSUE THREAD

**Issue by darkdragon-001** [kopia/kopia#478]
Please package the UI also as .deb file.

**Comment by jkowalski** [comment]
Created `deb` and `rpm` packages. I would appreciate if you could take them for a spin:

https://github.com/kopia/kopia-ui-release/releases/tag/20200717.0.200337

**Comment by darkdragon-001** [comment]
The deb installs and opens fine, although it also exhibits #479: When I close the UI/server, all policy changes are lost.

**Comment by jkowalski** [comment]
cool, I think I understand #479. will close this one.
