### ISSUE TITLE
Policies not working in UI

### ISSUE THREAD

**Issue by darkdragon-001** [kopia/kopia#479]
Whenever I quit the AppImage, all policies are lost. More interestingly, if I change policies from the command line (installed via .deb), these policies are loaded whenever the AppImage is loaded. The other way round, any changes made within the AppImage are not reflected by the system.

**Comment by jkowalski** [comment]
i think the changes are buffered in memory and never flushed on server exit. This explains both behaviors.

**Comment by darkdragon-001** [comment]
I think changes should be sent out _immediately_ and _always_ after "save" button is clicked.
