### ISSUE TITLE
switch back to using v-prefixed release tags

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#485]
Apparently bare tags (0.6.0) don't work well with Golang

**Comment by julio-lopez** [comment]
When using `go get` in module mode, then releases that are not tagged with the `v` prefix are ignored.
The following gets the last release that had a `v` prefix and not the latest release:
```
GO111MODULE=on go get github.com/kopia/kopia@latest
```

**Comment by jkowalski** [comment]
This is now fixed.

**Comment by julio-lopez** [comment]
🎊 🎉 🎈 🏆 💯
