### ISSUE TITLE
gitignore Syntax problems

### ISSUE THREAD

**Issue by darkdragon-001** [kopia/kopia#492]
I am trying to ignore files. The following parts of the [gitignore format](https://git-scm.com/docs/gitignore#_pattern_format) don't seem to work:

- negated patterns prefixed with `!`
- absolute paths starting with `/`: I tried paths relative to system root (`/`) and repository root (`/home/USER` in my case)

**Comment by jkowalski** [comment]
I'm curious what are you trying to achieve here. 

In general you can attach policies and ignore rules/dotignore files to any directory in a hierarchy, in addition to that you can mark policies to either inherit from the parent or not, so you can organize your ignores in a quite flexible way.

**Comment by darkdragon-001** [comment]
I want to backup my home `~` folder but exclude `~/bin` but want to include `~/Development/bin` for example. Re-including excluded files is not supported by gitignore.

**Comment by julio-lopez** [comment]
@darkdragon-001 Could you submit a PR with your suggestions to improve the documentation? Contributions are welcome.

**Comment by darkdragon-001** [comment]
Actually, I would prefer Kopia implementing gitignore specification. This has the nice effects, that all `.gitignore` files in all backed up git repositories will be taken into account!

**Comment by jkowalski** [comment]
Looking at the code, `!` should be supported (https://github.com/kopia/kopia/blob/aa1b24762d495337583dfd0a88e4487e6742e8d6/internal/ignore/ignore.go) but it may be missing some cases/have bugs. If you have a concrete example that's not working, please add it here or in the form of a test or even better a PR with the fix 😄 

As for absolute pathnames, they are somewhat tricky, since the code to do upload is never operating on absolute pathnames, but instead it uses virtual filesystem. While this probably __could__ be fixed, it may be more tricky since the upload code is used not just for uploads from the filesystem but also repo-to-repo migrations, so definitely needs more investigation.

**Comment by darkdragon-001** [comment]
Thanks for checking and the link to the code!

I think I was testing a combination of `!` and `/path`.

Regarding absolute path names, the library should support this when setting `baseDir` correctly:
https://github.com/kopia/kopia/blob/aa1b24762d495337583dfd0a88e4487e6742e8d6/internal/ignore/ignore.go#L17

According to the [spec](https://git-scm.com/docs/gitignore#_pattern_format), absolute paths are relative to the `.gitignore` location. This is correctly implemented in the library. `baseDir` should be set to the folder where gitignore is located in. The `path` which is passed to the returned matcher object should be the absolute path of the current file to check (which is the root of the problem if I understand you correctly). This will then also work correctly when it is called with paths _outside_ of the gitignore sub-tree!

---

I think I spotted an error in `parseNonGlobPattern()`:
https://github.com/kopia/kopia/blob/aa1b24762d495337583dfd0a88e4487e6742e8d6/internal/ignore/ignore.go#L112
https://github.com/kopia/kopia/blob/aa1b24762d495337583dfd0a88e4487e6742e8d6/internal/ignore/ignore.go#L125
https://github.com/kopia/kopia/blob/aa1b24762d495337583dfd0a88e4487e6742e8d6/internal/ignore/ignore.go#L136
Should use `filepath.Match()` instead of `==` as in 
https://github.com/kopia/kopia/blob/aa1b24762d495337583dfd0a88e4487e6742e8d6/internal/ignore/ignore.go#L102
Even better would be to call `parseGlobPattern(pattern string)` instead of performing the comparison itself.
If I am not mistaken, the current situation should fail e.g. in `a/b/c*d` (when pattern contains slashes and globs in the filename component).
