### ISSUE TITLE
[KopiaUI] Download folder/selection as zip

### ISSUE THREAD

**Issue by darkdragon-001** [kopia/kopia#494]
Add option to download a folder or a selection of multiple items as zip.

**Comment by julio-lopez** [comment]
#482

**Comment by jkowalski** [comment]
Indeed, 482 will add base mechanism for that, but adding UI support is probably too big of a change to fit in 0.6 (which is already too big and overdue).

**Comment by jkowalski** [comment]
this is now supported at the folder level. Each folder now supports Restore to either a directory, zip or tar file.

**Comment by trenoduro** [comment]
> this is now supported at the folder level. Each folder now supports Restore to either a directory, zip or tar file.

This is either not the case, or not totally related to the issue title. If i restore to a zip file using the webui nothing is downloaded on my end (i assume it's saved somewhere on the filesystem).
Sorry if it sounds rude, totally not my intention

**Comment by Ember-ruby** [comment]
looks like that pr is for the command line only, i guess they missed that this issue is asking for a webui feature
