### ISSUE TITLE
Use XDG environment variables for paths

### ISSUE THREAD

**Issue by darkdragon-001** [kopia/kopia#495]
You seem to be using `$XDG_CONFIG_HOME` correctly, but should prefer `$XDG_CACHE_HOME` if set for the cache directory instead of `$HOME/.cache/kopia` as defined in the [Freedesktop specification](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html).

This is needed for #475.

**Comment by jkowalski** [comment]
https://github.com/kopia/kopia/blob/6217df1a87d0a740cd70ffe392988ab25d23ebb5/internal/ospath/ospath_xdg.go seems to be doing it, if that's not expected, would you mind making a PR with the fix (ideally with some test, too).

**Comment by jkowalski** [comment]
Actually my bad, this is for logs. Cache directory used to be handled here, but we've since switched to `os.UserCacheDir`, which should be handling this already.

**Comment by darkdragon-001** [comment]
Is the cache directory stored in some config file or is it always generated? (I just copied the non-flatpak config files for testing :see_no_evil: )

**Comment by darkdragon-001** [comment]
I see, it is included in `repository.config`. Going through the wizard works.
