### ISSUE TITLE
Use case: using multiple repositories from a single host (laptop)

### ISSUE THREAD

**Issue by rubiojr** [kopia/kopia#502]
:wave: I have the following use case:

* A single laptop where I run `kopia`.
* Multiple repositories: some of them to backup my own data and some others to share data with other users/friends, without giving them access to my backups.
* S3 (filebase.com) is the common backend for all of them.
* Multiple subdirectories to store repository config (under `~/.config/kopia/<repo-name>`).

To achieve that, I've been using `--config-file` so I can have multiple config files defined locally. Without that, kopia defaults to `~/.config/kopia/repository.config` which could cause data to be sent to the wrong location inadvertently.

## Setup

**Creating multiple isolated repos**

One for my backups:

```
export KOPIA_REPO=my-backup
# Create repo
kopia --config-file=$HOME/.config/kopia/$KOPIA_REPO/repository.config repository create s3 --endpoint=s3.filebase.com --bucket=this-is-my-data
# Connect
kopia --config-file=$HOME/.config/kopia/$KOPIA_REPO/repository.config repository connect s3 --endpoint=s3.filebase.com --bucket=this-is-my-data
# Snapshot
kopia --config-file=$HOME/.config/kopia/$KOPIA_REPO/repository.config snapshot create /home/rubiojr
```

Other repos to share data:

```
export KOPIA_REPO=shared
# Create repo
kopia --config-file=$HOME/.config/kopia/$KOPIA_REPO/repository.config repository create s3 --endpoint=s3.filebase.com --bucket=this-is-shared
# Connect
kopia --config-file=$HOME/.config/kopia/$KOPIA_REPO/repository.config repository connect s3 --endpoint=s3.filebase.com --bucket=this-is-shared
# Snapshot, mount, etc
kopia --config-file=$HOME/.config/kopia/$KOPIA_REPO/repository.config snapshot create /shared/data
```

I can easily share the output of `kopia --config-file=$HOME/.config/kopia/$KOPIA_REPO/repository.config repository status -t -s` through a secure channel so others can access the shared/encrypted data, which is great.

I've been using this (successfully it seems) while waiting for https://github.com/kopia/kopia/issues/310 to land, but the official documentation doesn't mention this particular case, so is this is a well supported use case?

If that's the case, would be really nice to always be forced to use a `--repository-name` or something similar that stores config in a repository dedicated local dir (`~/.config/kopia/<repo-name>`), so it's harder to send the data to the wrong repository after running `kopia repository connect`.

**Comment by rubiojr** [comment]
I just found https://github.com/kopia/kopia/pull/398, which seems to suggest this is a reasonable approach for multiple repositories when using the CLI also?

**Comment by 0x53A** [comment]
It would be useful if the ``connect`` was optional and you could pass the connection parameters directly to the actual commands.

For example, ``kopia --token abcdefg snapshot create``

I want to use kopia from a CI server, and the workaround would be to use a new, randomly generated config file each time.

**Comment by BrenBarn** [comment]
I guess this still isn't supported (at least not in an intuitive way from KopiaUI)?  It seems like basic functionality to me to want to specify the what, when, and where of backups independently.  Right now as far as I can tell you can't do this with Kopia.  You can't say "These are some groups of files I want to back up" and then (independently) say "these are some places to back things up" and then say "back up groups A and B to backup locations X and Y".  Is that correct?

**Comment by xxxliqu1dxxx** [comment]
> I guess this still isn't supported (at least not in an intuitive way from KopiaUI)? It seems like basic functionality to me to want to specify the what, when, and where of backups independently. Right now as far as I can tell you can't do this with Kopia. You can't say "These are some groups of files I want to back up" and then (independently) say "these are some places to back things up" and then say "back up groups A and B to backup locations X and Y". Is that correct?

Yes you can. Please review my answer to your other post on https://github.com/kopia/kopia/issues/2066

Kopia CLI and UI can definitely be used with different policies to identify what to backup and then the repo identifies where you want it backed up. You can have multiple repos at the same time, backing the same source directories and/or different ones... this is absolutely doable.
