### ISSUE TITLE
Feature request: Ability to sync between repositories

### ISSUE THREAD

**Issue by Ciantic** [kopia/kopia#509]
I have following scheme using Restic:

Windows 10 → _hourly_ → Raspberry Pi → _4:13 am every day_ → S3

It's not possible to replicate this with Kopia, exactly like this at the moment, I talked with @jkowalski at the Slack. This is because different repository types have different filesystem layout. I can't for example rclone the filesystem repo in the Raspberry Pi to S3 because Kopia could not open it directly then.

Instead there could be a feature to sync between repos, then I would setup my Raspberry Pi to *sync* to S3 repository each night.

**Edit** My use case is for *one-way* sync from repo to repo. Two-way sync is can of worms which is better left for sync programs like syncthing.

**Comment by flibustenet** [comment]
What if you use minio on the Raspberry and then rclone to s3 ?

**Comment by Ciantic** [comment]
@flibustenet yes, that would work because the filelayout would be same. I got that devious plan too, but I opened this issue as requested in Slack, since it could be useful anyway.

**Comment by jkowalski** [comment]
Please take a look at the proposed implementation in #522

Usage demo: https://asciinema.org/a/352299

**Comment by flibustenet** [comment]
@jkowalski The ui looks very fine, simple. The code doesn't seems too complicate also.
I'm not sure, it looks like the two repositories doesn't need to be in sync before ? It doesn't matter ? It's more like a fusion than a sync ?

**Comment by Ciantic** [comment]
Yes, it seems simple! I assume that `sync-to` only copies the changes to target repo if it already exists.

In my case I would make a cron job to Raspberry Pi:

```
kopia repository sync-to s3 --endpoint="..." --bucket=mybucket --access-key=mykey --secret-access-key=mysecret --prefix=kopia/
```

(I don't know can Kopia know if the destination repo is "older" version of the source repo, but if it does, it could be used to throw error if they are not at all same repos.)

**Comment by jkowalski** [comment]
That’s exactly right. It’s incremental and is based on the fact that Kopia never reuses file names. You should also pass —delete. Otherwise the list of files will only keep growing and you won’t get benefits of compaction in s3 (everything should still work, though)

**Comment by flibustenet** [comment]
I'm not english speaker, but maybe the term is more like `push` like in git ?

**Comment by Ciantic** [comment]
I think `sync-to` is fine. Behavior is pretty similar to `rclone sync` which also mirrors the changes to other destination. It also has `--delete` flag if I'm not mistaken.

**Comment by flibustenet** [comment]
You're right about rclone, i've to read many time the doc each time to be sure my source will not be altered ! I prefer `sync-to` than `sync`.
