### ISSUE TITLE
Global policy got deleted even though I didn't do it

### ISSUE THREAD

**Issue by Ciantic** [kopia/kopia#511]
Background: I started my repo with `jarip@desktop-16aq323`, then I figured I have an ugly hostname and username, started a new backup with by changing the username and hostname to `jari@jari-desktop`, snapshotted again, and started to remove old snapshots/policies. 

Following happened:

Global policy got deleted, even though I didn't do it.

Following transcript:

```shell
PS C:\Users\jarip> kopia policy list
248e14f53cef48dbe6a9f8fe082d773b (global)
af787532bf6f08b24e14088eab529215 jari@jari-desktop:C:\Source
6d87cee5f814aaea6c304f6e4c6af88f jari@jari-desktop:C:\Zotero
e4b8a8ad181acc8c2632e8f3c6b5b2a6 jarip@desktop-16aq323:C:\Source
254b201bbbd115198f53be8ee065fd11 jarip@desktop-16aq323:C:\Zotero

PS C:\Users\jarip> kopia policy remove e4b8a8ad181acc8c2632e8f3c6b5b2a6
01:11:37.870 [kopia/cli] Removing policy on "(global)"...

PS C:\Users\jarip> kopia policy remove 254b201bbbd115198f53be8ee065fd11
01:11:45.870 [kopia/cli] Removing policy on "(global)"...

PS C:\Users\jarip> kopia policy list
af787532bf6f08b24e14088eab529215 jari@jari-desktop:C:\Source
6d87cee5f814aaea6c304f6e4c6af88f jari@jari-desktop:C:\Zotero
```

P.S. I was trying to remove old host (snapshots and policies).

**Comment by jkowalski** [comment]
yeah, it's a usability issue - the parameters to `kopia policy rm` are path names, so proper usage should be:

```
kopia policy rm jari@jari-desktop:C:\Source
```

I'm going to make the other usage also work, since it makes a ton of sense.

**Comment by jkowalski** [comment]
Actually my bad, looks like it should be working, so there's a bug somewhere.
