### ISSUE TITLE
Snapshotting reports unrealistic data size

### ISSUE THREAD

**Issue by dhopfm** [kopia/kopia#514]
v0.6.0-rc2 on MacOS 10.15.6

While running an initial backup job, kopia reports having snapshot an unrealistic amount of data (the "Infinity%" component might be related to #513):

![image](https://user-images.githubusercontent.com/1190204/89186366-f6791900-d59b-11ea-9d9b-7e1b8172df88.png)

I was backing up `/Users/<user>` and there was only one disk connected which is 500 GB in size, about 350 GB used and only a fraction of that in the backup path. The backup target reported ~150 GB in additional storage, although that's the compressed size.

**Comment by jkowalski** [comment]
Yeah, kopia reports the percentage when compared to the size of previous backup of the same path. We clearly need to revisit this, since it's confusing to folks. Other than the cosmetics, is this causing trouble?

**Comment by dhopfm** [comment]
Personally, I'm not so much concerned about the percentage and there is #513 to deal with it. I opened this issue regarding the reported amount of data (~850 GB) which is way beyond the SSD's size. In combination with the broken percentage this makes it impossible to gauge the progress.
