### ISSUE TITLE
Ability to backup/restore socket files or at least ignore them (enhancement)

### ISSUE THREAD

**Issue by hickinbottoms** [kopia/kopia#515]
I'd like to try kopia as a means to perform Linux system backups (I currently use restic for this), which means pointing it to the root of a server.

While I ignore a number of directories, such as temporary directories, logs and caches, I find a large number of sockets dotted around the filesystem that are not practical to pick out with .kopiaignore files.

Currently, when kopia hits such a thing, it emits errors like the following:

```
21:48:54.303 [kopia/localfs] unable to create directory entry "monitor.sock": unsupported filesystem entry: &{monitor.sock 0 16777725 {296897266 63617043679 0x1b16520} {64775 29622315 1 49661 107 107 0 0 0 4096 0 {1481446879 296897266} {1481446879 296897266} {1481446879 296897266} [0 0 0]}}
21:48:54.304 [kopia/localfs] unable to create directory entry "monitor.sock": unsupported filesystem entry: &{monitor.sock 0 16777725 {90185942 63617043648 0x1b16520} {64775 29622287 1 49661 107 107 0 0 0 4096 0 {1481446848 90185942} {1481446848 90185942} {1481446848 90185942} [0 0 0]}}
```
Would it be possible for kopia to support backing up and recreating socket files on restore?

Failing that, an option to ignore socket files (effectively just suppressing the above warning) would be a handy interim solution.

**Comment by jkowalski** [comment]
I think this is just a warning, albeit a noisy one. Can you confirm that your snapshots are actually succeeding and those special files get skipped?

**Comment by hickinbottoms** [comment]
Sorry I should have clarified that.

Yes it does seem like just a noisy warning. Snapshots seem fine and the overall status of the backup is still success with a zero exit status.

**Comment by jkowalski** [comment]
I opened #544 to track adding all missing filesystem features. Closing this issue.
