### ISSUE TITLE
SMB Share with space in the path

### ISSUE THREAD

**Issue by Scott-Ain** [kopia/kopia#527]
I have a server with a file share:
    \\servername\Home Drives
I can configure the snapshot for this location but nothing ever gets backed up and the size remains at 0 B. Tried in both 0.5.2 and 0.6. My other shares on this server snapshot just fine so I suspect that Kopia gets confused by the space in the share name?

**Comment by jkowalski** [comment]
Can you explain how you're doing this? I just used kopia CLI and was able to create snapshot of `\\server\my videos` just fine.

**Comment by jkowalski** [comment]
Looks like a no-repro from my end. The "0 B" size could be a display issue that was fixed in v0.7.0-rc2. Please reopen if not fixed.
