### ISSUE TITLE
SFTP Storage

### ISSUE THREAD

**Issue by jbrodriguez** [kopia/kopia#54]
Are you looking into implementing this ?

What would it take to be implemented ?

**Comment by jkowalski** [comment]
Shouldn’t be hard. You need to implement blob.Storage which is basically key-value store. There are 4 examples of that already.

**Comment by jbrodriguez** [comment]
You were right.

It has a nice interface to add providers.

I'm making good progress

```shell
⟩ dist/integration/kopia repository create ssh --path /mnt/cache/kopia --host server --username root --keyfile /Users/johndoe/.ssh/johndoe.private
Enter password to create new repository:
Re-enter password for verification:
Initializing repository with:
  block hash:          BLAKE2B-256-128
  encryption:          SALSA20-HMAC
  splitter:            DYNAMIC-4M-BUZHASH
17:16:31.344 [kopia/cli] Saved password
Connected to repository.

Help improve Kopia by sharing anonymous usage statistics with developers:

The information includes:
  Current build version:        kopia-v0-unofficial-amd64-darwin
  Random anonymous identifier:  404b88679bebd4b7
  Type and version of storage:  (e.g. 'gcs-v1', 's3-v1')
  Name of the feature used:     (e.g. 'snapshot create', 'policy set')

No personal information (user names, host names, filenames, etc.) is ever sent:

Do you agree? (y/n) n
Policy for (global):
Keep:
  Annual snapshots:    3           (default)
  Monthly snapshots:  24           (default)
  Weekly snapshots:   25           (default)
  Daily snapshots:    14           (default)
  Hourly snapshots:   48           (default)
  Latest snapshots:   10           (default)

Files policy:
  No ignore rules.
  Read ignore rules from files:
    .kopiaignore                   (default)
```

```
⟩ dist/integration/kopia repository connect ssh --path /mnt/cache/kopia --host server --username root --keyfile /Users/johndoe/.ssh/johndoe.private
Enter password to open repository:

17:17:30.073 [kopia/cli] Saved password
Connected to repository.

Help improve Kopia by sharing anonymous usage statistics with developers:

The information includes:
  Current build version:        kopia-v0-unofficial-amd64-darwin
  Random anonymous identifier:  8b895651cfd1d043
  Type and version of storage:  (e.g. 'gcs-v1', 's3-v1')
  Name of the feature used:     (e.g. 'snapshot create', 'policy set')

No personal information (user names, host names, filenames, etc.) is ever sent:

Do you agree? (y/n) n
```

```
⟩ dist/integration/kopia snapshot create $HOME/.config/kitty
17:43:35.252 [kopia/cli] snapshotting johndoe@workstation:/Users/johndoe/.config/kitty
17:43:35.252 [kopia/cli] uploading johndoe@workstation:/Users/johndoe/.config/kitty using 0 previous manifests
17:43:35.254 [kopia/cli] processing directory '.' (3 files) 25.2 KB of 26.3 KB (95%)
17:43:35.255 [kopia/cli] completed directory '.' (3 files) 26.3 KB
uploaded snapshot 1972e2569adf516ff3736114a820a92d (root k7969472abe7895a7c86d04cb1f0b128d) in 3.119223ms
```

I'm still not sure how to simulate an ssh server for testing, so the test part  isn't there yet.

**Comment by jkowalski** [comment]
This is similar problem to testing GCS provider - I basically have a bucket for this and encrypted JSON that are decrypted by Travis CI and decrypted when the test runs.

Or perhaps use something like: https://github.com/gliderlabs/ssh

**Comment by jkowalski** [comment]
Pro tip - `kopia --analytics-consent=disagree` can be used for quicker testing.

**Comment by jbrodriguez** [comment]
Ok, I have an initial implementation at https://github.com/jbrodriguez/kopia/tree/sftp-storage.

I ended  up renaming the provider to sftp, since that's a more accurate representation of its semantics.

I'm using x/tools/ssh and pkg/sftp from the beginning, so for testing I had to build a mini sftp/ssh server from scratch, mostly because gliderlabs/ssh doesn't support sftp 🤷🏻‍♂️

A couple of notes:
- The provider assumes you have a working public/private key connection to the ssh server. No other authentication method is supported
- The repository path must exist in the server
- (testing related) The pkg/sftp server doesn't offer a way to set a filesystem root, so it runs from the local directory which is basicaly repo/blob/sftp during testing. So the tests leave some debris behind. Additionally, that's the reason why id_rsa and known_hosts are there at all.

Let me know your thoughts.

**Comment by jkowalski** [comment]
Looks pretty good. I think that perhaps instead of yet another copy of file/WebDAV we could extract common pieces into a common base. What do you think?

Also discussing on a pull request might be easier.

**Comment by jbrodriguez** [comment]
Sure, I'll open the PR later.

I'll check how much commonanility can be extracted.

**Comment by jbrodriguez** [comment]
Ok, so I sent the PR.

I was looking for shared code and I see only a couple of functions that could be extracted:

- getBlobIDFromFilename
- makeFileName
- getShardDirectory
- getDirPathAndFilePath
- createTempFileAndDir

Other that that each blob.Storage functions depend on different libraries and may have subtle differences.

Unless you were thinking about something else.

**Comment by jkowalski** [comment]
Per discussion, what's remaining here is adding E2E test with some actual linux host.

**Comment by jbrodriguez** [comment]
Sure thing. I've been busy these last few days.

I'm getting to it no later than the end of the week.

I don't foresee a lot of work, just the time to dedicate to it.

**Comment by jbrodriguez** [comment]
So finally got to work on it.

Opened #62

Not sure how the test will work on the CI server.

**Comment by jbrodriguez** [comment]
Closed by #55 and #62

**Comment by jkowalski** [comment]
I'm running into issues configuring E2E tests on my linux host (I created a dedicated SFTP-only account on Dreamhost)

@jbrodriguez can you DM on slack so I can share with you the credentials to the SFTP server I'm testing on (slack invite is on kopia.io homepage)

**Comment by jkowalski** [comment]
BTW, I'm getting

```
    verify.go:49: can't put blob: sftp: "Failure" (SSH_FX_FAILURE)
```

**Comment by jbrodriguez** [comment]
Sure, I'm busy today, but will talk to you tommorrow.

**Comment by jbrodriguez** [comment]
I DM'ed on slack.

I also did some tests on a local server on my network and I haven't been able to repro, so it will be nice to try on your test server.

**Comment by jkowalski** [comment]
closing this issue, SFTP tests have been working for a while now
