### ISSUE TITLE
Sparse file support

### ISSUE THREAD

**Issue by davidandreoletti** [kopia/kopia#540]
Large files (eg virtual machine disk) with holes (aka sparse file) have different sizes on disk depending on the tools/options used.

```du -h --apparent-size file.img```: Shows a file' size on the host system as the max size of the image.
```du -h file.img```: Shows a file' size on the host system as the current actual size of the image (less than max size of the image).

Does kopia support sparse files for backup and restore (assuming identical host/filesystem as when it was backed up) ?

PS: +1 on creating kopia.

**Comment by julio-lopez** [comment]
Kopia does not perform "sparse-region detection" per se. If the sparse regions are large enough (order ~4MB), then they may be captured by de-duplication. Also, Kopia supports compression, so regions with 0s are trivially compressible.

**Comment by SarenT** [comment]
I want to quickly add here that in my case snapshot  "estimate" was way off due to a map file created by `ddrescue`. Actualy size: 100MB, `ls -lah` was showing 8TB
