### ISSUE TITLE
kopia-ui improvements for dealing with kopia repository server

### ISSUE THREAD

**Issue by bullet64** [kopia/kopia#542]
Some ideas / questions from me for kopia-ui

    - Login for kopia server (atm i do it from cli)
    - when connected to kopia-server the pulldown (local snapshot) is unnecessary(?)
    - Tab Repositiory show nothing (can we fill it with data?)
    - The connection to the server remains established despite the restart? Why?

If necessary, I can create separate issues for the individual points. Wanted to discuss this first.

**Comment by jkowalski** [comment]
One issue is fine, those are all small enough. 

As for the last question, the parameters for connection to the server are saved in a file, there's no actual connection that's persisted across reboots.
