### ISSUE TITLE
B2 provider: 500 Internal Server Error

### ISSUE THREAD

**Issue by wmerlotto** [kopia/kopia#547]
With kopia version 0.6.2, repository connected on B2 and server created with command:
`kopia repository connect server --url=https://backup:51515 --server-cert-fingerprint=xxxxx`

On client, I executed this command:
`kopia snapshot create --parallel=2 /srv/`

And got this error after a while:
`\ 0 hashing, 15816 hashed (1.7 GB), 0 cached (0 B), 0 uploaded (0 B), 0 errorskopia: error: encountered 1 errors:
unable to process directory "OFF": unable to process directory "npm.domain.com": unable to process directory "storage": unable to process directory "@expo": unable to process directory "traveling-fastlane-linux": unable to write content chunk 3 of FILE:traveling-fastlane-linux-1.13.2.tgz: server error: 500 Internal Server Error: server error: 500 Internal Server Error, try --help`

**Comment by jkowalski** [comment]
Do you happen to have server-side logs?

**Comment by wmerlotto** [comment]
I activated the log in debug mode on the server, ran the snapshot again and got this error log:
`2020-08-17 10:22:45.303 D [logging_storage.go:46] [STORAGE] PutBlob("p9f1ce2f5c021d7e4fc48cae7cd5a4b3c",len=24088928)=&url.Error{Op:"Post", URL:"https://pod-000-1144-17.backblaze.com/b2api/v1/b2_upload_file/a80b691f7eeff328733e0e15/c001_v0001144_t0048", Err:http.tlsHandshakeTimeoutError{}} took 25.681085141s`
`2020-08-17 10:22:45.303 D [server.go:140] error code INTERNAL message internal server error: unable to write pack: error writing pack: can't save pack data content: Post "https://pod-000-1144-17.backblaze.com/b2api/v1/b2_upload_file/a80b691f7eeff328733e0e15/c001_v0001144_t0048": net/http: TLS handshake timeout`
`2020-08-17 10:22:45.306 D [server.go:117] request /api/v1/flush (0 bytes)`
`2020-08-17 10:22:45.307 D [content_manager.go:435] waiting for 4 in-progress packs to finish`
`2020-08-17 10:22:56.162 D [content_cache_base.go:144] finished sweeping directory in 224.795µs and retained 46873/5242880000 bytes (0 %)`
`2020-08-17 10:22:56.624 D [content_cache_base.go:144] finished sweeping directory in 3.766638ms and retained 322109279/5242880000 bytes (6 %)`

**Comment by jkowalski** [comment]
This appears to be an error from B2 provider. Looks like a bug.
