### ISSUE TITLE
Proposal: repository user management 

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#548]
## Background

In the v0.6.x release of Kopia, the API server can now be used as a limited repository backend.

Unlike directly-connected repository where the client has unrestricted read/write access to underlying files in S3, etc. in case of `kopia server` the server proxies access to blob storage and is in position to apply additional access control checks via higher-level API.

Not all operations are allowed when accessing repository via API server:

In the current the permission model, each user identified by `username@host` only has permissions to see snapshots and policies of their own username and host has read/write to contents if their ID is known. There is no low-level access to blob storage and no ability to list contents in the repository, no access to global or per-host policies and no ways to set fine-grained permissions such as accessing other users data.

Currently management user passwords is done via `htpasswd` file, which must be manually created by administrator with per-user passwords managed outside of the system and all users mentioned in the file get default access level.

The current solution is temporary until we come up with better strategy for managing user accounts and passwords and some form of role-based access control (RBAC) to allow more fine-grained access control checks. 

This mini-proposal is meant to address that:

## Proposal

We can manage users, their passwords and permissions through manifests in the repository, similar to how policies and snapshots are managed.

We can introduce new type of manifest, called `user` which defines a single user account with labels:

```
type:user
login:some-user
```

Each `user` manifest will contain login name, hashed password (in `htpasswd` format) and rules for controlling access to contents and various manifests.

```json
{
    "login": "jarek",
    "locked": false,
    "password": "$apr1$0xoMy8l4$zwPGcVq2ILY1VYqsI8sDI0",
    "contentAccess": "append",
    "manifestAccess": {
        "path:jarek@jareks-mbp:/some/path": "FULL",
        "user:jarek@jareks-mbp": "FULL",
        "host:jareks-mbp": "READ",
        "global": "READ",
    }
}
```

We will define the following access levels:

* `FULL` - can create, get, list and delete
* `APPEND` - can create, get, list but not delete
* `VIEW` - can get and list
* `NONE` - no access

The parameter `contentAccess` controls whether the user can create new contents, read (but not list) or delete contents.
`manifestAccess` assigns the level of access to snapshots/policies at particular levels - the most specific definition wins.

## CLI usage

The command-line tools for managing user accounts will only be available to any user with direct repository access.

The examples below should be self-explanatory:

```
$ kopia user create some-user ---content-access=APPEND \
  --manifest-access=user:jarek@jareks-mbp=FULL \
  --manifest-access=global:READ
Enter password for 'some-user': ****
```

```
$ kopia user update some-user ---content-access=READ \
  --manifest-access=user:jarek@jareks-mbp=APPEND \
  --manifest-access=global:FULL
```

```
$ kopia user update some-user --manifest-access=global:NONE
```

```
$ kopia user lock some-user
```

```
$ kopia user unlock some-user
```

```
$ kopia user passwd some-user
Enter password for 'some-user': ****
```

```
# this will allow user to change their own password and will also work in repository accessed through API:
$ kopia user passwd
Enter password for 'current-user': ****
```

## UI usage

UI will not allow access to user account management, except for changing one's own password. This may be reconsidered if new use cases arise.

## API usage

API will not (initially?) offer any access to user management. This may be reconsidered if new use cases arise.

**Comment by julio-lopez** [comment]
This was implemented

**Comment by abjoseph** [comment]
> This was implemented

@julio-lopez @jkowalski I'm currently running the `kopia server` on windows server and when I run the command `kopia server user add user@host` it returns the following error:

`ERROR error setting user profile: error looking for user profile: access denied`

Is the "User Management" logic officially supported on windows? If so, could either of you offer any assistance as to what's needed to fix this. Where is it looking for the user profile?? I searched the source code for that error and found the following line, but I don't know what this "manifests" is that it is expecting as a parameter...should that have been created somewhere on the filesystem, and if so, where?
