### ISSUE TITLE
WebDav backend not working with Synology Webdav

### ISSUE THREAD

**Issue by tboege** [kopia/kopia#551]
I have set up WebDav on Synology. I can connect and use the share using net use https:/....
When I setup the repository in the UI and pres Connect Repository, the screen changes to "Setup Repository", and I can press Initialize Repository. But first I have to fill the empty Confirm Repository Passowrord. After confirming Repository Password and pressing "Initialize Repository", I get a messagebox with error "failed to create repository..". In the share, a file, kopia.repository.f is created.
<img width="416" alt="Kopia-1" src="https://user-images.githubusercontent.com/31761931/90875642-c3a79100-e3a1-11ea-92a9-41e96347f796.PNG">

I have tried to find som log files, to show the dialogue between kopia and synology, but havn't found it. If I can get some help to provide needed information, I would like to repeat the process to get the needed information

**Comment by alphaleonis** [comment]
I'm getting similar errors here on a local QNAP WebDav.  I was actually able to create the repository, and a couple of times start creating a snapshot, but it then fails with a 403 error.

**Comment by jkowalski** [comment]
I have a theory this might have been fixed with 04fcddeff03e8b0b1c06281c7bb7f7bb74402562. The fix will be in 0.7.0 release, please let us know if you're still seeing the issue.

**Comment by julio-lopez** [comment]
Might be related to #624/#626

**Comment by miquella** [comment]
After a bit of sleuthing tonight, I believe I may have tracked down the issue:

When `PutBlobInPath` encounters `blob.ErrBlobNotFound`, this is usually an indicator that at least one of the directories is missing, so it performs a `MkdirAll`.

Unfortunately, with my Synology WebDAV it appears to return a `403 Forbidden` error, not `blob.ErrBlobNotFound`. To test my theory, I applied the below hack and was able to complete a snapshot successfully!

```patch
diff --git a/repo/blob/webdav/webdav_storage.go b/repo/blob/webdav/webdav_storage.go
index 71488142..158a5b50 100644
--- a/repo/blob/webdav/webdav_storage.go
+++ b/repo/blob/webdav/webdav_storage.go
@@ -32,6 +32,8 @@
 
 var fsDefaultShards = []int{3, 3}
 
+var errForbidden = errors.New("forbidden")
+
 // davStorage implements blob.Storage on top of remove WebDAV repository.
 // It is very similar to File storage, except uses HTTP URLs instead of local files.
 // Storage formats are compatible (both use sharded directory structure), so a repository
@@ -94,6 +96,9 @@ func (d *davStorageImpl) translateError(err error) error {
 
 		case http.StatusNotFound:
 			return blob.ErrBlobNotFound
+
+		case http.StatusForbidden:
+			return errForbidden
 		}
 	}
 
@@ -124,7 +129,7 @@ func (d *davStorageImpl) PutBlobInPath(ctx context.Context, dirPath, filePath st
 			return d.cli.Rename(tmpPath, filePath, true)
 		}
 
-		if !errors.Is(err, blob.ErrBlobNotFound) {
+		if !errors.Is(err, blob.ErrBlobNotFound) && !errors.Is(err, errForbidden) {
 			return errors.Wrap(err, "unexpected error when writing")
 		}
 
```

I'm unsure if this is a good approach, but it's been a long day, so I can't think of anything else off the top of my head. Happy to open a PR and flesh this out a bit more if it seems like the correct approach?

**Comment by jkowalski** [comment]
this is great, i'm wondering if we should be always trying to MkdirAll() regardless of the error code if original write fails?

Can you give that a try and send a pull request?

**Comment by miquella** [comment]
That sounds like a reasonable path forward. I'll try to push something up after work tonight!
