### ISSUE TITLE
KopiaUI 0.6.3 - Can't delete a snapshot

### ISSUE THREAD

**Issue by NickPyz** [kopia/kopia#556]
I created multiple snapshots within a single repository using KopiaUI. ALL good!

Now I want to delete a single snapshot. (It points to an empty folder). I can't find a KopiaUI method to do this. I went into the "Policies" tab and did edit > delete for the policy associated with the snapshot. Policy is gone, but the snapshot still shows in the "snapshots" tab.

How to proceed?

OS is Windows 10

**Comment by NickPyz** [comment]
I realize that the CLI has significantly more granularity than than KopiaUI. I have discovered the CLI command to remove a snapshot.

My issue is that this function belongs in the UI version. I think snapshot deletion is a routine task in a backup program.

**Comment by jkowalski** [comment]
You're absolutely right, the UI needs a whole bunch of these usability improvements.
