### ISSUE TITLE
kopia should not backup its own .cache directory

### ISSUE THREAD

**Issue by mbiebl** [kopia/kopia#562]
Afaics, kopia will by default backup its own .cache/kopia directory. I think this directory should be excluded by default, as it's constantly changing and safe to omit.

**Comment by julio-lopez** [comment]
I believe this has been addressed.

**Comment by julio-lopez** [comment]
bb2434dc

**Comment by mbiebl** [comment]
Do I have to create this marker file manually?
```
# ls -la .cache/kopia/
insgesamt 36940
drwx------ 2 root root     4096 Aug 29 01:01 .
drwx------ 3 root root     4096 Aug 28 22:11 ..
-rw-r--r-- 1 root root 27950551 Aug 29 00:53 kopia-20200828-221824-17332.log
-rw-r--r-- 1 root root  2043941 Aug 29 01:00 kopia-20200829-005425-19030.log
-rw-r--r-- 1 root root  7818187 Aug 29 02:18 kopia-20200829-010128-19133.log
lrwxrwxrwx 1 root root       31 Aug 29 01:01 kopia.latest.log -> kopia-20200829-010128-19133.log
```

**Comment by julio-lopez** [comment]
It should be automatically created on startup.

If you create it manually, it would skip it.

What is OS ? Linux or macOS ?

**Comment by mbiebl** [comment]
It's Linux.
I just noticed that the `.kopia-cache` marker is only created inside the subdirecories in `.cache/kopia/`.
So the actual cache directories are excluded, but not the log files. I guess this is fine, so closing.

**Comment by plumbeo** [comment]
Hi, in place of or in addition to using a custom file would you consider implementing support for the Cache Directory Tagging Specification (https://bford.info/cachedir/) which is already supported by several other backup tools (tar, borg and restic for sure, and it was recently added to déjà dup) and would make interoperability easier?
