### ISSUE TITLE
Implement support for Cache Directory Tagging Specification

### ISSUE THREAD

**Issue by plumbeo** [kopia/kopia#564]
Hi,

I’ve already commented in another issue (https://github.com/kopia/kopia/issues/562#issuecomment-683363801) but since it’s closed I thought best to open a new one.

Would you consider implementing support for the Cache Directory Tagging Specification (https://bford.info/cachedir/)? It’s already honoured by several backup tools (tar, borg, restic, déjà dup added it recently) and other non-backup softwares create the appropriate files in their cache directories (man, fontconfig, restic itself) so it would help with interoperability.

A basic implementation could just mirror what was added in PR #524, replacing the custom file with CACHEDIR.TAG or checking for the presence of either, eventually guarding it with a policy option.

**Comment by mbiebl** [comment]
Should this be opt-in? E.g. restic has an explicit command line parameter for this
```
      --exclude-caches                   excludes cache directories that are marked with a CACHEDIR.TAG file. See http://bford.info/cachedir/spec.html for the Cache Directory Tagging Standard
```

**Comment by jkowalski** [comment]
@mbiebl we can probably do this via policies (global, per host, per directory), but I think the default should be to ignore those caches.

**Comment by jkowalski** [comment]
PTAL @#565 - it adds `--ignore-cache-dirs` flag when setting a policy (defaults to true), also added UI for it.
