### ISSUE TITLE
Unable to verify `server status` when runiing in `https` mode

### ISSUE THREAD

**Issue by rahulchheda** [kopia/kopia#577]
So, I used `kopia server start --address=localhost:51515 --tls-generate-cert --tls-cert-file ~/my.cert  --tls-key-file ~/my.key` as given in the documentation, with an initialised `kopia repository`. I tried to connect clients to it by passing `--server-cert-fingerprint XXXX` was working flawlessly. But when I tried to check if the server is started with the command `kopia server status --address=https://<addr>:<port>` it gives me this error `tls: bad certificate`. I tried to pass the above argument i.e `--server-cert-fingerprint XXXX` with the status command, but that is not supported.
Any work around to make this work?

**Comment by jkowalski** [comment]
You're right, there's a missing flag here. Should be an easy fix.
