### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by githubuser0000000001** [kopia/kopia#586]
More clarity needed on the use of ignore paths with examples.  i.e.
```
--add-dot-ignore    | List of paths to add to the dot-ignore list
--add-ignore        | List of paths to add to the ignore list
```
Currently there is only one format it seems e.g.
```
--add-ignore my-sub-directory/
```
 that is accepted.  Could this be increased to recognise user specified regex, other basic globing patterns and order sequence?

What is the difference between these flags?
Could a file be used to store these patterns instead?

**Comment by GraphZal** [comment]
From what I've gathered, dot-ignore is the list of files treated as a ".ignore" file, i.e. files that will contain a list of paths to ignore. By default, that's any file called ".kopiaignore" (each directory can have one that applies to that directory and any subdirectory).

Bash-globbing is already supported in both ignore methods, if I'm not mistaken.

Documentation needs some general improvement, though.
