### ISSUE TITLE
Missing SFTP instructions on repositories page

### ISSUE THREAD

**Issue by francisco1844** [kopia/kopia#590]
In the [repository document page](https://kopia.io/docs/repositories/) there is a link for SFTP, but it doesn't point to anything. Also, scrolling through the page looking for it shows the SFTP repo instructions are missing.

**Comment by francisco1844** [comment]
Found the info.. somewhere else. Are the instructions on how to do PRs for documentation. I could help on this one and possibly other documentation related issues.

**Comment by ntolia** [comment]
@francisco1844 Documentation PRs are greatly appreciated. Contribution guidelines can be found at https://kopia.io/docs/contribution-guidelines/ but are a bit light. If you have any issues with the GitHub fork/create-a-PR workflow, LMK. I will be happy to help.
