### ISSUE TITLE
content stats histogram

### ISSUE THREAD

**Issue by githubuser0000000001** [kopia/kopia#614]
`kopia content stats` histogram output only shows file sizes up to 100MB and ignores larger files. 
Should include all file sizes up to at least 100GB such as might occur with large .tar.gz files.
e.g. output:
```
Histogram:

        0 between 0 B and 10 B (total 0 B)
    6873 between 10 B and 100 B (total 1.1 MB)
   1559 between 100 B and 1 KB (total 132.8 MB)
   5441 between 1 KB and 10 KB (total 1 GB)
    83 between 10 KB and 100 KB (total 3.4 GB)
    6368 between 100 KB and 1 MB (total 22.5 GB)
    3502 between 1 MB and 10 MB (total 298.7 GB)
        0 between 10 MB and 100 MB (total 0 B)
```
Although this may only be reflecting the blob sizes only, which are no larger than that shown, in which case this is a non-issue and can be closed.

File sizes are reflected in the `kopia snapshot estimate` command in any case.

**Comment by jkowalski** [comment]
`contents` are not files, they are chunks of files which never larger than ~20 MB - larger files are broken into smaller contents and concatenated using index objects, so this is by design
