### ISSUE TITLE
[Flatpak][UI] Blank UI window when starting kopia early in kde

### ISSUE THREAD

**Issue by bbregeault** [kopia/kopia#625]
When adding kopia (installed from Flatpak) to kde settings : Startup & Shutdown > Autostart,
Kopia starts at the session startup and its icon appears in the system tray as expected.
However, clicking on its icon and "My Repository" opens a window that remains blank forever, no matter how many times I try:

![kopia_window_header_bad](https://user-images.githubusercontent.com/25389499/93664425-412cf280-fa6f-11ea-8857-2a938de9838e.png)

Running 'ps ax | grep kopia' after a faulty autostart gives:
```
   1207 ?        S      0:00 bwrap --args 35 kopia-ui
   1271 ?        S      0:00 bwrap --args 35 kopia-ui
   1274 ?        Sl     0:00 /app/KopiaUI/kopia-ui
   1324 ?        S      0:00 /app/KopiaUI/chrome-sandbox /app/KopiaUI/kopia-ui --type=zygote
   1393 ?        Sl     0:00 /app/KopiaUI/kopia-ui --type=gpu-process --field-trial-handle=4411380971297327915,559398249473079437,131072 --disable-features=SpareRendererForSitePerProcess --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=2493871306675368367
   1428 ?        Sl     0:00 /app/KopiaUI/kopia-ui --type=utility --field-trial-handle=4411380971297327915,559398249473079437,131072 --disable-features=SpareRendererForSitePerProcess --lang=fr --service-sandbox-type=network --service-request-channel-token=10428896441128744953 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
```

Whereas 'ps ax | grep kopia' after starting kopia from the app menu gives a similar output with one more line:
```
   4619 ?        Sl     0:08 /app/KopiaUI/resources/server/kopia server --ui --random-password --tls-generate-cert --address=localhost:0
```

Here is the output of 'journalctl -b -g "flatpak|kopia"' after a faulty autostart:
```
sept. 19 11:21:11 Gigabyte systemd[1000]: /home/benoit/.config/autostart/io.kopia.kopiaui.desktop:7: Unknown key name 'StartupWMClass' in section 'Desktop Entry', ignoring.
sept. 19 11:21:11 Gigabyte dbus-daemon[1014]: [session uid=1000 pid=1014] Activating via systemd: service name='org.gtk.vfs.Daemon' unit='gvfs-daemon.service' requested by ':1.1' (uid=1000 pid=1012 comm="flatpak --installations " label="unconfined")
sept. 19 11:21:12 Gigabyte plasma_session[1044]: org.kde.plasma.session: Starting autostart service  "/home/benoit/.config/autostart/io.kopia.kopiaui.desktop" ("/usr/bin/flatpak", "run", "--branch=stable", "--arch=x86_64", "--command=kopia-ui", "--file-forwarding", "io.kopia.KopiaUI", "@@u", "@@")
sept. 19 11:21:12 Gigabyte dbus-daemon[1014]: [session uid=1000 pid=1014] Activating via systemd: service name='org.freedesktop.Flatpak' unit='flatpak-session-helper.service' requested by ':1.35' (uid=1000 pid=1207 comm="/usr/bin/flatpak run --branch=stable --arch=x86_64" label="unconfined")
sept. 19 11:21:12 Gigabyte systemd[992]: Starting flatpak session helper...
sept. 19 11:21:12 Gigabyte dbus-daemon[1014]: [session uid=1000 pid=1014] Successfully activated service 'org.freedesktop.Flatpak'
sept. 19 11:21:12 Gigabyte systemd[992]: Started flatpak session helper.
sept. 19 11:21:12 Gigabyte dbus-daemon[1014]: [session uid=1000 pid=1014] Activating via systemd: service name='org.freedesktop.portal.Documents' unit='xdg-document-portal.service' requested by ':1.35' (uid=1000 pid=1207 comm="/usr/bin/flatpak run --branch=stable --arch=x86_64" label="unconfined")
sept. 19 11:21:12 Gigabyte systemd[992]: Starting flatpak document portal service...
sept. 19 11:21:12 Gigabyte systemd[992]: Started flatpak document portal service.
sept. 19 11:21:12 Gigabyte dbus-daemon[1014]: [session uid=1000 pid=1014] Activating via systemd: service name='org.a11y.Bus' unit='at-spi-dbus-bus.service' requested by ':1.35' (uid=1000 pid=1207 comm="/usr/bin/flatpak run --branch=stable --arch=x86_64" label="unconfined")
sept. 19 11:21:12 Gigabyte systemd[992]: Started app-flatpak-io.kopia.KopiaUI-1207.scope.
sept. 19 11:21:14 Gigabyte kded5[1071]: Registering ":1.54/org/ayatana/NotificationItem/KopiaUI1" to system tray
```

And after a "normal" app menu start, two additional lines are mixed with the ones shown above:
```
sept. 19 10:53:23 Gigabyte systemd[1018]: Started apps-io.kopia.kopiaui-c4c8892470f542148d0352a2d9b3e92d.scope.
sept. 19 10:53:23 Gigabyte systemd[1018]: apps-io.kopia.kopiaui-c4c8892470f542148d0352a2d9b3e92d.scope: Succeeded.
```

Additional info:
Clicking on "Configure Repositories" displays the configuration window as expected
Starting Kopia from the application menu makes it work as expected
Quiting an autostarted Kopia and restarting it from the application menu makes it work as expected

System info:
Manjaro 20.1
Kde Plasma 5.19.5
Flatpak 1.8.1
Systemd 246.4
KopiaUI 0.6.0 (flatpak io.kopia.KopiaUI)

I have little knowledge of flatpaks but can provide more info if necessary.
Thanks

**Comment by darkdragon-001** [comment]
Thanks for your comprehensive analysis and report!

I packaged the Flatpak version (without being a Kopia developer), but didn't have time to look into autostart yet (but documented this in the Flathub repository flathub/io.kopia.KopiaUI#2). The way to go, seems to use a portal instead of creating a file directly as suggested in #630. Hopefully this will be implemented soon by the developers.

I was wondering how you setup the autorun in KDE? Did you create the file manually or did you use the _Launch At Startup_ menu item from Kopia itself? When I use the Kopia menu, it creates a startup file with command `/app/KopiaUI/kopia-ui`. So who created the autostart file from your logs?
> "/home/benoit/.config/autostart/io.kopia.kopiaui.desktop" ("/usr/bin/flatpak", "run", "--branch=stable", "--arch=x86_64", "--command=kopia-ui", "--file-forwarding", "io.kopia.KopiaUI", "@@u", "@@")

Running the logged command manually works for me and it was also suggested in flatpak/flatpak#118, but it might be that background applications need to request additional permissions (which would also go through the mentioned portal) as discussed in the issue.

**Comment by bbregeault** [comment]
Thanks for your prompt reply!

I didn't know that Flathub packages had their own issue tracker. This issue belongs there perhaps...
Anyway, I now think it is more of a race problem than an autostart problem, see below.



> The way to go, seems to use a portal instead of creating a file directly as suggested in #630. Hopefully this will be implemented soon by the developers.

Indeed, thanks for the link.

> I was wondering how you setup the autorun in KDE? Did you create the entry yourself via _KDE Settings > Startup & Shutdown > Autostart_ 

Yes. In this menu I clicked _Add a program_ and picked Kopia in the treeview.

> or did you use the _Launch At Startup_ menu item from Kopia tray icon? When I use the Kopia menu, it creates a startup file with command `/app/KopiaUI/kopia-ui`. 

Me too, I can see this file `.config/autostart/kopia-ui.desktop` with the line you mention : `Exec=/app/KopiaUI/kopia-ui`
However, it doesn't work for me, i.e. enabled or not, this option doesn't start Kopia after reboot.

> So who created the autostart file from your logs?
> > "/home/benoit/.config/autostart/io.kopia.kopiaui.desktop" ("/usr/bin/flatpak", "run", "--branch=stable", "--arch=x86_64", "--command=kopia-ui", "--file-forwarding", "io.kopia.KopiaUI", "@@U", "@@")

Kde did, as far as I can tell. It is a essentially a copy of `/var/lib/flatpak/exports/share/applications/io.kopia.KopiaUI.desktop` with some keys reordered and others added but left empty.
Note that the above command is also the one being launched when starting Kopia from the application menu.

> Running the logged command manually works for me and it was also suggested in [flatpak/flatpak#118](https://github.com/flatpak/flatpak/issues/118), but it might be that background applications need to request additional permissions (which would also go through the mentioned portal) as discussed in the issue. Or I could also imagine some environment variables or other conflicts when started through systemd instead of the desktop. Just guesses. Unfortunately, I don't know enough about Electron/Flatpak/Systemd/Kopia internals to help you further with this. Any help appreciated (IMHO manually adding an autostart flatpak entry should also be supported)!

After some further testing, I believe this is more of a race issue:
- Adding `sleep 10;` at the beginning of the Exec line in _KDE Settings > Startup & Shutdown > Autostart_ (which is then inserted in the file `.config/autostart/io.kopia.kopiaui.desktop` solves the problem: `ps ax` now shows `/app/KopiaUI/resources/server/kopia server --ui --random-password --tls-generate-cert --address=localhost:0` and the repository window works as expected
- On the opposite, disabling autostart and starting Kopia from KRunner as soon as I can after my session starts triggers the same issue

To me, it looks like the `kopia server --ui` process fails because of a dependency that is not running yet and I changed the issue title accordingly.
I have no clue beyond that. I'll stick with my workaround for now but I can do more tests if requested.

**Comment by bbregeault** [comment]
The problem persists with version 0.7.0.
The _Launch at startup_ option does not work either.
I raised the delay for the sleep command since 10 seconds is not always enough.
