### ISSUE TITLE
Cannot copy files on a mounted volume larger than 50MB

### ISSUE THREAD

**Issue by windware-ono** [kopia/kopia#629]
When I mount a snapshot on Windows, I can copy files less than 50MB but anything larger says `file size exceeded the maximum size permitted` and won't let me copy to a local folder.

Kopia UI : v0.7.0-rc1 (Windows 10)
Storage : Wasabi

**Comment by jkowalski** [comment]
This appears to be a limitation of Windows when mounting WebDAV files. https://www.thewindowsclub.com/file-size-exceeds-limit-allowed-cannot-saved has instructions for fixing. When restoring larger files you may need to use `kopia restore` command which does not have the limitation.

**Comment by windware-ono** [comment]
I think this should be documented as the error is only shown if I drag a file to copy to another local disk but if I directly try to play a movie file on the mounted volume, it just does nothing with no errors shown.

Regarding this and #628, is there a possibility to use a better mount client for Windows?
