### ISSUE TITLE
Restore single file error

### ISSUE THREAD

**Issue by graphixillusion** [kopia/kopia#634]
Hi everyone. Let's say that i'm in this case number 1:

1. Source directory is this:

sourcepath
  file1.txt
  file2.txt
  file3.txt

I have successfully created a snapshot of this "sourcepath" with this command:

`kopia snapshot create sourcepath`

When i need to restore this snapshot i need to use this command

`kopia restore id targetpath` 

becouse if i use

`kopia snapshot restore id targetpath`

it returns an error. 

Case number 2:

If now i try to create a snapshot of a single file instead of a dir with this command

`kopia snapshot create sourcepath\file1.txt`

i always get an error if i want to restore the file. Any clue?

**Comment by jkowalski** [comment]
Assigning to Nick to investigate.

In the meantime `kopia show id > targetpath` might work for you.

**Comment by graphixillusion** [comment]
@jkowalski i think i've found the issue. the error is becouse i used the wrong id. with this command i've found in the forum:

`kopia snap ls -m` 

i can see the manifest-id which is needed and the next command will works as intended:

`kopia snap restore manifest-id restore_dest\restoredfilename`

**Comment by jkowalski** [comment]
@redgoat650 

I think we should support restoring both by rootID/filename and snapshot restores by file ID (instead of manifest ID). This is just a matter of convenience, the file will be the same regardless of which manifest ID it belongs to.

**Comment by graphixillusion** [comment]
@jkowalski is it possible to add an option which uses the original file name in the snapshot as the name in the restored files if no new name is provided in the destination path? something like:

filename in the repository= **testname.txt**

`kopia snap restore id d:\restored\`

it will restores the file "testname.txt" in the d:\restored directory.
