### ISSUE TITLE
Refactor CI/CD

### ISSUE THREAD

**Issue by jkowalski** [kopia/kopia#636]
Currently we run pretty heavyweight CI/CD pipeline:

* Linux/AMD64 on Travis CI uses publishes CLI binaries for all platforms and KopiaUI build for Linux and pushes to RPM/DEB repositories.
* Linux/ARM64 on Travis CI runs tests only
* MacOS/AMD64 on TravisCI builds KopiaUI for macOS, signs and submits to Apple for notarization and publishes and DMG, ZIP 
* Windows/AMD64 on AppVeyor builds KopiaUI for Windows, signs the binary using code signing cert and publishes setup exe and ZIP.

Notably missing are:

- [x] Code signing of Windows CLI binaries (since they are built on Linux where signing is not available)
- [x] Signing & notarization of macOS CLI binary (same reason)
- [ ] Checksums.txt does not include KopiaUI binaries

It would be nice to:

- [ ] Separate building UI from the CLI and have them run in parallel
- [x] Avoid cross-compilation (so that windows CLI is built on Windows, mac on macOS, and linux on Linux)
  - [ ] Linux/amd64/travis - CLI for Linux + run integration tests
  - [ ] Linux/amd64/travis - KopiaUI for Linux only
  - [ ] macOS/amd64/travis - CLI for mac + run integration tests
  - [ ] macOS/amd64/travis - KopiaUI for mac only
  - [ ] Windows/amd64/appveyor - CLI for Windows, and KopiaUI for windows + run integration tests
- [ ] Also, if we could do something about ARMHF build (which does not have any CI/CD support that I could find) that would be awesome.

Doing all this will mean that the `checksums.txt.sig` file will need to be produced differently after all other build components have completed.

**Comment by julio-lopez** [comment]
Some of the enhancements described above have already been done. Also see #723 for related tasks.

@jkowalski Can you cross out the ones above that have already been implemented and close this issue if appropriate?
