### ISSUE TITLE
[Feature request] Friendlier output - flag

### ISSUE THREAD

**Issue by francisco1844** [kopia/kopia#642]
For commands like show, it would be most useful to be able to pass a flag to get the output on a human friendly format instead of json. There are other commands that would benefit from the same.

Something like --human-readable for any command that outputs json. Ideally would like human readable to be the default and have the flag for json be the exception

**Comment by jkowalski** [comment]
`kopia show` is a low-level command that shows contents of an object (file or directory) in repository.

For directories, if you have object-id there's equivalent `kopia ls <object-id>` that formats entries nicely.

**Comment by francisco1844** [comment]
But `kopia ls <object-id>` doesn't show errors. This is follow up of the discussion on the forum [here](https://kopia.discourse.group/t/tracking-down-backup-errors/126/7), but in general I think having human readable output and json as an option is a better option than the current json by default and no human readable output

**Comment by jkowalski** [comment]
Would this be reasonable?

https://asciinema.org/a/2rma0sx2mD6HoIPy6VL0QEFeP

**Comment by francisco1844** [comment]
Looks good. So if the error is on a sub-folder will it show?
i.e.
Snapshot /somefolder
Error in /somefolder/sub1/sub2

will the ls of the ID for /somefolder show the error or will I need to get the ID for /somefolder/sub1/sub2 ?

**Comment by jkowalski** [comment]
Yes.

```
$ kopia ls kc8bfbea67df7f0727d738f121241521c
.appveyor.yml
.git
.gitattributes
.github
.gitignore
.golangci.yml
.gometalinter.json
.goreleaser.yml
.travis.yml
BUILD.md
CODE_OF_CONDUCT.md
GOVERNANCE.md
LICENSE
Makefile
README.md
app
build_architecture.svg
cli
dist
examples
fs
go.mod
go.sum
htmlui
icons
install.cmd
internal
kopia.gpg.enc
main.go
repo
site
snapshot (1 errors)
tests
tools

NOTE: Encountered 1 errors while snapshotting this directory:

- Error in "snapshot/inaccessible-file": permission denied
```
