### ISSUE TITLE
kopia mount should accept general fuse mount options, such as allow_root

### ISSUE THREAD

**Issue by eras** [kopia/kopia#647]
My primary use case is to mount backups and then mount virtual machine images from inside them; but the latter cannot be achieved unless root is able to access the files.

This can be achieved by doing the mounting as root, but it is less convenient than just doing it as the same user.

Preferably the support would include also other standard mount options, as outlined in the fuse(8) manual page.

**Comment by ericek111** [comment]
Is this really not planned, or is it just the useless github-actions bot closing issues by itself?
