### ISSUE TITLE
Error correction feature request

### ISSUE THREAD

**Issue by aidanhs** [kopia/kopia#656]
I've been reviewing a number of backup tools and recently came across kopia, and it looks excellent!

One thing that I couldn't find discussed anywhere was error correction - the only mention I found was a brief question on a thread on the forum (https://kopia.discourse.group/t/data-corruption-checking-flag-clarification/66/8).

To reference some other tools here:
 - borg doesn't have EC - https://github.com/borgbackup/borg/issues/225
 - restic doesn't have EC - https://github.com/restic/restic/issues/256 https://github.com/restic/restic/pull/2441
 - bup *does* have optional support for par2 support

The user 'dumblob' in a couple of those issues above gives a view on what 'complete end to end FEC' might require (which the bup implementation doesn't fulfil) - I would expect getting to there to be an incremental process.

(personally, I'd be 'happy enough' with just the bup approach!)

**Comment by aidanhs** [comment]
As a note to self, I believe this was completed in https://github.com/kopia/kopia/pull/2270

Can read a bit about it at https://github.com/kopia/kopia/blob/b5005c939c96b6b13439761f92a494eef9d13d61/site/content/docs/Advanced/ECC/_index.md

**Comment by dumblob** [comment]
Perhaps proven defaults for long-term storage (10+ years on a hop-on hop-off turned on & off HDD/SSD disk) could be mentioned in the ECC/_index.md file as well as in Kopia documentation.

I speak of the defaults [rsbep-backup](https://github.com/ttsiodras/rsbep-backup ) uses.

**Comment by dumblob** [comment]
Also it seems Kopia went for implementation which does not cover size info of files/chunks (not to be confused with "blocks"). Which simply means it is still highly prone to corruption.

This should be also mentioned **in a red bold text at the very top** of documentation and in comments in the code to not mislead anyone.
