### ISSUE TITLE
Suggestion: A simpler way to request restore of the latest snapshot

### ISSUE THREAD

**Issue by k3a** [kopia/kopia#667]
The syntax to restore is 
`
kopia snapshot restore [<flags>] <source> <target-path>
`

where source is a directoryID.

That works fine but in my case, I often want to restore the latest snapshot of some kind (some device). 
I think it would be helpful if Kopia could find the latest snapshot ID for me without the requirement to manually do `snapshot list` first.

**Comment by adowair** [comment]
I like this suggestion. What could this new command look like? How about this:
```kopia snapshot restore --latest <source-path> <target-path>```
Where, if I am trying to restore my local `~/Downloads` from the latest snapshot taken against it, I'd issue:
```kopia snapshot restore --latest ~/Downloads ~/Downloads```

**Comment by 1iti1** [comment]
I would also like to have the "latest" parameter implemented to automatically restore the latest snapshot.

**Comment by onedr0p** [comment]
My workaround until this is added is:

```bash
kopia snap restore \
    "$(kopia snapshot list /app --json | jq --raw-output '.[-1] | .id')" \
    /data/config
```

**Comment by adowair** [comment]
#2335 now implements support for `latest`, albeit for a given path rather than ID

**Comment by ignaciogutierrez** [comment]
Use this
```
kopia snapshot restore --snapshot-time=latest "Administrator@WinServer:C:\users\Public\Documents"  my-dest-folder
```

**Comment by abstractionmage** [comment]
Thanks, but I don't think the `--snapshot-time=latest` argument satisfies OP's and my need for a simple command to restore the latest snapshot in its entirety.
