### ISSUE TITLE
[Feature Request] never expiring snapshots

### ISSUE THREAD

**Issue by saviodsouza** [kopia/kopia#669]
Hii

I would be nice to have a never expiring snapshot feature. something like sticky tag in addition to latest, hourly, daily weekly, monthly, annually, however the sticky tag is additional to the existing tags with a difference that keep policies will not delete them at all unless sticky tag is removed

something like......
kopia snap /home/userX/Documents --sticky # adds a sticky tag in addition to latest1, hourly1, etc
kopia snap sticky k........ --add # mark an existing snapshot sticky
kopia snap sticky k........ --remove # withdraw the sticky tag

Reference in the forum
https://kopia.discourse.group/t/never-expiring-a-snapshot/153

**Comment by saviodsouza** [comment]
In addition to individual sticky snapshots set policies to sticky which will disable auto deletion of snapshots of newly created snapshots.

**Comment by jkowalski** [comment]
This is now implemented `kopia snapshot pin`
