### ISSUE TITLE
[Feature] Better timed backups

### ISSUE THREAD

**Issue by philippneugebauer** [kopia/kopia#671]
I would like to have a better selection of timed backups: Weekdays, Time, etc.

If that is easy to implement, I might be able to contribute a PR.

**Comment by julio-lopez** [comment]
@philippneugebauer 

At a high level, it seems that there are 2 broad aspects to this feature:
1. Expressing the intent in the policy in a simple way. This requires expressing both (a) when the backup should happen and (b) how it should be retained (for how long, how many of these, etc). An option is to use some form of extended _"cron expressions"_ that includes the retention part, but that may end up being confusing for many users, so if there's a simpler approach, that'd be good. 
2. Computing the actual retention: As new snapshots are created, some of them need to be removed according to the retention policy.

Perhaps the initial problem could be simplified and built on top of the current implementation with the addition of _"offsets"_ for the different frequencies. that is, specifying an offset within the hour for hourly, an offset within the day for daily and so on.

For reference, look at https://github.com/kopia/kopia/blob/master/snapshot/policy/retention_policy.go in the `snapshot/policy` package to get an idea of how kopia does it right now.

Thoughts?

**Comment by philippneugebauer** [comment]
I don't really understand your points.

1.
a) sure, I could design a simple html prototype
b) why does this affect the current policy which cannot be applied anymore?

2. shouldn't it be possible to reuse the current behavior?

**Comment by julio-lopez** [comment]
My apologies, my explanation above is not clear. I should also have asked for some clarification first.

What do you mean by _"a better selection of timed backups: Weekdays, Time, etc."_? Could you give me an example?

**Comment by philippneugebauer** [comment]
sure. E.g. I want to backup each Wednesday, 18:00. Or I want to backup Monday, Wednesday and Friday at 12:00. Or all 4 weeks on a Wednesday at 14:00

**Comment by julio-lopez** [comment]
Thanks for the example.

For how long would you like to retain each of those?

**Comment by philippneugebauer** [comment]
I wouldn't change the current situation with the policy. Multiple days a week should be treated the same as daily backups so I don't see there any problems
