### ISSUE TITLE
 error: snapshot GC failure: unable to find in-use content ID

### ISSUE THREAD

**Issue by francisco1844** [kopia/kopia#675]
Every time full maintenance runs get this error:
`0:16:31.257 [maintenance] Finished full maintenance.
kopia: error: snapshot GC failure: unable to find in-use content ID: error walking snapshot tree: error verifying Ixaf725a51a9d21f01828462a151cbc5bd: content not found, try --help`

**Comment by francisco1844** [comment]
kopia --version
0.7.2 build: 6b756bad40abec83c5fdbb511766716703696745

**Comment by jkowalski** [comment]
I have few questions:

1. was the repo created using 0.7.2 or previous versions?
2. how many hosts are you backing up to this repo?
3. can you stash away the logs in case they are needed for debugging?

**Comment by francisco1844** [comment]
1- Repo was created on older version
2- One single host. I sync other machines to a "storage" machine and then run kopia from there
3- Sure. How far back? Not sure when it started, but seems it is giving that error every day

**Comment by jkowalski** [comment]
If you can hop on slack tomorrow we can take a closer look.

**Comment by jkowalski** [comment]
We resolved this on Slack - turns out it was a combination of bugs (#596 & #650) that have since been fixed.
