### ISSUE TITLE
Public Key signing the checksums.txt is not available on Keyservers

### ISSUE THREAD

**Issue by GraphZal** [kopia/kopia#681]
I just tried verifying the signature for the Checksums given, but was unable, since the key `A3B5843ED70529C23162E3687713E6D88ED70D9D`, which was used to create the signature, is not found on any public keyserver I tried. 

It would be great if the public key could be published, so we can check signatures.

Edit: Also: Could we get a checksum for the source-code archive?

**Comment by jkowalski** [comment]
The key is always available at https://kopia.io/signing-key

I uploaded it to couple key servers (hkp://keyserver.ubuntu.com and hkp://pool.sks-keyservers.net). I'm not really that familiar with GPG, so can you let me know if this works for you?

**Comment by GraphZal** [comment]
I somehow missed that the key is available on the website. Not sure if I was just blind, or if the key could be made more obvious.

sks-keyservers is one of the biggest server-groups around, iirc, so this should be fine. Sadly, they seem to have problems, as I can't find your key there. 
keyserver.ubuntu.com does work fine though!
