### ISSUE TITLE
Insecure steps described at packages.kopia.io/apt

### ISSUE THREAD

**Issue by efficiosoft** [kopia/kopia#687]
Hi,

First, thanks for creating and bringing this project forward! It quickly became the main building block of my backup strategy due to its unique feature set and amazing speed.

I found some repo setup instructions at http://packages.kopia.io/apt/

By nature, the repo site doesn't use HTTPS, however it suggests to blindly download some PGP key. Probably these instructions should be removed alltogether and instead link to the proper section in the docs?

Best regards
Robert

**Comment by jkowalski** [comment]
Good catch, replaced this left-over page with a redirect to https://kopia.io/docs/installation/
