### ISSUE TITLE
Allow overwriting the web root of kopia server for hosting behind reverse proxy

### ISSUE THREAD

**Issue by bob1de** [kopia/kopia#688]
Hi,

I would like to use the kopia server for backing up different servers and workstations to a common repo. However, in order to do TLS termination and access control centrally in a uniform way, all externally available web services sit behind a reverse proxy that serves services at different subdirectories. Of course, this results in kopia generating incorrect URLs on its web pages.

Would it be possible to support a syntax like `kopia server start --address http://127.0.0.1:51515/foo` to indicate that the server should serve all its resources at `/foo` and also construct URLs of static files etc. accordingly?

NextCloud, for instance, has an option for this called `overwritewebroot`, others have similar adjusting screws.

Thanks for considering!

Best regards
Robert

**Comment by jkowalski** [comment]
that should not be hard to implement.

**Comment by efficiosoft** [comment]
I absolutely never looked into Golang so far and thus prefer not to try implementing this myself, but needless to say that I could test the feature in case it gets implemented.

**Comment by sonnyka** [comment]
Any progress in this? Would help me a lot. :-)
