### ISSUE TITLE
Non-owners can change and disconnect repository config via HTTP server

### ISSUE THREAD

**Issue by efficiosoft** [kopia/kopia#693]
Kopia v0.7.3

Hi,

Today I connected to the `kopia server` via browser as a htpasswd-based user, but one which is not the repository owner. As that user, I could change repository config and even disconnect the whole repository, connect to a different one and thus hijack the server and steal future snapshots without the owner even noticing.

Is This wanted behavior? I expected the whole repository tab to be hidden in the UI if connected as a user which is not the repo owner.

Thanks and best regards
Robert

**Comment by jkowalski** [comment]
Can you describe the scenario in more detail? I'm not sure I follow the point about not being the repository owner.

**Comment by efficiosoft** [comment]
> Can you describe the scenario in more detail? I'm not sure I follow the point about not being the repository owner.

Sure, I'll try.

I run `kopia server start --htpasswd-file kopia.htpasswd`. The password file defines two users: root@host1 and root@host2. The server is ran by root@host1, which is also the one who created the repository and thus is responsible for maintenance. I call this user the "repository owner", but I guess that term is only related to maintenance tasks and there is not really a concept of administrative ownership for a repository.

Now I open `http://127.0.0.1:51515` in a web browser and authenticate as root@host2. The server prints "serving patched index" to stdout, probably telling the served index only contains snapshots created by root@host2. So far, so good.

However, back in my web browser, I can now open the repository tab, disconnect the server from its original repository and connect it to another one of my choice. At that point I haven't tried creating new snapshots on the still running server, but I guess they would end up in the new, compromised repository (why shouldn't they?), which basically allows root@host2 to steal subsequent snapshots of all users on that server.

All of this works no matter as which of the users defined in my htpasswd file I'm authenticated as, which is a privilege escalation issue IMHO, unless I got something totally wrong here.

BTW, `kopia server start --help` suggests that the web interface is only activated when passing `--ui`, but it is reachable even without this flag, or should I open another issue for that?

HTH
