### ISSUE TITLE
Backups aren't executed anymore

### ISSUE THREAD

**Issue by philippneugebauer** [kopia/kopia#694]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/1623885/97629244-1c447b80-1a2e-11eb-97ac-fca3b86e616a.png">

That's what my backups look like since a while. They start all the time, do a bit, then they stop and always in 5minutes is displayed. Unfortunately, I do not get an error message.

**Comment by jkowalski** [comment]
Can you try running the snapshot from CLI (`kopia snapshot create --all` and see if you get any errors?)

**Comment by philippneugebauer** [comment]
worked without any problems and created a new snapshot. Needed a restart in the UI to be executed though

**Comment by lupusA** [comment]
Hi @philippneugebauer, 

is this still an issue? 

Cheers,

**Comment by philippneugebauer** [comment]
I never used kopia afterwards anymore
