### ISSUE TITLE
[Feature Request] have a configuration-file less / stateless mode

### ISSUE THREAD

**Issue by 0x53A** [kopia/kopia#695]
I'm investigating a use of kopia from a CI server. Unfortunately, these servers are shared by multiple processes concurrently, and are also not cleaned up after each run.

This means I'd like to run kopia in a "stateless" mode where I pass the connection parameters directly to the kopia executable and it does not need to touch either global configuration files or the keychain / credential manager.

I [thought](https://github.com/kopia/kopia/issues/502#issuecomment-719975650) I could work around the global configuration file by just using a repository-local configuration file, but according to the documentation passwords are still saved in the credmanager.

My preference would to add a ``--token`` parameter to all commands that currently accept a ``--config-file``, would this fit your plans?

__Edit: this already works, use ``--no-use-credential-manager``, ``--config-file`` and ``--password``.__

**Comment by jkowalski** [comment]
This would not be very efficient (no caching), but in principle it could be done. Passing `--token` sounds like a good idea, probably even better if it was an environment variable.

What are you trying to do on the CI server? Take a snapshot?

**Comment by 0x53A** [comment]
So this might be out of the scope of kopia, but I'd like to investigate using kopia as a deduplicating store for all the build artefacts

**Comment by jkowalski** [comment]
1k of snapshots is not a problem at all since manifests are so tiny, I would be worried probably with 100k or more.
