### ISSUE TITLE
Authenticated server user can see all other users’ snapshots via web interface

### ISSUE THREAD

**Issue by draga79** [kopia/kopia#701]
I’ve noticed a problem: I’ve created a repository and, then, started a Kopia server to connect to that repository. I have some clients (each with different user/password) as I want to use a single repository for deduplication purposes. If I type “kopia snapshot ls --all” from a single client I can only see its snapshots, and it’s ok. But if I connect via web browser to https://xxxx:51515 and fill in any username and password set in the password file, I can see all the snapshots of all the clients.

**Comment by jkowalski** [comment]
Fixed with #871
