### ISSUE TITLE
Failed snapshot due to `interrupted system call`

### ISSUE THREAD

**Issue by julio-lopez** [kopia/kopia#702]
Backing up a directory in an Azure Files volume (mounted via SMB/CIFS) fails due to `interrupted system cal`

```
 unable to process directory "dist": read /www/xx/yy/zz.js: interrupted system call, try --help
```

Currently trying to narrow down which specific sys call.

cc: @bathina2

**Comment by julio-lopez** [comment]
The root cause seems to be the same as in restic/restic#2659

**Comment by julio-lopez** [comment]
golang/go@6b420169d798c7ebe733487b56ea5c3fa4aab5ce

**Comment by jkowalski** [comment]
It appears that the fix is in Go 1.16. Other than waiting for that, is there much we can do?

**Comment by julio-lopez** [comment]
golang/go#40846

**Comment by julio-lopez** [comment]
Dunno, maybe adding wrappers in the mean time that we would undo once 1.16 is out. 1.16 is ~2.5 months out.

**Comment by julio-lopez** [comment]
Not sure, but this issue may (or may not) also affect reading files from kopia snapshots mounted via FUSE. Needs investigation.

**Comment by julio-lopez** [comment]
Go 1.16 beta1 is coming out soon. It may be a good idea to test whether this particular issue is resolved with a custom build of kopia.

**Comment by julio-lopez** [comment]
This should be fixed with #842

**Comment by julio-lopez** [comment]
Re-opening until it is fully verified.

**Comment by julio-lopez** [comment]
cc: @pavannd1

**Comment by jkowalski** [comment]
@julio-lopez can this be closed now?
