### ISSUE TITLE
kopia snapshot list --all returns stale data

### ISSUE THREAD

**Issue by 0x53A** [kopia/kopia#704]
Scenario: Two computers connected to the same repository

1) Create snapshot 1 on computer A
2) Create snapshot 2 on computer B

``kopia snapshot list --all`` on ``A`` will return only ``1``. On B it will return ``1`` and ``2``.

3) Create snapshot 3 on computer A

Now ``kopia snapshot list --all`` on ``A`` will return ``1``, ``2`` and ``3``. On B it will still only return ``1`` and ``2``.

4) wait a few minutes

Now it returns the correct result on both computers.

----------

__Expected result:__

``kopia snapshot list --all`` should be an online operation that always queries the repository. (or optionally a ``--force-refresh`` argument)

__Actual result:__

There seems to be a rather large cache timeout of multiple minutes (after 5 minutes it was NOT visible, after 9 minutes it was).

---------

I looked at the documentation whether there is something like ``snapshot refresh`` but couldn't find anything.

``kopia --version`` 0.7.3 build: c3ade4b0ea7a1d20497fcfc4f4aec161f73c9505

Backend: s3 (wasabi)

**Comment by 0x53A** [comment]
Aha!

I found the index cache (https://github.com/kopia/kopia/pull/46/files#diff-06e9c27f8ddaf020809170d4da8beb2cafb0ea18492bcbbd44b8f7fa6859a387R13-R16)

It defaults to 600 seconds (10 minutes).

So I can change it with the command ``kopia cache set --max-list-cache-duration=30s``

**Comment by julio-lopez** [comment]
@0x53A Thanks for the detailed report and the followup debugging.

For various uses cases, in particular where the user is only looking at the snapshots of the same hosts, then this is less of an issue. But as you pointed out, it delays making the snapshots visible in other hosts.

I am wondering whether the default value should be changed and what the performance implications would be, or if there is another way of addressing the issue.

**Comment by 0x53A** [comment]
I can only speak for myself, but I'd intuitively expect ``snapshot list`` to bypass the cache and always query the repository. Otherwise a new parameter to do that would be really useful if you want to keep the current default.

Really bad comparison, but imagine if ``git pull`` had a 10 minute cache ¯\\\_(ツ)_/¯

**Comment by julio-lopez** [comment]
Fair point.

**Comment by 0x53A** [comment]
for the record, [--no-list-caching](https://github.com/kopia/kopia/issues/824#issuecomment-776387066) should solve this issue.
