### ISSUE TITLE
S3 strong consistency guarantees

### ISSUE THREAD

**Issue by flibustenet** [kopia/kopia#705]
https://aws.amazon.com/fr/blogs/opensource/community-collaboration-the-s3a-story/
Now AWS S3 has strong consistency.
Will it help reduce complexity in kopia, improve reliability ?
I believe Minio, Azure, GCS has also. But Scaleway (S3 compatible) has not currently.
Will kopia stay safe with ou without strong consistency ?
Could it be an option by service to reduce requests when consistency is guarantee ?

Thank you for your informative comments !

**Comment by jkowalski** [comment]
With strong consistency Kopia should be able to perform cleanups faster but there would not be much in terms of reduction of api traffic. 

Currently Kopia writes compaction logs and cleanup logs and delays trusting them until all writes have reliably settled (this is set to 1hr today to be very conservative). 

If we can have reliable LIST-after-PUT and LIST-after-DELETE we can get rid of some of these blobs altogether. 

Despite AWS S3 being strongly consistent I don’t think other S3-like providers provide list after delete strong consistency yet, so this optimization would need to be on case by case basis. 

@julio-lopez would you be interested in investigating that?

**Comment by julio-lopez** [comment]
If there is a reliable way to tell whether the store is AWS S3 vs. other S3-compatible ones, then kopia could at least initially treat AWS S3 as a consistent blob store. Then we could incrementally look at the other S3-compatible ones on a case-by-case basis.

**Comment by jkowalski** [comment]
We can expose provider-level function, say `IsStronglyConsistent()` that would detect the endpoints in use and for AWS S3 (and other known to be strongly consistent) it would return true but for others false (to be conservative)

**Comment by angristan** [comment]
> I believe Minio, Azure, GCS has also. But Scaleway (S3 compatible) has not currently.

FYI, Scaleway has strong read-after-write consistently.
