### ISSUE TITLE
Panic on repository  connect from-config --token

### ISSUE THREAD

**Issue by 0x53A** [kopia/kopia#706]
I have this on two computers, four crashes total:

```
Starting target 'CopyServerbuildOutputToKopiaRepository'
> "C:\serverbuildroot\2012021330-418066156-18428\Projekte\a_CommonBinaries\ThirdParty\Kopia\kopia.exe" repository connect from-config --token [MASKED] (In: false, Out: false, Err: false)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xd9a9df]
goroutine 67 [running]:
io.ReadAtLeast(0x0, 0x0, 0xc000662000, 0x200, 0x200, 0x200, 0x0, 0x1, 0xc00007d6e0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/io/io.go:314 +0x5f
io.ReadFull(...)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/io/io.go:333
github.com/minio/minio-go/v6.Client.getObjectWithContext.func1(0xc00065c000, 0xc00065c060, 0xc00065c0c0, 0xc0004561d0, 0xc00063e060, 0xc00064c000, 0x1c2fb40, 0xc00002f4a0, 0xc0001084e0, 0x15, ...)
	/home/travis/gopath/pkg/mod/github.com/minio/minio-go/v6@v6.0.58-0.20200612001654-a57fec8037ec/api-get-object.go:109 +0x485
created by github.com/minio/minio-go/v6.Client.getObjectWithContext
	/home/travis/gopath/pkg/mod/github.com/minio/minio-go/v6@v6.0.58-0.20200612001654-a57fec8037ec/api-get-object.go:66 +0x359
Finished (Failed) 'CopyServerbuildOutputToKopiaRepository' in 00:00:02.3514407
```

It did work for a while, then started failing on both of them, so a first guess might be repository corruption?

--------

I did have a kopia server running on my laptop (where I originally created the repo) because I used the UI and forgot to shut it down.

There was a maintenance task running, and my internet has been ... flakey.

I tried to stop it with CTRL+C, but it hung:

```
kopia server start --address="http://127.0.0.1:12345"
SERVER ADDRESS: http://127.0.0.1:12345
Open the address above in a web browser to use the UI.
serving patched index
Running quick maintenance...
Rewriting contents from short packs...
Looking for unreferenced blobs...
Deleted total 0 unreferenced blobs (0 B)
Compacting indexes...
Finished quick maintenance.
Running quick maintenance...
Rewriting contents from short packs...
Shutting down...
```

---------------

After stopping the server and the maintenance task, disconnect and connect works from my laptop.

It still reproducibly panics on the other computers.

So maybe the local cache is corrupted?

----------------

Environment:

Windows 10 x64 2004
Kopia 0.7.3

Repository: S3 / Wasabi

**Comment by jkowalski** [comment]
This appears to be s3 related, possibly wasabi specific. I think I’ve seen this error on wasabi before but it was very rare. 

I do think think this indicates repository corruption. 

If you can consistently reproduce this can you hop on slack so we can debug interactively?

**Comment by 0x53A** [comment]
The issue was an intercepting SSL proxy blocking wasabi, sorry!

**Comment by julio-lopez** [comment]
@jkowalski: does #707 address the panic?

**Comment by 0x53A** [comment]
with #707:

```
failed to open repository: unable to open content manager: error loading indexes: Last-Modified time format is invalid, failed with parsing time "" as "Mon, 02 Jan 2006 15:04:05 GMT": cannot parse "" as "Mon"
kopia.exe: error: unable to open content manager: error loading indexes: Last-Modified time format is invalid, failed with parsing time "" as "Mon, 02 Jan 2006 15:04:05 GMT": cannot parse "" as "Mon", try --help
```

which is much better than the panic

**Comment by julio-lopez** [comment]
Better yes. It provides some information about where the failure was: `error loading indexes`.
The last part ("Last-Modified ...") is misleading and confusing. But anyway.

**Comment by 0x53A** [comment]
> The last part ("Last-Modified ...") is misleading and confusing. But anyway.

Our intercepting proxy returns a HTML Page that says the request was blocked __and status code 200 OK__. So the calling app can't easily check that something went wrong, and then chokes somewhere when it tries to interpret the response.

I _assume_ that if a better proxy returned an appriopriate status code, it would show that in the output.
