### ISSUE TITLE
cp from mounted snapshot fails (i/o error)

### ISSUE THREAD

**Issue by enboig** [kopia/kopia#712]
System: ubuntu 20.04
kopia 0.7.3 build: c3ade4b0ea7a1d20497fcfc4f4aec161f73c9505
storage: S3 Wasabi

I mounted a snapshot and tried to copy a virtual machine disk (max file size 2G), but it fails. When downloading files using de UI (one by one...) there is no problem.

I know I give very little information, but I don't know how to enable a "verbose" mode to get more info.

**Comment by julio-lopez** [comment]
Wondering (really a shot in the dark), whether the root cause is the same as the one for #702
