### ISSUE TITLE
kopia mount does not work on Windows

### ISSUE THREAD

**Issue by CrendKing** [kopia/kopia#716]
In Windows, the mount function does not seem to work. Here’s what I did:

1. `kopia snapshot list`. Pick a snapshot ID.
2. `kopia mount <snapshot_id> x:`
3. Log:
```
2020-12-14 13:14:18.596 D [manifest_manager.go:288] listing manifest contents
2020-12-14 13:14:18.602 D [mount_webdav.go:32] creating webdav server...
2020-12-14 13:14:18.604 D [mount_net_use.go:41] running c:\windows\system32\net.exe [net use x: http://127.0.0.1:3132]
2020-12-14 13:14:18.623 D [mount_net_use.go:44] net use finished with  exit status 2
2020-12-14 13:14:18.623 D [mount_webdav.go:60] web server finished with http: Server closed
2020-12-14 13:14:19.124 D [logging_storage.go:28] [STORAGE] GetBlob("kopia.maintenance",0,-1)=({2141 bytes}, <nil>) took 0s
2020-12-14 13:14:19.124 D [maintenance_run.go:80] full manintenance cycle not enabled
2020-12-14 13:14:19.124 D [maintenance_run.go:92] quick manintenance cycle not enabled
2020-12-14 13:14:19.124 D [maintenance_run.go:171] not due for maintenance
2020-12-14 13:14:19.125 D [logging_storage.go:87] [STORAGE] Close()=<nil> took 0s
2020-12-14 13:14:19.126 D [memory_tracking.go:31] in use heap 3375104 (delta 3375104 max 0) stack 524288 (delta 524288 max 0)
```
I also went to made sure `net use` itself is working by sharing a folder and net use map to a drive. Something might be wrong with webdav.

OS: Windows 10
Version: 0.7.3 build: c3ade4b0ea7a1d20497fcfc4f4aec161f73c9505

**Comment by CrendKing** [comment]
Turns out this was caused by my `WebClient` service being disabled. I must have disabled it long time ago to test something. Once enabled and started, mounting works.

However, when I press Ctrl-C to unmount, it hangs at "Unmounting..." and no longer accept any input. I have to close the console altogether. The unmount was completed though, and the log file shows that. After some digging, I found that the hang is at https://github.com/kopia/kopia/blob/60aec0ee9f5ce41888e260f91e15fd459c40c875/cli/command_mount.go#L95. I know the `Done()` call is completed, but it hangs with the channel operator `<-`. I'm not familiar with the channel operator in Go, so I have no idea why is it needed here. However, if I remove that operator, everything works as expected.

I have a PR to demonstrate the change. Use your discretion though, as I don't know how this would affect other operating systems: https://github.com/kopia/kopia/pull/754

**Comment by jkowalski** [comment]
Thanks for #754. Would you be able to also add better error message when webdav fails due to Windows service being disabled? This would improve the experience for new users.

**Comment by CrendKing** [comment]
I can certainly do that, but how do you want to approach it? When the service is disabled, `net use` just returns an error code 2 ([ERROR_FILE_NOT_FOUND](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-#ERROR_FILE_NOT_FOUND)), which means network resource is not found. But this error could be caused by many other reasons. Is it enough to say something like "This error is often caused by but not limited to the 'WebClient' service being unable to start. Please check."?

**Comment by jkowalski** [comment]
That Sounds good.

**Comment by CrendKing** [comment]
PR: https://github.com/kopia/kopia/pull/757

When you say "GH issue", are you talking about this issue (#716)? Since we also discussed about the channel stuff, I think it might confuse users. Linking to external resource (such as https://superuser.com/questions/505191/mounting-webdav-drive-in-windows-server-2012) could be useful but also a bit distracting. You never know when that webpage goes away.

Ideally we could create a wiki page for ALL recognizable error codes and provide solution for each and link in the error message. But we only have one (error code 2) at the moment, and you will need to enable wiki functionality for this repository. It's up to you.

**Comment by jkowalski** [comment]
or we can just add a page to `kopia.io` - the source code is under `site`
