### ISSUE TITLE
kopia UI leaves orphan rclone.exe process from rclone repository 

### ISSUE THREAD

**Issue by CrendKing** [kopia/kopia#717]
Create a rclone repository and connect it. Launch kopia UI. Wait for the connection to complete then shutdown kopia UI. I can find the rclone process still lingers in task manager (along with the conhost.exe)

OS: Windows 10
Version: 0.7.3 build: c3ade4b0ea7a1d20497fcfc4f4aec161f73c9505

**Comment by julio-lopez** [comment]
@jkowalski IIRC you fixed this. Should we close this issue?

**Comment by jacklul** [comment]
Unfortunately the issue is still there.
Single Rclone remote ('repository.config'), after closing KopiaUI `rcone.exe` is still there. After I re-open KopiaUI another `rclone.exe` is spawned, exiting KopiaUI does not kill it.
