### ISSUE TITLE
[Feature]: make distinct paths in repo mountable

### ISSUE THREAD

**Issue by budachst** [kopia/kopia#738]
When running snapshots from different paths against the same repo - in our case a 380 share Samba server, it would be really good to be able to mount any of these snapshot paths separately, prefereably with the option to access all snapshots. 

The syntax for this could maybe be like this:

`kopia mount user@host:/path <mountpoint>`

This would be a tremendously good thing to present all the snapshots of a Samba share to its owners/users.

**Comment by bbccdd** [comment]
Great improvement idea indeed! 

Linking forum post that sparked it: https://kopia.discourse.group/t/mount-not-snapshot-but-the-whole-snapshot-tree/203/8
