### ISSUE TITLE
[Question] how do I use use the flag --use-credential-manager?

### ISSUE THREAD

**Issue by 0x53A** [kopia/kopia#740]
Because of https://github.com/kopia/kopia/issues/732 I want to stop using the credential manager.

But how do I actually use the flag ``--use-credential-manager``?

https://github.com/kopia/kopia/blob/f66fe5789ec3edb174c108bb074f4e93400bc757/cli/password_windows.go#L6

By default, it is enabled.

I tried ``\kopia.exe repository connect from-config --use-credential-manager=false --token=#####``, but that failed with 

```
kopia.exe: error: unexpected false, try --help
```

**Comment by julio-lopez** [comment]
Try:

   kopia.exe repository connect from-config --no-use-credential-manager --token=<actual_token>

**Comment by 0x53A** [comment]
Thank you!
