### ISSUE TITLE
Backup of root UNC path not working

### ISSUE THREAD

**Issue by YEGrolo** [kopia/kopia#751]
I am using KopiaUI 0.7.3 on Windows 10.

I have browsed to and selected the UNC path “**\\\server\backup**” as the source. When I select “Snapshot now” the status changes to “Uploading 0 bytes” and immediately stops. I also tried with a trailing “\” - “\\\server\backup\” but it does the same thing.

In the main.log it looks like it is appending “backup” to my UNC path:
`[2020-12-27 19:18:40.918] [info] snapshot error: upload error: open \\server\backup\backup: The system cannot find the file specified.`

If I select an individual subfolder as my source (i.e. “\\\server\backup\Documents”) the backup seemingly works as expected.

Edit: I just duplicated my share as “**\\\server\bkp**” as a quick test and had the same issue. This time the error in the log was:

`[2020-12-28 19:36:29.715] [info] snapshot error: upload error: open \\server\bkp\bkp: The system cannot find the file specified.`

So it appears it is appending the share name to itself.

**Comment by jkowalski** [comment]
This should be fixed in https://github.com/kopia/kopia/releases/tag/v0.8.0-beta1

**Comment by YEGrolo** [comment]
I've just gotten around to testing this application again and unfortunately things still aren't working when trying to select a network share.

I am now using 0.8.1 with KopiaUI on Windows 10.

From KopiaUI I can no longer use the UNC path to a network resource at all.

When creating a **New Snapshot**, I can browse to the network location (**\\\\server\backup**) but after selecting the path I cannot do anything else.

Clicking **Estimate** returns the error:
`{"code":"INTERNAL","error":"internal server error: can't get local fs entry: unable to determine entry type: CreateFile C:\\Users\\username\\server\\backup: The system cannot find the path specified."}`

In this instance it has appended the selected Network path to my local user profile path **C:\Users\username**

Clicking Snapshot Now returns the error:
`Error: path does not exist (PATH_NOT_FOUND)`

Attempting to create this via command prompt:
```
C:\Program Files\KopiaUI\resources\server>kopia snapshot create \\server\backup
Snapshotting username@rog:\\server\backup ...
Running full maintenance...
Looking for active contents...
Looking for unreferenced contents...
Not enough time has passed since previous successful Snapshot GC. Will try again next time.
Rewriting contents from short packs...
Skipping blob deletion because not enough time has passed yet (59m59s left).
Finished full maintenance.
ERROR: upload error: unable to read directory: open \\server\backup\backup: The system cannot find the file specified.

C:\Program Files\KopiaUI\resources\server>kopia snapshot list

C:\Program Files\KopiaUI\resources\server>
```
You can see above it has once again appended the share name twice to the UNC path showing **\\\\server\backup\backup**

Wrapping the path in quotes has the same effect:
```
C:\Program Files\KopiaUI\resources\server>kopia snapshot create "\\server\backup"
Snapshotting username@rog:\\server\backup ...
ERROR: upload error: unable to read directory: open \\server\backup\backup: The system cannot find the file specified.
```

If I can help test this in any other way for you or provide any other info please let me know.
