### ISSUE TITLE
Update docker images

### ISSUE THREAD

**Issue by Neurrone** [kopia/kopia#758]
Was looking for docker images for Kopia, and I found [these from 10 months ago](https://hub.docker.com/r/kopia/kopia/tags?page=1&ordering=last_updated).

Could this be kept up to date as new releases come out?

**Comment by julio-lopez** [comment]
A few unofficial images not tracking particular releases at https://hub.docker.com/r/kanisterio/kopia/

**Comment by julio-lopez** [comment]
Images are now being automatically pushed to [Docker hub](https://hub.docker.com/r/kopia/kopia/tags?page=1&ordering=last_updated)
