### ISSUE TITLE
Add support for s3 storage classes

### ISSUE THREAD

**Issue by olfway** [kopia/kopia#759]
Amazon has different storage classes with different prices

https://aws.amazon.com/s3/storage-classes/

but it seems there is no way to configure s3 storage class in kopia

**Comment by acl1704** [comment]
Are lifecycle rules insufficient for this operation?

**Comment by olfway** [comment]
I guess it's possible to do it with lifecycle rules but it will be easier to specify it in kopia

**Comment by andrewhampton** [comment]
I just discovered kopia on Hacker News today and this was my first question. I have a script that does daily backups using the glacier storage class. Will the delayed access of the glacier storage class work with kopia? In other words, does it store files in s3 that it needs immediate access to?

**Comment by acl1704** [comment]
> 
> 
> I just discovered kopia on Hacker News today and this was my first question. I have a script that does daily backups using the glacier storage class. Will the delayed access of the glacier storage class work with kopia? In other words, does it store files in s3 that it needs immediate access to?

Glacier will work but it'll take more time. You'd need to restore to hot storage before being able to run repository maintenance operations or make a new snapshot. In the past I did just that on Scaleway: restore the whole bucket, run snapshot creation and maintenance, and let lifecyles move it back to glacier. But AWS-specific charges for restoring glacier objects may not be cost effective as another provider.

**Comment by julio-lopez** [comment]
https://aws.amazon.com/s3/storage-classes/intelligent-tiering/ may work for most cases.
