### ISSUE TITLE
benchmark compression

### ISSUE THREAD

**Issue by icepic** [kopia/kopia#764]
I you choose a file to take data from while benchmarking compression, the block-size parameter is ignored.

I expected it to use the first X MB from the given file used for tests and not the whole VM image disk I gave it alongside with a size. =)

If I don't give a file to take data from, it shows 100 (rep#) * block-size, if I set repetitions, size and give it a file, it becomes rep# * <sizeof-file> and the block size doesn't seem to be involved. If block-size is used (perhaps as some input to the compressor or so), I would still like an option to grab only a part of the input-file, since I wanted to use real-world data for choosing compression algorithm, but the rep*file-size quickly outgrew my ram when choosing poor input files at my end.

**Comment by jkowalski** [comment]
That's a great idea, i'm going to mark it as good first issue and will be happy to review PRs. This is a good opportunity to contribute code to Kopia.

**Comment by icepic** [comment]
Solved in 0.9.0-rc3 (or before)
