### ISSUE TITLE
docs for Flags

### ISSUE THREAD

**Issue by icepic** [kopia/kopia#777]
Some small nits,

1.  the "Edit this page" thing for github points to nowhere is it gives the GH 404.
2. the flags should probably be sorted alphabetically so --help, --help-full, --help-man and --help-long get grouped together
3. The --log-level doesn't really document what levels exist, only shows you the default. The source says debug, warning and error also exist, so the Flags doc page should probably list them.
4. I didn't manage to find the source for the flags.md or any other occurences of "log-level" apart from the one place in the source in order to produce a diff to it, so an issue it is.

**Comment by jkowalski** [comment]
currently the CLI section of the docs (markdown) is generated dynamically from the source code. 2&3 are possible to fix by modifying the code generator (in `site/cli2md`). 

re:1, this is part of the website template, which is quite complex, but it should be possible to at least selectively disable it or change to point at cli2md location for those pages.
