### ISSUE TITLE
docs page missing a lot of formatting.

### ISSUE THREAD

**Issue by icepic** [kopia/kopia#781]
The descriptions of behaviours is very confusing to read as it is:
![Screen Shot 2021-01-12 at 14 06 48](https://user-images.githubusercontent.com/239532/104318379-9d64c800-54df-11eb-8d96-2584ab77114b.png)
(tested on both Chrome and FF)

**Comment by julio-lopez** [comment]
This part is auto generated from the CLI commands. So improving it requires some enhancements to the `cli2md` translator [tool](/kopia/kopia/blob/master/site/cli2md/cli2md.go).

**Comment by lupusA** [comment]
Should be fixed by now (https://kopia.io/docs/reference/command-line/common/)

Cheers,
