### ISSUE TITLE
[Feature] Improve large files snapshot performance

### ISSUE THREAD

**Issue by HenriTEL** [kopia/kopia#784]
Hi, first I want to thank you for this work, we really like this tool for it's simplicity and unique features.

### Use case
We want to use it to incrementally backup a few large mongoDB files (one per collection) that are already snappy compressed, especially one of 500 GB and one of 1.6 TB on GCS.

### Problem
The process underuses host resources and takes a lot of time (orders of magnitudes slower than rsync).
Even incremental backups are slow.

### Command used
`kopia snapshot create --parallel=20 --checkpoint-interval=180m /srv/bigstorage/pvc-506e553a-3adc-11eb-ab33-4c52620a9fcb/`

### Symptoms
During the process, almost none of the 64cpu is >50% busy, there is 37GB of free memory, disks are nvme.
At the beginning the disk reads at 600MB/s but over time performances decreases until reaching 16MB/s.
The number of hashing processes also decreases from 20 to 1.

Is this expected ?
If not do you think that it is possible to improve resources usage by taking advantages of the concurrency features of golang ?

**Comment by jkowalski** [comment]
Currently concurrency is on a file-by-file basis, individual files are not sharded yet, but we should be able to do that. There are some primitives already built in to be able to do that (concatenation support), but more work is needed.

**Comment by HenriTEL** [comment]
I'd like to work on this, could you please indicate where are the primitives as a starting point ?
