### ISSUE TITLE
Lack of webdav credentials docs

### ISSUE THREAD

**Issue by yurikoles** [kopia/kopia#80]
I didn't found any documentation on connection to webdav with authorization.

**Comment by jkowalski** [comment]
you're right, looks like it was never implemented :) should be an easy fix

**Comment by yurikoles** [comment]
Could you please give me an example how to create webdav repo with auth?

I hope to provide a PR.

**Comment by jkowalski** [comment]
The provider should already support the auth via [Options](https://github.com/kopia/kopia/blob/master/repo/blob/webdav/webdav_options.go).

What's left to do [here](https://github.com/kopia/kopia/blob/master/cli/storage_webdav.go) is translating command-line flags to those options.

**Comment by yurikoles** [comment]
@jkowalski thanks! But it still doesn't expose to help command :(
