### ISSUE TITLE
Repository corruption

### ISSUE THREAD

**Issue by kamushadenes** [kopia/kopia#806]
Hello there!

Just read about Kopia and it looks incredible, I'm eager to test it.

I'm currently considering moving from Duplicacy due to terrible restore times. I used borg and restic on the past, and was always concerned about repository/backup corruption, having been bitten by this issue more than a few times, specially with restic.

Ignoring the backend and assuming everything that was written was stored faithfully, what Kopia does to ensure it's own schema doesn't get corrupted by some bad writes or bugs?

I saw the relevant documentation:

```Kopia files can be often recovered even after partial loss of repository contents, because key index information and repository metadata is stored redundantly to prevent single points of failure```

And also https://kopia.io/docs/compatibility/, but I would like to know more about this very important point.

Also, which guarantees do I have that if this project gets abandoned I'm able to retrieve my files? I know, I'm responsible for storage, but I mean I don't want to reverse engineer the repository in case source code disappears for some reason.

Thanks, and keep up the good work!

**Comment by jkowalski** [comment]
Kopia does a number of things to protect the data from corruption on many levels:

- all contents are checksummed when writing and validated on read
- all index blobs are encrypted/checksummed and validated
- all local caches are checksummed/validated
- all repository blob writes are atomic (provided by either cloud providers or atomic writes for local filesystem)
- the format blob is redundantly stored to allow recovery when the master copy is destroyed
- index blobs are redundantly stored in pack blobs and can be completely recovered from surviving blobs
- there are tools to verify the consistency of the repository and fix any issues found (both high-level and low-level repair tools)
- the way kopia writes data is designed to be consistent in case of crashes on all levels (hardware, OS, process, etc.)
- we have mechanisms for dealing with eventually-consistent storage systems that sometimes don't make the data immediately readable after a write

Having said that, in all systems that are complex enough there will always be bugs, the more mature the system is, the fewer of those, but some rules of thumb will always apply:

- always have a backup (that means have at least two types of backups using different technologies that will not have correlated failures, backup to separate cloud providers)
- regularly test your backups (kopia has tools for that)

**Comment by kamushadenes** [comment]
Thank you for the detailed explanation and responsiveness.

Have a great day!
