### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by flibustenet** [kopia/kopia#81]
This backup tools looks a lot like borg and restic. Borg cannot backup directly to object storage and restic doesn't allow compression.
Will kopia allow compression to become the ultimate backup tools ?

Thanks

**Comment by jkowalski** [comment]
Compression should not be very difficult to add on per content-basis before content gets encrypted. We could mark encrypted contents with a special prefix like `z` to distingush them from regular contents.

**Comment by jkowalski** [comment]
update on implementation in #145: instead of content-level encryption, I implemented object-level encryption with special object prefix "Z" to distinguish compressed objects from non-compressed ones.

**Comment by flibustenet** [comment]
\o/

**Comment by julio-lopez** [comment]
@jkowalski meant to say _compression_ in the comment above 😄
