### ISSUE TITLE
Creating a policy with a schedule does not spin up scheduled snapshots unless a manual snapshot is taken

### ISSUE THREAD

**Issue by cooperaj** [kopia/kopia#813]
I'm attempting to put together an Ansible module to allow provisioning of backups on servers without manual management of a configuration file. 

What I'd like to do is setup snapshots that run on a schedule. There are two ways to do this right now, run a snapshot with a schedule option attached, and create a policy with a schedule. The former works fine but is not suitable to be used in provisioning as it runs the snapshot right away and this could take a long time. The latter would be ideal except it does not ever start its schedule.

**Replication**
`kopia policy set --snapshot-interval=0h0m30s $(pwd)`

This creates a policy with a schedule for the current directory. Assuming no snapshot exists for this directory nothing will happen at this point. You can wait > 30 seconds and a snapshot is not made.

**Expected Behaviour**
Creating a policy for a snapshot location that doesn't exist will cause the server to start a snapshot at that location when the schedule is met.

For example running the above command at 12:35:04 will result in a snapshot being created by the server process at 12:35:30.

**Comment by dcasado** [comment]
I'm facing the same issue.

Setting the interval in the policy like `kopia policy set /some-path --snapshot-interval 30m` does nothing.

The policy seems correct
```
$ kopia policy show /some-path
Policy for ubuntu@ubuntu:/some-path:

Retention:
  Annual snapshots:    3           inherited from (global)
  Monthly snapshots:  24           inherited from (global)
  Weekly snapshots:    4           inherited from (global)
  Daily snapshots:     7           inherited from (global)
  Hourly snapshots:   48           inherited from (global)
  Latest snapshots:   10           inherited from (global)

Files policy:
  Ignore cache directories:        true       (default)
  No ignore rules.
  Read ignore rules from files:
    .kopiaignore                   inherited from (global)
  Scan one filesystem only:       false       (default)

Error handling policy:
  Ignore file read errors:       false       inherited from (global)
  Ignore directory read errors:  false       inherited from (global)
  Ignore unknown types:           true       inherited from (global)

Scheduling policy:
  Scheduled snapshots:
    Snapshot interval:        30m0s  (defined for this target)
  Manual snapshot:           false   (default)

Compression disabled.

No actions defined.
```

Is there anything that I'm missing?

**Comment by dcasado** [comment]
Searching for an answer I just found out that you have to use the server or GUI to use the scheduling. https://kopia.discourse.group/t/policy-schedule/74

It would be nice to have that in the documentation because it's not very clear.
