### ISSUE TITLE
What is the supported way to set snapshot hostnames now?

### ISSUE THREAD

**Issue by Novex** [kopia/kopia#816]
It looks like the --hostname (and --username) flags were removed from the snapshot create command in 0.6.0 by https://github.com/kopia/kopia/pull/441.

What's the supported way now to set the hostname/username for taking a snapshot?

Our use case is to use Kopia from one backup container that mounts in the volumes for the containers it's backing up from, setting the --hostname for the snapshots appropriately. Is there another way to achieve this now? If not, would it be possible to put the --hostname and --username overrides back? (I noticed this has already happened in the past in https://github.com/kopia/kopia/pull/269)

**Comment by jkowalski** [comment]
You generally override the username/hostname when connecting to repository and the values are persisted in the configuration file.

This is needed so that hostname is not randomly floating and overridden when you for example connect to an airport wifi (this actually happened to me once).

**Comment by julio-lopez** [comment]
`--override-hostname`, `--override-username` in the `repo connect <type>` commands.  For example, 

`kopia repo connect filesystem --path=/path/to/repo --override-hostname=foo --override-username=bar`


https://kopia.io/docs/reference/command-line/common/repository-create-filesystem/

**Comment by Novex** [comment]
Ah gotcha, so the workflow should look like

```
cd /mnt/server1
kopia repo connect filesystem --path=/mnt/backups --override-hostname=server1
kopia snapshot create

cd /mnt/server2
kopia repo connect filesystem --path=/mnt/backups --override-hostname=server2
kopia snapshot create
```

Is there a way to denote the file kopia uses for its configuration in case we want to run two snapshot creations simultaneously? Otherwise things might get a little confusing if the kopia command starts with one hostname in the configuration then it changes to another?

**Comment by jkowalski** [comment]
This is curious. I did not realize that's your setup.

Is there a reason why you even need to override the hostname? Without it you'll have per-path backup history which seems equivalent. Am I missing something?

**Comment by Novex** [comment]
It felt like the correct way to denote different hosts, since the hosts themselves don't do their own backups. Also the paths we use aren't as clean as /mnt/server1, rather are EBS volumes by server like /mnt/vol-123abc which are liable to change (and are one more piece of information to have to know for restore).

So instead of just doing a `kopia snapshot restore <snapshotid> . --hostname server1` we'd need to first determine what the volume ID was at the time of backup (presumably with `kopia list <snapshotid>/mnt`) then do a `kopia snapshot restore "<snapshotid>/mnt/$volumeId" .`

So at the moment we mask our volume id's by symlinking to their relevant service (with the idea that a server might have more than one data mount in the future) and our snapshot list looks like this:

```
root@server1:/srv/service1
  2019-07-08 11:00:33 UTC k382a789d49f06542a3b451c2fc6afb9d 266.4 MB drwxr-xr-x files:80 dirs:67 (latest-10)
  2019-07-09 11:00:33 UTC k3ea01ab700d078b8bedf634cca3107aa 268.3 MB drwxr-xr-x files:82 dirs:67 (latest-9)
...

root@server2:/srv/service1
  2020-03-31 13:00:06 UTC ka5e17715547d39b5df984e6fa354145e 128.2 GB drwxrwxr-x files:4811 dirs:340 (monthly-12)
  2020-04-30 15:31:12 UTC kbdd4d5c1b9b1e9200314d25cbcf11aef 128.3 GB drwxrwxr-x files:4823 dirs:379 (monthly-11)
...
```

I guess we could symlink another level down and end up more like a structure that looks like this:

```
root@backup:/server1/srv/service1
  2019-07-08 11:00:33 UTC k382a789d49f06542a3b451c2fc6afb9d 266.4 MB drwxr-xr-x files:80 dirs:67 (latest-10)
  2019-07-09 11:00:33 UTC k3ea01ab700d078b8bedf634cca3107aa 268.3 MB drwxr-xr-x files:82 dirs:67 (latest-9)

root@backup:/server2/srv/service1
  2020-03-31 13:00:06 UTC ka5e17715547d39b5df984e6fa354145e 128.2 GB drwxrwxr-x files:4811 dirs:340 (monthly-12)
  2020-04-30 15:31:12 UTC kbdd4d5c1b9b1e9200314d25cbcf11aef 128.3 GB drwxrwxr-x files:4823 dirs:379 (monthly-11)
```

But then I think we'd have an issue with the retention on the existing hostname'd snapshots not rolling over to the new ones?

Do you mind if I ask why the `--hostname` flag was removed? It seems like the `--hostname-override` on the repo connect could still take precedence system-wide, but it would be easy enough to still have the `--hostname` flag to set it for certain operations?

**Comment by jkowalski** [comment]
I think we can bring this back, after all. Sounds like a valid use case.

**Comment by jkowalski** [comment]
@pavannd1 @julio-lopez what do you think? This seems mildly related to stdin backup feature, where we'll let people override paths. I think it would make sense to have similar/uniform treatment for hostnames and usernames.

How about something like this where the user specifies complete source information:

```
kopia snapshot create <path> --override-source=username@hostname:/manifest/path
kopia snapshot create --from-stdin --override-source=username@hostname:/manifest/path
```

or

```
kopia snapshot create <path> [--override-username=username] [--override-hostname=hostname] [--override-path=/manifest/path]
kopia snapshot create --from-stdin  --override-path=/manifest/path [--override-username=username] [--override-hostname=hostname]
```

(exact flag names TBD).

Note that this would not work with repository server today because it gives users access only to their own snapshots, but I think we can extend access control to support this cleanly, where some `username@hostname` can be granted to read/write snapshots belonging to `other-user@other-hostname`. Needs some UX consideration, though.

**Comment by julio-lopez** [comment]
> Is there a way to denote the file kopia uses for its configuration in case we want to run two snapshot creations simultaneously? Otherwise things might get a little confusing if the kopia command starts with one hostname in the configuration then it changes to another?

Yes, there's a `config-file` flag, which can be specified to `repo connect` and then subsequent commands.

`--config-file="/path/to/repository.config"`

If the flag is not specified, then the default path for the config file is used, which varies from platform to platform.

**Comment by flokli** [comment]
I wanted to convert a bunch of borg repositories to kopia. For this to work, I planned to `borg mount` the repo and essentially run `kopia snapshot create` for each folder, passing start time and other metadata in as-created from borg.

For this to work, I'd also need to use `--override-hostname` `--override-username` (on a per-snapshot level) and also `--override-path` (or the combined `--override-source` parameter).
