### ISSUE TITLE
Cannot restore big files via Mount on Windows

### ISSUE THREAD

**Issue by Hoffenbar** [kopia/kopia#820]
Just doing a few tests. Backed up ~560 GB in 116.000 Files overnight (mostly JPGs). Result: 7 incomplete snapshots. Executing snapshot again (via UI) did the trick, resulting in 1 complete snapshot. Strange, but maybe Ok.
Then mounted a subdir and tried to copy all files out of the mount: This fails with an error x800700DF: Maximum file size exceeded. So, two files left unrestored. Very bad. The sizes of these 2 files are ~50 MB and ~150 MB.
Maybe some WEBDAV Limitation? Didn't tried an restore via commandline without mounting yet, will try this next.
Manual download with UI (without mounting) worked, so I think I can leave out the commandline variant....

**Comment by jkowalski** [comment]
On Windows there's a limitation of the built-in webdav client component that is for some reason (likely legacy) set at 50 MB.

There are a bunch of online articles that describe increasing that such as this one:

https://support.microsoft.com/en-us/topic/you-cannot-download-more-than-50-mb-or-upload-large-files-when-the-upload-takes-longer-than-30-minutes-using-web-client-in-windows-7-8709ae9d-e808-c5a0-95d0-9a7143c50b11

For now the most reliable way of restoring large files on Windows is `kopia restore` command line.

Incomplete snapshots are done every 45 minutes for checkpointing reasons and are completely normal and expected. Next full snapshot should delete them.

**Comment by Hoffenbar** [comment]
Thank for the feedback!

**Comment by jkowalski** [comment]
n/p.
