### ISSUE TITLE
longpath support on windows

### ISSUE THREAD

**Issue by 0x53A** [kopia/kopia#821]
Kopia does not seem to support paths longer than ``MAX_PATH`` (260), for example during a restore:

```
Kopia.exe: error: restore error: copy file: error creating directory: cannot replace
"C:\\Progress\\gitlab-runner\\builds\\Djfa3c8w\\2\\ProgressGroup\\Projekte\\a_CommonBinaries\\ThirdParty\\dotnet-sdk\\dotnet\\sdk\\3.1.401\\DotnetTools\\dotnet-user-secrets\\3.1.7-servicing.20372.13\\tools\\netcoreapp3.1\\any\\Microsoft.Extensions.Configuration.Abstractions.dll"
with tempfile
"C:\\Progress\\gitlab-runner\\builds\\Djfa3c8w\\2\\ProgressGroup\\Projekte\\a_CommonBinaries\\ThirdParty\\dotnet-sdk\\dotnet\\sdk\\3.1.401\\DotnetTools\\dotnet-user-secrets\\3.1.7-servicing.20372.13\\tools\\netcoreapp3.1\\any\\Microsoft.Extensions.Configuration.Abstractions.dll917268726"
: replace
C:\Progress\gitlab-runner\builds\Djfa3c8w\2\ProgressGroup\Projekte\a_CommonBinaries\ThirdParty\dotnet-sdk\dotnet\sdk\3.1.401\DotnetTools\dotnet-user-secrets\3.1.7-servicing.20372.13\tools\netcoreapp3.1\any\Microsoft.Extensions.Configuration.Abstractions.dll917268726
C:\Progress\gitlab-runner\builds\Djfa3c8w\2\ProgressGroup\Projekte\a_CommonBinaries\ThirdParty\dotnet-sdk\dotnet\sdk\3.1.401\DotnetTools\dotnet-user-secrets\3.1.7-servicing.20372.13\tools\netcoreapp3.1\any\Microsoft.Extensions.Configuration.Abstractions.dll
: The system cannot find the path specified., try --help
```
(linebreaks added by me)

the first path is 266, the second one 257.

I'm on Windows 2004, with Kopia ``0.7.3 build: c3ade4b0ea7a1d20497fcfc4f4aec161f73c9505``

**Comment by 0x53A** [comment]
So I thought ``The system cannot find the path specified`` was caused by longpath.

But I also just got this error:

```
Processed 17060 (3.3 GB) of 54403 (10.5 GB) 561.7 Mbit/s (31.2%) remaining 1m43s.
Kopia.exe: error: restore error: copy file: error creating directory: cannot create temp file: open C:\serverbuildroot\17c63e75-2c36-4cf3-b036-50da83245f39\ThirdParty\dotnet-sdk\dotnet\sdk\2.1.301\DotnetTools\dotnet-dev-certs\2.1.1\tools\netcoreapp2.1\any\DotnetToolSettings.xml007841648: The system cannot find the path specified., try --help
```

The path in question this time is only 188 chars long, and the exact same snapshot could be restored, even on the same computer.

I believe there might be multiple causes, long paths seem to fail 100%, others with a low chance.

**Comment by julio-lopez** [comment]
#229 😢

**Comment by 0x53A** [comment]
Manifesting Kopia.exe seems to work:

I added ``Kopia.exe.manifest`` with the following content next to Kopia.exe:

(windows supports both internal manifests, embedded as a resource, and external manifests, which are just loose files next to the exe)

```
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
  <asmv3:application>
    <asmv3:windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
      <ws2:longPathAware>true</ws2:longPathAware>
    </asmv3:windowsSettings>
  </asmv3:application>
</assembly>
```

With this, I could successfully execute the following command:

```
kopia snapshot restore d3c6975e36258018b8a262c51c8bbbb9 C:\temp\long\path\even\longer\so\much\long\wow\abcdefghijklmnopqrstuvwxyz\1234567890\abcdefghijklmnopqrstuvwxyz\1234567890\abcdefghijklmnopqrstuvwxyz\1234567890\abcdefghijklmnopqrstuvwxyz\1234567890\abcdefghijklmnopqrstuvwxyz\1234567890\abcdefghijklmnopqrstuvwxyz\1234567890
```

(well, the snapshot is quite big so i cancelled it at 10%, but previously it would fail immediatly)



So the easiest solution would be to embed a manifest with this entry into kopia.

Unfortunately, this would break versions of windows older than 1607, because instead of ignoring unknown manifest entries, windows fails hard.

I don't know how golang handles this, but the windows api itself does support long paths even without manifest and before 1607 by prefixing the path with ``\\?\``, for example ``\\?\C:\Foldername``. But there are a few caveats with this way, and it's kinda annoying.

----------

Important note if you want to test it yourself:

https://csi-windows.com/blog/all/27-csi-news-general/245-find-out-why-your-external-manifest-is-being-ignored



    The Microsoft documentation on external manifests would lead one to conclude that as long as an EXE does not have an embedded manifest, an external manifest will be read and used instead.

    The truth, however, is that manifests are cached in the Activation Context Cache.

    The secret sauce here is that if you change the EXE’s modification date time stamp, the loader will look again for a manifest. This seems to work reliably every time.

**Comment by julio-lopez** [comment]
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

**Comment by jkowalski** [comment]
#822 should fix it without the need for a manifest. Turns out golang handles LFN in most cases and whenever Kopia was resorting to low-level Windows APIs, we have to handle it explicitly there too.

**Comment by 0x53A** [comment]
that's great, thank you!

at least with the manifest I have a workaround 'till the next release

**Comment by jkowalski** [comment]
#822 is now submitted, closing this one.
