### ISSUE TITLE
unable to open snapshot file

### ISSUE THREAD

**Issue by 0x53A** [kopia/kopia#824]
I created a snapshot on computer A.

Then I tried to restore this snapshot on both computer A and B.

On A I got an error.

```
Restoring to local filesystem (D:\gitlab-runner\builds\ewD4L6AA\0\ProgressGroup\Projekte\a_CommonBinaries) with parallelism=8...
Kopia.exe: error: restore error: error copying: copy file: error creating directory: unable to open snapshot file for D:\gitlab-runner\builds\ewD4L6AA\0\ProgressGroup\Projekte\a_CommonBinaries: object not found, try --help
```

On B it worked normally.

after waiting a bit, and trying it again, it also worked on A.

Could this be related to the index cache again?

Kopia ``0.7.3 build: c3ade4b0ea7a1d20497fcfc4f4aec161f73c9505`` on Windows 2004

**Comment by 0x53A** [comment]
Got the same thing again, this time in a different constellation:

Created a snapshot on A.

On A I can restore the snapshot, on B and C it fails with ``unable to open snapshot file for D:\Progress\gitlab-runner\builds\E6mGMPB8\0\ProgressGroup\Projekte\a_CommonBinaries: object not found``

I am using Azure Storage, which should be strongly consistent.

**Comment by 0x53A** [comment]
(apologies for the spam)

This is probably the same as https://github.com/kopia/kopia/issues/704 and caused by the metadata cache, I'll try if ``kopia cache sync`` helps.

**Comment by jkowalski** [comment]
Yes, that's all related, try using `--no-list-caching`. `cache sync` is for a different purpose and it had the desired effect only because it took some time.

**Comment by jkowalski** [comment]
BTW, it's surprising that in the first case A cannot restore its own snapshot. Can you try to reproduce this and share the logs with me privately on Slack?

**Comment by 0x53A** [comment]
I was looking through my logs and couldn't find the first issue again (snapshot restored on A, couldn't find it on A).
(I'm using Kopia to pass binaries between gitlab job stages and probably mixed up logs from different pipelines)

I can confirm that since I added ``--no-list-caching``, I haven't seen this issue again.

Thank you!
