### ISSUE TITLE
KopiaUI: filenames with ampersands are truncated when downloaded

### ISSUE THREAD

**Issue by davidhealy** [kopia/kopia#838]
When using KopiaUI v0.7.3 to download a file whose filename contains an ampersand, the downloaded filename is truncated and the file extension is stripped from the file. For example "One & Two.jpg" becomes "One_"

I'm running kopia server (Ubuntu 20.04.2 LTS) on my home network, connecting to KopiaUI using a browser on a client PC (Win 10). I can replicate the issue using the v0.7.3 Windows GUI on the client PC.

The issue doesn't occur when copying files whose filename contains an ampersand from a mounted repository using the Kopia CLI on the Ubuntu box - in that case, filenames and file extensions are maintained as expected.

**Comment by jkowalski** [comment]
Yeah, some characters are forbidden as Windows characters.

https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

We should adjust those at mount/restore time. Thanks for the bug report.

**Comment by davidhealy** [comment]
Hi Jarek, many thanks for the quick reply.

Just tested using a webDAV mount via the Windows GUI on the client PC, filenames and file extensions are maintained as expected when files are downloaded.

So to be clear, the behaviour I'm seeing in KopiaUI is triggered if you click a filename containing an ampersand in the "Name" column when browsing through a snapshot.

I'm pretty sure ampersands are safe to use across filesystems - the files in question were created on Windows and have been stored on Linux (ext4 via SMB) with no issues. However they do have a specific meaning when used in URLs, so I'm guessing that may be why KopiaUI is trying to sanitise them.
