### ISSUE TITLE
kopia server and other kopia client can not see policy

### ISSUE THREAD

**Issue by kuyagic** [kopia/kopia#868]
version 0.7.3
* Server Command
`kopia server start --address=0.0.0.0:16000`

* Client Command
`kopia repository connect server --url=http://192.168.11.12:16000`

Then list policy in client side with
```
kopia policy list --log-level=debug
build version v0.7.3, available v
no updated version available
password for C:\Users\Chinni\AppData\Roaming\kopia\repository.config retrieved from OS keyring
GET http://192.168.11.12:16000/api/v1/repo/parameters took 7.9777ms and returned 200 OK
GET http://192.168.11.12:16000/api/v1/manifests?type=policy took 1.0256ms and returned 200 OK
POST http://192.168.11.12:16000/api/v1/flush took 969.4µs and returned 200 OK
in use heap 2752512 (delta 2752512 max 0) stack 294912 (delta 294912 max 0)
```

But on web UI the ajax request is the following image

![image](https://user-images.githubusercontent.com/1469330/110214677-a7ec7e00-7ee0-11eb-9224-90e442edb69a.png)

* Result
` The api url is different`

**Comment by jkowalski** [comment]
That is intentional - `/policies` is UI-specific API, `/manifests` is repository client-specific API and they have different purposes.

Each repository client is supposed to only see their own policies (and in 0.8 also global policy).

I'm not sure if there's any particular issue you'd like to report here. Can you provide repro steps if some behavior is not right?

**Comment by kuyagic** [comment]
I have two machines 
- 1. I installed kopia 0.7.3 in A and create a repo with local path , set a global policy which exclude *.tmp and a compression method
- 2. I installed kopia in B and connect to server A with `kopia repository connect --url=http://A:15151` 
- 3. I run ` kopia policy list` in B see no policy.
My question
If I ran a `snapshot create` command in Machine B, will the data be compressed and *.tmp is excluded ?

Thank you

BTW the server and client situation above seems not working in the master branch build

**Comment by jkowalski** [comment]
@kuyagic can you try with 0.8.0-beta1?

**Comment by kuyagic** [comment]
0.8.0-beta1
I cant connect kopia server

- server command
```
kopia server start --tls-cert-file /usr/local/etc/kopia.crt --tls-key-file /usr/local/etc/kopia.key --a
ddress http://0.0.0.0:51515 --server-password=123456
SERVER ADDRESS: https://[::]:51515
Open the address above in a web browser to use the UI.
```


- client command and output
```
kopia repository connect server --url=kopia://192.168.11.12:51515 --server-cert-fingerprint=ee83c46189b08b00d2133c688d78fe3b0531621d3952d75c1664a5c187415b1f
Enter password to open repository:

failed to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = access denied for Chinni@desktop-home: EOF
kopia: error: error connecting to API server: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = access denied for Chinni@desktop-home: EOF, try --help
```


- screenshot
![image](https://user-images.githubusercontent.com/1469330/111060342-29db3900-84d7-11eb-98af-d8cfbe2d6f52.png)

**Comment by jkowalski** [comment]
I see 2 issues:

the user account you're connecting with is not defined on the server (you're connecting as `Chinni@desktop-home`).
To allow this you need to:

1. `kopia users add chinni@desktop-home`
2. Start kopia server with `--allow-repository-users` (this will be the default later)

A separate issue is why is the username in uppercase (only lowercase are allowed now and this should have been converted to lowercase automatically). For now you can pass `--override-username=chinni` when connecting.

**Comment by kuyagic** [comment]
It works.
Thank you for your help
