### ISSUE TITLE
--max-upload-speed unit and changing this setting

### ISSUE THREAD

**Issue by Gabisonfire** [kopia/kopia#876]
Hi,

First, I've been looking for a backup solution to s3 like Kopia for ages, so thanks a lot for this.

I've created my first s3 repo and used `--max-upload-speed`. There is no indication of what unit it expects to receive so I tried my luck at assuming it was in MBps. I've set it to `20` but was able to reach 50 when upload my first snapshot.

I've dug a bit ion the code and found `./cli/storage_s3.go:			cmd.Flag("max-upload-speed", "Limit the upload speed.").PlaceHolder("BYTES_PER_SEC").IntVar(&s3options.MaxUploadSpeedBytesPerSecond)` but seems like specifying in Bps would be excessive?.

So 2 questions:
- What unit kopia expects for max-upload/download speed?
- Is it possible to change this setting after creation?

Thank you very much.

**Comment by Gabisonfire** [comment]
By reconnecting you mean recreate?
Also, what about max-upload-speed?

**Comment by Gabisonfire** [comment]
Any ideas?

**Comment by jkowalski** [comment]
Thanks again for reporting, this looks like a bug, but looking at the code it's not obvious what may be going on here. Need to investigate further.

FWIW for now you can change the config by manually editing `repository.config` file. The `maxUploadSpeedBytesPerSecond` flag can be set in storage/config section.
