### ISSUE TITLE
After upgrade to 0.8.0-beta1, unable to access S3 repo via Kopia server

### ISSUE THREAD

**Issue by davidhealy** [kopia/kopia#880]
After upgrading to  0.8.0-beta1, Kopia server returns an ACCESS_DENIED error when attempting to connecting to S3 via storage configuration after upgrading to 0.8.0-beta1 - see screenshot:

![zyskY4CYeb](https://user-images.githubusercontent.com/82707/110978140-ec51a100-835a-11eb-9fde-c5748596f599.png)

Also seeing ACCESS_DENIED error in Kopia server when attempting to connecting to S3 using repository token - and noticed that the username and hostname are blank (which isn’t the case when using the repository token in 0.7.3)

![q9hznl6IgE](https://user-images.githubusercontent.com/82707/110978200-fb385380-835a-11eb-9fbc-df3459a43a2b.png)

Reproducible as follows:

1. While Kopia 0.7.3 is running, disconnect from the S3 repo via Kopia server
2. Stop the running Kopia server
3. Replace the 0.73 binary with the 0.8.0-beta1 binary
4. Restart the Kopia server
5. Connect to Kopia server via web browser
6. Attempt to connect to the S3 repo via storage configuration or repository token

Connecting via Kopia CLI works as expected. I am using htpasswd auth for the Kopia server user.

**Comment by jkowalski** [comment]
Can you provide more info on step 5 and 6? How are you starting the server in 0.8.0 (which of the password flags are you using) and how do you authenticate in the browser?

**Comment by davidhealy** [comment]
I'm starting Kopia server via a systemd unit file and authenticating in the browser via basic auth

[Unit]
Description=Kopia Server
After=network-online.target

[Service]
Type=simple
User=kopia
Group=kopia
ExecStart=/home/kopia/bin/kopia server start --htpasswd-file /home/kopia/password.txt --tls-cert-file /etc/letsencrypt/live/home.pixelatic.com/fullchain.pem --tls-key-file /etc/letsencrypt/live/home.pixelatic.com/privkey.pem --address 0.0.0.0:51515

[Install]
WantedBy=multi-user.target

**Comment by jkowalski** [comment]
I think I understand the problem. I presume the username/password you're using to login is in `passwords.txt`, right?

I also presume the username is not `kopia`. In this case you need to explicitly pass `--server-username` to specify which of the users has access to the UI (only one such user is currently supported, we may be able to tweak this in future versions in case there are multiple administrators)

The `--htpasswd-file` mechanism was never really meant to authenticate UI users (it was primarily for kopia repository clients), it just happened to be work this way. As a side effect it also allowed ANY user in the htpasswd file access to the entire UI which gave access to data from all users.

This was changed in #871 to fix #693.

Let me know if adding this flag resolves your issue, this is actually an unintended breaking change, which we'll need to include in the release notes.

**Comment by davidhealy** [comment]
The username/password for logging into Kopia server is indeed in password.txt. For convenience, I named the htpasswd user the same as the user running the service - they are both "kopia"

If I pass `--server-username kopia ` when starting the service, I can access the Kopia server interface but I still have the same issue of not being able to connect to the S3 repository.

The username and hostname are blank when I try to connect using a repository token - is that a clue? In 0.7.3 I see the "kopia" username and the Kopia server's hostname prepopulated in these fields when I toggle them open. With 0.8.0-beta1, it seems like Kopia server is not aware of these values.

I am thinking that maybe my configuration of the kopia binary might be to blame here.

I am backing up files belonging to other users, to which only root has access - in order to do so, I'm setting the uid bit on the kopia binary located within the kopia user's bin directory as follows:

```
# Set permissions on kopia binary
chmod 0750 /home/kopia/bin/kopia
# Change ownership on kopia binary
chown root:kopia /home/kopia/bin/kopia
# Set uid bit so that kopia user runs binary as root
chmod u+s /home/kopia/bin/kopia
```

I needed to set up this way as the Kopia server UI threw errors if I specified `root` for user and group within the systemd unit file.

**Comment by jkowalski** [comment]
I cannot reproduce this, here's what I did - can you see if this sequence of steps works for you:

1. htpasswd -c htpasswd.txt kopia
New password: 
Re-type new password: 
Adding password for user kopia

2. kopia server start --htpasswd-file ~/htpasswd.txt --address 0.0.0.0:51515 --insecure

3. In a browser:

a) go to <server>:51515
login as 'kopia/foo'

b) connect using previously working repository token for S3 (Wasabi) - works fine

(i can see username and hostname filled out in 'Advanced Options')

c) Disconnect

d) Connect to S3-based repository by providing endpoint/bucket/etc. - works fine

(i can see username and hostname filled out in 'Advanced Options')

e) Disconnect

4. set UID bit:

$ sudo chmod u+s /usr/bin/kopia
$ ls -al `which kopia`
-rwsr-xr-x 1 root root 28094464 Mar 11 21:14 /usr/bin/kopia

5. kopia server start --htpasswd-file ~/htpasswd.txt --address 0.0.0.0:51515 --insecure

6. In a browser:

a) go to <server>:51515
login as 'kopia/foo'

b) connect using previously working repository token for S3 (Wasabi) - works fine

(i can see username and hostname filled out in 'Advanced Options')

c) Disconnect

d) Connect to S3-based repository by providing endpoint/bucket/etc. - works fine

(i can see username and hostname filled out in 'Advanced Options')

e) Disconnect

**Comment by jkowalski** [comment]
(btw there may be clues if you look into Requests section in Chrome Developer Tools)

**Comment by davidhealy** [comment]
Jarek, thanks for the troubleshooting tips. After working through the steps suggested, everything now works as expected using htpasswd auth - I can connect via endpoint/bucket and repository token (with user and hostname correctly pre-filled in "Advanced Options").

I am quite new to Kopia (having come from Restic) and I don't really understand what was causing my issue yesterday. The only differences today are:

The `--htpasswd-file` path is different - now using `--htpasswd-file /home/kopia/htpasswd.txt` in place of the previous password.txt file.

The syntax for the user creation is slightly different. For troubleshooting I created the kopia user following your syntax `htpasswd -c htpasswd.txt kopia`. Previously I had created the user using the syntax `htpasswd -c password.txt kopia@hostname` shown here https://kopia.io/docs/repository-server/#configuring-allowed-users---kopia-v07

I ran `kopia server start` a couple of times manually as the `kopia` Linux user during troubleshooting. Yesterday I was reloading and restarting the systemd service unit.

I am still seeing the issue I noted in the Discourse thread whereby switching auth from `htpasswd` to `kopia user` results in my being unable to login to the Kopia server interface. Steps to replicate:

1. Connect to the repository via the kopia CLI
2. Create the user via the `kopia user add kopia@hostname`
3. Replace the `--htpasswd-file` flag with `--allow-repository-users` in the kopia server start
4. Restart Kopia server
5. Attempt to access the Kopia server interface in the browser. It's not possible to login as user "kopia" using the password defined in step 2, I just get repeated login prompts which I can't get past.

In case it's of relevance, I am accessing Kopia server by fully qualified domain name (home.mydomain.com) rather than machine hostname. This is so I can automate Let's Encrypt certificate renewal via certbot-dns-cloudflare, and have the certificate be trusted by all clients on the network.

**Comment by jkowalski** [comment]
That all makes sense now:

* `kopia` is a UI account - the only one that can login through the UI
* `kopia@hostname` is a repository server account (which you'd use in `kopia repo connect server ...` for a client running as. user 'kopia' on `hostname`).

If you want to access the UI with a user defined in `htpasswd.txt` it must be named `kopia` (or you must override it with`--server-user`).

If you don't want htpasswd file it's slightly more involved. Since `--allow-repository-users` we now enforces that usernames have `username@hostname` format, you can't just define a user named `kopia`. Instead define a user `myuiuser@somehost` and you must pass `--server-username myuiuser@somehost` to allow the UI access.

**Comment by vgivanovic** [comment]
I couldn't use the UI even though I could connect to a Backblaze B2 repository and take snapshots. Eventually, over the course of 3 days of experimenting, I found the following to work on my Arch Linux system:
```
$ kopia repository connect b2 --bucket<bucketname> --key-id=<B2 master application key ID> --key=<B2 master application key> --password=<B2 password>
$ htpasswd -c ~/.htpasswd <name@host>
<password>
$ kopia server user add --user-password=<password> <name@host>             # don't know if this is necessary
$ kopia repository set-client --username=<name@host>                       # don't know if this is necessary 
$ kopia server start --server-username <name@host> --address localhost:51515 --insecure
$ min http://localhost:51515                                               # `min' is a minimal browser 
```
I think I've got everything...

— Vladimir

**Comment by maclm** [comment]
I'm a bit confused with https://github.com/kopia/kopia/issues/880#issuecomment-798421751
If `kopia` it the default *admin* user for kopia server UI, what is the "default" password for it?
I like the idea of having an *admin* user that is not my user account, but I can't figure how to use it.

**Comment by jkowalski** [comment]
There are multiple options here:

Option 1. `kopia` won't ask for UI username/password and will have access to the current user's repository connection.

```
$ kopia server start --without-password`
```

Option 2. Additional basic authentication for UI user:

```
$ kopia server start --server-username=X --server-password=Y
```

Option 3. Generate and print a random password on startup, that's only good for this invocation of `kopia`. The username is `kopia` - good for ad-hoc messing with UI, while you normally 

```
$ kopia server start --random-password
```

Option 4: Use password from htpasswd file:

```
$ kopia server start --htpasswd-file filename.txt --server-username=<one-of-usernames-in-htpasswd-file>
```

Note that unless you set up TLS, you also need to pass `--insecure`.

**Comment by seaniedan** [comment]
Hmm, this is very confusing! I followed [these instructions](https://kopia.io/docs/repository-server/) to start my server:

kopia server start \
  --tls-generate-cert \
  --tls-cert-file ~/my.cert \
  --tls-key-file ~/my.key \
  --address 0.0.0.0:51515 \
  --server-control-username control \
  --server-control-password PASSWORD_HERE
  
  ...but when I go to the web address 0.0.0.0:51515, I can't log in with my _user on the local machine_ (which I tried first, no useful message yet), an _added kopia user_ (which allowed me to log in but brought me here), _kopia_ (as suggested above... but what is the password for the kopia user? I couldn't log in), or _control_ (which is the suggested user in the startup line I entered, with the plaintext password given in the line above also, and logged me in but with the same error message to come here!)
  
I'd love some more instructions on what to do, and what can be achieved from having the UI available - I'm not 100% sure what having the UI will allow me to do. Another issue for me is that once I've logged in with the credentials that show the error message to bring me here, there's no way to log out, so I can try with the correct credentials.

**Comment by maclm** [comment]
Hi @seaniedan 

I think the web address you mention, `0.0.0.0:51515`, is your localhost (client).
Have you tried visiting `server-ip:51515`?

When configuring the server, we have to input `--address 0.0.0.0:51515` but as far as I know, when accessing the server from another machine, we have to visit the server IP.

Hope that helps.

**Comment by seaniedan** [comment]
Thank you Maclm, I used my hostmachine name to connect, `myserver.local:51515` , but still have the issues above.

**Comment by silversword411** [comment]
So has anyone figured out how to login to the kopia repository servers web ui? Doesn't look like anyone has figured it out yet and posted an answer. :(

**Comment by nixcamic** [comment]
You have to either use a .htaccess file or pass the login/password in on
the command line. You also either need a TLS certificate (kopia can
generate one for you) or the -insecure flag. If you use the insecure flag
you will have to specify an IP to bond to.

**Comment by alextricity** [comment]
The install process was strait forward enough, for a somewhat skilled linux user, though this web interface issue is quite a headache. I do want it to be very secure as this will be a publicly facing server so, some constructive criticism (and this is a COOL project, I love it [Thanks!]); we really need to fine tune this.

**Comment by lacymorrow** [comment]
#### For folks coming for help setting up the Unraid Docker container:

Use username `kopia` and generate content for an htpasswd file: https://hostingcanada.org/htpasswd-generator/

Create the file at `/mnt/user/appdata/kopia/config/htpasswd` and paste the data.

Switch to the advanced view
<img width="301" alt="image" src="https://github.com/kopia/kopia/assets/1311301/ea477f27-a2f6-4882-96bb-0621bf0df2eb">

Add your username to the `Post Arguments`: 
<img width="843" alt="image" src="https://github.com/kopia/kopia/assets/1311301/1c231627-7203-4061-8611-4af5adb1c669">

Save

**Comment by mdrozdo** [comment]
> Hmm, this is very confusing! I followed [these instructions](https://kopia.io/docs/repository-server/) to start my server:
> 
> kopia server start --tls-generate-cert --tls-cert-file ~/my.cert --tls-key-file ~/my.key --address 0.0.0.0:51515 --server-control-username control --server-control-password PASSWORD_HERE
> 
> ...but when I go to the web address 0.0.0.0:51515, I can't log in with my _user on the local machine_ (which I tried first, no useful message yet), an _added kopia user_ (which allowed me to log in but brought me here), _kopia_ (as suggested above... but what is the password for the kopia user? I couldn't log in), or _control_ (which is the suggested user in the startup line I entered, with the plaintext password given in the line above also, and logged me in but with the same error message to come here!)
> 
> I'd love some more instructions on what to do, and what can be achieved from having the UI available - I'm not 100% sure what having the UI will allow me to do. Another issue for me is that once I've logged in with the credentials that show the error message to bring me here, there's no way to log out, so I can try with the correct credentials.

For anyone coming here after following the same guide, the solution is to call the control user "kopia", i.e. run the server with the command:
```
kopia server start --tls-generate-cert --tls-cert-file ~/my.cert --tls-key-file ~/my.key \
--address 0.0.0.0:51515 \ 
--server-control-username kopia \ 
--server-control-password PASSWORD_HERE
```

And then log in to the web UI with user: kopia and password: PASSWORD_HERE

**Comment by RipClaw2971** [comment]
> For anyone coming here after following the same guide, the solution is to call the control user "kopia", i.e. run the server with the command:
> 
> ```
> kopia server start --tls-generate-cert --tls-cert-file ~/my.cert --tls-key-file ~/my.key \
> --address 0.0.0.0:51515 \ 
> --server-control-username kopia \ 
> --server-control-password PASSWORD_HERE
> ```
> 
> And then log in to the web UI with user: kopia and password: PASSWORD_HERE

That is not solution but a bad idea. The password shows up in the process table. Anyone that has access to the same server sees the user and the password.

This is the command line:

`kopia server start --address=http://0.0.0.0:51515 --tls-cert-file=/root/kopia.crt --tls-key-file=/root/kopia.key  --htpasswd-file htpasswd.txt  --server-control-username kopia --server-control-password test123`

This is what it looks like when for example a unprivileged user lists the processes with "ps aux | grep kopia":

`root     1489792  0.5  1.4 1408088 114144 pts/0  Sl+  20:07   0:00 kopia server start --address=http://0.0.0.0:51515 --tls-cert-file=/root/kopia.crt --tls-key-file=/root/kopia.key --htpasswd-file htpasswd.txt --server-control-username kopia --server-control-password test123`

**Comment by bitinerant** [comment]
> If you want to access the UI with a user defined in `htpasswd.txt` it must be named `kopia` (or you must override it with`--server-user=some-other-user`, including possibly `--server-user=kopia@hostname` which will also work).

This tripped me up. It's `--server-username`, not `--server-user`.
