### ISSUE TITLE
Unable to use server since 0.8.0 beta1

### ISSUE THREAD

**Issue by CrendKing** [kopia/kopia#885]
Since a local server is the only way to do scheduled snapshots in background, I usually start a server at OS boot. Occasionally I'd go localhost:51515 to see if everything is working. My server start command line is

` kopia --config-file="<my.config>" server start --insecure`

I use `--insecure` because this server is not meant for publicly sharing or access control but merely a local UI (not sure if https://github.com/kopia/kopia/issues/800 would solve this use case). Starting one of the nightly versions a few days ago, this is changed because "Snapshots", "Policies" and "Tasks" tab just display "Request failed with status code 403". "Repository" tab works as before. This looks as a different issue than https://github.com/kopia/kopia/issues/880.

I also tried the new `users` command to add a new user `test@myhost`. Then start server with `--allow-repository-users`, enter credential. All the 3 tabs still show the same error.

Fortunately, it seems the automatic snapshotting still works without the authentication error. Also, KopiaUI has no such problem, so could this be related to `--insecure`?

**Comment by jkowalski** [comment]
Instead of `--allow-repository-users` please do `--server-username=test@myhost` and login as `test@myhost`.

Also if you upgrade past #884 you should get better error message, because the user you're logging in is not allowed to access UI.

**Comment by jkowalski** [comment]
I'll release beta2 this weekend so that everybody gets it since in beta1 Kopia was not properly rejecting UI access by non-UI user.

**Comment by CrendKing** [comment]
Thanks. It works.

Does #800 has scope to change the way authentication works (so that people don't need to add users to use the UI) or is it limited to the concurrency stuff?

**Comment by jkowalski** [comment]
#800 might be able to do this all (to streamline the UX as much as possible), but we have not started looking into it. Any help is appreciated.

**Comment by CrendKing** [comment]
Just for information, alternatively I could just set a static password with `--server-password=<password>` and use my password manager to auto fill the basic auth form without creating user. The username is `kopia`.

> Any help is appreciated.

If I want to help, where to start?

**Comment by jkowalski** [comment]
I could use help designing and implementing the streamlined user experience for all types of scenarios:

* internal server for Kopia UI (this one should probably be hidden command since it's the only one that auto-generates single-use password)
* Kopia daemon for a single user connecting using a browser (where should the password go? flags seem kind of bad) HTTP vs HTTPS, supporting reverse proxies, running as windows service, systemd scripts, TLS provisioning, etc.
* Multi-user Repository server with htpasswd-based user accounts (perhaps remove that?)
* Multi-user Repository server with repository-based user accounts (perhaps make the only option after migrating users)
* Multi-user Repository server with UI (this actually works, perhaps it should not) 
* CLI-only usage for repository client 
* CLI-only usage for directly-connected repository

Overall I'm thinking of killing off `kopia server` which supports all these case and replacing with individual commands with limited set of flags so that are more obvious.

We need some robust conceptual documentation regarding which server scenario is for what types of users.

I'll be happy to chat on https://slack.kopia.io

**Comment by CrendKing** [comment]
> * where should the password go

Can you explain more about this use case? Suppose we have a Linux with multiple non-root users. Each wants to start their own kopia server to backup their own files. I suppose the password is to protect user A from accessing user B's server on the same Linux, correct? In that case, can we just put the password in the config file, which is stored in each user's profile directory?

> * Multi-user Repository

Is this like the admin of that Linux starts the server, configuring it so that user A and B can access their own backups and files but not other's? What is the granularity of ACL in Kopia? Per snapshot? Per blob? Content? I don't really know the difference of these concepts.

My instinct is that the design can be simpler if we can make single-user a special case of multi-user system.

> * CLI-only usage

Are we talking about ACL here too?

------

Personally, I don't like that Kopia daemon is integrated into the UI server. I think a daemon that handling scheduled backups should be an separate non-ACL'd component. Whoever can connect the repository should able to start it. ACL'd server and UI should be built on top of the CLI and daemon, and completely optional (everything the server and UI can be should be able to be done with CLI).

There could be discussion whether UI should be on top of server or parallel to server (e.g. UI could be a wrapper of CLI commands, non-ACL'd). I think once CLI, daemon, UI and server are completely separated components, the design can be more clearly defined.

**Comment by jkowalski** [comment]
That's exactly what I was looking for. Figuring out answers to those questions (and more). Those are all great long-term improvements and I believe the time to do all this is now to set Kopia on a long-term path towards success.

How about we start a public Google Doc that will be sort of "Kopia Server User Guide", put all those use cases and ideas there, hash out the details, share with key steakholders (Julio, Niraj) and come up with implementation and migration plan.

We can perhaps meet on Hangouts/Zoom if needed to have higher-bandwidth discussions early on.

**Comment by CrendKing** [comment]
I agree with that Kopia can use some long-term plan for the server related development. For me it is the biggest confusing part when using Kopia, comparing to other backup solutions.

I don't know what's your vision of Kopia's future, so I wasn't really sure if any of my ideas above would align to yours. You clearly have some unique vision, because Kopia currently is very different to for example Areca or Deduplicati. One example is that most open source backups don't really care about "user". They are for personal use, period. There is no "server" concept. On the other hand, many enterprise solutions (I have some experience with Crashplan in my company) is full server-client model. Because different paths take very different solutions, I think the highest priority related to the server is to lay out the direction of Kopia design: A personal backup solution, A distributed backup solution, A distributed solution with personal use case supported, or some unique mix of both, etc.

Once that is clear, we can decide the role of server in the system. Should it be a required component, or optional component for convenience. Where should the server be: low-level like SQL server so that all CLI actually talks to the server for information and actions, or high level like currently where server shares some code with CLI in the background. Then how does the server interact with other components such as the daemon. Should they be separate or caller-callee relationship? How does Kopia handle ACL?

I think if you decide to go the full distributed system route, Kopia will be changed a lot. You might lose some users, but gain other users. One bonus might be that some enterprises interest in Kopia and start sponsoring, if Kopia can provide features important to them.

BTW, I don't know much about Go, so I can't help much on the implementation part.

And feel free to close this ticket. I think the discussion should be a different ticket.

**Comment by jkowalski** [comment]
The way I see it, a single Kopia deployment is meant to be a tool to manage backups of a relatively small set (1-100) computers in a LAN, small office, dorm,  etc to a shared storage where the data is deduplicated across users and machines.

I'm hoping the user experience of a single user backing up to a personally-owned repository does not need to be fundamentally different from N users backing up to a shared repository managed by local administrator and should be equally accessible via both CLI and UI.

Anyway, I'm going to close this issue and let's further discuss in a doc. Please request access so we can collaborate, I'm going to add few more folks and will share more broadly later:

https://docs.google.com/document/d/1f_WLQjOCuX301TVrSgfOZJ2_zlL2r5QhhZ5w_kZkBaw/edit?usp=sharing
