### ISSUE TITLE
Before and After actions

### ISSUE THREAD

**Issue by Hoffenbar** [kopia/kopia#908]
The new actions are great! Unfortunally, in conjunction with snapshots, I've not found a tool yet which creates and mounts a VSS snaphot and then giving control back. E.g., shadowtask and shadowspan are ceating and mounting a snapshot, then running a external program, and then deleting the snapshot (mount). This way it does not work well with kopia actions. I have to snapshot the whole disk, then start e.g. kopia-ui, but for this I don't need actions....

**Comment by jkowalski** [comment]
This VSS is horribly under-documented and it seems that CLI tooling required is not even present on Windows 10 (server does have it, though). I would really be prefer to have 1st-class support for this inside Kopia, but I'm not an expert in this area so I'm not even going to attempt it. Contributions are welcome & encouraged.

Assuming you want to go down the road of something like `shadowspawn`, here's a really bad idea to get this to work in the meantime, using only materials in the room:

We need three scripts:

## The `waiter` script

 * write own process identifier (`pid`) to some well-known file, say `c:\temp\waiter-%KOPIA_SNAPSHOT_ID%.txt`
 * sleep forever waiting to be externally killed

## The `before` script:

  * find (how?) an unused drive letter to mount to (say `Q:`)
  * start `shadowspawn %KOPIA_SOURCE_PATH% %DRIVE_LETTER%: waiter` in the background but don't wait for it
  * wait for `c:\temp\waiter-%KOPIA_SNAPSHOT_ID%.txt` to become available (say no more than 60 seconds). This is an indication that `waiter` script is running and %DRIVE_LETTER% has been mounted
  * echo "KOPIA_SNAPSHOT_PATH=%DRIVE_LETTER%"

## The `after` script:

  * read `c:\temp\waiter-%KOPIA_SNAPSHOT_ID%.txt` and kill the process whose ID is in the file.
  * This will cause `shadowspawn` to unmount the %DRIVE_LETTER% and clean up the snapshot
  * delete `c:\temp\waiter-%KOPIA_SNAPSHOT_ID%.txt`

**Comment by jkowalski** [comment]
Yeah, that was horrible. I did some research and it may be possible to write a proper script, though (cmd or powershell should be possible)

. Here's what I found so far:

Step 1:

```
wmic shadowcopy call create Volume=C:\
```

this prints a line containing something like:


```
        ShadowID = "{EF415FB9-F23A-477D-9A68-C8BDD0BB4221}";
```


Step 2:

```
vssadmin list shadows /Shadow={EF415FB9-F23A-477D-9A68-C8BDD0BB4221}
```

Prints a bunch of lines, including something like:

```
         Shadow Copy Volume: \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6
```

Step 3: Now create a directory symlink to it somewhere... Note the trailing backslash which is not in the line above. Ii is critical, without it, it silently does not work (whoever thought this was a good idea...)

```
mklink /d c:\shadow1 \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6\
```

To unmount it:

```
vssadmin delete shadows /quiet /shadow={ef415fb9-f23a-477d-9a68-c8bdd0bb4221}
rmdir c:\shadow1
```

So I think this could totally be scripted after all.

@julio-lopez thoughts about having Kopia native understanding of VSS and those commands (basically special pre-cooked action that does VSS?)  The user would specify VSS mode (`mandatory`, `best_effort`, `disabled`) and we'd magically run those commands before/after snapshot on Windows only?

**Comment by Hoffenbar** [comment]
Many thanks so far! I'll think both solutions are possible. Unfortunally, one cannot be safe, that this commands are always available on every windows and under this names with the always same command line args. Sometimes MS drops commands, renames commands. alter the behaviour of switches etc. etc. The only safe (or at least a safer) way I fear would be directly using the API (or perhaps powershell cmdlets, leading to other difficutlies) , but that would take the horror to a new high score level. MS often isn't able to abstract complex things through simple and usable (and stable) interfaces. I looked for VSS API docs last evening and gave up after understanding the first few MS pages.....

**Comment by jkowalski** [comment]
The good news is here that the number of Windows versions to worry about is somewhat countable so whatever solution emerges here could relatively easily be tested against all supported versions. I was under the impression that things like `WMI` and `wmic` tool are omni-present and vssadmin goes back to Vista so the risk of it disappearing is low (I'm mostly worried about relying on string parsing and subtle regionalization-specific differences, but those again could be tested and improved upon over time).

I really hope somebody can create a github repository that maintains kopia-compatible actions for VSS :)

**Comment by Hoffenbar** [comment]
Parts of the operation should be scriptable via COM, it seems....
(https://kimconnect.com/powershell-create-and-delete-vss-snapshots/)

**Comment by andrewpthompson** [comment]
There was a good Powershell script for Restic (another open-source backup system) by kmwoley that took a VSS snapshot before running a backup (this was before restic had its own native implementation of VSS). You should be able to adapt parts of it.
https://github.com/kmwoley/restic-windows-backup/blob/1eaef5f0c86824303cd57643d004e86582a608b5/backup.ps1
Note this link is to the repo's history because the VSS snapshot code was removed from this script on 2021-02-25 after restic implemented its own VSS support.

**Comment by CrendKing** [comment]
I wrote my before and after action PoweShell scripts (compatible with the current PoweShell 7.1) to automate [Jarek's method](https://github.com/kopia/kopia/issues/908#issuecomment-805390973). If you guys think it's helpful, we could put it in the [doc](https://kopia.io/docs/advanced/actions/#examples) for those need VSS but oblivious of this issue.

Before:
``` PowerShell
$sourceDrive = Split-Path -Qualifier $env:KOPIA_SOURCE_PATH
$sourcePath = Split-Path -NoQualifier $env:KOPIA_SOURCE_PATH
# use Kopia snapshot ID as mount point name for extra caution for duplication
$mountPoint = "${PSScriptRoot}\$($env:KOPIA_SNAPSHOT_ID)"

$shadowCopyOutput = ((WMIC SHADOWCOPY CALL Create Volume="${sourceDrive}\") | Select-String 'ShadowID = "(?<id>\S+)"').Matches
if (-not $shadowCopyOutput) {
    # fail the Kopia snapshot early if shadow copy was not created
    # question: is there a way to print error messages to the log file?
    exit 1
}
$currentShadowId = $shadowCopyOutput.Groups['id'].Value

$allShadows = (vssadmin List Shadows | Out-String | Select-String 'Shadow Copy ID: (?<id>\S+)[\s\S]*?Shadow Copy Volume: (?<volume>\S+)' -AllMatches).Matches
foreach ($m in $allShadows) {
    if ($m.Groups['id'].Value -eq $currentShadowId) {
        cmd /c mklink /d $mountPoint "$($m.Groups['volume'].Value)\"
        Write-Output "${mountPoint}${sourcePath}"
        exit 0
    }
}

exit 1
```

After:
``` PowerShell
$mountPoint = Get-Item "${PSScriptRoot}\$($env:KOPIA_SNAPSHOT_ID)"
$mountedVolume = $mountPoint.Target
Remove-Item $mountPoint

$allShadows = (vssadmin List Shadows | Out-String | Select-String 'Shadow Copy ID: (?<id>\S+)[\s\S]*?Shadow Copy Volume: (?<volume>\S+)' -AllMatches).Matches
foreach ($m in $allShadows) {
    if ("$($m.Groups['volume'].Value)\" -eq "\\?\${mountedVolume}") {
        vssadmin Delete Shadows /Shadow="$($m.Groups['id'].Value)" /Quiet
        exit 0
    }
}

exit 1
```

To use:
```
kopia policy set <folder> --before-folder-action 'pwsh <path_to_script>\before.ps1'
kopia policy set <folder> --after-folder-action 'pwsh <path_to_script>\after.ps1'
```

**Comment by cristihcd** [comment]
For reference, here is how duplicacy implements VSS on Windows: https://github.com/gilbertchen/duplicacy/blob/master/src/duplicacy_shadowcopy_windows.go

**Comment by CrendKing** [comment]
Wow, looks like PowerShell has *Power* in its name for a good reason 😉

**Comment by CrendKing** [comment]
Created PR: https://github.com/kopia/kopia/pull/1319

**Comment by CrendKing** [comment]
Is it OK to close this now?

**Comment by Hoffenbar** [comment]
Yes, it's ok. Thank you all.
