### ISSUE TITLE
handling of directory paths

### ISSUE THREAD

**Issue by deathtrip** [kopia/kopia#918]
When you create a repo in your current working directory, without specifying an absolute path. 
eg. `kopia repo create filesystem --path=kopia-repo`
Then when connected to the repo and you change your working directory, trying to do operations on it will give a error stating the directory doesn't exist. 
So kopia should use absolute paths to reference repositories by default (also in the repo config file).

Another thing i found on linux is the ~ alias for the home directory is not seen correctly.
`kopia repo create filesystem --path=~/kopia-repo` will create a `~` directory with `kopia-repo` as a subdirectory in your current location, instead of doing it under `/home/username/kopia-repo`

**Comment by jkowalski** [comment]
thanks, i'll try to get a fix in for this before 0.8.0

**Comment by jkowalski** [comment]
the `~` is normally expanded by the shell, but it can't do it in the middle of strings, if you drop `=` it will work:

```
kopia repo create filesystem --path ~/kopia-repo
```

but it trips many people and is relatively easy to handle ourselves, so we should do it.
