### ISSUE TITLE
Snapshotting without recursion

### ISSUE THREAD

**Issue by Hoffenbar** [kopia/kopia#920]
Suppose you have a directory with many config files and some subdirectories (speaking of the users profile root in windows...). For some important subdirectories, I already have separat snapshots.
But what if I only want to backup (snapshot) the files within some root, non-recursively (because I don't want to include what I already backed up elsewhere)? I don't want to exclude subdirs manually via policy. What I need is a flag like `--nonrecursive`....

**Comment by Hoffenbar** [comment]
Can't figure out how to configure the ignore rules to only backup everything exluding all subdirs.
`*/` won't work,

**Comment by julio-lopez** [comment]
@Hoffenbar Would it make sense to have a "How To" section in the documentation with tips and recipes? Contributions are welcome, feel free to open a docs pull request.

**Comment by Hoffenbar** [comment]
Absolutely!Especially the retention settings are very confusing! -- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 03.05.21, 07:37 schrieb Julio Lopez ***@***.***>:

   
  @Hoffenbar Would it make sense to have a "How To" section in the documentation with tips and recipes? Contributions are welcome, feel free to open a docs pull request.
