### ISSUE TITLE
stderr instead of stdout for version and --help

### ISSUE THREAD

**Issue by oderwat** [kopia/kopia#940]
I wonder about the decision that Kopia outputs its help and the result of `--version` on stderr instead of stdout. I stumbled over this while creating some helper scripts. I know how to work around but can't remember any other tool to output those to stderr. Isn't stderr supposed to be used for error messages "only"?

**Comment by jkowalski** [comment]
Good catch. Turns out the CLI parsing tool we use supports this option, I'll make a change.
