### ISSUE TITLE
Unable to create repositories with the command line

### ISSUE THREAD

**Issue by Neurrone** [kopia/kopia#959]
This is the very first command in the getting started document.

```sh
> kopia repository create filesystem --path d:/temp/kopia
Enter password to create new repository: kopia: error: getting password: password entry: password prompt error: The handle is invalid., try --help
```

I don't get a chance at all to enter the password before it prints that error message.

Environment: windows 10 2004 with Kopia 0.8.

I initially installed the gui and manually added the server folder in the installation location of the gui containing kopia.exe to path and this didn't work.

In case it was a problem with having the gui installed, I uninstalled it and it still doesn't work.

**Comment by jkowalski** [comment]
I can repro this too. Upgrading password prompt library likely caused a regression on Windows. I'll make a quick hotfix once I understand the problem.

**Comment by jkowalski** [comment]
I'm pushing 0.8.1 with the fix right now...

**Comment by Neurrone** [comment]
Thanks for fixing this so quickly 👍 

Any chance that this could have been caught by an automated test in the future? This made it completely unuseable on Windows
