### ISSUE TITLE
Ignore rules puzzle me

### ISSUE THREAD

**Issue by oderwat** [kopia/kopia#961]
This is what's in the filesystem:

```
/var/www/users/user1/logs/some.log
/var/www/users/user1/www/index.html
/var/www/users/user2/logs/another.log
/var/www/users/user2/www/index.html
```

I create a snapshot of `/var/www`

When I add an ignore rule like this:

```
/users/*/logs/
```

Kopia will not exclude anything.

When I add an ignore rule like this:

```
/users/user1/logs/
```

Kopia will exclude the logs of user1.

When I add an ignore rule like this:

```
/users/**/logs/
```

Kopia will exclude the logs of all users.

Why won't it explode all user logs with the single `*` rule?

P.S.: Kopia 0.8.0

**Comment by julio-lopez** [comment]
The ignore rules mostly follow the [gitignore format](https://git-scm.com/docs/gitignore#_pattern_format)

More documentation needed. Contributions welcomed.

Ref: #773 #571 #492

**Comment by xbb** [comment]
The wildcard match actually fails, I've noticed it too when trying to ignore a pattern like `foo-*/bar`

Test path: `/users/user1/logs`

`/users/user1/logs` matches
`/users/**/logs` matches
`/users/user?/logs` matches
`/users/user*/logs` fails
`/users/*/logs` fails

Code for the test cases (file `wcmatch_test.go`):

```
{"/users/user1/logs", "/users/user1/logs", true, true},
{"/users/**/logs", "/users/user1/logs", true, true},
{"/users/user?/logs", "/users/user1/logs", true, true},
{"/users/user*/logs", "/users/user1/logs", true, true},
{"/users/*/logs", "/users/user1/logs", true, true},
```

**Comment by alphaleonis** [comment]
This is indeed a (kind of embarrassing) bug in the pattern matching. Well spotted, and thanks to the test cases @xbb  provided I could fairly quickly identify it.  I would suggest removing the `documentation` tag from this issue since it actually is a *bug*.
