### ISSUE TITLE
Can't connect existing repository/snapshot and a few other nitpicks

### ISSUE THREAD

**Issue by ThoriumTextile** [kopia/kopia#963]
Hi, i just wanted to say that this project is really nice as is and has a lot of potential, given how there aren't many (as powerful and decked out) options for backing up on Linux, and maybe even on other OSes.

Though as the title says, i can't seem to be able to connect an existing repo:
```
~ $: kopia repository connect filesystem --path /mnt/usb-Samsung_M3_Portable_DFCB7DF602000068-0:0-part3/kopia
Enter password to open repository:

failed to open repository: unable to create shared content manager: error loading indexes: decrypt error: cipher: message authentication failed
kopia: error: error connecting to repository: unable to create shared content manager: error loading indexes: decrypt error: cipher: message authentication failed, try --help
```
(the

The GUI has no option to add an existing one, only to create a new one.
Also you can't:
- Delete snapshots
- Change snapshot destination
- The encryption seems to be a must. This is a really good habit for new users, but it can be inconvenient for users like me.
- Export the configuration through the GUI

Some minor and negligible nitpicks are:
- Can't change UI theme.
- The Archlinux AUR package doesn't include the GUI.
- Overall the GUI isn't bad at all, but can be a bit confusing for new users (i.e. i found pretty confusing which and what was the target drive and/or directory // could follow the style of a OS installation)

Again, i really hope this project gets more attention, because it really deserves it.
Regards.

**Comment by jkowalski** [comment]
Thanks for the feedback. 

I'm guessing one of your index files in the repository has gotten corrupt (I would look for zero-length files starting with `n` and delete those then try again). Please ping me on `slack.kopia.io` if that does not resolve the issue - there is a way to actually recover indexes even if they get completely damaged.

As for the UI - yeah, I'm really looking for help here since the UI paradigm needs a major rework to be user friendly. For 0.9 i'm thinking of having a single tree view of the filesystem to replace both Snapshots and Policies tab.

The UI actually allows reconnecting to the repository - it will check if a repository exists in a given storage and allow connecting to it, otherwise will create it.

**Comment by ThoriumTextile** [comment]
@jkowalski I have no idea of what voodoo wizardry you pulled off, but as soon as you replied to me it now sees the repo again 🤣.
And anyway i forgot to mention it was a test repo and nothing important was there. Still sucks that i can't export the policies.

**Comment by ThoriumTextile** [comment]
> @jkowalski I have no idea of what voodoo wizardry you pulled off, but as soon as you replied to me it now sees the repo again rofl.
> And anyway i forgot to mention it was a test repo and nothing important was there. Still sucks that i can't export the policies.

Oh i also wanted to ask if it's possible to do system-wide snapshots/backups with the GUI. I tried to but since i'm using the appimage version i can't execute Kopia as root.

**Comment by jkowalski** [comment]
Kopia is for file backup and not full system backup and does not support all fancy filesystem features (currently only files, directories and symlinks are supported). You can totally start `kopia server` as `root` and it will let you backup system files. It actually has the exact same UI available in a browser on `localhost`.

**Comment by ThoriumTextile** [comment]
@jkowalski 
![github](https://user-images.githubusercontent.com/75760340/114425120-0fb97700-9bb9-11eb-8977-5e3953b6cfe1.png)

Since i discovered that the server functionality exists, is there a way that all this could get integrated in a systemd service or maybe even autostarted in my session?
