### ISSUE TITLE
How to run kopiaUI as webserver?

### ISSUE THREAD

**Issue by amunhoz** [kopia/kopia#969]
Is there a way to run kopiaUI as a web server to access it using a browser?  Without using the process to debug the interface ("npm start" inside app directory, but having to compile from source).
The idea is to use the GUI on headless servers.

**Comment by hell0-Wor1d** [comment]
I think it's here : https://kopia.io/docs/repository-server/

**Comment by amunhoz** [comment]
Can't understand exactly what it does.
Does it only create a 'proxy' for storage?
Can i manage remote backup instances? (create backups on remote server managing from a local client)
Or the server interface will provide the GUI  interface on its port?

**Comment by jkowalski** [comment]
Yes, tthat's the target usecase for Kopia server. The server provides UI for current user - same as KopiaUI. 

There are several options there depending on your required security level:

Ranging from:

```
$ kopia server --insecure --without-password
```
(UI will be wide open and no TLS on http://localhost:51515., so you need to use some reverse proxy and provide your own auth)

To:

```
$ kopia server --address 1.2.3.4:56789 --htpasswd-file=passwords.txt  --tls-cert-file file.cer --tls-key-file file.key
```

**Comment by amunhoz** [comment]
Nice! Tested here. Thanks
