### ISSUE TITLE
Second upload of an unchanged directory seems to hash files again

### ISSUE THREAD

**Issue by ntolia** [kopia/kopia#97]
I ran a `snapshot create` on a directory with 10 ~1GB files (AWS S3 repository). The first run took:
```
real	5m38.102s
user	4m49.238s
sys	0m14.174s
```

I then created another snapshot on the same directory and it looks like it scanned all the files again. CPU usage was quite high. Running time:
```
real	0m39.730s
user	3m23.857s
sys	0m2.873s
```

From my understanding of the docs and options for `snapshot create`, I don't think it should be hashing the files.

**Comment by jkowalski** [comment]
I can't repro this:

```
$ time kopia snap create /tmp/10-1g-files
real	0m56.189s
user	2m59.254s
sys	0m6.784s

$ time kopia snap create /tmp/10-1g-files
real	0m0.252s
user	0m0.195s
sys	0m0.051s
```

**Comment by ntolia** [comment]
Based on Slack debugging, this might be a file system specific issue. I am running on Linux (no containers) and on ext4 that was mounted with `relatime`.
