### ISSUE TITLE
Add --no-progress to kopia sync-to

### ISSUE THREAD

**Issue by budachst** [kopia/kopia#982]
I am synching my local repo to a Wasabi S3 bucket daily. I am capturing the output from the cron job and have that one sent as an e-mail to myself. The output of the sync-to command is reallly… lengthy and I am actually not interested in that output.

How about adding the --no-progress option to this command, so it only outputs any errors ans not the whole progress?

**Comment by fhriley** [comment]
I'm not sure that Kopia needs an option for this. It could check if it is running under an interactive terminal. If it is, output the progress. If it is not, just print out a summary of statistics before exiting.

**Comment by YeapGuy** [comment]
Why was this closed? I just ran into this while creating a backup script... it's super annoying that there is no way to suppress the progress logs

**Comment by baryluk** [comment]
Please reopen. This is totally unusable in automation. Also detecting tty is not a good option, as one often wants to with tty interactively, and having a different output might mess other things.

I would be fine with progress, as long as it didn't also use the in-place editing, and the spinner thingy. Instead emit every X seconds (configurable) a new line instead.

The hacky solution now is to do some hacks with `tr` and change `\b` to `\n`, which is ridiculous.
