### ISSUE TITLE
Add support for parallel object storage PUTs

### ISSUE THREAD

**Issue by ntolia** [kopia/kopia#99]
For any relatively high-bandwidth network and a repository that is object storage based (e.g., in AWS S3), `kopia` can be a lot faster with parallel object puts. In my testing, kopia was not limited by either CPU or disk bandwidth and other benchmarking tools could easily get to 5X the throughput (similar object sizes) to the same bucket.

**Comment by jkowalski** [comment]
That's quite doable and relatively easy in `content_manager.go`. I was concerned about limiting memory usage since in-flight blobs would consume RAM, but a simple in-flight upload limit should do.

**Comment by ntolia** [comment]
Good point. For resource-constrained systems, we should likely introduce an additional flag to `snapshot create` that would allow the caller to limit parallelism.

**Comment by ntolia** [comment]
@jkowalski This too is done, right? I would close it but don't know if you anything else planned for this.
