### ISSUE TITLE
Estimates take policies into account

### ISSUE THREAD

**Issue by bbccdd** [kopia/kopia#997]
Currently (v0.8.2) when estimating, policies are not taken into account while this would be highly useful feature.

Especially when initially setting up backups - while playing with ignore rules - it would be very handy and cost-saving to see if the ignore rules would produce the desired effect before backing up.

In other words:
As a user who is setting up backups,
I would like to see estimates based on applicable policies,
So that I can save cost and see that ignore rules are effective.

**Comment by stpr-dev** [comment]
I think this is related to #1001 , it is a bug and it should actually take policies into account. The issue appears to be identified, and will likely be fixed soon.

**Comment by bbccdd** [comment]
Indeed! This ticket is fixed by #1005 .
