### ISSUE TITLE
GUI shows 'estimate' besides 'Snapshot now' button.

### ISSUE THREAD

**Issue by bbccdd** [kopia/kopia#998]
As a user testing ignore rules
I would like to see an '**estimate**' button next to the 'Snapshot now' button
So that I can see if ignore rules achieve the desired effect.

![image](https://user-images.githubusercontent.com/29344993/115353206-8ad1ed00-a1b8-11eb-8210-674f3b06e30f.png)

Preferably also taking applicable policies into account as per #997

**Comment by jkowalski** [comment]
`New Snapshot` button has `Estimate` option on separate page and you're not limited to pre-existing snapshots. I don't think this button will add much value at this level.

**Comment by bbccdd** [comment]
OK. Indeed, since the `estimate` feature works again including policies, one can just manually enter the path and estimate using the `new snapshot` button. Thanks for the quick fix on the estimation (super useful feature!).
